CREATE PROCEDURE [dbo].[HOME_MODIFY_HOJA_RUTA]
(@IPKEYJOB	AS VARCHAR(100),
 @OCODE		AS VARCHAR(2) OUTPUT,
 @OMENSAJE	AS VARCHAR(400) OUTPUT)
AS
 
DECLARE	@VID_AGENDA			VARCHAR(50),
		@VSERVICIO			VARCHAR(50),
		@VID_HOJA			VARCHAR(50),
		@VCLIENTE			VARCHAR(300),
		@VFECHA				DATETIME,
		@VNOMBRE			VARCHAR(100),
		@VCONSULTOR			VARCHAR(50),
		@VCONSULTOR_ACOMP	VARCHAR(50),
		@VVISITA			DATETIME,
		@VOBSERVACIONES		VARCHAR(400),
		@VFECHA_CIERRE		DATETIME,
		@VERROR				VARCHAR(50),
		@lstCadena			varchar(MAX), 
		@lstDato			varchar(4000), 
		@lnuPosComa			int , 
		@VID				VARCHAR(100), 
		@VALOR				VARCHAR(4000),
		@VID_PROYECTO_DOCUM	INT,
		@VINDICADOR			VARCHAR(50),
		@VPROYECTO			VARCHAR(50),
		@VTAB_SERV			VARCHAR(50)
 
 
BEGIN
 
	SELECT	@VID_AGENDA = ISNULL(AGENDA_ID,''),
			@VTAB_SERV = ISNULL(TAB_SERV,''),
			@VPROYECTO = ISNULL(PROYECTO_ID,''),
			/*@VID_HOJA  = ISNULL(HOJA_RUTA_ID,''),
			@VFECHA = ISNULL(FECHA_HR,''),
			@VCONSULTOR = ISNULL(CONSULTOR_HR,''),
			@VVISITA = NULLIF(ISNULL(VISITA_MES_HR,''),''),
			@VCONSULTOR_ACOMP = ISNULL(CONSULTOR_ACOMP_HR,''),
			@VOBSERVACIONES = ISNULL(OBSERVACION_HR,''),
			@VFECHA_CIERRE = NULLIF(ISNULL(FECHA_CIERRE_HR,''),''),
			@VNOMBRE = ISNULL(NOMBRE_HR,''),*/
			@VERROR = ISNULL(ERROR,''),
			@lstCadena = ISNULL(BUFFER,''),
			@VOBSERVACIONES = ISNULL(OBSERVACION_HR,'')
	FROM	XAGENDA
	WHERE	PAR_KEY = @IPKEYJOB
 
	IF (@VTAB_SERV = '9') BEGIN --anexo minuta de gestion
 
		--RECUPERO EL ID DE DOCUMENTACION DE LA MINUTA DE GESTION--
		SELECT	@VID_PROYECTO_DOCUM = ISNULL(TAB_AGENDA,'')
		FROM	XAGENDA
		WHERE	PAR_KEY = @IPKEYJOB
 
		--VUELVO A LA GRILLA CON EXPORTA-- ANEXO MINUTA DE GESTION
		SET @OCODE = '1'
	END
	
	IF (@VTAB_SERV = '8') BEGIN --minuta de gestion
 
		--RECUPERO EL ID DE DOCUMENTACION DE LA MINUTA DE GESTION--
		SELECT	@VID_PROYECTO_DOCUM = ID_PROYECTO_DOCUM
		FROM	LK_PROYECTO_DOCUM
		WHERE	ID_PROYECTO = @VPROYECTO
		AND		TIPO = 'MG'
 
		--VUELVO A LA GRILLA CON EXPORTA-- MINUTA DE GESTION
		SET @OCODE = '1'
 
	END ELSE BEGIN --HOJA DE RUTA--
 
		SELECT	@VSERVICIO = ISNULL(ID_SERVICIO,'')
		FROM	LK_AGENDA
		WHERE	ID_AGENDA = @VID_AGENDA
 
		SELECT	@VID_PROYECTO_DOCUM = ID_PROYECTO_DOCUM
		FROM	LK_PROYECTO_DOCUM
		WHERE	ID_AGENDA = @VID_AGENDA
		AND		ID_DOCUMENTACION = CASE WHEN @VSERVICIO = '1' THEN '7'
										WHEN @VSERVICIO = '2' THEN '5'
										WHEN @VSERVICIO = '3' THEN '6'
									END
 
		--VUELVO A LA TABLA SOLA-- HOJA DE RUTA
		SET @OCODE = '0'
	END
	/*
	IF @VERROR = '' BEGIN
		SET @OCODE = '0'
		SET @OMENSAJE = ''
 
	END ELSE BEGIN*/
 
		/*IF (@VFECHA = '') BEGIN
			SET @OCODE = '1'
			SET @OMENSAJE = '<html>
							<body>
							  <div class="w3-panel w3-pale-red" style="height: 20px;">
									<font style="font-family:Tahoma, Arial, Helvetica, sans-serif;font-size:12px;color:#641E16"><b>Debe completar el Campo Fecha Inicio</b></font>
							  </div>
							</div>
							</body>
							</html>'
			
			UPDATE	XAGENDA
			SET		ERROR = 'SI'
			WHERE	PAR_KEY = @IPKEYJOB
			RETURN
		END*/
 
		IF (@lstCadena <> '') BEGIN
			WHILE LEN(@lstCadena) > 0
			BEGIN 
				SET @lnuPosComa = CHARINDEX('|', @lstCadena) -- Busca el caracter a separador
				IF (@lnuPosComa = 0) BEGIN 
					SET @lstDato = @lstCadena
					SET @lstCadena = '' 
				END ELSE BEGIN
					SET @lstDato = SUBSTRING(@lstCadena, 1, @lnuPosComa - 1)
					SET @VID = SUBSTRING(@lstDato,1,CHARINDEX('=', @lstDato)-1)
					SET @VALOR = ISNULL(SUBSTRING(@lstDato,CHARINDEX('=', @lstDato)+1,LEN(@lstDato)),'')
 
					IF (@VID = 'L')  BEGIN
					
						UPDATE	LK_PROYECTO_DOCUM_DET
						SET		VALOR_DOC_DET = @VALOR
						WHERE	ID_PROYECTO_DOCUM = @VID_PROYECTO_DOCUM
						AND		GRUPO_DOC_DET = 'LOGISTICO'
						AND		ISNULL(VALOR_DOC_DET,'') = ''
					
					END ELSE IF (@VID = 'T')  BEGIN
						UPDATE	LK_PROYECTO_DOCUM_DET
						SET		VALOR_DOC_DET = @VALOR
						WHERE	ID_PROYECTO_DOCUM = @VID_PROYECTO_DOCUM
						AND		GRUPO_DOC_DET = 'TECNICO'
						AND		ISNULL(VALOR_DOC_DET,'') = ''
					
					END ELSE IF (@VID = 'A')  BEGIN
						UPDATE	LK_PROYECTO_DOCUM_DET
						SET		VALOR_DOC_DET = @VALOR
						WHERE	ID_PROYECTO_DOCUM = @VID_PROYECTO_DOCUM
						AND		GRUPO_DOC_DET = 'ADMINISTRACION'
						AND		ISNULL(VALOR_DOC_DET,'') = ''
					
					END ELSE BEGIN
 
						UPDATE	LK_PROYECTO_DOCUM_DET
						SET		VALOR_DOC_DET = @VALOR
						WHERE	ID_PROYECTO_DOCUM_DET = @VID
					END
 
					SET @lstCadena = SUBSTRING(@lstCadena, @lnuPosComa + 1, LEN(@lstCadena))
				END
			
			END
		END
		
		--IF (@VTAB_SERV = '8') BEGIN --minuta de gestion
		IF (@VID_AGENDA <> '') BEGIN --HOJA DE RUTA--
 
			UPDATE	LK_PROYECTO_DOCUM 
			SET		OBSERVACIONES = @VOBSERVACIONES
			WHERE	ID_AGENDA = @VID_AGENDA
 
			SET @VINDICADOR = [dbo].[FN_GET_STATUS_AGENDA] (@VID_AGENDA)
 
			UPDATE	LK_AGENDA 
			SET		INDICADOR_HR = @VINDICADOR
			WHERE	ID_AGENDA = @VID_AGENDA
		END
	--END
	/*
	IF (@OCODE = '0') BEGIN
		UPDATE	XAGENDA
		SET		ERROR = 'NO'
		WHERE	PAR_KEY = @IPKEYJOB
	END*/
 
END
