CREATE PROCEDURE [dbo].[HOME_INICIA_HOJA_RUTA]
(@IPKEYJOB	AS VARCHAR(100),
 @OSERVICIO	AS VARCHAR(100) OUTPUT,
 @OLABEL1	AS VARCHAR(100) OUTPUT,
 @OLABEL2	AS VARCHAR(100) OUTPUT,
 @OLABEL3	AS VARCHAR(100) OUTPUT,
 @OLABEL4	AS VARCHAR(100) OUTPUT)
AS
 
DECLARE	@VID		VARCHAR(50),
		@VSERVICIO	VARCHAR(50)
 
BEGIN
 
	SELECT	@VID = ISNULL(PROYECTO_SERV_ID,'')
	FROM	XAGENDA
	WHERE	PAR_KEY = @IPKEYJOB
	
	SELECT	@VSERVICIO  = ID_TIPO_SERVICIO
	FROM	LK_PROYECTO_SERVICIO
	WHERE	ID_PROYECTO_SERVICIO = @VID
 
	SELECT	@OSERVICIO = DESC_TIPO_SERVICIO
	FROM	LK_TIPO_SERVICIOS
	WHERE	ID_TIPO_SERVICIO = @VSERVICIO
 
	UPDATE	XAGENDA
	SET		--HOJA_RUTA_ID = NULL,
			FECHA_HR = NULL,
			CONSULTOR_HR = NULL,
			VISITA_MES_HR = NULL,
			CONSULTOR_ACOMP_HR = NULL,
			OBSERVACION_HR = NULL,
			FECHA_CIERRE_HR = NULL,
			NOMBRE_HR = NULL
	WHERE	PAR_KEY = @IPKEYJOB
 
	SET @OSERVICIO = 'SERVICIO: ' + UPPER(@OSERVICIO)
 
	--SELECT * FROM LK_TIPO_SERVICIOS
	/*	1	Consultoria
		2	Auditoria
		3	Capacitacion*/
	IF (@VSERVICIO = '1') BEGIN
		SET @OLABEL1 = 'Visita Mes:'
		SET @OLABEL2 = 'Nro/Nombre Int.:'
		SET @OLABEL3 = 'Consultor:'
		SET @OLABEL4 = 'Consultor Acomp.:'
	END
 
	IF (@VSERVICIO = '2') BEGIN
		SET @OLABEL1 = 'F. Entrega Inf.:'
		SET @OLABEL2 = 'Fechas:'
		SET @OLABEL3 = 'Auditor:'
		SET @OLABEL4 = 'Auditor Acomp.:'
	END
 
	IF (@VSERVICIO = '3') BEGIN
		SET @OLABEL1 = 'Fechas:'
		SET @OLABEL2 = 'Capacitacion (Tipo,Lugar):'
		SET @OLABEL3 = 'Instructor:'
		SET @OLABEL4 = 'Instructor Acomp.:'
	END
END
 
