CREATE PROCEDURE PA_SYS_NEXT_CALL (@PS_UNIT_CODE AS VARCHAR(100), @PS_USER_ID AS VARCHAR(30), @PS_PKEY_CAMPAIGN AS VARCHAR(20), @PS_FECHA_HORA_INICIO_PROG AS VARCHAR(60), @PS_FECHA_HORA_FINAL_PROG AS VARCHAR(60), @PN_CANT_REG AS NUMERIC(15), @PS_NO_PROG AS VARCHAR(1), @PS_SALIDA AS VARCHAR(440) OUTPUT) AS
 
-- =========================================================================================================================
-- AUTOR: TITO - ENGAGE SOFTWARE COMPANY
-- FECHA DE CREACIÓN: 05/12/2007
-- EDITOR: TITO - ENGAGE SOFTWARE COMPANY
-- FECHA DE EDICIÓN: 23/02/2011
-- TABLAS LEÍDAS: CUSTOMER, ATTENDED_CUSTOMER, PHYSICAL_LIST, JOB_TYPE, PHYSICAL_JOB, CALL_TYPE
-- TABLAS MODIFICADAS:
-- DESCRIPCIÓN: PROCEDIMIENTO QUE DEVUELVE EL PRÓXIMO TRÁMITE DISPONIBLE PARA TRABAJAR EN EL AGENTE WEB
-- CONSIDERACIONES:
-- 1. @PS_PKEY_CAMPAIGN SE INFORMA CON UNA CLAVE O CON NULL. EN CASO DE QUE SEA NULL, SE OPERA DE FORMA DIFERENTE
-- 2. @PS_FECHA_HORA_INICIO_PROG ES DE TIPO VARCHAR(30) Y CONTIENE FECHA Y HORA: '2007-12-05 11:10:08 AM'
-- 3. @PS_FECHA_HORA_FINAL_PROG ES DE TIPO VARCHAR(30) Y CONTIENE FECHA Y HORA: '2007-12-05 11:10:08 AM'
-- 4. @PN_CANT_REG ES DE TIPO NUMERIC(15) Y CONTIENE LA CANTIDAD DE REGISTROS A DEVOLVER. PREDETERMINADO = 5
-- 5. @PS_NO_PROG ES DE TIPO VARCHAR(1) E INDICA SI SE CORRE EL QUERY DE PROGRAMADOS ('N') O EL DE NO PROGRAMADOS ('S')
-- 6. DEVUELVE UN PARÁMETRO DE SALIDA, @PS_SALIDA, QUE INDICA SI EL PROCEDIMIENTO TERMINÓ BIEN O MAL
-- =========================================================================================================================
 
SET NOCOUNT ON;
SET XACT_ABORT ON;
 
-- DECLARACIÓN E INICIALIZACIÓN DE VARIABLES DE ERROR Y AUXILIARES.
DECLARE @LNERRORNUM AS INTEGER,
	@LNSEVERITY AS SMALLINT,
	@LNFILAS_AFEC AS INTEGER,
	@LDINICIO_OPE AS DATETIME,
	@LNDURACION AS INTEGER,
	@LSOPERA AS VARCHAR(30),
	@LSPROC AS VARCHAR(30),
	@LSTABLA AS VARCHAR(30),
	@LSERRORLOG AS VARCHAR(440),
	@LSERRORDESC AS VARCHAR(440),
	@LSSQL_CMD AS VARCHAR(4000)
;
SELECT 	@LNERRORNUM = 0,
	@LNSEVERITY = 16,
	@LNFILAS_AFEC = 0,
	@LDINICIO_OPE = GETDATE(),
	@LNDURACION = 0,
	@LSOPERA = 'EXECUTE',
	@LSPROC = OBJECT_NAME(@@PROCID),
	@LSTABLA = 'NINGUNA',
	@LSERRORLOG = @@SERVERNAME + '.' + DB_NAME() + '.' + USER_NAME() + '.' + OBJECT_NAME(@@PROCID) + ' - ',
	@LSERRORDESC = NULL,
	@LSSQL_CMD = NULL
;
DECLARE	@LS_FECHA_HORA_DESDE AS VARCHAR(60),
	@LS_FECHA_HORA_HASTA AS VARCHAR(60),
	@LS_UNIT_CODE AS VARCHAR(100),
	@LS_USER_ID AS VARCHAR(30),
	@LS_PKEY_CAMPAIGN AS VARCHAR(20),
	@LN_CANT_REG AS NUMERIC(15),
	@LS_NO_PROG AS VARCHAR(1)
;
-- DECLARA LAS VARIABLES Y ASIGNA VALORES PREDETERMINADOS.
SELECT	@LS_FECHA_HORA_DESDE = UPPER(NULLIF(RTRIM(LTRIM(@PS_FECHA_HORA_INICIO_PROG)), '')), -- DEVUELVE LA FECHA CON LA HORA ('2001-01-01 00:00:00').
	@LS_FECHA_HORA_HASTA = UPPER(NULLIF(RTRIM(LTRIM(@PS_FECHA_HORA_FINAL_PROG)), '')), -- DEVUELVE LA FECHA CON LA HORA ('2001-01-01 00:00:00').
	@LS_UNIT_CODE = ISNULL(@PS_UNIT_CODE, ' '),
	@LS_USER_ID = ISNULL(@PS_USER_ID, ' '),
	@LS_PKEY_CAMPAIGN = NULLIF(RTRIM(LTRIM(@PS_PKEY_CAMPAIGN)), ''),
	@LN_CANT_REG = ISNULL(@PN_CANT_REG, 5),
	@LS_NO_PROG = ISNULL(@PS_NO_PROG, 'N')
;
 
-- DECLARO LA TRANSACCIÓN.
BEGIN TRANSACTION
 
IF (@LS_NO_PROG = 'N') BEGIN
	-- EJECUTA EL QUERY DE TRÁMITES PROGRAMADOS SEAN O NO DE CAMPAÑAS.
	-- LAS CONDICIONES DEL WHERE DE ESTE QUERY PUEDEN SER CAMBIADAS PARA ADECUARSE A SU IMPLEMENTACIÓN.
	SET @LSSQL_CMD = 'SELECT	TOP ' + CONVERT(VARCHAR, @LN_CANT_REG) + CHAR(13) + CHAR(10);
	SET @LSSQL_CMD = @LSSQL_CMD + 'ATTENDED_CUSTOMER.PKEY_JOB,' + CHAR(13) + CHAR(10);
	SET @LSSQL_CMD = @LSSQL_CMD + 'CUSTOMER.CUST_PRIMARY_ID,' + CHAR(13) + CHAR(10);
	SET @LSSQL_CMD = @LSSQL_CMD + 'ATTENDED_CUSTOMER.CALL_TYPE_CODE,' + CHAR(13) + CHAR(10);
	SET @LSSQL_CMD = @LSSQL_CMD + 'CUSTOMER.CUST_TYPE_CODE,' + CHAR(13) + CHAR(10);
	SET @LSSQL_CMD = @LSSQL_CMD + 'ATTENDED_CUSTOMER.PROGRAMMED_DATE_TIME,' + CHAR(13) + CHAR(10);
	SET @LSSQL_CMD = @LSSQL_CMD + 'ATTENDED_CUSTOMER.PKEY AS ATT_PKEY,' + CHAR(13) + CHAR(10);
	SET @LSSQL_CMD = @LSSQL_CMD + 'CUSTOMER.PKEY,' + CHAR(13) + CHAR(10);
	SET @LSSQL_CMD = @LSSQL_CMD + 'PHYSICAL_JOB.JOB_TYPE_CODE,' + CHAR(13) + CHAR(10);
	SET @LSSQL_CMD = @LSSQL_CMD + 'ISNULL(NULLIF(RTRIM(LTRIM(ATTENDED_CUSTOMER.MEDIA_ID1)), ''''), NULLIF(RTRIM(LTRIM(PHYSICAL_JOB.MEDIA_ID1)), '''')) AS MEDIA_ID1' + CHAR(13) + CHAR(10);
	SET @LSSQL_CMD = @LSSQL_CMD + 'FROM	CUSTOMER,' + CHAR(13) + CHAR(10);
	SET @LSSQL_CMD = @LSSQL_CMD + 'ATTENDED_CUSTOMER,' + CHAR(13) + CHAR(10);
	SET @LSSQL_CMD = @LSSQL_CMD + 'JOB_TYPE,' + CHAR(13) + CHAR(10);
	SET @LSSQL_CMD = @LSSQL_CMD + 'PHYSICAL_JOB' + CHAR(13) + CHAR(10);
	SET @LSSQL_CMD = @LSSQL_CMD + 'WHERE	(JOB_TYPE.JOB_TYPE_CODE = PHYSICAL_JOB.JOB_TYPE_CODE)' + CHAR(13) + CHAR(10);
	SET @LSSQL_CMD = @LSSQL_CMD + 'AND (PHYSICAL_JOB.PKEY_CUSTOMER = CUSTOMER.PKEY)' + CHAR(13) + CHAR(10);
	SET @LSSQL_CMD = @LSSQL_CMD + 'AND (PHYSICAL_JOB.PKEY = ATTENDED_CUSTOMER.PKEY_JOB)' + CHAR(13) + CHAR(10);
	SET @LSSQL_CMD = @LSSQL_CMD + 'AND (JOB_TYPE.JOB_READY_IDR = ''1'')' + CHAR(13) + CHAR(10);
	SET @LSSQL_CMD = @LSSQL_CMD + 'AND (PHYSICAL_JOB.ATT_GROUP_CODE = ''' + @LS_UNIT_CODE + ''')' + CHAR(13) + CHAR(10);
	SET @LSSQL_CMD = @LSSQL_CMD + 'AND (PHYSICAL_JOB.USER_ID = ''' + @LS_USER_ID + ''' OR PHYSICAL_JOB.USER_ID IS NULL)' + CHAR(13) + CHAR(10);
	SET @LSSQL_CMD = @LSSQL_CMD + 'AND (PHYSICAL_JOB.JOB_STATE_CODE = ''OPENED'' OR PHYSICAL_JOB.JOB_STATE_CODE = ''NOTWORKED'')' + CHAR(13) + CHAR(10);
	SET @LSSQL_CMD = @LSSQL_CMD + 'AND (ATTENDED_CUSTOMER.ATT_STATE_CODE = ''Abierto'' OR ATTENDED_CUSTOMER.ATT_STATE_CODE = ''NOTWORKED'')' + CHAR(13) + CHAR(10);
	SET @LSSQL_CMD = @LSSQL_CMD + 'AND (PHYSICAL_JOB.PROGRAMMED_IDR = ''SI'' AND PHYSICAL_JOB.PROGRAMMED_DATE_TIME >= ' + @LS_FECHA_HORA_DESDE + ' AND PHYSICAL_JOB.PROGRAMMED_DATE_TIME <= ' + @LS_FECHA_HORA_HASTA + ' AND PHYSICAL_JOB.PROGRAMMED_DATE_TIME <= GETDATE())' + CHAR(13) + CHAR(10);
	SET @LSSQL_CMD = @LSSQL_CMD + 'AND (ATTENDED_CUSTOMER.PKEY_CAMPAIGN = ''NO APLICA''' + CHAR(13) + CHAR(10);
	SET @LSSQL_CMD = @LSSQL_CMD + 'OR EXISTS (' + CHAR(13) + CHAR(10);
	SET @LSSQL_CMD = @LSSQL_CMD + 'SELECT	1' + CHAR(13) + CHAR(10);
	SET @LSSQL_CMD = @LSSQL_CMD + 'FROM	PHYSICAL_LIST' + CHAR(13) + CHAR(10);
	SET @LSSQL_CMD = @LSSQL_CMD + 'WHERE	(PHYSICAL_LIST.PKEY = ATTENDED_CUSTOMER.PKEY_CAMPAIGN)' + CHAR(13) + CHAR(10);
	SET @LSSQL_CMD = @LSSQL_CMD + 'AND (PHYSICAL_LIST.STATE_CODE = ''INICIADA'')' + CHAR(13) + CHAR(10);
	SET @LSSQL_CMD = @LSSQL_CMD + 'AND (PHYSICAL_LIST.MEDIA_TYPE = ''AGENT'')' + CHAR(13) + CHAR(10);
	SET @LSSQL_CMD = @LSSQL_CMD + ')' + CHAR(13) + CHAR(10);
	SET @LSSQL_CMD = @LSSQL_CMD + ')' + CHAR(13) + CHAR(10);
	SET @LSSQL_CMD = @LSSQL_CMD + 'ORDER BY PHYSICAL_JOB.JOB_PRIORITY ASC,' + CHAR(13) + CHAR(10);
	SET @LSSQL_CMD = @LSSQL_CMD + 'PHYSICAL_JOB.PROGRAMMED_DATE_TIME ASC' + CHAR(13) + CHAR(10);
 
	-- EJECUTA LA CONSULTA QUE DEVUELVE EL CONJUNTO DE DATOS.
	-- PRINT @LSSQL_CMD;
	EXECUTE (@LSSQL_CMD);
 
	SELECT @LSOPERA = 'SELECT', @LSTABLA = 'ATTENDED_CUSTOMER', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
END
ELSE BEGIN
	-- EJECUTA EL QUERY DE NO PROGRAMADOS, SEAN O NO DE CAMPAÑAS, SÓLO SI NO HUBO RESULTADOS DEL QUERY DE PROGRAMADOS.
	-- LAS CONDICIONES DEL WHERE DE ESTE QUERY PUEDEN SER CAMBIADAS PARA ADECUARSE A SU IMPLEMENTACIÓN.
	SET @LSSQL_CMD = 'SELECT	TOP ' + CONVERT(VARCHAR, @LN_CANT_REG) + CHAR(13) + CHAR(10);
	SET @LSSQL_CMD = @LSSQL_CMD + 'ATTENDED_CUSTOMER.PKEY_JOB,' + CHAR(13) + CHAR(10);
	SET @LSSQL_CMD = @LSSQL_CMD + 'CUSTOMER.CUST_PRIMARY_ID,' + CHAR(13) + CHAR(10);
	SET @LSSQL_CMD = @LSSQL_CMD + 'ATTENDED_CUSTOMER.CALL_TYPE_CODE,' + CHAR(13) + CHAR(10);
	SET @LSSQL_CMD = @LSSQL_CMD + 'CUSTOMER.CUST_TYPE_CODE,' + CHAR(13) + CHAR(10);
	SET @LSSQL_CMD = @LSSQL_CMD + 'ATTENDED_CUSTOMER.PROGRAMMED_DATE_TIME,' + CHAR(13) + CHAR(10);
	SET @LSSQL_CMD = @LSSQL_CMD + 'ATTENDED_CUSTOMER.PKEY AS ATT_PKEY,' + CHAR(13) + CHAR(10);
	SET @LSSQL_CMD = @LSSQL_CMD + 'CUSTOMER.PKEY,' + CHAR(13) + CHAR(10);
	SET @LSSQL_CMD = @LSSQL_CMD + 'PHYSICAL_JOB.JOB_TYPE_CODE,' + CHAR(13) + CHAR(10);
	SET @LSSQL_CMD = @LSSQL_CMD + 'ISNULL(NULLIF(RTRIM(LTRIM(ATTENDED_CUSTOMER.MEDIA_ID1)), ''''), NULLIF(RTRIM(LTRIM(PHYSICAL_JOB.MEDIA_ID1)), '''')) AS MEDIA_ID1' + CHAR(13) + CHAR(10);
	SET @LSSQL_CMD = @LSSQL_CMD + 'FROM	CUSTOMER,' + CHAR(13) + CHAR(10);
	SET @LSSQL_CMD = @LSSQL_CMD + 'ATTENDED_CUSTOMER,' + CHAR(13) + CHAR(10);
	SET @LSSQL_CMD = @LSSQL_CMD + 'JOB_TYPE,' + CHAR(13) + CHAR(10);
	SET @LSSQL_CMD = @LSSQL_CMD + 'PHYSICAL_JOB' + CHAR(13) + CHAR(10);
	SET @LSSQL_CMD = @LSSQL_CMD + ', CALL_TYPE' + CHAR(13) + CHAR(10);
	SET @LSSQL_CMD = @LSSQL_CMD + 'WHERE	(JOB_TYPE.JOB_TYPE_CODE = PHYSICAL_JOB.JOB_TYPE_CODE)' + CHAR(13) + CHAR(10);
	SET @LSSQL_CMD = @LSSQL_CMD + 'AND (PHYSICAL_JOB.PKEY_CUSTOMER = CUSTOMER.PKEY)' + CHAR(13) + CHAR(10);
	SET @LSSQL_CMD = @LSSQL_CMD + 'AND (PHYSICAL_JOB.PKEY = ATTENDED_CUSTOMER.PKEY_JOB)' + CHAR(13) + CHAR(10);
	SET @LSSQL_CMD = @LSSQL_CMD + 'AND (CALL_TYPE.CALL_TYPE_CODE = ATTENDED_CUSTOMER.CALL_TYPE_CODE)' + CHAR(13) + CHAR(10);
	SET @LSSQL_CMD = @LSSQL_CMD + 'AND (JOB_TYPE.JOB_READY_IDR = ''1'')' + CHAR(13) + CHAR(10);
	SET @LSSQL_CMD = @LSSQL_CMD + 'AND (PHYSICAL_JOB.ATT_GROUP_CODE = ''' + @LS_UNIT_CODE + ''')' + CHAR(13) + CHAR(10);
	SET @LSSQL_CMD = @LSSQL_CMD + 'AND (PHYSICAL_JOB.USER_ID = ''' + @LS_USER_ID + ''' OR PHYSICAL_JOB.USER_ID IS NULL)' + CHAR(13) + CHAR(10);
	SET @LSSQL_CMD = @LSSQL_CMD + 'AND (PHYSICAL_JOB.JOB_STATE_CODE = ''OPENED'' OR PHYSICAL_JOB.JOB_STATE_CODE = ''NOTWORKED'')' + CHAR(13) + CHAR(10);
	SET @LSSQL_CMD = @LSSQL_CMD + 'AND (ATTENDED_CUSTOMER.ATT_STATE_CODE = ''Abierto'' OR ATTENDED_CUSTOMER.ATT_STATE_CODE = ''NOTWORKED'')' + CHAR(13) + CHAR(10);
	SET @LSSQL_CMD = @LSSQL_CMD + 'AND (PHYSICAL_JOB.PROGRAMMED_IDR IN (''NO'', ''AGENDADO''))' + CHAR(13) + CHAR(10);
	SET @LSSQL_CMD = @LSSQL_CMD + 'AND EXISTS (' + CHAR(13) + CHAR(10);
	SET @LSSQL_CMD = @LSSQL_CMD + 'SELECT	1' + CHAR(13) + CHAR(10);
	SET @LSSQL_CMD = @LSSQL_CMD + 'FROM	PHYSICAL_LIST' + CHAR(13) + CHAR(10);
	SET @LSSQL_CMD = @LSSQL_CMD + 'WHERE	(PHYSICAL_LIST.PKEY = ATTENDED_CUSTOMER.PKEY_CAMPAIGN)' + CHAR(13) + CHAR(10);
	IF (@LS_PKEY_CAMPAIGN IS NOT NULL) BEGIN
		-- AGREGA EL FILTRO DE LA LISTA INDICADA.
		SET @LSSQL_CMD = @LSSQL_CMD + 'AND (PHYSICAL_LIST.PKEY = ''' + @LS_PKEY_CAMPAIGN + ''')' + CHAR(13) + CHAR(10);
	END;
	SET @LSSQL_CMD = @LSSQL_CMD + 'AND (PHYSICAL_LIST.STATE_CODE = ''INICIADA'')' + CHAR(13) + CHAR(10);
	SET @LSSQL_CMD = @LSSQL_CMD + 'AND (PHYSICAL_LIST.MEDIA_TYPE = ''AGENT'')' + CHAR(13) + CHAR(10);
	SET @LSSQL_CMD = @LSSQL_CMD + ')' + CHAR(13) + CHAR(10);
	SET @LSSQL_CMD = @LSSQL_CMD + 'AND (CALL_TYPE.IN_OUT_IDR <> ''INBOUND'')' + CHAR(13) + CHAR(10);
	SET @LSSQL_CMD = @LSSQL_CMD + 'ORDER BY PHYSICAL_JOB.ORDERBY ASC' + CHAR(13) + CHAR(10);
 
	-- EJECUTA LA CONSULTA.
	-- PRINT @LSSQL_CMD;
	EXECUTE (@LSSQL_CMD);
 
	SELECT @LSOPERA = 'SELECT', @LSTABLA = 'ATTENDED_CUSTOMER', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
END;
 
-- DEVUELVE 'OK' EN EL PARÁMETRO DE SALIDA.
SET @PS_SALIDA = 'OK';
 
FALLO:
-- REGISTRO DE SUCESOS Y CONTROL DE FIN DE PROCEDIMIENTO. CONCLUYE LA TRANSACCIÓN SI TODO FUE EXITOSO.
SELECT @LNDURACION = DATEDIFF(SECOND, @LDINICIO_OPE, GETDATE()), @LNSEVERITY = ISNULL(EM.SEVERITY, 16), @LSERRORDESC = 'ERROR ' + CONVERT(VARCHAR, ISNULL(EM.ERROR, 0)) + ' - ' + ISNULL(EM.DESCRIPTION, ' ') FROM MASTER.DBO.SYSMESSAGES EM WHERE (EM.ERROR = @LNERRORNUM);
IF (@LNERRORNUM <> 0) BEGIN
	-- NOTIFICACIÓN EN EL REGISTRO DE SQL SERVER.
	SET @LSERRORLOG = @LSERRORLOG + CASE WHEN (ISNULL(CHARINDEX('%', @LSERRORDESC), 0) > 0) THEN RTRIM(LEFT(@LSERRORDESC, 11)) ELSE @LSERRORDESC END;
	-- DEVUELVE EL ERROR EN EL PARÁMETRO DE SALIDA.
	SET @PS_SALIDA = SUBSTRING(@LSERRORDESC, 1, 440);
	-- DESHACE LA TRANSACCIÓN COMPLETA SI LA OPERACIÓN FALLÓ.
	IF (@@TRANCOUNT > 0) ROLLBACK TRANSACTION;
	EXECUTE @LNERRORNUM = PA_SYS_REGISTRO_SUCESOS_INSERT @PSPROCEDIMIENTO_1 = @LSPROC, @PSTABLA_2 = @LSTABLA, @PNFILAS_AFECTADAS_3 = @LNFILAS_AFEC, @PSOPERACION_4 = @LSOPERA, @PNDURACION_5 = @LNDURACION, @PSRESULTADO_6 = @LSERRORDESC, @PSSQL_CMD_7 = @LSERRORDESC;
	-- RAISERROR(@LSERRORLOG, @LNSEVERITY, -1) WITH NOWAIT;
END
ELSE BEGIN
-- 	EXECUTE @LNERRORNUM = PA_SYS_REGISTRO_SUCESOS_INSERT @PSPROCEDIMIENTO_1 = @LSPROC, @PSTABLA_2 = @LSTABLA, @PNFILAS_AFECTADAS_3 = @LNFILAS_AFEC, @PSOPERACION_4 = @LSOPERA, @PNDURACION_5 = @LNDURACION, @PSRESULTADO_6 = @LSERRORDESC, @PSSQL_CMD_7 = @LSERRORDESC;
	IF (@@TRANCOUNT > 0) COMMIT TRANSACTION;
END;
RETURN;
