CREATE PROCEDURE [dbo].[HOME_ADD_MINUTA_VISITA]
(@IPKEYJOB	AS VARCHAR(100),
 @IAGENTE	AS VARCHAR(100),
 @OCODE		AS VARCHAR(2) OUTPUT,
 @OMENSAJE	AS VARCHAR(400) OUTPUT)
AS
 
DECLARE	@VPROYECTO			VARCHAR(50),
		@VPROYECTO_SERV		VARCHAR(50),
		@VSERVICIO			VARCHAR(50),
		@VFECHA				DATETIME,
		@VOBSERVACION		VARCHAR(400),
		@VID_DOC			VARCHAR(50),
		@VID_PROYECTO_DOCUM	VARCHAR(50),
		@VDESC_DOC_DET		VARCHAR(400), 
		@VGRUPO_DOC_DET		VARCHAR(50),
		@VCANT				INT,
		@VERROR				VARCHAR(50),
		@VAGENDA_ID			VARCHAR(50),
		@VTIPO				VARCHAR(50),
		@VADJUNTO	VARCHAR(100)	
 
BEGIN	
 
	SET @OCODE = '0'
	SET @OMENSAJE = ''
 
	SELECT	@VAGENDA_ID = ISNULL(AGENDA_ID,''),
			@VFECHA = ISNULL(CONS_FECHA_MC,''),
			@VOBSERVACION = ISNULL(CONS_OBSERV_MC,''),
			@VERROR = ISNULL(ERROR,''),
			@VTIPO = ISNULL(TIPO_SELEC,''),
			@VPROYECTO_SERV = ISNULL(PROYECTO_SERV_ID,'')
	FROM	XAGENDA
	WHERE	PAR_KEY = @IPKEYJOB
	
	SELECT	@VPROYECTO  = ID_PROYECTO,
			@VSERVICIO  = ID_SERVICIO
	FROM	LK_AGENDA
	WHERE	ID_AGENDA = @VAGENDA_ID
 
	SELECT	@VADJUNTO = ISNULL(PKEY,'')
	FROM	PHYSICAL_ATTACHED_DOCUMENT
	WHERE	PAR_KEY = @IPKEYJOB
 
	IF @VERROR = '' BEGIN
		SET @OCODE = '0'
		SET @OMENSAJE = ''
 
	END ELSE BEGIN
 
		IF (@VFECHA = '') BEGIN
			SET @OCODE = '1'
			SET @OMENSAJE = '<html>
							<body>
							  <div class="w3-panel w3-pale-red" style="height: 20px;">
									<font style="font-family:Tahoma, Arial, Helvetica, sans-serif;font-size:12px;color:#641E16"><b>Debe completar el Campo Fecha</b></font>
							  </div>
							</div>
							</body>
							</html>'
			
			UPDATE	XAGENDA
			SET		ERROR = 'SI'
			WHERE	PAR_KEY = @IPKEYJOB
			RETURN
		END
	
		BEGIN
		
			INSERT INTO LK_PROYECTO_DOCUM
			(ID_PROYECTO, ID_TIPO_SERVICIO, ID_DOCUMENTACION, FECHA_DOCUM, NRO_DOCUM_INTERNO,
			 PARTICIPANTES_DOCUM, TEMAS_DOCUM, ADJUNTO_DOCUM,
			 CONSULTOR, VISITA_MES, CONSULTOR_ACOMP, OBSERVACIONES,FECHA_CIERRE, ID_AGENDA, TIPO, ID_ADJUNTO, PROYECTO_SERV_ID)
			VALUES
			(@VPROYECTO, @VSERVICIO, 0, @VFECHA, 'Minuta de Visita',
			 NULL, NULL, NULL,
			 NULL, NULL, NULL, @VOBSERVACION, NULL, @VAGENDA_ID, @VTIPO, @VADJUNTO, @VPROYECTO_SERV)
 
		END
 
		IF (@VADJUNTO <> '') BEGIN
			UPDATE	PHYSICAL_ATTACHED_DOCUMENT
			SET		PAR_KEY = @VPROYECTO
			WHERE	PKEY = @VADJUNTO
		END
 
		UPDATE	XAGENDA
		SET		CONS_FECHA_MC = NULL,
				CONS_OBSERV_MC = NULL
		WHERE	PAR_KEY = @IPKEYJOB
	END
 
	
	IF (@OCODE = '0') BEGIN
		UPDATE	XAGENDA
		SET		ERROR = 'NO'
		WHERE	PAR_KEY = @IPKEYJOB
	END
END
