CREATE PROCEDURE [dbo].[HOME_CMB_ESTADO_PROYECTO]
(@IPKEYJOB	AS VARCHAR(100))
AS
 
DECLARE	@VACCION	VARCHAR(100)
 
BEGIN	
 
	SELECT	@VACCION = ISNULL(ACTION,'')
	FROM	XAGENDA
	WHERE	PAR_KEY = @IPKEYJOB
 
 
	IF (@VACCION <> 'COTIZACIONES' ) BEGIN
 
		SELECT	CAT_DATA_CODE,
				CAT_DATA_DESC,
				'true'
		FROM	CAT_DATA
		WHERE	PAR_KEY = (SELECT PKEY FROM CAT_TYPE WHERE CAT_TYPE_CODE = 'ESTADOS_PROYECTO')
		AND		CAT_DATA_CODE = 'CONFIRMADO'
	
	END ELSE BEGIN
 
		SELECT	CAT_DATA_CODE,
				CAT_DATA_DESC,
				'true'
		FROM	CAT_DATA
		WHERE	PAR_KEY = (SELECT PKEY FROM CAT_TYPE WHERE CAT_TYPE_CODE = 'ESTADOS_PROYECTO')
		UNION
		SELECT	'SIN_ASIGNAR',
				'Sin Asignar',
				'true'
	END
END
