CREATE  PROCEDURE PA_SYS_THIS_NOTES
	(@pkey_job AS VARCHAR(100))
AS
BEGIN
	SET NOCOUNT ON;
 
	SELECT TOP 5 NOTES AS "Notas y Observaciones"
	FROM PHYSICAL_NOTES
	WHERE PAR_KEY = @pkey_job
	ORDER BY NOTE_STATE_DATE DESC
 
END
