CREATE PROCEDURE PA_SYS_EXCL_VALIDAR (@PS_SQL VARCHAR(4000) OUTPUT, @PS_EXCL_IDR VARCHAR(1), @PS_JOB_TYPE_CODE VARCHAR(20), @PN_PRIORITY_VALUE NUMERIC(15, 0), @PN_ROWS NUMERIC(15, 0) = 0 OUTPUT, @PS_RET_MESSAGE VARCHAR(440) = NULL OUTPUT) AS
 
-- =========================================================================================================================
-- AUTOR: TITO - ENGAGE SOFTWARE COMPANY
-- FECHA DE CREACIÓN: 28/10/2008
-- EDITOR: MBRIZZI - ENGAGE SOFTWARE COMPANY
-- FECHA DE EDICIÓN: 31/08/2010
-- TABLAS LEÍDAS: CUSTOMER, LIST_TYPE, PHYSICAL_LIST, PHYSICAL_JOB Y LAS QUE VENGAN EN EL PARÁMETRO @PS_SQL.
-- TABLAS MODIFICADAS: NINGUNA
-- DESCRIPCIÓN: PROCEDIMIENTO PARA AVERIGUAR LA CANTIDAD TOTAL DE REGISTROS DE LA CONSULTA DINÁMICA ENVIADA POR PARÁMETROS.
-- PARÁMETROS:
-- @PS_SQL -> RECIBE LA CONSULTA SQL GENERADA DESDE ENGAGE MANAGER A TRAVÉS DEL ASISTENTE DE CRITERIOS O DE FORMA MANUAL A
-- TRAVÉS DEL EDITOR AVANZADO DE SQL.
-- @PS_EXCL_IDR -> INDICA SI LA LISTA ES EXCLUYENTE O NO.
-- @PS_JOB_TYPE_CODE -> ES EL JOB_TYPE_CODE USADO PARA RESTRINGIR LA CONSULTA DE VALIDACIÓN DE LISTAS EXCLUYENTES.
-- @PN_PRIORITY_VALUE -> INDICA LA PRIORIDAD DE LA LISTA. SE INFORMA COMO VALORES DE 0 A 100.
-- @PN_ROWS -> DEVUELVE LA CANTIDAD DE REGISTROS DE LA LISTA.
-- @PS_RET_MESSAGE -> DEVUELVE EL MENSAJE DE ERROR. NULL SI NO HUBO.
-- CONSIDERACIONES:
-- LA LONGITUD DEL CONTENIDO DEL PARÁMETRO @PS_SQL DEBE SER MENOR O IGUAL 3500 CARÁCTERES PARA EVITAR UN ERROR.
-- =========================================================================================================================
 
SET NOCOUNT ON;
SET XACT_ABORT ON;
 
-- DECLARACIÓN E INICIALIZACIÓN DE VARIABLES DE ERROR Y AUXILIARES.
DECLARE @LNERRORNUM AS INTEGER,
	@LNSEVERITY AS SMALLINT,
	@LNFILAS_AFEC AS INTEGER,
	@LDINICIO_OPE AS DATETIME,
	@LNDURACION AS INTEGER,
	@LSOPERA AS VARCHAR(30),
	@LSPROC AS VARCHAR(30),
	@LSTABLA AS VARCHAR(30),
	@LSERRORLOG AS VARCHAR(440),
	@LSERRORDESC AS VARCHAR(440),
	@LSSQL_CMD AS VARCHAR(4000)
;
SELECT 	@LNERRORNUM = 0,
	@LNSEVERITY = 16,
	@LNFILAS_AFEC = 0,
	@LDINICIO_OPE = GETDATE(),
	@LNDURACION = 0,
	@LSOPERA = 'EXECUTE',
	@LSPROC = OBJECT_NAME(@@PROCID),
	@LSTABLA = 'NINGUNA',
	@LSERRORLOG = @@SERVERNAME + '.' + DB_NAME() + '.' + USER_NAME() + '.' + OBJECT_NAME(@@PROCID) + ' - ',
	@LSERRORDESC = NULL,
	@LSSQL_CMD = NULL
;
-- DECLARACIÓN DE VARIABLES DE USUARIO.
DECLARE
@LS_HINT VARCHAR(30),
@LS_SQL VARCHAR(4000),
@LS_EXCL_IDR VARCHAR(1), -- '0', '1'.
@LS_JOB_TYPE_CODE VARCHAR(20),
@LN_PRIORITY_VALUE NUMERIC(15, 0),
@LN_ROWS NUMERIC(15, 0),
@LS_RET_MESSAGE VARCHAR(440),
@LS_SELECT_COUNT VARCHAR(4000),
@LS_SQL_CUR NVARCHAR(4000),
@LS_SQL_PAR NVARCHAR(4000);
 
SELECT	@LS_HINT = ' WITH (NOLOCK) ', -- ''
	@LS_SQL = NULLIF(@PS_SQL, ''),
	@LS_EXCL_IDR = NULLIF(@PS_EXCL_IDR, ''), -- '0', '1'.
	@LS_JOB_TYPE_CODE = ISNULL(NULLIF(@PS_JOB_TYPE_CODE, ''), ' '),
	@LN_PRIORITY_VALUE = @PN_PRIORITY_VALUE,
	@LN_ROWS = 0,
	@LS_RET_MESSAGE = NULL,
	@LS_SELECT_COUNT = 'SELECT @LN_VAR_LEN_OUT = CONVERT(NUMERIC(15, 0), COUNT(1)) FROM (',
	@LS_SQL_CUR = NULL,
	@LS_SQL_PAR = N'@LN_VAR_LEN_OUT NUMERIC(15, 0) OUTPUT'; -- ASOCIA EL PARÁMETRO DE SALIDA CON EL RESULTADO DEL QUERY DINÁMICO.
 
BEGIN TRANSACTION
 
-- TODOS LOS PARÁMETROS DEBEN SER VÁLIDOS.
IF (@LS_SQL IS NOT NULL) BEGIN
	IF (LEN(@LS_SQL) < 3501) BEGIN
		IF (@LS_EXCL_IDR IS NOT NULL) BEGIN
			IF (@LN_PRIORITY_VALUE IS NOT NULL) BEGIN
				-- MODIFICA LA CONSULTA DINÁMICA ENVIADA POR PARÁMETRO CON UNA LISTA DE CLIENTES EXCLUÍDOS.
				SET @LS_SQL = @LS_SQL + ' AND CUSTOMER.PKEY NOT IN (SELECT DISTINCT PJ.PKEY_CUSTOMER';
				SET @LS_SQL = @LS_SQL + ' FROM PHYSICAL_JOB PJ' + @LS_HINT + ', PHYSICAL_LIST PL' + @LS_HINT + ', LIST_TYPE LT' + @LS_HINT ;
				SET @LS_SQL = @LS_SQL + ' WHERE PJ.PKEY_CAMPAIGN = PL.PKEY';
				SET @LS_SQL = @LS_SQL + ' AND PL.LIST_TYPE_PKEY = LT.PKEY';
				-- LISTAS EXCLUYENTES VIGENTES.
				SET @LS_SQL = @LS_SQL + ' AND PL.LAST_DATE >= CONVERT(VARCHAR, GETDATE(), 112)';
				-- LISTAS EXCLUYENTES INICIADAS O CARGADAS.
				SET @LS_SQL = @LS_SQL + ' AND (PL.STATE_CODE = ''INICIADA'' OR PL.STATE_CODE = ''CARGADA'')';
				-- LISTAS EXCLUYENTES DEL TIPO DE TRÁMITE ESPECIFICADO POR PARÁMETRO.
				SET @LS_SQL = @LS_SQL + ' AND LT.EXCL_IDR = ''1'' AND (LT.EXCL_JOB_TYPE_CODE IS NULL OR LT.EXCL_JOB_TYPE_CODE = ''' + @LS_JOB_TYPE_CODE + ''')';
				-- SÓLO SE AGREGA ESTA RESTRICCIÓN SI EL USUARIO ESTÁ CREANDO UNA LISTA EXCLUYENTE. POR EJEMPLO, DE PRIORIDAD 2.
				IF (@LS_EXCL_IDR = '1') BEGIN
					SET @LS_SQL = @LS_SQL + ' AND PL.PRIORITY < ''' + CONVERT(VARCHAR, @LN_PRIORITY_VALUE) + '''';
				END;
				-- CIERRA LA CONSULTA DINÁMICA.
				SET @LS_SQL = @LS_SQL + ')';
 
				-- ARMA UNA CONSULTA DINÁMICA DE CONTEO DE REGISTROS EN BASE A LA CONSULTA ANTERIOR.
				SET @LS_SQL_CUR = @LS_SELECT_COUNT + @LS_SQL + ') T1';
				-- PRINT @LS_SQL_CUR;
 
				-- COMPILA Y EJECUTA EL CÓDIGO DINÁMICO, OBTENIENDO LA CANTIDAD DE REGISTROS.
				EXECUTE	@LNERRORNUM = SP_EXECUTESQL @LS_SQL_CUR, @LS_SQL_PAR, @LN_VAR_LEN_OUT = @LN_ROWS OUTPUT;
				SELECT @LSOPERA = 'EXECUTE', @LSTABLA = 'SP_EXECUTESQL', @LSSQL_CMD = @LS_SQL_CUR, @LNFILAS_AFEC = @@ROWCOUNT;
				IF (@LNERRORNUM <> 0) GOTO FALLO;
 
				-- DEVUELVE LA CANTIDAD DE REGISTROS.
				SET @PN_ROWS = @LN_ROWS;
				-- DEVUELVE LA CONSULTA EDITADA RESULTANTE.
				SET @PS_SQL = REPLACE(@LS_SQL, LTRIM(RTRIM(@LS_HINT)), '');
			END
			ELSE BEGIN
				SET @LS_RET_MESSAGE = 'EL PARÁMETRO @PS_PRIORITY_VALUE ES NULO.';
			END;
		END
		ELSE BEGIN
			SET @LS_RET_MESSAGE = 'EL PARÁMETRO @PS_EXCL_IDR ES NULO.';
		END;
	END
	ELSE BEGIN
		SET @LS_RET_MESSAGE = 'LA CONSULTA ENVIADA EN EL PARÁMETRO @PS_SQL TIENE MÁS DE 3500 CARÁCTERES.';
	END; 
END
ELSE BEGIN
	SET @LS_RET_MESSAGE = 'EL PARÁMETRO @PS_SQL ES NULO.';
END;
 
-- DEVUELVE EL MENSAJE DE ERROR. NULL SI NO HUBO.
SET @PS_RET_MESSAGE = @LS_RET_MESSAGE;
 
FALLO:
-- REGISTRO DE SUCESOS Y CONTROL DE FIN DE PROCEDIMIENTO. CONCLUYE LA TRANSACCIÓN SI TODO FUE EXITOSO.
SELECT @LNDURACION = DATEDIFF(SECOND, @LDINICIO_OPE, GETDATE()), @LNSEVERITY = ISNULL(EM.SEVERITY, 16), @LSERRORDESC = 'ERROR ' + CONVERT(VARCHAR, ISNULL(EM.ERROR, 0)) + ' - ' + ISNULL(EM.DESCRIPTION, ' ') FROM MASTER.DBO.SYSMESSAGES EM WHERE (EM.ERROR = @LNERRORNUM);
IF (@LNERRORNUM <> 0) BEGIN
	-- NOTIFICACIÓN EN EL REGISTRO DE SQL SERVER.
	SET @LSERRORLOG = @LSERRORLOG + CASE WHEN (ISNULL(CHARINDEX('%', @LSERRORDESC), 0) > 0) THEN RTRIM(LEFT(@LSERRORDESC, 11)) ELSE @LSERRORDESC END;
	-- DEVUELVE EL ERROR EN EL PARÁMETRO DE SALIDA.
	SET @PS_RET_MESSAGE = SUBSTRING(@LSERRORDESC, 1, 440);
	-- DESHACE LA TRANSACCIÓN COMPLETA SI LA OPERACIÓN FALLÓ.
	IF (@@TRANCOUNT > 0) ROLLBACK TRANSACTION;
	EXECUTE @LNERRORNUM = PA_SYS_REGISTRO_SUCESOS_INSERT @PSPROCEDIMIENTO_1 = @LSPROC, @PSTABLA_2 = @LSTABLA, @PNFILAS_AFECTADAS_3 = @LNFILAS_AFEC, @PSOPERACION_4 = @LSOPERA, @PNDURACION_5 = @LNDURACION, @PSRESULTADO_6 = @LSERRORDESC, @PSSQL_CMD_7 = @LSSQL_CMD;
	-- RAISERROR(@LSERRORLOG, @LNSEVERITY, -1) WITH NOWAIT;
END
ELSE BEGIN
	-- EXECUTE @LNERRORNUM = PA_SYS_REGISTRO_SUCESOS_INSERT @PSPROCEDIMIENTO_1 = @LSPROC, @PSTABLA_2 = @LSTABLA, @PNFILAS_AFECTADAS_3 = @LNFILAS_AFEC, @PSOPERACION_4 = @LSOPERA, @PNDURACION_5 = @LNDURACION, @PSRESULTADO_6 = @LSERRORDESC, @PSSQL_CMD_7 = @LSSQL_CMD;
	IF (@@TRANCOUNT > 0) COMMIT TRANSACTION;
END;
RETURN;
