CREATE   PROCEDURE [dbo].[M_CONFIG_CMB_GROUPS_MODULOS]
(@IPKEYJOB	AS VARCHAR(100))
AS
 
DECLARE @V_PERFIL_SEL VARCHAR(50)
 
BEGIN
 
	SELECT	@V_PERFIL_SEL = ISNULL(ID_GROUP_SEL,'')
	FROM	M_CONFIG
	WHERE	PAR_KEY = @IPKEYJOB
 
	SELECT  PKEY	AS CAT_DATA_CODE,
			CALL_TYPE_DESC	AS CAT_DATA_DESC, 
			'TRUE'
	FROM	CALL_TYPE
	WHERE	PKEY not in ( 
				select PKEY_CALL_TYPE from UNIT_CALL_TYPE
				where UNIT_CODE = @V_PERFIL_SEL) 
	order by CALL_TYPE_DESC
 
END
