CREATE   PROCEDURE [dbo].[SV_01_CMB_CAMPO_ASOCIADO]
(@IPKEYJOB	AS VARCHAR(100))
AS
 
DECLARE @VCLAVE_DOC	 VARCHAR(100),
		@VCODIGO_DOC VARCHAR(50)
DECLARE @VDATO		VARCHAR(50)
 
BEGIN
 
	SELECT	@VCLAVE_DOC = CLAVE_DOC,
			@VDATO = ISNULL(DATO,'')
	FROM	TMT_SV_01
	WHERE	PAR_KEY = @IPKEYJOB
 
	SELECT	@VCODIGO_DOC = CODE_DOCUMENTACION
	FROM	LK_DOCUMENTACION
	WHERE	ID_DOCUMENTACION = @VCLAVE_DOC
 
	IF (@VDATO = 'LK_CLIENTES') BEGIN
		SELECT	COLUMN_NAME AS CAT_DATA_CODE,
				REPLACE(COLUMN_NAME,'_',' ') AS CAT_DATA_DESC,
				'TRUE'
		FROM	EVI_TABLE_COLUMNS
		WHERE	TABLE_NAME = @VDATO
		AND		COLUMN_NAME IN ('RAZON_SOCIAL_CLIENTE','CONTACTO_CLIENTE')
		UNION
		SELECT	'DOMICILIO', 'DOMICILIO','TRUE'
		ORDER BY 2 ASC
	END
 
	IF (@VDATO = 'LK_PROYECTO') BEGIN
		SELECT	COLUMN_NAME AS CAT_DATA_CODE,
				CASE WHEN COLUMN_NAME = 'FECHA_INICIO_REAL' THEN
						'FECHA INICIO'
					 WHEN COLUMN_NAME = 'FECHA_FIN_REAL' THEN
						'FECHA FIN'
					WHEN COLUMN_NAME = 'OBSERVACIONES' THEN
						'ANALISTA A CARGO'
				ELSE
					REPLACE(COLUMN_NAME,'_',' ')
				END			AS CAT_DATA_DESC,
				'TRUE'
		FROM	EVI_TABLE_COLUMNS
		WHERE	TABLE_NAME = @VDATO
		AND		COLUMN_NAME IN ('NORMAS','CODIGO','CONTACTO','ID_COTIZACION','FECHA_INICIO_REAL','FECHA_FIN_REAL','OBSERVACIONES')
		ORDER BY 2 ASC
	END	
 
	IF (@VDATO = 'LK_DOCUMENTACION_DET') BEGIN
		SELECT	ID_DOCUMENTACION_DET AS CAT_DATA_CODE,
				CONVERT(VARCHAR,ORDEN) + ' - ' + DESC_DOC_DET  AS CAT_DATA_DESC,
				'TRUE'	
		FROM	LK_DOCUMENTACION_DET
		WHERE	ID_DOCUMENTACION = CASE WHEN @VCODIGO_DOC = 'RE-PP-022-A-Anex' THEN 8
										WHEN @VCODIGO_DOC = 'RE-PP-022-CA-Anex' THEN 9
										WHEN @VCODIGO_DOC = 'RE-PP-022-CO-Anex' THEN 10 END
		ORDER BY CASE WHEN GRUPO_DOC_DET = 'GENERAL' THEN 1 ELSE 2 END, ORDEN ASC
	END
 
END
 
