CREATE PROCEDURE [dbo].[HOME_ADD_MINUTA_GESTION]
(@ICLIENTE	AS VARCHAR(100),
 @IPROYECTO	AS VARCHAR(100),
 @IAGENTE	AS VARCHAR(100),
 @ISERVICIO	AS VARCHAR(50))
AS
 
DECLARE	@VID_DOC			VARCHAR(50),
		@VID_PROYECTO_DOCUM	VARCHAR(50),
		@VDESC_DOC_DET		VARCHAR(400), 
		@VGRUPO_DOC_DET		VARCHAR(50),
		@VORDEN				NUMERIC(5,0),
		@VOBLIGATORIO_DET	VARCHAR(50),
		@VDATO_DET			VARCHAR(50),
		@VCAMPO_DET			VARCHAR(50),
		@VEXPORTA_DET		VARCHAR(50),
		@VFECHA				DATETIME,
 
		@VALOR				NVARCHAR(400),
        @VQUERY_FROM		VARCHAR(400),
        @VQUERY_WHERE		VARCHAR(400),
        @SQL				NVARCHAR(MAX);
 
BEGIN	
 
	/* Grabo el ID de Documentacion que corresponda segun el Servicio
		8	RE-PP-022-A		Minuta de Gestion Auditoria
		9	RE-PP-022-CA	Minuta de Gestion Capacitacion
		10	RE-PP-022-CO	Minuta de Gestion Consultoria
 
		1	Consultoria --> GRABO ID 10
		2	Auditoria --> GRABO ID 8
		3	Capacitacion --> GRABO ID 9
	*/
	SELECT	@VID_DOC =	CASE WHEN @ISERVICIO = '1' THEN '10'
							 WHEN @ISERVICIO = '2' THEN '8'
							 WHEN @ISERVICIO = '3' THEN '9'
						END 
	
	SET @VFECHA = GETDATE()
 
	INSERT INTO LK_PROYECTO_DOCUM
		(ID_PROYECTO, ID_TIPO_SERVICIO, ID_DOCUMENTACION, 
		FECHA_DOCUM, NRO_DOCUM_INTERNO,
		PARTICIPANTES_DOCUM, TEMAS_DOCUM, ADJUNTO_DOCUM,
		CONSULTOR, VISITA_MES, CONSULTOR_ACOMP, OBSERVACIONES,FECHA_CIERRE,
		ID_AGENDA, TIPO)
	VALUES
		(@IPROYECTO, @ISERVICIO, @VID_DOC, 
		GETDATE(), 'Minuta de Gestion '+ CASE WHEN @ISERVICIO = '1' THEN 'Consultoria' WHEN @ISERVICIO = '2' THEN 'Auditoria' WHEN @ISERVICIO = '3' THEN 'Capacitacion' END + ' - ' + CONVERT(varchar, DATEPART(DD, @VFECHA))+'-'+CONVERT(varchar, DATEPART(MM, @VFECHA))+'-'+CONVERT(varchar, DATEPART(YYYY, @VFECHA)), 
		NULL, NULL, NULL,
		NULL, NULL, NULL, NULL, NULL,
		NULL, 'MG')
 
	SELECT	@VID_PROYECTO_DOCUM = IDENT_CURRENT ('LK_PROYECTO_DOCUM')
 
		--RECUPERO TODOS LOS ITEMS QUE CORRESPONDEN AL DETALLE DE LA HOJA DE RUTA QUE CORRESPONDA SEGUN SERVICIO--
	DECLARE Items CURSOR FOR 
		SELECT	DESC_DOC_DET, GRUPO_DOC_DET, ISNULL(ORDEN,99) ORDEN, OBLIGATORIO_DET, EXPORTA_DET, DATO_DET, CASE WHEN CAMPO_DET IN ('FECHA_INICIO_REAL','FECHA_FIN_REAL') THEN 'CONVERT(VARCHAR,'+ CAMPO_DET + ',103)' ELSE CAMPO_DET END
		FROM	LK_DOCUMENTACION_DET
		WHERE	ID_DOCUMENTACION = @VID_DOC
		AND		STATUS_DOC_DET = '1'
		ORDER BY CASE WHEN GRUPO_DOC_DET = 'GENERAL' THEN 1 
						WHEN GRUPO_DOC_DET = 'CIERRE' THEN 2 END, ISNULL(ORDEN,99)
 
	OPEN Items  
	FETCH NEXT FROM Items INTO @VDESC_DOC_DET, @VGRUPO_DOC_DET, @VORDEN, @VOBLIGATORIO_DET,	@VEXPORTA_DET, @VDATO_DET,	@VCAMPO_DET
 
	WHILE @@FETCH_STATUS = 0  
	BEGIN  
		
		SET @VALOR = NULL
 
		--SI EL DATO_DET TIENE DATO, CARGO EL CAMPO VAlor--
		IF (ISNULL(@VDATO_DET,'') <> '') BEGIN
			
			--RECUPERO EL VALOR SEGUN EL DATO Y EL CAMPO--
			IF @VDATO_DET = 'LK_CLIENTES' BEGIN
				
				IF (@VCAMPO_DET = 'DOMICILIO') BEGIN
					
					SELECT	@VALOR = ISNULL(CALLE_CLIENTE,'') + ' ' + ISNULL(NRO_CALLE_CLIENTE,'') + ' / ' + --' - Depto: '+ ISNULL(@VPISO,'') + char(10) +
									 ISNULL(LOCALIDAD_CLIENTE,'') + ' - ' + ISNULL(PROVINCIA_CLIENTE,'')
					FROM	LK_CLIENTES
					WHERE	ID_CLIENTE = ISNULL(@ICLIENTE, '')
 
				END ELSE BEGIN
					
					SET @VQUERY_FROM = ' FROM ' + ISNULL(@VDATO_DET, '')
					SET @VQUERY_WHERE = ' WHERE ID_CLIENTE = ' + ISNULL(@ICLIENTE, '')
 
					-- Construct the dynamic SQL
					SET @SQL = N'SELECT @ValorOUT = ' + @VCAMPO_DET + @VQUERY_FROM + @VQUERY_WHERE
					--QUOTENAME(@VCAMPO_DET) + @VQUERY_FROM + @VQUERY_WHERE
 
					-- ASOCIA EL PARÁMETRO DE SALIDA CON EL RESULTADO DEL QUERY DINÁMICO.
					-- Execute the dynamic SQL with parameter
					EXEC sp_executesql @SQL,
						N'@ValorOUT NVARCHAR(400) OUTPUT',
						@ValorOUT = @VALOR OUTPUT					
 
				END
			END
 
			IF @VDATO_DET = 'LK_PROYECTO' BEGIN
				
				SET @VQUERY_FROM = ' FROM ' + ISNULL(@VDATO_DET,'')
				SET @VQUERY_WHERE = ' WHERE ID_PROYECTO = ' + ISNULL(@IPROYECTO,'')
 
				-- Construct the dynamic SQL
				SET @SQL = N'SELECT @ValorOUT = ' + @VCAMPO_DET + @VQUERY_FROM + @VQUERY_WHERE
				--QUOTENAME(@VCAMPO_DET) + @VQUERY_FROM + @VQUERY_WHERE
 
				-- ASOCIA EL PARÁMETRO DE SALIDA CON EL RESULTADO DEL QUERY DINÁMICO.
				-- Execute the dynamic SQL with parameter
				EXEC sp_executesql @SQL,
					N'@ValorOUT NVARCHAR(400) OUTPUT',
					@ValorOUT = @VALOR OUTPUT	
					
				IF (@VCAMPO_DET = 'NORMAS') BEGIN
					SELECT @VALOR = REPLACE(dbo.FN_GET_NORMA_HTML('',ISNULL(@VALOR,''),''),'</br>',char(10))
				END
				
				IF (@VCAMPO_DET = 'ID_COTIZACION') BEGIN
					SELECT	@VALOR = ISNULL(NRO_COTIZACION,'')
					FROM	LK_COTIZACIONES
					WHERE	ID_COTIZACION = ID_COTIZACION
				END					
			END
		END
 
		INSERT INTO LK_PROYECTO_DOCUM_DET
		(ID_PROYECTO_DOCUM, DESC_DOC_DET, VALOR_DOC_DET, GRUPO_DOC_DET, ADJUNTO_DOC_DET, ORDEN, OBLIGATORIO_DOC_DET, DATO_DOC_DET, CAMPO_DOC_DET, EXPORTA_DOC_DET)
		VALUES
		(@VID_PROYECTO_DOCUM, @VDESC_DOC_DET, ISNULL(@VALOR,''), @VGRUPO_DOC_DET, NULL, @VORDEN, @VOBLIGATORIO_DET, @VDATO_DET, @VCAMPO_DET, @VEXPORTA_DET)
 
		FETCH NEXT FROM Items INTO @VDESC_DOC_DET, @VGRUPO_DOC_DET, @VORDEN, @VOBLIGATORIO_DET, @VEXPORTA_DET, @VDATO_DET,	@VCAMPO_DET
	END 
 
	CLOSE Items  
	DEALLOCATE Items
END
