CREATE PROCEDURE [dbo].[EP_DATOS_UTILES]
(@IPKEYJOB	AS VARCHAR(100),
 @IAGENTE	AS VARCHAR(100))
AS
BEGIN	
	
 
	SELECT distinct P.PLANTA as 'Planta', '<a target="_blank" href="mailto:'+isnull(U.Email,'')+'">'+U.[NAME]+'</a>' as 'Responsable', U.Phone as 'Telefono' FROM EP_PLANTAS_USUARIOS PU
	INNER JOIN GROUPSUSERMEMBERS G ON G.USERMEMBERID=PU.IDUSUARIO AND GROUPID='EP_EJECUTIVOS'
	INNER JOIN USERS U ON U.ID=G.USERMEMBERID
	INNER JOIN EP_PLANTAS P ON P.IDPLANTA=PU.IDPLANTA
	WHERE PU.IDPlanta in 
		(SELECT DISTINCT PU.IDPlanta FROM EP_PLANTAS_USUARIOS PU
		INNER JOIN GROUPSUSERMEMBERS G ON G.USERMEMBERID=PU.IDUSUARIO AND G.GROUPID='EP_CLIENTES'
		INNER JOIN USERS U ON U.ID=G.USERMEMBERID
		WHERE PU.IdUsuario=@IAGENTE)
  
 
END
