CREATE PROCEDURE BUSCA_EN_XML (@PSXML AS VARCHAR(4000), @PSELEMENTO AS VARCHAR(4000), @PSVALOR AS VARCHAR(4000) OUTPUT) AS
 
-- PROCEDIMIENTO QUE BUSCA UN NODO DETERMINADO DENTRO DE UNA CADENA DE XML.
 
DECLARE @LSXML AS VARCHAR(4000),
	@LSELEMENTO1 AS VARCHAR(4000),
	@LSELEMENTO2 AS VARCHAR(4000),
	@LNDESDE AS INTEGER,
	@LNLARGO AS INTEGER,
	@LSVALOR AS VARCHAR(4000)
;
SELECT	@LSXML = ISNULL(LTRIM(RTRIM(@PSXML)), ' '),
	@LSELEMENTO1 = '<' + ISNULL(LTRIM(RTRIM(@PSELEMENTO)), ' ') + '>',
	@LSELEMENTO2 = '</' + ISNULL(LTRIM(RTRIM(@PSELEMENTO)), ' ') + '>',
	@LNDESDE = 0,
	@LNLARGO = 0,
	@LSVALOR = ' '
;
 
BEGIN TRANSACTION
 
SET @LNDESDE = CHARINDEX(@LSELEMENTO1, @LSXML, 1) + LEN(@LSELEMENTO1);
SET @LNLARGO = CHARINDEX(@LSELEMENTO2, @LSXML, 1) - @LNDESDE;
 
IF (@LSXML <> ' ') AND (@LNDESDE > 0) AND (@LNLARGO > 0)
BEGIN
	SET @LSVALOR = SUBSTRING(@LSXML, @LNDESDE, @LNLARGO);
END;
 
SET @PSVALOR = @LSVALOR;
 
COMMIT TRANSACTION;
 
RETURN;
