 
CREATE PROCEDURE [dbo].[EP_ADD_USR_PLANTA]
(@IPKEYJOB	AS VARCHAR(100),
 @IUSERID	AS VARCHAR(100),
 @RTA AS VARCHAR(100) OUTPUT)
AS
 
BEGIN	
 
 
	DECLARE 
	@ID_PLANTA_SEL VARCHAR(50),
	@ACTION VARCHAR(50),
	@ID_USER_SEL VARCHAR(30);
 
	SELECT @ID_PLANTA_SEL = ID_PLANTA_SEL, @ID_USER_SEL=ID_USER_SEL, @ACTION=[ACTION] FROM TMT_CRON WHERE PAR_KEY= @IPKEYJOB;
 
	IF @ACTION ='ASIGN_USER'
		BEGIN
			INSERT INTO EP_PLANTAS_USUARIOS (IDPlanta, IdUsuario) VALUES (CAST(@ID_PLANTA_SEL AS INT), @ID_USER_SEL);
			SET @RTA='<br><p><b><font color="red">Usuario asignado con exito.</font></b></p>'
		END
	ELSE
		BEGIN 
			SET @RTA=''
		END
 
END
