CREATE PROCEDURE [PA_SYS_CLOSEJOB] (@PS_IDJOB AS VARCHAR(100), @PS_IDESTADO AS VARCHAR(20), @PS_IDREASON AS VARCHAR(50), @PS_IDSUBREASON AS VARCHAR(50) = NULL, @PS_IDESTADOATT AS VARCHAR(20), @PS_RET_MESSAGE AS VARCHAR(440) OUTPUT) AS
 
-- =========================================================================================================================
-- TABLAS LEÍDAS: PHYSICAL_JOB, DSS_TBPHYSICAL_JOB, ATTENDED_CUSTOMER, DSS_TBATTENDED_CUSTOMER, PHYSICAL_CALL,
-- DSS_TBPHYSICAL_CALL, PHYSICAL_CALL_CONV_STEPS, DSS_TBPHYSICAL_CALL_CONV_STEPS, PHYS_CALL_ANSWERED_QUESTIONS,
-- DSS_TBPHYS_CALL_ANSWERED_QUES.
-- TABLAS MODIFICADAS: PHYSICAL_JOB, ATTENDED_CUSTOMER, PHYSICAL_CALL, DSS_TBPHYSICAL_JOB, DSS_TBATTENDED_CUSTOMER,
-- DSS_TBPHYSICAL_CALL, DSS_TBPHYSICAL_CALL_CONV_STEPS, DSS_TBPHYS_CALL_ANSWERED_QUES.
-- DESCRIPCIÓN: PROCEDIMIENTO PARA CERRAR TRÁMITES A PARTIR DE UNA CLAVE, UN ESTADO DE TRÁMITE, UN MOTIVO, UN SUBMOTIVO Y UN
-- ESTADO DE ACTIVIDAD PROVISTOS POR PARÁMETROS. ADEMÁS, OBTIENE LA ÚLTIMA UNIDAD Y EL ÚLTIMO USUARIO QUE OPERÓ EL PROCESO.
-- CONSIDERACIONES:
-- 1. REGISTRA SÓLO LOS ERRORES EN LA TABLA EDA_REGISTRO_SUCESOS
-- 2. DEVUELVE UN PARÁMETRO DE SALIDA QUE INDICA SI EL PROCEDIMIENTO TERMINÓ BIEN O MAL.
-- =========================================================================================================================
 
SET NOCOUNT ON;
SET XACT_ABORT ON;
 
-- DECLARACIÓN E INICIALIZACIÓN DE VARIABLES DE ERROR Y AUXILIARES.
DECLARE @LNERRORNUM AS INTEGER,
	@LNSEVERITY AS SMALLINT,
	@LNFILAS_AFEC AS INTEGER,
	@LDINICIO_OPE AS DATETIME,
	@LNDURACION AS INTEGER,
	@LSOPERA AS VARCHAR(30),
	@LSPROC AS VARCHAR(30),
	@LSTABLA AS VARCHAR(30),
	@LSERRORLOG AS VARCHAR(440),
	@LSERRORDESC AS VARCHAR(440),
	@LSSQL_CMD AS VARCHAR(4000)
;
SELECT 	@LNERRORNUM = 0,
	@LNSEVERITY = 16,
	@LNFILAS_AFEC = 0,
	@LDINICIO_OPE = GETDATE(),
	@LNDURACION = 0,
	@LSOPERA = 'EXECUTE',
	@LSPROC = OBJECT_NAME(@@PROCID),
	@LSTABLA = 'NINGUNA',
	@LSERRORLOG = @@SERVERNAME + '.' + DB_NAME() + '.' + USER_NAME() + '.' + OBJECT_NAME(@@PROCID) + ' - ',
	@LSERRORDESC = NULL,
	@LSSQL_CMD = NULL
;
DECLARE	@LDFECHA_DESDE AS DATETIME,
	@LDFECHA_HASTA AS DATETIME,
	@LSHORA_DESDE AS VARCHAR(8),
	@LSHORA_HASTA AS VARCHAR(8),
	@LSRANGO_HORA AS VARCHAR(5),
	@LS_IDJOB AS VARCHAR(100),
	@LS_IDESTADO AS VARCHAR(20),
	@LS_IDREASON AS VARCHAR(50),
	@LS_IDSUBREASON AS VARCHAR(50),
	@LS_IDESTADOATT AS VARCHAR(20),
	@LS_RET_MESSAGE AS VARCHAR(440),
	@LS_JOB_STATE_CODE AS VARCHAR(20),
	@LS_ATT_STATE_CODE AS VARCHAR(20),
	@LS_PHYS_STATE_CODE AS VARCHAR(20),
	@LS_PHYS_RESULT_CODE AS VARCHAR(20),
	@LS_TS_USER_ID AS VARCHAR(30),
	@LS_NO_APLICA AS VARCHAR(20),
	@LS_UNIT_CODE AS VARCHAR(100),
	@LS_USER_ID AS VARCHAR(30),
	@LS_PREV_UNIT_CODE AS VARCHAR(100),
	@LS_PREV_USER_ID AS VARCHAR(30),
	@LS_ATT_COMMENT AS VARCHAR(250),
	@LS_PKEY_ATTENDED_CUSTOMER AS VARCHAR(80),
	@LNCOUNT AS NUMERIC(15, 0)
;
-- DECLARA LAS VARIABLES Y ASIGNA VALORES PREDETERMINADOS.
SELECT	@LDFECHA_DESDE = CONVERT(VARCHAR, GETDATE(), 112); -- DEVUELVE LA FECHA CON LA HORA Y LOS MILISEGUNDOS EN 0 ('2001-01-01 00:00:00.000').
SELECT	@LDFECHA_HASTA = CONVERT(VARCHAR, GETDATE(), 112); -- DEVUELVE LA FECHA CON LA HORA Y LOS MILISEGUNDOS EN 0 ('2001-01-01 00:00:00.000').
SELECT	@LSHORA_DESDE = CONVERT(VARCHAR, GETDATE(), 108); -- DEVUELVE LA HORA (12:45:03).
SELECT	@LSHORA_HASTA = CONVERT(VARCHAR, GETDATE(), 108); -- DEVUELVE LA HORA (12:45:03).
SELECT	@LSRANGO_HORA = RIGHT('00' + CONVERT(VARCHAR, DATEPART(HOUR, GETDATE())), 2) + '-' + RIGHT('00' + CONVERT(VARCHAR, DATEPART(HOUR, GETDATE()) + 1), 2); -- DEVUELVE LA HORA + 1 (17-18) (RANGO DE HORA).
SELECT	@LS_IDJOB = @PS_IDJOB,
	@LS_IDESTADO = @PS_IDESTADO,
	@LS_IDREASON = @PS_IDREASON,
	@LS_IDSUBREASON = ISNULL(@PS_IDSUBREASON, @PS_IDREASON), -- SI EL SUBMOTIVO NO FUE INFORMADO, SE LE ASIGNA EL MOTIVO.
	@LS_IDESTADOATT = @PS_IDESTADOATT,
	@LS_RET_MESSAGE = 'OK',
	@LS_JOB_STATE_CODE = 'CLOSED',
	@LS_ATT_STATE_CODE = 'Cerrado',
	@LS_PHYS_STATE_CODE = 'CLOSED',
	@LS_PHYS_RESULT_CODE = 'SUCCESSFUL',
	@LS_TS_USER_ID = 'ADMINISTRADOR',
	@LS_NO_APLICA = 'NO APLICA',
	@LS_UNIT_CODE = NULL,
	@LS_USER_ID = NULL,
	@LS_PREV_UNIT_CODE = NULL,
	@LS_PREV_USER_ID = NULL,
	@LS_ATT_COMMENT = NULL,
	@LS_PKEY_ATTENDED_CUSTOMER = NULL,
	@LNCOUNT = 0
;
 
-- DECLARO LA TRANSACCIÓN.
BEGIN TRANSACTION
 
-- VALIDA TODOS LOS PARÁMETROS DE ENTRADA.
IF (@LS_IDJOB IS NOT NULL) BEGIN
	IF (@LS_IDESTADO IS NOT NULL) BEGIN
		IF (@LS_IDREASON IS NOT NULL) BEGIN
			IF (@LS_IDESTADOATT IS NOT NULL) BEGIN
 
				-- DETERMINA SI EXISTEN ACTIVIDADES PARA EL TRÁMITE ESPECIFICADO EN ATTENDED_CUSTOMER.
				SELECT @LNCOUNT = COUNT(1) FROM ATTENDED_CUSTOMER AC2 WHERE (AC2.PKEY_JOB = @LS_IDJOB);
 
				IF (@LNCOUNT > 0) BEGIN
					-- BUSCA LA UNIDAD Y EL USUARIO DE LA ÚLTIMA ACTIVIDAD DEL PROCESO, ENTRE OTROS DATOS.
					SELECT	@LS_PKEY_ATTENDED_CUSTOMER = AC.PKEY, @LS_UNIT_CODE = AC.GROUP_CODE, @LS_USER_ID = AC.USER_ID, @LS_PREV_UNIT_CODE = AC.PREV_GROUPCODE, @LS_PREV_USER_ID = AC.PREV_USERID, @LS_ATT_COMMENT = AC.ATT_COMMENT
					FROM	ATTENDED_CUSTOMER AC
					WHERE	AC.PKEY = (SELECT TOP 1 AC2.PKEY FROM ATTENDED_CUSTOMER AC2 WHERE (AC2.PKEY_JOB = @LS_IDJOB) ORDER BY AC2.TS_BEGIN DESC);
 
					-- CIERRA EL TRÁMITE.
					UPDATE	PHYSICAL_JOB
					SET	JOB_RESULT_CODE = @LS_IDESTADO,
						JOB_STATE_CODE = @LS_JOB_STATE_CODE,
						JOB_STATE_DATE = @LDINICIO_OPE,
						ATT_STATE_CODE = @LS_ATT_STATE_CODE,
						ATT_RESULT_CODE = @LS_IDESTADOATT,
						JOB_REASON_CODE = @LS_IDREASON,
						JOB_SUBREASON_CODE = @LS_IDSUBREASON,
						PKEY_ATTENDED_CUSTOMER = @LS_PKEY_ATTENDED_CUSTOMER,
						ATT_GROUP_CODE = @LS_UNIT_CODE,
						USER_ID = @LS_USER_ID,
						PREV_GROUP_CODE = @LS_PREV_UNIT_CODE,
						PREV_USER_ID = @LS_PREV_USER_ID,
						ATT_COMMENT = @LS_ATT_COMMENT,
						TS_USER_ID = @LS_TS_USER_ID,
						TS_END = @LDINICIO_OPE
					WHERE	(PKEY = @LS_IDJOB);
					SELECT @LSOPERA = 'UPDATE', @LSTABLA = 'PHYSICAL_JOB', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
					IF (@LNERRORNUM <> 0) GOTO FALLO;
 
					-- CIERRA LAS ATENCIONES DEL TRÁMITE.
					UPDATE	ATTENDED_CUSTOMER
					SET	ATT_STATE_CODE = @LS_ATT_STATE_CODE,
						ATT_RESULT_CODE = @LS_IDESTADOATT,
						TS_USER_ID = @LS_TS_USER_ID,
						TS_END = @LDINICIO_OPE
					WHERE	(PKEY_JOB = @LS_IDJOB)
						AND (ATT_STATE_CODE <> @LS_ATT_STATE_CODE);
					SELECT @LSOPERA = 'UPDATE', @LSTABLA = 'ATTENDED_CUSTOMER', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
					IF (@LNERRORNUM <> 0) GOTO FALLO;
 
					-- CIERRA LAS LLAMADAS DE LAS ATENCIONES DEL TRÁMITE.
					UPDATE	PHYSICAL_CALL
					SET	PHYS_STATE_CODE = @LS_PHYS_STATE_CODE,
						PHYS_RESULT_CODE = @LS_PHYS_RESULT_CODE,
						TS_USER_ID = @LS_TS_USER_ID,
						TS_END = @LDINICIO_OPE
					WHERE	(PHYS_STATE_CODE <> @LS_PHYS_STATE_CODE)
						AND EXISTS (
						SELECT	1
						FROM	ATTENDED_CUSTOMER T1
						WHERE	(T1.PKEY = PHYSICAL_CALL.PAR_KEY)
							AND (T1.PKEY_JOB = @LS_IDJOB)
						);
					SELECT @LSOPERA = 'UPDATE', @LSTABLA = 'PHYSICAL_CALL', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
					IF (@LNERRORNUM <> 0) GOTO FALLO;
 
					-- INSERTA LOS REGISTROS CERRADOS EN DSS_TBPHYSICAL_JOB, MAPEANDO LOS CAMPOS DE LA MISMA FORMA QUE LO HACE ENGAGE.
					INSERT INTO	DSS_TBPHYSICAL_JOB (PKEY_PHYSICAL_JOB, ID_CUSTOMER, ID_JOB_TYPE, JOB_STATE_CODE, JOB_STATE_DATE_TIME, JOB_RESULT_CODE, ID_CAMPAIGN, ID_AGENT, ID_GROUP, STATE_CALL, SUBSTATE_CALL, ID_TIME_ATT, ID_FECHA_ATT, ATT_STATE_CODE, ATT_RESULT_CODE, ID_CALL_TYPE, JOB_START_DATE, PKEY_ATTENDED_CUSTOMER, JOB_MAX_END_DATE, CUST_PRIMARY_ID, ID_OPPORTUNITY, ID_CONTACT, ID_ACCOUNT, JOB_PRIORITY, JOB_ORIGEN_CODE, JOB_REASON_CODE, JOB_SEQ, PREV_GROUP_CODE, PREV_USER_ID, ID_ENTITY_VALUE, ID_ENTITY_TYPE, PRODUCT_TYPE_ID, BRAND_ID, EXT_BRAND_ID, ATTR_1, RELATION_TYPE, STATUS, STATUS_DATE, CUST_TYPE_CODE, INTERNAL_ID, JOB_STATE_DATE, JOB_STATE_TIME, JOB_START_DATE_TIME, JOB_START_TIME, JOB_SUBREASON_CODE, PARENT_JOB_PKEY)
						SELECT	T1.PKEY AS PKEY_PHYSICAL_JOB,
							T1.PKEY_CUSTOMER AS ID_CUSTOMER,
							T1.JOB_TYPE_CODE AS ID_JOB_TYPE,
							T1.JOB_STATE_CODE,
							T1.JOB_STATE_DATE AS JOB_STATE_DATE_TIME,
							T1.JOB_RESULT_CODE,
							T1.PKEY_CAMPAIGN AS ID_CAMPAIGN,
							T1.USER_ID AS ID_AGENT,
							T1.ATT_GROUP_CODE AS ID_GROUP,
							@LS_NO_APLICA AS STATE_CALL,
							@LS_NO_APLICA AS SUBSTATE_CALL,
							CONVERT(VARCHAR, T1.JOB_STATE_DATE, 108) AS ID_TIME_ATT,
							CONVERT(VARCHAR, T1.JOB_STATE_DATE, 112) AS ID_FECHA_ATT,
							T1.ATT_STATE_CODE, -- LS_NO_APLICA
							T1.ATT_RESULT_CODE, -- LS_NO_APLICA
							T1.CALL_TYPE_CODE AS ID_CALL_TYPE,
							CONVERT(VARCHAR, T1.JOB_START_DATE, 112) AS JOB_START_DATE,
							T1.PKEY_ATTENDED_CUSTOMER,
							T1.JOB_MAX_END_DATE,
							T1.CUST_PRIMARY_ID,
							T1.PKEY_OPPORTUNITY AS ID_OPPORTUNITY,
							T1.PKEY_CONTACT AS ID_CONTACT,
							NULL AS ID_ACCOUNT,
							T1.JOB_PRIORITY,
							T1.JOB_ORIGEN_CODE,
							T1.JOB_REASON_CODE,
							T1.JOB_SEQ,
							T1.PREV_GROUP_CODE, -- LS_NO_APLICA
							T1.PREV_USER_ID, -- LS_NO_APLICA
							T1.PKEY_ENTITY_VALUE AS ID_ENTITY_VALUE,
							T1.PKEY_ENTITY_TYPE AS ID_ENTITY_TYPE,
							NULL AS PRODUCT_TYPE_ID,
							NULL AS BRAND_ID,
							NULL AS EXT_BRAND_ID,
							NULL AS ATTR_1,
							NULL AS RELATION_TYPE,
							NULL AS STATUS,
							NULL AS STATUS_DATE,
							NULL AS CUST_TYPE_CODE,
							NULL AS INTERNAL_ID,
							CONVERT(VARCHAR, T1.JOB_STATE_DATE, 112) AS JOB_STATE_DATE,
							CONVERT(VARCHAR, T1.JOB_STATE_DATE, 108) AS JOB_STATE_TIME,
							T1.JOB_START_DATE AS JOB_START_DATE_TIME,
							CONVERT(VARCHAR, T1.JOB_START_DATE, 108) AS JOB_START_TIME,
							T1.JOB_SUBREASON_CODE,
							T1.PARENT_JOB_PKEY
					--		T1.PKEY_ACCOUNT,
					--		T1.ORIGIN_IDR,
					--		T1.ORIGIN_DESC,
					--		T1.CAMPAIGN_IDR,
					--		T1.PROGRAMMED_IDR,
					--		T1.PROGRAMMED_DATE_TIME,
					--		T1.MEDIA_TYPE,
					--		T1.MEDIA_ID1,
					--		T1.MEDIA_ID2,
					--		T1.JOB_GROUP_CODE,
					--		T1.ATT_COMMENT,
					--		T1.ORDERBY,
					--		T1.DELETED_CODE,
					--		T1.ATTEMPTS,
					--		T1.TS_BEGIN,
					--		T1.TS_END,
					--		T1.TS_USER_ID,
					--		T1.ATT_STATE_DESC,
						FROM	PHYSICAL_JOB T1
						WHERE	(T1.PKEY = @LS_IDJOB)
							AND NOT EXISTS (
							SELECT	1
							FROM	DSS_TBPHYSICAL_JOB T2
							WHERE	(T2.PKEY_PHYSICAL_JOB = T1.PKEY)
							);
					SELECT @LSOPERA = 'INSERT', @LSTABLA = 'DSS_TBPHYSICAL_JOB', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
					IF (@LNERRORNUM <> 0) GOTO FALLO;
 
					-- INSERTA LOS REGISTROS CERRADOS EN DSS_TBATTENDED_CUSTOMER, MAPEANDO LOS CAMPOS DE LA MISMA FORMA QUE LO HACE ENGAGE.
					INSERT INTO	DSS_TBATTENDED_CUSTOMER (PKEY_ATTENDED_CUSTOMER, ID_CUSTOMER, ID_CALL_TYPE, ATT_STATE_CODE, ATT_STATE_DATE_TIME, ATT_RESULT_CODE, ID_CAMPAIGN, ID_AGENT, ID_GROUP, STATE_CALL, SUBSTATE_CALL, ID_TIME_ATT, ID_FECHA_ATT, ID_CAU_NOTCONTACT, COMMENTA, PKEY_PHYSICAL_JOB, ATT_MAX_END_DATE, MEDIA_ID1, PROGRAMMED_IDR, PROGRAMMED_DATE_TIME, TS_BEGIN, TS_END, TS_USER_ID)
						SELECT	T1.PKEY AS PKEY_ATTENDED_CUSTOMER,
							T1.PKEY_CUSTOMER AS ID_CUSTOMER,
							T1.CALL_TYPE_CODE AS ID_CALL_TYPE,
							T1.ATT_STATE_CODE,
							T1.ATT_STATE_DATE_TIME,
							ISNULL(NULLIF(LTRIM(RTRIM(T1.ATT_RESULT_CODE)), ''), @LS_NO_APLICA) AS ATT_RESULT_CODE,
							T1.PKEY_CAMPAIGN AS ID_CAMPAIGN,
							T1.USER_ID AS ID_AGENT,
							T1.GROUP_CODE AS ID_GROUP,
							@LS_NO_APLICA AS STATE_CALL,
							@LS_NO_APLICA AS SUBSTATE_CALL,
							CONVERT(VARCHAR, T1.ATT_STATE_DATE_TIME, 108) AS ID_TIME_ATT,
							CONVERT(VARCHAR, T1.ATT_STATE_DATE_TIME, 112) AS ID_FECHA_ATT,
							T1.REASON_CODE AS ID_CAU_NOTCONTACT,
							T1.ATT_COMMENT AS COMMENTA,
							T1.PKEY_JOB AS PKEY_PHYSICAL_JOB,
							T1.ATT_MAX_END_DATE,
							T1.MEDIA_ID1 AS MEDIA_ID1, -- NULL
							T1.PROGRAMMED_IDR AS PROGRAMMED_IDR, -- NULL
							T1.PROGRAMMED_DATE_TIME AS PROGRAMMED_DATE_TIME, -- NULL
							T1.TS_BEGIN, -- @LDINICIO_OPE
							T1.TS_END, -- @LDINICIO_OPE
							T1.TS_USER_ID -- T1.USER_ID
					--		T1.JOB_TYPE_CODE,
					--		T1.CUST_PRIMARY_ID,
					--		T1.PREV_USERID,
					--		T1.PREV_GROUPCODE,
						FROM	ATTENDED_CUSTOMER T1
						WHERE	(T1.PKEY_JOB = @LS_IDJOB)
							AND NOT EXISTS (
							SELECT	1
							FROM	DSS_TBATTENDED_CUSTOMER T2
							WHERE	(T2.PKEY_ATTENDED_CUSTOMER = T1.PKEY)
							);
					SELECT @LSOPERA = 'INSERT', @LSTABLA = 'DSS_TBATTENDED_CUSTOMER', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
					IF (@LNERRORNUM <> 0) GOTO FALLO;
 
					-- INSERTA LOS REGISTROS CERRADOS EN DSS_TBPHYSICAL_CALL, MAPEANDO LOS CAMPOS DE LA MISMA FORMA QUE LO HACE ENGAGE.
					INSERT INTO	DSS_TBPHYSICAL_CALL (PKEY_PHYSICAL_CALL, PKEY_ATTENDED_CUSTOMER, CALL_ID, CALL_DATE_TIME, CALL_DATE_TIME_END, ID_AGENT, ID_GROUP, PHYS_STATE_CODE, PHYS_RESULT_CODE, ANI, DNIS, IN_OUT_IDR, CALL_DATE, ID_FECHA, ID_TIME_PHYS, ID_DATE_END, ID_TIME_END, ID_RANGHOUR, DURACION_SEG, ID_CUSTOMER, ID_CAMPAIGN, ATT_RESULT_CODE, ATT_STATE_CODE, ID_CAU_NOTCONTACT, COMMENTA, PROGRAMMED_DATE_TIME, PKEY_PHYSICAL_JOB)
						SELECT	T1.PKEY AS PKEY_PHYSICAL_CALL,
							T1.PAR_KEY AS PKEY_ATTENDED_CUSTOMER,
							T2.CALL_TYPE_CODE AS CALL_ID, -- T1.CALL_ID
							T1.CALL_DATE_TIME,
							T1.CALL_DATE_TIME_END,
							T1.USER_ID AS ID_AGENT,
							T1.UNIT_CODE AS ID_GROUP,
							T1.PHYS_STATE_CODE,
							T1.PHYS_RESULT_CODE,
							T1.ANI,
							T1.DNIS,
							T1.IN_OUT_IDR,
							T1.CALL_DATE_TIME AS CALL_DATE,
							CONVERT(VARCHAR, T1.CALL_DATE_TIME, 112) AS ID_FECHA,
							CONVERT(VARCHAR, T1.CALL_DATE_TIME, 108) AS ID_TIME_PHYS,
							CONVERT(VARCHAR, T1.CALL_DATE_TIME_END, 112) AS ID_DATE_END,
							CONVERT(VARCHAR, T1.CALL_DATE_TIME_END, 108) AS ID_TIME_END,
							RIGHT('00' + CONVERT(VARCHAR, DATEPART(HOUR, T1.CALL_DATE_TIME)), 2) + '-' + RIGHT('00' + CONVERT(VARCHAR, DATEPART(HOUR, T1.CALL_DATE_TIME) + 1), 2) AS ID_RANGHOUR,
							0 AS DURACION_SEG,
							T1.PKEY_CUSTOMER AS ID_CUSTOMER,
							T2.PKEY_CAMPAIGN AS ID_CAMPAIGN,
							T2.ATT_RESULT_CODE,
							T2.ATT_STATE_CODE,
							T2.REASON_CODE AS ID_CAU_NOTCONTACT,
							T2.ATT_COMMENT AS COMMENTA,
							T2.PROGRAMMED_DATE_TIME AS PROGRAMMED_DATE_TIME, -- NULL
							T2.PKEY_JOB AS PKEY_PHYSICAL_JOB
					--		T1.MEDIA_ID1
					--		T1.SESSION_ID,
					--		T1.TS_BEGIN,
					--		T1.TS_END,
					--		T1.TS_USER_ID,
						FROM	PHYSICAL_CALL T1
							INNER JOIN ATTENDED_CUSTOMER T2 ON (T1.PAR_KEY = T2.PKEY)
						WHERE	(T2.PKEY_JOB = @LS_IDJOB)
							AND NOT EXISTS (
							SELECT	1
							FROM	DSS_TBPHYSICAL_CALL T3
							WHERE	(T3.PKEY_PHYSICAL_CALL = T1.PKEY)
							);
					SELECT @LSOPERA = 'INSERT', @LSTABLA = 'DSS_TBPHYSICAL_CALL', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
					IF (@LNERRORNUM <> 0) GOTO FALLO;
 
					-- INSERTA LOS REGISTROS CERRADOS EN DSS_TBPHYSICAL_CALL_CONV_STEPS, MAPEANDO LOS CAMPOS DE LA MISMA FORMA QUE LO HACE ENGAGE.
					INSERT INTO	DSS_TBPHYSICAL_CALL_CONV_STEPS (ID_CONV_STEPS, STEPS_SEQ, PKEY_CONV_STEP, NAVIGATION_IDR, PKEY_PHYSICAL_CALL)
						SELECT	T1.PKEY AS ID_CONV_STEPS,
							T1.STEPS_SEQ,
							T1.PKEY_CONV_STEP,
							T1.NAVIGATION_IDR,
							T1.PAR_KEY AS PKEY_PHYSICAL_CALL
					--		T1.STEP_TYPE_CODE,
					--		T1.TS_BEGIN,
					--		T1.TS_END,
					--		T1.TS_USER_ID,
					--		T1.PKEY_CALL_CONV
						FROM	PHYSICAL_CALL_CONV_STEPS T1
						WHERE	EXISTS (
							SELECT	1
							FROM	DSS_TBPHYSICAL_CALL T2
						 	WHERE	(T2.PKEY_PHYSICAL_CALL = T1.PAR_KEY)
								AND EXISTS (
								SELECT	1
								FROM	DSS_TBATTENDED_CUSTOMER T3
								WHERE	(T3.PKEY_ATTENDED_CUSTOMER = T2.PKEY_ATTENDED_CUSTOMER)
									AND (T3.PKEY_PHYSICAL_JOB = @LS_IDJOB)
								)
							)
							AND NOT EXISTS (
							SELECT	1
							FROM	DSS_TBPHYSICAL_CALL_CONV_STEPS T4
							WHERE	(T4.ID_CONV_STEPS = T1.PKEY)
							);
					SELECT @LSOPERA = 'INSERT', @LSTABLA = 'DSS_TBPHYSICAL_CALL_CONV_STEPS', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
					IF (@LNERRORNUM <> 0) GOTO FALLO;
 
					---- INSERTA LOS REGISTROS CERRADOS EN DSS_TBPHYS_CALL_ANSWERED_QUES, MAPEANDO LOS CAMPOS DE LA MISMA FORMA QUE LO HACE ENGAGE.
					--INSERT INTO	DSS_TBPHYS_CALL_ANSWERED_QUES (PKEY_PHYS_CALL_ANSWERED_QUES, ID_CONV_STEPS, PKEY_QUESTION, PKEY_ANSWER, ANSWER_DESCRIPTION)
					--	SELECT	T1.PKEY AS PKEY_PHYS_CALL_ANSWERED_QUES,
					--		T1.PAR_KEY AS ID_CONV_STEPS,
					--		T1.PKEY_QUESTION,
					--		T1.PKEY_ANSWER,
					--		T1.ANSWER_DESCRIPTION
					----		T1.TS_BEGIN,
					----		T1.TS_END,
					----		T1.TS_USER_ID
					--	FROM	PHYS_CALL_ANSWERED_QUESTIONS T1
					--	WHERE	EXISTS (
					--		SELECT	1
					--		FROM	DSS_TBPHYSICAL_CALL_CONV_STEPS T2
					--		WHERE	(T2.ID_CONV_STEPS = T1.PAR_KEY)
					--			AND EXISTS (
					--			SELECT	1
					--			FROM	DSS_TBPHYSICAL_CALL T3
					--	 		WHERE	(T3.PKEY_PHYSICAL_CALL = T2.PKEY_PHYSICAL_CALL)
					--				AND EXISTS (
					--				SELECT	1
					--				FROM	DSS_TBATTENDED_CUSTOMER T4
					--				WHERE	(T4.PKEY_ATTENDED_CUSTOMER = T3.PKEY_ATTENDED_CUSTOMER)
					--					AND (T4.PKEY_PHYSICAL_JOB = @LS_IDJOB)
					--				)
					--			)
					--		)
					--		AND NOT EXISTS (
					--		SELECT	1
					--		FROM	DSS_TBPHYS_CALL_ANSWERED_QUES T5
					--		WHERE	(T5.PKEY_PHYS_CALL_ANSWERED_QUES = T1.PKEY)
					--		);
					--SELECT @LSOPERA = 'INSERT', @LSTABLA = 'DSS_TBPHYS_CALL_ANSWERED_QUES', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
					--IF (@LNERRORNUM <> 0) GOTO FALLO;
				END;
 
				-- DETERMINA SI EXISTEN ACTIVIDADES PARA EL TRÁMITE ESPECIFICADO EN DSS_TBATTENDED_CUSTOMER.
				SELECT @LNCOUNT = COUNT(1) FROM DSS_TBATTENDED_CUSTOMER AC2 WHERE (AC2.PKEY_PHYSICAL_JOB = @LS_IDJOB);
 
				IF (@LNCOUNT > 0) BEGIN
					-- BUSCA LA UNIDAD Y EL USUARIO DE LA ÚLTIMA ACTIVIDAD DEL PROCESO, ENTRE OTROS DATOS, AMBOS HISTÓRICOS.
					SELECT	@LS_PKEY_ATTENDED_CUSTOMER = AC.PKEY_ATTENDED_CUSTOMER, @LS_UNIT_CODE = AC.ID_GROUP, @LS_USER_ID = AC.ID_AGENT
					FROM	DSS_TBATTENDED_CUSTOMER AC
					WHERE	AC.PKEY_ATTENDED_CUSTOMER = (SELECT TOP 1 AC2.PKEY_ATTENDED_CUSTOMER FROM DSS_TBATTENDED_CUSTOMER AC2 WHERE (AC2.PKEY_PHYSICAL_JOB = @LS_IDJOB) ORDER BY AC2.TS_BEGIN DESC);
 
					-- CIERRA EL REGISTRO DE LA HISTORIA DEL TRÁMITE.
					UPDATE	DSS_TBPHYSICAL_JOB
					SET	JOB_RESULT_CODE = @LS_IDESTADO,
						JOB_STATE_CODE = @LS_JOB_STATE_CODE,
						JOB_STATE_DATE_TIME = @LDINICIO_OPE,
						ATT_STATE_CODE = @LS_ATT_STATE_CODE,
						ATT_RESULT_CODE = @LS_IDESTADOATT,
						JOB_REASON_CODE = @LS_IDREASON,
						JOB_SUBREASON_CODE = @LS_IDSUBREASON,
						JOB_STATE_DATE = @LDFECHA_HASTA,
						JOB_STATE_TIME = @LSHORA_HASTA,
						PKEY_ATTENDED_CUSTOMER = @LS_PKEY_ATTENDED_CUSTOMER,
						ID_GROUP = @LS_UNIT_CODE,
						ID_AGENT = @LS_USER_ID
					--	TS_USER_ID = @LS_TS_USER_ID,
					--	TS_END = @LDINICIO_OPE
					WHERE	(PKEY_PHYSICAL_JOB = @LS_IDJOB);
					SELECT @LSOPERA = 'UPDATE', @LSTABLA = 'DSS_TBPHYSICAL_JOB', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
					IF (@LNERRORNUM <> 0) GOTO FALLO;
 
					-- CIERRA LOS REGISTROS DE LA HISTORIA DE LAS ATENCIONES DEL TRÁMITE.
					UPDATE	DSS_TBATTENDED_CUSTOMER
					SET	ATT_STATE_CODE = @LS_ATT_STATE_CODE,
						ATT_RESULT_CODE = @LS_IDESTADOATT,
						TS_USER_ID = @LS_TS_USER_ID,
						TS_END = @LDINICIO_OPE
					WHERE	(PKEY_PHYSICAL_JOB = @LS_IDJOB)
						AND (ATT_STATE_CODE <> @LS_ATT_STATE_CODE);
					SELECT @LSOPERA = 'UPDATE', @LSTABLA = 'DSS_TBATTENDED_CUSTOMER', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
					IF (@LNERRORNUM <> 0) GOTO FALLO;
 
					-- CIERRA LOS REGISTROS DE LA HISTORIA DE LAS LLAMADAS DE LAS ATENCIONES DEL TRÁMITE.
					UPDATE	DSS_TBPHYSICAL_CALL
					SET	PHYS_STATE_CODE = @LS_PHYS_STATE_CODE,
						PHYS_RESULT_CODE = @LS_PHYS_RESULT_CODE
					--	TS_USER_ID = @LS_TS_USER_ID,
					--	TS_END = @LDINICIO_OPE
					WHERE	(PHYS_STATE_CODE <> @LS_PHYS_STATE_CODE)
						AND EXISTS (
						SELECT	1
						FROM	DSS_TBATTENDED_CUSTOMER T1
						WHERE	(T1.PKEY_ATTENDED_CUSTOMER = DSS_TBPHYSICAL_CALL.PKEY_ATTENDED_CUSTOMER)
							AND (T1.PKEY_PHYSICAL_JOB = @LS_IDJOB)
						);
					SELECT @LSOPERA = 'UPDATE', @LSTABLA = 'DSS_TBPHYSICAL_CALL', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
					IF (@LNERRORNUM <> 0) GOTO FALLO;
 
					-- ELIMINA EL TRÁMITE ESPECIFICADO POR PARÁMETRO, CONSERVANDO LA HISTORIA DEL MISMO.
					EXECUTE @LNERRORNUM = PA_SYS_BORRAR_TRAMITE_POR_PKEY @PNTRAMITE_NRO = NULL, @PSPKEY = @LS_IDJOB, @PSCONSERVAR_DSS = 'S', @PS_RET_MESSAGE = @LS_RET_MESSAGE OUTPUT;
					SELECT @LSOPERA = 'EXECUTE', @LSTABLA = 'PA_SYS_BORRAR_TRAMITE_POR_PKEY', @LNFILAS_AFEC = @@ROWCOUNT;
					IF (@LNERRORNUM <> 0) GOTO FALLO;
				END
				ELSE BEGIN
					SET @LS_RET_MESSAGE = 'EL TRÁMITE ESPECIFICADO EN EL PARÁMETRO @PS_IDJOB NO EXISTE.';
				END;
			END
			ELSE BEGIN
				SET @LS_RET_MESSAGE = 'EL PARÁMETRO @PS_IDESTADOATT ES NULO.';
			END;
		END
		ELSE BEGIN
			SET @LS_RET_MESSAGE = 'EL PARÁMETRO @PS_IDREASON ES NULO.';
		END;
	END
	ELSE BEGIN
		SET @LS_RET_MESSAGE = 'EL PARÁMETRO @PS_IDESTADO ES NULO.';
	END;
END
ELSE BEGIN
	SET @LS_RET_MESSAGE = 'EL PARÁMETRO @PS_IDJOB ES NULO.';
END;
 
-- DEVUELVE EL MENSAJE DE ERROR. 'OK' SI NO HUBO.
SET @PS_RET_MESSAGE = @LS_RET_MESSAGE;
 
FALLO:
-- REGISTRO DE SUCESOS Y CONTROL DE FIN DE PROCEDIMIENTO. CONCLUYE LA TRANSACCIÓN SI TODO FUE EXITOSO.
SELECT @LNDURACION = DATEDIFF(SECOND, @LDINICIO_OPE, GETDATE()), @LNSEVERITY = ISNULL(EM.SEVERITY, 16), @LSERRORDESC = 'ERROR ' + CONVERT(VARCHAR, ISNULL(EM.ERROR, 0)) + ' - ' + ISNULL(EM.DESCRIPTION, ' ') FROM MASTER.DBO.SYSMESSAGES EM WHERE (EM.ERROR = @LNERRORNUM);
IF (@LNERRORNUM <> 0) BEGIN
	-- NOTIFICACIÓN EN EL REGISTRO DE SQL SERVER.
	SET @LSERRORLOG = @LSERRORLOG + CASE WHEN (ISNULL(CHARINDEX('%', @LSERRORDESC), 0) > 0) THEN RTRIM(LEFT(@LSERRORDESC, 11)) ELSE @LSERRORDESC END;
	-- DEVUELVE EL ERROR EN EL PARÁMETRO DE SALIDA.
	SET @PS_RET_MESSAGE = SUBSTRING(@LSERRORDESC, 1, 440);
	-- DESHACE LA TRANSACCIÓN COMPLETA SI LA OPERACIÓN FALLÓ.
	IF (@@TRANCOUNT > 0) ROLLBACK TRANSACTION;
	EXECUTE @LNERRORNUM = PA_SYS_REGISTRO_SUCESOS_INSERT @PSPROCEDIMIENTO_1 = @LSPROC, @PSTABLA_2 = @LSTABLA, @PNFILAS_AFECTADAS_3 = @LNFILAS_AFEC, @PSOPERACION_4 = @LSOPERA, @PNDURACION_5 = @LNDURACION, @PSRESULTADO_6 = @LSERRORDESC, @PSSQL_CMD_7 = @LSERRORDESC;
	-- RAISERROR(@LSERRORLOG, @LNSEVERITY, -1) WITH NOWAIT;
END
ELSE BEGIN
	EXECUTE @LNERRORNUM = PA_SYS_REGISTRO_SUCESOS_INSERT @PSPROCEDIMIENTO_1 = @LSPROC, @PSTABLA_2 = @LSTABLA, @PNFILAS_AFECTADAS_3 = @LNFILAS_AFEC, @PSOPERACION_4 = @LSOPERA, @PNDURACION_5 = @LNDURACION, @PSRESULTADO_6 = @LSERRORDESC, @PSSQL_CMD_7 = @LSERRORDESC;
	IF (@@TRANCOUNT > 0) COMMIT TRANSACTION;
END;
RETURN;
