CREATE   PROCEDURE [dbo].[M_CONFIG_ADD_USER]
(@IPKEYJOB	AS VARCHAR(100),
 @IUSERID	AS VARCHAR(100),
 @ORETCODE	AS INT OUTPUT)
AS
 
BEGIN	
 
	DECLARE @VUSUARIO_TMT	VARCHAR(50),
			@VNOMBRE_TMT	VARCHAR(100),
			@VEMAIL_TMT		VARCHAR(100),
			@VPASS_TMT		VARCHAR(100),
			@VESTADO_TMT	VARCHAR(50),
			@VESTADO_CODE	INT,
			@VPERFIL_TMT	VARCHAR(50),
			@CURRENT_PASS	VARCHAR(100),
			@VEXISTE		INT
 
	SELECT	@VUSUARIO_TMT	= ISNULL(NEW_ID,''),
			@VNOMBRE_TMT	= ISNULL(NEW_NAME,''),
			@VEMAIL_TMT		= ISNULL(NEW_EMAIL,''),
			@VPASS_TMT		= ISNULL(NEW_PASSWORD,''),
			@VESTADO_TMT	= ISNULL(NEW_ESTADO_CUENTA,''),
			@VPERFIL_TMT	= ISNULL(NEW_PERFIL,'')
	FROM	M_CONFIG 
	WHERE	PAR_KEY = @IPKEYJOB;
 
	SET @ORETCODE = 0
 
	IF (@VUSUARIO_TMT = '') BEGIN
		SET @ORETCODE = 1
		UPDATE	M_CONFIG
		SET		DESC_ERROR = 'Debe Completar el campo Usuario'
		WHERE	PAR_KEY = @IPKEYJOB;
		RETURN
	END ELSE BEGIN
		
		--VALIDO QUE NO EXISTA EL MISMO USUARIO
		SELECT	@VEXISTE = COUNT(1)
		FROM	Users
		WHERE	ID = LTRIM(RTRIM(@VUSUARIO_TMT))
 
		IF (@VEXISTE <> 0) BEGIN
			SET @ORETCODE = 1
			UPDATE	M_CONFIG
			SET		DESC_ERROR = 'El Usuario ingresado ya existe'
			WHERE	PAR_KEY = @IPKEYJOB;
			RETURN
		END
 
	END
 
	IF (@VNOMBRE_TMT = '') BEGIN
		SET @ORETCODE = 1
		UPDATE	M_CONFIG
		SET		DESC_ERROR = 'Debe Completar el campo Nombre y Apellido'
		WHERE	PAR_KEY = @IPKEYJOB;
		RETURN
	END ELSE BEGIN
		
		--VALIDO QUE NO EXISTA EL MISMO NOMBRE Y APELLIDO QUE OTRO USUARIO
		SELECT	@VEXISTE = COUNT(1)
		FROM	Users
		WHERE	Name = LTRIM(RTRIM(@VNOMBRE_TMT))
		AND		ID <> @VUSUARIO_TMT
 
		IF (@VEXISTE <> 0) BEGIN
			SET @ORETCODE = 1
			UPDATE	M_CONFIG
			SET		DESC_ERROR = 'Ya existe otro Usuario con el Nombre y Apellido ingresado'
			WHERE	PAR_KEY = @IPKEYJOB;
			RETURN
		END
	END
 
	IF (@VPASS_TMT = '') BEGIN
		SET @ORETCODE = 1
		UPDATE	M_CONFIG
		SET		DESC_ERROR = 'Debe Completar el campo Password'
		WHERE	PAR_KEY = @IPKEYJOB;
		RETURN
	END ELSE BEGIN
	
		SET @VPASS_TMT = CONVERT(VARCHAR(40), HashBytes('SHA1', upper(@VUSUARIO_TMT)+@VPASS_TMT), 2)
	END
 
	IF (@VPERFIL_TMT = '') BEGIN
		SET @ORETCODE = 1
		UPDATE	M_CONFIG
		SET		DESC_ERROR = 'Debe Completar el campo Perfil'
		WHERE	PAR_KEY = @IPKEYJOB;
		RETURN
	END
 
	IF (@VESTADO_TMT = '') BEGIN
		SET @ORETCODE = 1
		UPDATE	M_CONFIG
		SET		DESC_ERROR = 'Debe Completar el campo Estado'
		WHERE	PAR_KEY = @IPKEYJOB;
		RETURN
	END ELSE BEGIN
 
		SELECT @VESTADO_CODE=cast(attr1 as int) FROM CAT_DATA WHERE CAT_DATA_CODE = @VESTADO_TMT;
	END
 
	/* ====== Insert ====== */
	BEGIN TRANSACTION
 
		INSERT INTO Users
		(Id,Name,State,LoginFailure,Email,Phone,Avatar,Password,rowguid,ModifiedDate,CreationDate)
		values 
		(@VUSUARIO_TMT, @VNOMBRE_TMT, @VESTADO_CODE, 0, @VEMAIL_TMT, null, null,@VPASS_TMT, NEWID(), GETDATE(),GETDATE())
 
		INSERT INTO GroupsUserMembers values (@VPERFIL_TMT, UPPER(@VUSUARIO_TMT), NEWID(), GETDATE())
 
		DECLARE @VESTADO_DESC VARCHAR(300), @VPERFIL_DESC VARCHAR(300)
 
		SELECT	@VESTADO_DESC = ISNULL(CAT_DATA_DESC,'')
		FROM	CAT_DATA
		WHERE	PAR_KEY = '3ECEABE3-13FD-4779-ADE7-CDECF2EC3992'
		AND		CAT_DATA_CODE = @VESTADO_TMT
 
		SELECT	@VPERFIL_DESC = ISNULL(NAME,'')
		FROM	GROUPS
		WHERE	ID = @VPERFIL_TMT
 
		 --AGREGO INSERT PARA INGRESO AL MODULO DE SEGURIDAD
		 IF (@VPERFIL_TMT = 'SYS_ADM') BEGIN
			
			INSERT INTO RolesUserMembers
			SELECT 'root', @VUSUARIO_TMT, NEWID(), GETDATE()
 
		 END
 
	COMMIT TRANSACTION
	RETURN;
 
END
