CREATE PROCEDURE [dbo].[HOME_CMB_CONSULTOR_VIATICO]
(@IPKEYJOB	AS VARCHAR(100))
AS
 
DECLARE	@VID_AGENDA			VARCHAR(50),
		@VTIPO_CONSULTOR	VARCHAR(50),
		@VCONSULTOR			VARCHAR(100),
		@VOBSERVADOR		VARCHAR(400),
		@lstDato		varchar(100), 
		@lnuPosComa		int ,
		@VID			INT,
		@VALOR			VARCHAR(400),
		@VQUERY			VARCHAR(MAX)
		
BEGIN	
 
	SELECT	@VID_AGENDA = ISNULL(AGENDA_ID,''),
			@VTIPO_CONSULTOR = ISNULL(TIPO_CONSULTOR_PROV,'')
	FROM	XAGENDA
	WHERE	PAR_KEY = @IPKEYJOB
 
	--ME FIJO SI TENGO CONSULTOR Y/O OBSERVADOR EN LA AGENDA
	SELECT	@VCONSULTOR = ISNULL(ID_CONSULTOR,''),
			@VOBSERVADOR = ISNULL(OBSERVADOR,'')
	FROM	LK_AGENDA
	WHERE	ID_AGENDA = @VID_AGENDA
 
	SELECT * FROM [dbo].[FN_GET_CONSULTORES] (@VID_AGENDA)
	/*UNION ALL
	SELECT CAT_DATA_CODE,CASE WHEN CAT_DATA_CODE = 'SO' THEN '' ELSE CAT_DATA_DESC + ' (Observador)' END,TRUE FROM [dbo].[FN_GET_OBSERVADOR] (@VID_AGENDA)
 
	SELECT * FROM [dbo].[FN_GET_OBSERVADOR] (1)*/
 
	/*IF (@VTIPO_CONSULTOR = 'OBSERVADOR') BEGIN
	
		SELECT * FROM [dbo].[FN_GET_OBSERVADOR] (@VID_AGENDA)
	
	END ELSE IF (@VTIPO_CONSULTOR = 'CONSULTOR') BEGIN
		
		SELECT * FROM [dbo].[FN_GET_CONSULTORES] (@VID_AGENDA)
 
	END*/
	
END
 
