CREATE PROCEDURE SP_UPD_SALE_STS
	(@PKEY_JOB AS VARCHAR(100))
AS
BEGIN
	DECLARE @ERROR AS INT,
			@ROWCOUNT AS INT
 
	BEGIN TRAN
 
	UPDATE TMT WITH (ROWLOCK)
	SET TMT.SALE_STS = PJ.JOB_REASON_CODE
	FROM PHYSICAL_JOB AS PJ WITH (NOLOCK)
		INNER JOIN TMT_SEG_AP AS TMT
			ON PJ.PKEY = TMT.PAR_KEY
	WHERE PJ.PKEY = @PKEY_JOB
 
	SELECT @ERROR = @@ERROR, @ROWCOUNT = @@ROWCOUNT
 
	IF @ERROR = 0 AND @ROWCOUNT = 1 BEGIN
		UPDATE CUSTOMER WITH (ROWLOCK)
		SET TS_USER_ID = CASE WHEN TS_USER_ID IS NULL OR TS_USER_ID = '' THEN OWNER_UNIT_CODE ELSE TS_USER_ID END,
			OWNER_UNIT_CODE = 'CYB_AUDITORIA'
		WHERE CUST_PRIMARY_ID = (SELECT CUST_PRIMARY_ID
								FROM PHYSICAL_JOB WITH (NOLOCK)
								WHERE PKEY = @PKEY_JOB)
 
		SELECT @ERROR = @@ERROR, @ROWCOUNT = @@ROWCOUNT
	END 
 
	IF @ERROR = 0 AND @ROWCOUNT = 1 BEGIN
		IF @@TRANCOUNT > 0 COMMIT TRAN
	END
	ELSE BEGIN
		IF @@TRANCOUNT > 0 ROLLBACK TRAN
	END
END
RETURN
