CREATE PROCEDURE PA_SYS_VALIDACIONES_MD (@PS_TYPE VARCHAR(50), @PS_ORIGIN VARCHAR(10), @PS_PKEY VARCHAR(60), @PS_RET_MESSAGE VARCHAR(440) = NULL OUTPUT) AS
 
-- =========================================================================================================================
-- AUTOR: SERGIO MERINO - ENGAGE SOFTWARE COMPANY
-- FECHA DE CREACIÓN: 23/11/2010
-- EDITOR: TITO - ENGAGE SOFTWARE COMPANY
-- FECHA DE MODIFICACIÓN: 23/02/2011
-- TABLAS LEÍDAS:
-- TABLAS MODIFICADAS: NINGUNA.
-- DESCRIPCIÓN: REALIZA VALIDACIONES DE DEPENDENCIAS PARA UN METADATO QUE SE QUIERE ELIMINAR.
-- PARÁMETROS:
-- @PS_TYPE -> TIPO DE VALIDACIÓN DE DEPENDECIA QUE SE VA A REALIZAR.
-- @PS_ORIGIN -> NIVEL LÓGICO AL QUE PERTENECE EL TIPO DE VALIDACIÓN DE DEPENDECIA QUE SE VA A REALIZAR.
-- @PS_PKEY -> CLAVE DEL METADATO QUE SE DESEA ELIMINAR Y PARA EL CUAL SE REALIZAN VALIDACIONES DE DEPENDENCIAS.
-- @PS_RET_MESSAGE -> DEVUELVE EL MENSAJE DE ERROR. NULL SI NO HUBO.
-- CONSIDERACIONES: 
-- 1. REGISTRA SÓLO LOS ERRORES EN LA TABLA EDA_REGISTRO_SUCESOS.
-- =========================================================================================================================
 
SET NOCOUNT ON;
SET XACT_ABORT ON;
 
-- DECLARACIÓN E INICIALIZACIÓN DE VARIABLES DE ERROR Y AUXILIARES.
DECLARE @LNERRORNUM AS INTEGER,
	@LNSEVERITY AS SMALLINT,
	@LNFILAS_AFEC AS INTEGER,
	@LDINICIO_OPE AS DATETIME,
	@LNDURACION AS INTEGER,
	@LSOPERA AS VARCHAR(30),
	@LSPROC AS VARCHAR(30),
	@LSTABLA AS VARCHAR(30),
	@LSERRORLOG AS VARCHAR(440),
	@LSERRORDESC AS VARCHAR(440),
	@LSSQL_CMD AS VARCHAR(4000)
;
SELECT 	@LNERRORNUM = 0,
	@LNSEVERITY = 16,
	@LNFILAS_AFEC = 0,
	@LDINICIO_OPE = GETDATE(),
	@LNDURACION = 0,
	@LSOPERA = 'EXECUTE',
	@LSPROC = OBJECT_NAME(@@PROCID),
	@LSTABLA = 'NINGUNA',
	@LSERRORLOG = @@SERVERNAME + '.' + DB_NAME() + '.' + USER_NAME() + '.' + OBJECT_NAME(@@PROCID) + ' - ',
	@LSERRORDESC = NULL,
	@LSSQL_CMD = NULL
;
-- DECLARACIÓN DE VARIABLES DE USUARIO.
DECLARE
@LS_TYPE VARCHAR(50), 
@LS_ORIGIN VARCHAR(10), 
@LS_PKEY VARCHAR(60), 
@LS_RET_MESSAGE VARCHAR(440),
@LS_SQL_CUR VARCHAR(4000); -- @SQL VARCHAR(2000)
 
SELECT	@LS_TYPE = NULLIF(@PS_TYPE, ''),
	@LS_ORIGIN = NULLIF(@PS_ORIGIN, ''),
	@LS_PKEY = NULLIF(@PS_PKEY, ''),
	@LS_RET_MESSAGE = NULL,
	@LS_SQL_CUR = NULL;
 
BEGIN TRANSACTION
 
-- TODOS LOS PARÁMETROS DEBEN SER VÁLIDOS.
IF (@LS_TYPE IS NOT NULL) BEGIN
	IF (@LS_ORIGIN IS NOT NULL) BEGIN
		IF (@LS_PKEY IS NOT NULL) BEGIN
 
			-- CREA LA TABLA TEMPORAL PARA ALOJAR LOS VALORES INTERMEDIOS.
			CREATE TABLE #LO_TEMP_TABLE (DESCRIPTION VARCHAR(1000));
 
			-- AGREGA APÓSTROFOS A LA CLAVE DEL METADATO QUE SE DESEA ELIMINAR.
			SET @LS_PKEY = CHAR(39) + @LS_PKEY + CHAR(39);
 
			-- AGREGAR CONSULTAS DE CATEGORIAS.
			-- AGREGAR CONSULTAS DE ENTIDADES.
			-- AGREGAR CONSULTAS DE PROCEDIMIENTOS ALMACENADOS.
			-- AGREGAR CONSULTAS DE TRANSACCIONES.
			-- PRUEBA DE INSERCIÓN DE REGISTROS EN VARIABLE TABLA.
			-- SET @LS_SQL_CUR = 'SELECT CUST_TYPE_DESC FROM CUSTOMER_TYPE WHERE CUST_TYPE_CODE = ''GLOBAL''';
			-- INSERT INTO #LO_TEMP_TABLE EXECUTE (@LS_SQL_CUR);
 
			-- DEVUELVE EL CURSOR CON TODAS LAS VALIDACIONES REALIZADAS.
			SELECT	DESCRIPTION
			FROM	#LO_TEMP_TABLE;
 
			-- ELIMINA LA TABLA TEMPORAL.
			DROP TABLE #LO_TEMP_TABLE;
 
		END
		ELSE BEGIN
			SET @LS_RET_MESSAGE = 'EL PARÁMETRO @PS_TYPE ES NULO.';
		END;
	END
	ELSE BEGIN
		SET @LS_RET_MESSAGE = 'EL PARÁMETRO @PS_ORIGIN ES NULO.';
	END;
END
ELSE BEGIN
	SET @LS_RET_MESSAGE = 'EL PARÁMETRO @PS_PKEY ES NULO.';
END;
 
-- DEVUELVE EL MENSAJE DE ERROR. NULL SI NO HUBO.
SET @PS_RET_MESSAGE = @LS_RET_MESSAGE;
 
FALLO:
-- REGISTRO DE SUCESOS Y CONTROL DE FIN DE PROCEDIMIENTO. CONCLUYE LA TRANSACCIÓN SI TODO FUE EXITOSO.
SELECT @LNDURACION = DATEDIFF(SECOND, @LDINICIO_OPE, GETDATE()), @LNSEVERITY = ISNULL(EM.SEVERITY, 16), @LSERRORDESC = 'ERROR ' + CONVERT(VARCHAR, ISNULL(EM.ERROR, 0)) + ' - ' + ISNULL(EM.DESCRIPTION, ' ') FROM MASTER.DBO.SYSMESSAGES EM WHERE (EM.ERROR = @LNERRORNUM);
IF (@LNERRORNUM <> 0) BEGIN
	-- NOTIFICACIÓN EN EL REGISTRO DE SQL SERVER.
	SET @LSERRORLOG = @LSERRORLOG + CASE WHEN (ISNULL(CHARINDEX('%', @LSERRORDESC), 0) > 0) THEN RTRIM(LEFT(@LSERRORDESC, 11)) ELSE @LSERRORDESC END;
	-- DEVUELVE EL ERROR EN EL PARÁMETRO DE SALIDA.
	SET @PS_RET_MESSAGE = SUBSTRING(@LSERRORDESC, 1, 440);
	-- DESHACE LA TRANSACCIÓN COMPLETA SI LA OPERACIÓN FALLÓ.
	IF (@@TRANCOUNT > 0) ROLLBACK TRANSACTION;
	EXECUTE @LNERRORNUM = PA_SYS_REGISTRO_SUCESOS_INSERT @PSPROCEDIMIENTO_1 = @LSPROC, @PSTABLA_2 = @LSTABLA, @PNFILAS_AFECTADAS_3 = @LNFILAS_AFEC, @PSOPERACION_4 = @LSOPERA, @PNDURACION_5 = @LNDURACION, @PSRESULTADO_6 = @LSERRORDESC, @PSSQL_CMD_7 = @LSSQL_CMD;
	-- RAISERROR(@LSERRORLOG, @LNSEVERITY, -1) WITH NOWAIT;
END
ELSE BEGIN
	-- EXECUTE @LNERRORNUM = PA_SYS_REGISTRO_SUCESOS_INSERT @PSPROCEDIMIENTO_1 = @LSPROC, @PSTABLA_2 = @LSTABLA, @PNFILAS_AFECTADAS_3 = @LNFILAS_AFEC, @PSOPERACION_4 = @LSOPERA, @PNDURACION_5 = @LNDURACION, @PSRESULTADO_6 = @LSERRORDESC, @PSSQL_CMD_7 = @LSSQL_CMD;
	IF (@@TRANCOUNT > 0) COMMIT TRANSACTION;
END;
RETURN;
