CREATE PROCEDURE PA_SYS_DEPURAR_TABLAS_MD (@PS_EXEC_MODE VARCHAR(30) = 'LOG', @PDFECHA_DESDE DATETIME = NULL, @PDFECHA_HASTA DATETIME = NULL, @PS_RET_MESSAGE VARCHAR(440) = NULL OUTPUT) AS
 
-- =========================================================================================================================
-- AUTOR: CLAUDIO IRIGOYEN - ENGAGE SOFTWARE COMPANY
-- FECHA DE CREACIÓN: 30/10/2008
-- EDITOR: TITO - ENGAGE SOFTWARE COMPANY
-- FECHA DE EDICIÓN: 13/03/2009
-- TABLAS LEÍDAS:
-- TABLAS MODIFICADAS: ACTIVITY_TYPE, ALARM, ALARM_CHECKS, ALARM_POPUP_DETAIL, ALARM_TRANSACTIONS, ANSWER,
-- CALL_CONV_STRUCTURES, CALL_RESULT_TYPE, CALL_TYPE, CALL_TYPE_EMAIL, CAT_DATA, CAT_TYPE, CAT_TYPE_GROUP,
-- CONV_STRUCTURE_STEP_NORMAL, CONV_STRUCTURE_STEP_QUESTION, CONV_STRUCTURE_STEP_TRAN, CUSTOMER_DOCUMENTS,
-- CUSTOMER_DOCUMENTS_ATT, CUSTOMER_TYPE, DETAIL_FIELD, DETAIL_FILE, DETAIL_LABEL, DETAIL_SPREAD, ENTITY_BROWSER,
-- ENTITY_BROWSER_DETAIL, ENTITY_VIRTUAL_DETAIL, JOB_ACTIONS, JOB_DIAGRAM, JOB_DIAGRAM_MULT_INFLOWS_RULES, JOB_FLOW,
-- JOB_NEXTATT_RULES, JOB_NOTIF_BY_EVENT, JOB_NOTIF_BY_RULE, JOB_RESULT_TYPE, JOB_TYPE, NOT_CONTACT_REASONS, QUESTION,
-- SP_PRM_IN, SP_PRM_OUT, SP_PRM_OUT_VALUE, STEP_CHECKS, STEP_CHECKS_SP, STEP_NORMAL_FLOW, STEP_QUESTION_FLOW,
-- STEP_RESULTS, STEP_TRANSACTION_FLOW, STORED_PROCEDURES, TRAN_PRM_IN, TRAN_PRM_OUT, TRAN_PRM_VALUE, TRANSACTIONS.
-- DESCRIPCIÓN: PROCEDIMIENTO QUE DETECTA Y/O ELIMINA REGISTROS HUÉRFANOS EN LAS TABLAS QUE CONFORMAN LA METADATA DE ENGAGE.
-- CONSIDERACIONES:
-- 1. TIENE DOS MODOS DE EJECUCIÓN:
-- @PS_EXEC_MODE = 'LOG'. ES EL MODO PREDETERMINADO. REALIZA INSERCIONES EN LA TABLA EDA_REGISTRO_SUCESOS DETALLANDO LAS
-- INCONSISTENCIAS DETECTADAS. PROVEE LAS SENTENCIAS DE DELETE INDIVIDUALES PARA HACER DEPURACIONES MANUALES.
-- @PS_EXEC_MODE = 'ERASE'. BORRA LAS INCONSISTENCIAS DETECTADAS.
-- 2. AFECTA A TODAS LAS TABLAS UBICADAS EN EL TABLESPACE '[PRIMARY]', EXCEPTO LAS SIGUIENTES QUE YA NO SE USAN:
-- CAT_TYPE_DATA_REL, CHAT_MESSAGE, CHAT_STRUCTURES, CUSTOMER_TYPE_DATA_REL, DNIS, DNIS_CALL_TYPE, EMAILIN_MESSAGE,
-- EMAILIN_STRUCTURES, ENTITY_BROWSER_SUGER, JOB_ATTACHED_DATA, JOB_TYPE_DATA_REL, LINK, LINK_PRM, POPUP_BROWSER,
-- POPUP_BROWSER_DETAIL, SMS_MESSAGE, TEXT_MESSAGE.
-- 3. HAY TABLAS DE METADATA QUE NO SE DEPURAN:
-- COD_GEN, DATA_TYPE, PRM, SQL_SELECTS.
-- =========================================================================================================================
 
SET NOCOUNT ON;
SET XACT_ABORT ON;
 
-- DECLARACIÓN E INICIALIZACIÓN DE VARIABLES DE ERROR Y AUXILIARES.
DECLARE	@LNERRORNUM AS INTEGER,
	@LNSEVERITY AS SMALLINT,
	@LNFILAS_AFEC AS INTEGER,
	@LDINICIO_OPE AS DATETIME,
	@LNDURACION AS INTEGER,
	@LSOPERA AS VARCHAR(30),
	@LSPROC AS VARCHAR(30),
	@LSTABLA AS VARCHAR(30),
	@LSERRORLOG AS VARCHAR(440),
	@LSERRORDESC AS VARCHAR(440);
 
SELECT	@LNERRORNUM = 0,
	@LNSEVERITY = 16,
	@LNFILAS_AFEC = 0,
	@LDINICIO_OPE = GETDATE(),
	@LNDURACION = 0,
	@LSOPERA = 'EXECUTE',
	@LSPROC = OBJECT_NAME(@@PROCID),
	@LSTABLA = 'NINGUNA',
	@LSERRORLOG = @@SERVERNAME + '.' + DB_NAME() + '.' + USER_NAME() + '.' + OBJECT_NAME(@@PROCID) + ' - ',
	@LSERRORDESC = NULL;
 
-- DECLARA LAS VARIABLES.
DECLARE	@LS_EXEC_MODE AS VARCHAR(30),
	@LDFECHA_DESDE AS DATETIME,
	@LDFECHA_HASTA AS DATETIME,
	@LS_RET_MESSAGE AS VARCHAR(440),
	@LS_CLAVE AS VARCHAR(100),
	@LS_DATO AS VARCHAR(100),
	@LS_JERARQUIA AS VARCHAR(20),
	@LS_MD_ERROR_RH AS VARCHAR(440);
 
SELECT	@LS_EXEC_MODE = @PS_EXEC_MODE,
	@LDFECHA_DESDE = @PDFECHA_DESDE,
	@LDFECHA_HASTA = @PDFECHA_HASTA,
	@LS_RET_MESSAGE = @PS_RET_MESSAGE,
	@LS_CLAVE = NULL,
	@LS_DATO = NULL,
	@LS_JERARQUIA = NULL,
	@LS_MD_ERROR_RH = 'REGISTRO HUÉRFANO IDENTIFICADO CON';
 
-- DECLARO LA TRANSACCIÓN.
BEGIN TRANSACTION
 
IF (@LS_EXEC_MODE = 'LOG') BEGIN
 
	-- INICIO - SECCIÓN DE DEPURACIÓN DE LA JERARQUÍA DE TIPO DE CLIENTE.
 
	-- LA JERARQUÍA DE TIPO DE CLIENTE TIENE COMO TABLA RAÍZ O DE NIVEL CERO A CUSTOMER_TYPE.
	-- NOTA: SÓLO SE DEPURAN LAS TABLAS HIJAS DE CUSTOMER_TYPE, ES DECIR, LAS DE NIVEL 1 DENTRO DE LA JERARQUÍA,
	-- YA QUE LAS TABLAS DE NIVEL 2 Y POSTERIORES SE DEPURAN MÁS ADELANTE.
 
	-- INICIO DE DEPURACIÓN DE TABLAS DE TIPO DE CLIENTE DE NIVEL 1.
 
	SET @LS_JERARQUIA = 'CLIENTE';
 
	INSERT INTO	EDA_REGISTRO_SUCESOS (PROCEDIMIENTO, TABLA, FILAS_AFECTADAS, OPERACION, DURACION, RESULTADO, SQL_CMD)
		SELECT	@LSPROC AS PROCEDIMIENTO,
			'ACTIVITY_TYPE' AS TABLA,
			1 AS FILAS_AFECTADAS,
			@LS_EXEC_MODE AS OPERACION,
			0 AS DURACION,
			@LS_MD_ERROR_RH + ' PKEY = ' + CHAR(39) + PKEY + CHAR(39) + '.' AS RESULTADO,
			'DELETE FROM ACTIVITY_TYPE WHERE (PKEY = ' + CHAR(39) + PKEY + CHAR(39) + ')' AS SQL_CMD
		FROM	ACTIVITY_TYPE
		WHERE	(ACTIVITY_TYPE_CODE = @LS_JERARQUIA)
			AND PAR_KEY NOT IN (SELECT PKEY FROM CUSTOMER_TYPE);
	SELECT @LSOPERA = 'INSERT', @LSTABLA = 'EDA_REGISTRO_SUCESOS', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
 
	SET @LS_JERARQUIA = 'Cliente';
 
	INSERT INTO	EDA_REGISTRO_SUCESOS (PROCEDIMIENTO, TABLA, FILAS_AFECTADAS, OPERACION, DURACION, RESULTADO, SQL_CMD)
		SELECT	@LSPROC AS PROCEDIMIENTO,
			'ALARM' AS TABLA,
			1 AS FILAS_AFECTADAS,
			@LS_EXEC_MODE AS OPERACION,
			0 AS DURACION,
			@LS_MD_ERROR_RH + ' PKEY = ' + CHAR(39) + PKEY + CHAR(39) + '.' AS RESULTADO,
			'DELETE FROM ALARM WHERE (PKEY = ' + CHAR(39) + PKEY + CHAR(39) + ')' AS SQL_CMD
		FROM	ALARM
		WHERE	(ALARM_TYPE = @LS_JERARQUIA)
			AND ALARM_TYPE_CODE NOT IN (SELECT CUST_TYPE_CODE FROM CUSTOMER_TYPE);
	SELECT @LSOPERA = 'INSERT', @LSTABLA = 'EDA_REGISTRO_SUCESOS', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
 
	INSERT INTO	EDA_REGISTRO_SUCESOS (PROCEDIMIENTO, TABLA, FILAS_AFECTADAS, OPERACION, DURACION, RESULTADO, SQL_CMD)
		SELECT	@LSPROC AS PROCEDIMIENTO,
			'ENTITY_BROWSER' AS TABLA,
			1 AS FILAS_AFECTADAS,
			@LS_EXEC_MODE AS OPERACION,
			0 AS DURACION,
			@LS_MD_ERROR_RH + ' PKEY = ' + CHAR(39) + PKEY + CHAR(39) + '.' AS RESULTADO,
			'DELETE FROM ENTITY_BROWSER WHERE (PKEY = ' + CHAR(39) + PKEY + CHAR(39) + ')' AS SQL_CMD
		FROM	ENTITY_BROWSER
		WHERE	(ENTITY_TYPE = @LS_JERARQUIA)
			AND PAR_KEY NOT IN (SELECT PKEY FROM CUSTOMER_TYPE)
			AND (ENTITY_LEVEL = 1);
	SELECT @LSOPERA = 'INSERT', @LSTABLA = 'EDA_REGISTRO_SUCESOS', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
 
	INSERT INTO	EDA_REGISTRO_SUCESOS (PROCEDIMIENTO, TABLA, FILAS_AFECTADAS, OPERACION, DURACION, RESULTADO, SQL_CMD)
		SELECT	@LSPROC AS PROCEDIMIENTO,
			'JOB_TYPE' AS TABLA,
			1 AS FILAS_AFECTADAS,
			@LS_EXEC_MODE AS OPERACION,
			0 AS DURACION,
			@LS_MD_ERROR_RH + ' PKEY = ' + CHAR(39) + PKEY + CHAR(39) + '.' AS RESULTADO,
			'DELETE FROM JOB_TYPE WHERE (PKEY = ' + CHAR(39) + PKEY + CHAR(39) + ')' AS SQL_CMD
		FROM	JOB_TYPE
		WHERE	CUST_TYPE_CODE NOT IN (SELECT CUST_TYPE_CODE FROM CUSTOMER_TYPE);
	SELECT @LSOPERA = 'INSERT', @LSTABLA = 'EDA_REGISTRO_SUCESOS', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
 
	INSERT INTO	EDA_REGISTRO_SUCESOS (PROCEDIMIENTO, TABLA, FILAS_AFECTADAS, OPERACION, DURACION, RESULTADO, SQL_CMD)
		SELECT	@LSPROC AS PROCEDIMIENTO,
			'STORED_PROCEDURES' AS TABLA,
			1 AS FILAS_AFECTADAS,
			@LS_EXEC_MODE AS OPERACION,
			0 AS DURACION,
			@LS_MD_ERROR_RH + ' PKEY = ' + CHAR(39) + PKEY + CHAR(39) + '.' AS RESULTADO,
			'DELETE FROM STORED_PROCEDURES WHERE (PKEY = ' + CHAR(39) + PKEY + CHAR(39) + ')' AS SQL_CMD
		FROM	STORED_PROCEDURES
		WHERE	(SP_TYPE_IDR = @LS_JERARQUIA)
			AND SP_TYPE_CODE NOT IN (SELECT CUST_TYPE_CODE FROM CUSTOMER_TYPE);
	SELECT @LSOPERA = 'INSERT', @LSTABLA = 'EDA_REGISTRO_SUCESOS', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
 
	INSERT INTO	EDA_REGISTRO_SUCESOS (PROCEDIMIENTO, TABLA, FILAS_AFECTADAS, OPERACION, DURACION, RESULTADO, SQL_CMD)
		SELECT	@LSPROC AS PROCEDIMIENTO,
			'TRANSACTIONS' AS TABLA,
			1 AS FILAS_AFECTADAS,
			@LS_EXEC_MODE AS OPERACION,
			0 AS DURACION,
			@LS_MD_ERROR_RH + ' PKEY = ' + CHAR(39) + PKEY + CHAR(39) + '.' AS RESULTADO,
			'DELETE FROM TRANSACTIONS WHERE (PKEY = ' + CHAR(39) + PKEY + CHAR(39) + ')' AS SQL_CMD
		FROM	TRANSACTIONS
		WHERE	(TRAN_IDR = @LS_JERARQUIA)
			AND CALL_TYPE_CODE NOT IN (SELECT CUST_TYPE_CODE FROM CUSTOMER_TYPE);
	SELECT @LSOPERA = 'INSERT', @LSTABLA = 'EDA_REGISTRO_SUCESOS', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
 
	-- FIN DE DEPURACIÓN DE TABLAS DE TIPO DE CLIENTE DE NIVEL 1.
 
	-- INICIO DE DEPURACIÓN DE TABLAS DE TIPO DE CLIENTE DE NIVEL 2.
 
	-- LA DEPURACIÓN DE LAS SIGUIENTES TABLAS SE REALIZA POSTERIORMENTE EN LAS OTRAS JERARQUÍAS,
	-- CON EL FIN DE EVITAR I/O POR REPETICIÓN DE LAS MISMAS OPERACIONES.
	-- ALARM_CHECKS
	-- ALARM_POPUP_DETAIL
	-- ALARM_TRANSACTIONS
	-- ENTITY_BROWSER
	-- ENTITY_BROWSER_DETAIL
	-- ENTITY_VIRTUAL_DETAIL
	-- SP_PRM_IN
	-- SP_PRM_OUT
	-- TRAN_PRM_IN
	-- TRAN_PRM_OUT
 
	-- FIN DE DEPURACIÓN DE TABLAS DE TIPO DE CLIENTE DE NIVEL 2.
 
	-- INICIO DE DEPURACIÓN DE TABLAS DE TIPO DE CLIENTE DE NIVEL 3.
 
	-- LA DEPURACIÓN DE LAS SIGUIENTES TABLAS SE REALIZA POSTERIORMENTE EN LAS OTRAS JERARQUÍAS,
	-- CON EL FIN DE EVITAR I/O POR REPETICIÓN DE LAS MISMAS OPERACIONES.
	-- SP_PRM_OUT_VALUE
	-- TRAN_PRM_VALUE
 
	-- FIN DE DEPURACIÓN DE TABLAS DE TIPO DE CLIENTE DE NIVEL 3.
 
	-- FIN - SECCIÓN DE DEPURACIÓN DE LA JERARQUÍA DE TIPO DE CLIENTE.
 
	-- INICIO - SECCIÓN DE DEPURACIÓN DE LA JERARQUÍA DE TIPO DE PROCESO.
 
	-- LA JERARQUÍA DE TIPO DE PROCESO TIENE COMO TABLA RAÍZ O DE NIVEL CERO A JOB_TYPE.
	-- NOTA: EN PRIMER LUGAR, SE DEPURAN LAS TABLAS HIJAS DE JOB_TYPE, ES DECIR, LAS DE NIVEL 1 DENTRO DE LA JERARQUÍA Y,
	-- LUEGO, LAS TABLAS DE NIVEL 2 Y POSTERIORES.
 
	-- INICIO DE DEPURACIÓN DE TABLAS DE TIPO DE PROCESO DE NIVEL 1.
 
	SET @LS_JERARQUIA = 'TRAMITE';
 
	INSERT INTO	EDA_REGISTRO_SUCESOS (PROCEDIMIENTO, TABLA, FILAS_AFECTADAS, OPERACION, DURACION, RESULTADO, SQL_CMD)
		SELECT	@LSPROC AS PROCEDIMIENTO,
			'ACTIVITY_TYPE' AS TABLA,
			1 AS FILAS_AFECTADAS,
			@LS_EXEC_MODE AS OPERACION,
			0 AS DURACION,
			@LS_MD_ERROR_RH + ' PKEY = ' + CHAR(39) + PKEY + CHAR(39) + '.' AS RESULTADO,
			'DELETE FROM ACTIVITY_TYPE WHERE (PKEY = ' + CHAR(39) + PKEY + CHAR(39) + ')' AS SQL_CMD
		FROM	ACTIVITY_TYPE
		WHERE	(ACTIVITY_TYPE_CODE = @LS_JERARQUIA)
			AND PAR_KEY NOT IN (SELECT PKEY FROM JOB_TYPE);
	SELECT @LSOPERA = 'INSERT', @LSTABLA = 'EDA_REGISTRO_SUCESOS', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
 
	SET @LS_JERARQUIA = 'Tramite';
	
	INSERT INTO	EDA_REGISTRO_SUCESOS (PROCEDIMIENTO, TABLA, FILAS_AFECTADAS, OPERACION, DURACION, RESULTADO, SQL_CMD)
		SELECT	@LSPROC AS PROCEDIMIENTO,
			'ALARM' AS TABLA,
			1 AS FILAS_AFECTADAS,
			@LS_EXEC_MODE AS OPERACION,
			0 AS DURACION,
			@LS_MD_ERROR_RH + ' PKEY = ' + CHAR(39) + PKEY + CHAR(39) + '.' AS RESULTADO,
			'DELETE FROM ALARM WHERE (PKEY = ' + CHAR(39) + PKEY + CHAR(39) + ')' AS SQL_CMD
		FROM	ALARM
		WHERE	(ALARM_TYPE = @LS_JERARQUIA)
			AND ALARM_TYPE_CODE NOT IN (SELECT JOB_TYPE_CODE FROM JOB_TYPE);
	SELECT @LSOPERA = 'INSERT', @LSTABLA = 'EDA_REGISTRO_SUCESOS', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
	
	INSERT INTO	EDA_REGISTRO_SUCESOS (PROCEDIMIENTO, TABLA, FILAS_AFECTADAS, OPERACION, DURACION, RESULTADO, SQL_CMD)
		SELECT	@LSPROC AS PROCEDIMIENTO,
			'CALL_TYPE' AS TABLA,
			1 AS FILAS_AFECTADAS,
			@LS_EXEC_MODE AS OPERACION,
			0 AS DURACION,
			@LS_MD_ERROR_RH + ' PKEY = ' + CHAR(39) + PKEY + CHAR(39) + '.' AS RESULTADO,
			'DELETE FROM CALL_TYPE WHERE (PKEY = ' + CHAR(39) + PKEY + CHAR(39) + ')' AS SQL_CMD
		FROM	CALL_TYPE
		WHERE	PAR_KEY NOT IN (SELECT PKEY FROM JOB_TYPE);
	SELECT @LSOPERA = 'INSERT', @LSTABLA = 'EDA_REGISTRO_SUCESOS', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
	
	INSERT INTO	EDA_REGISTRO_SUCESOS (PROCEDIMIENTO, TABLA, FILAS_AFECTADAS, OPERACION, DURACION, RESULTADO, SQL_CMD)
		SELECT	@LSPROC AS PROCEDIMIENTO,
			'ENTITY_BROWSER' AS TABLA,
			1 AS FILAS_AFECTADAS,
			@LS_EXEC_MODE AS OPERACION,
			0 AS DURACION,
			@LS_MD_ERROR_RH + ' PKEY = ' + CHAR(39) + PKEY + CHAR(39) + '.' AS RESULTADO,
			'DELETE FROM ENTITY_BROWSER WHERE (PKEY = ' + CHAR(39) + PKEY + CHAR(39) + ')' AS SQL_CMD
		FROM	ENTITY_BROWSER
		WHERE	(ENTITY_TYPE = @LS_JERARQUIA)
			AND PAR_KEY NOT IN (SELECT PKEY FROM JOB_TYPE)
			AND (ENTITY_LEVEL = 1);
	SELECT @LSOPERA = 'INSERT', @LSTABLA = 'EDA_REGISTRO_SUCESOS', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
	
	INSERT INTO	EDA_REGISTRO_SUCESOS (PROCEDIMIENTO, TABLA, FILAS_AFECTADAS, OPERACION, DURACION, RESULTADO, SQL_CMD)
		SELECT	@LSPROC AS PROCEDIMIENTO,
			'JOB_DIAGRAM' AS TABLA,
			1 AS FILAS_AFECTADAS,
			@LS_EXEC_MODE AS OPERACION,
			0 AS DURACION,
			@LS_MD_ERROR_RH + ' PKEY = ' + CHAR(39) + PKEY + CHAR(39) + '.' AS RESULTADO,
			'DELETE FROM JOB_DIAGRAM WHERE (PKEY = ' + CHAR(39) + PKEY + CHAR(39) + ')' AS SQL_CMD
		FROM	JOB_DIAGRAM
		WHERE	PAR_KEY NOT IN (SELECT PKEY FROM JOB_TYPE);
	SELECT @LSOPERA = 'INSERT', @LSTABLA = 'EDA_REGISTRO_SUCESOS', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
	
	INSERT INTO	EDA_REGISTRO_SUCESOS (PROCEDIMIENTO, TABLA, FILAS_AFECTADAS, OPERACION, DURACION, RESULTADO, SQL_CMD)
		SELECT	@LSPROC AS PROCEDIMIENTO,
			'JOB_NOTIF_BY_EVENT' AS TABLA,
			1 AS FILAS_AFECTADAS,
			@LS_EXEC_MODE AS OPERACION,
			0 AS DURACION,
			@LS_MD_ERROR_RH + ' PKEY = ' + CHAR(39) + PKEY + CHAR(39) + '.' AS RESULTADO,
			'DELETE FROM JOB_NOTIF_BY_EVENT WHERE (PKEY = ' + CHAR(39) + PKEY + CHAR(39) + ')' AS SQL_CMD
		FROM	JOB_NOTIF_BY_EVENT
		WHERE	PAR_KEY NOT IN (SELECT PKEY FROM JOB_TYPE);
	SELECT @LSOPERA = 'INSERT', @LSTABLA = 'EDA_REGISTRO_SUCESOS', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
 
	INSERT INTO	EDA_REGISTRO_SUCESOS (PROCEDIMIENTO, TABLA, FILAS_AFECTADAS, OPERACION, DURACION, RESULTADO, SQL_CMD)
		SELECT	@LSPROC AS PROCEDIMIENTO,
			'JOB_NOTIF_BY_RULE' AS TABLA,
			1 AS FILAS_AFECTADAS,
			@LS_EXEC_MODE AS OPERACION,
			0 AS DURACION,
			@LS_MD_ERROR_RH + ' PKEY = ' + CHAR(39) + PKEY + CHAR(39) + '.' AS RESULTADO,
			'DELETE FROM JOB_NOTIF_BY_RULE WHERE (PKEY = ' + CHAR(39) + PKEY + CHAR(39) + ')' AS SQL_CMD
		FROM	JOB_NOTIF_BY_RULE
		WHERE	PAR_KEY NOT IN (SELECT PKEY FROM JOB_TYPE);
	SELECT @LSOPERA = 'INSERT', @LSTABLA = 'EDA_REGISTRO_SUCESOS', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
 
	INSERT INTO	EDA_REGISTRO_SUCESOS (PROCEDIMIENTO, TABLA, FILAS_AFECTADAS, OPERACION, DURACION, RESULTADO, SQL_CMD)
		SELECT	@LSPROC AS PROCEDIMIENTO,
			'JOB_RESULT_TYPE' AS TABLA,
			1 AS FILAS_AFECTADAS,
			@LS_EXEC_MODE AS OPERACION,
			0 AS DURACION,
			@LS_MD_ERROR_RH + ' PKEY = ' + CHAR(39) + PKEY + CHAR(39) + '.' AS RESULTADO,
			'DELETE FROM JOB_RESULT_TYPE WHERE (PKEY = ' + CHAR(39) + PKEY + CHAR(39) + ')' AS SQL_CMD
		FROM	JOB_RESULT_TYPE
		WHERE	PAR_KEY NOT IN (SELECT PKEY FROM JOB_TYPE);
	SELECT @LSOPERA = 'INSERT', @LSTABLA = 'EDA_REGISTRO_SUCESOS', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
 
	INSERT INTO	EDA_REGISTRO_SUCESOS (PROCEDIMIENTO, TABLA, FILAS_AFECTADAS, OPERACION, DURACION, RESULTADO, SQL_CMD)
		SELECT	@LSPROC AS PROCEDIMIENTO,
			'STORED_PROCEDURES' AS TABLA,
			1 AS FILAS_AFECTADAS,
			@LS_EXEC_MODE AS OPERACION,
			0 AS DURACION,
			@LS_MD_ERROR_RH + ' PKEY = ' + CHAR(39) + PKEY + CHAR(39) + '.' AS RESULTADO,
			'DELETE FROM STORED_PROCEDURES WHERE (PKEY = ' + CHAR(39) + PKEY + CHAR(39) + ')' AS SQL_CMD
		FROM	STORED_PROCEDURES
		WHERE	(SP_TYPE_IDR = @LS_JERARQUIA)
			AND SP_TYPE_CODE NOT IN (SELECT JOB_TYPE_CODE FROM JOB_TYPE);
	SELECT @LSOPERA = 'INSERT', @LSTABLA = 'EDA_REGISTRO_SUCESOS', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
 
	INSERT INTO	EDA_REGISTRO_SUCESOS (PROCEDIMIENTO, TABLA, FILAS_AFECTADAS, OPERACION, DURACION, RESULTADO, SQL_CMD)
		SELECT	@LSPROC AS PROCEDIMIENTO,
			'TRANSACTIONS' AS TABLA,
			1 AS FILAS_AFECTADAS,
			@LS_EXEC_MODE AS OPERACION,
			0 AS DURACION,
			@LS_MD_ERROR_RH + ' PKEY = ' + CHAR(39) + PKEY + CHAR(39) + '.' AS RESULTADO,
			'DELETE FROM TRANSACTIONS WHERE (PKEY = ' + CHAR(39) + PKEY + CHAR(39) + ')' AS SQL_CMD
		FROM	TRANSACTIONS
		WHERE	(TRAN_IDR = @LS_JERARQUIA)
			AND CALL_TYPE_CODE NOT IN (SELECT JOB_TYPE_CODE FROM JOB_TYPE);
	SELECT @LSOPERA = 'INSERT', @LSTABLA = 'EDA_REGISTRO_SUCESOS', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
 
	-- FIN DE DEPURACIÓN DE TABLAS DE TIPO DE PROCESO DE NIVEL 1.
 
	-- INICIO DE DEPURACIÓN DE TABLAS DE TIPO DE PROCESO DE NIVEL 2.
 
	INSERT INTO	EDA_REGISTRO_SUCESOS (PROCEDIMIENTO, TABLA, FILAS_AFECTADAS, OPERACION, DURACION, RESULTADO, SQL_CMD)
		SELECT	@LSPROC AS PROCEDIMIENTO,
			'ENTITY_BROWSER' AS TABLA,
			1 AS FILAS_AFECTADAS,
			@LS_EXEC_MODE AS OPERACION,
			0 AS DURACION,
			@LS_MD_ERROR_RH + ' PKEY = ' + CHAR(39) + PKEY + CHAR(39) + '.' AS RESULTADO,
			'DELETE FROM ENTITY_BROWSER WHERE (PKEY = ' + CHAR(39) + PKEY + CHAR(39) + ')' AS SQL_CMD
		FROM	ENTITY_BROWSER
		WHERE	(ENTITY_LEVEL > 1)
			AND PAR_KEY NOT IN (SELECT PKEY FROM ENTITY_BROWSER);
	SELECT @LSOPERA = 'INSERT', @LSTABLA = 'EDA_REGISTRO_SUCESOS', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
 
	INSERT INTO	EDA_REGISTRO_SUCESOS (PROCEDIMIENTO, TABLA, FILAS_AFECTADAS, OPERACION, DURACION, RESULTADO, SQL_CMD)
		SELECT	@LSPROC AS PROCEDIMIENTO,
			'ENTITY_BROWSER_DETAIL' AS TABLA,
			1 AS FILAS_AFECTADAS,
			@LS_EXEC_MODE AS OPERACION,
			0 AS DURACION,
			@LS_MD_ERROR_RH + ' PKEY = ' + CHAR(39) + PKEY + CHAR(39) + '.' AS RESULTADO,
			'DELETE FROM ENTITY_BROWSER_DETAIL WHERE (PKEY = ' + CHAR(39) + PKEY + CHAR(39) + ')' AS SQL_CMD
		FROM	ENTITY_BROWSER_DETAIL
		WHERE	PAR_KEY NOT IN (SELECT PKEY FROM ENTITY_BROWSER);
	SELECT @LSOPERA = 'INSERT', @LSTABLA = 'EDA_REGISTRO_SUCESOS', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
 
	INSERT INTO	EDA_REGISTRO_SUCESOS (PROCEDIMIENTO, TABLA, FILAS_AFECTADAS, OPERACION, DURACION, RESULTADO, SQL_CMD)
		SELECT	@LSPROC AS PROCEDIMIENTO,
			'ENTITY_VIRTUAL_DETAIL' AS TABLA,
			1 AS FILAS_AFECTADAS,
			@LS_EXEC_MODE AS OPERACION,
			0 AS DURACION,
			@LS_MD_ERROR_RH + ' PKEY = ' + CHAR(39) + PKEY + CHAR(39) + '.' AS RESULTADO,
			'DELETE FROM ENTITY_VIRTUAL_DETAIL WHERE (PKEY = ' + CHAR(39) + PKEY + CHAR(39) + ')' AS SQL_CMD
		FROM	ENTITY_VIRTUAL_DETAIL
		WHERE	PAR_KEY NOT IN (SELECT PKEY FROM ENTITY_BROWSER);
	SELECT @LSOPERA = 'INSERT', @LSTABLA = 'EDA_REGISTRO_SUCESOS', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
 
	INSERT INTO	EDA_REGISTRO_SUCESOS (PROCEDIMIENTO, TABLA, FILAS_AFECTADAS, OPERACION, DURACION, RESULTADO, SQL_CMD)
		SELECT	@LSPROC AS PROCEDIMIENTO,
			'JOB_FLOW' AS TABLA,
			1 AS FILAS_AFECTADAS,
			@LS_EXEC_MODE AS OPERACION,
			0 AS DURACION,
			@LS_MD_ERROR_RH + ' PKEY = ' + CHAR(39) + PKEY + CHAR(39) + '.' AS RESULTADO,
			'DELETE FROM JOB_FLOW WHERE (PKEY = ' + CHAR(39) + PKEY + CHAR(39) + ')' AS SQL_CMD
		FROM	JOB_FLOW
		WHERE	PAR_KEY NOT IN (SELECT PKEY FROM JOB_DIAGRAM);
	SELECT @LSOPERA = 'INSERT', @LSTABLA = 'EDA_REGISTRO_SUCESOS', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
 
	INSERT INTO	EDA_REGISTRO_SUCESOS (PROCEDIMIENTO, TABLA, FILAS_AFECTADAS, OPERACION, DURACION, RESULTADO, SQL_CMD)
		SELECT	@LSPROC AS PROCEDIMIENTO,
			'JOB_NEXTATT_RULES' AS TABLA,
			1 AS FILAS_AFECTADAS,
			@LS_EXEC_MODE AS OPERACION,
			0 AS DURACION,
			@LS_MD_ERROR_RH + ' PKEY = ' + CHAR(39) + PKEY + CHAR(39) + '.' AS RESULTADO,
			'DELETE FROM JOB_NEXTATT_RULES WHERE (PKEY = ' + CHAR(39) + PKEY + CHAR(39) + ')' AS SQL_CMD
		FROM	JOB_NEXTATT_RULES
		WHERE	PAR_KEY NOT IN (SELECT PKEY FROM JOB_DIAGRAM);
	SELECT @LSOPERA = 'INSERT', @LSTABLA = 'EDA_REGISTRO_SUCESOS', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
 
	-- LA DEPURACIÓN DE LAS SIGUIENTES TABLAS SE REALIZA POSTERIORMENTE EN LAS OTRAS JERARQUÍAS,
	-- CON EL FIN DE EVITAR I/O POR REPETICIÓN DE LAS MISMAS OPERACIONES.
	-- ALARM_CHECKS
	-- ALARM_POPUP_DETAIL
	-- ALARM_TRANSACTIONS
	-- SP_PRM_IN
	-- SP_PRM_OUT
	-- TRAN_PRM_IN
	-- TRAN_PRM_OUT
 
	-- FIN DE DEPURACIÓN DE TABLAS DE TIPO DE PROCESO DE NIVEL 2.
 
	-- INICIO DE DEPURACIÓN DE TABLAS DE TIPO DE PROCESO DE NIVEL 3.
 
	-- LA DEPURACIÓN DE LAS SIGUIENTES TABLAS SE REALIZA POSTERIORMENTE EN LAS OTRAS JERARQUÍAS,
	-- CON EL FIN DE EVITAR I/O POR REPETICIÓN DE LAS MISMAS OPERACIONES.
	-- SP_PRM_OUT_VALUE
	-- TRAN_PRM_VALUE
 
	-- FIN DE DEPURACIÓN DE TABLAS DE TIPO DE PROCESO DE NIVEL 3.
 
	-- FIN - SECCIÓN DE DEPURACIÓN DE LA JERARQUÍA DE TIPO DE PROCESO.
 
	-- INICIO - SECCIÓN DE DEPURACIÓN DE LA JERARQUÍA DE TIPO DE ACTIVIDAD.
 
	-- LA JERARQUÍA DE TIPO DE ACTIVIDAD TIENE COMO TABLA RAÍZ O DE NIVEL CERO A CALL_TYPE.
	-- NOTA: EN PRIMER LUGAR, SE DEPURAN LAS TABLAS HIJAS DE CALL_TYPE, ES DECIR, LAS DE NIVEL 1 DENTRO DE LA JERARQUÍA Y,
	-- LUEGO, LAS TABLAS DE NIVEL 2 Y POSTERIORES.
 
	-- INICIO DE DEPURACIÓN DE TABLAS DE TIPO DE ACTIVIDAD DE NIVEL 1.
 
	SET @LS_JERARQUIA = 'Atencion';
 
	INSERT INTO	EDA_REGISTRO_SUCESOS (PROCEDIMIENTO, TABLA, FILAS_AFECTADAS, OPERACION, DURACION, RESULTADO, SQL_CMD)
		SELECT	@LSPROC AS PROCEDIMIENTO,
			'ALARM' AS TABLA,
			1 AS FILAS_AFECTADAS,
			@LS_EXEC_MODE AS OPERACION,
			0 AS DURACION,
			@LS_MD_ERROR_RH + ' PKEY = ' + CHAR(39) + PKEY + CHAR(39) + '.' AS RESULTADO,
			'DELETE FROM ALARM WHERE (PKEY = ' + CHAR(39) + PKEY + CHAR(39) + ')' AS SQL_CMD
		FROM	ALARM
		WHERE	(ALARM_TYPE = @LS_JERARQUIA)
			AND ALARM_TYPE_CODE NOT IN (SELECT CALL_TYPE_CODE FROM CALL_TYPE);
	SELECT @LSOPERA = 'INSERT', @LSTABLA = 'EDA_REGISTRO_SUCESOS', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
 
	INSERT INTO	EDA_REGISTRO_SUCESOS (PROCEDIMIENTO, TABLA, FILAS_AFECTADAS, OPERACION, DURACION, RESULTADO, SQL_CMD)
		SELECT	@LSPROC AS PROCEDIMIENTO,
			'CALL_CONV_STRUCTURES' AS TABLA,
			1 AS FILAS_AFECTADAS,
			@LS_EXEC_MODE AS OPERACION,
			0 AS DURACION,
			@LS_MD_ERROR_RH + ' PKEY = ' + CHAR(39) + PKEY + CHAR(39) + '.' AS RESULTADO,
			'DELETE FROM CALL_CONV_STRUCTURES WHERE (PKEY = ' + CHAR(39) + PKEY + CHAR(39) + ')' AS SQL_CMD
		FROM	CALL_CONV_STRUCTURES
		WHERE	PAR_KEY NOT IN (SELECT PKEY FROM CALL_TYPE);
	SELECT @LSOPERA = 'INSERT', @LSTABLA = 'EDA_REGISTRO_SUCESOS', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
 
	INSERT INTO	EDA_REGISTRO_SUCESOS (PROCEDIMIENTO, TABLA, FILAS_AFECTADAS, OPERACION, DURACION, RESULTADO, SQL_CMD)
		SELECT	@LSPROC AS PROCEDIMIENTO,
			'CALL_RESULT_TYPE' AS TABLA,
			1 AS FILAS_AFECTADAS,
			@LS_EXEC_MODE AS OPERACION,
			0 AS DURACION,
			@LS_MD_ERROR_RH + ' PKEY = ' + CHAR(39) + PKEY + CHAR(39) + '.' AS RESULTADO,
			'DELETE FROM CALL_RESULT_TYPE WHERE (PKEY = ' + CHAR(39) + PKEY + CHAR(39) + ')' AS SQL_CMD
		FROM	CALL_RESULT_TYPE
		WHERE	PAR_KEY NOT IN (SELECT PKEY FROM CALL_TYPE);
	SELECT @LSOPERA = 'INSERT', @LSTABLA = 'EDA_REGISTRO_SUCESOS', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
 
	INSERT INTO	EDA_REGISTRO_SUCESOS (PROCEDIMIENTO, TABLA, FILAS_AFECTADAS, OPERACION, DURACION, RESULTADO, SQL_CMD)
		SELECT	@LSPROC AS PROCEDIMIENTO,
			'CALL_TYPE_EMAIL' AS TABLA,
			1 AS FILAS_AFECTADAS,
			@LS_EXEC_MODE AS OPERACION,
			0 AS DURACION,
			@LS_MD_ERROR_RH + ' PKEY = ' + CHAR(39) + PKEY + CHAR(39) + '.' AS RESULTADO,
			'DELETE FROM CALL_TYPE_EMAIL WHERE (PKEY = ' + CHAR(39) + PKEY + CHAR(39) + ')' AS SQL_CMD
		FROM	CALL_TYPE_EMAIL
		WHERE	PAR_KEY NOT IN (SELECT PKEY FROM CALL_TYPE);
	SELECT @LSOPERA = 'INSERT', @LSTABLA = 'EDA_REGISTRO_SUCESOS', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
 
	INSERT INTO	EDA_REGISTRO_SUCESOS (PROCEDIMIENTO, TABLA, FILAS_AFECTADAS, OPERACION, DURACION, RESULTADO, SQL_CMD)
		SELECT	@LSPROC AS PROCEDIMIENTO,
			'CUSTOMER_DOCUMENTS' AS TABLA,
			1 AS FILAS_AFECTADAS,
			@LS_EXEC_MODE AS OPERACION,
			0 AS DURACION,
			@LS_MD_ERROR_RH + ' PKEY = ' + CHAR(39) + PKEY + CHAR(39) + '.' AS RESULTADO,
			'DELETE FROM CUSTOMER_DOCUMENTS WHERE (PKEY = ' + CHAR(39) + PKEY + CHAR(39) + ')' AS SQL_CMD
		FROM	CUSTOMER_DOCUMENTS
		WHERE	CALL_TYPE_CODE NOT IN (SELECT CALL_TYPE_CODE FROM CALL_TYPE);
	SELECT @LSOPERA = 'INSERT', @LSTABLA = 'EDA_REGISTRO_SUCESOS', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
 
	INSERT INTO	EDA_REGISTRO_SUCESOS (PROCEDIMIENTO, TABLA, FILAS_AFECTADAS, OPERACION, DURACION, RESULTADO, SQL_CMD)
		SELECT	@LSPROC AS PROCEDIMIENTO,
			'CUSTOMER_DOCUMENTS_ATT' AS TABLA,
			1 AS FILAS_AFECTADAS,
			@LS_EXEC_MODE AS OPERACION,
			0 AS DURACION,
			@LS_MD_ERROR_RH + ' PKEY = ' + CHAR(39) + PKEY + CHAR(39) + '.' AS RESULTADO,
			'DELETE FROM CUSTOMER_DOCUMENTS_ATT WHERE (PKEY = ' + CHAR(39) + PKEY + CHAR(39) + ')' AS SQL_CMD
		FROM	CUSTOMER_DOCUMENTS_ATT
		WHERE	CALL_TYPE_REL NOT IN (SELECT CALL_TYPE_CODE FROM CALL_TYPE);
	SELECT @LSOPERA = 'INSERT', @LSTABLA = 'EDA_REGISTRO_SUCESOS', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
 
	INSERT INTO	EDA_REGISTRO_SUCESOS (PROCEDIMIENTO, TABLA, FILAS_AFECTADAS, OPERACION, DURACION, RESULTADO, SQL_CMD)
		SELECT	@LSPROC AS PROCEDIMIENTO,
			'JOB_ACTIONS' AS TABLA,
			1 AS FILAS_AFECTADAS,
			@LS_EXEC_MODE AS OPERACION,
			0 AS DURACION,
			@LS_MD_ERROR_RH + ' PKEY = ' + CHAR(39) + PKEY + CHAR(39) + '.' AS RESULTADO,
			'DELETE FROM JOB_ACTIONS WHERE (PKEY = ' + CHAR(39) + PKEY + CHAR(39) + ')' AS SQL_CMD
		FROM	JOB_ACTIONS
		WHERE	PAR_KEY NOT IN (SELECT PKEY FROM CALL_TYPE);
	SELECT @LSOPERA = 'INSERT', @LSTABLA = 'EDA_REGISTRO_SUCESOS', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
 
	INSERT INTO	EDA_REGISTRO_SUCESOS (PROCEDIMIENTO, TABLA, FILAS_AFECTADAS, OPERACION, DURACION, RESULTADO, SQL_CMD)
		SELECT	@LSPROC AS PROCEDIMIENTO,
			'JOB_DIAGRAM_MULT_INFLOWS_RULES' AS TABLA,
			1 AS FILAS_AFECTADAS,
			@LS_EXEC_MODE AS OPERACION,
			0 AS DURACION,
			@LS_MD_ERROR_RH + ' PKEY = ' + CHAR(39) + PKEY + CHAR(39) + '.' AS RESULTADO,
			'DELETE FROM JOB_DIAGRAM_MULT_INFLOWS_RULES WHERE (PKEY = ' + CHAR(39) + PKEY + CHAR(39) + ')' AS SQL_CMD
		FROM	JOB_DIAGRAM_MULT_INFLOWS_RULES
		WHERE	PAR_KEY NOT IN (SELECT PKEY FROM CALL_TYPE);
	SELECT @LSOPERA = 'INSERT', @LSTABLA = 'EDA_REGISTRO_SUCESOS', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
 
	INSERT INTO	EDA_REGISTRO_SUCESOS (PROCEDIMIENTO, TABLA, FILAS_AFECTADAS, OPERACION, DURACION, RESULTADO, SQL_CMD)
		SELECT	@LSPROC AS PROCEDIMIENTO,
			'NOT_CONTACT_REASONS' AS TABLA,
			1 AS FILAS_AFECTADAS,
			@LS_EXEC_MODE AS OPERACION,
			0 AS DURACION,
			@LS_MD_ERROR_RH + ' PKEY = ' + CHAR(39) + PKEY + CHAR(39) + '.' AS RESULTADO,
			'DELETE FROM NOT_CONTACT_REASONS WHERE (PKEY = ' + CHAR(39) + PKEY + CHAR(39) + ')' AS SQL_CMD
		FROM	NOT_CONTACT_REASONS
		WHERE	PAR_KEY NOT IN (SELECT PKEY FROM CALL_TYPE);
	SELECT @LSOPERA = 'INSERT', @LSTABLA = 'EDA_REGISTRO_SUCESOS', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
 
	INSERT INTO	EDA_REGISTRO_SUCESOS (PROCEDIMIENTO, TABLA, FILAS_AFECTADAS, OPERACION, DURACION, RESULTADO, SQL_CMD)
		SELECT	@LSPROC AS PROCEDIMIENTO,
			'QUESTION' AS TABLA,
			1 AS FILAS_AFECTADAS,
			@LS_EXEC_MODE AS OPERACION,
			0 AS DURACION,
			@LS_MD_ERROR_RH + ' PKEY = ' + CHAR(39) + PKEY + CHAR(39) + '.' AS RESULTADO,
			'DELETE FROM QUESTION WHERE (PKEY = ' + CHAR(39) + PKEY + CHAR(39) + ')' AS SQL_CMD
		FROM	QUESTION
		WHERE	CALL_TYPE_CODE NOT IN (SELECT CALL_TYPE_CODE FROM CALL_TYPE);
	SELECT @LSOPERA = 'INSERT', @LSTABLA = 'EDA_REGISTRO_SUCESOS', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
 
	INSERT INTO	EDA_REGISTRO_SUCESOS (PROCEDIMIENTO, TABLA, FILAS_AFECTADAS, OPERACION, DURACION, RESULTADO, SQL_CMD)
		SELECT	@LSPROC AS PROCEDIMIENTO,
			'STORED_PROCEDURES' AS TABLA,
			1 AS FILAS_AFECTADAS,
			@LS_EXEC_MODE AS OPERACION,
			0 AS DURACION,
			@LS_MD_ERROR_RH + ' PKEY = ' + CHAR(39) + PKEY + CHAR(39) + '.' AS RESULTADO,
			'DELETE FROM STORED_PROCEDURES WHERE (PKEY = ' + CHAR(39) + PKEY + CHAR(39) + ')' AS SQL_CMD
		FROM	STORED_PROCEDURES
		WHERE	(SP_TYPE_IDR = @LS_JERARQUIA)
			AND SP_TYPE_CODE NOT IN (SELECT CALL_TYPE_CODE FROM CALL_TYPE);
	SELECT @LSOPERA = 'INSERT', @LSTABLA = 'EDA_REGISTRO_SUCESOS', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
 
	INSERT INTO	EDA_REGISTRO_SUCESOS (PROCEDIMIENTO, TABLA, FILAS_AFECTADAS, OPERACION, DURACION, RESULTADO, SQL_CMD)
		SELECT	@LSPROC AS PROCEDIMIENTO,
			'TRANSACTIONS' AS TABLA,
			1 AS FILAS_AFECTADAS,
			@LS_EXEC_MODE AS OPERACION,
			0 AS DURACION,
			@LS_MD_ERROR_RH + ' PKEY = ' + CHAR(39) + PKEY + CHAR(39) + '.' AS RESULTADO,
			'DELETE FROM TRANSACTIONS WHERE (PKEY = ' + CHAR(39) + PKEY + CHAR(39) + ')' AS SQL_CMD
		FROM	TRANSACTIONS
		WHERE	(TRAN_IDR = @LS_JERARQUIA)
			AND CALL_TYPE_CODE NOT IN (SELECT CALL_TYPE_CODE FROM CALL_TYPE);
	SELECT @LSOPERA = 'INSERT', @LSTABLA = 'EDA_REGISTRO_SUCESOS', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
 
	-- FIN DE DEPURACIÓN DE TABLAS DE TIPO DE ACTIVIDAD DE NIVEL 1.
 
	-- INICIO DE DEPURACIÓN DE TABLAS DE TIPO DE ACTIVIDAD DE NIVEL 2.
 
	INSERT INTO	EDA_REGISTRO_SUCESOS (PROCEDIMIENTO, TABLA, FILAS_AFECTADAS, OPERACION, DURACION, RESULTADO, SQL_CMD)
		SELECT	@LSPROC AS PROCEDIMIENTO,
			'ALARM_CHECKS' AS TABLA,
			1 AS FILAS_AFECTADAS,
			@LS_EXEC_MODE AS OPERACION,
			0 AS DURACION,
			@LS_MD_ERROR_RH + ' PKEY = ' + CHAR(39) + PKEY + CHAR(39) + '.' AS RESULTADO,
			'DELETE FROM ALARM_CHECKS WHERE (PKEY = ' + CHAR(39) + PKEY + CHAR(39) + ')' AS SQL_CMD
		FROM	ALARM_CHECKS
		WHERE	PAR_KEY NOT IN (SELECT PKEY FROM ALARM);
	SELECT @LSOPERA = 'INSERT', @LSTABLA = 'EDA_REGISTRO_SUCESOS', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
 
	INSERT INTO	EDA_REGISTRO_SUCESOS (PROCEDIMIENTO, TABLA, FILAS_AFECTADAS, OPERACION, DURACION, RESULTADO, SQL_CMD)
		SELECT	@LSPROC AS PROCEDIMIENTO,
			'ALARM_POPUP_DETAIL' AS TABLA,
			1 AS FILAS_AFECTADAS,
			@LS_EXEC_MODE AS OPERACION,
			0 AS DURACION,
			@LS_MD_ERROR_RH + ' PKEY = ' + CHAR(39) + PKEY + CHAR(39) + '.' AS RESULTADO,
			'DELETE FROM ALARM_POPUP_DETAIL WHERE (PKEY = ' + CHAR(39) + PKEY + CHAR(39) + ')' AS SQL_CMD
		FROM	ALARM_POPUP_DETAIL
		WHERE	PAR_KEY NOT IN (SELECT PKEY FROM ALARM);
	SELECT @LSOPERA = 'INSERT', @LSTABLA = 'EDA_REGISTRO_SUCESOS', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
 
	INSERT INTO	EDA_REGISTRO_SUCESOS (PROCEDIMIENTO, TABLA, FILAS_AFECTADAS, OPERACION, DURACION, RESULTADO, SQL_CMD)
		SELECT	@LSPROC AS PROCEDIMIENTO,
			'ALARM_TRANSACTIONS' AS TABLA,
			1 AS FILAS_AFECTADAS,
			@LS_EXEC_MODE AS OPERACION,
			0 AS DURACION,
			@LS_MD_ERROR_RH + ' PKEY = ' + CHAR(39) + PKEY + CHAR(39) + '.' AS RESULTADO,
			'DELETE FROM ALARM_TRANSACTIONS WHERE (PKEY = ' + CHAR(39) + PKEY + CHAR(39) + ')' AS SQL_CMD
		FROM	ALARM_TRANSACTIONS
		WHERE	PAR_KEY NOT IN (SELECT PKEY FROM ALARM);
	SELECT @LSOPERA = 'INSERT', @LSTABLA = 'EDA_REGISTRO_SUCESOS', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
 
	INSERT INTO	EDA_REGISTRO_SUCESOS (PROCEDIMIENTO, TABLA, FILAS_AFECTADAS, OPERACION, DURACION, RESULTADO, SQL_CMD)
		SELECT	@LSPROC AS PROCEDIMIENTO,
			'CONV_STRUCTURE_STEP_NORMAL' AS TABLA,
			1 AS FILAS_AFECTADAS,
			@LS_EXEC_MODE AS OPERACION,
			0 AS DURACION,
			@LS_MD_ERROR_RH + ' PKEY = ' + CHAR(39) + PKEY + CHAR(39) + '.' AS RESULTADO,
			'DELETE FROM CONV_STRUCTURE_STEP_NORMAL WHERE (PKEY = ' + CHAR(39) + PKEY + CHAR(39) + ')' AS SQL_CMD
		FROM	CONV_STRUCTURE_STEP_NORMAL
		WHERE	PAR_KEY NOT IN (SELECT PKEY FROM CALL_CONV_STRUCTURES);
	SELECT @LSOPERA = 'INSERT', @LSTABLA = 'EDA_REGISTRO_SUCESOS', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
 
	INSERT INTO	EDA_REGISTRO_SUCESOS (PROCEDIMIENTO, TABLA, FILAS_AFECTADAS, OPERACION, DURACION, RESULTADO, SQL_CMD)
		SELECT	@LSPROC AS PROCEDIMIENTO,
			'CONV_STRUCTURE_STEP_QUESTION' AS TABLA,
			1 AS FILAS_AFECTADAS,
			@LS_EXEC_MODE AS OPERACION,
			0 AS DURACION,
			@LS_MD_ERROR_RH + ' PKEY = ' + CHAR(39) + PKEY + CHAR(39) + '.' AS RESULTADO,
			'DELETE FROM CONV_STRUCTURE_STEP_QUESTION WHERE (PKEY = ' + CHAR(39) + PKEY + CHAR(39) + ')' AS SQL_CMD
		FROM	CONV_STRUCTURE_STEP_QUESTION
		WHERE	PAR_KEY NOT IN (SELECT PKEY FROM CALL_CONV_STRUCTURES);
	SELECT @LSOPERA = 'INSERT', @LSTABLA = 'EDA_REGISTRO_SUCESOS', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
 
	INSERT INTO	EDA_REGISTRO_SUCESOS (PROCEDIMIENTO, TABLA, FILAS_AFECTADAS, OPERACION, DURACION, RESULTADO, SQL_CMD)
		SELECT	@LSPROC AS PROCEDIMIENTO,
			'CONV_STRUCTURE_STEP_TRAN' AS TABLA,
			1 AS FILAS_AFECTADAS,
			@LS_EXEC_MODE AS OPERACION,
			0 AS DURACION,
			@LS_MD_ERROR_RH + ' PKEY = ' + CHAR(39) + PKEY + CHAR(39) + '.' AS RESULTADO,
			'DELETE FROM CONV_STRUCTURE_STEP_TRAN WHERE (PKEY = ' + CHAR(39) + PKEY + CHAR(39) + ')' AS SQL_CMD
		FROM	CONV_STRUCTURE_STEP_TRAN
		WHERE	PAR_KEY NOT IN (SELECT PKEY FROM CALL_CONV_STRUCTURES);
	SELECT @LSOPERA = 'INSERT', @LSTABLA = 'EDA_REGISTRO_SUCESOS', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
 
	INSERT INTO	EDA_REGISTRO_SUCESOS (PROCEDIMIENTO, TABLA, FILAS_AFECTADAS, OPERACION, DURACION, RESULTADO, SQL_CMD)
		SELECT	@LSPROC AS PROCEDIMIENTO,
			'ANSWER' AS TABLA,
			1 AS FILAS_AFECTADAS,
			@LS_EXEC_MODE AS OPERACION,
			0 AS DURACION,
			@LS_MD_ERROR_RH + ' PKEY = ' + CHAR(39) + PKEY + CHAR(39) + '.' AS RESULTADO,
			'DELETE FROM ANSWER WHERE (PKEY = ' + CHAR(39) + PKEY + CHAR(39) + ')' AS SQL_CMD
		FROM	ANSWER
		WHERE	PAR_KEY NOT IN (SELECT PKEY FROM QUESTION);
	SELECT @LSOPERA = 'INSERT', @LSTABLA = 'EDA_REGISTRO_SUCESOS', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
 
	INSERT INTO	EDA_REGISTRO_SUCESOS (PROCEDIMIENTO, TABLA, FILAS_AFECTADAS, OPERACION, DURACION, RESULTADO, SQL_CMD)
		SELECT	@LSPROC AS PROCEDIMIENTO,
			'SP_PRM_IN' AS TABLA,
			1 AS FILAS_AFECTADAS,
			@LS_EXEC_MODE AS OPERACION,
			0 AS DURACION,
			@LS_MD_ERROR_RH + ' PKEY = ' + CHAR(39) + PKEY + CHAR(39) + '.' AS RESULTADO,
			'DELETE FROM SP_PRM_IN WHERE (PKEY = ' + CHAR(39) + PKEY + CHAR(39) + ')' AS SQL_CMD
		FROM	SP_PRM_IN
		WHERE	PAR_KEY NOT IN (SELECT PKEY FROM STORED_PROCEDURES); 
	SELECT @LSOPERA = 'INSERT', @LSTABLA = 'EDA_REGISTRO_SUCESOS', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
 
	INSERT INTO	EDA_REGISTRO_SUCESOS (PROCEDIMIENTO, TABLA, FILAS_AFECTADAS, OPERACION, DURACION, RESULTADO, SQL_CMD)
		SELECT	@LSPROC AS PROCEDIMIENTO,
			'SP_PRM_OUT' AS TABLA,
			1 AS FILAS_AFECTADAS,
			@LS_EXEC_MODE AS OPERACION,
			0 AS DURACION,
			@LS_MD_ERROR_RH + ' PKEY = ' + CHAR(39) + PKEY + CHAR(39) + '.' AS RESULTADO,
			'DELETE FROM SP_PRM_OUT WHERE (PKEY = ' + CHAR(39) + PKEY + CHAR(39) + ')' AS SQL_CMD
		FROM	SP_PRM_OUT
		WHERE	PAR_KEY NOT IN (SELECT PKEY FROM STORED_PROCEDURES);
	SELECT @LSOPERA = 'INSERT', @LSTABLA = 'EDA_REGISTRO_SUCESOS', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
 
	INSERT INTO	EDA_REGISTRO_SUCESOS (PROCEDIMIENTO, TABLA, FILAS_AFECTADAS, OPERACION, DURACION, RESULTADO, SQL_CMD)
		SELECT	@LSPROC AS PROCEDIMIENTO,
			'TRAN_PRM_IN' AS TABLA,
			1 AS FILAS_AFECTADAS,
			@LS_EXEC_MODE AS OPERACION,
			0 AS DURACION,
			@LS_MD_ERROR_RH + ' PKEY = ' + CHAR(39) + PKEY + CHAR(39) + '.' AS RESULTADO,
			'DELETE FROM TRAN_PRM_IN WHERE (PKEY = ' + CHAR(39) + PKEY + CHAR(39) + ')' AS SQL_CMD
		FROM	TRAN_PRM_IN
		WHERE	PAR_KEY NOT IN (SELECT PKEY FROM TRANSACTIONS);
	SELECT @LSOPERA = 'INSERT', @LSTABLA = 'EDA_REGISTRO_SUCESOS', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
 
	INSERT INTO	EDA_REGISTRO_SUCESOS (PROCEDIMIENTO, TABLA, FILAS_AFECTADAS, OPERACION, DURACION, RESULTADO, SQL_CMD)
		SELECT	@LSPROC AS PROCEDIMIENTO,
			'TRAN_PRM_OUT' AS TABLA,
			1 AS FILAS_AFECTADAS,
			@LS_EXEC_MODE AS OPERACION,
			0 AS DURACION,
			@LS_MD_ERROR_RH + ' PKEY = ' + CHAR(39) + PKEY + CHAR(39) + '.' AS RESULTADO,
			'DELETE FROM TRAN_PRM_OUT WHERE (PKEY = ' + CHAR(39) + PKEY + CHAR(39) + ')' AS SQL_CMD
		FROM	TRAN_PRM_OUT
		WHERE	PAR_KEY NOT IN (SELECT PKEY FROM TRANSACTIONS);
	SELECT @LSOPERA = 'INSERT', @LSTABLA = 'EDA_REGISTRO_SUCESOS', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
 
	-- FIN DE DEPURACIÓN DE TABLAS DE TIPO DE ACTIVIDAD DE NIVEL 2.
 
	-- INICIO DE DEPURACIÓN DE TABLAS DE TIPO DE ACTIVIDAD DE NIVEL 3.
 
	INSERT INTO	EDA_REGISTRO_SUCESOS (PROCEDIMIENTO, TABLA, FILAS_AFECTADAS, OPERACION, DURACION, RESULTADO, SQL_CMD)
		SELECT	@LSPROC AS PROCEDIMIENTO,
			'DETAIL_FIELD' AS TABLA,
			1 AS FILAS_AFECTADAS,
			@LS_EXEC_MODE AS OPERACION,
			0 AS DURACION,
			@LS_MD_ERROR_RH + ' PKEY = ' + CHAR(39) + PKEY + CHAR(39) + '.' AS RESULTADO,
			'DELETE FROM DETAIL_FIELD WHERE (PKEY = ' + CHAR(39) + PKEY + CHAR(39) + ')' AS SQL_CMD
		FROM	DETAIL_FIELD
		WHERE	PAR_KEY NOT IN (SELECT PKEY FROM CONV_STRUCTURE_STEP_NORMAL);
	SELECT @LSOPERA = 'INSERT', @LSTABLA = 'EDA_REGISTRO_SUCESOS', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
 
	INSERT INTO	EDA_REGISTRO_SUCESOS (PROCEDIMIENTO, TABLA, FILAS_AFECTADAS, OPERACION, DURACION, RESULTADO, SQL_CMD)
		SELECT	@LSPROC AS PROCEDIMIENTO,
			'DETAIL_FILE' AS TABLA,
			1 AS FILAS_AFECTADAS,
			@LS_EXEC_MODE AS OPERACION,
			0 AS DURACION,
			@LS_MD_ERROR_RH + ' PKEY = ' + CHAR(39) + PKEY + CHAR(39) + '.' AS RESULTADO,
			'DELETE FROM DETAIL_FILE WHERE (PKEY = ' + CHAR(39) + PKEY + CHAR(39) + ')' AS SQL_CMD
		FROM	DETAIL_FILE
		WHERE	PAR_KEY NOT IN (SELECT PKEY FROM CONV_STRUCTURE_STEP_NORMAL);
	SELECT @LSOPERA = 'INSERT', @LSTABLA = 'EDA_REGISTRO_SUCESOS', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
 
	INSERT INTO	EDA_REGISTRO_SUCESOS (PROCEDIMIENTO, TABLA, FILAS_AFECTADAS, OPERACION, DURACION, RESULTADO, SQL_CMD)
		SELECT	@LSPROC AS PROCEDIMIENTO,
			'DETAIL_LABEL' AS TABLA,
			1 AS FILAS_AFECTADAS,
			@LS_EXEC_MODE AS OPERACION,
			0 AS DURACION,
			@LS_MD_ERROR_RH + ' PKEY = ' + CHAR(39) + PKEY + CHAR(39) + '.' AS RESULTADO,
			'DELETE FROM DETAIL_LABEL WHERE (PKEY = ' + CHAR(39) + PKEY + CHAR(39) + ')' AS SQL_CMD
		FROM	DETAIL_LABEL
		WHERE	(CTL_TYPE_CODE <> 'pregunta')
			AND PAR_KEY NOT IN (SELECT PKEY FROM CONV_STRUCTURE_STEP_NORMAL);
	SELECT @LSOPERA = 'INSERT', @LSTABLA = 'EDA_REGISTRO_SUCESOS', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
 
	INSERT INTO	EDA_REGISTRO_SUCESOS (PROCEDIMIENTO, TABLA, FILAS_AFECTADAS, OPERACION, DURACION, RESULTADO, SQL_CMD)
		SELECT	@LSPROC AS PROCEDIMIENTO,
			'STEP_CHECKS' AS TABLA,
			1 AS FILAS_AFECTADAS,
			@LS_EXEC_MODE AS OPERACION,
			0 AS DURACION,
			@LS_MD_ERROR_RH + ' PKEY = ' + CHAR(39) + PKEY + CHAR(39) + '.' AS RESULTADO,
			'DELETE FROM STEP_CHECKS WHERE (PKEY = ' + CHAR(39) + PKEY + CHAR(39) + ')' AS SQL_CMD
		FROM	STEP_CHECKS
		WHERE	PAR_KEY NOT IN (SELECT PKEY FROM CONV_STRUCTURE_STEP_NORMAL);
	SELECT @LSOPERA = 'INSERT', @LSTABLA = 'EDA_REGISTRO_SUCESOS', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
 
	INSERT INTO	EDA_REGISTRO_SUCESOS (PROCEDIMIENTO, TABLA, FILAS_AFECTADAS, OPERACION, DURACION, RESULTADO, SQL_CMD)
		SELECT	@LSPROC AS PROCEDIMIENTO,
			'STEP_NORMAL_FLOW' AS TABLA,
			1 AS FILAS_AFECTADAS,
			@LS_EXEC_MODE AS OPERACION,
			0 AS DURACION,
			@LS_MD_ERROR_RH + ' PKEY = ' + CHAR(39) + PKEY + CHAR(39) + '.' AS RESULTADO,
			'DELETE FROM STEP_NORMAL_FLOW WHERE (PKEY = ' + CHAR(39) + PKEY + CHAR(39) + ')' AS SQL_CMD
		FROM	STEP_NORMAL_FLOW
		WHERE	(FLOW_TYPE_CODE IN ('flujonormal', 'flujostrnormal'))
			AND PAR_KEY NOT IN (SELECT PKEY FROM CONV_STRUCTURE_STEP_NORMAL);
	SELECT @LSOPERA = 'INSERT', @LSTABLA = 'EDA_REGISTRO_SUCESOS', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
 
	INSERT INTO	EDA_REGISTRO_SUCESOS (PROCEDIMIENTO, TABLA, FILAS_AFECTADAS, OPERACION, DURACION, RESULTADO, SQL_CMD)
		SELECT	@LSPROC AS PROCEDIMIENTO,
			'STEP_RESULTS' AS TABLA,
			1 AS FILAS_AFECTADAS,
			@LS_EXEC_MODE AS OPERACION,
			0 AS DURACION,
			@LS_MD_ERROR_RH + ' PKEY = ' + CHAR(39) + PKEY + CHAR(39) + '.' AS RESULTADO,
			'DELETE FROM STEP_RESULTS WHERE (PKEY = ' + CHAR(39) + PKEY + CHAR(39) + ')' AS SQL_CMD
		FROM	STEP_RESULTS
		WHERE	(RIGHT(PAR_KEY, 2) = '55')
			AND PAR_KEY NOT IN (SELECT PKEY FROM CONV_STRUCTURE_STEP_NORMAL);
	SELECT @LSOPERA = 'INSERT', @LSTABLA = 'EDA_REGISTRO_SUCESOS', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
 
	INSERT INTO	EDA_REGISTRO_SUCESOS (PROCEDIMIENTO, TABLA, FILAS_AFECTADAS, OPERACION, DURACION, RESULTADO, SQL_CMD)
		SELECT	@LSPROC AS PROCEDIMIENTO,
			'DETAIL_LABEL' AS TABLA,
			1 AS FILAS_AFECTADAS,
			@LS_EXEC_MODE AS OPERACION,
			0 AS DURACION,
			@LS_MD_ERROR_RH + ' PKEY = ' + CHAR(39) + PKEY + CHAR(39) + '.' AS RESULTADO,
			'DELETE FROM DETAIL_LABEL WHERE (PKEY = ' + CHAR(39) + PKEY + CHAR(39) + ')' AS SQL_CMD
		FROM	DETAIL_LABEL
		WHERE	(CTL_TYPE_CODE = 'pregunta')
			AND PAR_KEY NOT IN (SELECT PKEY FROM CONV_STRUCTURE_STEP_QUESTION);
	SELECT @LSOPERA = 'INSERT', @LSTABLA = 'EDA_REGISTRO_SUCESOS', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
 
	INSERT INTO	EDA_REGISTRO_SUCESOS (PROCEDIMIENTO, TABLA, FILAS_AFECTADAS, OPERACION, DURACION, RESULTADO, SQL_CMD)
		SELECT	@LSPROC AS PROCEDIMIENTO,
			'DETAIL_SPREAD' AS TABLA,
			1 AS FILAS_AFECTADAS,
			@LS_EXEC_MODE AS OPERACION,
			0 AS DURACION,
			@LS_MD_ERROR_RH + ' PKEY = ' + CHAR(39) + PKEY + CHAR(39) + '.' AS RESULTADO,
			'DELETE FROM DETAIL_SPREAD WHERE (PKEY = ' + CHAR(39) + PKEY + CHAR(39) + ')' AS SQL_CMD
		FROM	DETAIL_SPREAD
		WHERE	PAR_KEY NOT IN (SELECT PKEY FROM CONV_STRUCTURE_STEP_QUESTION);
	SELECT @LSOPERA = 'INSERT', @LSTABLA = 'EDA_REGISTRO_SUCESOS', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
 
	INSERT INTO	EDA_REGISTRO_SUCESOS (PROCEDIMIENTO, TABLA, FILAS_AFECTADAS, OPERACION, DURACION, RESULTADO, SQL_CMD)
		SELECT	@LSPROC AS PROCEDIMIENTO,
			'STEP_NORMAL_FLOW' AS TABLA,
			1 AS FILAS_AFECTADAS,
			@LS_EXEC_MODE AS OPERACION,
			0 AS DURACION,
			@LS_MD_ERROR_RH + ' PKEY = ' + CHAR(39) + PKEY + CHAR(39) + '.' AS RESULTADO,
			'DELETE FROM STEP_NORMAL_FLOW WHERE (PKEY = ' + CHAR(39) + PKEY + CHAR(39) + ')' AS SQL_CMD
		FROM	STEP_NORMAL_FLOW
		WHERE	(FLOW_TYPE_CODE IN ('flujomultiple', 'flujostrmultiple'))
			AND PAR_KEY NOT IN (SELECT PKEY FROM CONV_STRUCTURE_STEP_QUESTION);
	SELECT @LSOPERA = 'INSERT', @LSTABLA = 'EDA_REGISTRO_SUCESOS', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
 
	INSERT INTO	EDA_REGISTRO_SUCESOS (PROCEDIMIENTO, TABLA, FILAS_AFECTADAS, OPERACION, DURACION, RESULTADO, SQL_CMD)
		SELECT	@LSPROC AS PROCEDIMIENTO,
			'STEP_QUESTION_FLOW' AS TABLA,
			1 AS FILAS_AFECTADAS,
			@LS_EXEC_MODE AS OPERACION,
			0 AS DURACION,
			@LS_MD_ERROR_RH + ' PKEY = ' + CHAR(39) + PKEY + CHAR(39) + '.' AS RESULTADO,
			'DELETE FROM STEP_QUESTION_FLOW WHERE (PKEY = ' + CHAR(39) + PKEY + CHAR(39) + ')' AS SQL_CMD
		FROM	STEP_QUESTION_FLOW
		WHERE	PAR_KEY NOT IN (SELECT PKEY FROM CONV_STRUCTURE_STEP_QUESTION);
	SELECT @LSOPERA = 'INSERT', @LSTABLA = 'EDA_REGISTRO_SUCESOS', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
 
	INSERT INTO	EDA_REGISTRO_SUCESOS (PROCEDIMIENTO, TABLA, FILAS_AFECTADAS, OPERACION, DURACION, RESULTADO, SQL_CMD)
		SELECT	@LSPROC AS PROCEDIMIENTO,
			'STEP_RESULTS' AS TABLA,
			1 AS FILAS_AFECTADAS,
			@LS_EXEC_MODE AS OPERACION,
			0 AS DURACION,
			@LS_MD_ERROR_RH + ' PKEY = ' + CHAR(39) + PKEY + CHAR(39) + '.' AS RESULTADO,
			'DELETE FROM STEP_RESULTS WHERE (PKEY = ' + CHAR(39) + PKEY + CHAR(39) + ')' AS SQL_CMD
		FROM	STEP_RESULTS
		WHERE	(RIGHT(PAR_KEY, 2) = '49')
			AND PAR_KEY NOT IN (SELECT PKEY FROM CONV_STRUCTURE_STEP_QUESTION);
	SELECT @LSOPERA = 'INSERT', @LSTABLA = 'EDA_REGISTRO_SUCESOS', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
 
	INSERT INTO	EDA_REGISTRO_SUCESOS (PROCEDIMIENTO, TABLA, FILAS_AFECTADAS, OPERACION, DURACION, RESULTADO, SQL_CMD)
		SELECT	@LSPROC AS PROCEDIMIENTO,
			'STEP_RESULTS' AS TABLA,
			1 AS FILAS_AFECTADAS,
			@LS_EXEC_MODE AS OPERACION,
			0 AS DURACION,
			@LS_MD_ERROR_RH + ' PKEY = ' + CHAR(39) + PKEY + CHAR(39) + '.' AS RESULTADO,
			'DELETE FROM STEP_RESULTS WHERE (PKEY = ' + CHAR(39) + PKEY + CHAR(39) + ')' AS SQL_CMD
		FROM	STEP_RESULTS
		WHERE	(RIGHT(PAR_KEY, 2) = '56')
			AND PAR_KEY NOT IN (SELECT PKEY FROM CONV_STRUCTURE_STEP_TRAN);
	SELECT @LSOPERA = 'INSERT', @LSTABLA = 'EDA_REGISTRO_SUCESOS', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
 
	INSERT INTO	EDA_REGISTRO_SUCESOS (PROCEDIMIENTO, TABLA, FILAS_AFECTADAS, OPERACION, DURACION, RESULTADO, SQL_CMD)
		SELECT	@LSPROC AS PROCEDIMIENTO,
			'STEP_TRANSACTION_FLOW' AS TABLA,
			1 AS FILAS_AFECTADAS,
			@LS_EXEC_MODE AS OPERACION,
			0 AS DURACION,
			@LS_MD_ERROR_RH + ' PKEY = ' + CHAR(39) + PKEY + CHAR(39) + '.' AS RESULTADO,
			'DELETE FROM STEP_TRANSACTION_FLOW WHERE (PKEY = ' + CHAR(39) + PKEY + CHAR(39) + ')' AS SQL_CMD
		FROM	STEP_TRANSACTION_FLOW
		WHERE	PAR_KEY NOT IN (SELECT PKEY FROM CONV_STRUCTURE_STEP_TRAN);
	SELECT @LSOPERA = 'INSERT', @LSTABLA = 'EDA_REGISTRO_SUCESOS', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
 
	INSERT INTO	EDA_REGISTRO_SUCESOS (PROCEDIMIENTO, TABLA, FILAS_AFECTADAS, OPERACION, DURACION, RESULTADO, SQL_CMD)
		SELECT	@LSPROC AS PROCEDIMIENTO,
			'SP_PRM_OUT_VALUE' AS TABLA,
			1 AS FILAS_AFECTADAS,
			@LS_EXEC_MODE AS OPERACION,
			0 AS DURACION,
			@LS_MD_ERROR_RH + ' PKEY = ' + CHAR(39) + PKEY + CHAR(39) + '.' AS RESULTADO,
			'DELETE FROM SP_PRM_OUT_VALUE WHERE (PKEY = ' + CHAR(39) + PKEY + CHAR(39) + ')' AS SQL_CMD
		FROM	SP_PRM_OUT_VALUE
		WHERE	PAR_KEY NOT IN (SELECT PKEY FROM SP_PRM_OUT); 
	SELECT @LSOPERA = 'INSERT', @LSTABLA = 'EDA_REGISTRO_SUCESOS', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
 
	INSERT INTO	EDA_REGISTRO_SUCESOS (PROCEDIMIENTO, TABLA, FILAS_AFECTADAS, OPERACION, DURACION, RESULTADO, SQL_CMD)
		SELECT	@LSPROC AS PROCEDIMIENTO,
			'TRAN_PRM_VALUE' AS TABLA,
			1 AS FILAS_AFECTADAS,
			@LS_EXEC_MODE AS OPERACION,
			0 AS DURACION,
			@LS_MD_ERROR_RH + ' PKEY = ' + CHAR(39) + PKEY + CHAR(39) + '.' AS RESULTADO,
			'DELETE FROM TRAN_PRM_VALUE WHERE (PKEY = ' + CHAR(39) + PKEY + CHAR(39) + ')' AS SQL_CMD
		FROM	TRAN_PRM_VALUE
		WHERE	PAR_KEY NOT IN (SELECT PKEY FROM TRAN_PRM_OUT);
	SELECT @LSOPERA = 'INSERT', @LSTABLA = 'EDA_REGISTRO_SUCESOS', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
 
	-- FIN DE DEPURACIÓN DE TABLAS DE TIPO DE ACTIVIDAD DE NIVEL 3.
 
	-- INICIO DE DEPURACIÓN DE TABLAS DE TIPO DE ACTIVIDAD DE NIVEL 4.
 
	INSERT INTO	EDA_REGISTRO_SUCESOS (PROCEDIMIENTO, TABLA, FILAS_AFECTADAS, OPERACION, DURACION, RESULTADO, SQL_CMD)
		SELECT	@LSPROC AS PROCEDIMIENTO,
			'STEP_CHECKS_SP' AS TABLA,
			1 AS FILAS_AFECTADAS,
			@LS_EXEC_MODE AS OPERACION,
			0 AS DURACION,
			@LS_MD_ERROR_RH + ' PKEY = ' + CHAR(39) + PKEY + CHAR(39) + '.' AS RESULTADO,
			'DELETE FROM STEP_CHECKS_SP WHERE (PKEY = ' + CHAR(39) + PKEY + CHAR(39) + ')' AS SQL_CMD
		FROM	STEP_CHECKS_SP
		WHERE	PAR_KEY NOT IN (SELECT PKEY FROM STEP_CHECKS);
	SELECT @LSOPERA = 'INSERT', @LSTABLA = 'EDA_REGISTRO_SUCESOS', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
 
	-- FIN DE DEPURACIÓN DE TABLAS DE TIPO DE ACTIVIDAD DE NIVEL 4.
 
	-- FIN - SECCIÓN DE DEPURACIÓN DE LA JERARQUÍA DE TIPO DE ACTIVIDAD.
 
	-- INICIO - SECCIÓN DE DEPURACIÓN DE LA JERARQUÍA DE CATEGORÍAS DE DATOS.
 
	-- LA JERARQUÍA DE CATEGORÍAS DE DATOS TIENE COMO TABLA RAÍZ O DE NIVEL CERO A CAT_TYPE_GROUP.
	-- NOTA: EN PRIMER LUGAR, SE DEPURAN LAS TABLAS HIJAS DE CAT_TYPE_GROUP, ES DECIR, LAS DE NIVEL 1 DENTRO DE LA JERARQUÍA Y,
	-- LUEGO, LAS TABLAS DE NIVEL 2 Y POSTERIORES.
 
	-- INICIO DE DEPURACIÓN DE TABLAS DE TIPO DE CATEGORÍAS DE DATOS DE NIVEL 1.
 
	INSERT INTO	EDA_REGISTRO_SUCESOS (PROCEDIMIENTO, TABLA, FILAS_AFECTADAS, OPERACION, DURACION, RESULTADO, SQL_CMD)
		SELECT	@LSPROC AS PROCEDIMIENTO,
			'CAT_TYPE_GROUP' AS TABLA,
			1 AS FILAS_AFECTADAS,
			@LS_EXEC_MODE AS OPERACION,
			0 AS DURACION,
			@LS_MD_ERROR_RH + ' PKEY = ' + CHAR(39) + PKEY + CHAR(39) + '.' AS RESULTADO,
			'UPDATE CAT_TYPE_GROUP SET PAR_KEY = NULL WHERE (PKEY = ' + CHAR(39) + PKEY + CHAR(39) + ')' AS SQL_CMD
		FROM	CAT_TYPE_GROUP
		WHERE	NULLIF(LTRIM(RTRIM(PAR_KEY)), '') IS NOT NULL
			AND PAR_KEY NOT IN (SELECT PKEY FROM CAT_TYPE_GROUP);
	SELECT @LSOPERA = 'INSERT', @LSTABLA = 'EDA_REGISTRO_SUCESOS', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
 
	INSERT INTO	EDA_REGISTRO_SUCESOS (PROCEDIMIENTO, TABLA, FILAS_AFECTADAS, OPERACION, DURACION, RESULTADO, SQL_CMD)
		SELECT	@LSPROC AS PROCEDIMIENTO,
			'CAT_TYPE' AS TABLA,
			1 AS FILAS_AFECTADAS,
			@LS_EXEC_MODE AS OPERACION,
			0 AS DURACION,
			@LS_MD_ERROR_RH + ' PKEY = ' + CHAR(39) + PKEY + CHAR(39) + '.' AS RESULTADO,
			'DELETE FROM CAT_TYPE WHERE (PKEY = ' + CHAR(39) + PKEY + CHAR(39) + ')' AS SQL_CMD
		FROM	CAT_TYPE
		WHERE	NULLIF(LTRIM(RTRIM(CAT_TYPE_GROUP)), '') IS NOT NULL
			AND (CAT_LEVEL = 1)
			AND CAT_TYPE_GROUP NOT IN (SELECT PKEY FROM CAT_TYPE_GROUP);
	SELECT @LSOPERA = 'INSERT', @LSTABLA = 'EDA_REGISTRO_SUCESOS', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
 
	-- FIN DE DEPURACIÓN DE TABLAS DE TIPO DE CATEGORÍAS DE DATOS DE NIVEL 1.
 
	-- INICIO DE DEPURACIÓN DE TABLAS DE TIPO DE CATEGORÍAS DE DATOS DE NIVEL 2.
 
	INSERT INTO	EDA_REGISTRO_SUCESOS (PROCEDIMIENTO, TABLA, FILAS_AFECTADAS, OPERACION, DURACION, RESULTADO, SQL_CMD)
		SELECT	@LSPROC AS PROCEDIMIENTO,
			'CAT_TYPE' AS TABLA,
			1 AS FILAS_AFECTADAS,
			@LS_EXEC_MODE AS OPERACION,
			0 AS DURACION,
			@LS_MD_ERROR_RH + ' PKEY = ' + CHAR(39) + PKEY + CHAR(39) + '.' AS RESULTADO,
			'DELETE FROM CAT_TYPE WHERE (PKEY = ' + CHAR(39) + PKEY + CHAR(39) + ')' AS SQL_CMD
		FROM	CAT_TYPE
		WHERE	NULLIF(LTRIM(RTRIM(PAR_KEY)), '') IS NOT NULL
			AND (CAT_LEVEL > 1)
			AND PAR_KEY NOT IN (SELECT PKEY FROM CAT_TYPE);
	SELECT @LSOPERA = 'INSERT', @LSTABLA = 'EDA_REGISTRO_SUCESOS', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
 
	INSERT INTO	EDA_REGISTRO_SUCESOS (PROCEDIMIENTO, TABLA, FILAS_AFECTADAS, OPERACION, DURACION, RESULTADO, SQL_CMD)
		SELECT	@LSPROC AS PROCEDIMIENTO,
			'CAT_DATA' AS TABLA,
			1 AS FILAS_AFECTADAS,
			@LS_EXEC_MODE AS OPERACION,
			0 AS DURACION,
			@LS_MD_ERROR_RH + ' PKEY = ' + CHAR(39) + PKEY + CHAR(39) + '.' AS RESULTADO,
			'DELETE FROM CAT_DATA WHERE (PKEY = ' + CHAR(39) + PKEY + CHAR(39) + ')' AS SQL_CMD
		FROM	CAT_DATA
		WHERE	PAR_KEY NOT IN (SELECT PKEY FROM CAT_TYPE);
	SELECT @LSOPERA = 'INSERT', @LSTABLA = 'EDA_REGISTRO_SUCESOS', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
 
	-- FIN DE DEPURACIÓN DE TABLAS DE TIPO DE CATEGORÍAS DE DATOS DE NIVEL 2.
 
	-- INICIO DE DEPURACIÓN DE TABLAS DE TIPO DE CATEGORÍAS DE DATOS DE NIVEL 3.
 
	INSERT INTO	EDA_REGISTRO_SUCESOS (PROCEDIMIENTO, TABLA, FILAS_AFECTADAS, OPERACION, DURACION, RESULTADO, SQL_CMD)
		SELECT	@LSPROC AS PROCEDIMIENTO,
			'CAT_DATA' AS TABLA,
			1 AS FILAS_AFECTADAS,
			@LS_EXEC_MODE AS OPERACION,
			0 AS DURACION,
			@LS_MD_ERROR_RH + ' PKEY = ' + CHAR(39) + PKEY + CHAR(39) + '.' AS RESULTADO,
			'UPDATE CAT_DATA SET PARENT_CAT_DATA_PKEY = NULL WHERE (PKEY = ' + CHAR(39) + PKEY + CHAR(39) + ')' AS SQL_CMD
		FROM	CAT_DATA
		WHERE	NULLIF(LTRIM(RTRIM(PARENT_CAT_DATA_PKEY)), '') IS NOT NULL
			AND PARENT_CAT_DATA_PKEY NOT IN (SELECT PKEY FROM CAT_DATA);
	SELECT @LSOPERA = 'INSERT', @LSTABLA = 'EDA_REGISTRO_SUCESOS', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
 
	-- FIN DE DEPURACIÓN DE TABLAS DE TIPO DE CATEGORÍAS DE DATOS DE NIVEL 3.
 
	-- FIN - SECCIÓN DE DEPURACIÓN DE LA JERARQUÍA DE CATEGORÍAS DE DATOS.
 
	-- INICIO - SECCIÓN DE DEPURACIÓN DE OTRAS RELACIONES FORÁNEAS Y DE REFERENCIAS A OBJETOS.
 
	-- BLANQUEAR VALIDACIONES CONTRA CATEGORIAS INEXISTENTES
	INSERT INTO	EDA_REGISTRO_SUCESOS (PROCEDIMIENTO, TABLA, FILAS_AFECTADAS, OPERACION, DURACION, RESULTADO, SQL_CMD)
		SELECT	@LSPROC AS PROCEDIMIENTO,
				'DETAIL_FIELD' AS TABLA,
			1 AS FILAS_AFECTADAS,
			@LS_EXEC_MODE AS OPERACION,
			0 AS DURACION,
			@LS_MD_ERROR_RH + ' PKEY = ' + CHAR(39) + PKEY + CHAR(39) + '.' AS RESULTADO,
				'UPDATE DETAIL_FIELD SET VAL_TBL_NAME = NULL WHERE (PKEY = ' + CHAR(39) + PKEY + CHAR(39) + ')' AS SQL_CMD
		FROM	DETAIL_FIELD
		WHERE	VAL_TBL_NAME NOT IN (SELECT PKEY FROM CAT_TYPE UNION SELECT PKEY FROM CAT_TYPE_EXT)
			AND NULLIF(LTRIM(RTRIM(VAL_TBL_NAME)), '') IS NOT NULL
			AND CTL_TYPE_CODE = 'campovalidable';
	SELECT @LSOPERA = 'INSERT', @LSTABLA = 'EDA_REGISTRO_SUCESOS', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
 
	INSERT INTO	EDA_REGISTRO_SUCESOS (PROCEDIMIENTO, TABLA, FILAS_AFECTADAS, OPERACION, DURACION, RESULTADO, SQL_CMD)
		SELECT	@LSPROC AS PROCEDIMIENTO,
				'ENTITY_BROWSER_DETAIL' AS TABLA,
			1 AS FILAS_AFECTADAS,
			@LS_EXEC_MODE AS OPERACION,
			0 AS DURACION,
			@LS_MD_ERROR_RH + ' PKEY = ' + CHAR(39) + PKEY + CHAR(39) + '.' AS RESULTADO,
				'UPDATE ENTITY_BROWSER_DETAIL SET VAL_TBL_NAME = NULL WHERE (PKEY = ' + CHAR(39) + PKEY + CHAR(39) + ')' AS SQL_CMD
		FROM	ENTITY_BROWSER_DETAIL
		WHERE	VAL_TBL_NAME NOT IN (SELECT PKEY FROM CAT_TYPE UNION SELECT PKEY FROM CAT_TYPE_EXT)
			AND NULLIF(LTRIM(RTRIM(VAL_TBL_NAME)), '') IS NOT NULL;
	SELECT @LSOPERA = 'INSERT', @LSTABLA = 'EDA_REGISTRO_SUCESOS', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
 
	-- PROCEDIMIENTO ALMACENADO INEXISTENTE EN EL ESQUEMA DE BASE DE DATOS DE ENGAGE.
	INSERT INTO	EDA_REGISTRO_SUCESOS (PROCEDIMIENTO, TABLA, FILAS_AFECTADAS, OPERACION, DURACION, RESULTADO, SQL_CMD)
		SELECT	@LSPROC AS PROCEDIMIENTO,
				'STORED_PROCEDURES' AS TABLA,
			1 AS FILAS_AFECTADAS,
			@LS_EXEC_MODE AS OPERACION,
			0 AS DURACION,
			@LS_MD_ERROR_RH + ' PKEY = ' + CHAR(39) + PKEY + CHAR(39) + '.' AS RESULTADO,
				'UPDATE STORED_PROCEDURES SET SP_NAME = NULL WHERE (PKEY = ' + CHAR(39) + PKEY + CHAR(39) + ')' AS SQL_CMD
		FROM	STORED_PROCEDURES
		WHERE	(LOCAL_IDR = '1')
			AND SP_NAME NOT IN (SELECT SUBPROCEDURE_NAME FROM EVI_PROCEDURES WHERE PROCEDURE_TYPE = 'PROCEDURE');
	SELECT @LSOPERA = 'INSERT', @LSTABLA = 'EDA_REGISTRO_SUCESOS', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
 
	-- PROCEDIMIENTO ALMACENADO INEXISTENTE EN EL ESQUEMA DE BASE DE DATOS DE ENGAGE.
	INSERT INTO	EDA_REGISTRO_SUCESOS (PROCEDIMIENTO, TABLA, FILAS_AFECTADAS, OPERACION, DURACION, RESULTADO, SQL_CMD)
		SELECT	@LSPROC AS PROCEDIMIENTO,
				'JOB_ACTIONS' AS TABLA,
			1 AS FILAS_AFECTADAS,
			@LS_EXEC_MODE AS OPERACION,
			0 AS DURACION,
			@LS_MD_ERROR_RH + ' PKEY = ' + CHAR(39) + PKEY + CHAR(39) + '.' AS RESULTADO,
				'UPDATE JOB_ACTIONS SET SP_PRE = NULL WHERE (PKEY = ' + CHAR(39) + PKEY + CHAR(39) + ')' AS SQL_CMD
		FROM	JOB_ACTIONS
		WHERE	NULLIF(LTRIM(RTRIM(SP_PRE)), '') IS NOT NULL
			AND SP_PRE NOT IN (SELECT SUBPROCEDURE_NAME FROM EVI_PROCEDURES WHERE PROCEDURE_TYPE = 'PROCEDURE');
	SELECT @LSOPERA = 'INSERT', @LSTABLA = 'EDA_REGISTRO_SUCESOS', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
 
	-- PROCEDIMIENTO ALMACENADO INEXISTENTE EN EL ESQUEMA DE BASE DE DATOS DE ENGAGE.
	INSERT INTO	EDA_REGISTRO_SUCESOS (PROCEDIMIENTO, TABLA, FILAS_AFECTADAS, OPERACION, DURACION, RESULTADO, SQL_CMD)
		SELECT	@LSPROC AS PROCEDIMIENTO,
				'JOB_ACTIONS' AS TABLA,
			1 AS FILAS_AFECTADAS,
			@LS_EXEC_MODE AS OPERACION,
			0 AS DURACION,
			@LS_MD_ERROR_RH + ' PKEY = ' + CHAR(39) + PKEY + CHAR(39) + '.' AS RESULTADO,
				'UPDATE JOB_ACTIONS SET SP_POST = NULL WHERE (PKEY = ' + CHAR(39) + PKEY + CHAR(39) + ')' AS SQL_CMD
		FROM	JOB_ACTIONS
		WHERE	NULLIF(LTRIM(RTRIM(SP_POST)), '') IS NOT NULL
			AND SP_POST NOT IN (SELECT SUBPROCEDURE_NAME FROM EVI_PROCEDURES WHERE PROCEDURE_TYPE = 'PROCEDURE');
	SELECT @LSOPERA = 'INSERT', @LSTABLA = 'EDA_REGISTRO_SUCESOS', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
 
	-- TABLA INEXISTENTE EN EL ESQUEMA DE BASE DE DATOS DE ENGAGE.
	INSERT INTO	EDA_REGISTRO_SUCESOS (PROCEDIMIENTO, TABLA, FILAS_AFECTADAS, OPERACION, DURACION, RESULTADO, SQL_CMD)
		SELECT	@LSPROC AS PROCEDIMIENTO,
				'ENTITY_BROWSER' AS TABLA,
			1 AS FILAS_AFECTADAS,
			@LS_EXEC_MODE AS OPERACION,
			0 AS DURACION,
			@LS_MD_ERROR_RH + ' PKEY = ' + CHAR(39) + PKEY + CHAR(39) + '.' AS RESULTADO,
				'UPDATE ENTITY_BROWSER SET ENTITY_TABLE_REL = NULL WHERE (PKEY = ' + CHAR(39) + PKEY + CHAR(39) + ')' AS SQL_CMD
		FROM	ENTITY_BROWSER
		WHERE	ENTITY_TABLE_REL NOT IN (SELECT TABLE_NAME FROM EVI_TABLES)
			AND ENTITY_TABLE_REL NOT IN (SELECT VIEW_NAME FROM EVI_VIEWS);
	SELECT @LSOPERA = 'INSERT', @LSTABLA = 'EDA_REGISTRO_SUCESOS', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
 
	-- PROCEDIMIENTO ALMACENADO INEXISTENTE EN ENGAGE PARA ENTIDAD VIRTUAL CON PKEY = 'XX'.
	INSERT INTO	EDA_REGISTRO_SUCESOS (PROCEDIMIENTO, TABLA, FILAS_AFECTADAS, OPERACION, DURACION, RESULTADO, SQL_CMD)
		SELECT	@LSPROC AS PROCEDIMIENTO,
				'ENTITY_BROWSER' AS TABLA,
			1 AS FILAS_AFECTADAS,
			@LS_EXEC_MODE AS OPERACION,
			0 AS DURACION,
			@LS_MD_ERROR_RH + ' PKEY = ' + CHAR(39) + PKEY + CHAR(39) + '.' AS RESULTADO,
				'UPDATE ENTITY_BROWSER SET SP_VAL = NULL WHERE (PKEY = ' + CHAR(39) + PKEY + CHAR(39) + ')' AS SQL_CMD
		FROM	ENTITY_BROWSER
		WHERE	VIRTUAL_IDR = '1'
			AND SP_VAL NOT IN (SELECT SP_CODE FROM STORED_PROCEDURES);
	SELECT @LSOPERA = 'INSERT', @LSTABLA = 'EDA_REGISTRO_SUCESOS', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
 
	-- PROCEDIMIENTO ALMACENADO DE VALIDACIÓN INEXISTENTE EN ENGAGE PARA ENTIDAD CON PKEY = 'XX'.
	INSERT INTO	EDA_REGISTRO_SUCESOS (PROCEDIMIENTO, TABLA, FILAS_AFECTADAS, OPERACION, DURACION, RESULTADO, SQL_CMD)
		SELECT	@LSPROC AS PROCEDIMIENTO,
				'ENTITY_BROWSER' AS TABLA,
			1 AS FILAS_AFECTADAS,
			@LS_EXEC_MODE AS OPERACION,
			0 AS DURACION,
			@LS_MD_ERROR_RH + ' PKEY = ' + CHAR(39) + PKEY + CHAR(39) + '.' AS RESULTADO,
				'UPDATE ENTITY_BROWSER SET SP_VAL = NULL WHERE (PKEY = ' + CHAR(39) + PKEY + CHAR(39) + ')' AS SQL_CMD
		FROM	ENTITY_BROWSER
		WHERE	VIRTUAL_IDR = '0'
			AND NULLIF(LTRIM(RTRIM(SP_VAL)), '') IS NOT NULL
			AND SP_VAL NOT IN (SELECT SP_CODE FROM STORED_PROCEDURES);
	SELECT @LSOPERA = 'INSERT', @LSTABLA = 'EDA_REGISTRO_SUCESOS', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
 
	-- PROCEDIMIENTO ALMACENADO DE EJECUCIÓN INEXISTENTE EN ENGAGE PARA ENTIDAD CON PKEY = 'XX'.
	INSERT INTO	EDA_REGISTRO_SUCESOS (PROCEDIMIENTO, TABLA, FILAS_AFECTADAS, OPERACION, DURACION, RESULTADO, SQL_CMD)
		SELECT	@LSPROC AS PROCEDIMIENTO,
				'ENTITY_BROWSER' AS TABLA,
			1 AS FILAS_AFECTADAS,
			@LS_EXEC_MODE AS OPERACION,
			0 AS DURACION,
			@LS_MD_ERROR_RH + ' PKEY = ' + CHAR(39) + PKEY + CHAR(39) + '.' AS RESULTADO,
				'UPDATE ENTITY_BROWSER SET SP_EJEC = NULL WHERE (PKEY = ' + CHAR(39) + PKEY + CHAR(39) + ')' AS SQL_CMD
		FROM	ENTITY_BROWSER
		WHERE	VIRTUAL_IDR = '0'
			AND NULLIF(LTRIM(RTRIM(SP_EJEC)), '') IS NOT NULL
			AND SP_EJEC NOT IN (SELECT SP_CODE FROM STORED_PROCEDURES); 
	SELECT @LSOPERA = 'INSERT', @LSTABLA = 'EDA_REGISTRO_SUCESOS', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
 
	-- FIN - SECCIÓN DE DEPURACIÓN DE OTRAS RELACIONES FORÁNEAS Y DE REFERENCIAS A OBJETOS.
 
END
ELSE BEGIN
	IF (@LS_EXEC_MODE = 'ERASE') BEGIN
		---------------------
		-- SECCION CLIENTE
		---------------------
		DELETE ENTITY_BROWSER 
		 WHERE ENTITY_TYPE = 'Cliente' 
		   AND PAR_KEY NOT IN (SELECT PKEY FROM CUSTOMER_TYPE);
		SELECT @LSOPERA = 'DELETE', @LSTABLA = 'ENTITY_BROWSER', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
		IF (@LNERRORNUM <> 0) GOTO FALLO;
 
		DELETE ACTIVITY_TYPE 
		 WHERE PAR_KEY NOT IN (SELECT PKEY FROM CUSTOMER_TYPE)
		   AND ACTIVITY_TYPE_CODE = 'CLIENTE';
		SELECT @LSOPERA = 'DELETE', @LSTABLA = 'ACTIVITY_TYPE', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
		IF (@LNERRORNUM <> 0) GOTO FALLO;
 
		DELETE STORED_PROCEDURES
		 WHERE SP_TYPE_IDR = 'Cliente' 
		   AND SP_TYPE_CODE NOT IN (SELECT CUST_TYPE_CODE FROM CUSTOMER_TYPE);
		SELECT @LSOPERA = 'DELETE', @LSTABLA = 'STORED_PROCEDURES', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
		IF (@LNERRORNUM <> 0) GOTO FALLO;
 
		DELETE TRANSACTIONS 
		 WHERE TRAN_IDR = 'Cliente' 
		   AND CALL_TYPE_CODE NOT IN (SELECT CUST_TYPE_CODE FROM CUSTOMER_TYPE);
		SELECT @LSOPERA = 'DELETE', @LSTABLA = 'TRANSACTIONS', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
		IF (@LNERRORNUM <> 0) GOTO FALLO;
 
		DELETE ALARM 
		 WHERE ALARM_TYPE = 'Cliente' 
		   AND ALARM_TYPE_CODE NOT IN (SELECT CUST_TYPE_CODE FROM CUSTOMER_TYPE);
		SELECT @LSOPERA = 'DELETE', @LSTABLA = 'ALARM', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
		IF (@LNERRORNUM <> 0) GOTO FALLO;
 
		---------------------
		-- SECCION TRAMITE
		---------------------
		DELETE JOB_TYPE 
		 WHERE CUST_TYPE_CODE NOT IN (SELECT CUST_TYPE_CODE FROM CUSTOMER_TYPE);
		SELECT @LSOPERA = 'DELETE', @LSTABLA = 'JOB_TYPE', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
		IF (@LNERRORNUM <> 0) GOTO FALLO;
 
		DELETE ACTIVITY_TYPE 
		 WHERE PAR_KEY NOT IN (SELECT PKEY FROM JOB_TYPE)
		   AND ACTIVITY_TYPE_CODE = 'TRAMITE';
		SELECT @LSOPERA = 'DELETE', @LSTABLA = 'ACTIVITY_TYPE', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
		IF (@LNERRORNUM <> 0) GOTO FALLO;
 
		DELETE POPUP_BROWSER 
		 WHERE PAR_KEY NOT IN (SELECT PKEY FROM JOB_TYPE);
		SELECT @LSOPERA = 'DELETE', @LSTABLA = 'POPUP_BROWSER', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
		IF (@LNERRORNUM <> 0) GOTO FALLO;
 
		DELETE JOB_RESULT_TYPE 
		 WHERE PAR_KEY NOT IN (SELECT PKEY FROM JOB_TYPE);
		SELECT @LSOPERA = 'DELETE', @LSTABLA = 'JOB_RESULT_TYPE', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
		IF (@LNERRORNUM <> 0) GOTO FALLO;
 
		DELETE JOB_NOTIF_BY_RULE 
		 WHERE PAR_KEY NOT IN (SELECT PKEY FROM JOB_TYPE);
		SELECT @LSOPERA = 'DELETE', @LSTABLA = 'JOB_NOTIF_BY_RULE', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
		IF (@LNERRORNUM <> 0) GOTO FALLO;
 
		DELETE JOB_NOTIF_BY_EVENT 
		 WHERE PAR_KEY NOT IN (SELECT PKEY FROM JOB_TYPE);
		SELECT @LSOPERA = 'DELETE', @LSTABLA = 'JOB_NOTIF_BY_EVENT', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
		IF (@LNERRORNUM <> 0) GOTO FALLO;
 
		DELETE JOB_DIAGRAM 
		 WHERE PAR_KEY NOT IN (SELECT PKEY FROM JOB_TYPE);
		SELECT @LSOPERA = 'DELETE', @LSTABLA = 'JOB_DIAGRAM', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
		IF (@LNERRORNUM <> 0) GOTO FALLO;
 
		DELETE ENTITY_BROWSER 
		 WHERE ENTITY_TYPE = 'Tramite' 
		   AND PAR_KEY NOT IN (SELECT PKEY FROM JOB_TYPE);
		SELECT @LSOPERA = 'DELETE', @LSTABLA = 'ENTITY_BROWSER', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
		IF (@LNERRORNUM <> 0) GOTO FALLO;
 
		DELETE JOB_ACTIONS 
		 WHERE PAR_KEY NOT IN (SELECT PKEY FROM CALL_TYPE);
		SELECT @LSOPERA = 'DELETE', @LSTABLA = 'JOB_ACTIONS', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
		IF (@LNERRORNUM <> 0) GOTO FALLO;
 
		DELETE ALARM 
		 WHERE ALARM_TYPE = 'Tramite' 
		   AND ALARM_TYPE_CODE NOT IN (SELECT JOB_TYPE_CODE FROM JOB_TYPE);
		SELECT @LSOPERA = 'DELETE', @LSTABLA = 'ALARM', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
		IF (@LNERRORNUM <> 0) GOTO FALLO;
 
		DELETE STORED_PROCEDURES
		 WHERE SP_TYPE_IDR = 'Tramite' 
		   AND SP_TYPE_CODE NOT IN (SELECT JOB_TYPE_CODE FROM JOB_TYPE);
		SELECT @LSOPERA = 'DELETE', @LSTABLA = 'STORED_PROCEDURES', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
		IF (@LNERRORNUM <> 0) GOTO FALLO;
 
		DELETE TRANSACTIONS 
		 WHERE TRAN_IDR = 'Tramite' 
		   AND CALL_TYPE_CODE NOT IN (SELECT JOB_TYPE_CODE FROM JOB_TYPE);
		SELECT @LSOPERA = 'DELETE', @LSTABLA = 'TRANSACTIONS', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
		IF (@LNERRORNUM <> 0) GOTO FALLO;
 
		DELETE POPUP_BROWSER_DETAIL 
		 WHERE PAR_KEY NOT IN (SELECT PKEY FROM POPUP_BROWSER);
		SELECT @LSOPERA = 'DELETE', @LSTABLA = 'POPUP_BROWSER_DETAIL', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
		IF (@LNERRORNUM <> 0) GOTO FALLO;
 
		DELETE JOB_NEXTATT_RULES 
		 WHERE PAR_KEY NOT IN (SELECT PKEY FROM JOB_DIAGRAM);
		SELECT @LSOPERA = 'DELETE', @LSTABLA = 'JOB_NEXTATT_RULES', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
		IF (@LNERRORNUM <> 0) GOTO FALLO;
 
		DELETE JOB_FLOW 
		 WHERE PAR_KEY NOT IN (SELECT PKEY FROM JOB_DIAGRAM);
		SELECT @LSOPERA = 'DELETE', @LSTABLA = 'JOB_FLOW', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
		IF (@LNERRORNUM <> 0) GOTO FALLO;
 
		DELETE ENTITY_VIRTUAL_DETAIL 
		 WHERE PAR_KEY NOT IN (SELECT PKEY FROM ENTITY_BROWSER);
		SELECT @LSOPERA = 'DELETE', @LSTABLA = 'ENTITY_VIRTUAL_DETAIL', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
		IF (@LNERRORNUM <> 0) GOTO FALLO;
 
		DELETE ENTITY_BROWSER_DETAIL 
		 WHERE PAR_KEY NOT IN (SELECT PKEY FROM ENTITY_BROWSER);
		SELECT @LSOPERA = 'DELETE', @LSTABLA = 'ENTITY_BROWSER_DETAIL', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
		IF (@LNERRORNUM <> 0) GOTO FALLO;
 
		---------------------
		-- SECCION ACTIVIDAD
		---------------------
		DELETE CALL_TYPE 
		 WHERE PAR_KEY NOT IN (SELECT PKEY FROM JOB_TYPE);
		SELECT @LSOPERA = 'DELETE', @LSTABLA = 'CALL_TYPE', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
		IF (@LNERRORNUM <> 0) GOTO FALLO;
 
		DELETE ALARM 
		 WHERE ALARM_TYPE = 'Atencion' 
		   AND ALARM_TYPE_CODE NOT IN (SELECT CALL_TYPE_CODE FROM CALL_TYPE);
		SELECT @LSOPERA = 'DELETE', @LSTABLA = 'ALARM', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
		IF (@LNERRORNUM <> 0) GOTO FALLO;
 
		DELETE CALL_CONV_STRUCTURES 
		 WHERE PAR_KEY NOT IN (SELECT PKEY FROM CALL_TYPE);
		SELECT @LSOPERA = 'DELETE', @LSTABLA = 'CALL_CONV_STRUCTURES', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
		IF (@LNERRORNUM <> 0) GOTO FALLO;
 
		DELETE CALL_RESULT_TYPE 
		 WHERE PAR_KEY NOT IN (SELECT PKEY FROM CALL_TYPE);
		SELECT @LSOPERA = 'DELETE', @LSTABLA = 'CALL_RESULT_TYPE', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
		IF (@LNERRORNUM <> 0) GOTO FALLO;
 
		DELETE CALL_TYPE_EMAIL 
		 WHERE PAR_KEY NOT IN (SELECT PKEY FROM CALL_TYPE);
		SELECT @LSOPERA = 'DELETE', @LSTABLA = 'CALL_TYPE_EMAIL', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
		IF (@LNERRORNUM <> 0) GOTO FALLO;
 
		DELETE JOB_DIAGRAM_MULT_INFLOWS_RULES 
		 WHERE PAR_KEY NOT IN (SELECT PKEY FROM CALL_TYPE);
		SELECT @LSOPERA = 'DELETE', @LSTABLA = 'JOB_DIAGRAM_MULT_INFLOWS_RULES', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
		IF (@LNERRORNUM <> 0) GOTO FALLO;
 
		DELETE NOT_CONTACT_REASONS 
		 WHERE PAR_KEY NOT IN (SELECT PKEY FROM CALL_TYPE);
		SELECT @LSOPERA = 'DELETE', @LSTABLA = 'NOT_CONTACT_REASONS', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
		IF (@LNERRORNUM <> 0) GOTO FALLO;
 
		DELETE QUESTION 
		 WHERE CALL_TYPE_CODE NOT IN (SELECT CALL_TYPE_CODE FROM CALL_TYPE);
		SELECT @LSOPERA = 'DELETE', @LSTABLA = 'QUESTION', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
		IF (@LNERRORNUM <> 0) GOTO FALLO;
 
		DELETE STORED_PROCEDURES
		 WHERE SP_TYPE_IDR = 'Atencion' 
		   AND SP_TYPE_CODE NOT IN (SELECT CALL_TYPE_CODE FROM CALL_TYPE);
		SELECT @LSOPERA = 'DELETE', @LSTABLA = 'STORED_PROCEDURES', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
		IF (@LNERRORNUM <> 0) GOTO FALLO;
 
		DELETE TRANSACTIONS 
		 WHERE TRAN_IDR = 'Atencion' 
		   AND CALL_TYPE_CODE NOT IN (SELECT CALL_TYPE_CODE FROM CALL_TYPE);
		SELECT @LSOPERA = 'DELETE', @LSTABLA = 'TRANSACTIONS', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
		IF (@LNERRORNUM <> 0) GOTO FALLO;
 
		DELETE ALARM_CHECKS 
		 WHERE PAR_KEY NOT IN (SELECT PKEY FROM ALARM);
		SELECT @LSOPERA = 'DELETE', @LSTABLA = 'ALARM_CHECKS', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
		IF (@LNERRORNUM <> 0) GOTO FALLO;
 
		DELETE ALARM_POPUP_DETAIL 
		 WHERE PAR_KEY NOT IN (SELECT PKEY FROM ALARM);
		SELECT @LSOPERA = 'DELETE', @LSTABLA = 'ALARM_POPUP_DETAIL', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
		IF (@LNERRORNUM <> 0) GOTO FALLO;
 
		DELETE ALARM_TRANSACTIONS 
		 WHERE PAR_KEY NOT IN (SELECT PKEY FROM ALARM);
		SELECT @LSOPERA = 'DELETE', @LSTABLA = 'ALARM_TRANSACTIONS', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
		IF (@LNERRORNUM <> 0) GOTO FALLO;
 
		DELETE CONV_STRUCTURE_STEP_NORMAL 
		 WHERE PAR_KEY NOT IN (SELECT PKEY FROM CALL_CONV_STRUCTURES);
		SELECT @LSOPERA = 'DELETE', @LSTABLA = 'CONV_STRUCTURE_STEP_NORMAL', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
		IF (@LNERRORNUM <> 0) GOTO FALLO;
 
		DELETE CONV_STRUCTURE_STEP_QUESTION 
		 WHERE PAR_KEY NOT IN (SELECT PKEY FROM CALL_CONV_STRUCTURES);
		SELECT @LSOPERA = 'DELETE', @LSTABLA = 'CONV_STRUCTURE_STEP_QUESTION', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
		IF (@LNERRORNUM <> 0) GOTO FALLO;
 
		DELETE CONV_STRUCTURE_STEP_TRAN 
		 WHERE PAR_KEY NOT IN (SELECT PKEY FROM CALL_CONV_STRUCTURES);
		SELECT @LSOPERA = 'DELETE', @LSTABLA = 'CONV_STRUCTURE_STEP_TRAN', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
		IF (@LNERRORNUM <> 0) GOTO FALLO;
 
		DELETE ANSWER 
		 WHERE PAR_KEY NOT IN (SELECT PKEY FROM QUESTION);
		SELECT @LSOPERA = 'DELETE', @LSTABLA = 'ANSWER', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
		IF (@LNERRORNUM <> 0) GOTO FALLO;
 
		DELETE SP_PRM_IN 
		 WHERE PAR_KEY NOT IN (SELECT PKEY FROM STORED_PROCEDURES);
		SELECT @LSOPERA = 'DELETE', @LSTABLA = 'SP_PRM_IN', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
		IF (@LNERRORNUM <> 0) GOTO FALLO;
 
		DELETE SP_PRM_OUT 
		 WHERE PAR_KEY NOT IN (SELECT PKEY FROM STORED_PROCEDURES);
		SELECT @LSOPERA = 'DELETE', @LSTABLA = 'SP_PRM_OUT', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
		IF (@LNERRORNUM <> 0) GOTO FALLO;
 
		DELETE TRAN_PRM_IN 
		 WHERE PAR_KEY NOT IN (SELECT PKEY FROM TRANSACTIONS);
		SELECT @LSOPERA = 'DELETE', @LSTABLA = 'TRAN_PRM_IN', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
		IF (@LNERRORNUM <> 0) GOTO FALLO;
 
		DELETE TRAN_PRM_OUT 
		 WHERE PAR_KEY NOT IN (SELECT PKEY FROM TRANSACTIONS);
		SELECT @LSOPERA = 'DELETE', @LSTABLA = 'TRAN_PRM_OUT', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
		IF (@LNERRORNUM <> 0) GOTO FALLO;
 
		DELETE DETAIL_FIELD 
		 WHERE PAR_KEY NOT IN (SELECT PKEY FROM CONV_STRUCTURE_STEP_NORMAL);
		SELECT @LSOPERA = 'DELETE', @LSTABLA = 'DETAIL_FIELD', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
		IF (@LNERRORNUM <> 0) GOTO FALLO;
 
		DELETE DETAIL_FILE 
		 WHERE PAR_KEY NOT IN (SELECT PKEY FROM CONV_STRUCTURE_STEP_NORMAL);
		SELECT @LSOPERA = 'DELETE', @LSTABLA = 'DETAIL_FILE', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
		IF (@LNERRORNUM <> 0) GOTO FALLO;
 
		DELETE DETAIL_LABEL 
		 WHERE PAR_KEY NOT IN (SELECT PKEY FROM CONV_STRUCTURE_STEP_NORMAL 
								UNION SELECT PKEY FROM CONV_STRUCTURE_STEP_QUESTION);
		SELECT @LSOPERA = 'DELETE', @LSTABLA = 'DETAIL_LABEL', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
		IF (@LNERRORNUM <> 0) GOTO FALLO;
 
		DELETE STEP_CHECKS 
		 WHERE PAR_KEY NOT IN (SELECT PKEY FROM CONV_STRUCTURE_STEP_NORMAL);
		SELECT @LSOPERA = 'DELETE', @LSTABLA = 'STEP_CHECKS', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
		IF (@LNERRORNUM <> 0) GOTO FALLO;
 
		DELETE STEP_NORMAL_FLOW 
		 WHERE PAR_KEY NOT IN (SELECT PKEY FROM CONV_STRUCTURE_STEP_NORMAL
							   UNION SELECT PKEY FROM CONV_STRUCTURE_STEP_QUESTION);
		SELECT @LSOPERA = 'DELETE', @LSTABLA = 'STEP_NORMAL_FLOW', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
		IF (@LNERRORNUM <> 0) GOTO FALLO;
 
		DELETE STEP_RESULTS 
		 WHERE PAR_KEY NOT IN (SELECT PKEY FROM CONV_STRUCTURE_STEP_NORMAL
								UNION SELECT PKEY FROM CONV_STRUCTURE_STEP_QUESTION
								UNION SELECT PKEY FROM CONV_STRUCTURE_STEP_TRAN);
		SELECT @LSOPERA = 'DELETE', @LSTABLA = 'STEP_RESULTS', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
		IF (@LNERRORNUM <> 0) GOTO FALLO;
 
		DELETE DETAIL_SPREAD 
		 WHERE PAR_KEY NOT IN (SELECT PKEY FROM CONV_STRUCTURE_STEP_QUESTION);
		SELECT @LSOPERA = 'DELETE', @LSTABLA = 'DETAIL_SPREAD', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
		IF (@LNERRORNUM <> 0) GOTO FALLO;
 
		DELETE STEP_QUESTION_FLOW 
		 WHERE PAR_KEY NOT IN (SELECT PKEY FROM CONV_STRUCTURE_STEP_QUESTION);
		SELECT @LSOPERA = 'DELETE', @LSTABLA = 'STEP_QUESTION_FLOW', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
		IF (@LNERRORNUM <> 0) GOTO FALLO;
 
		DELETE STEP_TRANSACTION_FLOW 
		 WHERE PAR_KEY NOT IN (SELECT PKEY FROM CONV_STRUCTURE_STEP_TRAN);
		SELECT @LSOPERA = 'DELETE', @LSTABLA = 'STEP_TRANSACTION_FLOW', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
		IF (@LNERRORNUM <> 0) GOTO FALLO;
 
		DELETE SP_PRM_OUT_VALUE 
		 WHERE PAR_KEY NOT IN (SELECT PKEY FROM SP_PRM_OUT);
		SELECT @LSOPERA = 'DELETE', @LSTABLA = 'SP_PRM_OUT_VALUE', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
		IF (@LNERRORNUM <> 0) GOTO FALLO;
 
		DELETE TRAN_PRM_VALUE 
		 WHERE PAR_KEY NOT IN (SELECT PKEY FROM TRAN_PRM_OUT);
		SELECT @LSOPERA = 'DELETE', @LSTABLA = 'TRAN_PRM_VALUE', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
		IF (@LNERRORNUM <> 0) GOTO FALLO;
 
		DELETE STEP_CHECKS_SP 
		 WHERE PAR_KEY NOT IN (SELECT PKEY FROM STEP_CHECKS);
		SELECT @LSOPERA = 'DELETE', @LSTABLA = 'STEP_CHECKS_SP', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
		IF (@LNERRORNUM <> 0) GOTO FALLO;
 
		DELETE SCRIPT_TABLE 
		 WHERE STEP_KEY NOT IN (SELECT PKEY FROM CONV_STRUCTURE_STEP_NORMAL);
		SELECT @LSOPERA = 'DELETE', @LSTABLA = 'SCRIPT_TABLE', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
		IF (@LNERRORNUM <> 0) GOTO FALLO;
 
		DELETE CUSTOMER_DOCUMENTS_ATT 
		 WHERE CALL_TYPE_REL NOT IN (SELECT CALL_TYPE_CODE FROM CALL_TYPE);
		SELECT @LSOPERA = 'DELETE', @LSTABLA = 'CUSTOMER_DOCUMENTS_ATT', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
		IF (@LNERRORNUM <> 0) GOTO FALLO;
 
		DELETE CUSTOMER_DOCUMENTS 
		 WHERE CALL_TYPE_CODE NOT IN (SELECT CALL_TYPE_CODE FROM CALL_TYPE);
		SELECT @LSOPERA = 'DELETE', @LSTABLA = 'CUSTOMER_DOCUMENTS', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
		IF (@LNERRORNUM <> 0) GOTO FALLO;
 
		---------------------
		-- SECCION CATEGORIAS
		---------------------
		DELETE CAT_DATA
		 WHERE PAR_KEY NOT IN (SELECT PKEY FROM CAT_TYPE);
		SELECT @LSOPERA = 'DELETE', @LSTABLA = 'CAT_DATA', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
		IF (@LNERRORNUM <> 0) GOTO FALLO;
 
		UPDATE CAT_TYPE SET PAR_KEY = NULL
		 WHERE PAR_KEY NOT IN (SELECT PKEY FROM CAT_TYPE)
		   AND NULLIF(LTRIM(RTRIM(PAR_KEY)), '') IS NOT NULL;
		SELECT @LSOPERA = 'UPDATE', @LSTABLA = 'CAT_TYPE', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
		IF (@LNERRORNUM <> 0) GOTO FALLO;
 
		UPDATE CAT_TYPE SET CAT_TYPE_GROUP = NULL
		 WHERE CAT_TYPE_GROUP NOT IN (SELECT PKEY FROM CAT_TYPE_GROUP)
		   AND NULLIF(LTRIM(RTRIM(CAT_TYPE_GROUP)), '') IS NOT NULL;
		SELECT @LSOPERA = 'UPDATE', @LSTABLA = 'CAT_TYPE', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
		IF (@LNERRORNUM <> 0) GOTO FALLO;
 
		UPDATE CAT_TYPE_GROUP SET PAR_KEY = NULL
		 WHERE PAR_KEY NOT IN (SELECT PKEY FROM CAT_TYPE_GROUP)
		   AND NULLIF(LTRIM(RTRIM(PAR_KEY)), '') IS NOT NULL;
		SELECT @LSOPERA = 'UPDATE', @LSTABLA = 'CAT_TYPE_GROUP', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
		IF (@LNERRORNUM <> 0) GOTO FALLO;
 
		IF (CURSOR_STATUS('LOCAL', 'LOCUR1') >= 0) BEGIN
			-- CIERRA Y DESALOJA EL CURSOR.
			CLOSE LOCUR1;
			DEALLOCATE LOCUR1;
		END;
		DECLARE LOCUR1 CURSOR LOCAL FAST_FORWARD TYPE_WARNING FOR
				SELECT PKEY, PARENT_CAT_DATA_PKEY
				  FROM CAT_DATA
				 WHERE NULLIF(LTRIM(RTRIM(PARENT_CAT_DATA_PKEY)), '') IS NOT NULL
				   AND PARENT_CAT_DATA_PKEY NOT IN (SELECT PKEY FROM CAT_DATA);
		OPEN LOCUR1;
		FETCH NEXT FROM LOCUR1 INTO @LS_CLAVE, @LS_DATO;
		WHILE (@@FETCH_STATUS = 0) BEGIN
			PRINT 'ATENCION! Referencia no válida: CAT_DATA -> PARENT_CAT_DATA_PKEY = ' + CHAR(39) + @LS_DATO + CHAR(39) + ' ; PKEY = ' + CHAR(39) + @LS_CLAVE + CHAR(39);
			FETCH NEXT FROM LOCUR1 INTO @LS_CLAVE, @LS_DATO;
		END;
		CLOSE LOCUR1;
		DEALLOCATE LOCUR1;
 
		---------------------
		-- SECCION VALIDACIONES Y REFERENCIAS
		---------------------
		-- BLANQUEAR VALIDACIONES CONTRA CATEGORIAS INEXISTENTES
		DECLARE LOCUR1 CURSOR LOCAL FAST_FORWARD TYPE_WARNING FOR
				SELECT PKEY, VAL_TBL_NAME
				  FROM DETAIL_FIELD
		 WHERE VAL_TBL_NAME NOT IN (SELECT PKEY FROM CAT_TYPE UNION SELECT PKEY FROM CAT_TYPE_EXT)
		   AND NULLIF(LTRIM(RTRIM(VAL_TBL_NAME)), '') IS NOT NULL
		   AND CTL_TYPE_CODE = 'campovalidable';
		OPEN LOCUR1;
		FETCH NEXT FROM LOCUR1 INTO @LS_CLAVE, @LS_DATO;
		WHILE (@@FETCH_STATUS = 0) BEGIN
			PRINT 'ATENCION! Validación de campo en pantalla hacia categ. inexist.: DETAIL_FIELD -> VAL_TBL_NAME = ' + CHAR(39) + @LS_DATO + CHAR(39) + ' ; PKEY = ' + CHAR(39) + @LS_CLAVE + CHAR(39);
			FETCH NEXT FROM LOCUR1 INTO @LS_CLAVE, @LS_DATO;
		END;
		CLOSE LOCUR1;
		DEALLOCATE LOCUR1;
 
		DECLARE LOCUR1 CURSOR LOCAL FAST_FORWARD TYPE_WARNING FOR
				SELECT PKEY, VAL_TBL_NAME
				  FROM ENTITY_BROWSER_DETAIL
		 WHERE VAL_TBL_NAME NOT IN (SELECT PKEY FROM CAT_TYPE UNION SELECT PKEY FROM CAT_TYPE_EXT)
		   AND NULLIF(LTRIM(RTRIM(VAL_TBL_NAME)), '') IS NOT NULL;
		OPEN LOCUR1;
		FETCH NEXT FROM LOCUR1 INTO @LS_CLAVE, @LS_DATO;
		WHILE (@@FETCH_STATUS = 0) BEGIN
			PRINT 'ATENCION! Validación de campo de entidad hacia categ. inexist.: ENTITY_BROWSER_DETAIL -> VAL_TBL_NAME = ' + CHAR(39) + @LS_DATO + CHAR(39) + ' ; PKEY = ' + CHAR(39) + @LS_CLAVE + CHAR(39);
			FETCH NEXT FROM LOCUR1 INTO @LS_CLAVE, @LS_DATO;
		END;
		CLOSE LOCUR1;
		DEALLOCATE LOCUR1;
 
		-- PROCEDIMIENTO ALMACENADO INEXISTENTE EN EL ESQUEMA DE BASE DE DATOS DE ENGAGE.
		DECLARE LOCUR1 CURSOR LOCAL FAST_FORWARD TYPE_WARNING FOR
				SELECT PKEY, SP_NAME
				  FROM STORED_PROCEDURES
				 WHERE (LOCAL_IDR = '1')
				   AND SP_NAME NOT IN (SELECT SUBPROCEDURE_NAME FROM EVI_PROCEDURES WHERE PROCEDURE_TYPE = 'PROCEDURE');
		OPEN LOCUR1;
		FETCH NEXT FROM LOCUR1 INTO @LS_CLAVE, @LS_DATO;
		WHILE (@@FETCH_STATUS = 0) BEGIN
			PRINT 'ATENCION! P.A. inexist. en esquema de base: STORED_PROCEDURES -> SP_NAME = ' + CHAR(39) + @LS_DATO + CHAR(39) + ' ; PKEY = ' + CHAR(39) + @LS_CLAVE + CHAR(39);
			FETCH NEXT FROM LOCUR1 INTO @LS_CLAVE, @LS_DATO;
		END;
		CLOSE LOCUR1;
		DEALLOCATE LOCUR1;
 
		-- TABLA INEXISTENTE EN EL ESQUEMA DE BASE DE DATOS DE ENGAGE.
		DECLARE LOCUR1 CURSOR LOCAL FAST_FORWARD TYPE_WARNING FOR
				SELECT PKEY, ENTITY_TABLE_REL
				  FROM ENTITY_BROWSER
				 WHERE ENTITY_TABLE_REL NOT IN (SELECT TABLE_NAME FROM EVI_TABLES)
				   AND ENTITY_TABLE_REL NOT IN (SELECT VIEW_NAME FROM EVI_VIEWS);
		OPEN LOCUR1;
		FETCH NEXT FROM LOCUR1 INTO @LS_CLAVE, @LS_DATO;
		WHILE (@@FETCH_STATUS = 0) BEGIN
			PRINT 'ATENCION! Tabla/Vista inexist. en esquema de base: ENTITY_BROWSER -> ENTITY_TABLE_REL = ' + CHAR(39) + @LS_DATO + CHAR(39) + ' ; PKEY = ' + CHAR(39) + @LS_CLAVE + CHAR(39);
			FETCH NEXT FROM LOCUR1 INTO @LS_CLAVE, @LS_DATO;
		END;
		CLOSE LOCUR1;
		DEALLOCATE LOCUR1;
 
		-- PROCEDIMIENTO ALMACENADO INEXISTENTE EN ENGAGE PARA ENTIDAD VIRTUAL CON PKEY = 'XX'.
		DECLARE LOCUR1 CURSOR LOCAL FAST_FORWARD TYPE_WARNING FOR
				SELECT PKEY, SP_VAL
				  FROM ENTITY_BROWSER
				 WHERE VIRTUAL_IDR = '1'
				   AND SP_VAL NOT IN (SELECT SP_CODE FROM STORED_PROCEDURES);
		OPEN LOCUR1;
		FETCH NEXT FROM LOCUR1 INTO @LS_CLAVE, @LS_DATO;
		WHILE (@@FETCH_STATUS = 0) BEGIN
			PRINT 'ATENCION! P.A. inexist. en Engage para entidad virtual: ENTITY_BROWSER -> SP_VAL = ' + CHAR(39) + @LS_DATO + CHAR(39) + ' ; PKEY = ' + CHAR(39) + @LS_CLAVE + CHAR(39);
			FETCH NEXT FROM LOCUR1 INTO @LS_CLAVE, @LS_DATO;
		END;
		CLOSE LOCUR1;
		DEALLOCATE LOCUR1;
 
		-- PROCEDIMIENTO ALMACENADO DE VALIDACIÓN INEXISTENTE EN ENGAGE PARA ENTIDAD CON PKEY = 'XX'.
		DECLARE LOCUR1 CURSOR LOCAL FAST_FORWARD TYPE_WARNING FOR
				SELECT PKEY, SP_VAL
				  FROM ENTITY_BROWSER
				 WHERE VIRTUAL_IDR = '0'
				   AND NULLIF(LTRIM(RTRIM(SP_VAL)), '') IS NOT NULL
				   AND SP_VAL NOT IN (SELECT SP_CODE FROM STORED_PROCEDURES);
		OPEN LOCUR1;
		FETCH NEXT FROM LOCUR1 INTO @LS_CLAVE, @LS_DATO;
		WHILE (@@FETCH_STATUS = 0) BEGIN
			PRINT 'ATENCION! P.A. de validación inexist. en Engage para entidad: ENTITY_BROWSER -> SP_VAL = ' + CHAR(39) + @LS_DATO + CHAR(39) + ' ; PKEY = ' + CHAR(39) + @LS_CLAVE + CHAR(39);
			FETCH NEXT FROM LOCUR1 INTO @LS_CLAVE, @LS_DATO;
		END;
		CLOSE LOCUR1;
		DEALLOCATE LOCUR1;
 
		-- PROCEDIMIENTO ALMACENADO DE EJECUCIÓN INEXISTENTE EN ENGAGE PARA ENTIDAD CON PKEY = 'XX'.
		DECLARE LOCUR1 CURSOR LOCAL FAST_FORWARD TYPE_WARNING FOR
			SELECT	PKEY,
				SP_EJEC
			FROM	ENTITY_BROWSER
			WHERE	(VIRTUAL_IDR = '0')
				AND NULLIF(LTRIM(RTRIM(SP_EJEC)), '') IS NOT NULL
				AND SP_EJEC NOT IN (SELECT SP_CODE FROM STORED_PROCEDURES); 
 
		OPEN LOCUR1;
		FETCH NEXT FROM LOCUR1 INTO @LS_CLAVE, @LS_DATO;
 
		WHILE (@@FETCH_STATUS = 0) BEGIN
			PRINT 'ATENCION! P.A. de ejecución inexist. en Engage para entidad: ENTITY_BROWSER -> SP_EJEC = ' + CHAR(39) + @LS_DATO + CHAR(39) + ' ; PKEY = ' + CHAR(39) + @LS_CLAVE + CHAR(39);
			FETCH NEXT FROM LOCUR1 INTO @LS_CLAVE, @LS_DATO;
		END;
 
		CLOSE LOCUR1;
		DEALLOCATE LOCUR1;
	END;
END;
 
FALLO:
-- REGISTRO DE SUCESOS Y CONTROL DE FIN DE PROCEDIMIENTO. CONCLUYE LA TRANSACCIÓN SI TODO FUE EXITOSO.
SELECT @LNDURACION = DATEDIFF(SECOND, @LDINICIO_OPE, GETDATE()), @LNSEVERITY = ISNULL(EM.SEVERITY, 16), @LSERRORDESC = 'ERROR ' + CONVERT(VARCHAR, ISNULL(EM.ERROR, 0)) + ' - ' + ISNULL(EM.DESCRIPTION, ' ') FROM MASTER.DBO.SYSMESSAGES EM WHERE (EM.ERROR = @LNERRORNUM);
IF (@LNERRORNUM <> 0) BEGIN
	-- NOTIFICACIÓN EN EL REGISTRO DE SQL SERVER.
	SET @LSERRORLOG = @LSERRORLOG + CASE WHEN (ISNULL(CHARINDEX('%', @LSERRORDESC), 0) > 0) THEN RTRIM(LEFT(@LSERRORDESC, 11)) ELSE @LSERRORDESC END;
	-- DEVUELVE EL ERROR EN EL PARÁMETRO DE SALIDA.
	SET @PS_RET_MESSAGE = SUBSTRING(@LSERRORDESC, 1, 440);
	-- DESHACE LA TRANSACCIÓN COMPLETA SI LA OPERACIÓN FALLÓ.
	IF (@@TRANCOUNT > 0) ROLLBACK TRANSACTION;
	EXECUTE @LNERRORNUM = PA_SYS_REGISTRO_SUCESOS_INSERT @PSPROCEDIMIENTO_1 = @LSPROC, @PSTABLA_2 = @LSTABLA, @PNFILAS_AFECTADAS_3 = @LNFILAS_AFEC, @PSOPERACION_4 = @LSOPERA, @PNDURACION_5 = @LNDURACION, @PSRESULTADO_6 = @LSERRORDESC, @PSSQL_CMD_7 = @LSERRORDESC;
	-- RAISERROR(@LSERRORLOG, @LNSEVERITY, -1) WITH NOWAIT;
END
ELSE BEGIN
	-- EXECUTE @LNERRORNUM = PA_SYS_REGISTRO_SUCESOS_INSERT @PSPROCEDIMIENTO_1 = @LSPROC, @PSTABLA_2 = @LSTABLA, @PNFILAS_AFECTADAS_3 = @LNFILAS_AFEC, @PSOPERACION_4 = @LSOPERA, @PNDURACION_5 = @LNDURACION, @PSRESULTADO_6 = @LSERRORDESC, @PSSQL_CMD_7 = @LSERRORDESC;
	IF (@@TRANCOUNT > 0) COMMIT TRANSACTION;
END;
RETURN;
