CREATE PROCEDURE [dbo].[HOME_ADD_HONORARIO]
(@IPKEYJOB	AS VARCHAR(100),
 @IAGENTE	AS VARCHAR(100),
 @OCODE		AS VARCHAR(2) OUTPUT,
 @OMENSAJE	AS VARCHAR(400) OUTPUT)
AS
 
DECLARE	@VPROYECTO				VARCHAR(50),
		@VSERVICIO				VARCHAR(50),
		@VPROYECTO_SERV			VARCHAR(50),
		@VTIPO_SERV				VARCHAR(50),
		@VPROVEEDOR_ID			VARCHAR(50),
		@VTIPO_PROV				VARCHAR(50),
		@VNRO_FACTURA_PROV		VARCHAR(50),
		@VCANT_PERSONAS_PROV	VARCHAR(50),
		@VDESCRIP_SERVICIO_PROV	VARCHAR(100),
		@VFECHA_FACTURA_PROV	DATETIME,
		@VPRECIO_FINAL_PROV		VARCHAR(50),
		@VFORMA_PAGO_PROV		VARCHAR(50),
		@VCANT_CUOTAS_PROV		VARCHAR(50),
		@VESTADO_PAGO_PROV		VARCHAR(50),
		@VFECHA_ULT_PAGO_PROV	DATETIME,
		@VPRECIO_CUOTA_PROV		VARCHAR(50),
		@VFECHA_PROX_VTO_PROV	DATETIME,
		@VSALDO_PEND_PROV		VARCHAR(50),
		@VDESTINO_PROV			VARCHAR(100),
		@VFECHA_DESDE_SERV_PROV	DATETIME,
		@VFECHA_HASTA_SERV_PROV	DATETIME,
		@VCANT					INT,
		@UNITDESC				VARCHAR(300),
		@USERDESC				VARCHAR(300),
		@VAGENDA_ID				VARCHAR(50),
		@VERROR					VARCHAR(50),
		@VCLIENTE				VARCHAR(300),
		@VIDCLIENTE				VARCHAR(100),
		@VNORMA					VARCHAR(300),
		@VFECHA					VARCHAR(50),
		@VDIASP					VARCHAR(50),
		@VTIPO_CONSULTOR		VARCHAR(50),
		@VCONSULTOR				VARCHAR(50),
		@VTIENE_CONS			VARCHAR(50),
		@VTIENE_OBS				VARCHAR(50),
		@VFECHA_HONOR			DATETIME,
		@VLUGAR					VARCHAR(300),
		@VCONSULTOR_HONOR		VARCHAR(50),
		@VIMPORTE				VARCHAR(50),
		@VID_SELEC				VARCHAR(100)
 
BEGIN	
 
	SET @OCODE = '0'
	SET @OMENSAJE = ''
 
	SELECT	@VAGENDA_ID = ISNULL(AGENDA_ID,''),
			@VERROR = ISNULL(ERROR,'')
	FROM	XAGENDA
	WHERE	PAR_KEY = @IPKEYJOB
 
	SELECT	@VPROYECTO  = ID_PROYECTO,
			@VSERVICIO  = ID_SERVICIO
	FROM	LK_AGENDA
	WHERE	ID_AGENDA = @VAGENDA_ID
 
	SELECT	@VID_SELEC		= ISNULL(HOJA_RUTA_ID,''),
			@VFECHA_HONOR	=	ISNULL(HONOR_FECHA,''),
			@VLUGAR			=	ISNULL(HONOR_LUGAR,''),
			@VCONSULTOR_HONOR = ISNULL(HONOR_CONSULTOR,''),
			@VIMPORTE		=	ISNULL(HONOR_IMPORTE,'')
	FROM	XAGENDA
	WHERE	PAR_KEY = @IPKEYJOB
	
 
	IF (@VFECHA_HONOR = '') BEGIN
		SET @OCODE = '1'
			
		UPDATE	XAGENDA
		SET		ERROR = 'SI', DESC_ERROR = 'Debe Completar el Campo Fecha'
		WHERE	PAR_KEY = @IPKEYJOB
		RETURN
	END
 
	IF (@VCONSULTOR_HONOR = '') BEGIN
		SET @OCODE = '1'
			
		UPDATE	XAGENDA
		SET		ERROR = 'SI', DESC_ERROR = 'Debe Completar el Campo Consultor'
		WHERE	PAR_KEY = @IPKEYJOB
		RETURN
			
	END
	
	IF (@VID_SELEC = '') BEGIN 
 
		INSERT INTO LK_PROYECTO_HONORARIOS
		(ID_PROYECTO, ID_TIPO_SERVICIO, ID_AGENDA, ID_CONSULTOR, FECHA, LUGAR, IMPORTE)
		VALUES
		(@VPROYECTO, @VSERVICIO, @VAGENDA_ID, @VCONSULTOR_HONOR, @VFECHA_HONOR, @VLUGAR, @VIMPORTE)
 
	END ELSE BEGIN
 
		UPDATE	LK_PROYECTO_HONORARIOS
		SET		ID_CONSULTOR = @VCONSULTOR_HONOR, FECHA = @VFECHA_HONOR, LUGAR = @VLUGAR, IMPORTE = @VIMPORTE
		WHERE	ID_PROYECTO_HONORARIOS = @VID_SELEC
 
	END
 
	IF (@OCODE = '0') BEGIN
		UPDATE	XAGENDA
		SET		ERROR = 'NO', DESC_ERROR = NULL
		WHERE	PAR_KEY = @IPKEYJOB
	END
END
 
