CREATE   PROCEDURE [dbo].[SV_01_CMB_GRUPO_DOC_DET]
(@IPKEYJOB	AS VARCHAR(100))
AS
 
DECLARE @VCLAVE_DOC	VARCHAR(100)
 
BEGIN
 
	SELECT	@VCLAVE_DOC = CLAVE_DOC
	FROM	TMT_SV_01
	WHERE	PAR_KEY = @IPKEYJOB
 
	SELECT	CAT_DATA_CODE AS CAT_DATA_CODE,
			CAT_DATA_DESC AS CAT_DATA_DESC,
			'TRUE'
	FROM	CAT_DATA
	WHERE	PAR_KEY = (SELECT PKEY FROM CAT_TYPE WHERE CAT_TYPE_CODE = 'GRUPO_DOC_DET')
	AND		CHARINDEX(@VCLAVE_DOC,ATTR1) > 0
	ORDER BY CAT_DATA_DESC
	
END
 
