CREATE PROCEDURE [dbo].[HOME_MOD_INFO_CAPA]
(@IPKEYJOB	AS VARCHAR(100),
 @IAGENTE	AS VARCHAR(100),
 @OCODE		AS VARCHAR(2) OUTPUT,
 @OMENSAJE	AS VARCHAR(400) OUTPUT)
AS
 
DECLARE	@VPROYECTO			VARCHAR(50),
		@VPROYECTO_SERV		VARCHAR(50),
		@VSERVICIO			VARCHAR(50),
		@VFECHA				DATETIME,
		@VOBSERVACION		VARCHAR(400),
		@VID_DOC			VARCHAR(50),
		@VID_PROYECTO_DOCUM	VARCHAR(50),
		@VDESC_DOC_DET		VARCHAR(400), 
		@VGRUPO_DOC_DET		VARCHAR(50),
		@VCANT				INT,
		@VERROR				VARCHAR(50),
		@VAGENDA_ID			VARCHAR(50),
		@VTIPO				VARCHAR(50),
		@VADJUNTO	VARCHAR(100),
		@VADJUNTO_ANT	VARCHAR(100),
		@VINFORME	VARCHAR(50)	
 
BEGIN	
 
	SET @OCODE = '0'
	SET @OMENSAJE = ''
 
	SELECT	--@VAGENDA_ID = ISNULL(AGENDA_ID,''),
			@VFECHA = ISNULL(CAPA_FECHA_IC,''),
			@VOBSERVACION = ISNULL(CAPA_OBSERV_IC,''),
			@VERROR = ISNULL(ERROR,''),
			@VTIPO = ISNULL(TIPO_SELEC,''),
			@VINFORME = ISNULL(ID_MINUTA,'')
	FROM	XAGENDA
	WHERE	PAR_KEY = @IPKEYJOB
 
	SELECT	@VADJUNTO_ANT = ISNULL(ID_ADJUNTO,'')
	FROM	LK_PROYECTO_DOCUM
	WHERE	ID_PROYECTO_DOCUM = @VINFORME
 
	SELECT	@VADJUNTO = ISNULL(PKEY,'')
	FROM	PHYSICAL_ATTACHED_DOCUMENT
	WHERE	PAR_KEY = @IPKEYJOB
 
	IF @VERROR = '' BEGIN
		SET @OCODE = '0'
		SET @OMENSAJE = ''
 
	END ELSE BEGIN
 
		IF (@VFECHA = '') BEGIN
			SET @OCODE = '1'
			SET @OMENSAJE = '<html>
							<body>
							  <div class="w3-panel w3-pale-red" style="height: 20px;">
									<font style="font-family:Tahoma, Arial, Helvetica, sans-serif;font-size:12px;color:#641E16"><b>Debe completar el Campo Fecha</b></font>
							  </div>
							</div>
							</body>
							</html>'
			
			UPDATE	XAGENDA
			SET		ERROR = 'SI'
			WHERE	PAR_KEY = @IPKEYJOB
			RETURN
		END
	
		BEGIN
		
			UPDATE	LK_PROYECTO_DOCUM
			SET		FECHA_DOCUM = @VFECHA,
					OBSERVACIONES = @VOBSERVACION,
					ID_ADJUNTO = ISNULL(@VADJUNTO,@VADJUNTO_ANT)
			WHERE	ID_PROYECTO_DOCUM = @VINFORME
 
		END
 
		IF (@VADJUNTO <> '') BEGIN
			UPDATE	PHYSICAL_ATTACHED_DOCUMENT
			SET		PAR_KEY = @VPROYECTO
			WHERE	PKEY = @VADJUNTO
 
			DELETE	PHYSICAL_ATTACHED_DOCUMENT
			WHERE	PKEY = @VADJUNTO_ANT
		END
 
		UPDATE	XAGENDA
		SET		CAPA_FECHA_IC = NULL,
				CAPA_OBSERV_IC = NULL
		WHERE	PAR_KEY = @IPKEYJOB
	END
 
	
	IF (@OCODE = '0') BEGIN
		UPDATE	XAGENDA
		SET		ERROR = 'NO'
		WHERE	PAR_KEY = @IPKEYJOB
	END
END
