CREATE PROCEDURE [dbo].[SP_VAL_NUEVO_CONTACTO_OP]
(@PKEY_JOB VARCHAR (100), @RTA AS VARCHAR(1) OUTPUT)
AS
DECLARE
@LS_TIPO_DOC   VARCHAR(50),
@LS_NRO_DOC	   VARCHAR(12),
@LS_PRIMARY_ID	VARCHAR(50)
 
BEGIN	
	
	SELECT 
		@LS_TIPO_DOC=TIPO_DOC, 
		@LS_NRO_DOC	= NRO_DOC
	FROM OPERATIVO
	WHERE PAR_KEY = @PKEY_JOB;
	
	SET @LS_PRIMARY_ID = LTRIM(RTRIM(@LS_TIPO_DOC))+LTRIM(RTRIM(@LS_NRO_DOC));
	
	SET @RTA= (SELECT  COUNT(*) FROM CUSTOMER 	WHERE CUST_PRIMARY_ID = @LS_PRIMARY_ID)
		   
END
 
 
 
 
