CREATE PROCEDURE [dbo].[PA_SYS_PSESSIONS_FAILURES_INS] (@PS_USER_ID VARCHAR(30), @PN_ATTEMPT_NUMBER NUMERIC(2, 0), @PN_ACCOUNT_STATE NUMERIC(1, 0), @PS_MODULE_NAME VARCHAR(20) = NULL, @PS_STATION_NAME VARCHAR(20) = NULL, @PS_DOMAIN_SERVER VARCHAR(20) = NULL, @PS_RET_MESSAGE VARCHAR(440) = NULL OUTPUT) AS
 
-- =========================================================================================================================
-- AUTOR: TITO - ENGAGE SOFTWARE COMPANY
-- FECHA DE CREACIÓN: 12/06/2009
-- EDITOR: TITO - ENGAGE SOFTWARE COMPANY
-- FECHA DE MODIFICACIÓN: 12/06/2009
-- TABLAS LEÍDAS:
-- TABLAS MODIFICADAS: PSESSIONS_FAILURES.
-- DESCRIPCIÓN: PROCEDIMIENTO QUE INSERTA UN REGISTRO EN LA TABLA PSESSIONS_FAILURES.
-- CONSIDERACIONES:
-- 1. EL PARÁMETRO DE SALIDA @PS_RET_MESSAGE DEVUELVE EL MENSAJE DE ERROR. NULL SI NO HUBO.
-- =========================================================================================================================
 
SET NOCOUNT ON;
SET XACT_ABORT ON;
 
-- DECLARACIÓN E INICIALIZACIÓN DE VARIABLES DE ERROR Y AUXILIARES.
DECLARE @LNERRORNUM AS INTEGER,
	@LNSEVERITY AS SMALLINT,
	@LNFILAS_AFEC AS INTEGER,
	@LDINICIO_OPE AS DATETIME,
	@LNDURACION AS INTEGER,
	@LSOPERA AS VARCHAR(30),
	@LSPROC AS VARCHAR(30),
	@LSTABLA AS VARCHAR(30),
	@LSERRORLOG AS VARCHAR(440),
	@LSERRORDESC AS VARCHAR(440),
	@LSSQL_CMD AS VARCHAR(4000)
;
SELECT 	@LNERRORNUM = 0,
	@LNSEVERITY = 16,
	@LNFILAS_AFEC = 0,
	@LDINICIO_OPE = GETDATE(),
	@LNDURACION = 0,
	@LSOPERA = 'EXECUTE',
	@LSPROC = OBJECT_NAME(@@PROCID),
	@LSTABLA = 'NINGUNA',
	@LSERRORLOG = @@SERVERNAME + '.' + DB_NAME() + '.' + USER_NAME() + '.' + OBJECT_NAME(@@PROCID) + ' - ',
	@LSERRORDESC = NULL,
	@LSSQL_CMD = NULL
;
DECLARE
@LS_USER_ID VARCHAR(30),
@LN_ATTEMPT_NUMBER NUMERIC(2, 0),
@LN_ACCOUNT_STATE NUMERIC(1, 0),
@LS_MODULE_NAME VARCHAR(20),
@LS_STATION_NAME VARCHAR(20),
@LS_DOMAIN_SERVER VARCHAR(20)
;
SELECT	@LS_USER_ID = ISNULL(NULLIF(@PS_USER_ID, ''), 'EMPTY'),
	@LN_ATTEMPT_NUMBER = ISNULL(@PN_ATTEMPT_NUMBER, 0),
	@LN_ACCOUNT_STATE = ISNULL(@PN_ACCOUNT_STATE, -1),
	@LS_MODULE_NAME = @PS_MODULE_NAME,
	@LS_STATION_NAME = @PS_STATION_NAME,
	@LS_DOMAIN_SERVER = @PS_DOMAIN_SERVER
;
-- DECLARO LA TRANSACCIÓN.
BEGIN TRANSACTION
 
IF (@LS_USER_ID IS NOT NULL) BEGIN
	IF (@LN_ATTEMPT_NUMBER > 0) BEGIN
		IF (@LN_ACCOUNT_STATE > 0 AND @LN_ACCOUNT_STATE < 6) BEGIN
			-- INSERTA UN REGISTRO DE INTENTO DE SESIÓN FALLIDO.
			INSERT INTO	PSESSIONS_FAILURES (USER_ID, ATTEMPT_NUMBER, ACCOUNT_STATE, MODULE_NAME, STATION_NAME, DOMAIN_SERVER)
			VALUES		(@LS_USER_ID, @LN_ATTEMPT_NUMBER, @LN_ACCOUNT_STATE, @LS_MODULE_NAME, @LS_STATION_NAME, @LS_DOMAIN_SERVER);
			SELECT @LSOPERA = 'INSERT', @LSTABLA = 'PSESSIONS_FAILURES', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
			IF (@LNERRORNUM <> 0) GOTO FALLO;
		END
		ELSE BEGIN
			SET @PS_RET_MESSAGE = 'EL PARÁMETRO @PN_ACCOUNT_STATE DEBE TENER UN VALOR DE CERO A CINCO';
		END;
	END
	ELSE BEGIN
		SET @PS_RET_MESSAGE = 'EL PARÁMETRO @PN_ATTEMPT_NUMBER NO ES MAYOR A CERO';
	END;
END
ELSE BEGIN
	SET @PS_RET_MESSAGE = 'EL PARÁMETRO @PS_USER_ID ES NULO';
END;
 
FALLO:
-- REGISTRO DE SUCESOS Y CONTROL DE FIN DE PROCEDIMIENTO. CONCLUYE LA TRANSACCIÓN SI TODO FUE EXITOSO.
SELECT @LNDURACION = DATEDIFF(SECOND, @LDINICIO_OPE, GETDATE()), @LNSEVERITY = ISNULL(EM.SEVERITY, 16), @LSERRORDESC = 'ERROR ' + CONVERT(VARCHAR, ISNULL(EM.ERROR, 0)) + ' - ' + ISNULL(EM.DESCRIPTION, ' ') FROM MASTER.DBO.SYSMESSAGES EM WHERE (EM.ERROR = @LNERRORNUM);
IF (@LNERRORNUM <> 0) BEGIN
	-- NOTIFICACIÓN EN EL REGISTRO DE SQL SERVER.
	SET @LSERRORLOG = @LSERRORLOG + CASE WHEN (ISNULL(CHARINDEX('%', @LSERRORDESC), 0) > 0) THEN RTRIM(LEFT(@LSERRORDESC, 11)) ELSE @LSERRORDESC END;
	-- DEVUELVE EL ERROR EN EL PARÁMETRO DE SALIDA.
	SET @PS_RET_MESSAGE = SUBSTRING(@LSERRORDESC, 1, 440);
	-- DESHACE LA TRANSACCIÓN COMPLETA SI LA OPERACIÓN FALLÓ.
	IF (@@TRANCOUNT > 0) ROLLBACK TRANSACTION;
	EXECUTE @LNERRORNUM = PA_SYS_REGISTRO_SUCESOS_INSERT @PSPROCEDIMIENTO_1 = @LSPROC, @PSTABLA_2 = @LSTABLA, @PNFILAS_AFECTADAS_3 = @LNFILAS_AFEC, @PSOPERACION_4 = @LSOPERA, @PNDURACION_5 = @LNDURACION, @PSRESULTADO_6 = @LSERRORDESC, @PSSQL_CMD_7 = @LSERRORDESC;
	-- RAISERROR(@LSERRORLOG, @LNSEVERITY, -1) WITH NOWAIT;
END
ELSE BEGIN
--	EXECUTE @LNERRORNUM = PA_SYS_REGISTRO_SUCESOS_INSERT @PSPROCEDIMIENTO_1 = @LSPROC, @PSTABLA_2 = @LSTABLA, @PNFILAS_AFECTADAS_3 = @LNFILAS_AFEC, @PSOPERACION_4 = @LSOPERA, @PNDURACION_5 = @LNDURACION, @PSRESULTADO_6 = @LSERRORDESC, @PSSQL_CMD_7 = @LSERRORDESC;
	IF (@@TRANCOUNT > 0) COMMIT TRANSACTION;
END;
RETURN;
