CREATE   PROCEDURE [dbo].[M_CONFIG_DEL_GROUP]
(@IPKEYJOB	AS VARCHAR(100),
 @IUSERID	AS VARCHAR(100),
 @ORETCODE	AS INT OUTPUT,
 @ORETDESC	AS VARCHAR(4000) OUTPUT)
AS
 
BEGIN	
 
	DECLARE @ID_GROUP_SEL VARCHAR(50),
			@VCANT	INT
 
	SELECT	@ID_GROUP_SEL = ISNULL(ID_GROUP_SEL,'')
	FROM	M_CONFIG 
	WHERE	PAR_KEY = @IPKEYJOB;
 
	SET @ORETCODE = 0
	SET @ORETDESC = ''
 
	SET @VCANT = 0
 
	IF (@ID_GROUP_SEL <> '') BEGIN 
		
		--VALIDO QUE NO TENGA USUARIOS--
		SELECT	@VCANT = COUNT(1)
		FROM	GroupsUserMembers
		WHERE	GroupID = @ID_GROUP_SEL
 
		IF (@VCANT > 0) BEGIN
			SET @ORETCODE = 1
			SET	@ORETDESC = '<script>alert("NO Puede eliminar el Perfil si tiene Usuarios Asociados");</script>'
			RETURN
		END
 
		--VALIDO QUE NO TENGA MODULOS--
		SELECT	@VCANT = COUNT(1)
		FROM	CALL_TYPE
		WHERE	PKEY IN ( 
					SELECT	PKEY_CALL_TYPE FROM UNIT_CALL_TYPE
					WHERE	UNIT_CODE = @ID_GROUP_SEL)
 
		IF (@VCANT > 0) BEGIN
			SET @ORETCODE = 1
			SET	@ORETDESC = '<script>alert("NO Puede eliminar el Perfil si tiene Modulos Asociados");</script>'
			RETURN
		END
	
		--VALIDO QUE NO TENGA PERMISOS--
		SELECT	@VCANT = COUNT(1)
		FROM	GroupsActions
		WHERE	GroupId = @ID_GROUP_SEL
 
		IF (@VCANT > 0) BEGIN
			SET @ORETCODE = 1
			SET	@ORETDESC = '<script>alert("NO Puede eliminar el Perfil si tiene Permisos Asociados");</script>'
			RETURN
		END
 
		/* ====== Insert ====== */
		BEGIN TRANSACTION
 
			DECLARE @VDESC_GROUP VARCHAR(100)
 
			SELECT	@VDESC_GROUP = NAME
			FROM	GROUPS
			WHERE	ID = @ID_GROUP_SEL
 
			--ELIMINO LOS USUARIOS, MODULOS Y PERMISOS POR SI LE QUEDAN--
			DELETE FROM GroupsUserMembers WHERE	GroupID = @ID_GROUP_SEL
 
			DELETE FROM CALL_TYPE WHERE	PKEY IN (SELECT	PKEY_CALL_TYPE FROM UNIT_CALL_TYPE WHERE	UNIT_CODE = @ID_GROUP_SEL)
 
			DELETE FROM GroupsActions WHERE	GroupId = @ID_GROUP_SEL
 
			--ELIMINO EL PERFIL--
			DELETE FROM Groups WHERE Id = @ID_GROUP_SEL
 
		COMMIT TRANSACTION
		RETURN;
	END
END
