CREATE   PROCEDURE [dbo].[M_CONFIG_CMB_GROUPS_USERS]
(@IPKEYJOB	AS VARCHAR(100))
AS
 
DECLARE @V_PERFIL_SEL VARCHAR(50)
 
BEGIN
 
	SELECT	@V_PERFIL_SEL = ISNULL(ID_GROUP_SEL,'')
	FROM	M_CONFIG
	WHERE	PAR_KEY = @IPKEYJOB
 
	SELECT	Id		AS CAT_DATA_CODE, 
			Name	AS CAT_DATA_DESC,
			'TRUE'
	FROM	Users u
	WHERE	Id not in (
			select UserMemberId from GroupsUserMembers 
			WHERE isnull(GroupId,'')=@V_PERFIL_SEL)
	ORDER BY Name
 
END
