CREATE PROCEDURE [dbo].[PA_SYS_BORRAR_TRAMITE_POR_PKEY] (@PNTRAMITE_NRO AS NUMERIC(15) = NULL, @PSPKEY AS VARCHAR(100) = NULL, @PSCONSERVAR_DSS AS VARCHAR(1) = 'N', @PS_RET_MESSAGE VARCHAR(440) = NULL OUTPUT) AS
 
-- =========================================================================================================================
-- AUTOR: TITO - ENGAGE SOFTWARE COMPANY
-- FECHA DE CREACIÓN: 27/11/2006
-- EDITOR: MBRIZZI - ENGAGE SOFTWARE COMPANY
-- FECHA DE EDICIÓN: 01/09/2010
-- TABLAS LEÍDAS: DSS_TBPHYSICAL_JOB, PHYSICAL_JOB, JOB_TYPE, ENTITY_BROWSER, EVI_TABLES.
-- TABLAS MODIFICADAS: PHYSICAL_JOB_ACTIONS, PHYSICAL_ACTIVITIES, PHYSICAL_JOB_ALARMS, PHYSICAL_JOB_ATTACHED_DATA,
-- PHYSICAL_ATTACHED_DOCUMENT, PHYSICAL_NOTES, PHYSICAL_JOB_NOTIFICATIONS, PHYS_CALL_ANSWERED_QUESTIONS,
-- PHYSICAL_CALL_TRANSACTIONS, PHYSICAL_CALL_CONV_STEPS, PHYSICAL_CALL_NUMBERS, PHYSICAL_CALL, ATTENDED_CUSTOMER,
-- PHYSICAL_JOB, DSS_TBPHYS_CALL_ANSWERED_QUES, DSS_TBPHYSICAL_CALL_CONV_STEPS, DSS_TBPHYSICAL_CALL, DSS_TBATTENDED_CUSTOMER,
-- DSS_TBPHYSICAL_JOB Y TODAS LAS TABLAS ASOCIADAS AL TIPO DE TRÁMITE MEDIANTE ENTITY_BROWSER.
-- DESCRIPCIÓN: PROCEDIMIENTO QUE ELIMINA UN TRÁMITE CUYA CLAVE SE PASA POR PARÁMETRO, INCLUYENDO TODAS SUS DEPENDENCIAS.
-- CONSIDERACIONES:
-- 1. SÓLO SE BORRAN LAS ENTIDADES PERSONALIZADAS HASTA EL NIVEL 3 ASOCIADAS AL TIPO DE TRÁMITE.
-- 2. SI EL TRÁMITE POSEYERA ENTIDADES DE MAYOR NIVEL DE PROFUNDIDAD JERÁRQUICA, LAS MISMAS SE DEBERÁN DEPURAR MANUALMENTE.
-- 3. EL PROCEDIMIENTO PERMITE CONSERVAR LA HISTORIA DEL TRÁMITE CUANDO @PSCONSERVAR_DSS = 'S'.
-- 4. EL PARÁMETRO DE SALIDA @PS_RET_MESSAGE DEVUELVE EL MENSAJE DE ERROR. NULL SI NO HUBO.
-- =========================================================================================================================
 
SET NOCOUNT ON;
SET XACT_ABORT ON;
 
-- DECLARACIÓN E INICIALIZACIÓN DE VARIABLES DE ERROR Y AUXILIARES.
DECLARE @LNERRORNUM AS INTEGER,
	@LNSEVERITY AS SMALLINT,
	@LNFILAS_AFEC AS INTEGER,
	@LDINICIO_OPE AS DATETIME,
	@LNDURACION AS INTEGER,
	@LSOPERA AS VARCHAR(30),
	@LSPROC AS VARCHAR(30),
	@LSTABLA AS VARCHAR(30),
	@LSERRORLOG AS VARCHAR(440),
	@LSERRORDESC AS VARCHAR(440),
	@LSSQL_CMD AS VARCHAR(4000)
;
SELECT 	@LNERRORNUM = 0,
	@LNSEVERITY = 16,
	@LNFILAS_AFEC = 0,
	@LDINICIO_OPE = GETDATE(),
	@LNDURACION = 0,
	@LSOPERA = 'EXECUTE',
	@LSPROC = OBJECT_NAME(@@PROCID),
	@LSTABLA = 'NINGUNA',
	@LSERRORLOG = @@SERVERNAME + '.' + DB_NAME() + '.' + USER_NAME() + '.' + OBJECT_NAME(@@PROCID) + ' - ',
	@LSERRORDESC = NULL,
	@LSSQL_CMD = NULL
;
 
-- DECLARA LAS VARIABLES.
DECLARE @LNTRAMITE_NRO AS INTEGER,
	@LSPKEY AS VARCHAR(100),
	@LSCONSERVAR_DSS AS VARCHAR(1),
	@LS_ENTITY_TABLE_REL VARCHAR(30),
	@LS_ENTITY_LEVEL NUMERIC(1),
	@LS_ENTITY_TABLE_PARENT_1 VARCHAR(30),
	@LS_ENTITY_TABLE_PARENT_2 VARCHAR(30),
	@LS_RET_MESSAGE VARCHAR(440)
;
-- ASIGNA VALORES PREDETERMINADOS A LAS VARIABLES.
SELECT	@LNTRAMITE_NRO = ISNULL(@PNTRAMITE_NRO, 0),
	@LSPKEY = ISNULL(@PSPKEY, ' '),
	@LSCONSERVAR_DSS = ISNULL(@PSCONSERVAR_DSS, 'N'),
	@LS_ENTITY_TABLE_REL = NULL,
	@LS_ENTITY_LEVEL = NULL,
	@LS_ENTITY_TABLE_PARENT_1 = NULL,
	@LS_ENTITY_TABLE_PARENT_2 = NULL,
	@LS_RET_MESSAGE = NULL
;
 
-- DECLARO LA TRANSACCIÓN.
BEGIN TRANSACTION
 
IF (CURSOR_STATUS('LOCAL', 'LOCUR1') >= 0) BEGIN
	-- CIERRA Y DESALOJA EL CURSOR.
	CLOSE LOCUR1;
	DEALLOCATE LOCUR1;
END;
 
-- SI SE PASÓ UN NÚMERO DE TRÁMITE MAYOR A CERO, TOMA SU PKEY.
IF (@LNTRAMITE_NRO > 0) BEGIN
	-- TOMA EL VALOR DE LA PKEY PARA EL NÚMERO DE TRÁMITE SELECCIONADO.
	SELECT @LSPKEY = ISNULL(PKEY, ' ') FROM PHYSICAL_JOB WHERE (ISNULL(JOB_SEQ, 0) = @LNTRAMITE_NRO);
	SET @LS_RET_MESSAGE = '. @PNTRAMITE_NRO = ' + CONVERT(VARCHAR, @LNTRAMITE_NRO) + ', @PSPKEY = ' + CHAR(39) + @LSPKEY + CHAR(39);
END
ELSE BEGIN
	SET @LS_RET_MESSAGE = '. @PSPKEY = ' + CHAR(39) + @LSPKEY + CHAR(39);
END;
 
-- SI EL PARÁMETRO ES VÁLIDO, OPERA.
IF (ISNULL(@LSPKEY, ' ') <> ' ') BEGIN
 
	-- INICIO DEL BORRADO DE LAS TABLAS DE TRÁMITES DE ENGAGE.
 
	-- TABLA DE GESTIÓN QUE CONSERVA HISTORIA NO REQUERIDA POR EL SOFTWARE DE ENGAGE.
	DELETE	PHYSICAL_JOB_ACTIONS
	WHERE	(PAR_KEY = @LSPKEY);
	SELECT @LSOPERA = 'DELETE', @LSTABLA = 'PHYSICAL_JOB_ACTIONS', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
--	PRINT @LSOPERA + ' - ' + @LSTABLA + ' - FILAS AFECTADAS = ' + CONVERT(VARCHAR, @LNFILAS_AFEC);
 
	-- TABLA DE GESTIÓN QUE CONSERVA HISTORIA NO REQUERIDA POR EL SOFTWARE DE ENGAGE.
	DELETE	PHYSICAL_JOB_NOTIFICATIONS
	WHERE	(PAR_KEY = @LSPKEY);
	SELECT @LSOPERA = 'DELETE', @LSTABLA = 'PHYSICAL_JOB_NOTIFICATIONS', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
--	PRINT @LSOPERA + ' - ' + @LSTABLA + ' - FILAS AFECTADAS = ' + CONVERT(VARCHAR, @LNFILAS_AFEC);
 
	-- TABLA DE GESTIÓN QUE CONSERVA HISTORIA NO REQUERIDA POR EL SOFTWARE DE ENGAGE.
--	DELETE	PHYS_CALL_ANSWERED_QUESTIONS
--	WHERE	(PAR_KEY IN (SELECT PKEY FROM PHYSICAL_CALL_CONV_STEPS WHERE PAR_KEY IN (SELECT PKEY FROM PHYSICAL_CALL WHERE PAR_KEY IN (SELECT PKEY FROM ATTENDED_CUSTOMER WHERE PKEY_JOB = @LSPKEY))));
--	SELECT @LSOPERA = 'DELETE', @LSTABLA = 'PHYS_CALL_ANSWERED_QUESTIONS', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
--	IF (@LNERRORNUM <> 0) GOTO FALLO;
--	PRINT @LSOPERA + ' - ' + @LSTABLA + ' - FILAS AFECTADAS = ' + CONVERT(VARCHAR, @LNFILAS_AFEC);
 
	-- TABLA DE REGISTRO DE TRANSACCIONES DE PASOS Y GLOBALES QUE CONSERVA HISTORIA NO REQUERIDA POR EL SOFTWARE DE ENGAGE.
	DELETE	PHYSICAL_CALL_TRANSACTIONS
	WHERE	(PAR_KEY IN (SELECT PKEY FROM PHYSICAL_CALL_CONV_STEPS WHERE PAR_KEY IN (SELECT PKEY FROM PHYSICAL_CALL WHERE PAR_KEY IN (SELECT PKEY FROM ATTENDED_CUSTOMER WHERE PKEY_JOB = @LSPKEY))));
	SELECT @LSOPERA = 'DELETE', @LSTABLA = 'PHYSICAL_CALL_TRANSACTIONS', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
--	PRINT @LSOPERA + ' - ' + @LSTABLA + ' - FILAS AFECTADAS = ' + CONVERT(VARCHAR, @LNFILAS_AFEC);
 
	-- TABLA DE REGISTRO DE PASOS EJECUTADOS DE LAS ESTRUCTURAS QUE CONSERVA HISTORIA NO REQUERIDA POR EL SOFTWARE DE ENGAGE.
	DELETE	PHYSICAL_CALL_CONV_STEPS
	WHERE	(PAR_KEY IN (SELECT PKEY FROM PHYSICAL_CALL WHERE PAR_KEY IN (SELECT PKEY FROM ATTENDED_CUSTOMER WHERE PKEY_JOB = @LSPKEY)));
	SELECT @LSOPERA = 'DELETE', @LSTABLA = 'PHYSICAL_CALL_CONV_STEPS', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
--	PRINT @LSOPERA + ' - ' + @LSTABLA + ' - FILAS AFECTADAS = ' + CONVERT(VARCHAR, @LNFILAS_AFEC);
 
	DELETE	PHYSICAL_CALL
	WHERE	(PAR_KEY IN (SELECT PKEY FROM ATTENDED_CUSTOMER WHERE PKEY_JOB = @LSPKEY));
	SELECT @LSOPERA = 'DELETE', @LSTABLA = 'PHYSICAL_CALL', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
--	PRINT @LSOPERA + ' - ' + @LSTABLA + ' - FILAS AFECTADAS = ' + CONVERT(VARCHAR, @LNFILAS_AFEC);
 
	DELETE	ATTENDED_CUSTOMER
	WHERE	(PKEY_JOB = @LSPKEY);
	SELECT @LSOPERA = 'DELETE', @LSTABLA = 'ATTENDED_CUSTOMER', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
--	PRINT @LSOPERA + ' - ' + @LSTABLA + ' - FILAS AFECTADAS = ' + CONVERT(VARCHAR, @LNFILAS_AFEC);
 
	DELETE	PHYSICAL_JOB
	WHERE	(PKEY = @LSPKEY);
	SELECT @LSOPERA = 'DELETE', @LSTABLA = 'ATTENDED_CUSTOMER', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
--	PRINT @LSOPERA + ' - ' + @LSTABLA + ' - FILAS AFECTADAS = ' + CONVERT(VARCHAR, @LNFILAS_AFEC);
 
	-- VERIFICA SI SE HA ELEGIDO CONSERVAR LA HISTORIA DEL TRÁMITE.
	IF (@LSCONSERVAR_DSS = 'N') BEGIN
		SET @LS_RET_MESSAGE = 'SE HA BORRADO EL TRÁMITE Y SUS DATOS RELACIONADOS' + @LS_RET_MESSAGE;
 
		DELETE	DSS_TBPHYS_CALL_ANSWERED_QUES
		WHERE	(ID_CONV_STEPS IN (SELECT ID_CONV_STEPS FROM DSS_TBPHYSICAL_CALL_CONV_STEPS WHERE PKEY_PHYSICAL_CALL IN (SELECT PKEY_PHYSICAL_CALL FROM DSS_TBPHYSICAL_CALL WHERE PKEY_ATTENDED_CUSTOMER IN (SELECT PKEY_ATTENDED_CUSTOMER FROM DSS_TBATTENDED_CUSTOMER WHERE PKEY_PHYSICAL_JOB = @LSPKEY))));
		SELECT @LSOPERA = 'DELETE', @LSTABLA = 'DSS_TBPHYS_CALL_ANSWERED_QUES', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
		IF (@LNERRORNUM <> 0) GOTO FALLO;
--		PRINT @LSOPERA + ' - ' + @LSTABLA + ' - FILAS AFECTADAS = ' + CONVERT(VARCHAR, @LNFILAS_AFEC);
 
		DELETE	DSS_TBPHYSICAL_CALL_CONV_STEPS
		WHERE	(PKEY_PHYSICAL_CALL IN (SELECT PKEY_PHYSICAL_CALL FROM DSS_TBPHYSICAL_CALL WHERE PKEY_ATTENDED_CUSTOMER IN (SELECT PKEY_ATTENDED_CUSTOMER FROM DSS_TBATTENDED_CUSTOMER WHERE PKEY_PHYSICAL_JOB = @LSPKEY)));
		SELECT @LSOPERA = 'DELETE', @LSTABLA = 'DSS_TBPHYSICAL_CALL_CONV_STEPS', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
		IF (@LNERRORNUM <> 0) GOTO FALLO;
--		PRINT @LSOPERA + ' - ' + @LSTABLA + ' - FILAS AFECTADAS = ' + CONVERT(VARCHAR, @LNFILAS_AFEC);
 
		DELETE	DSS_TBPHYSICAL_CALL
		WHERE	(PKEY_ATTENDED_CUSTOMER IN (SELECT PKEY_ATTENDED_CUSTOMER FROM DSS_TBATTENDED_CUSTOMER WHERE PKEY_PHYSICAL_JOB = @LSPKEY));
		SELECT @LSOPERA = 'DELETE', @LSTABLA = 'DSS_TBPHYSICAL_CALL', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
		IF (@LNERRORNUM <> 0) GOTO FALLO;
--		PRINT @LSOPERA + ' - ' + @LSTABLA + ' - FILAS AFECTADAS = ' + CONVERT(VARCHAR, @LNFILAS_AFEC);
 
		DELETE	DSS_TBATTENDED_CUSTOMER
		WHERE	(PKEY_PHYSICAL_JOB = @LSPKEY);
		SELECT @LSOPERA = 'DELETE', @LSTABLA = 'DSS_TBATTENDED_CUSTOMER', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
		IF (@LNERRORNUM <> 0) GOTO FALLO;
--		PRINT @LSOPERA + ' - ' + @LSTABLA + ' - FILAS AFECTADAS = ' + CONVERT(VARCHAR, @LNFILAS_AFEC);
 
		-- INICIO: 5 TABLAS DE GESTIÓN QUE CONSERVAN HISTORIA REQUERIDA POR EL SOFTWARE DE ENGAGE.
 
		DELETE	PHYSICAL_ACTIVITIES
		WHERE	(PAR_KEY = @LSPKEY);
		SELECT @LSOPERA = 'DELETE', @LSTABLA = 'PHYSICAL_ACTIVITIES', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
		IF (@LNERRORNUM <> 0) GOTO FALLO;
	--	PRINT @LSOPERA + ' - ' + @LSTABLA + ' - FILAS AFECTADAS = ' + CONVERT(VARCHAR, @LNFILAS_AFEC);
 
		DELETE	PHYSICAL_JOB_ALARMS
		WHERE	(PAR_KEY = @LSPKEY);
		SELECT @LSOPERA = 'DELETE', @LSTABLA = 'PHYSICAL_JOB_ALARMS', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
		IF (@LNERRORNUM <> 0) GOTO FALLO;
	--	PRINT @LSOPERA + ' - ' + @LSTABLA + ' - FILAS AFECTADAS = ' + CONVERT(VARCHAR, @LNFILAS_AFEC);
 
		DELETE	PHYSICAL_JOB_ATTACHED_DATA
		WHERE	(PAR_KEY = @LSPKEY);
		SELECT @LSOPERA = 'DELETE', @LSTABLA = 'PHYSICAL_JOB_ATTACHED_DATA', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
		IF (@LNERRORNUM <> 0) GOTO FALLO;
	--	PRINT @LSOPERA + ' - ' + @LSTABLA + ' - FILAS AFECTADAS = ' + CONVERT(VARCHAR, @LNFILAS_AFEC);
 
		DELETE	PHYSICAL_ATTACHED_DOCUMENT
		WHERE	(PAR_KEY = @LSPKEY);
		SELECT @LSOPERA = 'DELETE', @LSTABLA = 'PHYSICAL_ATTACHED_DOCUMENT', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
		IF (@LNERRORNUM <> 0) GOTO FALLO;
	--	PRINT @LSOPERA + ' - ' + @LSTABLA + ' - FILAS AFECTADAS = ' + CONVERT(VARCHAR, @LNFILAS_AFEC);
 
		DELETE	PHYSICAL_NOTES
		WHERE	(PAR_KEY = @LSPKEY);
		SELECT @LSOPERA = 'DELETE', @LSTABLA = 'PHYSICAL_NOTES', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
		IF (@LNERRORNUM <> 0) GOTO FALLO;
	--	PRINT @LSOPERA + ' - ' + @LSTABLA + ' - FILAS AFECTADAS = ' + CONVERT(VARCHAR, @LNFILAS_AFEC);
 
		-- FIN: 5 TABLAS DE GESTIÓN QUE CONSERVAN HISTORIA REQUERIDA POR EL SOFTWARE DE ENGAGE.
 
		-- ELIMINA LOS REGISTROS EN LAS TABLAS ASOCIADAS AL TIPO DE TRÁMITE.
		-- CARGA UN CURSOR.
		DECLARE LOCUR1 CURSOR LOCAL FAST_FORWARD TYPE_WARNING FOR
			SELECT	T0.ENTITY_TABLE_REL,
				T0.ENTITY_LEVEL,
				T0.ENTITY_TABLE_PARENT_1,
				T0.ENTITY_TABLE_PARENT_2
--				T0.JOB_TYPE_PKEY,
--				T0.PKEY
			FROM	(
				-- ENTITY_LEVEL = 1
				SELECT	TH.ENTITY_TABLE_REL,
					TH.ENTITY_LEVEL,
					NULL AS ENTITY_TABLE_PARENT_1,
					NULL AS ENTITY_TABLE_PARENT_2
--					TH.PAR_KEY AS JOB_TYPE_PKEY,
--					TH.PKEY
				FROM	DSS_TBPHYSICAL_JOB PJ,
					JOB_TYPE JT,
					ENTITY_BROWSER TH
				WHERE	(PJ.ID_JOB_TYPE = JT.JOB_TYPE_CODE)
					AND (JT.PKEY = TH.PAR_KEY AND TH.ENTITY_TYPE = 'Tramite')
					AND (PJ.PKEY_PHYSICAL_JOB = @LSPKEY)
					AND TH.ENTITY_TABLE_REL IN (SELECT TABLE_NAME FROM EVI_TABLES)
				UNION
				-- ENTITY_LEVEL = 2
				SELECT	TH.ENTITY_TABLE_REL,
					TH.ENTITY_LEVEL,
					TP.ENTITY_TABLE_REL AS ENTITY_TABLE_PARENT_1,
					NULL AS ENTITY_TABLE_PARENT_2
--					TP.PAR_KEY AS JOB_TYPE_PKEY,
--					TH.PKEY
				FROM	DSS_TBPHYSICAL_JOB PJ,
					JOB_TYPE JT,
					ENTITY_BROWSER TP,
					ENTITY_BROWSER TH
				WHERE	(PJ.ID_JOB_TYPE = JT.JOB_TYPE_CODE)
					AND (JT.PKEY = TP.PAR_KEY AND TP.ENTITY_TYPE = 'Tramite')
					AND (TP.PKEY = TH.PAR_KEY)
					AND (PJ.PKEY_PHYSICAL_JOB = @LSPKEY)
					AND TP.ENTITY_TABLE_REL IN (SELECT TABLE_NAME FROM EVI_TABLES)
					AND TH.ENTITY_TABLE_REL IN (SELECT TABLE_NAME FROM EVI_TABLES)
				UNION
				-- ENTITY_LEVEL = 3
				SELECT	TH.ENTITY_TABLE_REL,
					TH.ENTITY_LEVEL,
					TP.ENTITY_TABLE_REL AS ENTITY_TABLE_PARENT_1,
					TA.ENTITY_TABLE_REL AS ENTITY_TABLE_PARENT_2
--					TA.PAR_KEY AS JOB_TYPE_PKEY,
--					TH.PKEY
				FROM	DSS_TBPHYSICAL_JOB PJ,
					JOB_TYPE JT,
					ENTITY_BROWSER TA,
					ENTITY_BROWSER TP,
					ENTITY_BROWSER TH
				WHERE	(PJ.ID_JOB_TYPE = JT.JOB_TYPE_CODE)
					AND (JT.PKEY = TA.PAR_KEY AND TA.ENTITY_TYPE = 'Tramite')
					AND (TA.PKEY = TP.PAR_KEY)
					AND (TP.PKEY = TH.PAR_KEY)
					AND (PJ.PKEY_PHYSICAL_JOB = @LSPKEY)
					AND TA.ENTITY_TABLE_REL IN (SELECT TABLE_NAME FROM EVI_TABLES)
					AND TP.ENTITY_TABLE_REL IN (SELECT TABLE_NAME FROM EVI_TABLES)
					AND TH.ENTITY_TABLE_REL IN (SELECT TABLE_NAME FROM EVI_TABLES)
				) T0
			ORDER BY T0.ENTITY_LEVEL DESC, T0.ENTITY_TABLE_REL ASC;
 
		OPEN LOCUR1;
		FETCH NEXT FROM LOCUR1 INTO @LS_ENTITY_TABLE_REL, @LS_ENTITY_LEVEL, @LS_ENTITY_TABLE_PARENT_1, @LS_ENTITY_TABLE_PARENT_2;
 
		-- CICLO DE NIVEL DE TRÁMITE.
		WHILE (@@FETCH_STATUS = 0)
		BEGIN
			-- COMPONE LA SENTENCIA DE BORRADO DE ACUERDO AL NIVEL DE LA TABLA ASOCIADA AL TIPO DE TRÁMITE.
			IF (@LS_ENTITY_LEVEL = 3) BEGIN
				SET @LSSQL_CMD = 'DELETE ' + @LS_ENTITY_TABLE_REL + ' WHERE (PAR_KEY IN (SELECT PKEY FROM ' + @LS_ENTITY_TABLE_PARENT_1 + ' WHERE (PAR_KEY IN (SELECT PKEY FROM ' + @LS_ENTITY_TABLE_PARENT_2 + ' WHERE (PAR_KEY = ' + CHAR(39) + @LSPKEY + CHAR(39) + ')))))';
			END
			ELSE BEGIN
				IF (@LS_ENTITY_LEVEL = 2) BEGIN
					SET @LSSQL_CMD = 'DELETE ' + @LS_ENTITY_TABLE_REL + ' WHERE (PAR_KEY IN (SELECT PKEY FROM ' + @LS_ENTITY_TABLE_PARENT_1 + ' WHERE (PAR_KEY = ' + CHAR(39) + @LSPKEY + CHAR(39) + ')))';
				END
				ELSE BEGIN
					SET @LSSQL_CMD = 'DELETE ' + @LS_ENTITY_TABLE_REL + ' WHERE (PAR_KEY = ' + CHAR(39) + @LSPKEY + CHAR(39) + ')';
				END;
			END;
 
			-- ELIMINA EL TRÁMITE ESPECIFICADO POR PARÁMETRO, CONSERVANDO LA HISTORIA DEL MISMO.
			EXECUTE (@LSSQL_CMD);
			SELECT @LSOPERA = 'DELETE', @LSTABLA = @LS_ENTITY_TABLE_REL, @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
			IF (@LNERRORNUM <> 0) GOTO FALLO;
--			PRINT @LSOPERA + ' - ' + @LSTABLA + ' - FILAS AFECTADAS = ' + CONVERT(VARCHAR, @LNFILAS_AFEC);
 
			FETCH NEXT FROM LOCUR1 INTO @LS_ENTITY_TABLE_REL, @LS_ENTITY_LEVEL, @LS_ENTITY_TABLE_PARENT_1, @LS_ENTITY_TABLE_PARENT_2;
		END;
 
		CLOSE LOCUR1;
		DEALLOCATE LOCUR1;
 
		DELETE	DSS_TBPHYSICAL_JOB
		WHERE	(PKEY_PHYSICAL_JOB = @LSPKEY);
		SELECT @LSOPERA = 'DELETE', @LSTABLA = 'DSS_TBPHYSICAL_JOB', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
		IF (@LNERRORNUM <> 0) GOTO FALLO;
--		PRINT @LSOPERA + ' - ' + @LSTABLA + ' - FILAS AFECTADAS = ' + CONVERT(VARCHAR, @LNFILAS_AFEC);
	END
	ELSE BEGIN
		SET @LS_RET_MESSAGE = 'SE HA DEPURADO EL TRÁMITE CONSERVANDO SU HISTORIA' + @LS_RET_MESSAGE;
	END;
 
	-- FIN DEL BORRADO DE LAS TABLAS DE TRÁMITES DE ENGAGE.
	PRINT @LS_RET_MESSAGE;
 
END;
 
FALLO:
-- REGISTRO DE SUCESOS Y CONTROL DE FIN DE PROCEDIMIENTO. CONCLUYE LA TRANSACCIÓN SI TODO FUE EXITOSO.
SELECT @LNDURACION = DATEDIFF(SECOND, @LDINICIO_OPE, GETDATE()), @LNSEVERITY = ISNULL(EM.SEVERITY, 16), @LSERRORDESC = 'ERROR ' + CONVERT(VARCHAR, ISNULL(EM.ERROR, 0)) + ' - ' + ISNULL(EM.DESCRIPTION, ' ') FROM MASTER.DBO.SYSMESSAGES EM WHERE (EM.ERROR = @LNERRORNUM);
IF (@LNERRORNUM <> 0) BEGIN
	-- NOTIFICACIÓN EN EL REGISTRO DE SQL SERVER.
	SET @LSERRORLOG = @LSERRORLOG + CASE WHEN (ISNULL(CHARINDEX('%', @LSERRORDESC), 0) > 0) THEN RTRIM(LEFT(@LSERRORDESC, 11)) ELSE @LSERRORDESC END;
	-- DEVUELVE EL ERROR EN EL PARÁMETRO DE SALIDA.
	SET @PS_RET_MESSAGE = SUBSTRING(@LSERRORDESC, 1, 440);
	-- DESHACE LA TRANSACCIÓN COMPLETA SI LA OPERACIÓN FALLÓ.
	IF (@@TRANCOUNT > 0) ROLLBACK TRANSACTION;
	EXECUTE @LNERRORNUM = PA_SYS_REGISTRO_SUCESOS_INSERT @PSPROCEDIMIENTO_1 = @LSPROC, @PSTABLA_2 = @LSTABLA, @PNFILAS_AFECTADAS_3 = @LNFILAS_AFEC, @PSOPERACION_4 = @LSOPERA, @PNDURACION_5 = @LNDURACION, @PSRESULTADO_6 = @LSERRORDESC, @PSSQL_CMD_7 = @LSERRORDESC;
	-- RAISERROR(@LSERRORLOG, @LNSEVERITY, -1) WITH NOWAIT;
END
ELSE BEGIN
	EXECUTE @LNERRORNUM = PA_SYS_REGISTRO_SUCESOS_INSERT @PSPROCEDIMIENTO_1 = @LSPROC, @PSTABLA_2 = @LSTABLA, @PNFILAS_AFECTADAS_3 = @LNFILAS_AFEC, @PSOPERACION_4 = @LSOPERA, @PNDURACION_5 = @LNDURACION, @PSRESULTADO_6 = @LSERRORDESC, @PSSQL_CMD_7 = @LSERRORDESC;
	IF (@@TRANCOUNT > 0) COMMIT TRANSACTION;
END;
RETURN;
 
