CREATE PROCEDURE PA_SYS_NAMED_PARAMETERS_SUPP (@PS_RET_MESSAGE VARCHAR(440) = NULL OUTPUT) AS
 
-- =========================================================================================================================
-- AUTOR: TITO - ENGAGE SOFTWARE COMPANY
-- FECHA DE CREACIÓN: 03/06/2008
-- EDITOR: TITO - ENGAGE SOFTWARE COMPANY
-- FECHA DE EDICIÓN: 17/07/2009
-- TABLAS LEÍDAS: @TMP_SP_PARAMETERS, STORED_PROCEDURES, TRANSACTIONS, SP_PRM_IN, SP_PRM_OUT, EVI_PROCEDURE_PARAMETERS.
-- TABLAS MODIFICADAS: @TMP_SP_PARAMETERS, SP_PRM_IN, SP_PRM_OUT, SP_PRM_OUT_VALUE, DETAIL_FIELD, STEP_TRANSACTION_FLOW,
-- TRAN_PRM_IN, SP_PRM_IN.
-- DESCRIPCIÓN: PROCEDIMIENTO QUE AGREGA SOPORTE PARA LA LLAMADA DE PROCEDIMIENTOS MEDIANTE EL MÉTODO NAMED PARAMETERS.
-- CONSIDERACIONES:
-- 1. ESTO PERMITE EL USO DE LOS DRIVERS DE ORACLE 9I POSTERIORES A LA VERSIÓN 9.2.0.1 Y DE ORACLE 10G EN ENGAGE 5.0,
-- YA QUE SÓLO PERMITEN EL USO DEL MÉTODO NAMED PARAMETERS EN LA LLAMADA A UN PROCEDIMIENTO ALMACENADO DESDE LA APLICACIÓN
-- 2. SE ACTUALIZAN LOS NOMBRES DE LOS PARÁMETROS DE ENTRADA Y SALIDA AL IGUAL QUE COMO ESTÁN EN LA BASE DE DATOS,
-- TENIENDO EN CUENTA EL ORDENAMIENTO ASCENDENTE POR PRM_INDEX QUE USA ENGAGE EN LA LLAMADA A UN PROCEDIMIENTO ALMACENADO.
-- 3. EL PARÁMETRO DE SALIDA @PS_RET_MESSAGE DEVUELVE EL MENSAJE DE ERROR. NULL SI NO HUBO.
-- =========================================================================================================================
 
SET NOCOUNT ON;
SET XACT_ABORT ON;
 
-- DECLARACIÓN E INICIALIZACIÓN DE VARIABLES DE ERROR Y AUXILIARES.
DECLARE @LNERRORNUM AS INTEGER,
	@LNSEVERITY AS SMALLINT,
	@LNFILAS_AFEC AS INTEGER,
	@LDINICIO_OPE AS DATETIME,
	@LNDURACION AS INTEGER,
	@LSOPERA AS VARCHAR(30),
	@LSPROC AS VARCHAR(30),
	@LSTABLA AS VARCHAR(30),
	@LSERRORLOG AS VARCHAR(440),
	@LSERRORDESC AS VARCHAR(440),
	@LSSQL_CMD AS VARCHAR(4000)
;
SELECT 	@LNERRORNUM = 0,
	@LNSEVERITY = 16,
	@LNFILAS_AFEC = 0,
	@LDINICIO_OPE = GETDATE(),
	@LNDURACION = 0,
	@LSOPERA = 'EXECUTE',
	@LSPROC = OBJECT_NAME(@@PROCID),
	@LSTABLA = 'NINGUNA',
	@LSERRORLOG = @@SERVERNAME + '.' + DB_NAME() + '.' + USER_NAME() + '.' + OBJECT_NAME(@@PROCID) + ' - ',
	@LSERRORDESC = NULL,
	@LSSQL_CMD = NULL
;
 
DECLARE
@LS_PARAM_PAR_KEY VARCHAR(20),
@LS_PARAM_PAR_KEY_ANT VARCHAR(20),
@LS_TRAN_CODE VARCHAR(60),
@LS_SP_CODE VARCHAR(20),
@LS_PROCEDURE_NAME VARCHAR(70),
@LS_SUBPROCEDURE_NAME VARCHAR(30),
@LN_ORDINAL_POSITION NUMERIC(15, 0),
@LS_PARAMETER_NAME VARCHAR(30),
@LS_NEW_PARAMETER_NAME VARCHAR(30),
@LS_IN_OUT VARCHAR(30),
@LS_PARAM_PKEY VARCHAR(20),
@LN_COUNT NUMERIC(10, 0),
@LS_TRAN_TYPE VARCHAR(20),
@LS_CTL_TYPE_CODE VARCHAR(20),
@LS_FIELD_TYPE VARCHAR(20),
@LS_PRM_IDR VARCHAR(20);
 
SELECT	@LS_PARAM_PAR_KEY = NULL,
	@LS_PARAM_PAR_KEY_ANT = NULL,
	@LS_TRAN_CODE = NULL,
	@LS_SP_CODE = NULL,
	@LS_PROCEDURE_NAME = NULL,
	@LS_SUBPROCEDURE_NAME = NULL,
	@LN_ORDINAL_POSITION = NULL,
	@LS_PARAMETER_NAME = NULL,
	@LS_NEW_PARAMETER_NAME = NULL,
	@LS_IN_OUT = NULL,
	@LS_PARAM_PKEY = NULL,
	@LN_COUNT = 0,
	@LS_TRAN_TYPE = 'Stored Procedure',
	@LS_CTL_TYPE_CODE = 'sp',
	@LS_FIELD_TYPE = 'SP',
	@LS_PRM_IDR = 'formula';
 
-- DECLARACIÓN DE VARIABLE DE TABLA EN MEMORIA.
DECLARE
@TMP_SP_PARAMETERS TABLE (
	PARAM_PAR_KEY VARCHAR(20) NOT NULL,
	SP_CODE VARCHAR(20) NOT NULL,
	PROCEDURE_NAME VARCHAR(70) NOT NULL,
	SUBPROCEDURE_NAME VARCHAR(30) NOT NULL,
	ORDINAL_POSITION NUMERIC(15, 0) NOT NULL,
	PARAMETER_NAME VARCHAR(30) NOT NULL,
	NEW_PARAMETER_NAME VARCHAR(30) NOT NULL,
	IN_OUT VARCHAR(30) NOT NULL,
	PARAM_PKEY VARCHAR(20) UNIQUE NOT NULL,
	PRIMARY KEY (PARAM_PAR_KEY, ORDINAL_POSITION)
	-- UNIQUE (PROCEDURE_NAME, SUBPROCEDURE_NAME, PARAMETER_NAME)
);
 
-- DECLARO LA TRANSACCIÓN.
BEGIN TRANSACTION
 
-- ELIMINA EL CURSOR GLOBAL, SI EXISTE.
IF (CURSOR_STATUS('LOCAL', 'LOCUR2') >= 0) BEGIN
	-- CIERRA Y DESALOJA EL CURSOR.
	CLOSE LOCUR2;
	DEALLOCATE LOCUR2;
END;
 
-- RESTRICCIONES DEL MODELO DE DATOS QUE SE DEBEN CORREGIR ANTES DE CORRER EL PROCEDIMIENTO.
 
-- 1. LA NUMERACIÓN DE LOS PARÁMETROS DE ENTRADA DEBE SER CONSECUTIVA Y SIN INTERCALACIONES.
DECLARE LOCUR2 CURSOR LOCAL FAST_FORWARD TYPE_WARNING FOR
	SELECT	PE2.PAR_KEY,
		PE2.PRM_INDEX
	FROM	SP_PRM_IN PE2
	WHERE	PE2.PAR_KEY IN (
		SELECT	PE.PAR_KEY
		FROM	SP_PRM_IN PE
		GROUP BY PE.PAR_KEY
		HAVING	(MAX(PE.PRM_INDEX) > COUNT(PE.PRM_INDEX))
		)
	ORDER BY PE2.PAR_KEY ASC,
		PE2.PRM_INDEX ASC;
SELECT @LSOPERA = 'DECLARE CURSOR', @LSTABLA = 'LOCUR2', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
IF (@LNERRORNUM <> 0) GOTO FALLO;
 
-- ABRE EL CURSOR Y PROCESA LA PRIMERA FILA.
OPEN LOCUR2;
FETCH NEXT FROM LOCUR2 INTO @LS_PARAM_PAR_KEY, @LN_ORDINAL_POSITION;
 
-- ASIGNA EL ID DE PROCEDURE A UNA VARIABLE AUXILIAR.
SET @LS_PARAM_PAR_KEY_ANT = @LS_PARAM_PAR_KEY;
SET @LN_COUNT = 0;
 
-- PROCESA LAS FILAS DEL CURSOR.
WHILE (@@FETCH_STATUS = 0)
BEGIN
	-- COMPARA EL ID DE PROCEDURE DEL PARÁMETRO ACTUAL CON EL ANTERIOR.
	IF (@LS_PARAM_PAR_KEY <> @LS_PARAM_PAR_KEY_ANT) BEGIN
		-- SI EL ID DE PROCEDURE DEL PARÁMETRO ACTUAL ES DIFERENTE, ENTONCES SE TRATA DEL PRIMER PARÁMETRO DE UN NUEVO PROCEDURE.
		SET @LN_COUNT = 1;
		-- ASIGNA EL ID DE PROCEDURE A UNA VARIABLE AUXILIAR.
		SET @LS_PARAM_PAR_KEY_ANT = @LS_PARAM_PAR_KEY;
	END
	ELSE BEGIN
		-- SI EL ID DE PROCEDURE DEL PARÁMETRO ACTUAL ES EL MISMO, ENTONCES SE TRATA DEL N PARÁMETRO DEL MISMO PROCEDURE.
		SET @LN_COUNT = @LN_COUNT + 1;
	END;
	-- RENUMERA EN FORMA CONSECUTIVA LOS PARÁMETROS DE ENTRADA DEL PROCEDIMIENTO ACTUAL.
	UPDATE	SP_PRM_IN
	SET	PRM_INDEX = @LN_COUNT
	WHERE	(PAR_KEY = @LS_PARAM_PAR_KEY
		AND PRM_INDEX = @LN_ORDINAL_POSITION);
	SELECT @LSOPERA = 'UPDATE', @LSTABLA = 'SP_PRM_IN', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
 
	FETCH NEXT FROM LOCUR2 INTO @LS_PARAM_PAR_KEY, @LN_ORDINAL_POSITION;
END;
 
-- CIERRA EL CURSOR.
CLOSE LOCUR2;
DEALLOCATE LOCUR2;
 
-- 2. LA NUMERACIÓN DE LOS PARÁMETROS DE SALIDA DEBE SER CONSECUTIVA Y SIN INTERCALACIONES.
DECLARE LOCUR2 CURSOR LOCAL FAST_FORWARD TYPE_WARNING FOR
	SELECT	PS2.PAR_KEY,
		PS2.PRM_INDEX
	FROM	SP_PRM_OUT PS2
	WHERE	PS2.PAR_KEY IN (
		SELECT	PS.PAR_KEY
		FROM	SP_PRM_OUT PS
		GROUP BY PS.PAR_KEY
		HAVING	(MAX(PS.PRM_INDEX) > COUNT(PS.PRM_INDEX))
		)
	ORDER BY PS2.PAR_KEY ASC,
		PS2.PRM_INDEX ASC;
SELECT @LSOPERA = 'DECLARE CURSOR', @LSTABLA = 'LOCUR2', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
IF (@LNERRORNUM <> 0) GOTO FALLO;
 
-- ABRE EL CURSOR Y PROCESA LA PRIMERA FILA.	
OPEN LOCUR2;
FETCH NEXT FROM LOCUR2 INTO @LS_PARAM_PAR_KEY, @LN_ORDINAL_POSITION;
 
-- ASIGNA EL ID DE PROCEDURE A UNA VARIABLE AUXILIAR.
SET @LS_PARAM_PAR_KEY_ANT = @LS_PARAM_PAR_KEY;
SET @LN_COUNT = 0;
 
-- PROCESA LAS FILAS DEL CURSOR.
WHILE (@@FETCH_STATUS = 0)
BEGIN
	-- COMPARA EL ID DE PROCEDURE DEL PARÁMETRO ACTUAL CON EL ANTERIOR.
	IF (@LS_PARAM_PAR_KEY <> @LS_PARAM_PAR_KEY_ANT) BEGIN
		-- SI EL ID DE PROCEDURE DEL PARÁMETRO ACTUAL ES DIFERENTE, ENTONCES SE TRATA DEL PRIMER PARÁMETRO DE UN NUEVO PROCEDURE.
		SET @LN_COUNT = 1;
		-- ASIGNA EL ID DE PROCEDURE A UNA VARIABLE AUXILIAR.
		SET @LS_PARAM_PAR_KEY_ANT = @LS_PARAM_PAR_KEY;
	END
	ELSE BEGIN
		-- SI EL ID DE PROCEDURE DEL PARÁMETRO ACTUAL ES EL MISMO, ENTONCES SE TRATA DEL N PARÁMETRO DEL MISMO PROCEDURE.
		SET @LN_COUNT = @LN_COUNT + 1;
	END;
	-- RENUMERA EN FORMA CONSECUTIVA LOS PARÁMETROS DE SALIDA DEL PROCEDIMIENTO ACTUAL.
	UPDATE	SP_PRM_OUT
	SET	PRM_INDEX = @LN_COUNT
	WHERE	(PAR_KEY = @LS_PARAM_PAR_KEY
		AND PRM_INDEX = @LN_ORDINAL_POSITION);
	SELECT @LSOPERA = 'UPDATE', @LSTABLA = 'SP_PRM_OUT', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
 
	FETCH NEXT FROM LOCUR2 INTO @LS_PARAM_PAR_KEY, @LN_ORDINAL_POSITION;
END;
 
-- CIERRA EL CURSOR.
CLOSE LOCUR2;
DEALLOCATE LOCUR2;
 
-- CARGA UN CURSOR CON LA CONSULTA DINÁMICA QUE TRAE LOS PARÁMETROS DE ENTRADA DE PROCEDURES Y FUNCTIONS.
DECLARE LOCUR2 CURSOR LOCAL FAST_FORWARD TYPE_WARNING FOR
	SELECT	T1.PARAM_PAR_KEY,
		T1.SP_CODE,
		T1.PROCEDURE_NAME,
		T1.SUBPROCEDURE_NAME,
		T1.ORDINAL_POSITION,
		T1.PARAMETER_NAME,
		T1.NEW_PARAMETER_NAME,
		T1.IN_OUT,
		T1.PARAM_PKEY
	FROM	(
		SELECT	S1.PKEY AS PARAM_PAR_KEY,
			S1.SP_CODE,
			S1.SP_NAME AS PROCEDURE_NAME,
			S1.SP_NAME AS SUBPROCEDURE_NAME,
			PE.PRM_INDEX AS ORDINAL_POSITION,
			PE.PRM_CODE AS PARAMETER_NAME,
			PE.PRM_CODE AS NEW_PARAMETER_NAME,
			'IN' AS IN_OUT,
			PE.PKEY AS PARAM_PKEY
		FROM	STORED_PROCEDURES S1
			INNER JOIN SP_PRM_IN PE ON (S1.PKEY = PE.PAR_KEY)
		UNION ALL
		SELECT	S2.PKEY AS PARAM_PAR_KEY,
			S2.SP_CODE,
			S2.SP_NAME AS PROCEDURE_NAME,
			S2.SP_NAME AS SUBPROCEDURE_NAME,
			(ISNULL(T2.QTY_PRM_INDEX_IN, 0) + PS.PRM_INDEX) AS ORDINAL_POSITION,
			-- PS.PRM_INDEX AS ORDINAL_POSITION,
			PS.PRM_CODE AS PARAMETER_NAME,
			PS.PRM_CODE AS NEW_PARAMETER_NAME,
			'IN/OUT' AS IN_OUT, -- EN MSSQL DEBE SER 'IN/OUT'.
			PS.PKEY AS PARAM_PKEY
		FROM	STORED_PROCEDURES S2
			INNER JOIN SP_PRM_OUT PS ON (S2.PKEY = PS.PAR_KEY)
			LEFT OUTER JOIN (
			SELECT	PE2.PAR_KEY,
				COUNT(PE2.PRM_INDEX) AS QTY_PRM_INDEX_IN
			FROM	SP_PRM_IN PE2
			GROUP BY PE2.PAR_KEY
			) T2 ON (S2.PKEY = T2.PAR_KEY)
		) T1
	ORDER BY T1.PARAM_PAR_KEY ASC,
		T1.IN_OUT ASC,
		T1.ORDINAL_POSITION ASC;
SELECT @LSOPERA = 'DECLARE CURSOR', @LSTABLA = 'LOCUR2', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
IF (@LNERRORNUM <> 0) GOTO FALLO;
 
-- ABRE EL CURSOR Y PROCESA LA PRIMERA FILA.
OPEN LOCUR2;
FETCH NEXT FROM LOCUR2 INTO @LS_PARAM_PAR_KEY, @LS_SP_CODE, @LS_PROCEDURE_NAME, @LS_SUBPROCEDURE_NAME, @LN_ORDINAL_POSITION, @LS_PARAMETER_NAME, @LS_NEW_PARAMETER_NAME, @LS_IN_OUT, @LS_PARAM_PKEY;
 
-- ASIGNA EL ID DE PROCEDURE A UNA VARIABLE AUXILIAR.
SET @LS_PARAM_PAR_KEY_ANT = @LS_PARAM_PAR_KEY;
SET @LN_COUNT = 0;
 
-- PROCESA LAS FILAS DEL CURSOR.
WHILE (@@FETCH_STATUS = 0)
BEGIN
	-- COMPARA EL ID DE PROCEDURE DEL PARÁMETRO ACTUAL CON EL ANTERIOR.
	IF (@LS_PARAM_PAR_KEY <> @LS_PARAM_PAR_KEY_ANT) BEGIN
		-- SI EL ID DE PROCEDURE DEL PARÁMETRO ACTUAL ES DIFERENTE, ENTONCES SE TRATA DEL PRIMER PARÁMETRO DE UN NUEVO PROCEDURE.
		SET @LN_COUNT = 1;
		-- ASIGNA EL ID DE PROCEDURE A UNA VARIABLE AUXILIAR.
		SET @LS_PARAM_PAR_KEY_ANT = @LS_PARAM_PAR_KEY;
	END
	ELSE BEGIN
		-- SI EL ID DE PROCEDURE DEL PARÁMETRO ACTUAL ES EL MISMO, ENTONCES SE TRATA DEL N PARÁMETRO DEL MISMO PROCEDURE.
		SET @LN_COUNT = @LN_COUNT + 1;
	END;
 
	-- INSERTA LOS DATOS DE LOS PROCEDIMIENTOS ALMACENADOS Y SUS PARÁMETROS DE ENTRADA Y SALIDA DE FORMA ORDENADA POR NOMBRE DE PROCEDURE Y POSICIÓN ORDINAL. ESTA ÚLTIMA SE NORMALIZA.
	INSERT INTO	@TMP_SP_PARAMETERS (PARAM_PAR_KEY, SP_CODE, PROCEDURE_NAME, SUBPROCEDURE_NAME, ORDINAL_POSITION, PARAMETER_NAME, NEW_PARAMETER_NAME, IN_OUT, PARAM_PKEY)
	VALUES		(@LS_PARAM_PAR_KEY, @LS_SP_CODE, @LS_PROCEDURE_NAME, @LS_SUBPROCEDURE_NAME, @LN_COUNT, @LS_PARAMETER_NAME, @LS_NEW_PARAMETER_NAME, @LS_IN_OUT, @LS_PARAM_PKEY);
	SELECT @LSOPERA = 'INSERT', @LSTABLA = '@TMP_SP_PARAMETERS', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
 
	FETCH NEXT FROM LOCUR2 INTO @LS_PARAM_PAR_KEY, @LS_SP_CODE, @LS_PROCEDURE_NAME, @LS_SUBPROCEDURE_NAME, @LN_ORDINAL_POSITION, @LS_PARAMETER_NAME, @LS_NEW_PARAMETER_NAME, @LS_IN_OUT, @LS_PARAM_PKEY;
END;
 
-- CIERRA EL CURSOR.
CLOSE LOCUR2;
DEALLOCATE LOCUR2;
 
-- ACTUALIZA LOS NOMBRES DE LOS PARÁMETROS DE LA TABLA TEMPORAL AL IGUAL QUE COMO ESTÁN EN LA BASE DE DATOS.
-- ES PROBABLE QUE HAYA PROCEDIMIENTOS DEFINIDOS EN ENGAGE QUE NO ESTÉN CREADOS FÍSICAMENTE EN LA BASE DE DATOS.
-- EN ESTE ÚLTIMO CASO, NO HABRÁ ACTUALIZACIONES DE LOS NOMBRES DE LOS PARÁMETROS.
UPDATE	@TMP_SP_PARAMETERS
SET	NEW_PARAMETER_NAME = UPPER(REPLACE(P1.PARAMETER_NAME, '@', ''))
FROM	@TMP_SP_PARAMETERS T2
	INNER JOIN EVI_PROCEDURE_PARAMETERS P1 ON (UPPER(T2.PROCEDURE_NAME) = UPPER(P1.PROCEDURE_NAME) AND T2.ORDINAL_POSITION = P1.ORDINAL_POSITION);
SELECT @LSOPERA = 'UPDATE', @LSTABLA = '@TMP_SP_PARAMETERS', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
IF (@LNERRORNUM <> 0) GOTO FALLO;
 
-- ACTUALIZA LOS NOMBRES DE LOS PARÁMETROS DE SALIDA DE PROCEDIMIENTOS ALMACENADOS DE ENGAGE AL IGUAL QUE COMO ESTÁN EN LA BASE DE DATOS.
UPDATE	SP_PRM_OUT
SET	PRM_CODE = T2.NEW_PARAMETER_NAME
--	PRM_INDEX = T2.ORDINAL_POSITION
FROM	@TMP_SP_PARAMETERS T2
WHERE	(SP_PRM_OUT.PKEY = T2.PARAM_PKEY);
SELECT @LSOPERA = 'UPDATE', @LSTABLA = 'SP_PRM_OUT', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
IF (@LNERRORNUM <> 0) GOTO FALLO;
 
-- ACTUALIZA LOS NOMBRES DE LOS PARÁMETROS DE SALIDA QUE ESTÁN COMO CLAVE FORÁNEA EN SP_PRM_OUT_VALUE.
UPDATE	SP_PRM_OUT_VALUE
SET	PRM_CODE = T2.PRM_CODE
FROM	SP_PRM_OUT T2
WHERE	(SP_PRM_OUT_VALUE.PAR_KEY = T2.PKEY);
SELECT @LSOPERA = 'UPDATE', @LSTABLA = 'SP_PRM_OUT_VALUE', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
IF (@LNERRORNUM <> 0) GOTO FALLO;
 
-- ACTUALIZA LOS NOMBRES DE LOS PARÁMETROS DE ENTRADA DE PROCEDIMIENTOS ALMACENADOS DE ENGAGE AL IGUAL QUE COMO ESTÁN EN LA BASE DE DATOS.
UPDATE	SP_PRM_IN
SET	PRM_NAME = T2.NEW_PARAMETER_NAME
--	PRM_CODE = T2.NEW_PARAMETER_NAME, -- SÓLO PARA ENGAGE 5.0.
--	PRM_INDEX = T2.ORDINAL_POSITION
FROM	@TMP_SP_PARAMETERS T2
WHERE	(SP_PRM_IN.PKEY = T2.PARAM_PKEY);
SELECT @LSOPERA = 'UPDATE', @LSTABLA = 'SP_PRM_IN', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
IF (@LNERRORNUM <> 0) GOTO FALLO;
 
-- ACTUALIZA LOS NOMBRES DE LOS PARÁMETROS DE SALIDA DE TRANSACCIONES ASOCIADAS A PROCEDIMIENTOS ALMACENADOS DE ENGAGE, QUE SE MUESTRAN EN FORMULARIOS, AL IGUAL QUE COMO ESTÁN EN LA BASE DE DATOS.
UPDATE	DETAIL_FIELD
SET	FIELD_CODE = T2.NEW_PARAMETER_NAME
FROM	@TMP_SP_PARAMETERS T2
WHERE	(DETAIL_FIELD.CTL_TYPE_CODE = @LS_CTL_TYPE_CODE -- 'sp'
	AND DETAIL_FIELD.FIELD_TYPE = @LS_FIELD_TYPE -- 'SP'
	AND DETAIL_FIELD.FIELD_TYPE_CODE = T2.SP_CODE
	AND DETAIL_FIELD.FIELD_CODE = T2.PARAMETER_NAME);
SELECT @LSOPERA = 'UPDATE', @LSTABLA = 'DETAIL_FIELD', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
IF (@LNERRORNUM <> 0) GOTO FALLO;
 
-- ACTUALIZA LOS NOMBRES DE LOS PARÁMETROS DE SALIDA DE TRANSACCIONES ASOCIADAS A PROCEDIMIENTOS ALMACENADOS DE ENGAGE AL IGUAL QUE COMO ESTÁN EN LA BASE DE DATOS.
-- CARGA UN CURSOR CON LA CONSULTA DINÁMICA QUE TRAE LOS PARÁMETROS DE SALIDA DE TRANSACCIONES ASOCIADAS A PROCEDIMIENTOS ALMACENADOS.
DECLARE LOCUR2 CURSOR LOCAL FAST_FORWARD TYPE_WARNING FOR
	SELECT	TR2.TRAN_CODE,
		T1.SP_CODE,
		T1.PROCEDURE_NAME,
		T1.SUBPROCEDURE_NAME,
		T1.PARAMETER_NAME,
		T1.NEW_PARAMETER_NAME
	FROM	@TMP_SP_PARAMETERS T1
		INNER JOIN TRANSACTIONS TR2 ON (T1.SP_CODE = TR2.TRAN_PROGRAM AND TR2.TRAN_TYPE = @LS_TRAN_TYPE) -- 'Stored Procedure'
	WHERE	(TR2.TRAN_PROGRAM IS NOT NULL
		AND T1.IN_OUT = 'IN/OUT')
	ORDER BY TR2.TRAN_CODE ASC,
		T1.PROCEDURE_NAME ASC,
		T1.ORDINAL_POSITION ASC;
SELECT @LSOPERA = 'DECLARE CURSOR', @LSTABLA = 'LOCUR2', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
IF (@LNERRORNUM <> 0) GOTO FALLO;
 
-- ABRE EL CURSOR Y PROCESA LA PRIMERA FILA.
OPEN LOCUR2;
FETCH NEXT FROM LOCUR2 INTO @LS_TRAN_CODE, @LS_SP_CODE, @LS_PROCEDURE_NAME, @LS_SUBPROCEDURE_NAME, @LS_PARAMETER_NAME, @LS_NEW_PARAMETER_NAME;
 
-- PROCESA LAS FILAS DEL CURSOR.
WHILE (@@FETCH_STATUS = 0)
BEGIN
	-- ACTUALIZA LOS NOMBRES DE LOS PARÁMETROS DE SALIDA DE LAS FÓRMULAS EN LOS FLUJOS DE TRANSACCIONES.
	UPDATE	STEP_TRANSACTION_FLOW
	SET	PRM_VALUE = REPLACE(PRM_VALUE, @LS_TRAN_CODE + '.' + @LS_PARAMETER_NAME, @LS_TRAN_CODE + '.' + @LS_NEW_PARAMETER_NAME)
	WHERE	(STEP_TRANSACTION_FLOW.PRM_IDR = @LS_PRM_IDR -- 'formula'
		AND STEP_TRANSACTION_FLOW.TRAN_CODE = @LS_TRAN_CODE);
	SELECT @LSOPERA = 'UPDATE', @LSTABLA = 'STEP_TRANSACTION_FLOW', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
 
	-- ACTUALIZA LOS NOMBRES DE LOS PARÁMETROS DE SALIDA UTILIZADOS COMO PARÁMETROS DE ENTRADA DE OTROS PROCEDIMIENTOS ALMACENADOS.
	UPDATE	SP_PRM_IN
	SET	PRM_VAL = REPLACE(PRM_VAL, 'SP.' + @LS_PARAMETER_NAME + '.' + @LS_SP_CODE, 'SP.' + @LS_NEW_PARAMETER_NAME + '.' + @LS_SP_CODE)
	WHERE	(SP_PRM_IN.SP_CODE = @LS_SP_CODE
		AND SP_PRM_IN.PRM_VAL LIKE 'SP.%');
	SELECT @LSOPERA = 'UPDATE', @LSTABLA = 'SP_PRM_IN', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
 
	-- ACTUALIZA LOS NOMBRES DE LOS PARÁMETROS DE SALIDA UTILIZADOS COMO PARÁMETROS DE ENTRADA DE OTRAS TRANSACCIONES.
	UPDATE	TRAN_PRM_IN
	SET	PRM_VAL = REPLACE(PRM_VAL, 'SP.' + @LS_PARAMETER_NAME + '.' + @LS_SP_CODE, 'SP.' + @LS_NEW_PARAMETER_NAME + '.' + @LS_SP_CODE)
	WHERE	(TRAN_PRM_IN.TRAN_CODE = @LS_TRAN_CODE
		AND TRAN_PRM_IN.PRM_VAL LIKE 'SP.%');
	SELECT @LSOPERA = 'UPDATE', @LSTABLA = 'TRAN_PRM_IN', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
 
	FETCH NEXT FROM LOCUR2 INTO @LS_TRAN_CODE, @LS_SP_CODE, @LS_PROCEDURE_NAME, @LS_SUBPROCEDURE_NAME, @LS_PARAMETER_NAME, @LS_NEW_PARAMETER_NAME;
END;
 
-- CIERRA EL CURSOR.
CLOSE LOCUR2;
DEALLOCATE LOCUR2;
 
FALLO:
-- REGISTRO DE SUCESOS Y CONTROL DE FIN DE PROCEDIMIENTO. CONCLUYE LA TRANSACCIÓN SI TODO FUE EXITOSO.
SELECT @LNDURACION = DATEDIFF(SECOND, @LDINICIO_OPE, GETDATE()), @LNSEVERITY = ISNULL(EM.SEVERITY, 16), @LSERRORDESC = 'ERROR ' + CONVERT(VARCHAR, ISNULL(EM.ERROR, 0)) + ' - ' + ISNULL(EM.DESCRIPTION, ' ') FROM MASTER.DBO.SYSMESSAGES EM WHERE (EM.ERROR = @LNERRORNUM);
IF (@LNERRORNUM <> 0) BEGIN
	-- NOTIFICACIÓN EN EL REGISTRO DE SQL SERVER.
	SET @LSERRORLOG = @LSERRORLOG + CASE WHEN (ISNULL(CHARINDEX('%', @LSERRORDESC), 0) > 0) THEN RTRIM(LEFT(@LSERRORDESC, 11)) ELSE @LSERRORDESC END;
	-- DEVUELVE EL ERROR EN EL PARÁMETRO DE SALIDA.
	SET @PS_RET_MESSAGE = SUBSTRING(@LSERRORDESC, 1, 440);
	-- DESHACE LA TRANSACCIÓN COMPLETA SI LA OPERACIÓN FALLÓ.
	IF (@@TRANCOUNT > 0) ROLLBACK TRANSACTION;
	EXECUTE @LNERRORNUM = PA_SYS_REGISTRO_SUCESOS_INSERT @PSPROCEDIMIENTO_1 = @LSPROC, @PSTABLA_2 = @LSTABLA, @PNFILAS_AFECTADAS_3 = @LNFILAS_AFEC, @PSOPERACION_4 = @LSOPERA, @PNDURACION_5 = @LNDURACION, @PSRESULTADO_6 = @LSERRORDESC, @PSSQL_CMD_7 = @LSERRORDESC;
	-- RAISERROR(@LSERRORLOG, @LNSEVERITY, -1) WITH NOWAIT;
END
ELSE BEGIN
	EXECUTE @LNERRORNUM = PA_SYS_REGISTRO_SUCESOS_INSERT @PSPROCEDIMIENTO_1 = @LSPROC, @PSTABLA_2 = @LSTABLA, @PNFILAS_AFECTADAS_3 = @LNFILAS_AFEC, @PSOPERACION_4 = @LSOPERA, @PNDURACION_5 = @LNDURACION, @PSRESULTADO_6 = @LSERRORDESC, @PSSQL_CMD_7 = @LSERRORDESC;
	IF (@@TRANCOUNT > 0) COMMIT TRANSACTION;
END;
RETURN;
