CREATE PROCEDURE [dbo].[HOME_VAL_AGENDA_PASO4]
(@IPKEYJOB	AS VARCHAR(100),
 @FORM_ID	AS VARCHAR(100),
 @OCODE		AS INT OUTPUT)
AS
 
DECLARE	@VCLIENTE			VARCHAR(100), 
		@VID_PROYECTO		VARCHAR(100),
		@VID_SERVICIO		VARCHAR(100),
		@VID_AGENDA			VARCHAR(100),
		@VTIPO_SERVICIO		VARCHAR(100),
		@VFECHA_DESDE		VARCHAR(100),
		@VFECHA_HASTA		DATETIME,
		@VSELECCION			VARCHAR(MAX),	
		@VAGENDAS			VARCHAR(MAX),
		@VID				VARCHAR(100),
		@VALOR				VARCHAR(400),
		@lstDato			VARCHAR(100), 
		@lnuPosComa			INT,
		@lstNorma			VARCHAR(100),
		@lnuPosComa2		INT,
		@VDIF				INT,
		@VREG				INT,
		@VCANT				INT,
		@VFECHA				DATETIME,
		@VDESCCONS			VARCHAR(4000),
		@RESULTADO			INT,
		@VEXISTE			VARCHAR(50),
		@VAGREGO			VARCHAR(50),
		@VTORF				VARCHAR(50),
		@VUSUARIO			VARCHAR(100),
		@VTOTAL_HORAS_DIA	NUMERIC(5),
		@VCONSULTOR			VARCHAR(50),
		@VFECHA_VISITA		VARCHAR(50),
		@VHORAS_VISITA		INT,
		@VHORAS_DISP		INT,
		@VHORAS_DIA			INT,
		@VCONSULTORES		VARCHAR(MAX),
		@VHORAS_AGENDA		INT,
		@VCONSULORES_AGENDA	VARCHAR(MAX),
		@VTIENE_HORAS		INT,
		@VTOTAL_HORAS_CONSULTOR	NUMERIC(5),
		@ES_FERIADO			INT,
		@VTOTAL_HORAS_SERV	INT,
		@VTOTAL_HORAS_EJEC_SERV	INT,
		@VTOTAL_HORAS_CARGA	INT
		
BEGIN
	
	SET @OCODE = 0
 
	SELECT	@VCLIENTE = ISNULL(CLIENTE,''),
			@VID_PROYECTO =	ISNULL(PROYECTO_ID,''),
			@VID_SERVICIO = ISNULL(PROYECTO_SERV_ID,''),
			@VID_AGENDA	= ISNULL(AGENDA_ID,''),
			@VFECHA_DESDE = ISNULL(AGENDA_DESDE,''),
			@VFECHA_HASTA = ISNULL(AGENDA_HASTA,''),
			@VSELECCION = ISNULL(ALMACENA_HORAS,''),
			@VCONSULTORES = ISNULL(AGENDA_CONSULTORES,'')
	FROM	XAGENDA
	WHERE	PAR_KEY = @IPKEYJOB
 
	SELECT	@VTOTAL_HORAS_SERV = ISNULL(TOTAL_HORAS_PROYECTADAS,0),
			@VTOTAL_HORAS_EJEC_SERV = ISNULL(CONVERT(VARCHAR,[dbo].[FN_GET_TOTAL_HS_EJECUTADAS] ('PS', NULL, NULL, ID_PROYECTO_SERVICIO)),0)
	FROM	LK_PROYECTO_SERVICIO
	WHERE	ID_PROYECTO_SERVICIO = @VID_SERVICIO
 
	IF (@VID_AGENDA <> '') BEGIN
						
		SELECT	@VCONSULORES_AGENDA = ID_CONSULTOR
		FROM	LK_AGENDA
		WHERE	ID_AGENDA = @VID_AGENDA
	END
 
	--SI SELECCIONA CONSULTOR/ES VALIDO QUE ESTEN DISPONIBLE EN EL RANGO DE FECHAS DESDE Y HASTA-- 
	IF (ISNULL(@VCONSULTORES,'') <> '') BEGIN
 
		IF (ISNULL(@VSELECCION,'') <> '') BEGIN
 
			SET @VAGENDAS = @VSELECCION
				
			--RECORRO EL/LAS VISITAS
			WHILE LEN(@VAGENDAS) > 0
			BEGIN 
				SET @VALOR = NULL
				SET @lnuPosComa = CHARINDEX('|', @VAGENDAS) -- Busca el caracter a separador
 
				IF (@lnuPosComa = 0) BEGIN 
					SET @lstDato = @VAGENDAS
					SET @VAGENDAS = '' 
				END ELSE BEGIN
					SET @lstDato = SUBSTRING(@VAGENDAS, 1, @lnuPosComa - 1)
					SET @VID = SUBSTRING(@lstDato,1,CHARINDEX('=', @lstDato)-1)
					SET @VALOR = SUBSTRING(@lstDato,CHARINDEX('=', @lstDato)+1,LEN(@lstDato))
				
					--GRABO EN LA TABLA DE VISITAS LOS VALORES HORARIOS CARGADOS--
					UPDATE	XAGENDA_VISITAS
					SET		HORAS = CONVERT(NUMERIC,@VALOR)
					WHERE	PKEY = @VID
 
					SET @VAGENDAS = SUBSTRING(@VAGENDAS, @lnuPosComa + 1, LEN(@VAGENDAS))
				END
			END
 
			--valido que haya al menos una hora por fecha--
			SET @VREG = 0
			SET @VDIF = DATEDIFF(DD,@VFECHA_DESDE,@VFECHA_HASTA)
			SET @VFECHA = @VFECHA_DESDE
 
			WHILE @VREG <= @VDIF  
			BEGIN 
			
				SELECT	@VTOTAL_HORAS_DIA = ISNULL(SUM(HORAS),0)
				FROM	XAGENDA_VISITAS
				WHERE	PAR_KEY = @IPKEYJOB	
				AND		FECHA = CONVERT(VARCHAR,@VFECHA,23)
			
				IF (@VTOTAL_HORAS_DIA = 0) BEGIN
					UPDATE	XAGENDA
					SET		DESC_ERROR = 'Debe Ingresar al menos una Hora para la Fecha '+CONVERT(VARCHAR,CONVERT(DATE,@VFECHA,23),103)
					WHERE	PAR_KEY = @IPKEYJOB
 
					SET @OCODE = 1
					RETURN
				END
 
				SET @VFECHA = DATEADD(DD,1,@VFECHA)
				SET @VREG = @VREG + 1
			END
 
			SET @ES_FERIADO = 0
			--SET @VTOTAL_HORAS_CARGA = 0
 
			--recorro todas las visitas-- valido disponibilidad por dia por consultor
			DECLARE Visitas CURSOR FOR
			SELECT	ID_CONSULTOR, FECHA, HORAS
			FROM	XAGENDA_VISITAS
			WHERE	PAR_KEY = @IPKEYJOB
			ORDER BY FECHA
 
			OPEN Visitas
			FETCH NEXT FROM Visitas INTO @VCONSULTOR, @VFECHA_VISITA, @VHORAS_VISITA
	
				WHILE @@FETCH_STATUS = 0  
				BEGIN  
					
					--AGREGO CONTROL POR FECHA PARA VER SI ES FERIADO O NO-- GENERO UN REGISTRO
					SELECT	@ES_FERIADO = COUNT(1)
					FROM	Calendar
					WHERE	FECHA = @VFECHA_VISITA
					AND		ISHOLIDAY = 1
 
					IF (@ES_FERIADO = 0) BEGIN
 
						--busco la disponibilidad horaria del consultor por fecha--
						SET @VHORAS_DISP = [dbo].[FN_GET_CONSULTOR_HORAS_DISP] (@VCONSULTOR, @VFECHA_VISITA)
					
						SET @VHORAS_DIA = [dbo].[FN_GET_CONSULTOR_HORAS] (@VCONSULTOR, @VFECHA_VISITA)
					
					END ELSE BEGIN
						SET @VHORAS_DISP = @VHORAS_VISITA
						SET @VHORAS_DIA = @VHORAS_VISITA
					END
					
					SELECT	@VDESCCONS = APELLIDO_EMPLEADO + ', ' + NOMBRE_EMPLEADO
					FROM	LK_EMPLEADOS
					WHERE	CONVERT(VARCHAR,ID_EMPLEADO) = @VCONSULTOR
 
					--VALIDO SI SELECCIONO UN CONSULTOR PERO NO CARGO HORAS PARA NINGUN DIA--
					SELECT	@VTOTAL_HORAS_CONSULTOR = SUM(HORAS)
					FROM	XAGENDA_VISITAS
					WHERE	PAR_KEY = @IPKEYJOB
					AND		ID_CONSULTOR = @VCONSULTOR
 
					IF (@VTOTAL_HORAS_CONSULTOR = 0) BEGIN
						UPDATE	XAGENDA
						SET		DESC_ERROR = 'NO Debe Seleccionar al Consultor '+ISNULL(@VDESCCONS,'')+' Sino Carga Horas para Ninguna de las Fechas de la Visita'
						WHERE	PAR_KEY = @IPKEYJOB
 
						SET @OCODE = 1
						RETURN
					END
 
					--RECUPERO LAS HORAS DEL CONSULTOR POR FECHA PARA ESA AGENDA-- si modifica 
					IF (@VID_AGENDA <> '') BEGIN
						
						--si modifica y el consultor ya estaba en la agenda-- recupero las horas cargadas previas
						IF (CHARINDEX('|'+@VCONSULTOR+'|','|'+@VCONSULORES_AGENDA) > 0) BEGIN
							
							SET @VTIENE_HORAS = 0
 
							SELECT	@VTIENE_HORAS = COUNT(1)
							FROM	LK_AGENDA_EMPLEADO
							WHERE	ID_EMPLEADO = @VCONSULTOR
							AND		FECHA = @VFECHA_VISITA
							AND		HOLIDAYTEXT = @VID_AGENDA
 
							IF (@VTIENE_HORAS <> 0) BEGIN
								SELECT	@VHORAS_AGENDA = ISNULL(HORAS,0)
								FROM	LK_AGENDA_EMPLEADO
								WHERE	ID_EMPLEADO = @VCONSULTOR
								AND		FECHA = @VFECHA_VISITA
								AND		HOLIDAYTEXT = @VID_AGENDA
 
							END ELSE BEGIN
 
								SET @VHORAS_AGENDA = 0
 
							END
						
						END ELSE BEGIN
							
							SET @VHORAS_AGENDA = 0
						END
					END
 
					IF (@VID_AGENDA = '') BEGIN
						IF (@ES_FERIADO = 0) BEGIN
							SET @VHORAS_DISP = @VHORAS_DISP - @VHORAS_DIA
						END
 
					END ELSE BEGIN
						IF (@ES_FERIADO = 0) BEGIN
							SET @VHORAS_DISP = (@VHORAS_DISP - @VHORAS_DIA) + @VHORAS_AGENDA
						END
					END
 
					IF (@VHORAS_DISP < @VHORAS_VISITA) BEGIN
						UPDATE	XAGENDA
						SET		DESC_ERROR = 'El Consultor '+ISNULL(@VDESCCONS,'')+' tiene '+ CONVERT(VARCHAR,@VHORAS_DISP)+' Horas Disponibles para la Fecha '+CONVERT(VARCHAR,CONVERT(DATE,@VFECHA_VISITA,23),103)
						WHERE	PAR_KEY = @IPKEYJOB
 
						SET @OCODE = 1
						RETURN
					END				
 
					FETCH NEXT FROM Visitas INTO @VCONSULTOR, @VFECHA_VISITA, @VHORAS_VISITA
				END 
 
			CLOSE Visitas  
			DEALLOCATE Visitas
		
		END ELSE BEGIN
			UPDATE	XAGENDA
			SET		DESC_ERROR = 'Debe Ingresar al menos una Hora para la/s Fecha/s y el/los Consultor/es Seleccionados'
			WHERE	PAR_KEY = @IPKEYJOB
 
			SET @OCODE = 1
			RETURN
		END
	END
 
	--valido que el total de horas ingresadas para el/los consultor/es NO supere el total de horas del servicio--
	IF (@VID_AGENDA = '') BEGIN
		--SI AGREGA NO HAY AGENDA (HORAS) PREVIAS--
		--RECUPERO EL TOTAL DE HORAS CARGADAS PARA EL/LOS CONSULTOR/ES PARA LA/S FECHA/S SELECCIONADAS
		SELECT	@VTOTAL_HORAS_CARGA = SUM(HORAS)
		FROM	XAGENDA_VISITAS
		WHERE	PAR_KEY = @IPKEYJOB
 
		SET @VTOTAL_HORAS_EJEC_SERV = @VTOTAL_HORAS_EJEC_SERV + @VTOTAL_HORAS_CARGA
 
	END ELSE BEGIN
		
		DECLARE @VHORAS_PREVIAS_AGENDA INT
 
		--SI MODIFICA, RECUPERO LAS HORAS CARGADAS PREVIAMENTE PARA LA AGENDA, CON LA MISMA O DISTINTA FECHA--
		SELECT	@VHORAS_PREVIAS_AGENDA = ISNULL(SUM(HORAS),0)
		FROM	LK_AGENDA_EMPLEADO
		WHERE	HOLIDAYTEXT = @VID_AGENDA
		
		SELECT	@VTOTAL_HORAS_CARGA = SUM(HORAS)
		FROM	XAGENDA_VISITAS
		WHERE	PAR_KEY = @IPKEYJOB
 
		SET @VTOTAL_HORAS_EJEC_SERV = (@VTOTAL_HORAS_EJEC_SERV + @VTOTAL_HORAS_CARGA) - @VHORAS_PREVIAS_AGENDA
 
	END
 
	--valido que el total de horas ingresadas para el/los consultor/es NO supere el total de horas del servicio--
	IF (@VTOTAL_HORAS_EJEC_SERV > @VTOTAL_HORAS_SERV) BEGIN
		UPDATE	XAGENDA
		SET		DESC_ERROR = 'El Total de Horas ingresadas, supera el Total de Horas del Servicio ('+CONVERT(VARCHAR,@VTOTAL_HORAS_SERV)+'). Horas ejecutadas ('+CONVERT(VARCHAR,@VTOTAL_HORAS_EJEC_SERV)+')'
		WHERE	PAR_KEY = @IPKEYJOB
 
		SET @OCODE = 1
		RETURN
	END
 
	IF (@OCODE = 0) BEGIN
		UPDATE	XAGENDA
		SET		DESC_ERROR = NULL
		WHERE	PAR_KEY = @IPKEYJOB
	END
END
