CREATE PROCEDURE [dbo].[PA_SYS_CAT_DATA_INI]
 
@PKEY_JOB VARCHAR(100)
 
AS
 
BEGIN
 
DECLARE 
@AT_1_LABEL VARCHAR(20),
@AT_2_LABEL VARCHAR(20),
@AT_3_LABEL VARCHAR(20),
@AT_4_LABEL VARCHAR(20),
@AT_5_LABEL VARCHAR(20),
@AT_6_LABEL VARCHAR(20)
 
SELECT @AT_1_LABEL=CT.ATTR1, @AT_2_LABEL=CT.ATTR2, @AT_3_LABEL=CT.ATTR3, @AT_4_LABEL=CT.ATTR4,
@AT_5_LABEL=CT.ATTR5,@AT_6_LABEL=CT.ATTR6
FROM     CAT_DATA CD 
INNER JOIN TMT_CATEGORIAS TMT ON CD.PKEY = TMT.PKEY_ELEM
INNER JOIN CAT_TYPE CT ON CT.PKEY = CD.PAR_KEY
WHERE    TMT.PAR_KEY = @PKEY_JOB;
 
UPDATE TMT_CATEGORIAS
SET COD_ELEMENTO=NULL,
ELEM_DESC=NULL,
AT_1=NULL,
AT_2=NULL,
AT_3=NULL,
AT_4=NULL,
AT_5=NULL,
AT_6=NULL,
AT_1_LABEL=@AT_1_LABEL,
AT_2_LABEL=@AT_2_LABEL,
AT_3_LABEL=@AT_3_LABEL,
AT_4_LABEL=@AT_4_LABEL,
AT_5_LABEL=@AT_5_LABEL,
AT_6_LABEL=@AT_6_LABEL
WHERE PAR_KEY = @PKEY_JOB
 
END
 
