CREATE PROCEDURE [dbo].[PA_SYS_CAT_DATA_GRABAR]
 
@PKEY_JOB VARCHAR(100), @ACCION VARCHAR(10), @USER_ID VARCHAR(30),@RET VARCHAR(100) OUTPUT 
 
AS
 
BEGIN
 
DECLARE 
@AT_1 VARCHAR(300),
@AT_2 VARCHAR(50),
@AT_3 VARCHAR(50),
@AT_4 VARCHAR(50),
@AT_5 VARCHAR(50),
@AT_6 VARCHAR(50),
@COD VARCHAR(50),
@DESC VARCHAR(300),
@PKEY_CAT VARCHAR(36),
@CANT int
 
SELECT @COD=TMT.COD_ELEMENTO, @DESC = TMT.ELEM_DESC, @AT_1=TMT.AT_1, 
@AT_2=TMT.AT_2, @AT_3=TMT.AT_3, @AT_4=TMT.AT_4, @AT_5=TMT.AT_5, @AT_6=tmt.AT_6,
@PKEY_CAT=PKEY_CATEG
FROM     TMT_CATEGORIAS TMT
WHERE    TMT.PAR_KEY = @PKEY_JOB;
 
IF @ACCION='NUEVO'
	BEGIN
		
		set @COD=REPLACE(LTRIM(rtrim(@COD)),' ', '_');
		select @CANT=COUNT(*) from CAT_DATA where PAR_KEY=@PKEY_CAT and CAT_DATA_CODE=@COD;
		IF @CANT>0 
			BEGIN
				SET @RET='El codigo ya existe, no se puede repetir'
			END
		ELSE
			BEGIN
				INSERT INTO CAT_DATA(PKEY, PAR_KEY, CAT_DATA_CODE, CAT_DATA_DESC, ATTR1, ATTR2, ATTR3, ATTR4, ATTR5, ATTR6, TS_BEGIN, TS_END, TS_USER_ID, CAT_INACTIVE)
				VALUES (NEWID(),@PKEY_CAT,  REPLACE(LTRIM(rtrim(@COD)),' ', '_'), @DESC, @AT_1,@AT_2,@AT_3,@AT_4,@AT_5, @AT_6,GETDATE(), GETDATE(),@USER_ID, '0');
				SET @RET='OK'
			END
	END
ELSE
	BEGIN
		UPDATE CD
		SET CAT_DATA_DESC=@DESC,
		ATTR1=@AT_1,
		ATTR2=@AT_2,
		ATTR3=@AT_3,
		ATTR4=@AT_4,
		ATTR5=@AT_5,
		ATTR6=@AT_6
		FROM CAT_DATA CD INNER JOIN TMT_CATEGORIAS TMT ON TMT.PKEY_ELEM=CD.PKEY
		WHERE TMT.PAR_KEY = @PKEY_JOB;
		SET @RET='OK'
	END
END
 
