 
CREATE PROCEDURE [dbo].[HOME_ELIMINA_VISITA]
(@IPKEYJOB	AS VARCHAR(100),
 @ELIMINA	AS VARCHAR(50))
AS
 
DECLARE	@VCLIENTE			VARCHAR(100), 
		@VID_PROYECTO		VARCHAR(100),
		@VID_SERVICIO		VARCHAR(100),
		@VID_AGENDA			VARCHAR(100),
		@VID_DELETE			VARCHAR(100),
		@VFECHA_DESDE		DATE,
		@VFECHA_HASTA		DATE,
		@VFECHA				DATE,
		@VHORAS_AGENDA		INT,
		@VCONSULTORES_AGENDA VARCHAR(MAX),
		@VCONSULTORES		VARCHAR(MAX),
		@lnuPosComa			INT,
		@lstDato			VARCHAR(100),
		@VCANT				INT,
		@ES_FERIADO			INT
 
BEGIN	
 
	SELECT	@VCLIENTE = ISNULL(CLIENTE,''),
			@VID_PROYECTO =	ISNULL(PROYECTO_ID,''),
			@VID_SERVICIO = ISNULL(PROYECTO_SERV_ID,''),
			@VID_AGENDA	= ISNULL(AGENDA_ID,''),
			@VID_DELETE = ISNULL(ID_DELETE,'')
	FROM	XAGENDA
	WHERE	PAR_KEY = @IPKEYJOB
	
	IF (@VID_DELETE <> '') BEGIN
 
		SELECT	@VFECHA_DESDE = FECHA,
				@VFECHA_HASTA = FECHA_HASTA,
				@VCONSULTORES_AGENDA = ID_CONSULTOR
		FROM	LK_AGENDA
		WHERE	ID_AGENDA = @VID_DELETE
		
		SELECT	@VHORAS_AGENDA = SUM(HORAS)
		FROM	LK_AGENDA_EMPLEADO
		WHERE	HOLIDAYTEXT = @VID_DELETE
 
		--RECORRO FECHA_DESDE A FECHA_HASTA DE LA AGENDA A EL/LOS CONSULTOR/ES--
		SET @VFECHA = @VFECHA_DESDE
 
		WHILE @VFECHA <= @VFECHA_HASTA BEGIN
			
			SET @VCONSULTORES = @VCONSULTORES_AGENDA
 
			WHILE LEN(@VCONSULTORES) > 0
			BEGIN 
				SET @lnuPosComa = CHARINDEX('|', @VCONSULTORES) -- Busca el caracter a separador
				IF (@lnuPosComa = 0) BEGIN 
					SET @lstDato = @VCONSULTORES
					SET @VCONSULTORES = '' 
				END ELSE BEGIN
					SET @lstDato = SUBSTRING(@VCONSULTORES, 1, @lnuPosComa - 1)
 
					SET @VCANT = 0
					SET @ES_FERIADO = 0
 
					--AGREGO CONTROL POR FECHA PARA VER SI ES FERIADO O NO-- GENERO UN REGISTRO
					SELECT	@ES_FERIADO = COUNT(1)
					FROM	Calendar
					WHERE	FECHA = @VFECHA
					AND		ISHOLIDAY = 1
 
					--VERIFICO CUANTOS REGISTROS TIENE EL CONSULTOR POR FECHA DISTINTOS DE LA AGENDA--
					SELECT	@VCANT = COUNT(1)
					FROM	LK_AGENDA_EMPLEADO
					WHERE	FECHA		= @VFECHA
					AND		CONVERT(VARCHAR,ID_EMPLEADO) = @lstDato
					AND		HOLIDAYTEXT <> @VID_DELETE
 
					IF (@ES_FERIADO > 0) BEGIN
						SET @VCANT = 1
					END
 
					IF (@VCANT = 0) BEGIN
						--ACTUALIZO EL REGISTRO DE LA AGENDA DEL EMPLEADO A DISPONIBLE--
						UPDATE LK_AGENDA_EMPLEADO
						SET	   TIPO = 'D', HOLIDAYTEXT = '', HORAS = 0
						WHERE  FECHA		= @VFECHA
						AND		HOLIDAYTEXT = @VID_DELETE
						AND		CONVERT(VARCHAR,ID_EMPLEADO) = @lstDato
 
					END ELSE BEGIN
 
						--SI TENGO OTRA/S AGENDA/S, BORRO EL REGISTRO DE LA AGENDA DEL EMPLEADO--
						DELETE	LK_AGENDA_EMPLEADO
						WHERE  FECHA		= @VFECHA
						AND		HOLIDAYTEXT = @VID_DELETE
						AND		CONVERT(VARCHAR,ID_EMPLEADO) = @lstDato
					END
				
					SET @VCONSULTORES = SUBSTRING(@VCONSULTORES, @lnuPosComa + 1, LEN(@VCONSULTORES))
				END
			END
 
			SET @VFECHA = CONVERT(date, DATEADD(DD,1,@VFECHA), 105)
 
		END
		
		--actualizo el total de horas del servicio y del proyecto
		UPDATE	LK_PROYECTO_SERVICIO
		SET		TOTAL_HORAS_EJECUTADAS = ISNULL(TOTAL_HORAS_EJECUTADAS,0) - ISNULL(@VHORAS_AGENDA,0)
		WHERE	ID_PROYECTO_SERVICIO = @VID_SERVICIO
 
		UPDATE	LK_PROYECTO
		SET		TOTAL_HORAS_EJECUTADAS = ISNULL(TOTAL_HORAS_EJECUTADAS,0) - ISNULL(@VHORAS_AGENDA,0)
		WHERE	ID_PROYECTO = @VID_PROYECTO
 
		--ACTUALIZO LOS PORCENTAJES
		UPDATE	LK_PROYECTO_SERVICIO
		SET		PORCENTAJE_AVANCE = CASE WHEN TOTAL_HORAS_PROYECTADAS = 0 THEN 0 ELSE TOTAL_HORAS_EJECUTADAS * 100 / TOTAL_HORAS_PROYECTADAS END
		WHERE	ID_PROYECTO_SERVICIO = @VID_SERVICIO
 
		UPDATE	LK_PROYECTO
		SET		PORCENTAJE_AVANCE_TOTAL = CASE WHEN TOTAL_HORAS_PROYECTADAS = 0 THEN 0 ELSE TOTAL_HORAS_EJECUTADAS * 100 / TOTAL_HORAS_PROYECTADAS END
		WHERE	ID_PROYECTO = @VID_PROYECTO	
 
		UPDATE	XAGENDA
		SET		ID_DELETE = NULL--, AGENDA_ID = NULL
		WHERE	PAR_KEY = @IPKEYJOB
 
		--ELIMINO DOCUMENTACION, HOJA DE RUTA, VIATICOS Y LA AGENDA DEL PROYECTO/SERVICIO SOLO SI ELIMINA LA VISITA--
		IF (@ELIMINA = 'SI') BEGIN
			DELETE LK_PROYECTO_DOCUM_DET WHERE ID_PROYECTO_DOCUM IN (SELECT ID_PROYECTO_DOCUM FROM LK_PROYECTO_DOCUM WHERE ID_AGENDA = @VID_DELETE)
			DELETE LK_PROYECTO_DOCUM WHERE ID_AGENDA = @VID_DELETE
			DELETE LK_PROYECTO_VIATICOS WHERE ID_AGENDA = @VID_DELETE
			DELETE LK_PROYECTO_VIATICOS_DET WHERE ID_AGENDA = @VID_DELETE
			DELETE LK_PROYECTO_HONORARIOS WHERE ID_AGENDA = @VID_DELETE
			DELETE LK_AGENDA WHERE ID_AGENDA = @VID_DELETE
		END		
	END
 
END
 
