CREATE PROCEDURE [dbo].[PA_SYS_EXISTE_USR_SHARED_CUST]
@PSCUSTPKEY VARCHAR(60),
@PSUSERID VARCHAR(30),
@PNCANTIDAD INT OUTPUT
 
AS
DECLARE @RESULT as INT
 
--Verifica que tenga permiso en la unidad
SET @RESULT = (
	select count(*) from CUSTOMER 
		where PKEY = @PSCUSTPKEY  
		AND OWNER_UNIT_CODE IN (
			SELECT DISTINCT OD.UNIT_CODE
			FROM ORGANIZATION O
			INNER JOIN ORGANIZATION OD ON (
			(O.UNIT_CODE=OD.NIVEL1)
			OR
			(O.UNIT_CODE=OD.NIVEL2)
			OR
			(O.UNIT_CODE=OD.NIVEL3)
			OR
			(O.UNIT_CODE=OD.NIVEL4)
			OR
			(O.UNIT_CODE=OD.NIVEL5)
			OR
			(O.UNIT_CODE=OD.NIVEL6)
			OR
			(O.UNIT_CODE=OD.NIVEL7)
			) 
			INNER JOIN SUPERVISOR S ON O.UNIT_CODE=S.UNIT_CODE
			AND O.NIVEL=S.UNIT_LEVEL 
			AND OD.NIVEL>=S.UNIT_LEVEL 
			WHERE OD.BOTTOM=1 
			AND S.SUPERVISOR_CODE=@PSUSERID
			UNION 
			SELECT DISTINCT O.UNIT_CODE
			FROM AGENTE A 
			INNER JOIN ORGANIZATION O ON A.UNIT_CODE=O.UNIT_CODE 
			WHERE O.BOTTOM=1
			AND A.USER_ID=@PSUSERID)
	)
 
IF @RESULT > 0
    SET @PNCANTIDAD = 1
ELSE
	BEGIN
		--SINO Verifica que tenga permiso el usuario
		SET @RESULT = (select count(*) from SHARED_CUSTOMER where PAR_KEY = @PSCUSTPKEY  AND USER_ID = @PSUSERID AND UNIT_CODE IN 
		(SELECT DISTINCT OD.UNIT_CODE
		FROM ORGANIZATION O
		INNER JOIN ORGANIZATION OD ON (
		(O.UNIT_CODE=OD.NIVEL1)
		OR
		(O.UNIT_CODE=OD.NIVEL2)
		OR
		(O.UNIT_CODE=OD.NIVEL3)
		OR
		(O.UNIT_CODE=OD.NIVEL4)
		OR
		(O.UNIT_CODE=OD.NIVEL5)
		OR
		(O.UNIT_CODE=OD.NIVEL6)
		OR
		(O.UNIT_CODE=OD.NIVEL7)
		) 
		INNER JOIN SUPERVISOR S ON O.UNIT_CODE=S.UNIT_CODE
		AND O.NIVEL=S.UNIT_LEVEL 
		AND OD.NIVEL>=S.UNIT_LEVEL 
		WHERE OD.BOTTOM=1 
		AND S.SUPERVISOR_CODE=@PSUSERID
		UNION 
		SELECT DISTINCT O.UNIT_CODE
		FROM AGENTE A 
		INNER JOIN ORGANIZATION O ON A.UNIT_CODE=O.UNIT_CODE 
		WHERE O.BOTTOM=1
		AND A.USER_ID=@PSUSERID))
	END
	
 
IF @RESULT > 0
    SET @PNCANTIDAD = 1
ELSE
	BEGIN
		SET @PNCANTIDAD = 0
	END
	
	SELECT @PNCANTIDAD
    
RETURN
