CREATE PROCEDURE [dbo].[HOME_ADD_VIATICO]
(@IPKEYJOB	AS VARCHAR(100),
 @IAGENTE	AS VARCHAR(100),
 @OCODE		AS VARCHAR(2) OUTPUT,
 @OMENSAJE	AS VARCHAR(400) OUTPUT)
AS
 
DECLARE	@VPROYECTO				VARCHAR(50),
		@VSERVICIO				VARCHAR(50),
		@VPROYECTO_SERV			VARCHAR(50),
		@VID_SELEC				VARCHAR(100),
		@VTIPO_SERV				VARCHAR(50),
		@VPROVEEDOR_ID			VARCHAR(50),
		@VTIPO_PROV				VARCHAR(50),
		@VNRO_FACTURA_PROV		VARCHAR(50),
		@VCANT_PERSONAS_PROV	VARCHAR(50),
		@VDESCRIP_SERVICIO_PROV	VARCHAR(100),
		@VFECHA_FACTURA_PROV	DATETIME,
		@VPRECIO_FINAL_PROV		NUMERIC(14,2),
		@VFORMA_PAGO_PROV		VARCHAR(50),
		@VCANT_CUOTAS_PROV		VARCHAR(50),
		@VESTADO_PAGO_PROV		VARCHAR(50),
		@VFECHA_ULT_PAGO_PROV	DATETIME,
		@VPRECIO_CUOTA_PROV		VARCHAR(50),
		@VFECHA_PROX_VTO_PROV	DATETIME,
		@VSALDO_PEND_PROV		VARCHAR(50),
		@VDESTINO_PROV			VARCHAR(100),
		@VFECHA_DESDE_SERV_PROV	DATETIME,
		@VFECHA_HASTA_SERV_PROV	DATETIME,
		@VCANT					INT,
		@UNITDESC				VARCHAR(300),
		@USERDESC				VARCHAR(300),
		@VAGENDA_ID				VARCHAR(50),
		@VERROR					VARCHAR(50),
		@VCLIENTE				VARCHAR(300),
		@VIDCLIENTE				VARCHAR(100),
		@VNORMA					VARCHAR(300),
		@VFECHA					VARCHAR(50),
		@VDIASP					VARCHAR(50),
		@VTIPO_CONSULTOR		VARCHAR(50),
		@VCONSULTOR				VARCHAR(50),
		@VTIENE_CONS			VARCHAR(50),
		@VTIENE_OBS				VARCHAR(50),
		@VDESC_PAGO				VARCHAR(300)
 
BEGIN	
 
	SET @OCODE = '0'
	SET @OMENSAJE = ''
 
	SELECT	@VAGENDA_ID = ISNULL(AGENDA_ID,''),
			@VERROR = ISNULL(ERROR,'')
	FROM	XAGENDA
	WHERE	PAR_KEY = @IPKEYJOB
 
	SELECT	@VPROYECTO  = ID_PROYECTO,
			@VSERVICIO  = ID_SERVICIO
	FROM	LK_AGENDA
	WHERE	ID_AGENDA = @VAGENDA_ID
 
	SELECT	--@VPROYECTO		=	ISNULL(PROYECTO_ID,''),
			--@VPROYECTO_SERV =	ISNULL(PROYECTO_SERV_ID,''),
			@VID_SELEC		= ISNULL(HOJA_RUTA_ID,''),
			@VPROVEEDOR_ID	=	ISNULL(PROVEEDOR_ID,''),
			@VTIPO_PROV		=	ISNULL(TIPO_PROV,''),
			@VNRO_FACTURA_PROV = ISNULL(NRO_FACTURA_PROV,''),
			@VCANT_PERSONAS_PROV =	ISNULL(CANT_PERSONAS_PROV,''),
			@VDESCRIP_SERVICIO_PROV = ISNULL(DESCRIP_SERVICIO_PROV,''),
			@VFECHA_FACTURA_PROV = 	NULLIF(ISNULL(FECHA_FACTURA_PROV,''),''),
			@VPRECIO_FINAL_PROV	= ISNULL(PRECIO_FINAL_PROV,0),--ISNULL(replace(replace(PRECIO_CUOTA_PROV,',',''),'.',''),''),
			@VFORMA_PAGO_PROV	= ISNULL(FORMA_PAGO_PROV,''),
			@VCANT_CUOTAS_PROV	= ISNULL(CANT_CUOTAS_PROV,''),
			@VESTADO_PAGO_PROV	= ISNULL(ESTADO_PAGO_PROV,''),
			@VFECHA_ULT_PAGO_PROV = NULLIF(ISNULL(FECHA_ULT_PAGO_PROV,''),''),
			@VPRECIO_CUOTA_PROV	= ISNULL(PRECIO_CUOTA_PROV,0),--ISNULL(replace(replace(PRECIO_CUOTA_PROV,',',''),'.',''),''),
			@VFECHA_PROX_VTO_PROV = NULLIF(ISNULL(FECHA_PROX_VTO_PROV,''),''),
			@VSALDO_PEND_PROV	= ISNULL(SALDO_PEND_PROV,0),--ISNULL(replace(replace(SALDO_PEND_PROV,',',''),'.',''),''),
			@VDESTINO_PROV	= ISNULL(DESTINO_PROV,''),
			@VFECHA_DESDE_SERV_PROV = NULLIF(ISNULL(FECHA_DESDE_SERV_PROV,''),''),
			@VFECHA_HASTA_SERV_PROV	= NULLIF(ISNULL(FECHA_HASTA_SERV_PROV,''),''),
			@VTIPO_CONSULTOR = ISNULL(TIPO_CONSULTOR_PROV,''),
			@VCONSULTOR = ISNULL(CONSULTOR_PROV,''),
			@VDESC_PAGO = ISNULL(DESC_FORMA_PAGO_PROV,'')
	FROM	XAGENDA
	WHERE	PAR_KEY = @IPKEYJOB
 
	IF (@VTIPO_PROV = '') BEGIN
		SET @OCODE = '1'
			
		UPDATE	XAGENDA
		SET		ERROR = 'SI', DESC_ERROR = 'Debe completar el Campo Tipo Viatico'
		WHERE	PAR_KEY = @IPKEYJOB
		RETURN
	END
 
	IF (@VPROVEEDOR_ID = '' AND @VTIPO_PROV <> 'AUTO') BEGIN
		SET @OCODE = '1'
			
		UPDATE	XAGENDA
		SET		ERROR = 'SI', DESC_ERROR = 'Debe completar el Campo Proveedor'
		WHERE	PAR_KEY = @IPKEYJOB
		RETURN
	END
		
	IF (@VTIPO_CONSULTOR = '') BEGIN
		SET @OCODE = '1'
			
		UPDATE	XAGENDA
		SET		ERROR = 'SI', DESC_ERROR = 'Debe completar el Campo Corresponde'
		WHERE	PAR_KEY = @IPKEYJOB
		RETURN
			
	END
		
	--SELECT * FROM [dbo].[FN_GET_OBSERVADOR] (1)
	SELECT TOP 1 @VTIENE_CONS = CAT_DATA_CODE FROM [dbo].[FN_GET_CONSULTORES] (@VAGENDA_ID) --= 'SC'
 
	--SELECT TOP 1 CAT_DATA_CODE FROM [dbo].[FN_GET_CONSULTORES] (7)
 
	IF (@VTIPO_CONSULTOR = 'CONSULTOR' AND @VTIENE_CONS = 'SC') BEGIN
		SET @OCODE = '1'
			
		UPDATE	XAGENDA
		SET		ERROR = 'SI', DESC_ERROR = 'No Puede Seleccionar la opcion CONSULTOR si la Agenda NO tiene Consultor/es'
		WHERE	PAR_KEY = @IPKEYJOB
		RETURN
			
	END ELSE BEGIN
 
		IF (@VCONSULTOR = '') BEGIN
			
			SET @OCODE = '1'
 
			UPDATE	XAGENDA
			SET		ERROR = 'SI', DESC_ERROR = 'Debe completar el Campo Consultor/Observador'
			WHERE	PAR_KEY = @IPKEYJOB
			RETURN
		END
	END
 
	SELECT TOP 1 @VTIENE_OBS = CAT_DATA_CODE FROM [dbo].[FN_GET_OBSERVADOR] (@VAGENDA_ID) --= 'SC'
		
	IF (@VTIPO_CONSULTOR = 'OBSERVADOR' AND @VTIENE_OBS = 'SO') BEGIN
		SET @OCODE = '1'
			
		UPDATE	XAGENDA
		SET		ERROR = 'SI', DESC_ERROR = 'No Puede Seleccionar la opcion OBSERVADOR si la Agenda NO tiene Observador'
		WHERE	PAR_KEY = @IPKEYJOB
		RETURN
			
	END ELSE BEGIN
 
		IF (@VCONSULTOR = '') BEGIN
			
			SET @OCODE = '1'
			
			UPDATE	XAGENDA
			SET		ERROR = 'SI', DESC_ERROR = 'Debe completar el Campo Consultor/Observador'
			WHERE	PAR_KEY = @IPKEYJOB
			RETURN
		END			
	END
 
	IF (@VPROVEEDOR_ID = '9999' AND @VDESCRIP_SERVICIO_PROV = '') BEGIN
		SET @OCODE = '1'
			
		UPDATE	XAGENDA
		SET		ERROR = 'SI', DESC_ERROR = 'Debe completar el Descripcion Servicio si el Proveedor es "Otros"'
		WHERE	PAR_KEY = @IPKEYJOB
		RETURN
	END
 
	IF (@VID_SELEC = '') BEGIN 
 
		INSERT INTO LK_PROYECTO_VIATICOS
		(ID_PROYECTO, ID_TIPO_SERVICIO, ID_AGENDA, TIPO_CONSULTOR, ID_CONSULTOR, ID_PROVEEDOR, TIPO_PROVEEDOR, NRO_FC, CANT_PERSONAS,
			DESCRIP_SERVICIO, FECHA_FC, PRECIO_FINAL, FORMA_PAGO, CANT_CUOTAS, ESTADO_PAGO,
			FECHA_ULT_PAGO, PRECIO_CUOTA, PROX_VENCIMIENTO, SALDO_PEND, DESTINO, 
			FECHA_DESDE_SERV, FECHA_HASTA_SERV, DESC_FORMA_PAGO)
		VALUES
		(@VPROYECTO, @VSERVICIO, @VAGENDA_ID, @VTIPO_CONSULTOR, @VCONSULTOR, @VPROVEEDOR_ID, @VTIPO_PROV, @VNRO_FACTURA_PROV, @VCANT_PERSONAS_PROV,
			@VDESCRIP_SERVICIO_PROV, NULLIF(ISNULL(@VFECHA_FACTURA_PROV,''),''), @VPRECIO_FINAL_PROV, @VFORMA_PAGO_PROV, @VCANT_CUOTAS_PROV, @VESTADO_PAGO_PROV,
			NULLIF(ISNULL(@VFECHA_ULT_PAGO_PROV,''),''), @VPRECIO_CUOTA_PROV, NULLIF(ISNULL(@VFECHA_PROX_VTO_PROV,''),''), @VSALDO_PEND_PROV, @VDESTINO_PROV,
			NULLIF(ISNULL(@VFECHA_DESDE_SERV_PROV,''),''), NULLIF(ISNULL(@VFECHA_HASTA_SERV_PROV,''),''), @VDESC_PAGO)
	
	END ELSE BEGIN
		
		UPDATE	LK_PROYECTO_VIATICOS
		SET		TIPO_CONSULTOR = @VTIPO_CONSULTOR,
				ID_CONSULTOR = @VCONSULTOR,
				ID_PROVEEDOR = @VPROVEEDOR_ID,
				TIPO_PROVEEDOR = @VTIPO_PROV,
				NRO_FC = @VNRO_FACTURA_PROV,
				DESCRIP_SERVICIO = @VDESCRIP_SERVICIO_PROV,
				FECHA_FC = @VFECHA_FACTURA_PROV,
				PRECIO_FINAL = @VPRECIO_FINAL_PROV,
				FORMA_PAGO = @VFORMA_PAGO_PROV,
				CANT_CUOTAS = @VCANT_CUOTAS_PROV,
				FECHA_DESDE_SERV = @VFECHA_DESDE_SERV_PROV,
				FECHA_HASTA_SERV = @VFECHA_HASTA_SERV_PROV,
				DESC_FORMA_PAGO = @VDESC_PAGO
		WHERE	ID_PROYECTO_VIATICOS = @VID_SELEC	
	
	END
 
	IF (@OCODE = '0') BEGIN
		UPDATE	XAGENDA
		SET		ERROR = 'NO'
		WHERE	PAR_KEY = @IPKEYJOB
	END
END
