 
CREATE PROCEDURE [dbo].[EP_EDIT_EQUIPO]
(@IPKEYJOB	AS VARCHAR(100))
AS
 
BEGIN	
 
	DECLARE @ID_EQ_SEL VARCHAR(36),
	@TIPO_EQ VARCHAR(50),
	@NRO_EQUIPO INT,
	@MARCA_MODELO VARCHAR(300),
	@NRO_SERIE VARCHAR(300),
	@ESTADO VARCHAR(50)
	
	UPDATE TMT_CRON 
	SET [ACTION]='EDIT_EQUIPO',
	EQ_FECHA_DESDE=NULL,
	EQ_FECHA_HASTA=NULL
	WHERE PAR_KEY= @IPKEYJOB;
 
	SELECT @ID_EQ_SEL = EQ_SEL FROM TMT_CRON WHERE PAR_KEY = @IPKEYJOB;
	SELECT @TIPO_EQ= TipoEquipo, @NRO_EQUIPO=NroEquipo, @MARCA_MODELO=MarcaModelo, @NRO_SERIE=NroSerie, @ESTADO=Estado FROM EP_EQUIPOS WHERE Id = @ID_EQ_SEL;
 
	UPDATE TMT_CRON
	SET EQ_TIPO= @TIPO_EQ,
	EQ_NRO=@NRO_EQUIPO,
	EQ_MARCA_MOD=@MARCA_MODELO,
	EQ_NRO_SERIE=@NRO_SERIE,
	EQ_ESTADO=@ESTADO
	WHERE PAR_KEY = @IPKEYJOB;
	 
 
END
