CREATE PROCEDURE [dbo].[HOME_VAL_AGENDA_PASO5]
(@IPKEYJOB	AS VARCHAR(100),
 @FORM_ID	AS VARCHAR(100),
 @IAGENTE	AS VARCHAR(100),
 @OCODE		AS INT OUTPUT)
AS
 
DECLARE	@VCLIENTE			VARCHAR(100), 
		@VID_PROYECTO		VARCHAR(100),
		@VID_SERVICIO		VARCHAR(100),
		@VID_AGENDA			VARCHAR(100),
		@VID_AGENDA_NEW		VARCHAR(100),
		@VTIPO_SERVICIO		VARCHAR(100),
		@VFECHA_DESDE		DATETIME,
		@VFECHA_HASTA		DATETIME,
		@VCONSULTORES		VARCHAR(4000),
		@VCONSULTORES_AGENDA VARCHAR(4000),
		@VESTADO			VARCHAR(100),
		@VNORMA				VARCHAR(4000),
		@VOBSERVACIONES		VARCHAR(400),
		@VID_DOC			VARCHAR(50),
		@VID_PROYECTO_DOCUM	VARCHAR(50),
		@VDESC_DOC_DET		VARCHAR(400), 
		@VGRUPO_DOC_DET		VARCHAR(50),
		@VDIAS				INT,
		@lstDato			VARCHAR(100), 
		@lnuPosComa			INT ,
		@VALOR				VARCHAR(400),
		@VTORF				VARCHAR(50),
		@VDESCCONS			VARCHAR(400),
		@VEXISTE			INT,
		@VTOTAL_EJEC		INT,
		@VTOTAL_SERV		INT,
		@VOBS_CALIF			VARCHAR(400),
		@VOBS_LOGIS			VARCHAR(400),
		@VHORAS				INT,
		@VHORAS_TOTALES		INT,
		@VSELECCION			VARCHAR(4000),
		@VPREVIAS			VARCHAR(4000),
		@VNUEVAS			VARCHAR(4000),
		@RESULTADO			VARCHAR(400),
		@RESULTADO2			VARCHAR(400),
		@VALOR2				VARCHAR(400),
		@VALORNORMA			VARCHAR(400),
		@VAGREGO			VARCHAR(50),
		@VSELECCION2		VARCHAR(4000),
		@VESTA				VARCHAR(50),
		@VLIDER				VARCHAR(400),
		@VLIDERES			VARCHAR(400),
		@VNORMAS_SELEC		VARCHAR(4000),
		@VNORMAS_SELEC2		VARCHAR(4000),
		@VNORMAS_PREVIAS	VARCHAR(4000),
		@VNORMAS_NUEVAS		VARCHAR(4000),
		@VAGREGO_NORMA		VARCHAR(50),
		@VESTA_NORMA		VARCHAR(50),			
		@VNORMAS_SERV		VARCHAR(4000),
		@VID				VARCHAR(100),
		@VORDEN				NUMERIC(5,0),
		@VFECHA_FIN_SERV	VARCHAR(50),
		@VALERT_CALIF		VARCHAR(50),
		@VDIF				INT,
		@VREG				INT,
		@VFECHA				DATETIME,
		@V_DISPONIBLE		INT,
		@VHORAS_VISITA		NUMERIC(5),
		@VHORAS_DISP		INT,
		@VES_AGENDA_ACTUAL	INT,
		@VTIENE_AGENDA		INT,
		@ES_FERIADO			INT,
		@VINDICADOR_ANT		VARCHAR(50)
 
BEGIN	
	SET @VID_AGENDA = 0
	SET @OCODE = 0
	
	SELECT	@VCLIENTE = ISNULL(CLIENTE,''),
			@VID_PROYECTO =	ISNULL(PROYECTO_ID,''),
			@VID_SERVICIO = ISNULL(PROYECTO_SERV_ID,''),
			@VID_AGENDA	= ISNULL(AGENDA_ID,''),
			@VFECHA_DESDE = ISNULL(AGENDA_DESDE,''),
			@VFECHA_HASTA = ISNULL(AGENDA_HASTA,''),
			@VCONSULTORES = ISNULL(AGENDA_CONSULTORES,''),
			--@VHORAS = ISNULL(AGENDA_HORAS,0),
			@VESTADO = ISNULL(AGENDA_ESTADO,''),
			--@VNORMA = ISNULL(AGENDA_NORMA,''),
			@VOBSERVACIONES = ISNULL(AGENDA_OBSERVADOR,''),
			@VOBS_CALIF = ISNULL(AGENDA_OBSERV_CALIF,''),
			@VOBS_LOGIS = ISNULL(AGENDA_OBSERV_LOGIS,''),
			@VALERT_CALIF = ISNULL(ALERTA_CALIF,''),
			@VSELECCION = ISNULL(ACUMULA,''),
			@VPREVIAS = ISNULL(LIDER,''),
			@VNORMAS_SELEC = ISNULL(AGENDA_NORMAS,''),
			@VNORMAS_PREVIAS = ISNULL(AGENDA_NORMA,'')
	FROM	XAGENDA
	WHERE	PAR_KEY = @IPKEYJOB
 
	IF (@VID_SERVICIO <> '') BEGIN
		SELECT	@VTIPO_SERVICIO = ID_TIPO_SERVICIO
		FROM	LK_PROYECTO_SERVICIO
		WHERE	ID_PROYECTO_SERVICIO = @VID_SERVICIO
	END
 
	--RECORRO LOS CHECKS DE LIDER
	SET @VNUEVAS = @VPREVIAS
	SET @VSELECCION2 = [dbo].[FN_GET_SELECCION] (@VSELECCION)
	
	WHILE PATINDEX('%|%',@VNUEVAS)>0
	BEGIN
		SET @RESULTADO = PATINDEX('%|%',@VNUEVAS) --+ @N
		SET  @VALOR = SUBSTRING(@VNUEVAS,1, @RESULTADO-1)
		
		SET @VESTA = DBO.FN_GET_NORMA(@VSELECCION2,@VALOR)
 
		--aca agrego o elimino el dato en el string--
		IF (@VESTA = 'SI') BEGIN
			SET @VAGREGO = 'NO'
		END ELSE BEGIN
			SET @VAGREGO = 'SI'
		END
 
		IF (@VAGREGO = 'SI') BEGIN
			SET @VSELECCION = ISNULL(@VSELECCION,'') + @VALOR + '=true|'
		END
		
		SELECT @VNUEVAS = RIGHT(@VNUEVAS,LEN(@VNUEVAS)-PATINDEX('%|%',@VNUEVAS))
	END
 
	--GRABO SELECCION DE LIDERES--
	UPDATE	XAGENDA
	SET		ACUMULA = @VSELECCION
	WHERE	PAR_KEY = @IPKEYJOB
 
	SET @VALOR = NULL
	SET @VLIDERES = @VSELECCION
 
	IF (@VLIDERES <> '') BEGIN
		WHILE LEN(@VLIDERES) > 0
		BEGIN 
			SET @lnuPosComa = CHARINDEX('|', @VLIDERES) -- Busca el caracter a separador
			IF (@lnuPosComa = 0) BEGIN 
				SET @lstDato = @VLIDERES
				SET @VLIDERES = '' 
			END ELSE BEGIN
				SET @lstDato = SUBSTRING(@VLIDERES, 1, @lnuPosComa - 1)
				SET @VTORF = SUBSTRING(@lstDato,CHARINDEX('=', @lstDato)+1,LEN(@lstDato))
						
				IF (@VTORF = 'FALSE') BEGIN
					SET @VALOR = REPLACE('|'+ @VALOR,'|'+@VALOR+'|','|')
						IF (SUBSTRING(@VALOR,1,1) = '|') BEGIN
							SET @VALOR = SUBSTRING(@VALOR,2,LEN(@VALOR))
 
						END
				END ELSE BEGIN
 
					SET @VALOR = ISNULL(@VALOR,'') + SUBSTRING(@lstDato,1,CHARINDEX('=', @lstDato)-1) + '|'
 
					SET @lstDato = SUBSTRING(@lstDato,1,CHARINDEX('=', @lstDato)-1)
 
				END
				
				SET @VLIDERES = SUBSTRING(@VLIDERES, @lnuPosComa + 1, LEN(@VLIDERES))
			END
		END
 
		--GRABO LIDERES--
		UPDATE	XAGENDA
		SET		LIDER = case when CHARINDEX(@VALOR, @VCONSULTORES) > 0 THEN @VALOR ELSE '' END
		WHERE	PAR_KEY = @IPKEYJOB
 
	END
 
	--RECORRO LOS CHECKS DE NORMAS
	SET @VNORMAS_NUEVAS = @VNORMAS_PREVIAS
	SET @VNORMAS_SELEC2 = [dbo].[FN_GET_SELECCION] (@VNORMAS_SELEC)
	
	WHILE PATINDEX('%|%',@VNORMAS_NUEVAS)>0
	BEGIN
		SET @RESULTADO = PATINDEX('%|%',@VNORMAS_NUEVAS) --+ @N
		SET  @VALORNORMA = SUBSTRING(@VNORMAS_NUEVAS,1, @RESULTADO-1)
		
		SET @VESTA_NORMA = DBO.FN_GET_NORMA(@VNORMAS_SELEC2,@VALORNORMA)
 
		--aca agrego o elimino el dato en el string--
		IF (@VESTA_NORMA = 'SI') BEGIN
			SET @VAGREGO_NORMA = 'NO'
		END ELSE BEGIN
			SET @VAGREGO_NORMA = 'SI'
		END
 
		IF (@VAGREGO_NORMA = 'SI') BEGIN
			SET @VNORMAS_SELEC = ISNULL(@VNORMAS_SELEC,'') + @VALORNORMA + '=true|'
		END
		
		SELECT @VNORMAS_NUEVAS = RIGHT(@VNORMAS_NUEVAS,LEN(@VNORMAS_NUEVAS)-PATINDEX('%|%',@VNORMAS_NUEVAS))
	END
 
	--GRABO SELECCION DE NORMAS--
	UPDATE	XAGENDA
	SET		AGENDA_NORMAS = @VNORMAS_SELEC
	WHERE	PAR_KEY = @IPKEYJOB
 
	SET @VALORNORMA = NULL
	SET @VNORMAS_SERV = @VNORMAS_SELEC
 
	IF (@VNORMAS_SERV <> '') BEGIN
		WHILE LEN(@VNORMAS_SERV) > 0
		BEGIN 
			SET @lnuPosComa = CHARINDEX('|', @VNORMAS_SERV) -- Busca el caracter a separador
			IF (@lnuPosComa = 0) BEGIN 
				SET @lstDato = @VNORMAS_SERV
				SET @VNORMAS_SERV = '' 
			END ELSE BEGIN
				SET @lstDato = SUBSTRING(@VNORMAS_SERV, 1, @lnuPosComa - 1)
				SET @VTORF = SUBSTRING(@lstDato,CHARINDEX('=', @lstDato)+1,LEN(@lstDato))
						
				IF (@VTORF = 'FALSE') BEGIN
					SET @VALORNORMA = REPLACE('|'+ @VALORNORMA,'|'+@VALORNORMA+'|','|')
						IF (SUBSTRING(@VALORNORMA,1,1) = '|') BEGIN
							SET @VALORNORMA = SUBSTRING(@VALORNORMA,2,LEN(@VALORNORMA))
 
						END
				END ELSE BEGIN
 
					SET @VALORNORMA = ISNULL(@VALORNORMA,'') + SUBSTRING(@lstDato,1,CHARINDEX('=', @lstDato)-1) + '|'
 
					SET @lstDato = SUBSTRING(@lstDato,1,CHARINDEX('=', @lstDato)-1)
 
				END
				
				SET @VNORMAS_SERV = SUBSTRING(@VNORMAS_SERV, @lnuPosComa + 1, LEN(@VNORMAS_SERV))
			END
		END
 
		--GRABO NORMAS--
		UPDATE	XAGENDA
		SET		AGENDA_NORMA = @VALORNORMA
		WHERE	PAR_KEY = @IPKEYJOB
 
	END
	
	--RECUPERO CAMPO LIDER DE LA TMT
	SELECT	@VLIDER = ISNULL(LIDER,''),
			@VNORMA = ISNULL(AGENDA_NORMA,'')
	FROM	XAGENDA
	WHERE	PAR_KEY = @IPKEYJOB
 
	--CON CONSULTOR/ES--
	IF (@VCONSULTORES <> '') BEGIN
		
		--VALIDO QUE SELECCIONE LIDER--
		/*IF (ISNULL(@VLIDER,'') = '') BEGIN
			UPDATE	XAGENDA
			SET		DESC_ERROR = 'Debe Seleccionar al menos un Consultor como Lider'
			WHERE	PAR_KEY = @IPKEYJOB
 
			SET @OCODE = 1
			RETURN
 
		END ELSE BEGIN*/
 
		IF (ISNULL(@VLIDER,'') <> '') BEGIN
 
			IF ISNULL(SUBSTRING(@VLIDER,CHARINDEX('|', @VLIDER)+1,LEN(@VLIDER)),'') <> '' BEGIN
				
				UPDATE	XAGENDA
				SET		DESC_ERROR = 'Debe Seleccionar SOLO un Consultor como Lider'
				WHERE	PAR_KEY = @IPKEYJOB
 
				SET @OCODE = 1
				RETURN
			END
		END
 
		IF (@VALERT_CALIF = 'SI') BEGIN
			IF (@VOBS_CALIF = '') BEGIN
				UPDATE	XAGENDA
				SET		DESC_ERROR = 'Debe Completar el Campo Observacion Calificacion'
				WHERE	PAR_KEY = @IPKEYJOB
 
				SET @OCODE = 1
				RETURN
			END
		END
	END
 
	--VALIDO QUE SELECCIONE NORMA-- CON O SIN CONSULTORES
	IF (ISNULL(@VNORMA,'') = '') BEGIN
		UPDATE	XAGENDA
		SET		DESC_ERROR = 'Debe Seleccionar al menos una Norma'
		WHERE	PAR_KEY = @IPKEYJOB
 
		SET @OCODE = 1
		RETURN
	END
	/*FIN VALIDACIONES*/
 
	--MODIFICA VISITA--
	IF (@VID_AGENDA <> '') BEGIN
 
		--sin cosnultores--
		IF (@VCONSULTORES = '') BEGIN
			
			--ACTUALIZO LA VISITA EXISTENTE CON LOS NUEVOS DATOS Y ELIMINO LOS CONSULTORES SI TENIA PREVIAMENTE--
			UPDATE	XAGENDA 
			SET		ID_DELETE = @VID_AGENDA
			WHERE	PAR_KEY = @IPKEYJOB
 
			----ELIMINO LOS REGISTROS PREVIOS DE LAS AGENDA_CONSULTOR Y DEJO DISPONIBLE EL/LOS CONSULTOR/ES Y ACTUALIZO LOS TOTALES---
			EXEC HOME_ELIMINA_VISITA @IPKEYJOB, 'NO'
 
			UPDATE	LK_AGENDA
			SET		FECHA = @VFECHA_DESDE,
					FECHA_HASTA = @VFECHA_HASTA,
					ESTADO = @VESTADO,
					ID_CONSULTOR = @VCONSULTORES,
					OBSERVADOR = @VOBSERVACIONES,
					DIA = CONVERT(varchar, DATEPART(DD, @VFECHA_DESDE)),
					MES= CONVERT(varchar, DATEPART(MM, @VFECHA_DESDE)),
					ANO = CONVERT(varchar, DATEPART(YYYY, @VFECHA_DESDE)),
					DIAS =  DATEDIFF(DD,@VFECHA_DESDE,@VFECHA_HASTA) +1,
					LIDER = NULL,
					NORMA = @VNORMA,
					OBSERV_LOGISTICA = @VOBS_LOGIS,
					OBSERV_CALIF = @VOBS_CALIF,
					INDICADOR_HR = 'R'
			WHERE	ID_AGENDA = @VID_AGENDA
		
		END ELSE BEGIN
			
			--CAMBIA HORAS, CONSULTORES--
			--RECORRO DE FECHA DESDE A FECHA Y POR CADA CONSULTOR--
			--MODIFICO EL PRIMER REGISTRO EN LA TABLA LK_aGENDA_EMPLEADO PARA LA FECHA Y CONSULTOR-- PASA DE D "Disponible" a A "Agendado"
			--SI YA TIENE UNA AGENDA PREVIA PARA LA FECHA, SE INSERTA UN NUEVO REGISTRO POR FECHA/CONSULTOR DIRECTO COMO A "Agendado"
			BEGIN
				
				--GRABO EL ID_AGENDA QUE MODIFICA PARA BORRAR LA AGENDA--
				UPDATE	XAGENDA 
				SET		ID_DELETE = @VID_AGENDA
				WHERE	PAR_KEY = @IPKEYJOB
 
				--RECUPERO EL INDICADOR DE LA HOJA DE RUTA QUE TENIA LA AGENDA MODIFICADA--
				SELECT	@VINDICADOR_ANT = ISNULL(INDICADOR_HR,'R')
				FROM	LK_AGENDA
				WHERE	ID_AGENDA = @VID_AGENDA
 
				--GENERO UN AGENDA NUEVA IGUAL CON LA MODIFICACION--
				INSERT INTO LK_AGENDA
				(FECHA,ID_CLIENTE,ID_PROYECTO,ID_SERVICIO,ID_CONSULTOR,
					DIA,MES,ANO,
					ESTADO,NORMA,FECHA_ALTA,USUARIO_ALTA,OBSERVADOR,FECHA_HASTA,DIAS, 
					OBSERV_LOGISTICA, OBSERV_CALIF, LIDER, PROYECTO_SERV_ID, INDICADOR_HR)
				VALUES
				(@VFECHA_DESDE, @VCLIENTE, @VID_PROYECTO, @VTIPO_SERVICIO, @VCONSULTORES,
				CONVERT(varchar, DATEPART(DD, @VFECHA_DESDE)),CONVERT(varchar, DATEPART(MM, @VFECHA_DESDE)),CONVERT(varchar, DATEPART(YYYY, @VFECHA_DESDE)),
				@VESTADO, @VNORMA, GETDATE(), @IAGENTE, @VOBSERVACIONES, @VFECHA_HASTA, DATEDIFF(DD,@VFECHA_DESDE,@VFECHA_HASTA) +1,	
				@VOBS_LOGIS, @VOBS_CALIF, CASE WHEN ISNULL(@VLIDER,'') = '' THEN NULL ELSE @VLIDER END, @VID_SERVICIO,
				CASE WHEN @VCONSULTORES = '' THEN 'R' ELSE @VINDICADOR_ANT END)
 
				SELECT	@VID_AGENDA_NEW = IDENT_CURRENT ('LK_AGENDA')
 
				--ACTUALIZO LOS DOCUMENTOS. VIATICOS Y HONORARIOS IGUALES A LOS QUE TENIA PREVIAMENTE--
				UPDATE	LK_PROYECTO_DOCUM 
				SET		ID_AGENDA = @VID_AGENDA_NEW
				WHERE	ID_AGENDA = @VID_AGENDA
 
				UPDATE	LK_PROYECTO_VIATICOS 
				SET		ID_AGENDA = @VID_AGENDA_NEW
				WHERE	ID_AGENDA = @VID_AGENDA
 
				UPDATE	LK_PROYECTO_VIATICOS_DET 
				SET		ID_AGENDA = @VID_AGENDA_NEW
				WHERE	ID_AGENDA = @VID_AGENDA
 
				UPDATE	LK_PROYECTO_HONORARIOS 
				SET		ID_AGENDA = @VID_AGENDA_NEW
				WHERE	ID_AGENDA = @VID_AGENDA
				
				----ELIMINO LOS REGISTROS PREVIOS DE LAS AGENDA_CONSULTOR Y DEJO DISPONIBLE EL/LOS CONSULTOR/ES Y ACTUALIZO LOS TOTALES---
				EXEC HOME_ELIMINA_VISITA @IPKEYJOB, 'SI'
				
				UPDATE	XAGENDA
				SET		AGENDA_ID = @VID_AGENDA_NEW
				WHERE	PAR_KEY = @IPKEYJOB
 
				--RECORRO DE FECHA DESDE A FECHA Y POR CADA CONSULTOR--
				--MODIFICO EL PRIMER REGISTRO EN LA TABLA LK_aGENDA_EMPLEADO PARA LA FECHA Y CONSULTOR-- PASA DE D "Disponible" a A "Agendado"
				--SI YA TIENE UNA AGENDA PREVIA PARA LA FECHA, SE INSERTA UN NUEVO REGISTRO POR FECHA/CONSULTOR DIRECTO COMO A "Agendado"
				BEGIN
			
					WHILE LEN(@VCONSULTORES) > 0
					BEGIN 
						SET @lnuPosComa = CHARINDEX('|', @VCONSULTORES) -- Busca el caracter a separador
						IF (@lnuPosComa = 0) BEGIN 
							SET @lstDato = @VCONSULTORES
							SET @VCONSULTORES = '' 
						END ELSE BEGIN
 
							SET @lstDato = SUBSTRING(@VCONSULTORES, 1, @lnuPosComa - 1)
				
							SET @VREG = 0
							SET @ES_FERIADO = 0
							SET @VDIF = DATEDIFF(DD,@VFECHA_DESDE,@VFECHA_HASTA)
							SET @VFECHA = @VFECHA_DESDE
 
							WHILE @VREG <= @VDIF  
							BEGIN 
								
								--AGREGO CONTROL POR FECHA PARA VER SI ES FERIADO O NO-- GENERO UN REGISTRO
								SELECT	@ES_FERIADO = COUNT(1)
								FROM	Calendar
								WHERE	FECHA = @VFECHA
								AND		ISHOLIDAY = 1
 
								--RECUPERO LAS HORAS POR FECHA Y CONSULTOR DE LA TABLA XAGENDA_VISITAS
								SELECT	@VHORAS_VISITA = ISNULL(HORAS,0)
								FROM	XAGENDA_VISITAS
								WHERE	PAR_KEY = @IPKEYJOB
								AND		ID_CONSULTOR = @lstDato
								AND		FECHA = CONVERT(VARCHAR,@VFECHA,23)
 
								IF (@ES_FERIADO = 0) BEGIN
									--busco la disponibilidad horaria del consultor por fecha--
									SET @VHORAS_DISP = [dbo].[FN_GET_CONSULTOR_HORAS_DISP] (@lstDato, CONVERT(VARCHAR,@VFECHA,23))
								END ELSE BEGIN
									SET @VHORAS_DISP = @VHORAS_VISITA
								END								
 
								--SI NO CARGO HORAS PARA ESA FECHA/CONSULTOR-- NO HAGO NADA CON EL REGISTRO DE LA TABLA LK_AGENDA_EMPLEADO
								IF (ISNULL(@VHORAS_VISITA,0)) <> 0 BEGIN
							
									--ME FIJO SI TENGO UN REGISTRO EN ESTADO D "Disponible" o POT "Potencial" PARA LA FECHA/CONSULTOR-- 10/08/2025 se agrega opcion Potencial
									SELECT	@V_DISPONIBLE = COUNT(1)
									FROM	LK_AGENDA_EMPLEADO
									WHERE	ID_EMPLEADO = @lstDato
									AND		FECHA = CONVERT(VARCHAR,@VFECHA,23)
									AND		TIPO IN ('D','POT')
 
									IF (@V_DISPONIBLE = 1) BEGIN
										--ACTUALIZO EL REGISTRO DEL CONSULTOR DE LA TABLA LK_AGENDA_EMPLEADO
										UPDATE	LK_AGENDA_EMPLEADO
										SET		TIPO = 'A', 
												HOLIDAYTEXT = convert(varchar,@VID_AGENDA_NEW),
												HORAS = @VHORAS_VISITA,
												HORAS_DISP = CASE WHEN @ES_FERIADO = 0 THEN HORAS_DISP ELSE @VHORAS_VISITA END
										WHERE	ID_EMPLEADO = @lstDato
										AND		FECHA = CONVERT(VARCHAR,@VFECHA,23)
							
									END ELSE BEGIN
 
										--GENERO UN NUEVO REGISTRO EN LA TABLA LK_AGENDA_EMPLEADO PARA EL CONSULTOR/FECHA EN ESTADO A "Agendado" DIRECTAMENTE
										INSERT INTO LK_AGENDA_EMPLEADO
										(ID_EMPLEADO, FECHA, 
										 DIA, MES, ANO, 
										 ISHOLIDAY, HOLIDAYTEXT, TIPO, FECHA_ALTA, USUARIO_ALTA, HORAS, DESCRIPCION, HORAS_DISP)
										VALUES
										(@lstDato, CONVERT(VARCHAR,@VFECHA,23),
										 CONVERT(varchar, DATEPART(DD, @VFECHA)),CONVERT(varchar, DATEPART(MM, @VFECHA)),CONVERT(varchar, DATEPART(YYYY, @VFECHA)),
										 0, convert(varchar,@VID_AGENDA_NEW), 'A', GETDATE(), @IAGENTE, @VHORAS_VISITA, NULL, @VHORAS_DISP)
 
									END
								END
 
								SET @VFECHA = DATEADD(DD,1,@VFECHA)
								SET @VREG = @VREG + 1
							END
 
							SET @VCONSULTORES = SUBSTRING(@VCONSULTORES, @lnuPosComa + 1, LEN(@VCONSULTORES))
						END	
					END
				END
			END
		END
		--FIN MODIFICA VISITA--
 
	END ELSE BEGIN
 
		--sin cosnultores--
		IF (@VCONSULTORES = '') BEGIN
					
			INSERT INTO LK_AGENDA
			(FECHA,ID_CLIENTE,ID_PROYECTO,ID_SERVICIO,ID_CONSULTOR,
				DIA,MES,ANO,
				ESTADO,NORMA,FECHA_ALTA,USUARIO_ALTA,OBSERVADOR,FECHA_HASTA,DIAS, PROYECTO_SERV_ID, INDICADOR_HR)
			VALUES
			(@VFECHA_DESDE, @VCLIENTE, @VID_PROYECTO, @VTIPO_SERVICIO, @VCONSULTORES,
			 CONVERT(varchar, DATEPART(DD, @VFECHA_DESDE)),CONVERT(varchar, DATEPART(MM, @VFECHA_DESDE)),CONVERT(varchar, DATEPART(YYYY, @VFECHA_DESDE)),
			 @VESTADO, @VALORNORMA, GETDATE(), @IAGENTE, @VOBSERVACIONES, @VFECHA_HASTA, DATEDIFF(DD,@VFECHA_DESDE,@VFECHA_HASTA) +1, @VID_SERVICIO, 'R')
 
			SELECT	@VID_AGENDA = IDENT_CURRENT ('LK_AGENDA')
 
			/* no grabo LK_AGENDA_EMPLEADO porque NO tengo CONSULTOR */
			/* Grabo el ID de Documentacion que corresponda segun el Servicio
				5	RE-PP-038	Hoja de Ruta Auditoria
				6	RE-PP-039	Hoja de Ruta Capacitacion
				7	RE-PP-040	Hoja de Ruta Consultoria
 
				1	Consultoria --> GRABO ID 7
				2	Auditoria --> GRABO ID 5
				3	Capacitacion --> GRABO ID 6
			*/
			SELECT	@VID_DOC =	CASE WHEN @VTIPO_SERVICIO = '1' THEN '7'
									 WHEN @VTIPO_SERVICIO = '2' THEN '5'
									 WHEN @VTIPO_SERVICIO = '3' THEN '6'
								END 
 
			INSERT INTO LK_PROYECTO_DOCUM
			(ID_PROYECTO, ID_TIPO_SERVICIO, ID_DOCUMENTACION, 
				FECHA_DOCUM, NRO_DOCUM_INTERNO,
				PARTICIPANTES_DOCUM, TEMAS_DOCUM, ADJUNTO_DOCUM,
				CONSULTOR, VISITA_MES, CONSULTOR_ACOMP, OBSERVACIONES,FECHA_CIERRE,
				ID_AGENDA)
			VALUES
			(@VID_PROYECTO, @VTIPO_SERVICIO, @VID_DOC, 
				GETDATE(), 'Hoja de Ruta '+ CASE WHEN @VTIPO_SERVICIO = '1' THEN 'Consultoria' WHEN @VTIPO_SERVICIO = '2' THEN 'Auditoria' WHEN @VTIPO_SERVICIO = '3' THEN 'Capacitacion' END + ' - ' + CONVERT(varchar, DATEPART(DD, @VFECHA_DESDE))+'-'+CONVERT(varchar, DATEPART(MM, @VFECHA_DESDE))+'-'+CONVERT(varchar, DATEPART(YYYY, @VFECHA_DESDE)), 
				NULL, NULL, NULL,
				@VCONSULTORES, NULL, NULL, NULL, NULL,
				@VID_AGENDA)
 
			SELECT	@VID_PROYECTO_DOCUM = IDENT_CURRENT ('LK_PROYECTO_DOCUM')
 
				--RECUPERO TODOS LOS ITEMS QUE CORRESPONDEN AL DETALLE DE LA HOJA DE RUTA QUE CORRESPONDA SEGUN SERVICIO--
			DECLARE Items CURSOR FOR 
				SELECT	DESC_DOC_DET, GRUPO_DOC_DET, ISNULL(ORDEN,99) ORDEN
				FROM	LK_DOCUMENTACION_DET
				WHERE	ID_DOCUMENTACION = @VID_DOC
				AND		STATUS_DOC_DET = '1'
				ORDER BY CASE WHEN GRUPO_DOC_DET = 'LOGISTICO' THEN 1 
								WHEN GRUPO_DOC_DET = 'TECNICO' THEN 2
								WHEN GRUPO_DOC_DET = 'ADMINISTRACION' THEN 3 END, ISNULL(ORDEN,99)
 
			OPEN Items  
			FETCH NEXT FROM Items INTO @VDESC_DOC_DET, @VGRUPO_DOC_DET, @VORDEN  
 
			WHILE @@FETCH_STATUS = 0  
			BEGIN  
 
				INSERT INTO LK_PROYECTO_DOCUM_DET
				(ID_PROYECTO_DOCUM, DESC_DOC_DET, VALOR_DOC_DET, GRUPO_DOC_DET, ADJUNTO_DOC_DET, ORDEN)
				VALUES
				(@VID_PROYECTO_DOCUM, @VDESC_DOC_DET, NULL, @VGRUPO_DOC_DET, NULL, @VORDEN)
 
				FETCH NEXT FROM Items INTO @VDESC_DOC_DET, @VGRUPO_DOC_DET, @VORDEN
			END 
 
			CLOSE Items  
			DEALLOCATE Items
	
		END ELSE BEGIN
		
			INSERT INTO LK_AGENDA
			(FECHA,ID_CLIENTE,ID_PROYECTO,ID_SERVICIO,ID_CONSULTOR,
				DIA,MES,ANO,
				ESTADO,NORMA,FECHA_ALTA,USUARIO_ALTA,OBSERVADOR,FECHA_HASTA,DIAS, 
				OBSERV_LOGISTICA, OBSERV_CALIF, LIDER, PROYECTO_SERV_ID, INDICADOR_HR)
			VALUES
			(@VFECHA_DESDE, @VCLIENTE, @VID_PROYECTO, @VTIPO_SERVICIO, @VCONSULTORES,
				CONVERT(varchar, DATEPART(DD, @VFECHA_DESDE)),CONVERT(varchar, DATEPART(MM, @VFECHA_DESDE)),CONVERT(varchar, DATEPART(YYYY, @VFECHA_DESDE)),
				@VESTADO, @VNORMA, GETDATE(), @IAGENTE, @VOBSERVACIONES, @VFECHA_HASTA, DATEDIFF(DD,@VFECHA_DESDE,@VFECHA_HASTA) +1,	
				@VOBS_LOGIS, @VOBS_CALIF, CASE WHEN ISNULL(@VLIDER,'') = '' THEN NULL ELSE @VLIDER END, @VID_SERVICIO,
				CASE WHEN @VCONSULTORES = '' THEN 'R' ELSE 'N' END)
 
			SELECT	@VID_AGENDA = IDENT_CURRENT ('LK_AGENDA')
 
			SELECT	@VID_DOC =	CASE WHEN @VTIPO_SERVICIO = '1' THEN '7'
									 WHEN @VTIPO_SERVICIO = '2' THEN '5'
									 WHEN @VTIPO_SERVICIO = '3' THEN '6'
								END 
 
			INSERT INTO LK_PROYECTO_DOCUM
			(ID_PROYECTO, ID_TIPO_SERVICIO, ID_DOCUMENTACION, 
				FECHA_DOCUM, NRO_DOCUM_INTERNO,
				PARTICIPANTES_DOCUM, TEMAS_DOCUM, ADJUNTO_DOCUM,
				CONSULTOR, VISITA_MES, CONSULTOR_ACOMP, OBSERVACIONES,FECHA_CIERRE,
				ID_AGENDA)
			VALUES
			(@VID_PROYECTO, @VTIPO_SERVICIO, @VID_DOC, 
				GETDATE(), 'Hoja de Ruta '+ CASE WHEN @VTIPO_SERVICIO = '1' THEN 'Consultoria' WHEN @VTIPO_SERVICIO = '2' THEN 'Auditoria' WHEN @VTIPO_SERVICIO = '3' THEN 'Capacitacion' END + ' - ' + CONVERT(varchar, DATEPART(DD, @VFECHA_DESDE))+'-'+CONVERT(varchar, DATEPART(MM, @VFECHA_DESDE))+'-'+CONVERT(varchar, DATEPART(YYYY, @VFECHA_DESDE)), 
				NULL, NULL, NULL,
				@VCONSULTORES, NULL, NULL, NULL, NULL,
				@VID_AGENDA)
 
			SELECT	@VID_PROYECTO_DOCUM = IDENT_CURRENT ('LK_PROYECTO_DOCUM')
 
				--RECUPERO TODOS LOS ITEMS QUE CORRESPONDEN AL DETALLE DE LA HOJA DE RUTA QUE CORRESPONDA SEGUN SERVICIO--
			DECLARE Items CURSOR FOR 
				SELECT	DESC_DOC_DET, GRUPO_DOC_DET, ISNULL(ORDEN,99) ORDEN
				FROM	LK_DOCUMENTACION_DET
				WHERE	ID_DOCUMENTACION = @VID_DOC
				AND		STATUS_DOC_DET = '1'
				ORDER BY CASE WHEN GRUPO_DOC_DET = 'LOGISTICO' THEN 1 
								WHEN GRUPO_DOC_DET = 'TECNICO' THEN 2
								WHEN GRUPO_DOC_DET = 'ADMINISTRACION' THEN 3 END, ISNULL(ORDEN,99)
 
			OPEN Items  
			FETCH NEXT FROM Items INTO @VDESC_DOC_DET, @VGRUPO_DOC_DET, @VORDEN
 
			WHILE @@FETCH_STATUS = 0  
			BEGIN  
 
				INSERT INTO LK_PROYECTO_DOCUM_DET
				(ID_PROYECTO_DOCUM, DESC_DOC_DET, VALOR_DOC_DET, GRUPO_DOC_DET, ADJUNTO_DOC_DET, ORDEN)
				VALUES
				(@VID_PROYECTO_DOCUM, @VDESC_DOC_DET, NULL, @VGRUPO_DOC_DET, NULL, @VORDEN)
 
				FETCH NEXT FROM Items INTO @VDESC_DOC_DET, @VGRUPO_DOC_DET, @VORDEN
			END 
 
			CLOSE Items  
			DEALLOCATE Items
 
 
			--RECORRO DE FECHA DESDE A FECHA Y POR CADA CONSULTOR--
			--MODIFICO EL PRIMER REGISTRO EN LA TABLA LK_aGENDA_EMPLEADO PARA LA FECHA Y CONSULTOR-- PASA DE D "Disponible" a A "Agendado"
			--SI YA TIENE UNA AGENDA PREVIA PARA LA FECHA, SE INSERTA UN NUEVO REGISTRO POR FECHA/CONSULTOR DIRECTO COMO A "Agendado"
			BEGIN
			
				WHILE LEN(@VCONSULTORES) > 0
				BEGIN 
					SET @lnuPosComa = CHARINDEX('|', @VCONSULTORES) -- Busca el caracter a separador
					IF (@lnuPosComa = 0) BEGIN 
						SET @lstDato = @VCONSULTORES
						SET @VCONSULTORES = '' 
					END ELSE BEGIN
 
						SET @lstDato = SUBSTRING(@VCONSULTORES, 1, @lnuPosComa - 1)
				
						SET @VREG = 0
						SET @ES_FERIADO = 0
						SET @VDIF = DATEDIFF(DD,@VFECHA_DESDE,@VFECHA_HASTA)
						SET @VFECHA = @VFECHA_DESDE
 
						WHILE @VREG <= @VDIF  
						BEGIN 
							
							--AGREGO CONTROL POR FECHA PARA VER SI ES FERIADO O NO-- GENERO UN REGISTRO
							SELECT	@ES_FERIADO = COUNT(1)
							FROM	Calendar
							WHERE	FECHA = @VFECHA
							AND		ISHOLIDAY = 1
 
							--RECUPERO LAS HORAS POR FECHA Y CONSULTOR DE LA TABLA XAGENDA_VISITAS
							SELECT	@VHORAS_VISITA = ISNULL(HORAS,0)
							FROM	XAGENDA_VISITAS
							WHERE	PAR_KEY = @IPKEYJOB
							AND		ID_CONSULTOR = @lstDato
							AND		FECHA = CONVERT(VARCHAR,@VFECHA,23)
 
							IF (@ES_FERIADO = 0) BEGIN
								--busco la disponibilidad horaria del consultor por fecha--
								SET @VHORAS_DISP = [dbo].[FN_GET_CONSULTOR_HORAS_DISP] (@lstDato, CONVERT(VARCHAR,@VFECHA,23))
							END ELSE BEGIN
								SET @VHORAS_DISP = @VHORAS_VISITA
							END	
 
							--SI NO CARGO HORAS PARA ESA FECHA/CONSULTOR-- NO HAGO NADA CON EL REGISTRO DE LA TABLA LK_AGENDA_EMPLEADO
							IF (ISNULL(@VHORAS_VISITA,0)) <> 0 BEGIN
							
								--ME FIJO SI TENGO UN REGISTRO EN ESTADO D "Disponible" o POT "Potencial" PARA LA FECHA/CONSULTOR-- 10/08/2025 se agrega opcion Potencial
								SELECT	@V_DISPONIBLE = COUNT(1)
								FROM	LK_AGENDA_EMPLEADO
								WHERE	ID_EMPLEADO = @lstDato
								AND		FECHA = CONVERT(VARCHAR,@VFECHA,23)
								AND		TIPO IN ('D','POT')
 
								IF (@V_DISPONIBLE = 1) BEGIN
									--ACTUALIZO EL REGISTRO DEL CONSULTOR DE LA TABLA LK_AGENDA_EMPLEADO
									UPDATE	LK_AGENDA_EMPLEADO
									SET		TIPO = 'A', 
											HOLIDAYTEXT = convert(varchar,@VID_AGENDA),
											HORAS = @VHORAS_VISITA
									WHERE	ID_EMPLEADO = @lstDato
									AND		FECHA = CONVERT(VARCHAR,@VFECHA,23)
							
								END ELSE BEGIN
 
									--GENERO UN NUEVO REGISTRO EN LA TABLA LK_AGENDA_EMPLEADO PARA EL CONSULTOR/FECHA EN ESTADO A "Agendado" DIRECTAMENTE
									INSERT INTO LK_AGENDA_EMPLEADO
									(ID_EMPLEADO, FECHA, 
									 DIA, MES, ANO, 
									 ISHOLIDAY, HOLIDAYTEXT, TIPO, FECHA_ALTA, USUARIO_ALTA, HORAS, DESCRIPCION, HORAS_DISP)
									VALUES
									(@lstDato, CONVERT(VARCHAR,@VFECHA,23),
									 CONVERT(varchar, DATEPART(DD, @VFECHA)),CONVERT(varchar, DATEPART(MM, @VFECHA)),CONVERT(varchar, DATEPART(YYYY, @VFECHA)),
									 0, convert(varchar,@VID_AGENDA), 'A', GETDATE(), @IAGENTE, @VHORAS_VISITA, NULL, @VHORAS_DISP)
 
								END
							END
 
							SET @VFECHA = DATEADD(DD,1,@VFECHA)
							SET @VREG = @VREG + 1
						END
 
						SET @VCONSULTORES = SUBSTRING(@VCONSULTORES, @lnuPosComa + 1, LEN(@VCONSULTORES))
					END	
				END
			END
		END
		--FIN AGREGA VISITA
	END
 
	--si no elige consultor-- no se ACTUALIZAN LOS VALORES--
	IF (@VCONSULTORES <> '') BEGIN
 
		SELECT	@VHORAS_TOTALES = SUM(HORAS)
		FROM	LK_AGENDA_EMPLEADO
		WHERE	HOLIDAYTEXT = convert(varchar,@VID_AGENDA)
 
		--actualizo el total de horas del servicio y del proyecto
		UPDATE	LK_PROYECTO_SERVICIO
		SET		ESTADO_PROYECTO = 'ENCURSO',
				TOTAL_HORAS_EJECUTADAS = ISNULL(TOTAL_HORAS_EJECUTADAS,0) + @VHORAS_TOTALES
		WHERE	ID_PROYECTO_SERVICIO = @VID_SERVICIO
 
		UPDATE	LK_PROYECTO
		SET		ESTADO_PROYECTO_TOTAL = 'ENCURSO',
				TOTAL_HORAS_EJECUTADAS = ISNULL(TOTAL_HORAS_EJECUTADAS,0) + @VHORAS_TOTALES
		WHERE	ID_PROYECTO = @VID_PROYECTO
 
		--ACTUALIZO LOS PORCENTAJES
		UPDATE	LK_PROYECTO_SERVICIO
		SET		PORCENTAJE_AVANCE = CASE WHEN TOTAL_HORAS_PROYECTADAS = 0 THEN 0 ELSE TOTAL_HORAS_EJECUTADAS * 100 / TOTAL_HORAS_PROYECTADAS END
		WHERE	ID_PROYECTO_SERVICIO = @VID_SERVICIO
 
		UPDATE	LK_PROYECTO
		SET		PORCENTAJE_AVANCE_TOTAL = CASE WHEN TOTAL_HORAS_PROYECTADAS = 0 THEN 0 ELSE TOTAL_HORAS_EJECUTADAS * 100 / TOTAL_HORAS_PROYECTADAS END
		WHERE	ID_PROYECTO = @VID_PROYECTO
	END
 
END
