CREATE PROCEDURE [dbo].[HOME_CMB_COTIZACIONES]
(@IPKEYJOB	AS VARCHAR(100))
AS
 
DECLARE	@VCLIENTE	VARCHAR(50),
		@VPROYECTO	VARCHAR(50)
 
BEGIN	
 
	SELECT	@VCLIENTE = ISNULL(CLIENTE,''),
			@VPROYECTO = ISNULL(PROYECTO_ID,'')			
	FROM	XAGENDA
	WHERE	PAR_KEY = @IPKEYJOB
 
	SELECT	CO.ID_COTIZACION AS CAT_DATA_CODE, 
			CO.NRO_COTIZACION AS CAT_DATA_DESC, 
			'true'
	FROM    LK_COTIZACIONES CO 
			INNER JOIN LK_CLIENTES CLI ON CO.ID_CLIENTE = CLI.ID_CLIENTE
			INNER JOIN LK_PROYECTO P ON CO.ID_COTIZACION = P.ID_COTIZACION
	WHERE	CLI.ID_CLIENTE = @VCLIENTE
	AND		P.ID_PROYECTO = @VPROYECTO
	UNION ALL
	SELECT	DISTINCT TOP 100 
			CO.ID_COTIZACION AS CAT_DATA_CODE, 
			CO.NRO_COTIZACION AS CAT_DATA_DESC, 
			'true'
	FROM    LK_COTIZACIONES CO 
			INNER JOIN LK_CLIENTES CLI ON CO.ID_CLIENTE = CLI.ID_CLIENTE
			--INNER JOIN LK_PROYECTO P ON CO.ID_COTIZACION = P.ID_COTIZACION
	WHERE	CO.ESTADO_COTIZACION = 'CONFIRMADO'
	AND		CO.ID_COTIZACION NOT IN (SELECT ID_COTIZACION FROM LK_PROYECTO WHERE ID_COTIZACION <> 0)
	AND		CLI.ID_CLIENTE = @VCLIENTE
 
	
END
 
