CREATE   PROCEDURE [dbo].[SV_01_CMB_DATO_ASOCIADO]
(@IPKEYJOB	AS VARCHAR(100))
AS
 
DECLARE @VCLAVE_DOC	 VARCHAR(100),
		@VCODIGO_DOC VARCHAR(50)
 
BEGIN
 
	SELECT	@VCLAVE_DOC = CLAVE_DOC
	FROM	TMT_SV_01
	WHERE	PAR_KEY = @IPKEYJOB
 
	SELECT	@VCODIGO_DOC = CODE_DOCUMENTACION
	FROM	LK_DOCUMENTACION
	WHERE	ID_DOCUMENTACION = @VCLAVE_DOC
 
	--IF (@VCODIGO_DOC IN ('RE-PP-022-A','RE-PP-022-CA','RE-PP-022-CO')) BEGIN
		SELECT	'LK_CLIENTES' AS CAT_DATA_CODE,
				'Cliente' AS CAT_DATA_DESC,
				'TRUE'
		UNION ALL
		SELECT	'LK_PROYECTO' AS CAT_DATA_CODE,
				'Proyecto' AS CAT_DATA_DESC,
				'TRUE'
	--END
 
	--IF (@VCODIGO_DOC IN ('RE-PP-022-A-Anex','RE-PP-022-CA-Anex','RE-PP-022-CO-Anex')) BEGIN
	--	SELECT	'LK_CLIENTES' AS CAT_DATA_CODE,
	--			'Cliente' AS CAT_DATA_DESC,
	--			'TRUE'
	--	UNION ALL
	--	SELECT	'LK_PROYECTO' AS CAT_DATA_CODE,
	--			'Proyecto' AS CAT_DATA_DESC,
	--			'TRUE'
	--	UNION ALL
	--	SELECT	'LK_DOCUMENTACION_DET' AS CAT_DATA_CODE,
	--			'Minuta de Gestion '+CASE WHEN @VCODIGO_DOC = 'RE-PP-022-A-Anex' THEN 'Auditoria'
	--									  WHEN @VCODIGO_DOC = 'RE-PP-022-CA-Anex' THEN 'Capacitacion'
	--									  WHEN @VCODIGO_DOC = 'RE-PP-022-CO-Anex' THEN 'Consultoria' END  AS CAT_DATA_DESC,
	--			'TRUE'
	--END
 
END
 
