CREATE PROCEDURE [dbo].[HOME_VAL_AGENDA_PASO2]
(@IPKEYJOB	AS VARCHAR(100),
 @FORM_ID	AS VARCHAR(100),
 @OCODE		AS INT OUTPUT)
AS
 
DECLARE	@VCLIENTE			VARCHAR(100), 
		@VID_PROYECTO		VARCHAR(100),
		@VID_SERVICIO		VARCHAR(100),
		@VID_AGENDA			VARCHAR(100),
		@VFECHA_DESDE		DATETIME,
		@VFECHA_HASTA		DATETIME,
		@VFECHA_FIN_SERV	DATETIME
		
BEGIN
	
	SET @OCODE = 0
 
	SELECT	@VCLIENTE = ISNULL(CLIENTE,''),
			@VID_PROYECTO =	ISNULL(PROYECTO_ID,''),
			@VID_SERVICIO = ISNULL(PROYECTO_SERV_ID,''),
			@VID_AGENDA	= ISNULL(AGENDA_ID,''),
			@VFECHA_DESDE = ISNULL(AGENDA_DESDE,''),
			@VFECHA_HASTA = ISNULL(AGENDA_HASTA,'')
	FROM	XAGENDA
	WHERE	PAR_KEY = @IPKEYJOB
 
	SELECT	@VFECHA_FIN_SERV = ISNULL(FECHA_FIN_REAL,'')
	FROM	LK_PROYECTO_SERVICIO
	WHERE	ID_PROYECTO_SERVICIO = @VID_SERVICIO
 
	IF (@VID_AGENDA <> '') BEGIN
		IF (@VFECHA_DESDE = '') BEGIN
			UPDATE	XAGENDA
			SET		DESC_ERROR = 'Debe Completar el Campo Fecha Desde'
			WHERE	PAR_KEY = @IPKEYJOB
 
			SET @OCODE = 1
			RETURN
		END
	END
 
	IF (@VFECHA_HASTA = '') BEGIN
		UPDATE	XAGENDA
		SET		DESC_ERROR = 'Debe Completar el Campo Fecha Hasta'
		WHERE	PAR_KEY = @IPKEYJOB
 
		SET @OCODE = 1
		RETURN
	END
 
	IF (@VFECHA_HASTA < @VFECHA_DESDE) BEGIN
		UPDATE	XAGENDA
		SET		DESC_ERROR = 'El Campo Fecha Hasta Debe ser Mayor o Igual a la Fecha Desde'
		WHERE	PAR_KEY = @IPKEYJOB
 
		SET @OCODE = 1
		RETURN
	END
 
	IF (@VFECHA_HASTA > @VFECHA_FIN_SERV) BEGIN
		UPDATE	XAGENDA
		SET		DESC_ERROR = 'La Fecha Hasta NO debe ser Mayor a la Fecha Fin del Servicio ('+ISNULL(CONVERT(varchar, @VFECHA_FIN_SERV,103),'')+')'
		WHERE	PAR_KEY = @IPKEYJOB
 
		SET @OCODE = 1
		RETURN
	END
 
	IF (@OCODE = 0) BEGIN
		UPDATE	XAGENDA
		SET		DESC_ERROR = NULL
		WHERE	PAR_KEY = @IPKEYJOB
	END
 
END
