CREATE   PROCEDURE [dbo].[M_CONFIG_EDIT_SECTOR]
(@IPKEYJOB	AS VARCHAR(100),
 @IUSERID	AS VARCHAR(100))
AS
 
BEGIN	
 
	declare @ID_SECTOR_SEL VARCHAR(50),
	@NEW_ID VARCHAR(50),
	@NEW_NAME VARCHAR(100),
	@NEW_MAIL VARCHAR(100),
	@NEW_AREA VARCHAR(100)
 
	SELECT  @ID_SECTOR_SEL = ID_SECTOR_SEL 
	FROM M_CONFIG WHERE PAR_KEY = @IPKEYJOB;
	
	SELECT  @NEW_ID= convert(varchar,Id_Sector), 
			@NEW_AREA=convert(varchar,Id_Area), 
			@NEW_MAIL=Mail_Sector ,
			@NEW_NAME=Desc_Sector 
	FROM Sectores WHERE Id_Sector= @ID_SECTOR_SEL;
	
	UPDATE M_CONFIG
	SET NEW_ID= @NEW_ID,
	NEW_AREA=@NEW_AREA,
	NEW_EMAIL=@NEW_MAIL,
	NEW_NAME=@NEW_NAME
	WHERE PAR_KEY = @IPKEYJOB;
	 
END
