CREATE   PROCEDURE [dbo].[SV_01_CMB_EMPLEADO_CONSULTOR]
(@IPKEYJOB	AS VARCHAR(100))
AS
BEGIN	
 
	SELECT	ID_EMPLEADO AS CAT_DATA_CODE,
			APELLIDO_EMPLEADO + ', ' + NOMBRE_EMPLEADO AS CAT_DATA_DESC,
			'TRUE'
	FROM	LK_EMPLEADOS
	WHERE	PERFIL_EMP = 'CONSULTOR'
	AND STATUS_EMP='1'
	ORDER BY APELLIDO_EMPLEADO
 
 
END
 
