CREATE PROCEDURE PA_SYS_QTY_ATTACH
	(@PKEY_JOB AS VARCHAR(100),
	@QTY_ATTACH AS CHAR(10) = '0' OUTPUT,
	@QTY_NOTES AS CHAR(10) = '0' OUTPUT)
AS 
 
BEGIN 
	SELECT @QTY_ATTACH = COUNT(1)
	FROM PHYSICAL_ATTACHED_DOCUMENT WITH (NOLOCK)
	WHERE PAR_KEY = @PKEY_JOB
		AND IMAGE_LEN > 0
 
	UPDATE TMT_SEG_AP WITH (ROWLOCK)
	SET QTY_AUDIOS = @QTY_ATTACH
	WHERE PAR_KEY = @PKEY_JOB
 
	SELECT @QTY_NOTES = COUNT (1)	
	FROM PHYSICAL_NOTES WITH (NOLOCK)
	WHERE PAR_KEY = @PKEY_JOB
 
	SELECT '(' + CONVERT(VARCHAR, @QTY_ATTACH) + ')',
		 '(' + CONVERT(VARCHAR, @QTY_NOTES) + ')'
END
