CREATE PROCEDURE [dbo].[HOME_GRD_NORMAS_SERVICIO]
(@IPKEYJOB	AS VARCHAR(100))
AS
 
DECLARE @VID_PROYECTO	INT,
		@VID			INT,
		@VNORMAS_PROY	VARCHAR(400),
		@VID_AGENDA		VARCHAR(50),
		@VDESC			VARCHAR(4000),
		@VNORMAS		VARCHAR(400),
		@VCANT			INT,
		@lstDato		varchar(100), 
		@lnuPosComa		int ,
		@VALOR			VARCHAR(400),
		@VTORF			VARCHAR(50),
		@VQUERY			VARCHAR(MAX)
 
BEGIN	
 
	SELECT	@VID = ISNULL(PROYECTO_SERV_ID,''),
			@VID_PROYECTO = ISNULL(PROYECTO_ID,''),
			@VNORMAS = ISNULL(AGENDA_NORMA,'')
	FROM	XAGENDA
	WHERE	PAR_KEY = @IPKEYJOB
 
	SELECT	@VNORMAS_PROY = ISNULL(NORMAS,'')
	FROM	LK_PROYECTO 
	WHERE	ID_PROYECTO = @VID_PROYECTO
	
	SELECT	'<input type="checkbox" id="'+CONVERT(VARCHAR,ID_APTITUD)+'"'+CASE WHEN ([dbo].[FN_GET_NORMA](ISNULL(@VNORMAS,''),ID_APTITUD) = 'SI') THEN ' checked="true"' ELSE '' END +'	 onchange="toggleCheckbox2(this);">' + ' '+
			'<font size="1">'+DESC_APTITUD+'</font>'	AS '<font size="1">Normas</font>'
	FROM	LK_APTITUDES
	WHERE	[dbo].[FN_GET_NORMA](@VNORMAS_PROY,ID_APTITUD) = 'SI'
	--'+CASE WHEN ([dbo].[FN_GET_NORMA](@VNORMAS_PROY,ID_APTITUD) = 'SI') THEN ' checked="true"' ELSE '' END +'		
END
