CREATE PROCEDURE [dbo].[CMB_CALIFICACIONES]
(@IPKEYJOB VARCHAR(100))
AS
 
DECLARE @UNITDESC		VARCHAR(300),
		@USERDESC		VARCHAR(300),
		@CALIF_SEL		VARCHAR(50),
		@APTITUD_SEL	INT,
		@TIPO_SERVICIO_SEL INT
 
BEGIN	
	
	SELECT	--@CALIF_SEL=CALIF_SEL,
			@APTITUD_SEL=APTITUD_SEL,
			@TIPO_SERVICIO_SEL=TIPO_SERVICIO_SEL
	FROM	TMT_SV_05
	WHERE	PAR_KEY = @IPKEYJOB
 
	SELECT	DISTINCT CALIFICACION AS CAT_DATA_CODE,
			CALIFICACION AS CAT_DATA_DESC,
			'TRUE'
	FROM	LK_EMPLEADOS_APTITUD
	WHERE	ID_APTITUD = @APTITUD_SEL
	AND		ID_TIPO = CASE WHEN ISNULL(@TIPO_SERVICIO_SEL,'') = '' THEN ID_TIPO ELSE @TIPO_SERVICIO_SEL END
	ORDER BY CALIFICACION
 
END
