CREATE   PROCEDURE [dbo].[SV_01_CMB_EMPLEADO_TIPO]
(@IPKEYJOB	AS VARCHAR(100))
AS
 
DECLARE @VEMPLEADO VARCHAR(50),
		@VTIPO		VARCHAR(50)
 
BEGIN
 
	SELECT	@VEMPLEADO = EMPLEADO
	FROM	TMT_SV_01
	WHERE	PAR_KEY = @IPKEYJOB	
 
	SELECT	ID_TIPO AS CAT_DATA_CODE,
			TS.DESC_TIPO_SERVICIO AS CAT_DATA_DESC,
			'TRUE'
	FROM	LK_EMPLEADOS_TIPO T
			INNER JOIN LK_TIPO_SERVICIOS TS ON TS.ID_TIPO_SERVICIO = T.ID_TIPO
	WHERE	ID_EMPLEADO = @VEMPLEADO
 
END
 
