 
CREATE   PROCEDURE dbo.VCT_NOTIF_ACCION
(
    @IPKEYJOB VARCHAR(100),
    @IAGENTE  VARCHAR(100)
)
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @FLAG VARCHAR(10), @CMD VARCHAR(100), @SEL3 VARCHAR(100), @U VARCHAR(100) = LOWER(LTRIM(RTRIM(ISNULL(@IAGENTE,''))));
    SELECT TOP 1 @FLAG = ISNULL(FLAG01,''), @CMD = UPPER(LTRIM(RTRIM(ISNULL(TEXTO30,'')))), @SEL3 = UPPER(LTRIM(RTRIM(ISNULL(IDSELEC03,''))))
    FROM dbo.VCT_BUFFER WITH(NOLOCK) WHERE PAR_KEY = @IPKEYJOB;
    IF CHARINDEX(',', @CMD) > 0 SET @CMD = LEFT(@CMD, CHARINDEX(',', @CMD) - 1);
    IF CHARINDEX(',', @SEL3) > 0 SET @SEL3 = LEFT(@SEL3, CHARINDEX(',', @SEL3) - 1);
    IF ISNULL(@FLAG,'') <> '1' OR @CMD <> 'NOTIF_LEER' RETURN;
 
    UPDATE dbo.VCT_BUFFER SET FLAG01 = '0', TEXTO30 = NULL, IDSELEC03 = NULL WHERE PAR_KEY = @IPKEYJOB;
 
    IF @SEL3 = 'TODAS'
        UPDATE dbo.VCT_NOTIFICACIONES SET LEIDA = 1, FECHA_LEIDA = GETDATE() WHERE USUARIO = @U AND LEIDA = 0;
    ELSE IF @SEL3 <> '' AND PATINDEX('%[^0-9]%', @SEL3) = 0 AND LEN(@SEL3) <= 9
        UPDATE dbo.VCT_NOTIFICACIONES SET LEIDA = 1, FECHA_LEIDA = GETDATE() WHERE USUARIO = @U AND ID = CONVERT(INT, @SEL3) AND LEIDA = 0;
END
