CREATE PROCEDURE [dbo].[HOME_ADD_SERVICIO]
(@IPKEYJOB	AS VARCHAR(100),
 @IAGENTE	AS VARCHAR(100),
 @OCODE		AS VARCHAR(2) OUTPUT,
 @OMENSAJE	AS VARCHAR(400) OUTPUT)
AS
 
DECLARE	@VID				VARCHAR(50),
		@VPROYECTO			VARCHAR(50),
		@VTIPOSERVICIO		VARCHAR(50),
		@VFECHA_INI			DATETIME,
		@VFECHA_FIN			DATETIME,
		@VHORAS				INT,
		@VMONTO				VARCHAR(50),
		@VERROR				VARCHAR(50),
		@VFECHA_INI_PROY	DATETIME,
		@VFECHA_FIN_PROY	DATETIME,
		@VHORAS_PROY		INT,
		@VHORAS_SERVICIOS	INT,
		@VCIERRE			VARCHAR(50),
		@VCANT_MC			INT,
		@VCANT_PE			INT,
		@VCANT_AGENDAS		INT,
		@VCANT_TOTAL_AGENDAS INT,
		@VID_AGENDA			VARCHAR(50),
		@VCANT_MV			INT,
		@VCANT_TOTAL_MV		INT,
		@VCANT_PA			INT,
		@VCANT_IA			INT,
		@VCANT_TOTAL_IA		INT,
		@VCANT_IC			INT,
		@VCANT_TOTAL_IC		INT,
		@VCANT_ESTADO		INT,
		@VNOMBRE			VARCHAR(300),
		@VLUGAR				VARCHAR(300)
 
BEGIN	
	
	SET @OCODE = '0'
 
	SELECT	@VTIPOSERVICIO = ISNULL(TIPO_SERVICIO,''),
			@VPROYECTO = ISNULL(PROYECTO_ID,''),
			@VFECHA_INI = ISNULL(FECHA_INICIO_SERV,''),
			@VFECHA_FIN = ISNULL(FECHA_FIN_SERV,''),
			@VHORAS = ISNULL(HORAS_SERV,''),
			@VMONTO = REPLACE(ISNULL(MONTO_SERV,'0'),'.',''),
			@VNOMBRE = ISNULL(NOMBRE_SERV,''),
			@VLUGAR = ISNULL(LUGAR_SERV,'')
	FROM	XAGENDA
	WHERE	PAR_KEY = @IPKEYJOB
 
	SELECT	@VFECHA_INI_PROY = FECHA_INICIO_REAL,
			@VFECHA_FIN_PROY = FECHA_FIN_REAL,
			@VHORAS_PROY = TOTAL_HORAS_PROYECTADAS
	FROM	LK_PROYECTO
	WHERE	ID_PROYECTO = @VPROYECTO
 
	SELECT	@VHORAS_SERVICIOS = ISNULL(SUM(TOTAL_HORAS_PROYECTADAS),0)
	FROM	LK_PROYECTO_SERVICIO
	WHERE	ID_PROYECTO = @VPROYECTO
	--AND		ID_TIPO_SERVICIO = @VTIPOSERVICIO
	--AND		ID_PROYECTO_SERVICIO <> @VID
 
	IF (@VTIPOSERVICIO = '') BEGIN
		
		SET @OCODE = '1'
			
		UPDATE	XAGENDA
		SET		DESC_ERROR = 'Debe Completar el Campo Tipo Servicio'
		WHERE	PAR_KEY = @IPKEYJOB
		RETURN
	END
 
	IF (@VFECHA_INI = '') BEGIN
		
		SET @OCODE = '1'
			
		UPDATE	XAGENDA
		SET		DESC_ERROR = 'Debe Completar el Campo Fecha Inicio'
		WHERE	PAR_KEY = @IPKEYJOB
		RETURN
	END
 
	IF (@VFECHA_FIN = '') BEGIN
		
		SET @OCODE = '1'
			
		UPDATE	XAGENDA
		SET		DESC_ERROR = 'Debe Completar el Campo Fecha Fin'
		WHERE	PAR_KEY = @IPKEYJOB
		RETURN
	END
 
	IF (@VFECHA_INI > @VFECHA_FIN) BEGIN
		SET @OCODE = '1'
			
		UPDATE	XAGENDA
		SET		DESC_ERROR = 'La Fecha Inicio del Servicio NO Puede ser Mayor que la Fecha Fin'
		WHERE	PAR_KEY = @IPKEYJOB
		RETURN
	END
 
	--VALIDO QUE LA FECHA INICIO DEL SERVICIO NO SE MENOR A LA FECHA INICIO DEL PROYECTO NI MAYOR A LA FECHA FIN
	IF (@VFECHA_INI < @VFECHA_INI_PROY) BEGIN
		SET @OCODE = '1'
			
		UPDATE	XAGENDA
		SET		DESC_ERROR = 'La Fecha Inicio del Servicio NO Puede ser Menor que la Fecha Inicio del Proyecto. Fecha Inicio Proyecto: '+CONVERT(VARCHAR,@VFECHA_INI_PROY,103)
		WHERE	PAR_KEY = @IPKEYJOB
		RETURN
	END
 
	IF (@VFECHA_INI > @VFECHA_FIN_PROY) BEGIN
		SET @OCODE = '1'
			
		UPDATE	XAGENDA
		SET		DESC_ERROR = 'La Fecha Inicio del Servicio NO Puede ser Mayor que la Fecha Fin del Proyecto. Fecha Fin Proyecto: '+CONVERT(VARCHAR,@VFECHA_FIN_PROY,103)
		WHERE	PAR_KEY = @IPKEYJOB
		RETURN
	END
 
	--VALIDO QUE LA FECHA FIN DEL SERVICIO NO SE MENOR A LA FECHA INICIO DEL PROYECTO NI MAYOR A LA FECHA FIN
	IF (@VFECHA_FIN < @VFECHA_INI_PROY) BEGIN
		SET @OCODE = '1'
			
		UPDATE	XAGENDA
		SET		DESC_ERROR = 'La Fecha Fin del Servicio NO Puede ser Menor que la Fecha Inicio del Proyecto. Fecha Inicio Proyecto: '+CONVERT(VARCHAR,@VFECHA_INI_PROY,103)
		WHERE	PAR_KEY = @IPKEYJOB
		RETURN
	END
 
	IF (@VFECHA_FIN > @VFECHA_FIN_PROY) BEGIN
		SET @OCODE = '1'
 
		UPDATE	XAGENDA
		SET		DESC_ERROR = 'La Fecha Fin del Servicio NO Puede ser Mayor que la Fecha Fin del Proyecto. Fecha Fin Proyecto: '+CONVERT(VARCHAR,@VFECHA_FIN_PROY,103)
		WHERE	PAR_KEY = @IPKEYJOB
		RETURN
	END
 
	IF (@VNOMBRE = '') BEGIN
		
		SET @OCODE = '1'
			
		UPDATE	XAGENDA
		SET		DESC_ERROR = 'Debe Completar el Campo Nombre'
		WHERE	PAR_KEY = @IPKEYJOB
		RETURN
	END
	
	IF (@VHORAS = '') BEGIN
		SET @OCODE = '1'
			
		UPDATE	XAGENDA
		SET		DESC_ERROR = 'Debe Completar el Campo Horas Proyectadas'
		WHERE	PAR_KEY = @IPKEYJOB
		RETURN
	END
 
	--VALIDO QUE LA SUMA DE TODOS LOS SERVICIOS NO SUPERE EL TOTAL DE HORAS DEL PROYECTO
	IF (@VHORAS_PROY < (@VHORAS_SERVICIOS + @VHORAS)) BEGIN
		SET @OCODE = '1'
			
		UPDATE	XAGENDA
		SET		DESC_ERROR = 'La Cantidad de Horas Proyectadas de los Servicios NO Puede Superar el Total de Horas Proyectadas del Proyecto. Total de Horas: '+CONVERT(VARCHAR,@VHORAS_PROY)
		WHERE	PAR_KEY = @IPKEYJOB
		RETURN
	END
 
	IF CHARINDEX(@VMONTO,',') > 0  BEGIN
		SET @OCODE = '1'
 
		UPDATE	XAGENDA
		SET		DESC_ERROR = 'El Campo Monto Presupuestado NO puede tener Decimales'
		WHERE	PAR_KEY = @IPKEYJOB
		RETURN
	END
 
	INSERT INTO LK_PROYECTO_SERVICIO
	(ID_PROYECTO, ID_TIPO_SERVICIO, PORCENTAJE_AVANCE, FECHA_ALTA, USUARIO_ALTA,
		ESTADO_PROYECTO, FECHA_INICIO, FECHA_FIN, FECHA_INICIO_REAL, FECHA_FIN_REAL,
		TOTAL_HORAS_PROYECTADAS, TOTAL_HORAS_EJECUTADAS, MONTO_PRESUP, MONTO_COBRADO, ESTADO_COBRO, CIERRE, NOMBRE, LUGAR)
	VALUES
	(@VPROYECTO, @VTIPOSERVICIO, NULL, GETDATE(), @IAGENTE,
		'ENCURSO', @VFECHA_INI, @VFECHA_FIN, @VFECHA_INI, @VFECHA_FIN,
		@VHORAS, NULL, @VMONTO, NULL, NULL, 'NO', @VNOMBRE, @VLUGAR)
 
	UPDATE	XAGENDA
	SET		FECHA_INICIO_SERV = NULL,
			FECHA_FIN_SERV = NULL,
			HORAS_SERV = NULL,
			MONTO_SERV = NULL,
			--PROYECTO_SERV_ID = NULL,
			CIERRE_SERVICIO = NULL,
			NOMBRE_SERV = NULL,
			LUGAR_SERV = NULL,
			TIPO_SERVICIO = NULL
	WHERE	PAR_KEY = @IPKEYJOB
	
	IF (@OCODE = '0') BEGIN
		UPDATE	XAGENDA
		SET		DESC_ERROR = NULL
		WHERE	PAR_KEY = @IPKEYJOB
	END
END
