CREATE PROCEDURE [dbo].[HOME_VAL_AGENDA_PASO3]
(@IPKEYJOB	AS VARCHAR(100),
 @FORM_ID	AS VARCHAR(100),
 @OCODE		AS INT OUTPUT)
AS
 
DECLARE	@VCLIENTE			VARCHAR(100), 
		@VID_PROYECTO		VARCHAR(100),
		@VID_SERVICIO		VARCHAR(100),
		@VID_AGENDA			VARCHAR(100),
		@VTIPO_SERVICIO		VARCHAR(100),
		@VFECHA_DESDE		VARCHAR(100),
		@VFECHA_HASTA		DATETIME,
		@VSELECCION			VARCHAR(MAX),
		@VSELECCION2		VARCHAR(MAX),	
		@VCONSULTORES		VARCHAR(MAX),
		@VPREVIOS			VARCHAR(MAX),
		@VNUEVOS			VARCHAR(MAX),
		@VCONSULORES_AGENDA VARCHAR(MAX),
		@VALOR				VARCHAR(400),
		@VCALIF				VARCHAR(100),
		@VALERT_CALIF		VARCHAR(50),
		@VNORMAS_PROY		VARCHAR(400),
		@lstDato			VARCHAR(100), 
		@lnuPosComa			INT,
		@lstNorma			VARCHAR(100),
		@lnuPosComa2		INT,
		@VDIF				INT,
		@VREG				INT,
		@VCANT				INT,
		@VFECHA				DATETIME,
		@VDESCCONS			VARCHAR(4000),
		@RESULTADO			INT,
		@VEXISTE			VARCHAR(50),
		@VAGREGO			VARCHAR(50),
		@VTORF				VARCHAR(50),
		@VUSUARIO			VARCHAR(100),
		@VHORAS_DISP		INT,
		@VHORAS_CONSULTOR	INT,
		@VHORAS_AGENDA		INT,
		@ES_FERIADO			INT,
		@VALIDO				INT
		
BEGIN
	
	SET @OCODE = 0
 
	SELECT	@VCLIENTE = ISNULL(CLIENTE,''),
			@VID_PROYECTO =	ISNULL(PROYECTO_ID,''),
			@VID_SERVICIO = ISNULL(PROYECTO_SERV_ID,''),
			@VID_AGENDA	= ISNULL(AGENDA_ID,''),
			@VFECHA_DESDE = ISNULL(AGENDA_DESDE,''),
			@VFECHA_HASTA = ISNULL(AGENDA_HASTA,''),
			@VSELECCION = ISNULL(BUFFER,''),
			@VPREVIOS = ISNULL(AGENDA_CONSULTORES,''),
			@VUSUARIO = ISNULL(TS_USER_ID,'')
	FROM	XAGENDA
	WHERE	PAR_KEY = @IPKEYJOB
 
	IF (@VID_PROYECTO <> '') BEGIN
		SELECT	@VNORMAS_PROY = NORMAS
		FROM	LK_PROYECTO
		WHERE	ID_PROYECTO = @VID_PROYECTO
	END
 
	IF (@VID_SERVICIO <> '') BEGIN
		SELECT	@VTIPO_SERVICIO = ID_TIPO_SERVICIO
		FROM	LK_PROYECTO_SERVICIO
		WHERE	ID_PROYECTO_SERVICIO = @VID_SERVICIO
	END
 
	--RECUPERO LOS CONSULTORES CARGADOS DE LA AGENDA-- FORMATO 8|9|
	IF (@VID_AGENDA <> '') BEGIN
		SELECT	@VCONSULORES_AGENDA = ID_CONSULTOR
		FROM	LK_AGENDA
		WHERE	ID_AGENDA = @VID_AGENDA
	END
	
	DELETE FROM XAGENDA_VISITAS WHERE PAR_KEY = @IPKEYJOB
 
	--SI SELECCIONA CONSULTOR/ES VALIDO QUE ESTEN DISPONIBLE EN EL TANGO DE FECHAS DESDE Y HASTA-- 
	--IF (@VSELECCION <> '') BEGIN
		
	SET @VNUEVOS = @VPREVIOS
	SET @VSELECCION2 = [dbo].[FN_GET_SELECCION] (@VSELECCION)
	
	WHILE PATINDEX('%|%',@VNUEVOS)>0
	BEGIN
		SET @RESULTADO = PATINDEX('%|%',@VNUEVOS) --+ @N
		SET  @VALOR = SUBSTRING(@VNUEVOS,1, @RESULTADO-1)
		
		SET @VEXISTE = DBO.FN_GET_NORMA(@VSELECCION2,@VALOR)
 
		--aca agrego o elimino el dato en el string--
		IF (@VEXISTE = 'SI') BEGIN
			SET @VAGREGO = 'NO'
		END ELSE BEGIN
			SET @VAGREGO = 'SI'
		END
 
		IF (@VAGREGO = 'SI') BEGIN
			SET @VSELECCION = ISNULL(@VSELECCION,'') + @VALOR + '=true|'
		END
		
		SELECT @VNUEVOS = RIGHT(@VNUEVOS,LEN(@VNUEVOS)-PATINDEX('%|%',@VNUEVOS))
	END
	
	SET @VALOR = NULL
	SET @VCONSULTORES = @VSELECCION
	SET @VALERT_CALIF = 'NO'
	SET @VCALIF = NULL
	SET @ES_FERIADO = 0
 
	IF (@VCONSULTORES <> '') BEGIN
		WHILE LEN(@VCONSULTORES) > 0
		BEGIN 
			SET @lnuPosComa = CHARINDEX('|', @VCONSULTORES) -- Busca el caracter a separador
			IF (@lnuPosComa = 0) BEGIN 
				SET @lstDato = @VCONSULTORES
				SET @VCONSULTORES = '' 
			END ELSE BEGIN
				SET @lstDato = SUBSTRING(@VCONSULTORES, 1, @lnuPosComa - 1)
				SET @VTORF = SUBSTRING(@lstDato,CHARINDEX('=', @lstDato)+1,LEN(@lstDato))
						
				IF (@VTORF = 'FALSE') BEGIN
					SET @VALOR = REPLACE('|'+ @VALOR,'|'+@VALOR+'|','|')
						IF (SUBSTRING(@VALOR,1,1) = '|') BEGIN
							SET @VALOR = SUBSTRING(@VALOR,2,LEN(@VALOR))
 
						END
				END ELSE BEGIN
 
					SET @VALOR = ISNULL(@VALOR,'') + SUBSTRING(@lstDato,1,CHARINDEX('=', @lstDato)-1) + '|'
 
					SET @lstDato = SUBSTRING(@lstDato,1,CHARINDEX('=', @lstDato)-1)
 
				END
				
				SET @VCONSULTORES = SUBSTRING(@VCONSULTORES, @lnuPosComa + 1, LEN(@VCONSULTORES))
			END
		END
 
		UPDATE	XAGENDA
		SET		AGENDA_CONSULTORES = @VALOR
		WHERE	PAR_KEY = @IPKEYJOB
 
		SET @VREG = 0
		SET @VDIF = DATEDIFF(DD,@VFECHA_DESDE,@VFECHA_HASTA)
		SET @VFECHA = @VFECHA_DESDE
		SET @VALIDO = 0 --NUEVA VARIABLE PARA VALIDAR TODO EL RANGO DE FECHA DESDE Y HASTA SI ESTA DISPONIBLE O TIENE HORAS EL CONSULTOR
 
		WHILE @VREG <= @VDIF  
		BEGIN
			
			SET @VCANT = 0	
			SET @VCONSULTORES = @VALOR
				
			--RECORRO EL/LOS CONSULTORES
			WHILE LEN(@VCONSULTORES) > 0
			BEGIN 
				SET @lnuPosComa = CHARINDEX('|', @VCONSULTORES) -- Busca el caracter a separador
				IF (@lnuPosComa = 0) BEGIN 
					SET @lstDato = @VCONSULTORES
					SET @VCONSULTORES = '' 
				END ELSE BEGIN
 
					SET @lstDato = SUBSTRING(@VCONSULTORES, 1, @lnuPosComa - 1)
 
					SELECT	@VDESCCONS = APELLIDO_EMPLEADO + ', ' + NOMBRE_EMPLEADO
					FROM	LK_EMPLEADOS
					WHERE	CONVERT(VARCHAR,ID_EMPLEADO) = @lstDato
 
					SET @VHORAS_AGENDA = 0
 
					--CHEQUEO SI EL CONSULTOR ESTA PREVIAMENTE CARGADO EN LA AGENDA-- solo cuando modifica
					IF (@VID_AGENDA <> '') BEGIN
						
						IF (CHARINDEX('|'+@lstDato+'|','|'+@VCONSULORES_AGENDA) > 0) BEGIN
							SET @VCANT = 1
 
							--RECUPERO LAS HORAS DEL CONSULTOR POR FECHA PARA ESA AGENDA--
							SELECT	@VHORAS_AGENDA = ISNULL(HORAS,0)
							FROM	LK_AGENDA_EMPLEADO
							WHERE	ID_EMPLEADO = @lstDato
							AND		FECHA = CONVERT(VARCHAR,@VFECHA,23)
							AND		HOLIDAYTEXT = @VID_AGENDA
 
						END ELSE BEGIN
							--VALIDO QUE EL RANGO DE FECHAS DESDE Y HASTA ESTES DISPONIBLES--10/08/2025 se agrega opcion Potencial
							SELECT	@VCANT = COUNT(1)
							FROM	LK_AGENDA_EMPLEADO
							WHERE	Fecha = @VFECHA
							AND		CONVERT(VARCHAR,ID_EMPLEADO) = @lstDato
							AND		TIPO IN ('D','POT')
						END
					END
 
					--AGREGO CONTROL POR FECHA PARA VER SI ES FERIADO O NO-- GENERO UN REGISTRO
					SELECT	@ES_FERIADO = COUNT(1)
					FROM	Calendar
					WHERE	FECHA = @VFECHA
					AND		ISHOLIDAY = 1
 
					SET @VHORAS_DISP = [dbo].[FN_GET_CONSULTOR_HORAS_DISP] (@lstDato, @VFECHA)
					SET @VHORAS_CONSULTOR = [dbo].[FN_GET_CONSULTOR_HORAS] (@lstDato, @VFECHA)
 
					IF ((@VCANT > 0) OR (@VHORAS_DISP - @VHORAS_CONSULTOR > 0) OR (@ES_FERIADO > 0)) BEGIN
						
						--SI INGRESA AL MENOS UNA VEZ COMO OK, YA VALIDO EL RANGO DE FECHA DESDE Y HASTA
						SET @VALIDO = 1
 
						--agrego el registro en la tabla temporal XAGENDA_VISITAS--
						INSERT INTO XAGENDA_VISITAS
						(ID_CONSULTOR, FECHA, HORAS, PKEY, PAR_KEY, TS_BEGIN, TS_END, TS_USER_ID)
						VALUES
						(@lstDato, CONVERT(VARCHAR,@VFECHA,23), @VHORAS_AGENDA, NEWID(), @IPKEYJOB, GETDATE(), GETDATE(), @VUSUARIO)
 
						SET @VCONSULTORES = SUBSTRING(@VCONSULTORES, @lnuPosComa + 1, LEN(@VCONSULTORES))
 
					END ELSE BEGIN
						
						IF (@VALIDO = 0) BEGIN
							UPDATE	XAGENDA
							SET		DESC_ERROR = 'La Fecha '+CONVERT(VARCHAR,@VFECHA,103)+' NO se encuentra Disponible para el Consultor '+  ISNULL(@VDESCCONS,'')
							WHERE	PAR_KEY = @IPKEYJOB
 
							SET @OCODE = 1
							RETURN
						
						END ELSE BEGIN 
 
							--agrego el registro en la tabla temporal XAGENDA_VISITAS--
							INSERT INTO XAGENDA_VISITAS
							(ID_CONSULTOR, FECHA, HORAS, PKEY, PAR_KEY, TS_BEGIN, TS_END, TS_USER_ID)
							VALUES
							(@lstDato, CONVERT(VARCHAR,@VFECHA,23), @VHORAS_AGENDA, NEWID(), @IPKEYJOB, GETDATE(), GETDATE(), @VUSUARIO)
 
							SET @VCONSULTORES = SUBSTRING(@VCONSULTORES, @lnuPosComa + 1, LEN(@VCONSULTORES))
						END
					END
				END	
			END
			
			SET @VFECHA = DATEADD(DD,1,@VFECHA)
			SET @VREG = @VREG + 1
		END
 
		SET @VCONSULTORES = @VALOR
 
		WHILE LEN(@VNORMAS_PROY) > 0 
		BEGIN 
				
			SET @lnuPosComa2 = CHARINDEX('|', @VNORMAS_PROY) -- Busca el caracter a separador
			IF (@lnuPosComa2 = 0) BEGIN 
				SET @lstNorma = @VNORMAS_PROY
				SET @VNORMAS_PROY = '' 
			END ELSE BEGIN
				SET @lstNorma = SUBSTRING(@VNORMAS_PROY, 1, @lnuPosComa2 - 1)
 
				WHILE LEN(@VCONSULTORES) > 0
				BEGIN 
					SET @lnuPosComa = CHARINDEX('|', @VCONSULTORES) -- Busca el caracter a separador
					IF (@lnuPosComa = 0) BEGIN 
						SET @lstDato = @VCONSULTORES
						SET @VALOR = '' 
					END ELSE BEGIN
						SET @lstDato = SUBSTRING(@VCONSULTORES, 1, @lnuPosComa - 1)
 
						SELECT @VCALIF = dbo.FN_GET_CALIFICACION(@lstDato,@lstNorma,@VTIPO_SERVICIO)
 
						IF (@VCALIF = 'NA' AND @VALERT_CALIF = 'NO') BEGIN
							SET @VALERT_CALIF = 'SI'
						END
 
					END
				
					SET @VCONSULTORES = SUBSTRING(@VCONSULTORES, @lnuPosComa + 1, LEN(@VCONSULTORES))
				END
			END
				
			SET @VNORMAS_PROY = SUBSTRING(@VNORMAS_PROY, @lnuPosComa2 + 1, LEN(@VNORMAS_PROY))
			SET @VCONSULTORES = @VALOR
 
		END
	
		UPDATE	XAGENDA
		SET		ALERTA_CALIF = @VALERT_CALIF
		WHERE	PAR_KEY = @IPKEYJOB
	END
 
	IF (@OCODE = 0) BEGIN
		UPDATE	XAGENDA
		SET		DESC_ERROR = NULL,
				ALMACENA_HORAS = NULL
		WHERE	PAR_KEY = @IPKEYJOB
	END
END
