CREATE PROCEDURE [dbo].[HOME_ADD_COTIZACION]
(@IPKEYJOB	AS VARCHAR(100),
 @IAGENTE	AS VARCHAR(100),
 @OCODE		AS VARCHAR(2) OUTPUT,
 @OMENSAJE	AS VARCHAR(400) OUTPUT)
AS
 
DECLARE @VNRO		VARCHAR(50),
		@VCLIENTE	VARCHAR(100),
		@VFECHA		DATETIME,
		@VESTADO	VARCHAR(50),
		@VERROR		VARCHAR(50),
		@VCANT		INT,
		@VADJUNTO	VARCHAR(100),
		@VID_SELEC	VARCHAR(100),
		@VADJUNTO_ANT VARCHAR(100)
 
BEGIN	
 
	SET @OCODE = '0'
	SET @OMENSAJE = ''
 
	SELECT	@VNRO = ISNULL(NRO_COTIZA,''),
			@VCLIENTE	= ISNULL(CLIENTE,''),
			@VFECHA = ISNULL(FECHA_COTIZA,''),
			@VESTADO = ISNULL(ESTADO_COTIZA,''),
			@VERROR = ISNULL(ERROR,''),
			@VID_SELEC = ISNULL(CLAVE_COTIZA,'')
	FROM	XAGENDA
	WHERE	PAR_KEY = @IPKEYJOB
 
	SELECT	@VADJUNTO = ISNULL(PKEY,'')
	FROM	PHYSICAL_ATTACHED_DOCUMENT
	WHERE	PAR_KEY = @IPKEYJOB
 
	IF (@VID_SELEC <> '') BEGIN
 
		SELECT	@VADJUNTO_ANT = ISNULL(ID_ADJUNTO,'')
		FROM	LK_COTIZACIONES
		WHERE	ID_COTIZACION = @VID_SELEC
 
	END
 
	IF (@VCLIENTE = '') BEGIN
		SET @OCODE = '1'
									
		UPDATE	XAGENDA
		SET		ERROR = 'SI',
				DESC_ERROR = 'Debe Completar el Campo Cliente'
		WHERE	PAR_KEY = @IPKEYJOB
		RETURN
	END
 
	IF (@VNRO = '') BEGIN
		SET @OCODE = '1'			
									
		UPDATE	XAGENDA
		SET		ERROR = 'SI',
				DESC_ERROR = 'Debe Completar el Campo Nro Cotizacion'
		WHERE	PAR_KEY = @IPKEYJOB
		RETURN
	END
 
	IF (@VFECHA = '') BEGIN
		SET @OCODE = '1'
									
		UPDATE	XAGENDA
		SET		ERROR = 'SI',
				DESC_ERROR = 'Debe Completar el Campo Fecha'
		WHERE	PAR_KEY = @IPKEYJOB
		RETURN
	END
 
	IF (@VESTADO = '') BEGIN
		SET @OCODE = '1'
									
		UPDATE	XAGENDA
		SET		ERROR = 'SI',
				DESC_ERROR ='Debe Completar el Campo Estado'
		WHERE	PAR_KEY = @IPKEYJOB
		RETURN
	END
 
	IF (@VID_SELEC = '') BEGIN
	
		--VALIDO QUE NO EXISTA EL MISMO CODIGO EN LK_DOCUMENTACION--
		SELECT	@VCANT = COUNT(1)
		FROM	LK_COTIZACIONES
		WHERE	CONVERT(VARCHAR,NRO_COTIZACION) = LTRIM(RTRIM(@VNRO))
		AND		CONVERT(VARCHAR,ID_CLIENTE) = @VCLIENTE
	
	END ELSE BEGIN
 
		--VALIDO QUE NO EXISTA EL MISMO CODIGO EN LK_DOCUMENTACION--
		SELECT	@VCANT = COUNT(1)
		FROM	LK_COTIZACIONES
		WHERE	CONVERT(VARCHAR,NRO_COTIZACION) = LTRIM(RTRIM(@VNRO))
		AND		CONVERT(VARCHAR,ID_CLIENTE) = @VCLIENTE
		AND		CONVERT(VARCHAR,ID_COTIZACION) <> @VID_SELEC
	END
 
	IF (@VCANT > 0) BEGIN
		
		SET @OCODE = '1'
									
		UPDATE	XAGENDA
		SET		ERROR = 'SI',
				DESC_ERROR ='Ya Existe una Cotizacion con el mismo Nro para ese Cliente'
		WHERE	PAR_KEY = @IPKEYJOB
		RETURN
 
	END ELSE BEGIN
		
		IF (@VID_SELEC = '') BEGIN
 
			INSERT INTO LK_COTIZACIONES
			(NRO_COTIZACION, ID_CLIENTE, FECHA_COTIZACION, ESTADO_COTIZACION, FECHA_ALTA, USUARIO_ALTA, ID_ADJUNTO)
			VALUES
			(@VNRO, @VCLIENTE, @VFECHA, @VESTADO, GETDATE(), @IAGENTE, @VADJUNTO)
 
			IF (@VADJUNTO <> '') BEGIN
				UPDATE	PHYSICAL_ATTACHED_DOCUMENT
				SET		PAR_KEY = @VCLIENTE
				WHERE	PKEY = @VADJUNTO
			END
 
		END ELSE BEGIN
			
			UPDATE LK_COTIZACIONES
			SET NRO_COTIZACION = @VNRO, 
				FECHA_COTIZACION = @VFECHA, 
				ESTADO_COTIZACION = @VESTADO, 
				ID_ADJUNTO = ISNULL(@VADJUNTO,@VADJUNTO_ANT)
			WHERE	ID_COTIZACION = @VID_SELEC
 
			IF (@VADJUNTO <> '') BEGIN
				UPDATE	PHYSICAL_ATTACHED_DOCUMENT
				SET		PAR_KEY = @VCLIENTE
				WHERE	PKEY = @VADJUNTO
 
				DELETE	PHYSICAL_ATTACHED_DOCUMENT
				WHERE	PKEY = @VADJUNTO_ANT
			END
 
		END
	END
 
	IF (@OCODE = '0') BEGIN
		UPDATE	XAGENDA
		SET		ERROR = 'NO'
		WHERE	PAR_KEY = @IPKEYJOB
	END
END
 
