CREATE   PROCEDURE [dbo].[SV_01_GRD_DOCUMENTACION_SEL]
(@IPKEYJOB	AS VARCHAR(100))
AS
 
DECLARE @VCLAVE_DOC	VARCHAR(100)
 
BEGIN	
 
	SELECT	@VCLAVE_DOC = CLAVE_DOC
	FROM	TMT_SV_01
	WHERE	PAR_KEY = @IPKEYJOB
 
	SELECT	CODE_DOCUMENTACION AS "<B>CODIGO</B>",
			DESC_DOCUMENTACION AS "<B>DOCUMENTACION</B>",
			CONVERT(VARCHAR,FECHA_ALTA,103) AS "<B>FECHA ALTA</B>",
			DETALLE_DOCUMENTACION AS "<B>DETALLE</B>"
	FROM	LK_DOCUMENTACION
	WHERE	ID_DOCUMENTACION = @VCLAVE_DOC
 
END
 
