 
 
CREATE PROCEDURE [dbo].[SP_PARENT_JOB] 
@jobKey as varchar (80)
 
AS
SELECT PJOB.PKEY, E.ENTITY_TABLE_REL
FROM PHYSICAL_CALL_TRANSACTIONS T, 
ATTENDED_CUSTOMER ATT, 
PHYSICAL_JOB PJOB, 
PHYSICAL_CALL_CONV_STEPS STP, 
PHYSICAL_CALL PCALL,
JOB_TYPE JOB,
ENTITY_BROWSER E
WHERE T.PAR_KEY=STP.PKEY
AND STP.PAR_KEY = PCALL.PKEY
AND PCALL.PAR_KEY = ATT.PKEY
AND ATT.PKEY_JOB = PJOB.PKEY
AND T.TRANS_CODE LIKE 'Generar_Mail%'
AND T.TRANS_RESULT_CODE = 'OK'
AND T.TRANS_PRM_OUT = 'OK|' + @jobKey
AND PJOB.JOB_TYPE_CODE = JOB.JOB_TYPE_CODE
AND JOB.ENTITY_CODE = E.ENTITY_CODE
 
 
