CREATE PROCEDURE [dbo].[SV_05_GRD_INDICE_TOTALES]
(@IPKEYJOB	AS VARCHAR(100),
 @FORM_ID	AS VARCHAR(100))
AS
 
DECLARE	@VFECHA_DESDE		DATETIME,
		@VFECHA_HASTA		DATETIME,
		@VTOTAL_CONS		INT,
		@VTOTAL_HS_CONS		INT,
		@VTOTAL_AUDI		INT,
		@VTOTAL_HS_AUDI		INT,
		@VTOTAL_CAPA		INT,
		@VTOTAL_HS_CAPA		INT,
		@VID_AGENDA			INT,
		@VHORAS_CONS		INT,
		@VHORAS_AUDI		INT,
		@VHORAS_CAPA		INT
 
BEGIN	
 
	SELECT	@VFECHA_DESDE = ISNULL(FECHA_DESDE,''),
			@VFECHA_HASTA = ISNULL(FECHA_HASTA,'')
	FROM	TMT_SV_05
	WHERE	PAR_KEY = @IPKEYJOB
 
	IF (@VFECHA_DESDE = '') BEGIN
		SELECT	'Debe Seleccionar Fecha Desde'  AS '<font size="2">Mensaje</font>'
	END
 
	IF (@VFECHA_HASTA = '') BEGIN
		SELECT	'Debe Seleccionar Fecha Hasta'  AS '<font size="2">Mensaje</font>'
	END
 
	IF (@VFECHA_DESDE > @VFECHA_HASTA) BEGIN
		SELECT	'La Fecha Desde debe ser Igual o Mayor a la Fecha Hasta'  AS '<font size="2">Mensaje</font>'
 
	END ELSE BEGIN
		
		SELECT	@VTOTAL_CONS = COUNT(*)
		FROM	LK_PROYECTO P
				INNER JOIN LK_PROYECTO_SERVICIO PS ON P.ID_PROYECTO = PS.ID_PROYECTO
		WHERE	PS.FECHA_INICIO_REAL >= @VFECHA_DESDE
		AND		PS.FECHA_INICIO_REAL <= @VFECHA_HASTA
		AND		PS.ID_TIPO_SERVICIO = '1'
 
		SET @VTOTAL_HS_CONS = 0
 
		DECLARE Consultorias CURSOR FOR 
			SELECT	ID_AGENDA
			FROM	LK_AGENDA A
					INNER JOIN LK_PROYECTO P ON A.ID_PROYECTO = P.ID_PROYECTO AND A.ID_CLIENTE = P.ID_CLIENTE
					INNER JOIN LK_PROYECTO_SERVICIO PS ON P.ID_PROYECTO = PS.ID_PROYECTO
			WHERE	PS.FECHA_INICIO_REAL >= @VFECHA_DESDE
			AND		PS.FECHA_INICIO_REAL <= @VFECHA_HASTA
			AND		A.ID_SERVICIO = 1
			
		OPEN Consultorias  
		FETCH NEXT FROM Consultorias INTO @VID_AGENDA
 
		WHILE @@FETCH_STATUS = 0  
		BEGIN  
		
			SELECT	@VHORAS_CONS = SUM(HORAS)
			FROM	LK_AGENDA_EMPLEADO
			WHERE	HOLIDAYTEXT = CONVERT(VARCHAR,@VID_AGENDA)
 
			SET @VTOTAL_HS_CONS = @VTOTAL_HS_CONS + @VHORAS_CONS
 
			FETCH NEXT FROM Consultorias INTO @VID_AGENDA
		END 
 
		CLOSE Consultorias  
		DEALLOCATE Consultorias
 
		SELECT	@VTOTAL_AUDI = COUNT(*)
		FROM	LK_PROYECTO P
				INNER JOIN LK_PROYECTO_SERVICIO PS ON P.ID_PROYECTO = PS.ID_PROYECTO
		WHERE	PS.FECHA_INICIO_REAL >= @VFECHA_DESDE
		AND		PS.FECHA_INICIO_REAL <= @VFECHA_HASTA
		AND		PS.ID_TIPO_SERVICIO = '2'
 
		SET @VTOTAL_HS_AUDI = 0
 
		DECLARE Auditorias CURSOR FOR 
			SELECT	ID_AGENDA
			FROM	LK_AGENDA A
					INNER JOIN LK_PROYECTO P ON A.ID_PROYECTO = P.ID_PROYECTO AND A.ID_CLIENTE = P.ID_CLIENTE
					INNER JOIN LK_PROYECTO_SERVICIO PS ON P.ID_PROYECTO = PS.ID_PROYECTO
			WHERE	PS.FECHA_INICIO_REAL >= @VFECHA_DESDE
			AND		PS.FECHA_INICIO_REAL <= @VFECHA_HASTA
			AND		A.ID_SERVICIO = 2
			
		OPEN Auditorias  
		FETCH NEXT FROM Auditorias INTO @VID_AGENDA
 
		WHILE @@FETCH_STATUS = 0  
		BEGIN  
		
			SELECT	@VHORAS_AUDI = SUM(HORAS)
			FROM	LK_AGENDA_EMPLEADO
			WHERE	HOLIDAYTEXT = CONVERT(VARCHAR,@VID_AGENDA)
 
			SET @VTOTAL_HS_AUDI = @VTOTAL_HS_AUDI + @VHORAS_AUDI
 
			FETCH NEXT FROM Auditorias INTO @VID_AGENDA
		END 
 
		CLOSE Auditorias  
		DEALLOCATE Auditorias
 
		SELECT	@VTOTAL_CAPA = COUNT(*)
		FROM	LK_PROYECTO P
				INNER JOIN LK_PROYECTO_SERVICIO PS ON P.ID_PROYECTO = PS.ID_PROYECTO
		WHERE	PS.FECHA_INICIO_REAL >= @VFECHA_DESDE
		AND		PS.FECHA_INICIO_REAL <= @VFECHA_HASTA
		AND		PS.ID_TIPO_SERVICIO = '3'
 
		SET @VTOTAL_HS_CAPA = 0
 
		DECLARE Capacitaciones CURSOR FOR 
			SELECT	ID_AGENDA
			FROM	LK_AGENDA A
					INNER JOIN LK_PROYECTO P ON A.ID_PROYECTO = P.ID_PROYECTO AND A.ID_CLIENTE = P.ID_CLIENTE
					INNER JOIN LK_PROYECTO_SERVICIO PS ON P.ID_PROYECTO = PS.ID_PROYECTO
			WHERE	PS.FECHA_INICIO_REAL >= @VFECHA_DESDE
			AND		PS.FECHA_INICIO_REAL <= @VFECHA_HASTA
			AND		A.ID_SERVICIO = 3
			
		OPEN Capacitaciones  
		FETCH NEXT FROM Capacitaciones INTO @VID_AGENDA
 
		WHILE @@FETCH_STATUS = 0  
		BEGIN  
		
			SELECT	@VHORAS_CAPA = SUM(HORAS)
			FROM	LK_AGENDA_EMPLEADO
			WHERE	HOLIDAYTEXT = CONVERT(VARCHAR,@VID_AGENDA)
 
			SET @VTOTAL_HS_CAPA = @VTOTAL_HS_CAPA + @VHORAS_CAPA
 
			FETCH NEXT FROM Capacitaciones INTO @VID_AGENDA
		END 
 
		CLOSE Capacitaciones  
		DEALLOCATE Capacitaciones
 
 
		SELECT	@VTOTAL_CONS	AS '<font size="2">Total Consultorias</font>',
				@VTOTAL_HS_CONS	AS '<font size="2">Total Horas Consultor</font>',
				@VTOTAL_AUDI	AS '<font size="2">Total Auditorias</font>',
				@VTOTAL_HS_AUDI	AS '<font size="2">Total Horas Auditor</font>',
				@VTOTAL_CAPA	AS '<font size="2">Total Capacitaciones</font>',
				@VTOTAL_HS_CAPA	AS '<font size="2">Total Horas Instructor</font>'
 
	END
END
