 
CREATE PROCEDURE [dbo].[PA_SYS_PRM_ACTUALIZAR] (@PS_RET_MESSAGE VARCHAR(440) = NULL OUTPUT) AS
 
-- =========================================================================================================================
-- AUTOR: TITO - ENGAGE SOFTWARE COMPANY
-- FECHA DE CREACIÓN: 18/12/2006
-- EDITOR: TITO - ENGAGE SOFTWARE COMPANY
-- FECHA DE MODIFICACIÓN: 22/10/2008
-- TABLAS LEÍDAS: TODAS LAS TABLAS QUE TIENEN EL SUFIJO '_KEY' EN PRM.PRM_COD
-- TABLAS MODIFICADAS: PRM
-- DESCRIPCIÓN: PROCEDIMIENTO QUE ACTUALIZA PRM.PRM_VAL CON EL VALOR + 1 DE LA ÚLTIMA CLAVE DE CADA TABLA.
-- CONSIDERACIONES:
-- 1. SI SE HAN BORRADO TABLAS FÍSICAS DE LA BASE DE DATOS DE ENGAGE QUE TIENEN CONTADORES DE PKEY EN PRM.PRM_COD CON EL
-- SUFIJO '_KEY', ESTE PROCEDIMIENTO BORRARÁ LOS REGISTROS CONTADORES CORRESPONDIENTES, PUDIENDO EJECUTARSE SIN ERRORES.
-- 2. SI HAY PROCEDIMIENTOS DE INTERFACES O DE OTRO TIPO QUE UTILICEN CONTADORES DE PKEY QUE NO TENGAN LAS TABLAS FÍSICAS
-- CORRESPONDIENTES, DEBERÁN MODIFICARSE DICHOS PROCEDIMIENTOS O SE DEBERÁ MODIFICAR ESTE PROCEDIMIENTO PARA EVITAR QUE
-- BORRE LOS CONTADORES DE PRM QUE AQUELLOS UTILIZAN.
-- 3. SE RECOMIENDA QUE TODO PROCEDIMIENTO ALMACENADO DE INTERFACES CON ENGAGE GENERE REGISTROS CON CLAVES PKEY
-- CORRECTAMENTE, HACIENDO USO DEL PROCEDIMIENTO PA_SYS_OBTIENE_PKEY, PARA MANTENER ACTUALIZADA LA TABLA PRM.
-- 4. A PARTIR DE LA VERSIÓN 4.9.9.11 DE ENGAGE DEL 2007-07-31, LAS CLAVES PKEY DE CUSTOMER SE GENERAN TODAS EN FORMATO
-- ESTÁNDAR.
-- 5. A PARTIR DE LA VERSIÓN 4.9.9.11.20070814 DE ENGAGE DEL 2007-08-14, ALGUNAS DE LAS CLAVES PKEY DE PHYSICAL_JOB SE
-- GENERAN EN FORMATO ESTÁNDAR.
-- 6. ESTE PROCEDIMIENTO NO FUE PENSADO COMO PARTE DEL METADATA MANAGER NI REEMPLAZA PARTE DE SU FUNCIONAMIENTO.
-- 7. EL USO DE ESTE PROCEDIMIENTO IMPLICA LA COMPRENSIÓN Y ACEPTACIÓN DE LOS PUNTOS ANTERIORES.
-- 8. EL PARÁMETRO DE SALIDA @PS_RET_MESSAGE DEVUELVE EL MENSAJE DE ERROR. NULL SI NO HUBO.
-- =========================================================================================================================
 
SET NOCOUNT ON;
SET XACT_ABORT ON;
 
-- DECLARACIÓN E INICIALIZACIÓN DE VARIABLES DE ERROR Y AUXILIARES.
DECLARE @LNERRORNUM AS INTEGER,
	@LNSEVERITY AS SMALLINT,
	@LNFILAS_AFEC AS INTEGER,
	@LDINICIO_OPE AS DATETIME,
	@LNDURACION AS INTEGER,
	@LSOPERA AS VARCHAR(30),
	@LSPROC AS VARCHAR(30),
	@LSTABLA AS VARCHAR(30),
	@LSERRORLOG AS VARCHAR(440),
	@LSERRORDESC AS VARCHAR(440),
	@LSSQL_CMD AS VARCHAR(4000)
;
SELECT 	@LNERRORNUM = 0,
	@LNSEVERITY = 16,
	@LNFILAS_AFEC = 0,
	@LDINICIO_OPE = GETDATE(),
	@LNDURACION = 0,
	@LSOPERA = 'EXECUTE',
	@LSPROC = OBJECT_NAME(@@PROCID),
	@LSTABLA = 'NINGUNA',
	@LSERRORLOG = @@SERVERNAME + '.' + DB_NAME() + '.' + USER_NAME() + '.' + OBJECT_NAME(@@PROCID) + ' - ',
	@LSERRORDESC = NULL,
	@LSSQL_CMD = NULL
;
 
-- DECLARA LAS VARIABLES.
DECLARE	@LSPRM_SEL_MAX VARCHAR(2000),
	@LSPRM_UPDATE1 VARCHAR(2000),
	@LSPRM_UPDATE2 VARCHAR(2000),
	@LS_SQL_CMD VARCHAR(4000),
	@LN_COUNT1 NUMERIC(10, 0),
	@LN_COUNT2 NUMERIC(10, 0);
 
-- ASIGNA VALORES PREDETERMINADOS A LAS VARIABLES.
SELECT	@LSPRM_SEL_MAX = ' ',
	@LSPRM_UPDATE1 = ' ',
	@LSPRM_UPDATE2 = ' ',
	@LS_SQL_CMD = ' ',
	@LN_COUNT1 = 0,
	@LN_COUNT2 = 0;
 
-- DECLARO LA TRANSACCIÓN.
BEGIN TRANSACTION
 
-- ELIMINA LOS CONTADORES DE PKEY PARA TABLAS QUE NO EXISTEN EN LA BASE DE DATOS DE ENGAGE.
DELETE
FROM	PRM
WHERE	(RIGHT(PRM.PRM_COD, 4) = '_KEY')
	AND NOT EXISTS (
	SELECT	1
	FROM	EVI_TABLES T2
	WHERE	T2.TABLE_NAME = REPLACE(PRM.PRM_COD, '_KEY', '')
	);
SELECT @LSOPERA = 'DELETE', @LSTABLA = 'PRM', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
IF (@LNERRORNUM <> 0) GOTO FALLO;
 
-- CARGA UN CURSOR.
DECLARE LOCURPARAM CURSOR LOCAL FAST_FORWARD TYPE_WARNING FOR
	SELECT	'(SELECT ISNULL(MAX(CONVERT(NUMERIC(10, 0), SUBSTRING(PKEY, 1, 10))) + 1, 1) FROM ' + SUBSTRING(PRM_COD, 1, LEN(PRM_COD) - 4) + ' WHERE (ISNUMERIC(SUBSTRING(PKEY, 1, 10)) = 1 AND LEN(PKEY) = ' + CONVERT(VARCHAR, 11 + LEN(ISNULL(PRM_NUM, '95'))) + '))' AS PRM_SEL_MAX,
		'UPDATE PRM SET PRM_VAL = ' AS PRM_UPDATE1,
		' WHERE (PRM_COD = ' + CHAR(39) + PRM_COD + CHAR(39) + ');' AS PRM_UPDATE2
	FROM	PRM
	WHERE	PRM_COD IN (
		SELECT	(TABLE_NAME + '_KEY') AS KEY_NAME
		FROM	EVI_TABLE_COLUMNS
		WHERE	(COLUMN_NAME = 'PKEY')
			AND (DATA_TYPE_NAME = 'VARCHAR')
			AND TABLE_NAME NOT IN ('PHYSICAL_JOB', 'ATTENDED_CUSTOMER', 'PHYSICAL_CALL', 'PHYSICAL_CALL_CONV_STEPS') -- SUS TABLAS HISTÓRICAS PUEDEN TENER PKEY MAYORES.
		);
 
OPEN LOCURPARAM;
FETCH NEXT FROM LOCURPARAM INTO @LSPRM_SEL_MAX, @LSPRM_UPDATE1, @LSPRM_UPDATE2;
 
-- CICLO DE NIVEL DE TRÁMITE.
WHILE (@@FETCH_STATUS = 0)
BEGIN
	SET @LS_SQL_CMD = @LSPRM_UPDATE1 + @LSPRM_SEL_MAX + @LSPRM_UPDATE2;
	PRINT @LS_SQL_CMD;
	EXECUTE (@LS_SQL_CMD);
	SELECT @LSOPERA = 'UPDATE', @LSTABLA = 'PRM', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
 
	FETCH NEXT FROM LOCURPARAM INTO @LSPRM_SEL_MAX, @LSPRM_UPDATE1, @LSPRM_UPDATE2;
END;
 
CLOSE LOCURPARAM;
DEALLOCATE LOCURPARAM;
 
-- ACTUALIZACIÓN DEL CONTADOR DE PRM PARA LAS TABLAS DE WORKFLOW QUE TIENEN HISTÓRICAS.
SET @LN_COUNT1 = (SELECT ISNULL(MAX(CONVERT(NUMERIC(10, 0), SUBSTRING(PKEY, 1, 10))) + 1, 1) FROM PHYSICAL_JOB WHERE (ISNUMERIC(SUBSTRING(PKEY, 1, 10)) = 1 AND LEN(PKEY) = 13));
SET @LN_COUNT2 = (SELECT ISNULL(MAX(CONVERT(NUMERIC(10, 0), SUBSTRING(PKEY_PHYSICAL_JOB, 1, 10))) + 1, 1) FROM DSS_TBPHYSICAL_JOB WHERE (ISNUMERIC(SUBSTRING(PKEY_PHYSICAL_JOB, 1, 10)) = 1 AND LEN(PKEY_PHYSICAL_JOB) = 13));
-- EVALÚA EN DÓNDE ESTA LA ÚLTIMA PKEY GENERADA, ENTRE LA TABLA ACTUAL Y SU HISTÓRICA.
IF (@LN_COUNT2 > @LN_COUNT1) BEGIN
	SET @LN_COUNT1 = @LN_COUNT2;
END;
UPDATE	PRM
SET	PRM_VAL = @LN_COUNT1
WHERE	(PRM_COD = 'PHYSICAL_JOB_KEY');
SELECT @LSOPERA = 'UPDATE', @LSTABLA = 'PRM', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
IF (@LNERRORNUM <> 0) GOTO FALLO;
 
SET @LN_COUNT1 = (SELECT ISNULL(MAX(CONVERT(NUMERIC(10, 0), SUBSTRING(PKEY, 1, 10))) + 1, 1) FROM ATTENDED_CUSTOMER WHERE (ISNUMERIC(SUBSTRING(PKEY, 1, 10)) = 1 AND LEN(PKEY) = 13));
SET @LN_COUNT2 = (SELECT ISNULL(MAX(CONVERT(NUMERIC(10, 0), SUBSTRING(PKEY_ATTENDED_CUSTOMER, 1, 10))) + 1, 1) FROM DSS_TBATTENDED_CUSTOMER WHERE (ISNUMERIC(SUBSTRING(PKEY_ATTENDED_CUSTOMER, 1, 10)) = 1 AND LEN(PKEY_ATTENDED_CUSTOMER) = 13));
-- EVALÚA EN DÓNDE ESTA LA ÚLTIMA PKEY GENERADA, ENTRE LA TABLA ACTUAL Y SU HISTÓRICA.
IF (@LN_COUNT2 > @LN_COUNT1) BEGIN
	SET @LN_COUNT1 = @LN_COUNT2;
END;
UPDATE	PRM
SET	PRM_VAL = @LN_COUNT1
WHERE	(PRM_COD = 'ATTENDED_CUSTOMER_KEY');
SELECT @LSOPERA = 'UPDATE', @LSTABLA = 'PRM', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
IF (@LNERRORNUM <> 0) GOTO FALLO;
 
SET @LN_COUNT1 = (SELECT ISNULL(MAX(CONVERT(NUMERIC(10, 0), SUBSTRING(PKEY, 1, 10))) + 1, 1) FROM PHYSICAL_CALL WHERE (ISNUMERIC(SUBSTRING(PKEY, 1, 10)) = 1 AND LEN(PKEY) = 13));
SET @LN_COUNT2 = (SELECT ISNULL(MAX(CONVERT(NUMERIC(10, 0), SUBSTRING(PKEY_PHYSICAL_CALL, 1, 10))) + 1, 1) FROM DSS_TBPHYSICAL_CALL WHERE (ISNUMERIC(SUBSTRING(PKEY_PHYSICAL_CALL, 1, 10)) = 1 AND LEN(PKEY_PHYSICAL_CALL) = 13));
-- EVALÚA EN DÓNDE ESTA LA ÚLTIMA PKEY GENERADA, ENTRE LA TABLA ACTUAL Y SU HISTÓRICA.
IF (@LN_COUNT2 > @LN_COUNT1) BEGIN
	SET @LN_COUNT1 = @LN_COUNT2;
END;
UPDATE	PRM
SET	PRM_VAL = @LN_COUNT1
WHERE	(PRM_COD = 'PHYSICAL_CALL_KEY');
SELECT @LSOPERA = 'UPDATE', @LSTABLA = 'PRM', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
IF (@LNERRORNUM <> 0) GOTO FALLO;
 
SET @LN_COUNT1 = (SELECT ISNULL(MAX(CONVERT(NUMERIC(10, 0), SUBSTRING(PKEY, 1, 10))) + 1, 1) FROM PHYSICAL_CALL_CONV_STEPS WHERE (ISNUMERIC(SUBSTRING(PKEY, 1, 10)) = 1 AND LEN(PKEY) = 13));
SET @LN_COUNT2 = (SELECT ISNULL(MAX(CONVERT(NUMERIC(10, 0), SUBSTRING(ID_CONV_STEPS, 1, 10))) + 1, 1) FROM DSS_TBPHYSICAL_CALL_CONV_STEPS WHERE (ISNUMERIC(SUBSTRING(ID_CONV_STEPS, 1, 10)) = 1 AND LEN(ID_CONV_STEPS) = 13));
-- EVALÚA EN DÓNDE ESTA LA ÚLTIMA PKEY GENERADA, ENTRE LA TABLA ACTUAL Y SU HISTÓRICA.
IF (@LN_COUNT2 > @LN_COUNT1) BEGIN
	SET @LN_COUNT1 = @LN_COUNT2;
END;
UPDATE	PRM
SET	PRM_VAL = @LN_COUNT1
WHERE	(PRM_COD = 'PHYSICAL_CALL_CONV_STEPS_KEY');
SELECT @LSOPERA = 'UPDATE', @LSTABLA = 'PRM', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
IF (@LNERRORNUM <> 0) GOTO FALLO;
 
--SET @LN_COUNT1 = (SELECT ISNULL(MAX(CONVERT(NUMERIC(10, 0), SUBSTRING(PKEY, 1, 10))) + 1, 1) FROM PHYS_CALL_ANSWERED_QUESTIONS WHERE (ISNUMERIC(SUBSTRING(PKEY, 1, 10)) = 1 AND LEN(PKEY) = 13));
--SET @LN_COUNT2 = (SELECT ISNULL(MAX(CONVERT(NUMERIC(10, 0), SUBSTRING(PKEY_PHYS_CALL_ANSWERED_QUES, 1, 10))) + 1, 1) FROM DSS_TBPHYS_CALL_ANSWERED_QUES WHERE (ISNUMERIC(SUBSTRING(PKEY_PHYS_CALL_ANSWERED_QUES, 1, 10)) = 1 AND LEN(PKEY_PHYS_CALL_ANSWERED_QUES) = 13));
---- EVALÚA EN DÓNDE ESTA LA ÚLTIMA PKEY GENERADA, ENTRE LA TABLA ACTUAL Y SU HISTÓRICA.
--IF (@LN_COUNT2 > @LN_COUNT1) BEGIN
--	SET @LN_COUNT1 = @LN_COUNT2;
--END;
--UPDATE	PRM
--SET	PRM_VAL = @LN_COUNT1
--WHERE	(PRM_COD = 'PHYS_CALL_ANSWERED_QUESTIONS_KEY');
--SELECT @LSOPERA = 'UPDATE', @LSTABLA = 'PRM', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
--IF (@LNERRORNUM <> 0) GOTO FALLO;
 
--UPDATE	PRM
--SET	PRM_VAL = (SELECT RIGHT('0000000000' + CONVERT(VARCHAR, ISNULL(MAX(CONVERT(NUMERIC(10, 0), ALARM_CODE)), 0) + 1), 10) FROM ALARM WHERE (ISNUMERIC(SUBSTRING(ALARM_CODE, 1, 10)) = 1))
--WHERE	PRM_COD = 'ALARM_CODE';
--SELECT @LSOPERA = 'UPDATE', @LSTABLA = 'PRM', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
--IF (@LNERRORNUM <> 0) GOTO FALLO;
 
--UPDATE	PRM
--SET	PRM_VAL = (SELECT RIGHT('0000000000' + CONVERT(VARCHAR, ISNULL(MAX(CONVERT(NUMERIC(10, 0), ANSWER_CODE)), 0) + 1), 10) FROM ANSWER WHERE (ISNUMERIC(SUBSTRING(ANSWER_CODE, 1, 10)) = 1))
--WHERE	PRM_COD = 'ANSWER_CODE';
--SELECT @LSOPERA = 'UPDATE', @LSTABLA = 'PRM', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
--IF (@LNERRORNUM <> 0) GOTO FALLO;
 
--UPDATE	PRM
--SET	PRM_VAL = (SELECT RIGHT('0000000000' + CONVERT(VARCHAR, ISNULL(MAX(CONVERT(NUMERIC(10, 0), PHYSICAL_LIST_NUMBER)), 0) + 1), 10) FROM PHYSICAL_LIST WHERE (ISNUMERIC(SUBSTRING(PHYSICAL_LIST_NUMBER, 1, 10)) = 1))
--WHERE	PRM_COD = 'CAMPAIGN_CODE';
--SELECT @LSOPERA = 'UPDATE', @LSTABLA = 'PRM', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
--IF (@LNERRORNUM <> 0) GOTO FALLO;
 
--UPDATE	PRM
--SET	PRM_VAL = (SELECT RIGHT('0000000000' + CONVERT(VARCHAR, ISNULL(MAX(CONVERT(NUMERIC(10, 0), MSS_CODE)), 0) + 1), 10) FROM CHAT_MESSAGE WHERE (ISNUMERIC(SUBSTRING(MSS_CODE, 1, 10)) = 1))
--WHERE	PRM_COD = 'CHAT_MESSAGE_CODE';
--SELECT @LSOPERA = 'UPDATE', @LSTABLA = 'PRM', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
--IF (@LNERRORNUM <> 0) GOTO FALLO;
 
--UPDATE	PRM
--SET	PRM_VAL = (SELECT RIGHT('0000000000' + CONVERT(VARCHAR, ISNULL(MAX(CONVERT(NUMERIC(10, 0), MSS_CODE)), 0) + 1), 10) FROM EMAILIN_MESSAGE WHERE (ISNUMERIC(SUBSTRING(MSS_CODE, 1, 10)) = 1))
--WHERE	PRM_COD = 'EMAILIN_MESSAGE_CODE';
--SELECT @LSOPERA = 'UPDATE', @LSTABLA = 'PRM', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
--IF (@LNERRORNUM <> 0) GOTO FALLO;
 
UPDATE	PRM
SET	PRM_VAL = (SELECT RIGHT('0000000000' + CONVERT(VARCHAR, ISNULL(MAX(CONVERT(NUMERIC(10, 0), ENTITY_CODE)), 0) + 1), 10) FROM ENTITY_BROWSER WHERE (ISNUMERIC(SUBSTRING(ENTITY_CODE, 1, 10)) = 1))
WHERE	PRM_COD = 'ENTITY_BROWSER_CODE';
SELECT @LSOPERA = 'UPDATE', @LSTABLA = 'PRM', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
IF (@LNERRORNUM <> 0) GOTO FALLO;
 
--UPDATE	PRM
--SET	PRM_VAL = (SELECT RIGHT('0000000000' + CONVERT(VARCHAR, ISNULL(MAX(CONVERT(NUMERIC(10, 0), PRM_CODE)), 0) + 1), 10) FROM LINK_PRM WHERE (ISNUMERIC(SUBSTRING(PRM_CODE, 1, 10)) = 1))
--WHERE	PRM_COD = 'PRM_CODE';
--SELECT @LSOPERA = 'UPDATE', @LSTABLA = 'PRM', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
--IF (@LNERRORNUM <> 0) GOTO FALLO;
 
UPDATE	PRM
SET	PRM_VAL = (SELECT RIGHT('0000000000' + CONVERT(VARCHAR, ISNULL(MAX(CONVERT(NUMERIC(10, 0), PRM_CODE)), 0) + 1), 10) FROM TRAN_PRM_IN WHERE (ISNUMERIC(SUBSTRING(PRM_CODE, 1, 10)) = 1))
WHERE	PRM_COD = 'PRMIN_CODE';
SELECT @LSOPERA = 'UPDATE', @LSTABLA = 'PRM', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
IF (@LNERRORNUM <> 0) GOTO FALLO;
 
--UPDATE	PRM
--SET	PRM_VAL = (SELECT RIGHT('0000000000' + CONVERT(VARCHAR, ISNULL(MAX(CONVERT(NUMERIC(10, 0), QUESTION_CODE)), 0) + 1), 10) FROM QUESTION WHERE (ISNUMERIC(SUBSTRING(QUESTION_CODE, 1, 10)) = 1))
--WHERE	PRM_COD = 'QUESTION_CODE';
--SELECT @LSOPERA = 'UPDATE', @LSTABLA = 'PRM', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
--IF (@LNERRORNUM <> 0) GOTO FALLO;
 
--UPDATE	PRM
--SET	PRM_VAL = (SELECT RIGHT('0000000000' + CONVERT(VARCHAR, ISNULL(MAX(CONVERT(NUMERIC(10, 0), MSS_CODE)), 0) + 1), 10) FROM SMS_MESSAGE WHERE (ISNUMERIC(SUBSTRING(MSS_CODE, 1, 10)) = 1))
--WHERE	PRM_COD = 'SMS_MESSAGE_CODE';
--SELECT @LSOPERA = 'UPDATE', @LSTABLA = 'PRM', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
--IF (@LNERRORNUM <> 0) GOTO FALLO;
 
-- SE QUITARÁ EN ENGAGE 5.0.
UPDATE	PRM
SET	PRM_VAL = (SELECT RIGHT('0000000000' + CONVERT(VARCHAR, ISNULL(MAX(CONVERT(NUMERIC(10, 0), PRM_CODE)), 0) + 1), 10) FROM SP_PRM_IN WHERE (ISNUMERIC(SUBSTRING(PRM_CODE, 1, 10)) = 1))
WHERE	PRM_COD = 'SP_PRM_IN_CODE';
SELECT @LSOPERA = 'UPDATE', @LSTABLA = 'PRM', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
IF (@LNERRORNUM <> 0) GOTO FALLO;
 
--UPDATE	PRM
--SET	PRM_VAL = (SELECT RIGHT('0000000000' + CONVERT(VARCHAR, ISNULL(MAX(CONVERT(NUMERIC(10, 0), MSS_CODE)), 0) + 1), 10) FROM TEXT_MESSAGE WHERE (ISNUMERIC(SUBSTRING(MSS_CODE, 1, 10)) = 1))
--WHERE	PRM_COD = 'TEXT_MESSAGE_CODE';
--SELECT @LSOPERA = 'UPDATE', @LSTABLA = 'PRM', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
--IF (@LNERRORNUM <> 0) GOTO FALLO;
 
FALLO:
-- REGISTRO DE SUCESOS Y CONTROL DE FIN DE PROCEDIMIENTO. CONCLUYE LA TRANSACCIÓN SI TODO FUE EXITOSO.
SELECT @LNDURACION = DATEDIFF(SECOND, @LDINICIO_OPE, GETDATE()), @LNSEVERITY = ISNULL(EM.SEVERITY, 16), @LSERRORDESC = 'ERROR ' + CONVERT(VARCHAR, ISNULL(EM.ERROR, 0)) + ' - ' + ISNULL(EM.DESCRIPTION, ' ') FROM MASTER.DBO.SYSMESSAGES EM WHERE (EM.ERROR = @LNERRORNUM);
IF (@LNERRORNUM <> 0) BEGIN
	-- NOTIFICACIÓN EN EL REGISTRO DE SQL SERVER.
	SET @LSERRORLOG = @LSERRORLOG + CASE WHEN (ISNULL(CHARINDEX('%', @LSERRORDESC), 0) > 0) THEN RTRIM(LEFT(@LSERRORDESC, 11)) ELSE @LSERRORDESC END;
	-- DEVUELVE EL ERROR EN EL PARÁMETRO DE SALIDA.
	SET @PS_RET_MESSAGE = SUBSTRING(@LSERRORDESC, 1, 440);
	-- DESHACE LA TRANSACCIÓN COMPLETA SI LA OPERACIÓN FALLÓ.
	IF (@@TRANCOUNT > 0) ROLLBACK TRANSACTION;
	EXECUTE @LNERRORNUM = PA_SYS_REGISTRO_SUCESOS_INSERT @PSPROCEDIMIENTO_1 = @LSPROC, @PSTABLA_2 = @LSTABLA, @PNFILAS_AFECTADAS_3 = @LNFILAS_AFEC, @PSOPERACION_4 = @LSOPERA, @PNDURACION_5 = @LNDURACION, @PSRESULTADO_6 = @LSERRORDESC, @PSSQL_CMD_7 = @LSERRORDESC;
	-- RAISERROR(@LSERRORLOG, @LNSEVERITY, -1) WITH NOWAIT;
END
ELSE BEGIN
	EXECUTE @LNERRORNUM = PA_SYS_REGISTRO_SUCESOS_INSERT @PSPROCEDIMIENTO_1 = @LSPROC, @PSTABLA_2 = @LSTABLA, @PNFILAS_AFECTADAS_3 = @LNFILAS_AFEC, @PSOPERACION_4 = @LSOPERA, @PNDURACION_5 = @LNDURACION, @PSRESULTADO_6 = @LSERRORDESC, @PSSQL_CMD_7 = @LSERRORDESC;
	IF (@@TRANCOUNT > 0) COMMIT TRANSACTION;
END;
RETURN;
