CREATE PROCEDURE [dbo].[HOME_GRABA_DATOS_AGENDA]
(@IPKEYJOB	AS VARCHAR(100),
 @FORM_ID	AS VARCHAR(100),
 @IAGENTE	AS VARCHAR(100))
AS
 
DECLARE	@VCLIENTE			VARCHAR(100), 
		@VID_PROYECTO		VARCHAR(100),
		@VID_SERVICIO		VARCHAR(100),
		@VID_AGENDA			VARCHAR(100),
		@VESTADO			VARCHAR(100),
		@VOBSERVACIONES		VARCHAR(400),
		@VOBS_CALIF			VARCHAR(400),
		@VOBS_LOGIS			VARCHAR(400)
 
BEGIN	
 
	SELECT	--@VCLIENTE = ISNULL(CLIENTE,''),
	--		@VID_PROYECTO =	ISNULL(PROYECTO_ID,''),
	--		@VID_SERVICIO = ISNULL(PROYECTO_SERV_ID,''),
			@VID_AGENDA		= isnull(nullif(ltrim(rtrim(AGENDA_ID)),''),''),
			@VESTADO		= isnull(nullif(ltrim(rtrim(AGENDA_ESTADO)),''),''),
			@VOBSERVACIONES = isnull(nullif(ltrim(rtrim(AGENDA_OBSERVADOR)),''),''),
			@VOBS_CALIF		= isnull(nullif(ltrim(rtrim(AGENDA_OBSERV_CALIF)),''),'')
			--@VOBS_LOGIS		= isnull(nullif(ltrim(rtrim(AGENDA_OBSERV_LOGIS)),''),'')
	FROM	XAGENDA
	WHERE	PAR_KEY = @IPKEYJOB
 
	UPDATE	LK_AGENDA
	SET		ESTADO = @VESTADO,
			OBSERVADOR = @VOBSERVACIONES,
			--OBSERV_LOGISTICA = @VOBS_LOGIS,
			OBSERV_CALIF = @VOBS_CALIF
	WHERE	convert(varchar,ID_AGENDA) = @VID_AGENDA
 
END
