CREATE PROCEDURE [dbo].[HOME_ADD_FEC_CONSULTOR]
(@IPKEYJOB	AS VARCHAR(100),
 @IAGENTE	AS VARCHAR(100),
 @OCODE		AS VARCHAR(2) OUTPUT,
 @OMENSAJE	AS VARCHAR(400) OUTPUT)
AS
 
DECLARE @VFECHA			VARCHAR(50),
		@VFECHAD		VARCHAR(50),
		@VFECHAH		VARCHAR(50),
		@VCONSULTOR		VARCHAR(50),
		@VTIPO			VARCHAR(50),
		@VMOTIVO		VARCHAR(50),
		@VERROR			VARCHAR(50),
		@VREG			INT,
		@VDIF			INT,
		@VCANT			INT,
		@VDESC			VARCHAR(300),
		@VHORAS			NUMERIC(5,0)
 
BEGIN	
 
	SET @OCODE = '0'
	SET @OMENSAJE = ''
 
	SELECT	@VCONSULTOR = ISNULL(AGENDA_CONSULTOR,''),
			@VFECHAD = ISNULL(FECHA_SELEC,''),
			@VFECHAH = ISNULL(AGENDA_FECHA,''),
			@VTIPO = ISNULL(AGENDA_TIPO,''),
			@VMOTIVO = ISNULL(AGENDA_MOTIVO,''),
			@VERROR = ISNULL(ERROR,''),
			@VDESC = ISNULL(AGENDA_DESC,''),
			@VHORAS = ISNULL(AGENDA_HORAS,0)
	FROM	XAGENDA
	WHERE	PAR_KEY = @IPKEYJOB
	
	/*IF @VERROR = '' BEGIN
		SET @OCODE = '0'
		SET @OMENSAJE = ''
 
	END ELSE BEGIN*/
 
		IF (@VFECHAH = '') BEGIN
			UPDATE	XAGENDA
			SET		DESC_ERROR = 'Debe Completar el Campo Fecha Hasta'
			WHERE	PAR_KEY = @IPKEYJOB
 
			SET @OCODE = '1'
			RETURN
		
		END ELSE BEGIN
			
			IF (@VFECHAH < @VFECHAD ) BEGIN
				UPDATE	XAGENDA
				SET		DESC_ERROR = 'El Campo Fecha Hasta Debe ser Mayor o Igual a la Fecha Desde'
				WHERE	PAR_KEY = @IPKEYJOB
 
				SET @OCODE = '1'
				RETURN
			END			
		
		END
 
		IF (@VTIPO = '') BEGIN
												
			UPDATE	XAGENDA
			SET		DESC_ERROR = 'Debe completar el Campo Tipo'
			WHERE	PAR_KEY = @IPKEYJOB
			
			SET @OCODE = '1'
			RETURN
 
		END ELSE BEGIN
			
			IF (@VTIPO = 'LIC' AND @VMOTIVO = '') BEGIN
													
				UPDATE	XAGENDA
				SET		DESC_ERROR = 'Debe completar el Campo Motivo para el Tipo Seleccionado'
				WHERE	PAR_KEY = @IPKEYJOB
				
				SET @OCODE = '1'
				RETURN
			END	
 
			IF (@VTIPO = 'POT' AND @VDESC = '') BEGIN
									
				UPDATE	XAGENDA
				SET		DESC_ERROR = 'Debe completar el Campo Descripción para el Tipo Seleccionado'
				WHERE	PAR_KEY = @IPKEYJOB
				
				SET @OCODE = '1'
				RETURN
			END
 
			IF (@VTIPO = 'D' AND @VHORAS <= 0) BEGIN
													
				UPDATE	XAGENDA
				SET		DESC_ERROR = 'Debe completar el Campo Horas (Mayor a Cero) para el Tipo Seleccionado',
						AGENDA_MOTIVO = NULL,
						AGENDA_DESC = NULL
				WHERE	PAR_KEY = @IPKEYJOB
				
				SET @OCODE = '1'
				RETURN
			END	
 
			IF (@VTIPO = 'POT' AND @VHORAS <> 8) BEGIN
													
				UPDATE	XAGENDA
				SET		DESC_ERROR = 'Debe completar el Campo Horas (8) para el Tipo Seleccionado',
						AGENDA_MOTIVO = NULL,
						AGENDA_DESC = NULL
				WHERE	PAR_KEY = @IPKEYJOB
				
				SET @OCODE = '1'
				RETURN
			END	
 
			IF (@VTIPO IN ('ND','OC','OP','LIC','OA') AND @VHORAS > 0) BEGIN
													
				UPDATE	XAGENDA
				SET		DESC_ERROR = 'NO Debe completar el Campo Horas para el Tipo Seleccionado',
						AGENDA_MOTIVO = NULL,
						AGENDA_DESC = NULL
				WHERE	PAR_KEY = @IPKEYJOB
				
				SET @OCODE = '1'
				RETURN
			END	
 
		END
 
		SET @VREG = 0
		SET @VDIF = DATEDIFF(DD,@VFECHAD,@VFECHAH)
		SET @VFECHA = @VFECHAD
 
		WHILE @VREG <= @VDIF  
		BEGIN  
			
			--VALIDO QUE NO LA FECHA NO SEA FERIADO-- SI ES FERIADO, NO LA INGRESO EN LK_AGENDA_EMPLEADO
			SELECT	@VCANT = COUNT(1)
			FROM	Calendar
			WHERE	Fecha = @VFECHA
			AND		IsHoliday = 1
 
			IF (@VCANT > 0) BEGIN
				
				SET @VFECHA = CONVERT(VARCHAR(10), CONVERT(date, DATEADD(DD,1,@VFECHA), 105), 23)
				SET @VREG = @VREG + 1
 
			END ELSE BEGIN
				
				--VALIDO SI LA FECHA YA ESTA CARGADA COMO DISPONIBLE, NO DISPOBLE O LICENCIA-- SI YA ESTA, NO LA INGRESO EN LK_AGENDA_CONSULTOR
				SELECT	@VCANT = COUNT(1)
				FROM	LK_AGENDA_EMPLEADO
				WHERE	FECHA = @VFECHA
				AND		ID_EMPLEADO = @VCONSULTOR
 
				IF (@VCANT > 0) BEGIN
				
					SET @VFECHA = CONVERT(VARCHAR(10), CONVERT(date, DATEADD(DD,1,@VFECHA), 105), 23)
					SET @VREG = @VREG + 1
				
				END ELSE BEGIN
 
					INSERT INTO LK_AGENDA_EMPLEADO
					(ID_EMPLEADO, FECHA, DIA, MES, ANO, 
					 ISHOLIDAY, HOLIDAYTEXT, TIPO, FECHA_ALTA, USUARIO_ALTA, DESCRIPCION, 
					 HORAS, HORAS_DISP)
					VALUES
					(@VCONSULTOR, @VFECHA, DATEPART(DD,@VFECHA), DATEPART(MM,@VFECHA), DATEPART(YYYY,@VFECHA),
					 CASE WHEN @VTIPO = 'LIC' THEN 1 ELSE 0 END, @VMOTIVO, @VTIPO, GETDATE(), @IAGENTE, CASE WHEN @VTIPO <> 'D' THEN @VDESC ELSE NULL END,
					 CASE WHEN @VTIPO = 'D' THEN 0 ELSE NULL END, CASE WHEN @VTIPO = 'ND' THEN NULL ELSE @VHORAS END)
 
					SET @VFECHA = CONVERT(VARCHAR(10), CONVERT(date, DATEADD(DD,1,@VFECHA), 105), 23)
					SET @VREG = @VREG + 1
 
				END
			END
		END 
 
	--END
	
	IF (@OCODE = '0') BEGIN
		UPDATE	XAGENDA
		SET		DESC_ERROR = NULL,
				FECHA_SELEC = NULL,
				AGENDA_FECHA = NULL,
				AGENDA_TIPO = NULL,
				AGENDA_MOTIVO = NULL,
				AGENDA_DESC = NULL,
				AGENDA_HORAS = NULL
		WHERE	PAR_KEY = @IPKEYJOB
	END
 
END
 
