CREATE PROCEDURE [dbo].[PA_SYS_REGISTRO_SUCESOS_INSERT] (@PSPROCEDIMIENTO_1 AS VARCHAR(30) = NULL, @PSTABLA_2 AS VARCHAR(30) = NULL, @PNFILAS_AFECTADAS_3 AS INTEGER = NULL, @PSOPERACION_4 AS VARCHAR(30) = NULL, @PNDURACION_5 AS INTEGER = NULL, @PSRESULTADO_6 AS VARCHAR(440) = NULL, @PSSQL_CMD_7 AS VARCHAR(4000) = NULL) AS
 
SET NOCOUNT ON;
SET XACT_ABORT ON;
 
-- DECLARACIÓN DE VARIABLES PARA OPERAR.
DECLARE	@LSPROCEDIMIENTO_1 AS VARCHAR(30),
	@LSTABLA_2 AS VARCHAR(30),
	@LNFILAS_AFECTADAS_3 AS INTEGER,
	@LSOPERACION_4 AS VARCHAR(30),
	@LNDURACION_5 AS INTEGER,
	@LSRESULTADO_6 AS VARCHAR(440),
	@LSSQL_CMD_7 AS VARCHAR(4000)
;
SELECT	@LSPROCEDIMIENTO_1 = @PSPROCEDIMIENTO_1,
	@LSTABLA_2  = @PSTABLA_2,
	@LNFILAS_AFECTADAS_3 = @PNFILAS_AFECTADAS_3,
	@LSOPERACION_4 = @PSOPERACION_4,
	@LNDURACION_5 = @PNDURACION_5,
	@LSRESULTADO_6 = @PSRESULTADO_6,
	@LSSQL_CMD_7 = @PSSQL_CMD_7
;
 
BEGIN TRANSACTION
 
-- INSERTA UNA FILA EN EL REGISTRO DE SUCESOS.
INSERT INTO	EDA_REGISTRO_SUCESOS (PROCEDIMIENTO, TABLA, FILAS_AFECTADAS, OPERACION, DURACION, RESULTADO, SQL_CMD)
VALUES		(@LSPROCEDIMIENTO_1, @LSTABLA_2, @LNFILAS_AFECTADAS_3, @LSOPERACION_4, @LNDURACION_5, @LSRESULTADO_6, @LSSQL_CMD_7);
 
COMMIT TRANSACTION;
 
RETURN;
 
