CREATE   PROCEDURE [dbo].[SV_01_DOC_RELACIONADA]
(@IPKEYJOB	AS VARCHAR(100),
 @IAGENTE	AS VARCHAR(100))
AS
 
DECLARE @VTIPO		VARCHAR(50),
		@VCLAVE_DOC	VARCHAR(100),
		@VCANT		INT
 
BEGIN	
 
	SELECT	@VTIPO = ISNULL(TIPO_SERVICIO,''),
			@VCLAVE_DOC = ISNULL(CLAVE_DOC,'')
	FROM	TMT_SV_01
	WHERE	PAR_KEY = @IPKEYJOB
 
	--REVISO SI EXISTE O NO UN REGISTRO EN LK_DOCUMENTACION_REL POR TIPO DE SERVICIO Y CLAVE DOC--
	SELECT	@VCANT = COUNT(1)
	FROM	LK_DOCUMENTACION_REL
	WHERE	ID_TIPO_SERVICIO = @VTIPO
	AND		ID_DOCUMENTACION = @VCLAVE_DOC
 
	--SINO EXISTE, AGREGO EL REGISTRO--
	IF (@VCANT = 0) BEGIN
		
		INSERT INTO LK_DOCUMENTACION_REL
		(ID_DOCUMENTACION, ID_TIPO_SERVICIO, FECHA_ALTA, USUARIO_ALTA)
		VALUES
		(@VCLAVE_DOC, @VTIPO, GETDATE(), @IAGENTE)
	
	--SI EXISTE, ELIMINO EL REGISTRO--
	END ELSE BEGIN
 
		DELETE	FROM LK_DOCUMENTACION_REL
		WHERE	ID_DOCUMENTACION = @VCLAVE_DOC
		AND		ID_TIPO_SERVICIO = @VTIPO
 
	END
 
	UPDATE	TMT_SV_01
	SET		CLAVE_DOC = NULL
	WHERE	PAR_KEY = @IPKEYJOB
 
END
 
