CREATE PROCEDURE [dbo].[HOME_CMB_SERVICIOS_TIPO_ANEXO]
(@IPKEYJOB	AS VARCHAR(100))
AS
 
DECLARE	@VID_PROYECTO	VARCHAR(50),
		@VTIPO_SERV_SEL	VARCHAR(50)
 
BEGIN	
 
	SELECT	@VID_PROYECTO = ISNULL(PROYECTO_ID,''),
			@VTIPO_SERV_SEL = ISNULL(AGENDA_ESTADO,'')
	FROM	XAGENDA
	WHERE	PAR_KEY = @IPKEYJOB
 
	--SINO TIENE MINUTA DE GESTION, ES PROYECTO VIEJO--
	IF (@VTIPO_SERV_SEL <> '') BEGIN
 
		SELECT	CONVERT(VARCHAR,ID_PROYECTO_SERVICIO)	AS CAT_DATA_CODE,
				ISNULL(NOMBRE,'')						AS CAT_DATA_DESC,
				'true'
		FROM	LK_PROYECTO_SERVICIO
		WHERE	ID_PROYECTO = @VID_PROYECTO
		AND		ID_TIPO_SERVICIO = @VTIPO_SERV_SEL
		ORDER BY CAT_DATA_DESC
	END
	
END
