CREATE PROCEDURE [dbo].[EP_DEL_USR_PLANTA]
(@IPKEYJOB	AS VARCHAR(100))
AS
 
BEGIN	
 
	DECLARE 
	@ID_PLANTA_SEL VARCHAR(50),
	@ID_USER_SEL VARCHAR(30);
 
	UPDATE TMT_CRON 
	SET [ACTION]='DELETE_USER'
	WHERE PAR_KEY= @IPKEYJOB;
	
	SELECT @ID_PLANTA_SEL = ID_PLANTA_SEL, @ID_USER_SEL=ID_USER_SEL FROM TMT_CRON WHERE PAR_KEY= @IPKEYJOB;
 
	DELETE EP_PLANTAS_USUARIOS 
		WHERE IDPlanta=CAST(@ID_PLANTA_SEL AS INT)
		AND IdUsuario = @ID_USER_SEL;
 
END
