 
CREATE PROCEDURE PA_SYS_UPD_PORTFOLIO_HISTORY (@PSCUSTOMER_PKEY VARCHAR(60), @PSPORTFOLIO_DESC_ANTERIOR VARCHAR(50)) AS
-- ESTE PROCEDIMIENTO ALMACENADO SE DEBERÁ UTILIZAR PARA MANTENER LA HISTORIA DE ASIGNACIONES DE ESTUDIOS JURÍDICOS DE UN CLIENTE ESPECÍFICO.
SET NOCOUNT ON;
SET XACT_ABORT ON;
 
DECLARE
@LSCUSTOMER_PKEY AS VARCHAR(60),
@LSPORTFOLIO_DESC_ANTERIOR AS VARCHAR(50);
 
BEGIN TRANSACTION
 
SELECT @LSCUSTOMER_PKEY = @PSCUSTOMER_PKEY;
SELECT @LSPORTFOLIO_DESC_ANTERIOR = @PSPORTFOLIO_DESC_ANTERIOR;
 
COMMIT TRANSACTION;
 
RETURN;
