CREATE PROCEDURE [dbo].[PA_SYS_CAT_DATA_EDITAR]
 
@PKEY_JOB VARCHAR(100)
 
AS
 
BEGIN
 
DECLARE 
@AT_1 VARCHAR(300),
@AT_2 VARCHAR(50),
@AT_3 VARCHAR(50),
@AT_4 VARCHAR(50),
@AT_5 VARCHAR(50),
@AT_6 VARCHAR(50),
@AT_1_LABEL VARCHAR(20),
@AT_2_LABEL VARCHAR(20),
@AT_3_LABEL VARCHAR(20),
@AT_4_LABEL VARCHAR(20),
@AT_5_LABEL VARCHAR(20),
@AT_6_LABEL VARCHAR(20),
@DESC VARCHAR(300),
@COD VARCHAR(50)
 
SELECT @COD=CD.CAT_DATA_CODE, @DESC = CD.CAT_DATA_DESC, @AT_1=CD.ATTR1, @AT_2=CD.ATTR2, @AT_3=CD.ATTR3, @AT_4=CD.ATTR4,
@AT_5=CD.ATTR5, @AT_6=CD.ATTR6, @AT_1_LABEL=CT.ATTR1, @AT_2_LABEL=CT.ATTR2, @AT_3_LABEL=CT.ATTR3, @AT_4_LABEL=CT.ATTR4,
@AT_5_LABEL=CT.ATTR5,@AT_6_LABEL=CT.ATTR6
FROM     CAT_DATA CD 
INNER JOIN TMT_CATEGORIAS TMT ON CD.PKEY = TMT.PKEY_ELEM
INNER JOIN CAT_TYPE CT ON CT.PKEY = CD.PAR_KEY
WHERE    TMT.PAR_KEY = @PKEY_JOB;
 
UPDATE TMT_CATEGORIAS
SET COD_ELEMENTO=@COD,
ELEM_DESC=@DESC,
AT_1=@AT_1,
AT_2=@AT_2,
AT_3=@AT_3,
AT_4=@AT_4,
AT_5=@AT_5,
AT_6=@AT_6,
AT_1_LABEL=@AT_1_LABEL,
AT_2_LABEL=@AT_2_LABEL,
AT_3_LABEL=@AT_3_LABEL,
AT_4_LABEL=@AT_4_LABEL,
AT_5_LABEL=@AT_5_LABEL,
AT_6_LABEL=@AT_6_LABEL
WHERE PAR_KEY = @PKEY_JOB
 
END
 
