CREATE   PROCEDURE [dbo].[M_CONFIG_CMB_SECTOR_USERS]
(@IPKEYJOB	AS VARCHAR(100))
AS
 
DECLARE @V_SECTOR_SEL VARCHAR(50)
 
BEGIN
 
	SELECT	@V_SECTOR_SEL = ISNULL(ID_SECTOR_SEL,'')
	FROM	M_CONFIG
	WHERE	PAR_KEY = @IPKEYJOB
 
	SELECT	Id		AS CAT_DATA_CODE, 
			Name	AS CAT_DATA_DESC,
			'TRUE'
	FROM	Users u
	WHERE	Id not in (
			select Id_User from UsersSector 
			WHERE convert(varchar,Id_Sector)=@V_SECTOR_SEL)
	ORDER BY Name
 
END
