CREATE PROCEDURE PA_SYS_DELETE_PROCESS_LIST (@PS_PKEY_CAMPAIGN VARCHAR(36), @PS_RET_MESSAGE VARCHAR(440) = NULL OUTPUT) AS
 
-- =========================================================================================================================
-- AUTOR: TITO - ENGAGE SOFTWARE COMPANY
-- FECHA DE CREACIÓN: 17/01/2011
-- EDITOR: TITO - ENGAGE SOFTWARE COMPANY
-- FECHA DE MODIFICACIÓN: 23/12/2011
-- TABLAS LEÍDAS: PHYSICAL_JOB, DSS_TBPHYSICAL_JOB.
-- TABLAS MODIFICADAS: PHYSICAL_JOB_ACTIONS, PHYSICAL_ACTIVITIES, PHYSICAL_JOB_ALARMS,
-- PHYSICAL_ATTACHED_DOCUMENT, PHYSICAL_NOTES, PHYSICAL_JOB_NOTIFICATIONS,
-- PHYSICAL_CALL_TRANSACTIONS, PHYSICAL_CALL_CONV_STEPS, PHYSICAL_CALL, ATTENDED_CUSTOMER,
-- PHYSICAL_JOB, DSS_TBPHYSICAL_CALL_CONV_STEPS, DSS_TBPHYSICAL_CALL, DSS_TBATTENDED_CUSTOMER, DSS_TBPHYSICAL_JOB.
-- DESCRIPCIÓN: PROCEDIMIENTO QUE OBTIENE LOS TRÁMITES NOTWORKED PERTENECIENTES A LA LISTA PARAMETRIZADA QUE, LUEGO, SON
-- DEPURADOS POR OTRO PROCEDIMIENTO SIN CONSERVAR LA HISTORIA.
-- CONSIDERACIONES:
-- LA DEPURACIÓN SE REALIZA SOBRE TRÁMITES NO TRABAJADOS Y TODA LA INFORMACIÓN RELACIONADA DE LOS MISMOS.
-- =========================================================================================================================
 
SET NOCOUNT ON;
SET XACT_ABORT ON;
 
-- DECLARACIÓN E INICIALIZACIÓN DE VARIABLES DE ERROR Y AUXILIARES.
DECLARE @LNERRORNUM AS INTEGER,
	@LNSEVERITY AS SMALLINT,
	@LNFILAS_AFEC AS INTEGER,
	@LDINICIO_OPE AS DATETIME,
	@LNDURACION AS INTEGER,
	@LSOPERA AS VARCHAR(30),
	@LSPROC AS VARCHAR(30),
	@LSTABLA AS VARCHAR(30),
	@LSERRORLOG AS VARCHAR(440),
	@LSERRORDESC AS VARCHAR(440);
 
SELECT 	@LNERRORNUM = 0,
	@LNSEVERITY = 16,
	@LNFILAS_AFEC = 0,
	@LDINICIO_OPE = GETDATE(),
	@LNDURACION = 0,
	@LSOPERA = 'EXECUTE',
	@LSPROC = OBJECT_NAME(@@PROCID),
	@LSTABLA = 'NINGUNA',
	@LSERRORLOG = @@SERVERNAME + '.' + DB_NAME() + '.' + USER_NAME() + '.' + OBJECT_NAME(@@PROCID) + ' - ',
	@LSERRORDESC = NULL;
 
-- DECLARA LAS VARIABLES.
DECLARE	@LS_PKEY_CAMPAIGN AS VARCHAR(36),
	@LS_RET_MESSAGE AS VARCHAR(440),
	@LN_JOB_SEQ AS NUMERIC(15, 0),
	@LS_JOB_STATE_CODE VARCHAR(20);
 
-- ASIGNA VALORES PREDETERMINADOS A LAS VARIABLES.
SELECT	@LS_PKEY_CAMPAIGN = NULLIF(@PS_PKEY_CAMPAIGN, ''),
	@LS_RET_MESSAGE = NULL,
	@LN_JOB_SEQ = NULL,
	@LS_JOB_STATE_CODE = 'NOTWORKED';
 
-- DECLARO LA TRANSACCIÓN.
BEGIN TRANSACTION
 
IF (@LS_PKEY_CAMPAIGN IS NOT NULL) BEGIN
	IF (CURSOR_STATUS('LOCAL', 'LOCUR1') >= 0) BEGIN
		-- CIERRA Y DESALOJA EL CURSOR.
		CLOSE LOCUR1;
		DEALLOCATE LOCUR1;
	END;
 
	-- CARGA UN CURSOR CON LAS PKEY DE LOS TRÁMITES NO TRABAJADOS DE LA LISTA INDICADA.
	DECLARE LOCUR1 CURSOR LOCAL FAST_FORWARD TYPE_WARNING FOR
		SELECT	JOB_SEQ
		FROM	PHYSICAL_JOB
		WHERE	(JOB_STATE_CODE = @LS_JOB_STATE_CODE)
			AND (PKEY_CAMPAIGN = @LS_PKEY_CAMPAIGN)
		UNION
		SELECT	JOB_SEQ
		FROM	DSS_TBPHYSICAL_JOB
		WHERE	(JOB_STATE_CODE = @LS_JOB_STATE_CODE)
			AND (ID_CAMPAIGN = @LS_PKEY_CAMPAIGN)
		ORDER BY JOB_SEQ ASC;
	SELECT @LSOPERA = 'DECLARE CURSOR', @LSTABLA = 'LOCUR1', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
 
	OPEN LOCUR1;
	FETCH NEXT FROM LOCUR1 INTO @LN_JOB_SEQ;
 
	-- CICLO DE PKEY DE TRÁMITES.
	WHILE (@@FETCH_STATUS = 0) AND (@LSERRORDESC IS NULL)
	BEGIN
		-- ELIMINA EL TRÁMITE ESPECIFICADO POR PARÁMETRO JUNTO CON LA HISTORIA DEL MISMO.
		EXECUTE @LNERRORNUM = PA_SYS_BORRAR_TRAMITE_POR_PKEY @PNTRAMITE_NRO = @LN_JOB_SEQ, @PSPKEY = NULL, @PSCONSERVAR_DSS = 'N', @PS_RET_MESSAGE = @LSERRORDESC OUTPUT;
		SELECT @LSOPERA = 'EXECUTE', @LSTABLA = 'PA_SYS_BORRAR_TRAMITE_POR_PKEY', @LNFILAS_AFEC = @@ROWCOUNT;
		IF (@LNERRORNUM <> 0) GOTO FALLO;
 
		FETCH NEXT FROM LOCUR1 INTO @LN_JOB_SEQ;
	END;
 
	CLOSE LOCUR1;
	DEALLOCATE LOCUR1;
END
ELSE BEGIN
	SET @LS_RET_MESSAGE = 'EL PARÁMETRO @PS_PKEY_CAMPAIGN ES NULO.';
END;
 
SET @PS_RET_MESSAGE = @LS_RET_MESSAGE;
 
FALLO:
-- REGISTRO DE SUCESOS Y CONTROL DE FIN DE PROCEDIMIENTO. CONCLUYE LA TRANSACCIÓN SI TODO FUE EXITOSO.
SELECT @LNDURACION = DATEDIFF(SECOND, @LDINICIO_OPE, GETDATE()), @LNSEVERITY = ISNULL(EM.SEVERITY, 16), @LSERRORDESC = 'ERROR ' + CONVERT(VARCHAR, ISNULL(EM.ERROR, 0)) + ' - ' + ISNULL(EM.DESCRIPTION, ' ') FROM MASTER.DBO.SYSMESSAGES EM WHERE (EM.ERROR = @LNERRORNUM);
IF (@LNERRORNUM <> 0) BEGIN
	-- NOTIFICACIÓN EN EL REGISTRO DE SQL SERVER.
	SET @LSERRORLOG = @LSERRORLOG + CASE WHEN (ISNULL(CHARINDEX('%', @LSERRORDESC), 0) > 0) THEN RTRIM(LEFT(@LSERRORDESC, 11)) ELSE @LSERRORDESC END;
	-- DEVUELVE EL ERROR EN EL PARÁMETRO DE SALIDA.
	SET @PS_RET_MESSAGE = SUBSTRING(@LSERRORDESC, 1, 440);
	-- DESHACE LA TRANSACCIÓN COMPLETA SI LA OPERACIÓN FALLÓ.
	IF (@@TRANCOUNT > 0) ROLLBACK TRANSACTION;
	EXECUTE @LNERRORNUM = PA_SYS_REGISTRO_SUCESOS_INSERT @PSPROCEDIMIENTO_1 = @LSPROC, @PSTABLA_2 = @LSTABLA, @PNFILAS_AFECTADAS_3 = @LNFILAS_AFEC, @PSOPERACION_4 = @LSOPERA, @PNDURACION_5 = @LNDURACION, @PSRESULTADO_6 = @LSERRORDESC, @PSSQL_CMD_7 = @LSERRORDESC;
	-- RAISERROR(@LSERRORLOG, @LNSEVERITY, -1) WITH NOWAIT;
END
ELSE BEGIN
	EXECUTE @LNERRORNUM = PA_SYS_REGISTRO_SUCESOS_INSERT @PSPROCEDIMIENTO_1 = @LSPROC, @PSTABLA_2 = @LSTABLA, @PNFILAS_AFECTADAS_3 = @LNFILAS_AFEC, @PSOPERACION_4 = @LSOPERA, @PNDURACION_5 = @LNDURACION, @PSRESULTADO_6 = @LSERRORDESC, @PSSQL_CMD_7 = @LSERRORDESC;
	IF (@@TRANCOUNT > 0) COMMIT TRANSACTION;
END;
RETURN;
