create PROCEDURE [dbo].[PA_SYS_CAT_DATA_ACTIVAR]
 
@PKEY_JOB VARCHAR(100)
 
AS
 
BEGIN
 
DECLARE @ESTADO VARCHAR(1)
 
SELECT  @ESTADO = CD.CAT_INACTIVE
FROM     CAT_DATA CD,  TMT_CATEGORIAS TMT
WHERE    TMT.PAR_KEY = @PKEY_JOB
AND CD.PKEY = TMT.PKEY_ELEM
 
IF @ESTADO='1' 
	BEGIN
		UPDATE CD
		SET CAT_INACTIVE='0'
		FROM     CAT_DATA CD,  TMT_CATEGORIAS TMT
		WHERE    TMT.PAR_KEY = @PKEY_JOB
		AND CD.PKEY = TMT.PKEY_ELEM
	END
ELSE
	BEGIN
		UPDATE CD
		SET CAT_INACTIVE='1'
		FROM     CAT_DATA CD,  TMT_CATEGORIAS TMT
		WHERE    TMT.PAR_KEY = @PKEY_JOB
		AND CD.PKEY = TMT.PKEY_ELEM	
	END
 
END
 
 
 
