CREATE   PROCEDURE [dbo].[SV_01_MOD_EMPLEADO_APT]
(@IPKEYJOB	AS VARCHAR(100),
 @IAGENTE	AS VARCHAR(100))
AS
 
DECLARE @VCLAVE			VARCHAR(100),
		@VOBSERVACION	VARCHAR(400),
		@VCALIFICACION	VARCHAR(50),
		@VEMPLEADO		VARCHAR(50),
		@VAPTITUD		VARCHAR(50),
		@VCANT			INT
 
BEGIN	
 
	SELECT	@VCLAVE = ISNULL(CLAVE,''),
			@VEMPLEADO	= ISNULL(EMPLEADO,''),
			@VAPTITUD = ISNULL(APTITUD,''),
			@VCALIFICACION = ISNULL(CALIFICACION,''),
			@VOBSERVACION = ISNULL(OBSERVACION,'')
	FROM	TMT_SV_01
	WHERE	PAR_KEY = @IPKEYJOB
 
	UPDATE	LK_EMPLEADOS_APTITUD
	SET		CALIFICACION = @VCALIFICACION, 
			OBSERVACION = @VOBSERVACION, 
			FECHA_UPD = GETDATE(), 
			USUARIO_UPD = @IAGENTE
	WHERE	ID_EMPLE_APTITUD = @VCLAVE
 
	UPDATE	TMT_SV_01
	SET		APTITUD = NULL,
			CALIFICACION = NULL,
			OBSERVACION = NULL,
			CLAVE = NULL
	WHERE	PAR_KEY = @IPKEYJOB
 
END
 
