CREATE   PROCEDURE [dbo].[SV_01_CMB_TIPO_SERVICIO]
(@IPKEYJOB	AS VARCHAR(100))
AS
BEGIN	
 
	SELECT	ID_TIPO_SERVICIO AS CAT_DATA_CODE,
			DESC_TIPO_SERVICIO AS CAT_DATA_DESC,
			'TRUE'
	FROM	LK_TIPO_SERVICIOS
	ORDER BY ID_TIPO_SERVICIO
 
END
 
