CREATE PROCEDURE [dbo].[PA_SYS_MY_JOBS]
	(@USER_ID AS VARCHAR(100),
	@PARENT_JOB AS VARCHAR(100),
	@GROUP_ID AS VARCHAR(100))
AS
BEGIN
 
	IF  @GROUP_ID = 'JEFES_OPERATIVOS' 
		BEGIN
			SELECT '<a href="javascript:restartTask(''' + ATT.PKEY_JOB + ''',''' + ATT.PKEY + ''',''' + cast(PJ.JOB_SEQ as varchar)  + ''',''' + @PARENT_JOB  + ''')">' + cast(PJ.JOB_SEQ as varchar) + '</a>' as "Nro Operativo", 
			NOMBRE as "Nombre Operativo", CT.CALL_TYPE_DESC AS "Actividad", FECHA_INI as "Fecha Ini", 
			FECHA_FIN as "Fecha Fin", JEFE_OPERATIVO as "Jefe Operativo", REFERENTE_POLITICO as "Referente Politico", 
			ESTADO as "Estado", LOCALIDAD as "Localidad", DEPARTAMENTO as "Departamento", PROVINCIA as "Provincia" 
			from PHYSICAL_JOB PJ WITH (NOLOCK) 
			INNER JOIN ABM_OPERATIVOS as ABM WITH (NOLOCK) ON PJ.PKEY = ABM.PAR_KEY
			INNER JOIN ATTENDED_CUSTOMER AS ATT WITH (NOLOCK) ON PJ.PKEY = ATT.PKEY_JOB AND ATT.ATT_STATE_CODE <> 'CERRADO'
			INNER JOIN CALL_TYPE AS CT WITH (NOLOCK) ON ATT.CALL_TYPE_CODE = CT.CALL_TYPE_CODE
			WHERE PJ.JOB_STATE_CODE <> 'CLOSED'
			AND PJ.JOB_TYPE_CODE='ABM_OPERATIVO'
			AND PJ.ATT_GROUP_CODE=@GROUP_ID
			AND ATT.USER_ID = @USER_ID
			ORDER BY PJ.JOB_SEQ DESC
		END
		
	ELSE IF @GROUP_ID = 'OPERATIVO_ALTA' 
	
		BEGIN
 
			SELECT '<a href="javascript:restartTask(''' + ATT.PKEY_JOB + ''',''' + ATT.PKEY + ''',''' + cast(PJ.JOB_SEQ as varchar)  + ''','''')">' + cast(PJ.JOB_SEQ as varchar) + '</a>' as "Nro. Turno", 
			CUSTOMER_NAME as "Apellido y Nombre", c.CUST_PRIMARY_ID as "Documento", 
			CUST_SECONDARY_ID as "CUIL", CT.CALL_TYPE_DESC AS "Actividad"		
			from PHYSICAL_JOB PJ WITH (NOLOCK) 
			INNER JOIN CUSTOMER as C WITH (NOLOCK) ON PJ.PKEY_CUSTOMER = C.PKEY
			INNER JOIN ATTENDED_CUSTOMER AS ATT WITH (NOLOCK) ON PJ.PKEY = ATT.PKEY_JOB AND ATT.ATT_STATE_CODE <> 'CERRADO'
			INNER JOIN CALL_TYPE AS CT WITH (NOLOCK) ON ATT.CALL_TYPE_CODE = CT.CALL_TYPE_CODE
			WHERE PJ.JOB_STATE_CODE <> 'CLOSED'
			AND PJ.JOB_TYPE_CODE='OPERATIVO'
			AND PJ.ATT_GROUP_CODE=@GROUP_ID
			AND ATT.USER_ID = @USER_ID
			ORDER BY PJ.JOB_SEQ
					
		END
	
	ELSE IF @GROUP_ID = 'SISTEMAS_SENDEROS' 
		BEGIN
			SELECT '<a href="javascript:restartTask(''' + ATT.PKEY_JOB + ''',''' + ATT.PKEY + ''',''' + cast(PJ.JOB_SEQ as varchar)  + ''','''')">' + cast(PJ.JOB_SEQ as varchar) + '</a>' as "Nro. Trámite", 
			CUSTOMER_NAME as "Apellido y Nombre", c.CUST_PRIMARY_ID as "Documento", 
			CUST_SECONDARY_ID as "CUIL", CT.CALL_TYPE_DESC AS "Actividad", att.GROUP_CODE as Grupo, att.user_id as Usuario		
			from PHYSICAL_JOB PJ WITH (NOLOCK) 
			INNER JOIN CUSTOMER as C WITH (NOLOCK) ON PJ.PKEY_CUSTOMER = C.PKEY
			INNER JOIN ATTENDED_CUSTOMER AS ATT WITH (NOLOCK) ON PJ.PKEY = ATT.PKEY_JOB AND ATT.ATT_STATE_CODE <> 'CERRADO'
			INNER JOIN CALL_TYPE AS CT WITH (NOLOCK) ON ATT.CALL_TYPE_CODE = CT.CALL_TYPE_CODE
			WHERE PJ.JOB_STATE_CODE <> 'CLOSED'
			AND (PJ.JOB_TYPE_CODE='ALTA_AFILIADO' or  PJ.JOB_TYPE_CODE='ABM_TRASPASOS') 
			AND PJ.ATT_GROUP_CODE=@GROUP_ID
			AND ATT.USER_ID = @USER_ID
			ORDER BY PJ.JOB_SEQ
		END
	ELSE 		
		BEGIN
			SELECT '<a href="javascript:restartTask(''' + ATT.PKEY_JOB + ''',''' + ATT.PKEY + ''',''' + cast(PJ.JOB_SEQ as varchar)  + ''','''')">' + cast(PJ.JOB_SEQ as varchar) + '</a>' as "Nro. Trámite", 
			CD.CAT_DATA_DESC as "Tipo Trámite", CT.CALL_TYPE_DESC AS "Tarea",
			CD1.CAT_DATA_DESC AS "Programa",
			CUSTOMER_NAME as "Apellido y Nombre", c.CUST_PRIMARY_ID as "Documento", 
			CUST_SECONDARY_ID as "CUIL", G.NAME as Grupo, U.NAME as Usuario,
			CD2.CAT_DATA_DESC as "Estado Trámite", MOT.CAT_DATA_DESC AS "Motivo Estado",
			G1.NAME as "Enviado por Grupo", U1.NAME as "Enviado por Usuario"
			from PHYSICAL_JOB PJ WITH (NOLOCK) 
			INNER JOIN CUSTOMER as C WITH (NOLOCK) ON PJ.PKEY_CUSTOMER = C.PKEY
			INNER JOIN ATTENDED_CUSTOMER AS ATT WITH (NOLOCK) ON PJ.PKEY = ATT.PKEY_JOB AND ATT.ATT_STATE_CODE <> 'CERRADO'
			INNER JOIN CALL_TYPE AS CT WITH (NOLOCK) ON ATT.CALL_TYPE_CODE = CT.CALL_TYPE_CODE
			INNER JOIN TMP_ALTA AS TMP WITH (NOLOCK) ON TMP.PAR_KEY = PJ.PKEY
			LEFT JOIN  VW_MOTIVOS_TRAMITE AS MOT WITH (NOLOCK) ON TMP.MOTIVO_ESTADO = MOT.CAT_DATA_CODE
			LEFT JOIN CAT_DATA CD ON CD.CAT_DATA_CODE=TMP.TIPO_TRAMITE AND CD.PAR_KEY = '9B890C8A-5730-4759-AFC6-E2FF9C8A86AF'
			LEFT JOIN CAT_DATA CD1 ON CD1.CAT_DATA_CODE=TMP.PROGRAMA AND CD1.PAR_KEY = '471CBC61-039A-4E01-BBD1-CB696355D9D9'
			LEFT JOIN CAT_DATA CD2 ON CD2.CAT_DATA_CODE=TMP.ESTADO_ANALISIS AND CD2.PAR_KEY = 'C671FDEA-89F0-4061-B17F-EFBD7BD91CFC'
			LEFT JOIN GROUPS G ON att.GROUP_CODE = G.Id
			LEFT JOIN USERS U ON att.user_id=U.ID
			LEFT JOIN GROUPS G1 ON att.prev_groupcode = G1.Id
			LEFT JOIN USERS U1 ON att.prev_userid=U1.ID
			WHERE PJ.JOB_STATE_CODE <> 'CLOSED'
			AND PJ.JOB_TYPE_CODE='ALTA_AFILIADO'
			AND PJ.ATT_GROUP_CODE=@GROUP_ID
			AND ATT.USER_ID = @USER_ID
			ORDER BY PJ.JOB_SEQ desc	
					
			--SELECT '<a href="javascript:restartTask(''' + ATT.PKEY_JOB + ''',''' + ATT.PKEY + ''',''' + cast(PJ.JOB_SEQ as varchar)  + ''','''')">' + cast(PJ.JOB_SEQ as varchar) + '</a>' as "Nro. Trámite", 
			--CUSTOMER_NAME as "Apellido y Nombre", c.CUST_PRIMARY_ID as "Documento", 
			--CUST_SECONDARY_ID as "CUIL", CT.CALL_TYPE_DESC AS "Actividad", att.GROUP_CODE as Grupo, att.user_id as Usuario		
			--from PHYSICAL_JOB PJ WITH (NOLOCK) 
			--INNER JOIN CUSTOMER as C WITH (NOLOCK) ON PJ.PKEY_CUSTOMER = C.PKEY
			--INNER JOIN ATTENDED_CUSTOMER AS ATT WITH (NOLOCK) ON PJ.PKEY = ATT.PKEY_JOB AND ATT.ATT_STATE_CODE <> 'CERRADO'
			--INNER JOIN CALL_TYPE AS CT WITH (NOLOCK) ON ATT.CALL_TYPE_CODE = CT.CALL_TYPE_CODE
			--WHERE PJ.JOB_STATE_CODE <> 'CLOSED'
			--AND PJ.JOB_TYPE_CODE='ALTA_AFILIADO'
			--AND PJ.ATT_GROUP_CODE=@GROUP_ID
			--AND ATT.USER_ID = @USER_ID
			--ORDER BY PJ.JOB_SEQ
		
		END
				
 
END
 
