 
CREATE PROCEDURE [dbo].[EP_UPD_EQUIPO]
(@IPKEYJOB	AS VARCHAR(100))
AS
 
BEGIN	
 
	DECLARE @ID_EQ_SEL VARCHAR(36),
	@TIPO_EQ VARCHAR(50),
	@NRO_EQUIPO INT,
	@MARCA_MODELO VARCHAR(300),
	@NRO_SERIE VARCHAR(300),
	@ESTADO VARCHAR(50)
	
	
	SELECT @ID_EQ_SEL = EQ_SEL FROM TMT_CRON WHERE PAR_KEY = @IPKEYJOB;
	SELECT @TIPO_EQ= EQ_TIPO, @NRO_EQUIPO=EQ_NRO, @MARCA_MODELO=EQ_MARCA_MOD, @NRO_SERIE=EQ_NRO_SERIE, @ESTADO=EQ_ESTADO FROM TMT_CRON WHERE PAR_KEY=@IPKEYJOB;
 
	UPDATE EP_EQUIPOS
	SET TipoEquipo=@TIPO_EQ,
	NroEquipo=@NRO_EQUIPO,
	MarcaModelo=@MARCA_MODELO,
	NroSerie = @NRO_SERIE,
	Estado = @ESTADO	
	WHERE [ID]=@ID_EQ_SEL;
	 
 
END
