CREATE PROCEDURE [dbo].[SP_SYS_VALIDAR_NUEVO_CLIENTE]
@CustomerType VARCHAR(80),
@PrimaryId VARCHAR(80),
@SecondaryId VARCHAR(80),
@CustomerName VARCHAR(80)
AS
 
DECLARE @ERROR as VARCHAR(1)
SET @ERROR = '0'
IF (SELECT COUNT(*) FROM CUSTOMER WHERE CUST_TYPE_CODE= @CustomerType AND CUST_PRIMARY_ID = @PrimaryId) >= 1
BEGIN
            SET @ERROR = '1'
END
SELECT @ERROR as Error
RETURN
