 
CREATE PROCEDURE [dbo].[EP_EDIT_USUARIO]
(@IPKEYJOB	AS VARCHAR(100),
 @IUSERID	AS VARCHAR(100))
AS
 
BEGIN	
 
	DECLARE @ID_USER_SEL VARCHAR(50),
	@NEW_ID VARCHAR(50),
	@NEW_NAME VARCHAR(100),
	@NEW_EMAIL VARCHAR(100),
	@NEW_PASS VARCHAR(100),
	@STATE INT,
	@NEW_ESTADO_CUENTA VARCHAR(50)
	
	UPDATE TMT_CRON 
	SET [ACTION]='EDIT_USER'
	WHERE PAR_KEY= @IPKEYJOB;
 
	SELECT @ID_USER_SEL = ID_USER_SEL FROM TMT_CRON WHERE PAR_KEY = @IPKEYJOB;
	SELECT @NEW_ID= ID, @NEW_EMAIL=Email, @NEW_NAME=[Name], @NEW_PASS=[Password], @state=[State] FROM Users WHERE Id = @ID_USER_SEL;
	SELECT @NEW_ESTADO_CUENTA=CAT_DATA_CODE FROM CAT_DATA WHERE ATTR1 = @state and PAR_KEY='3ECEABE3-13FD-4779-ADE7-CDECF2EC3992';
 
	UPDATE TMT_CRON
	SET NEW_ID= @NEW_ID,
	NEW_EMAIL=@NEW_EMAIL,
	NEW_PASSWORD=@NEW_PASS,
	NEW_NAME=@NEW_NAME,
	NEW_ESTADO_CUENTA=@NEW_ESTADO_CUENTA
	WHERE PAR_KEY = @IPKEYJOB;
	 
 
END
