CREATE   PROCEDURE [dbo].[M_CONFIG_CMB_SECTOR_PADRE]
(@IPKEYJOB	AS VARCHAR(100))
AS
 
DECLARE @V_SECTOR_SEL VARCHAR(50)
DECLARE @V_NIVEL VARCHAR(50)
 
BEGIN
 
	SELECT	@V_SECTOR_SEL = ISNULL(ID_SECTOR_SEL,'')
	FROM	M_CONFIG
	WHERE	PAR_KEY = @IPKEYJOB
 
	--RECUPERO EL NIVEL DEL SECTOR SELECCIONADO PARA MODIFICAR--
	SELECT	@V_NIVEL = Id_nivel
	FROM	Sectores
	WHERE	Id_Sector = @V_SECTOR_SEL
 
	SELECT	'0'	AS CAT_DATA_CODE,
			'NIVEL 0 - Organizacion' AS CAT_DATA_DESC,
			'TRUE'
	--WHERE	@V_NIVEL - 1 <= '1'
	--WHERE	@V_NIVEL - 1 = '0'
	UNION ALL
	SELECT	ID_SECTOR	AS CAT_DATA_CODE,
			'NIVEL '+convert(varchar,id_nivel)+ ' - ' + Desc_Sector AS CAT_DATA_DESC,
			'TRUE'
	FROM	Sectores
	WHERE	id_sector NOT IN (29,30)
	AND		(Id_nivel <= @V_NIVEL)
	AND		Id_Sector <> @V_SECTOR_SEL
	ORDER BY CAT_DATA_DESC
 
END
