CREATE PROCEDURE PA_SYS_GENERAR_TRAM_DE_LISTA (@PSPKEY_CAMPAIGN AS VARCHAR(20), @PSPKEY_CUSTOMER AS VARCHAR(60), @PSTABLA_TRAMITE AS VARCHAR(30)) AS
 
-- =========================================================================================================================
-- AUTOR: TITO - ENGAGE SOFTWARE COMPANY
-- FECHA DE CREACIÓN: 21/11/2006
-- EDITOR: TITO - ENGAGE SOFTWARE COMPANY
-- FECHA DE EDICIÓN: 23/02/2011
-- TABLAS LEÍDAS: CUSTOMER, PHYSICAL_LIST, JOB_TYPE
-- TABLAS MODIFICADAS: PHYSICAL_JOB, ATTENDED_CUSTOMER, @LSTABLA_TRAMITE, PHYSICAL_JOB_ACTIONS
-- DESCRIPCIÓN: PROCEDIMIENTO PARA GENERAR UN TRÁMITE NUEVO Y SUS DATOS ASOCIADOS A PARTIR DE LOS PARÁMETROS RECIBIDOS.
-- CONSIDERACIONES:
-- 1. REGISTRA SÓLO LOS ERRORES EN LA TABLA EDA_REGISTRO_SUCESOS.
-- =========================================================================================================================
 
SET NOCOUNT ON;
SET XACT_ABORT ON;
 
-- DECLARACIÓN E INICIALIZACIÓN DE VARIABLES DE ERROR Y AUXILIARES.
DECLARE @LNERRORNUM AS INTEGER,
	@LNSEVERITY AS SMALLINT,
	@LNFILAS_AFEC AS INTEGER,
	@LDINICIO_OPE AS DATETIME,
	@LNDURACION AS INTEGER,
	@LSOPERA AS VARCHAR(30),
	@LSPROC AS VARCHAR(30),
	@LSTABLA AS VARCHAR(30),
	@LSERRORLOG AS VARCHAR(440),
	@LSERRORDESC AS VARCHAR(440),
	@LSSQL_CMD_CMD AS VARCHAR(4000)
;
SELECT 	@LNERRORNUM = 0,
	@LNSEVERITY = 16,
	@LNFILAS_AFEC = 0,
	@LDINICIO_OPE = GETDATE(),
	@LNDURACION = 0,
	@LSOPERA = 'EXECUTE',
	@LSPROC = OBJECT_NAME(@@PROCID),
	@LSTABLA = 'NINGUNA',
	@LSERRORLOG = @@SERVERNAME + '.' + DB_NAME() + '.' + USER_NAME() + '.' + OBJECT_NAME(@@PROCID) + ' - ',
	@LSERRORDESC = NULL,
	@LSSQL_CMD_CMD = NULL
;
 
-- DECLARACIÓN DE VARIABLES PARA OPERAR.
DECLARE	@LSSQL_CMD AS VARCHAR(4000),
	@LNCOUNT AS INTEGER,
	@LSPKEY AS VARCHAR(50),
	@LSCUST_PRIMARY_ID AS VARCHAR(50),
	@LSPKEY_JOB AS VARCHAR(100),
	@LSJOB_STATE_CODE AS VARCHAR(20),
	@LSATT_STATE_CODE AS VARCHAR(20),
	@LDJOB_STATE_DATE AS DATETIME,
	@LSORIGIN_IDR AS VARCHAR(10),
	@LSCAMPAIGN_IDR AS VARCHAR(10),
	@LSPROGRAMMED_IDR AS VARCHAR(10),
	@LSMEDIA_ID1 AS VARCHAR(50),
	@LSUSER_ID AS VARCHAR(30),
	@LSJOB_TYPE_CODE AS VARCHAR(20),
	@LSJOB_PRIORITY AS VARCHAR(20),
	@LSCALL_TYPE_CODE AS VARCHAR(20),
	@LSJOB_GROUP_CODE AS VARCHAR(100),
	@LSATT_GROUP_CODE AS VARCHAR(50),
	@LNATTEMPTS AS NUMERIC(18, 0),
	@LSJOB_RESULT_CODE AS VARCHAR(20),
	@LDJOB_MAX_END_DATE AS DATETIME,
	@LSTS_USER_ID AS VARCHAR(30),
	@LSPHYSICAL_LIST_PKEY AS VARCHAR(20),
	@LSCUSTOMER_PKEY AS VARCHAR(60),
	@LSTABLA_TRAMITE AS VARCHAR(30),
	@LSATT_RESULT_CODE AS VARCHAR(20),
	@LSREASON_CODE AS VARCHAR(20),
	@LSFECHAHORALISTA AS VARCHAR(20)
;
SELECT	@LSSQL_CMD = NULL,
	@LNCOUNT = 0,
	@LSPKEY = NULL,
	@LSCUST_PRIMARY_ID = NULL,
	@LSPKEY_JOB = NULL,
	@LSJOB_STATE_CODE = 'NOTWORKED',
	@LSATT_STATE_CODE = 'NOTWORKED',
	@LDJOB_STATE_DATE = GETDATE(),
	@LSORIGIN_IDR = 'AUTO',
	@LSCAMPAIGN_IDR = 'SI',
	@LSPROGRAMMED_IDR = 'NO',
	@LSMEDIA_ID1 = '0',
	@LSUSER_ID = NULL,
	@LSJOB_TYPE_CODE = NULL,
	@LSJOB_PRIORITY = NULL,
	@LSCALL_TYPE_CODE = NULL,
	@LSJOB_GROUP_CODE = NULL,
	@LSATT_GROUP_CODE = NULL,
	@LNATTEMPTS = 0,
	@LSJOB_RESULT_CODE = NULL,
	@LDJOB_MAX_END_DATE = CONVERT(DATETIME, '2049-12-31 23:59:59', 120), -- CALCULAR JOB_MAX_END_DATE O PONER NULL (SIN VENCIMIENTO).
	@LSTS_USER_ID = 'ADMINISTRADOR',
	@LSPHYSICAL_LIST_PKEY = NULLIF(@PSPKEY_CAMPAIGN, ''),
	@LSCUSTOMER_PKEY = NULLIF(@PSPKEY_CUSTOMER, ''),
	@LSTABLA_TRAMITE = NULLIF(@PSTABLA_TRAMITE, ''),
	@LSATT_RESULT_CODE = NULL,
	@LSREASON_CODE = NULL,
	@LSFECHAHORALISTA = CONVERT(VARCHAR, GETDATE(), 112) + REPLACE(CONVERT(VARCHAR, GETDATE(), 108), ':', '') -- 20070102151600
;
 
-- DECLARO LA TRANSACCIÓN.
BEGIN TRANSACTION
 
IF (@LSPHYSICAL_LIST_PKEY IS NOT NULL AND @LSCUSTOMER_PKEY IS NOT NULL AND @LSTABLA_TRAMITE IS NOT NULL) BEGIN
 
	-- OBTIENE EL CUST_PRIMARY_ID DEL CLIENTE ENVIADO POR PARÁMETRO.
	SELECT	@LSCUST_PRIMARY_ID = CUST_PRIMARY_ID
	FROM	CUSTOMER
	WHERE	(PKEY = @LSCUSTOMER_PKEY);
 
	-- OBTIENE DATOS DE LA LISTA FÍSICA ENVIADA POR PARÁMETRO.
	SELECT	@LSJOB_GROUP_CODE = GROUP_CODE,
		@LSATT_GROUP_CODE = ATT_GROUP_CODE,
		@LSJOB_TYPE_CODE = JOB_TYPE_CODE,
		@LSCALL_TYPE_CODE = CALL_TYPE_CODE
	FROM	PHYSICAL_LIST
	WHERE	(PKEY = @LSPHYSICAL_LIST_PKEY);
 
	-- OBTIENE DATOS DEL TIPO DE TRÁMITE CON EL QUE SE RELACIONA LA LISTA FÍSICA.
	SELECT	@LSJOB_PRIORITY = JOB_PRIORITY
	FROM	JOB_TYPE
	WHERE	(JOB_TYPE_CODE = @LSJOB_TYPE_CODE);
 
	-- OBTIENE LA PKEY DE PHYSICAL_JOB.
	SET @LSPKEY_JOB = @LSCUST_PRIMARY_ID + @LSPHYSICAL_LIST_PKEY + @LSFECHAHORALISTA;
 
	-- INSERTA UN TRÁMITE NO TRABAJADO EN PHYSICAL_JOB, PERTENECIENTE A UN CLIENTE DE LA LISTA FÍSICA ENVIADA.
	INSERT INTO	PHYSICAL_JOB (PKEY, CUST_PRIMARY_ID, JOB_STATE_CODE, JOB_STATE_DATE, ORIGIN_IDR, CAMPAIGN_IDR, PKEY_CAMPAIGN, PROGRAMMED_IDR, MEDIA_ID1, USER_ID, JOB_TYPE_CODE, JOB_GROUP_CODE, CALL_TYPE_CODE, ATT_GROUP_CODE, ATT_STATE_CODE, ATTEMPTS, JOB_RESULT_CODE, JOB_MAX_END_DATE, PKEY_CUSTOMER, JOB_PRIORITY, TS_BEGIN, TS_END, TS_USER_ID)
	VALUES		(@LSPKEY_JOB, @LSCUST_PRIMARY_ID, @LSJOB_STATE_CODE, @LDJOB_STATE_DATE, @LSORIGIN_IDR, @LSCAMPAIGN_IDR, @LSPHYSICAL_LIST_PKEY, @LSPROGRAMMED_IDR, @LSMEDIA_ID1, @LSUSER_ID, @LSJOB_TYPE_CODE, @LSJOB_GROUP_CODE, @LSCALL_TYPE_CODE, @LSATT_GROUP_CODE, @LSATT_STATE_CODE, @LNATTEMPTS, @LSJOB_RESULT_CODE, @LDJOB_MAX_END_DATE, @LSCUSTOMER_PKEY, @LSJOB_PRIORITY, @LDJOB_STATE_DATE, @LDJOB_STATE_DATE, @LSTS_USER_ID);
	SELECT @LSOPERA = 'INSERT', @LSTABLA = 'PHYSICAL_JOB', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
 
	-- OBTIENE LA PKEY DE ATTENDED_CUSTOMER.
	EXECUTE @LNERRORNUM = PA_SYS_OBTIENE_PKEY @PSTABLA = 'ATTENDED_CUSTOMER', @PSPKEY = @LSPKEY OUTPUT;
	SELECT @LSOPERA = 'PA_SYS_OBTIENE_PKEY', @LSTABLA = 'ATTENDED_CUSTOMER', @LNFILAS_AFEC = @@ROWCOUNT;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
 
	-- INSERTA UNA ACTIVIDAD PARA EL TRÁMITE NO TRABAJADO DE PHYSICAL_JOB EN ATTENDED_CUSTOMER, PERTENECIENTE A UN CLIENTE DE LA LISTA FÍSICA ENVIADA.
	INSERT INTO	ATTENDED_CUSTOMER (PKEY, CUST_PRIMARY_ID, CALL_TYPE_CODE, ATT_STATE_CODE, ATT_STATE_DATE_TIME, ATT_RESULT_CODE, REASON_CODE, JOB_TYPE_CODE, PKEY_JOB, GROUP_CODE, PKEY_CAMPAIGN, PKEY_CUSTOMER, ATT_MAX_END_DATE, PROGRAMMED_IDR, USER_ID, MEDIA_ID1, TS_BEGIN, TS_END, TS_USER_ID)
	VALUES		(@LSPKEY, @LSCUST_PRIMARY_ID, @LSCALL_TYPE_CODE, @LSATT_STATE_CODE, @LDJOB_STATE_DATE, @LSATT_RESULT_CODE, @LSREASON_CODE, @LSJOB_TYPE_CODE, @LSPKEY_JOB, @LSATT_GROUP_CODE, @LSPHYSICAL_LIST_PKEY, @LSCUSTOMER_PKEY, @LDJOB_MAX_END_DATE, @LSPROGRAMMED_IDR, @LSUSER_ID, @LSMEDIA_ID1, @LDJOB_STATE_DATE, @LDJOB_STATE_DATE, @LSTS_USER_ID);
	SELECT @LSOPERA = 'INSERT', @LSTABLA = 'ATTENDED_CUSTOMER', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
 
	-- ACTUALIZA LA CLAVE DE LA ACTIVIDAD EN EL TRÁMITE.
	UPDATE	PHYSICAL_JOB
	SET	PKEY_ATTENDED_CUSTOMER = @LSPKEY
	WHERE	(PKEY = @LSPKEY_JOB);
	SELECT @LSOPERA = 'UPDATE', @LSTABLA = 'PHYSICAL_JOB', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
 
	-- OBTIENE LA PKEY DE LA ENTIDAD ASOCIADA AL TRÁMITE.
	EXECUTE @LNERRORNUM = PA_SYS_OBTIENE_PKEY @PSTABLA = @LSTABLA_TRAMITE, @PSPKEY = @LSPKEY OUTPUT;
	SELECT @LSOPERA = 'PA_SYS_OBTIENE_PKEY', @LSTABLA = @LSTABLA_TRAMITE, @LNFILAS_AFEC = @@ROWCOUNT;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
 
	-- PREPARA LA SENTENCIA DE INSERCIÓN EN LA ENTIDAD ASOCIADA AL TRÁMITE.
	SET @LSSQL_CMD = 'INSERT INTO ' + @LSTABLA_TRAMITE + ' (PKEY, PAR_KEY, TS_BEGIN, TS_END, TS_USER_ID) VALUES (' + CHAR(39) + @LSPKEY + CHAR(39) + ', ' + CHAR(39) + @LSPKEY_JOB + CHAR(39) + ', CONVERT(DATETIME, ' + CHAR(39) + CONVERT(VARCHAR, @LDJOB_STATE_DATE, 120) + CHAR(39) + ', 120), CONVERT(DATETIME, ' + CHAR(39) + CONVERT(VARCHAR, @LDJOB_STATE_DATE, 120) + CHAR(39) + ', 120), ' + CHAR(39) + @LSTS_USER_ID + CHAR(39) + ')';
 
	-- EJECUTA LA SENTENCIA DE INSERCIÓN EN LA ENTIDAD ASOCIADA AL TRÁMITE.
	EXECUTE (@LSSQL_CMD);
	SELECT @LSOPERA = 'INSERT', @LSTABLA = @LSTABLA_TRAMITE, @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
 
	/*
	-- PREPARAR INSERCIÓN DE REGLAS DE ESCALAMIENTO EN UN FUTURO RELEASE DEL PROCEDIMIENTO.
	SELECT	COUNT(1) CANTREGLAS
	FROM	JOB_ACTIONS
	WHERE	JOB_TYPE_CODE = 'TESTING'
		AND CALL_TYPE_CODE = 'TESTING_2'
 
	SELECT	PKEY
	FROM	JOB_ACTIONS
	WHERE	JOB_TYPE_CODE = 'TESTING'
		AND CALL_TYPE_CODE = 'TESTING_2'
		ORDER BY ACTION_INDEX
 
	INSERT INTO	PHYSICAL_JOB_ACTIONS (PKEY, PAR_KEY, ACTION_STATUS, JOB_TYPE_CODE, CALL_TYPE_CODE, ACTION_CODE, ACTION_INDEX, FORMULA, ACTION_TYPE, USER_ID, ACTION_KEY, TS_BEGIN, TS_END, TS_USER_ID, CALL_RESULT_CODE, PKEY_JOB_ACTIONS, PKEY_ATT_CUST, SP_PRE, SP_POST, NEXTTIME, GAPMINUTES, EVALUATE_IMMED, STARTTIME, FINISHTIME)
		SELECT	RIGHT( RTRIM('000000000' +CONVERT(VARCHAR, 563386 + JOB.JOB_SEQ - 349844)), 10)+'_'+'69',
			ATT.PKEY_JOB,
			'OFF',
			ATT.JOB_TYPE_CODE,
			ATT.CALL_TYPE_CODE,
			ACT.ACTION_CODE,
			ACT.ACTION_INDEX,
			ACT.FORMULA,
			ACT.ACTION_TYPE,
			ATT.USER_ID,
			RTRIM(ATT.PKEY_JOB) + RTRIM(ACT.PKEY),
			GETDATE(),
			GETDATE(),
			ATT.TS_USER_ID,
			ACT.CALL_RESULT_CODE,
			ACT.PKEY,
			ATT.PKEY,
			ACT.SP_PRE,
			ACT.SP_POST,
			GETDATE(),
			ACT.GAPMINUTES,
			0,
			ACT.STARTTIME,
			ACT.FINISHTIME
		FROM	ATTENDED_CUSTOMER ATT,
			JOB_ACTIONS ACT,
			PHYSICAL_JOB JOB
		WHERE	ATT.JOB_TYPE_CODE = 'TESTING'
			AND ATT.PKEY_CAMPAIGN = '0000000077_106'
			AND ATT.CALL_TYPE_CODE = 'TESTING_2'
			AND ATT.ATT_STATE_CODE IN ('NOTWORKED', 'Abierto')
			AND ACT.JOB_TYPE_CODE = JOB.JOB_TYPE_CODE
			AND ACT.CALL_TYPE_CODE = ATT.CALL_TYPE_CODE
			AND ACT.PKEY = '0000000033_67'
			AND JOB.PKEY = ATT.PKEY_JOB
 
	-- FIN ESCALAMIENTO
	*/
END;
 
FALLO:
-- REGISTRO DE SUCESOS Y CONTROL DE FIN DE PROCEDIMIENTO. CONCLUYE LA TRANSACCIÓN SI TODO FUE EXITOSO.
SELECT @LNDURACION = DATEDIFF(SECOND, @LDINICIO_OPE, GETDATE()), @LNSEVERITY = ISNULL(EM.SEVERITY, 16), @LSERRORDESC = 'ERROR ' + CONVERT(VARCHAR, ISNULL(EM.ERROR, 0)) + ' - ' + ISNULL(EM.DESCRIPTION, ' ') FROM MASTER.DBO.SYSMESSAGES EM WHERE (EM.ERROR = @LNERRORNUM);
IF (@LNERRORNUM <> 0) BEGIN
	-- NOTIFICACIÓN EN EL REGISTRO DE SQL SERVER.
	SET @LSERRORLOG = @LSERRORLOG + CASE WHEN (ISNULL(CHARINDEX('%', @LSERRORDESC), 0) > 0) THEN RTRIM(LEFT(@LSERRORDESC, 11)) ELSE @LSERRORDESC END;
	-- DESHACE LA TRANSACCIÓN COMPLETA SI LA OPERACIÓN FALLÓ.
	IF (@@TRANCOUNT > 0) ROLLBACK TRANSACTION;
	EXECUTE @LNERRORNUM = PA_SYS_REGISTRO_SUCESOS_INSERT @PSPROCEDIMIENTO_1 = @LSPROC, @PSTABLA_2 = @LSTABLA, @PNFILAS_AFECTADAS_3 = @LNFILAS_AFEC, @PSOPERACION_4 = @LSOPERA, @PNDURACION_5 = @LNDURACION, @PSRESULTADO_6 = @LSERRORDESC, @PSSQL_CMD_7 = @LSERRORDESC;
	RAISERROR(@LSERRORLOG, @LNSEVERITY, -1) WITH NOWAIT;
END
ELSE BEGIN
	-- EXECUTE @LNERRORNUM = PA_SYS_REGISTRO_SUCESOS_INSERT @PSPROCEDIMIENTO_1 = @LSPROC, @PSTABLA_2 = @LSTABLA, @PNFILAS_AFECTADAS_3 = @LNFILAS_AFEC, @PSOPERACION_4 = @LSOPERA, @PNDURACION_5 = @LNDURACION, @PSRESULTADO_6 = @LSERRORDESC, @PSSQL_CMD_7 = @LSERRORDESC;
	IF (@@TRANCOUNT > 0) COMMIT TRANSACTION;
END;
RETURN;
