CREATE PROCEDURE [dbo].[HOME_ADD_DET_VIATICO]
(@IPKEYJOB	AS VARCHAR(100),
 @IAGENTE	AS VARCHAR(100),
 @OCODE		AS VARCHAR(2) OUTPUT,
 @OMENSAJE	AS VARCHAR(400) OUTPUT)
AS
 
DECLARE	@VPROYECTO				VARCHAR(50),
		@VSERVICIO				VARCHAR(50),
		@VPROYECTO_SERV			VARCHAR(50),
		@VTIPO_SERV				VARCHAR(50),
		@VPROVEEDOR_ID			VARCHAR(50),
		@VTIPO_PROV				VARCHAR(50),
		@VCANT					INT,
		@VAGENDA_ID				VARCHAR(50),
		@VERROR					VARCHAR(50),
		@VID_VIATICO			VARCHAR(50),
		@VRESERVA				VARCHAR(100),
		@VFECHA					DATETIME,
		@VVUELO					VARCHAR(50),
		@VORIGEN				VARCHAR(100),
		@VDESTINO				VARCHAR(100),
		@VSALIDA				VARCHAR(100),
		@VLLEGADA				VARCHAR(100),
		@VLOCAL					VARCHAR(100),
		@VFINGRESO				DATETIME,
		@VFEGRESO				DATETIME,
		@VFPARTIDA				DATETIME,
		@VFLLEGADA				DATETIME,
		@VPAGA_CONSULTOR		VARCHAR(50),
		@VPAGA_CONSULTORA		VARCHAR(50),
		@VRENDICION_CLIENTE		VARCHAR(50),
		@VKMS					VARCHAR(50),
		@VPEAJES				VARCHAR(50),
		@VID_SELEC				VARCHAR(100)
		
BEGIN	
 
	SET @OCODE = '0'
	SET @OMENSAJE = ''
 
	SELECT	@VAGENDA_ID = ISNULL(AGENDA_ID,''),
			@VERROR = ISNULL(ERROR,''),
			@VID_VIATICO = ISNULL(HOJA_RUTA_ID,''),
			@VTIPO_PROV = ISNULL(TIPO_PROV,''),
			@VID_SELEC	= ISNULL(ID_DETALLE,'')
	FROM	XAGENDA
	WHERE	PAR_KEY = @IPKEYJOB
 
	SELECT	@VPROYECTO  = ID_PROYECTO,
			@VSERVICIO  = ID_SERVICIO
	FROM	LK_AGENDA
	WHERE	ID_AGENDA = @VAGENDA_ID
 
	SELECT	@VRESERVA = ISNULL(DET_PROV_RESERVA,''),
			@VFECHA = ISNULL(DET_PROV_FECHA,''),
			@VVUELO = ISNULL(DET_PROV_VUELO,''),
			@VORIGEN = ISNULL(DET_PROV_ORIGEN,''),
			@VDESTINO = ISNULL(DET_PROV_DESTINO,''),
			@VSALIDA = ISNULL(DET_PROV_SALIDA,''),
			@VLLEGADA = ISNULL(DET_PROV_LLEGADA,''),
			@VLOCAL = ISNULL(DET_PROV_LOCAL,''),
			@VFINGRESO = ISNULL(DET_PROV_FINGRESO,''),
			@VFEGRESO = ISNULL(DET_PROV_FEGRESO,''),
			@VFPARTIDA = ISNULL(DET_PROV_FPARTIDA,''),
			@VFLLEGADA = ISNULL(DET_PROV_FLLEGADA,''),
			@VPAGA_CONSULTOR = ISNULL(PAGA_CONSULTOR,''),
			@VPAGA_CONSULTORA = ISNULL(PAGA_CONSULTORA,''),
			@VRENDICION_CLIENTE = ISNULL(RENDICION_CLIENTE,''),
			@VKMS = ISNULL(DET_PROV_KMS,''),
			@VPEAJES = ISNULL(DET_PROV_PEAJES,'')
	FROM	XAGENDA
	WHERE	PAR_KEY = @IPKEYJOB
 
	
	IF (@VTIPO_PROV = 'AVION' OR @VTIPO_PROV = 'MICRO') BEGIN
 
		IF (@VFECHA = '') BEGIN
			SET @OCODE = '1'
			
			UPDATE	XAGENDA
			SET		ERROR = 'SI',
					DESC_ERROR = 'Debe Completar el Campo Fecha'
			WHERE	PAR_KEY = @IPKEYJOB
			RETURN
		END
			
		IF (@VID_SELEC = '') BEGIN
			
			INSERT INTO LK_PROYECTO_VIATICOS_DET
			(ID_PROYECTO_VIATICOS,ID_AGENDA,DET_PROV_RESERVA,DET_PROV_FECHA,DET_PROV_VUELO,DET_PROV_ORIGEN,DET_PROV_DESTINO,
				DET_PROV_SALIDA,DET_PROV_LLEGADA,DET_PROV_LOCAL,DET_PROV_FINGRESO,DET_PROV_FEGRESO,DET_PROV_FPARTIDA,DET_PROV_FLLEGADA,
				PAGA_CONSULTOR,PAGA_CONSULTORA,RENDICION_CLIENTE)
			VALUES (@VID_VIATICO, @VAGENDA_ID, @VRESERVA, @VFECHA, @VVUELO, @VORIGEN, @VDESTINO,
			@VSALIDA, @VLLEGADA, @VLOCAL, @VFINGRESO, @VFEGRESO, @VFPARTIDA, @VFLLEGADA,
			@VPAGA_CONSULTOR, @VPAGA_CONSULTORA, @VRENDICION_CLIENTE)
			
		END ELSE BEGIN
				
			UPDATE	LK_PROYECTO_VIATICOS_DET
			SET		DET_PROV_RESERVA = @VRESERVA, 
					DET_PROV_FECHA = @VFECHA,
					DET_PROV_VUELO = @VVUELO,
					DET_PROV_ORIGEN = @VORIGEN,
					DET_PROV_DESTINO = @VDESTINO,
					DET_PROV_SALIDA = @VSALIDA,
					DET_PROV_LLEGADA = @VLLEGADA,
					PAGA_CONSULTOR = @VPAGA_CONSULTOR,
					PAGA_CONSULTORA = @VPAGA_CONSULTORA,
					RENDICION_CLIENTE = @VRENDICION_CLIENTE
			WHERE	ID_PROYECTO_VIATICOS_DET = @VID_SELEC
 
		END
			
	END
 
	IF (@VTIPO_PROV = 'HOTEL') BEGIN
 
		IF (@VFINGRESO = '') BEGIN
			SET @OCODE = '1'
			
			UPDATE	XAGENDA
			SET		ERROR = 'SI',
					DESC_ERROR = 'Debe Completar el Campo Fecha Ingreso'
			WHERE	PAR_KEY = @IPKEYJOB
			RETURN
		END
 
		IF (@VFEGRESO = '') BEGIN
			SET @OCODE = '1'
			
			UPDATE	XAGENDA
			SET		ERROR = 'SI',
					DESC_ERROR = 'Debe Completar el Campo Fecha Egreso'
			WHERE	PAR_KEY = @IPKEYJOB
			RETURN
		END
 
		IF (@VID_SELEC = '') BEGIN
 
			INSERT INTO LK_PROYECTO_VIATICOS_DET
			(ID_PROYECTO_VIATICOS,ID_AGENDA,DET_PROV_RESERVA,DET_PROV_FECHA,DET_PROV_VUELO,DET_PROV_ORIGEN,DET_PROV_DESTINO,
				DET_PROV_SALIDA,DET_PROV_LLEGADA,DET_PROV_LOCAL,DET_PROV_FINGRESO,DET_PROV_FEGRESO,DET_PROV_FPARTIDA,DET_PROV_FLLEGADA,
				PAGA_CONSULTOR,PAGA_CONSULTORA,RENDICION_CLIENTE)
			VALUES (@VID_VIATICO, @VAGENDA_ID, @VRESERVA, @VFECHA, @VVUELO, @VORIGEN, @VDESTINO,
			@VSALIDA, @VLLEGADA, @VLOCAL, @VFINGRESO, @VFEGRESO, @VFPARTIDA, @VFLLEGADA,
			@VPAGA_CONSULTOR, @VPAGA_CONSULTORA, @VRENDICION_CLIENTE)
		
		END ELSE BEGIN
 
			UPDATE	LK_PROYECTO_VIATICOS_DET
			SET		DET_PROV_LOCAL = @VLOCAL, 
					DET_PROV_FINGRESO = @VFINGRESO,
					DET_PROV_FEGRESO = @VFEGRESO,
					PAGA_CONSULTOR = @VPAGA_CONSULTOR,
					PAGA_CONSULTORA = @VPAGA_CONSULTORA,
					RENDICION_CLIENTE = @VRENDICION_CLIENTE
			WHERE	ID_PROYECTO_VIATICOS_DET = @VID_SELEC
 
		END
 
	END
 
	IF (@VTIPO_PROV = 'TAXI' OR @VTIPO_PROV = 'REMIS') BEGIN
 
		IF (@VFPARTIDA = '') BEGIN
			SET @OCODE = '1'
			
			UPDATE	XAGENDA
			SET		ERROR = 'SI',
					DESC_ERROR = 'Debe Completar el Campo Fecha Partida'
			WHERE	PAR_KEY = @IPKEYJOB
			RETURN
		END
 
		IF (@VFLLEGADA = '') BEGIN
			SET @OCODE = '1'
			
			UPDATE	XAGENDA
			SET		ERROR = 'SI',
					DESC_ERROR = 'Debe Completar el Campo Fecha Llegada'
			WHERE	PAR_KEY = @IPKEYJOB
			RETURN
		END
 
		IF (@VID_SELEC = '') BEGIN
 
			INSERT INTO LK_PROYECTO_VIATICOS_DET
			(ID_PROYECTO_VIATICOS,ID_AGENDA,DET_PROV_RESERVA,DET_PROV_FECHA,DET_PROV_VUELO,DET_PROV_ORIGEN,DET_PROV_DESTINO,
				DET_PROV_SALIDA,DET_PROV_LLEGADA,DET_PROV_LOCAL,DET_PROV_FINGRESO,DET_PROV_FEGRESO,DET_PROV_FPARTIDA,DET_PROV_FLLEGADA,
				PAGA_CONSULTOR,PAGA_CONSULTORA,RENDICION_CLIENTE)
			VALUES (@VID_VIATICO, @VAGENDA_ID, @VRESERVA, @VFECHA, @VVUELO, @VORIGEN, @VDESTINO,
			@VSALIDA, @VLLEGADA, @VLOCAL, @VFINGRESO, @VFEGRESO, @VFPARTIDA, @VFLLEGADA,
			@VPAGA_CONSULTOR, @VPAGA_CONSULTORA, @VRENDICION_CLIENTE)
		
		END ELSE BEGIN
 
			UPDATE	LK_PROYECTO_VIATICOS_DET
			SET		DET_PROV_RESERVA = @VRESERVA, 
					DET_PROV_FECHA = @VFECHA,
					DET_PROV_VUELO = @VVUELO,
					DET_PROV_ORIGEN = @VORIGEN,
					DET_PROV_DESTINO = @VDESTINO,
					DET_PROV_FPARTIDA = @VFPARTIDA,
					DET_PROV_SALIDA = @VSALIDA,
					DET_PROV_FLLEGADA = @VFLLEGADA,
					DET_PROV_LLEGADA = @VLLEGADA,
					PAGA_CONSULTOR = @VPAGA_CONSULTOR,
					PAGA_CONSULTORA = @VPAGA_CONSULTORA,
					RENDICION_CLIENTE = @VRENDICION_CLIENTE
			WHERE	ID_PROYECTO_VIATICOS_DET = @VID_SELEC
 
		END
			
	END
 
	IF (@VTIPO_PROV = 'AUTO') BEGIN
 
		IF (@VFECHA = '') BEGIN
			SET @OCODE = '1'
			
			UPDATE	XAGENDA
			SET		ERROR = 'SI',
					DESC_ERROR = 'Debe Completar el Campo Fecha'
			WHERE	PAR_KEY = @IPKEYJOB
			RETURN
		END
 
		IF (@VID_SELEC = '') BEGIN
 
			INSERT INTO LK_PROYECTO_VIATICOS_DET
			(ID_PROYECTO_VIATICOS,ID_AGENDA,DET_PROV_RESERVA,DET_PROV_FECHA,DET_PROV_VUELO,DET_PROV_ORIGEN,DET_PROV_DESTINO,
				DET_PROV_SALIDA,DET_PROV_LLEGADA,DET_PROV_LOCAL,DET_PROV_FINGRESO,DET_PROV_FEGRESO,DET_PROV_FPARTIDA,DET_PROV_FLLEGADA,
				PAGA_CONSULTOR,PAGA_CONSULTORA,RENDICION_CLIENTE, DET_PROV_KMS, DET_PROV_PEAJES)
			VALUES (@VID_VIATICO, @VAGENDA_ID, @VRESERVA, @VFECHA, @VVUELO, @VORIGEN, @VDESTINO,
			@VSALIDA, @VLLEGADA, @VLOCAL, @VFINGRESO, @VFEGRESO, @VFPARTIDA, @VFLLEGADA,
			@VPAGA_CONSULTOR, @VPAGA_CONSULTORA, @VRENDICION_CLIENTE, @VKMS, @VPEAJES)
 
		END ELSE BEGIN
 
			UPDATE	LK_PROYECTO_VIATICOS_DET
			SET		DET_PROV_FECHA = @VFECHA,
					DET_PROV_KMS = @VKMS,
					DET_PROV_PEAJES = @VPEAJES,
					PAGA_CONSULTOR = @VPAGA_CONSULTOR,
					PAGA_CONSULTORA = @VPAGA_CONSULTORA,
					RENDICION_CLIENTE = @VRENDICION_CLIENTE
			WHERE	ID_PROYECTO_VIATICOS_DET = @VID_SELEC
		END
			
	END
 
	IF (@VTIPO_PROV = 'ALQUILER') BEGIN
 
		IF (@VFPARTIDA = '') BEGIN
			SET @OCODE = '1'
			
			UPDATE	XAGENDA
			SET		ERROR = 'SI',
					DESC_ERROR = 'Debe Completar el Campo Fecha Desde'
			WHERE	PAR_KEY = @IPKEYJOB
			RETURN
		END
 
		IF (@VFLLEGADA = '') BEGIN
			SET @OCODE = '1'
			
			UPDATE	XAGENDA
			SET		ERROR = 'SI',
					DESC_ERROR = 'Debe Completar el Campo Fecha Hasta'
			WHERE	PAR_KEY = @IPKEYJOB
			RETURN
		END
 
		IF (@VID_SELEC = '') BEGIN
			INSERT INTO LK_PROYECTO_VIATICOS_DET
			(ID_PROYECTO_VIATICOS,ID_AGENDA,DET_PROV_RESERVA,DET_PROV_FECHA,DET_PROV_VUELO,DET_PROV_ORIGEN,DET_PROV_DESTINO,
				DET_PROV_SALIDA,DET_PROV_LLEGADA,DET_PROV_LOCAL,DET_PROV_FINGRESO,DET_PROV_FEGRESO,DET_PROV_FPARTIDA,DET_PROV_FLLEGADA,
				PAGA_CONSULTOR,PAGA_CONSULTORA,RENDICION_CLIENTE)
			VALUES (@VID_VIATICO, @VAGENDA_ID, @VRESERVA, @VFECHA, @VVUELO, @VORIGEN, @VDESTINO,
			@VSALIDA, @VLLEGADA, @VLOCAL, @VFINGRESO, @VFEGRESO, @VFPARTIDA, @VFLLEGADA,
			@VPAGA_CONSULTOR, @VPAGA_CONSULTORA, @VRENDICION_CLIENTE)
 
		END ELSE BEGIN
 
			UPDATE	LK_PROYECTO_VIATICOS_DET
			SET		DET_PROV_ORIGEN = @VORIGEN,
					DET_PROV_DESTINO = @VDESTINO,
					DET_PROV_FPARTIDA = @VFPARTIDA,
					DET_PROV_FLLEGADA = @VFLLEGADA,
					DET_PROV_LLEGADA = @VLLEGADA,
					PAGA_CONSULTOR = @VPAGA_CONSULTOR,
					PAGA_CONSULTORA = @VPAGA_CONSULTORA,
					RENDICION_CLIENTE = @VRENDICION_CLIENTE
			WHERE	ID_PROYECTO_VIATICOS_DET = @VID_SELEC
 
		END
			
	END
 
	IF (@OCODE = '0') BEGIN
		UPDATE	XAGENDA
		SET		ERROR = NULL, DESC_ERROR = NULL
		WHERE	PAR_KEY = @IPKEYJOB
	END
END
 
