CREATE   PROCEDURE [dbo].[SV_01_ADD_EMPLEADO_APT]
(@IPKEYJOB	AS VARCHAR(100),
 @IAGENTE	AS VARCHAR(100),
 @OCODE		AS VARCHAR(2) OUTPUT,
 @OMENSAJE	AS VARCHAR(400) OUTPUT)
AS
 
DECLARE @VOBSERVACION	VARCHAR(400),
		@VEMPLEADO		VARCHAR(50),
		@VAPTITUD		VARCHAR(50),
		@VSERVICIO		VARCHAR(50),
		@VCALIFICACION	VARCHAR(50),
		@VCLAVE			VARCHAR(100),
		@VERROR		VARCHAR(50),
		@VCANT		INT
 
BEGIN	
 
	SET @OCODE = '0'
	SET @OMENSAJE = ''
 
	SELECT	@VEMPLEADO	= ISNULL(EMPLEADO,''),
			@VAPTITUD = ISNULL(APTITUD,''),
			@VSERVICIO = ISNULL(TIPO_SERVICIO,''),
			@VCALIFICACION = ISNULL(CALIFICACION,''),
			@VOBSERVACION = ISNULL(OBSERVACION,''),
			@VCLAVE = ISNULL(CLAVE,'')
	FROM	TMT_SV_01
	WHERE	PAR_KEY = @IPKEYJOB
 
	IF (@VEMPLEADO = '') BEGIN
		SET @OCODE = '1'
		SET @OMENSAJE = 'ERROR'
			
		UPDATE	TMT_SV_01
		SET		ERROR = 'SI', DESC_ERROR = 'Debe Completar el Campo Empleado/Consultor'
		WHERE	PAR_KEY = @IPKEYJOB
		RETURN
	END
 
	IF (@VAPTITUD = '') BEGIN
		SET @OCODE = '1'
		SET @OMENSAJE = 'ERROR'
			
		UPDATE	TMT_SV_01
		SET		ERROR = 'SI', DESC_ERROR = 'Debe Completar el Campo Aptitud'
		WHERE	PAR_KEY = @IPKEYJOB
		RETURN
	END
 
	IF (@VSERVICIO = '') BEGIN
		SET @OCODE = '1'
		SET @OMENSAJE = 'ERROR'
			
		UPDATE	TMT_SV_01
		SET		ERROR = 'SI', DESC_ERROR = 'Debe Completar el Campo Servicio'
		WHERE	PAR_KEY = @IPKEYJOB
		RETURN
	END
 
	IF (@VCALIFICACION = '') BEGIN
		SET @OCODE = '1'
		SET @OMENSAJE = 'ERROR'
			
		UPDATE	TMT_SV_01
		SET		ERROR = 'SI', DESC_ERROR = 'Debe Completar el Campo Calificación'
		WHERE	PAR_KEY = @IPKEYJOB
		RETURN
	END
 
	--VALIDO QUE NO EXISTA LA MISMA COMBINACION DE APTITUD/SERVICIO PARA EL EMPLEADO--
	IF (@VCLAVE = '') BEGIN
			
		SELECT	@VCANT = COUNT(1)
		FROM	LK_EMPLEADOS_APTITUD
		WHERE	ID_EMPLEADO = @VEMPLEADO
		AND		ID_APTITUD  = @VAPTITUD
		AND		ID_TIPO = @VSERVICIO
 
	END ELSE BEGIN
			
		SELECT	@VCANT = COUNT(1)
		FROM	LK_EMPLEADOS_APTITUD
		WHERE	ID_EMPLEADO = @VEMPLEADO
		AND		ID_APTITUD  = @VAPTITUD
		AND		ID_TIPO = @VSERVICIO
		AND		ID_EMPLE_APTITUD <> @VCLAVE
 
	END
		
	IF (@VCANT > 0) BEGIN
		
		SET @OCODE = '1'
		SET @OMENSAJE = 'ERROR'
			
		UPDATE	TMT_SV_01
		SET		ERROR = 'SI',  DESC_ERROR = 'El Empleado/Consultor ya tiene cargada la Aptitud ingresada para el Servicio Seleccionado'
		WHERE	PAR_KEY = @IPKEYJOB
		RETURN
 
	END ELSE BEGIN
			
		IF (@VCLAVE = '') BEGIN
 
			INSERT INTO LK_EMPLEADOS_APTITUD
			(ID_EMPLEADO, ID_APTITUD, CALIFICACION, OBSERVACION, FECHA_ALTA, USUARIO_ALTA, FECHA_UPD, USUARIO_UPD, ID_TIPO)
			VALUES
			(@VEMPLEADO, @VAPTITUD, @VCALIFICACION, @VOBSERVACION, GETDATE(), @IAGENTE, GETDATE(), @IAGENTE, @VSERVICIO)
			
		END ELSE BEGIN
 
			UPDATE	LK_EMPLEADOS_APTITUD
			SET		CALIFICACION = @VCALIFICACION, 
					OBSERVACION = @VOBSERVACION, 
					FECHA_UPD = GETDATE(), 
					USUARIO_UPD = @IAGENTE
			WHERE	ID_EMPLE_APTITUD = @VCLAVE
		END
	END
 
	IF (@OCODE = '0') BEGIN
		SET @OMENSAJE = ''
 
		UPDATE	TMT_SV_01
		SET		ERROR = 'NO', DESC_ERROR = NULL, CLAVE = NULL
		WHERE	PAR_KEY = @IPKEYJOB
	END
 
END
 
