CREATE PROCEDURE [dbo].[HOME_MODIFY_CHECKLIST]
(@IPKEYJOB	AS VARCHAR(100),
 @OCODE		AS VARCHAR(2) OUTPUT,
 @OMENSAJE	AS VARCHAR(400) OUTPUT)
AS
 
DECLARE	@VSERVICIO			VARCHAR(50),
		@VID_HOJA			VARCHAR(50),
		@VCLIENTE			VARCHAR(300),
		@VFECHA				DATETIME,
		@VNOMBRE			VARCHAR(100),
		@VCURSO				VARCHAR(50),
		@VASISTENTES		VARCHAR(50),
		@VOBSERVACIONES		VARCHAR(400),
		@VID_AGENDA			VARCHAR(50),
		@VERROR				VARCHAR(50),
		@lstCadena			varchar(4000), 
		@lstDato			varchar(10), 
		@lnuPosComa			int , 
		@VID				VARCHAR(50), 
		@VALOR				VARCHAR(50)
 
BEGIN
 
	SELECT	@VID_AGENDA = ISNULL(AGENDA_ID,''),
			@VID = ISNULL(PROYECTO_SERV_ID,''),
			@VID_HOJA  = ISNULL(HOJA_RUTA_ID,''),
			--@VFECHA = ISNULL(FECHA_CLC,''),
			--@VCURSO = ISNULL(CURSO_CLC,''),
			--@VASISTENTES = NULLIF(ISNULL(ASISTENTES_CLC,''),''),
			--@VOBSERVACIONES = ISNULL(OBSERVACION_HR,''),
			--@VNOMBRE = ISNULL(NOMBRE_CLC,''),
			@VERROR = ISNULL(ERROR,''),
			@lstCadena = ISNULL(BUFFER,'')
	FROM	XAGENDA
	WHERE	PAR_KEY = @IPKEYJOB
 
	IF (@lstCadena <> '') BEGIN
		WHILE LEN(@lstCadena) > 0
		BEGIN 
			SET @lnuPosComa = CHARINDEX('|', @lstCadena) -- Busca el caracter a separador
			IF (@lnuPosComa = 0) BEGIN 
				SET @lstDato = @lstCadena
				SET @lstCadena = '' 
			END ELSE BEGIN
				SET @lstDato = SUBSTRING(@lstCadena, 1, @lnuPosComa - 1)
				SET @VID = SUBSTRING(@lstDato,1,CHARINDEX('=', @lstDato)-1)
				SET @VALOR = SUBSTRING(@lstDato,CHARINDEX('=', @lstDato)+1,LEN(@lstDato))
 
				UPDATE	LK_PROYECTO_DOCUM_DET
				SET		VALOR_DOC_DET = @VALOR
				WHERE	ID_PROYECTO_DOCUM_DET = @VID
 
				SET @lstCadena = SUBSTRING(@lstCadena, @lnuPosComa + 1, LEN(@lstCadena))
			END		
		END
	END
 
	/*
	UPDATE	LK_PROYECTO_DOCUM 
	SET		FECHA_DOCUM = @VFECHA, 
			NRO_DOCUM_INTERNO = @VNOMBRE,
			TEMAS_DOCUM = @VCURSO,
			PARTICIPANTES_DOCUM = @VASISTENTES, 
			OBSERVACIONES = @VOBSERVACIONES
	WHERE	ID_PROYECTO_DOCUM = @VID_HOJA*/
 
END
 
