CREATE PROCEDURE [dbo].[PA_SYS_THISJOB] 
@jobKey as varchar (100)
AS
SELECT CALL_TYPE_DESC AS Actividad,
       ATT_STATE_DATE_TIME as Fecha,
       CALL_RESULT_DESC as Resultado,
       VW_SYS_USUARIO.USER_NAME AS Usuario,
       VW_SYS_UNIDAD.UNIT_DESCRIPTION as Unidad	
FROM ATTENDED_CUSTOMER,VW_SYS_UNIDAD,VW_SYS_USUARIO, CALL_TYPE, CALL_RESULT_TYPE
WHERE PKEY_JOB =  @jobKey
  AND ATT_STATE_CODE <> 'NOTWORKED'
  AND VW_SYS_UNIDAD.UNIT_CODE = GROUP_CODE
  AND VW_SYS_USUARIO.USER_ID = ATTENDED_CUSTOMER.USER_ID
  AND CALL_TYPE.CALL_TYPE_CODE = ATTENDED_CUSTOMER.CALL_TYPE_CODE
  AND CALL_RESULT_TYPE.CALL_RESULT_CODE = ATT_RESULT_CODE
  AND CALL_RESULT_TYPE.CALL_TYPE_CODE = ATTENDED_CUSTOMER.CALL_TYPE_CODE
ORDER BY ATTENDED_CUSTOMER.PKEY
