CREATE PROCEDURE [dbo].[HOME_GRABA_DATOS_CONSULTOR]
(@IPKEYJOB	AS VARCHAR(100),
 @IAGENTE	AS VARCHAR(100))
AS
 
DECLARE	@VCONSULTOR			VARCHAR(100),
		@VOBSERVACIONES		VARCHAR(400),
		@VMES			VARCHAR(50),
		@VANO			VARCHAR(50),
		@VCANT			INT
 
BEGIN	
	
	SELECT	@VMES = ISNULL(AGENDA_MES,''),
			@VANO = ISNULL(AGENDA_ANO,''),
			@VCONSULTOR = ISNULL(AGENDA_CONSULTOR,''),
			@VOBSERVACIONES = isnull(nullif(ltrim(rtrim(AGENDA_OBSERVADOR)),''),'')
	FROM	XAGENDA
	WHERE	PAR_KEY = @IPKEYJOB
 
	IF (@VOBSERVACIONES <> '') BEGIN
		
		SET @VCANT = 0
 
		SELECT	@VCANT = COUNT(1)
		FROM	LK_EMPLEADOS_OBSERV
		WHERE	ID_EMPLEADO = @VCONSULTOR
		AND		CONVERT(VARCHAR,Mes) = @VMES
		AND		CONVERT(VARCHAR,Ano) = @VANO
 
		IF (@VCANT = 0) BEGIN
			INSERT INTO LK_EMPLEADOS_OBSERV
			(ID_EMPLEADO,MES,ANO,OBSERVACION,FECHA_ALTA,USUARIO_ALTA,FECHA_UPD,USUARIO_UPD)
			VALUES
			(@VCONSULTOR,@VMES,@VANO,@VOBSERVACIONES,GETDATE(),@IAGENTE,GETDATE(),@IAGENTE)
 
		END ELSE BEGIN
 
			UPDATE	LK_EMPLEADOS_OBSERV
			SET		OBSERVACION = @VOBSERVACIONES, FECHA_UPD = GETDATE(), USUARIO_UPD = @IAGENTE
			WHERE	ID_EMPLEADO = @VCONSULTOR
			AND		CONVERT(VARCHAR,Mes) = @VMES
			AND		CONVERT(VARCHAR,Ano) = @VANO
		END
 
	END
 
	--UPDATE	XAGENDA
	--SET		AGENDA_OBSERVADOR = NULL
	--WHERE	PAR_KEY = @IPKEYJOB
	
END
