CREATE PROCEDURE [dbo].[HOME_ADD_PROYECTO]
(@IPKEYJOB	AS VARCHAR(100),
 @IAGENTE	AS VARCHAR(100),
 @OCODE		AS VARCHAR(2) OUTPUT,
 @OMENSAJE	AS VARCHAR(400) OUTPUT)
AS
 
DECLARE @VCLIENTE		VARCHAR(100),
		@VNOMBRE		VARCHAR(300),
		@VNRO_COTIZA	VARCHAR(50),
		@VFECHA			DATETIME,
		@VFECHA_FIN		DATETIME,
		@VHORAS			VARCHAR(50),
		@VMONTO			VARCHAR(50),
		@VAUDITORIA		VARCHAR(50),
		@VCAPACITACION	VARCHAR(50),
		@VCONSULTORIA	VARCHAR(50),
		@VID_PROYECTO	INT,
		@VDESC_ERROR	VARCHAR(4000),
		@VCODIGO		VARCHAR(100),
		@VOBSERVACIONES	VARCHAR(4000),
		@VNORMAS		VARCHAR(4000),
		@lstDato		varchar(100), 
		@lnuPosComa		int ,
		@VALOR			VARCHAR(400),
		@VTORF			VARCHAR(50),
		@VCANT			INT,
		@VESTADO		VARCHAR(50),
		@VNIVEL_RIESGO	VARCHAR(50),
		@VCONTACTO		VARCHAR(400),
		@VNUEVAS		VARCHAR(400),
		@VEXISTE		VARCHAR(50),
		@VPREVIAS		VARCHAR(4000),
		@VMINUTA		VARCHAR(50)
 
BEGIN	
 
	SET @OCODE = 0
	SET @VMINUTA = 'NO'
 
	SELECT	@VID_PROYECTO = ISNULL(PROYECTO_ID,''),
			@VCLIENTE	= ISNULL(CLIENTE,''),
			@VNOMBRE	= ISNULL(NOMBRE_PROY,''),
			@VNRO_COTIZA = ISNULL(NRO_COTIZA,''),
			@VFECHA = ISNULL(FECHA_INICIO_PROY,''),
			@VFECHA_FIN = ISNULL(FECHA_FIN_PROY,''),
			@VHORAS = ISNULL(HORAS_PROY,'0'),
			@VMONTO = REPLACE(ISNULL(MONTO_PROY,'0'),'.',''),
			@VESTADO = ISNULL(ESTADO_PROY,''),
			@VAUDITORIA = ISNULL(SERV_AUDI_PROY,'0'),
			@VCAPACITACION = ISNULL(SERV_CAPA_PROY,'0'),
			@VCONSULTORIA = ISNULL(SERV_CONS_PROY,'0'),
			@VCODIGO = ISNULL(CODIGO_PROY,''),
			@VOBSERVACIONES =  ISNULL(OBSERV_PROY,''),
			@VCONTACTO = ISNULL(CONTACTO_PROY,''),
			@VNIVEL_RIESGO = ISNULL(NIVEL_RIESGO,''),
			@VNORMAS = ISNULL(BUFFER,''),
			@VDESC_ERROR = ISNULL(DESC_ERROR,'')
	FROM	XAGENDA
	WHERE	PAR_KEY = @IPKEYJOB
 
	IF @VID_PROYECTO <> '' BEGIN
		SELECT	@VPREVIAS = NORMAS
		FROM	LK_PROYECTO
		WHERE	ID_PROYECTO = @VID_PROYECTO
	END
 
	IF (@VCLIENTE = '') BEGIN
		SET @OCODE = 1
									
		UPDATE	XAGENDA
		SET		DESC_ERROR = 'Debe Completar el Campo Cliente'
		WHERE	PAR_KEY = @IPKEYJOB
		RETURN
	END
 
	IF (@VNOMBRE = '') BEGIN
		SET @OCODE = 1
									
		UPDATE	XAGENDA
		SET		DESC_ERROR = 'Debe Completar el Campo Nombre Proyecto'
		WHERE	PAR_KEY = @IPKEYJOB
		RETURN
	END
 
	IF (@VFECHA = '') BEGIN
		SET @OCODE = 1
 
		UPDATE	XAGENDA
		SET		DESC_ERROR = 'Debe Completar el Campo Fecha Inicio'
		WHERE	PAR_KEY = @IPKEYJOB
		RETURN
	END
 
	IF (@VFECHA_FIN = '') BEGIN
		SET @OCODE = 1
									
		UPDATE	XAGENDA
		SET		DESC_ERROR = 'Debe Completar el Campo Fecha Fin'
		WHERE	PAR_KEY = @IPKEYJOB
		RETURN
	END
 
	IF @VFECHA > @VFECHA_FIN BEGIN
			
		SET @OCODE = 1
 
		UPDATE	XAGENDA
		SET		DESC_ERROR = 'La Fecha Fin debe ser Mayor a la Fecha Inicio'
		WHERE	PAR_KEY = @IPKEYJOB
		RETURN
	END
 
	IF (ISNUMERIC(@VHORAS) = '0') BEGIN
		SET @OCODE = 1
									
		UPDATE	XAGENDA
		SET		DESC_ERROR = 'El Campo Horas Proyectadas debe ser numerico'
		WHERE	PAR_KEY = @IPKEYJOB
		RETURN
	END
 
	IF (@VHORAS = '0') BEGIN
		SET @OCODE = 1
									
		UPDATE	XAGENDA
		SET		DESC_ERROR = 'Debe Completar el Campo Horas Proyectadas'
		WHERE	PAR_KEY = @IPKEYJOB
		RETURN
	END
 
	IF (ISNUMERIC(@VMONTO) = '0') BEGIN
		SET @OCODE = 1
									
		UPDATE	XAGENDA
		SET		DESC_ERROR = 'El Campo Monto debe ser numerico'
		WHERE	PAR_KEY = @IPKEYJOB
		RETURN
	END
 
	IF CHARINDEX(@VMONTO,',') > 0  BEGIN
		SET @OCODE = 1
									
		UPDATE	XAGENDA
		SET		DESC_ERROR = 'El Campo Monto no puede tener decimales'
		WHERE	PAR_KEY = @IPKEYJOB
		RETURN
	END
 
	IF (@VCONTACTO = '') BEGIN
		SET @OCODE = 1
									
		UPDATE	XAGENDA
		SET		DESC_ERROR = 'Debe Completar el Campo Contacto'
		WHERE	PAR_KEY = @IPKEYJOB
		RETURN
	END
 
	IF (@VAUDITORIA = '0' AND @VCAPACITACION = '0' AND @VCONSULTORIA = '0') BEGIN
		SET @OCODE = 1
									
		UPDATE	XAGENDA
		SET		DESC_ERROR = 'Debe Seleccionar al menos un Servicio para '+CASE WHEN (@VID_PROYECTO = '') THEN 'Agregar' ELSE 'Modificar' END+ ' el Proyecto'
		WHERE	PAR_KEY = @IPKEYJOB
		RETURN
	END
 
	--SI AGREGA--
	IF (@VID_PROYECTO = '') BEGIN
 
		IF (@VNORMAS = '') BEGIN
			SET @OCODE = 1
									
			UPDATE	XAGENDA
			SET		DESC_ERROR = 'Debe Selecionar al menos una Norma para '+CASE WHEN (@VID_PROYECTO = '') THEN 'Agregar' ELSE 'Modificar' END+ ' el Proyecto'
			WHERE	PAR_KEY = @IPKEYJOB
			RETURN
		
		END ELSE BEGIN
			
			WHILE LEN(@VNORMAS) > 0
			BEGIN 
				SET @lnuPosComa = CHARINDEX('|', @VNORMAS) -- Busca el caracter a separador
				IF (@lnuPosComa = 0) BEGIN 
					SET @lstDato = @VNORMAS
					SET @VNORMAS = '' 
				END ELSE BEGIN
					SET @lstDato = SUBSTRING(@VNORMAS, 1, @lnuPosComa - 1)
					SET @VTORF = SUBSTRING(@lstDato,CHARINDEX('=', @lstDato)+1,LEN(@lstDato))
						
					IF (@VTORF = 'FALSE') BEGIN
						SET @VALOR = REPLACE('|'+ @VALOR,'|'+@VALOR+'|','|')
							IF (SUBSTRING(@VALOR,1,1) = '|') BEGIN
								SET @VALOR = SUBSTRING(@VALOR,2,LEN(@VALOR))
							END
					END ELSE BEGIN
						
						SET @VALOR = ISNULL(@VALOR,'') + SUBSTRING(@lstDato,1,CHARINDEX('=', @lstDato)-1) + '|'
					END						
 
					SET @VNORMAS = SUBSTRING(@VNORMAS, @lnuPosComa + 1, LEN(@VNORMAS))
				END
			END
 
			IF (ISNULL(@VALOR,'') = '') BEGIN
				SET @OCODE = 1
									
				UPDATE	XAGENDA
				SET		DESC_ERROR = 'Debe Selecionar al menos una Norma para '+CASE WHEN (@VID_PROYECTO = '') THEN 'Agregar' ELSE 'Modificar' END+ ' el Proyecto'
				WHERE	PAR_KEY = @IPKEYJOB
				RETURN
			END
		END
 
	END ELSE BEGIN
		
		IF (@VPREVIAS = '' AND @VNORMAS = '') BEGIN
 
			SET @OCODE = 1
									
			UPDATE	XAGENDA
			SET		DESC_ERROR = 'Debe Selecionar al menos una Norma para '+CASE WHEN (@VID_PROYECTO = '') THEN 'Agregar' ELSE 'Modificar' END+ ' el Proyecto'
			WHERE	PAR_KEY = @IPKEYJOB
			RETURN
 
		END ELSE BEGIN
			
			SET @VNUEVAS = @VPREVIAS
 
			WHILE LEN(@VNORMAS) > 0
			BEGIN 
				SET @lnuPosComa = CHARINDEX('|', @VNORMAS) -- Busca el caracter a separador
				IF (@lnuPosComa = 0) BEGIN 
					SET @lstDato = @VNORMAS
					SET @VNORMAS = '' 
				END ELSE BEGIN
					SET @lstDato = SUBSTRING(@VNORMAS, 1, @lnuPosComa - 1)
					SET @VALOR = SUBSTRING(@lstDato,1,CHARINDEX('=', @lstDato)-1)
					SET @VTORF = SUBSTRING(@lstDato,CHARINDEX('=', @lstDato)+1,LEN(@lstDato))
 
					IF (@VTORF = 'FALSE') BEGIN
						SET @VEXISTE = [dbo].[FN_GET_NORMA](@VPREVIAS,@VALOR) 
							
						IF @VEXISTE = 'SI' BEGIN
							SET @VNUEVAS = REPLACE('|'+ @VNUEVAS,'|'+@VALOR+'|','|')
							IF (SUBSTRING(@VNUEVAS,1,1) = '|') BEGIN
								SET @VNUEVAS = SUBSTRING(@VNUEVAS,2,LEN(@VNUEVAS))
							END
						END
 
					END ELSE BEGIN
 
						SET @VEXISTE = [dbo].[FN_GET_NORMA](@VPREVIAS,@VALOR) 
							
						IF @VEXISTE <> 'SI' BEGIN
							SET @VNUEVAS = ISNULL(@VNUEVAS,'') + @VALOR + '|'
						END
					END
 
					SET @VNORMAS = SUBSTRING(@VNORMAS, @lnuPosComa + 1, LEN(@VNORMAS))
				END
			END
 
			IF (@VNUEVAS = '') BEGIN
				SET @OCODE = 1
									
				UPDATE	XAGENDA
				SET		DESC_ERROR = 'Debe Selecionar al menos una Norma para '+CASE WHEN (@VID_PROYECTO = '') THEN 'Agregar' ELSE 'Modificar' END+ ' el Proyecto'
				WHERE	PAR_KEY = @IPKEYJOB
				RETURN
			END
		END
	END
 
		--VALIDO QUE NO EXISTA EL MISMO CODIGO EN LK_DOCUMENTACION--
		/*SELECT	@VCANT = COUNT(1)
		FROM	LK_PROYECTO
		WHERE	CONVERT(VARCHAR,ID_CLIENTE) = @VCLIENTE
		AND		NORMA_REF = LTRIM(RTRIM(@VNOMBRE))
 
		IF (@VCANT > 0) BEGIN
		
			SET @OCODE = '1'
			SET @OMENSAJE = '<html>
								<body>
								  <div class="w3-panel w3-pale-red" style="height: 20px;">
										<font style="font-family:Tahoma, Arial, Helvetica, sans-serif;font-size:12px;color:#641E16"><b>Ya Existe un Proyecto con el mismo Nombre para ese Cliente</b></font>
								  </div>
								</div>
								</body>
								</html>'
									
			UPDATE	XAGENDA
			SET		ERROR = 'SI'
			WHERE	PAR_KEY = @IPKEYJOB
			RETURN
 
		END ELSE BEGIN*/
 
	IF (@VID_PROYECTO = '' AND @OCODE = 0) BEGIN 
 
		INSERT INTO LK_PROYECTO
		(ID_COTIZACION, ID_CLIENTE, NORMA_REF, FECHA_ALTA, USUARIO_ALTA, 
		 ESTADO_PROYECTO_TOTAL, FECHA_INICIO_TOTAL, FECHA_FIN_TOTAL, FECHA_INICIO_REAL, FECHA_FIN_REAL,
		 TOTAL_HORAS_PROYECTADAS, TOTAL_HORAS_EJECUTADAS, MONTO_PRESUP, MONTO_COBRADO, ESTADO_COBRO,
		 PORCENTAJE_AVANCE_TOTAL, CODIGO, OBSERVACIONES, NORMAS, CONTACTO, NIVEL_RIESGO)
		VALUES
		(@VNRO_COTIZA, @VCLIENTE, @VNOMBRE, GETDATE(), @IAGENTE,
		 @VESTADO, @VFECHA, @VFECHA_FIN, @VFECHA, @VFECHA_FIN,
		 @VHORAS, NULL, @VMONTO, NULL, NULL,
		 NULL, @VCODIGO, @VOBSERVACIONES, @VALOR, @VCONTACTO, @VNIVEL_RIESGO)
 
		--AGREGO EL UPDATE EN CATEGORIA PARA EL PROXIMO CODIGO DE PROYECTO
		UPDATE	CAT_DATA
		SET		ATTR1 = @VCODIGO
		WHERE	PAR_KEY = '0000000280_98'
		AND		CAT_DATA_CODE = 'PROYECTO_KEY'
 
		SELECT	@VID_PROYECTO = IDENT_CURRENT ('LK_PROYECTO')
 
		IF (@VCONSULTORIA = '1') BEGIN
			INSERT INTO LK_PROYECTO_SERVICIO
			(ID_PROYECTO, ID_TIPO_SERVICIO, PORCENTAJE_AVANCE, FECHA_ALTA, USUARIO_ALTA,
			 ESTADO_PROYECTO, FECHA_INICIO, FECHA_FIN, FECHA_INICIO_REAL, FECHA_FIN_REAL,
			 TOTAL_HORAS_PROYECTADAS, TOTAL_HORAS_EJECUTADAS, MONTO_PRESUP, MONTO_COBRADO, ESTADO_COBRO, CIERRE)
			VALUES
			(@VID_PROYECTO, 1, NULL, GETDATE(), @IAGENTE,
			 @VESTADO, @VFECHA, @VFECHA_FIN, @VFECHA, @VFECHA_FIN,
			 0, NULL, @VMONTO, NULL, NULL, 'NO')
 
			 IF @VMINUTA = 'NO' BEGIN
				SET @VMINUTA = 'SI'
 
				 --EJECUTO SP GENERA MINUTA DE GESTION CONSULTORIA--
				 EXEC [dbo].[HOME_ADD_MINUTA_GESTION] @VCLIENTE, @VID_PROYECTO, @IAGENTE, '1'
			END
 
		END
 
		IF (@VAUDITORIA = '1') BEGIN
			INSERT INTO LK_PROYECTO_SERVICIO
			(ID_PROYECTO, ID_TIPO_SERVICIO, PORCENTAJE_AVANCE, FECHA_ALTA, USUARIO_ALTA,
			 ESTADO_PROYECTO, FECHA_INICIO, FECHA_FIN, FECHA_INICIO_REAL, FECHA_FIN_REAL,
			 TOTAL_HORAS_PROYECTADAS, TOTAL_HORAS_EJECUTADAS, MONTO_PRESUP, MONTO_COBRADO, ESTADO_COBRO, CIERRE)
			VALUES
			(@VID_PROYECTO, 2, NULL, GETDATE(), @IAGENTE,
			 @VESTADO, @VFECHA, @VFECHA_FIN, @VFECHA, @VFECHA_FIN,
			 0, NULL, @VMONTO, NULL, NULL, 'NO')
 
			IF @VMINUTA = 'NO' BEGIN
				SET @VMINUTA = 'SI'
 
				 --EJECUTO SP GENERA MINUTA DE GESTION AUDITORIA--
				 EXEC [dbo].[HOME_ADD_MINUTA_GESTION] @VCLIENTE, @VID_PROYECTO, @IAGENTE, '2'
			END
 
		END
		 
		IF (@VCAPACITACION = '1') BEGIN
			INSERT INTO LK_PROYECTO_SERVICIO
			(ID_PROYECTO, ID_TIPO_SERVICIO, PORCENTAJE_AVANCE, FECHA_ALTA, USUARIO_ALTA,
			ESTADO_PROYECTO, FECHA_INICIO, FECHA_FIN, FECHA_INICIO_REAL, FECHA_FIN_REAL,
			TOTAL_HORAS_PROYECTADAS, TOTAL_HORAS_EJECUTADAS, MONTO_PRESUP, MONTO_COBRADO, ESTADO_COBRO, CIERRE)
			VALUES
			(@VID_PROYECTO, 3, NULL, GETDATE(), @IAGENTE,
			@VESTADO, @VFECHA, @VFECHA_FIN, @VFECHA, @VFECHA_FIN,
			0, NULL, @VMONTO, NULL, NULL, 'NO')
 
			IF @VMINUTA = 'NO' BEGIN
				SET @VMINUTA = 'SI'
 
				 --EJECUTO SP GENERA MINUTA DE GESTION CAPACITACION--
				 EXEC [dbo].[HOME_ADD_MINUTA_GESTION] @VCLIENTE, @VID_PROYECTO, @IAGENTE, '3'
			END
 
		END
	
	END ELSE BEGIN
 
		UPDATE	LK_PROYECTO
		SET		ID_COTIZACION	= @VNRO_COTIZA, 
				NORMA_REF		= @VNOMBRE, 
				FECHA_INICIO_TOTAL = @VFECHA,
				FECHA_INICIO_REAL = @VFECHA,
				FECHA_FIN_TOTAL = @VFECHA_FIN,
				FECHA_FIN_REAL = @VFECHA_FIN,
				TOTAL_HORAS_PROYECTADAS = @VHORAS, 
				MONTO_PRESUP = CAST(@VMONTO AS int),
				CODIGO = @VCODIGO, 
				OBSERVACIONES = @VOBSERVACIONES, 
				NORMAS = @VNUEVAS,
				ESTADO_PROYECTO_TOTAL = @VESTADO,--CASE WHEN ESTADO_PROYECTO_TOTAL NOT IN ('TERMINADO','ENCURSO') THEN @VESTADO ELSE ESTADO_PROYECTO_TOTAL END,
				CONTACTO = @VCONTACTO,
				NIVEL_RIESGO = @VNIVEL_RIESGO
		WHERE	ID_PROYECTO = @VID_PROYECTO
	END
	
	IF (@OCODE = 0) BEGIN
		UPDATE	XAGENDA
		SET		DESC_ERROR = NULL, BUFFER = NULL
		WHERE	PAR_KEY = @IPKEYJOB
	END
 
END
