CREATE PROCEDURE PA_SYS_GET_EIS_RESPONSE (@PS_TABLENAME VARCHAR(30) = 'EIS_RESPONSE', @PS_FIELDNAME VARCHAR(30) = 'EIS_RESPONSE', @PS_USERID VARCHAR(30) = 'ADMINISTRADOR', @PS_EIS_RESPONSE VARCHAR(4000) = NULL OUTPUT, @PS_RET_MESSAGE VARCHAR(440) = NULL OUTPUT) AS
 
-- =========================================================================================================================
-- AUTOR: ROLANDO - ENGAGE SOFTWARE COMPANY
-- FECHA DE CREACIÓN: 13/01/2011
-- EDITOR: TITO - ENGAGE SOFTWARE COMPANY
-- FECHA DE MODIFICACIÓN: 23/02/2011
-- TABLAS LEÍDAS: LA QUE VENGA POR PARÁMETRO EN @PS_TABLENAME.
-- TABLAS MODIFICADAS: NINGUNA.
-- DESCRIPCIÓN: DEVUELVE EL RESULTADO DE UNA RESPUESTA DE ENGAGE INTEGRATION SERVICES.
-- PARÁMETROS:
-- @PS_TABLENAME -> TABLA DONDE LA TRANSFORMACIÓN DE ENGAGE INTEGRATION SERVICES GUARDÓ LOS DATOS DEVUELTOS POR EL WEB SERVICE.
-- @PS_FIELDNAME -> CAMPO DE LA TABLA DONDE LA TRANSFORMACIÓN GUARDÓ LOS DATOS.
-- @PS_USERID -> USUARIO QUE SE USARÁ COMO FILTRO.
-- @PS_EIS_RESPONSE -> DATO DEVUELTO POR ENGAGE SERVICES.
-- @PS_RET_MESSAGE -> DEVUELVE EL MENSAJE DE ERROR. NULL SI NO HUBO.
-- CONSIDERACIONES: 
-- SE ESPERA QUE LA TRANSFORMACIÓN GUARDE LOS ATRIBUTOS DEVUELTOS EN UN SÓLO CAMPO DE UN SÓLO REGISTRO DE UNA SOLA TABLA.
-- =========================================================================================================================
 
SET NOCOUNT ON;
SET XACT_ABORT ON;
 
-- DECLARACIÓN E INICIALIZACIÓN DE VARIABLES DE ERROR Y AUXILIARES.
DECLARE @LNERRORNUM AS INTEGER,
	@LNSEVERITY AS SMALLINT,
	@LNFILAS_AFEC AS INTEGER,
	@LDINICIO_OPE AS DATETIME,
	@LNDURACION AS INTEGER,
	@LSOPERA AS VARCHAR(30),
	@LSPROC AS VARCHAR(30),
	@LSTABLA AS VARCHAR(30),
	@LSERRORLOG AS VARCHAR(440),
	@LSERRORDESC AS VARCHAR(440),
	@LSSQL_CMD AS VARCHAR(4000)
;
SELECT 	@LNERRORNUM = 0,
	@LNSEVERITY = 16,
	@LNFILAS_AFEC = 0,
	@LDINICIO_OPE = GETDATE(),
	@LNDURACION = 0,
	@LSOPERA = 'EXECUTE',
	@LSPROC = OBJECT_NAME(@@PROCID),
	@LSTABLA = 'NINGUNA',
	@LSERRORLOG = @@SERVERNAME + '.' + DB_NAME() + '.' + USER_NAME() + '.' + OBJECT_NAME(@@PROCID) + ' - ',
	@LSERRORDESC = NULL,
	@LSSQL_CMD = NULL
;
-- DECLARACIÓN DE VARIABLES DE USUARIO.
DECLARE
@LS_TABLENAME VARCHAR(30),
@LS_FIELDNAME VARCHAR(30),
@LS_USERID VARCHAR(30),
@LS_EIS_RESPONSE VARCHAR(4000),
@LS_RET_MESSAGE VARCHAR(440),
@LS_SQL_CUR NVARCHAR(4000),
@LS_SQL_PAR NVARCHAR(4000);
 
SELECT	@LS_TABLENAME = NULLIF(@PS_TABLENAME, ''),
	@LS_FIELDNAME = NULLIF(@PS_FIELDNAME, ''),
	@LS_USERID = NULLIF(@PS_USERID, ''),
	@LS_EIS_RESPONSE = NULL,
	@LS_RET_MESSAGE = NULL,
	@LS_SQL_CUR = NULL,
	@LS_SQL_PAR = N'@LS_EIS_RESPONSE_OUT VARCHAR(4000) OUTPUT'; -- ASOCIA EL PARÁMETRO DE SALIDA CON EL RESULTADO DEL QUERY DINÁMICO.
 
BEGIN TRANSACTION
 
-- TODOS LOS PARÁMETROS DEBEN SER VÁLIDOS.
IF (@LS_TABLENAME IS NOT NULL) BEGIN
	IF (@LS_FIELDNAME IS NOT NULL) BEGIN
		IF (@LS_USERID IS NOT NULL) BEGIN
			SET @LS_SQL_CUR = 'SELECT TOP 1 @LS_EIS_RESPONSE_OUT = ' + @LS_FIELDNAME + ' FROM ' + @LS_TABLENAME + ' WHERE TS_USER_ID = ''' + @LS_USERID + ''' ORDER BY TS_BEGIN DESC'
			EXECUTE @LNERRORNUM = SP_EXECUTESQL @LS_SQL_CUR, @LS_SQL_PAR, @LS_EIS_RESPONSE_OUT = @LS_EIS_RESPONSE OUTPUT;
			SELECT @LSOPERA = 'EXECUTE', @LSTABLA = 'SP_EXECUTESQL', @LSSQL_CMD = @LS_SQL_CUR, @LNFILAS_AFEC = @@ROWCOUNT;
			IF (@LNERRORNUM <> 0) GOTO FALLO;
			-- DEVUELVE LA RESPUESTA DE ENGAGE INTEGRATION SERVICES.
			SET @PS_EIS_RESPONSE = @LS_EIS_RESPONSE;
		END
		ELSE BEGIN
			SET @LS_RET_MESSAGE = 'EL PARÁMETRO @PS_USERID ES NULO.';
		END;
	END
	ELSE BEGIN
		SET @LS_RET_MESSAGE = 'EL PARÁMETRO @PS_FIELDNAME ES NULO.';
	END;
END
ELSE BEGIN
	SET @LS_RET_MESSAGE = 'EL PARÁMETRO @PS_TABLENAME ES NULO.';
END;
 
-- DEVUELVE EL MENSAJE DE ERROR. NULL SI NO HUBO.
SET @PS_RET_MESSAGE = @LS_RET_MESSAGE;
 
FALLO:
-- REGISTRO DE SUCESOS Y CONTROL DE FIN DE PROCEDIMIENTO. CONCLUYE LA TRANSACCIÓN SI TODO FUE EXITOSO.
SELECT @LNDURACION = DATEDIFF(SECOND, @LDINICIO_OPE, GETDATE()), @LNSEVERITY = ISNULL(EM.SEVERITY, 16), @LSERRORDESC = 'ERROR ' + CONVERT(VARCHAR, ISNULL(EM.ERROR, 0)) + ' - ' + ISNULL(EM.DESCRIPTION, ' ') FROM MASTER.DBO.SYSMESSAGES EM WHERE (EM.ERROR = @LNERRORNUM);
IF (@LNERRORNUM <> 0) BEGIN
	-- NOTIFICACIÓN EN EL REGISTRO DE SQL SERVER.
	SET @LSERRORLOG = @LSERRORLOG + CASE WHEN (ISNULL(CHARINDEX('%', @LSERRORDESC), 0) > 0) THEN RTRIM(LEFT(@LSERRORDESC, 11)) ELSE @LSERRORDESC END;
	-- DEVUELVE EL ERROR EN EL PARÁMETRO DE SALIDA.
	SET @PS_RET_MESSAGE = SUBSTRING(@LSERRORDESC, 1, 440);
	-- DESHACE LA TRANSACCIÓN COMPLETA SI LA OPERACIÓN FALLÓ.
	IF (@@TRANCOUNT > 0) ROLLBACK TRANSACTION;
	EXECUTE @LNERRORNUM = PA_SYS_REGISTRO_SUCESOS_INSERT @PSPROCEDIMIENTO_1 = @LSPROC, @PSTABLA_2 = @LSTABLA, @PNFILAS_AFECTADAS_3 = @LNFILAS_AFEC, @PSOPERACION_4 = @LSOPERA, @PNDURACION_5 = @LNDURACION, @PSRESULTADO_6 = @LSERRORDESC, @PSSQL_CMD_7 = @LSSQL_CMD;
	-- RAISERROR(@LSERRORLOG, @LNSEVERITY, -1) WITH NOWAIT;
END
ELSE BEGIN
	-- EXECUTE @LNERRORNUM = PA_SYS_REGISTRO_SUCESOS_INSERT @PSPROCEDIMIENTO_1 = @LSPROC, @PSTABLA_2 = @LSTABLA, @PNFILAS_AFECTADAS_3 = @LNFILAS_AFEC, @PSOPERACION_4 = @LSOPERA, @PNDURACION_5 = @LNDURACION, @PSRESULTADO_6 = @LSERRORDESC, @PSSQL_CMD_7 = @LSSQL_CMD;
	IF (@@TRANCOUNT > 0) COMMIT TRANSACTION;
END;
RETURN;
