CREATE   PROCEDURE [dbo].[M_CONFIG_ADD_USER_SECTOR]
(@IPKEYJOB	AS VARCHAR(100),
 @IUSERID	AS VARCHAR(100))
AS
 
BEGIN	
 
declare @ID_USER_SEL	VARCHAR(50),
		@ID_SECTOR_SEL	VARCHAR(50),
		@ID_ROL_SEL		VARCHAR(50)
 
	SELECT	@ID_USER_SEL = ID_USER_SEL, 
			@ID_SECTOR_SEL = ID_SECTOR_SEL,
			@ID_ROL_SEL = isnull(NEW_PERFIL,'')
	FROM	M_CONFIG 
	WHERE	PAR_KEY = @IPKEYJOB;
 
	--SET @ID_ROL_SEL=substring(@ID_USER_SEL,1,1)
	--SET @ID_USER_SEL=substring(@ID_USER_SEL,2,100)
 
	IF @ID_ROL_SEL='S'
		SET @ID_ROL_SEL='supervisor'
	else
		SET @ID_ROL_SEL='user'
 
	DECLARE @VSECTOR_DESC VARCHAR(300), @VDESC_USER VARCHAR(300)
 
	SELECT	@VSECTOR_DESC = DESC_SECTOR
	FROM	SECTORES
	WHERE	ID_SECTOR = CONVERT(NUMERIC,@ID_SECTOR_SEL)
 
	SELECT	@VDESC_USER = ISNULL(NAME,'')
	FROM	USERS
	WHERE	ID = @ID_USER_SEL
 
	/* ====== Insert ====== */
	BEGIN TRANSACTION
 
		insert into UsersSector (id_User, Id_Sector, rol, ModifiedDate, Userid) 
		values (@ID_USER_SEL, @ID_SECTOR_SEL, @ID_ROL_SEL, GETDATE(), @IUSERID);	
 
		
	COMMIT TRANSACTION
	RETURN;
END
