CREATE PROCEDURE PA_SYS_RPT_PARAMETROS (@PD_FECHA_DESDE DATETIME = NULL, @PD_FECHA_HASTA DATETIME = NULL, @PS_RET_MESSAGE VARCHAR(440) = NULL OUTPUT) AS
 
-- =========================================================================================================================
-- AUTOR: MBRIZZI - ENGAGE SOFTWARE COMPANY
-- FECHA DE CREACIÓN: 30/08/2011
-- EDITOR: TITO - ENGAGE SOFTWARE COMPANY
-- FECHA DE MODIFICACIÓN: 12/09/2011
-- TABLAS LEÍDAS: A DEFINIR
-- TABLAS MODIFICADAS: A DEFINIR
-- DESCRIPCIÓN: PROCEDIMIENTO DE REPORTE CUSTOMIZABLE.
-- CONSIDERACIONES:
-- 1. EL PARÁMETRO DE SALIDA @PS_RET_MESSAGE DEVUELVE EL MENSAJE DE ERROR. NULL SI NO HUBO.
-- 2. LOS RESULTADOS DEVUELTOS POR LA CONSULTA, SERÁN MOSTRADOS EN LA GRILLA DE REPORTES DEL SECURITY ADMINISTRATOR.
-- =========================================================================================================================
 
SET NOCOUNT ON;
SET XACT_ABORT ON;
 
-- DECLARACIÓN E INICIALIZACIÓN DE VARIABLES DE ERROR Y AUXILIARES.
DECLARE @LNERRORNUM AS INTEGER,
	@LNSEVERITY AS SMALLINT,
	@LNFILAS_AFEC AS INTEGER,
	@LDINICIO_OPE AS DATETIME,
	@LNDURACION AS INTEGER,
	@LSOPERA AS VARCHAR(30),
	@LSPROC AS VARCHAR(30),
	@LSTABLA AS VARCHAR(30),
	@LSERRORLOG AS VARCHAR(440),
	@LSERRORDESC AS VARCHAR(440),
	@LSSQL_CMD AS VARCHAR(4000)
;
SELECT 	@LNERRORNUM = 0,
	@LNSEVERITY = 16,
	@LNFILAS_AFEC = 0,
	@LDINICIO_OPE = GETDATE(),
	@LNDURACION = 0,
	@LSOPERA = 'EXECUTE',
	@LSPROC = OBJECT_NAME(@@PROCID),
	@LSTABLA = 'NINGUNA',
	@LSERRORLOG = @@SERVERNAME + '.' + DB_NAME() + '.' + USER_NAME() + '.' + OBJECT_NAME(@@PROCID) + ' - ',
	@LSERRORDESC = NULL,
	@LSSQL_CMD = NULL
;
DECLARE
@LD_FECHA_DESDE DATETIME,
@LD_FECHA_HASTA DATETIME;
 
-- DETERMINA LAS FECHAS DE PROCESO. SÓLO FECHA SIN HORA.
SELECT @LD_FECHA_DESDE = CASE WHEN @PD_FECHA_DESDE IS NULL THEN CONVERT(VARCHAR, GETDATE(), 112) ELSE CONVERT(VARCHAR, @PD_FECHA_DESDE, 112) END;
SELECT @LD_FECHA_HASTA = CASE WHEN @PD_FECHA_HASTA IS NULL THEN CONVERT(VARCHAR, GETDATE() + 1, 112) ELSE CONVERT(VARCHAR, @PD_FECHA_HASTA, 112) END;
 
-- DECLARO LA TRANSACCIÓN.
BEGIN TRANSACTION
 
IF (@LD_FECHA_DESDE = @LD_FECHA_HASTA) BEGIN
	SET @LD_FECHA_HASTA = @LD_FECHA_HASTA + 1;
END;
 
IF (@LD_FECHA_DESDE < @LD_FECHA_HASTA) BEGIN
	-- ARMAR LA CONSULTA DE REPORTE AQUÍ.
	SELECT 'Procedimiento Almacenado NO definido.';
	SELECT @LSOPERA = 'SELECT', @LSTABLA = NULL, @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
END
ELSE BEGIN
	SET @PS_RET_MESSAGE = 'EL PARÁMETRO @PD_FECHA_HASTA DEBE CONTENER UNA FECHA MAYOR A LA DE @PD_FECHA_DESDE';
END;
 
FALLO:
-- REGISTRO DE SUCESOS Y CONTROL DE FIN DE PROCEDIMIENTO. CONCLUYE LA TRANSACCIÓN SI TODO FUE EXITOSO.
SELECT @LNDURACION = DATEDIFF(SECOND, @LDINICIO_OPE, GETDATE()), @LNSEVERITY = ISNULL(EM.SEVERITY, 16), @LSERRORDESC = 'ERROR ' + CONVERT(VARCHAR, ISNULL(EM.ERROR, 0)) + ' - ' + ISNULL(EM.DESCRIPTION, ' ') FROM MASTER.DBO.SYSMESSAGES EM WHERE (EM.ERROR = @LNERRORNUM);
IF (@LNERRORNUM <> 0) BEGIN
	-- NOTIFICACIÓN EN EL REGISTRO DE SQL SERVER.
	SET @LSERRORLOG = @LSERRORLOG + CASE WHEN (ISNULL(CHARINDEX('%', @LSERRORDESC), 0) > 0) THEN RTRIM(LEFT(@LSERRORDESC, 11)) ELSE @LSERRORDESC END;
	-- DEVUELVE EL ERROR EN EL PARÁMETRO DE SALIDA.
	SET @PS_RET_MESSAGE = SUBSTRING(@LSERRORDESC, 1, 440);
	-- DESHACE LA TRANSACCIÓN COMPLETA SI LA OPERACIÓN FALLÓ.
	IF (@@TRANCOUNT > 0) ROLLBACK TRANSACTION;
	EXECUTE @LNERRORNUM = PA_SYS_REGISTRO_SUCESOS_INSERT @PSPROCEDIMIENTO_1 = @LSPROC, @PSTABLA_2 = @LSTABLA, @PNFILAS_AFECTADAS_3 = @LNFILAS_AFEC, @PSOPERACION_4 = @LSOPERA, @PNDURACION_5 = @LNDURACION, @PSRESULTADO_6 = @LSERRORDESC, @PSSQL_CMD_7 = @LSERRORDESC;
	-- RAISERROR(@LSERRORLOG, @LNSEVERITY, -1) WITH NOWAIT;
END
ELSE BEGIN
--	EXECUTE @LNERRORNUM = PA_SYS_REGISTRO_SUCESOS_INSERT @PSPROCEDIMIENTO_1 = @LSPROC, @PSTABLA_2 = @LSTABLA, @PNFILAS_AFECTADAS_3 = @LNFILAS_AFEC, @PSOPERACION_4 = @LSOPERA, @PNDURACION_5 = @LNDURACION, @PSRESULTADO_6 = @LSERRORDESC, @PSSQL_CMD_7 = @LSERRORDESC;
	IF (@@TRANCOUNT > 0) COMMIT TRANSACTION;
END;
RETURN;
