CREATE PROCEDURE SP_SYS_VALIDAR_NUEVO_TRAMITE (@PSCUSTOMERTYPE VARCHAR(20), @PSCUSTOMERPKEY VARCHAR(60), @PSJOBTYPE VARCHAR(20), @PSERROR VARCHAR(250) OUTPUT) AS
 
-- @PSERROR DEBE SER '0' PARA INDICAR QUE TODO ESTUVO OK.
SET @PSERROR = '0'; -- TODO OK
-- SET @PSERROR = 'ERROR AL CREAR EL TRAMITE';
 
SELECT @PSERROR;
 
RETURN;
