CREATE PROCEDURE [dbo].[PA_OPERATIVO_CONF_TRASP](
@PKEY_JOB   AS VARCHAR(100))
AS
DECLARE @PKEY_OPERATIVO   AS VARCHAR(36);
 
BEGIN
	print 'pkeyjob='+@PKEY_JOB;
	SET @PKEY_OPERATIVO = (SELECT OPERATIVO_SEL FROM GBL_OPERATIVOS WHERE PAR_KEY = @PKEY_JOB );
	print '@PKEY_OPERATIVO='+@PKEY_OPERATIVO;
	
	UPDATE TITULARES
	SET FECHA_TRASPASO = GETDATE(),
	ENVIAR_TRASPASO = NULL
	WHERE PKEY_OPERATIVO = RTRIM(LTRIM(@PKEY_OPERATIVO)) 
	AND ENVIAR_TRASPASO = '1' 
	AND OP_FOTOCOPIA_DNI = '1' 
	AND VALIDACION_SSS = 'SSS_OK'
	AND FECHA_TRASPASO IS NULL
 
END
 
 
