CREATE PROCEDURE [dbo].[HOME_CMB_SERVICIOS_ANEXO]
(@IPKEYJOB	AS VARCHAR(100))
AS
 
DECLARE	@VID_PROYECTO	VARCHAR(50),
		@VTIPO_SERV_MG	VARCHAR(50)
 
BEGIN	
 
	SELECT	@VID_PROYECTO = ISNULL(PROYECTO_ID,'')
	FROM	XAGENDA
	WHERE	PAR_KEY = @IPKEYJOB
 
	SELECT	@VTIPO_SERV_MG  = ISNULL(ID_TIPO_SERVICIO,'')
	FROM	LK_PROYECTO_DOCUM 
	WHERE	ID_PROYECTO = @VID_PROYECTO
	AND		TIPO = 'MG'
 
	--SINO TIENE MINUTA DE GESTION, ES PROYECTO VIEJO--
	IF (@VTIPO_SERV_MG <> '') BEGIN
 
		SELECT	DISTINCT ID_TIPO_SERVICIO AS CAT_DATA_CODE,
				CASE WHEN ID_TIPO_SERVICIO = '1' THEN 'Consultoria' 
					 WHEN ID_TIPO_SERVICIO = '2' THEN 'Auditoria'
					 WHEN ID_TIPO_SERVICIO = '3' THEN 'Capacitacion'
				END AS CAT_DATA_DESC,
				'true'
		FROM	LK_PROYECTO_SERVICIO
		WHERE	ID_PROYECTO = @VID_PROYECTO
		AND		ID_TIPO_SERVICIO <> @VTIPO_SERV_MG
		ORDER BY CAT_DATA_DESC
	END
	
END
