CREATE PROCEDURE [dbo].[PA_SYS_OBTIENE_PKEY] (@PSTABLA VARCHAR(50), @PSPKEY VARCHAR(50) OUTPUT) AS
 
-- =========================================================================================================================
-- AUTOR: GASTÓN ARIMÓN - ENGAGE SOFTWARE COMPANY
-- FECHA DE CREACIÓN: 27/11/2006
-- EDITOR: TITO - ENGAGE SOFTWARE COMPANY
-- FECHA DE EDICIÓN: 23/12/2011
-- TABLAS LEÍDAS: PRM.
-- TABLAS MODIFICADAS: PRM.
-- DESCRIPCIÓN: PROCEDIMIENTO QUE GENERA UNA CLAVE NUEVA PARA LA TABLA PASADA POR PARÁMETRO.
-- CONSIDERACIONES:
-- 1. SE EXCLUYEN LAS TABLAS DE HISTORIA, DE WORKFLOW Y DE LOG Y LAS NUEVAS TABLAS DE LA VERSIÓN 4.12.3 Y POSTERIORES.
-- =========================================================================================================================
 
SET NOCOUNT ON;
SET XACT_ABORT ON;
 
-- DECLARACIÓN E INICIALIZACIÓN DE VARIABLES DE ERROR Y AUXILIARES.
DECLARE @LNERRORNUM AS INTEGER,
	@LNSEVERITY AS SMALLINT,
	@LNFILAS_AFEC AS INTEGER,
	@LDINICIO_OPE AS DATETIME,
	@LNDURACION AS INTEGER,
	@LSOPERA AS VARCHAR(30),
	@LSPROC AS VARCHAR(30),
	@LSTABLA AS VARCHAR(30),
	@LSERRORLOG AS VARCHAR(440),
	@LSERRORDESC AS VARCHAR(440),
	@LSSQL_CMD AS VARCHAR(4000)
;
SELECT 	@LNERRORNUM = 0,
	@LNSEVERITY = 16,
	@LNFILAS_AFEC = 0,
	@LDINICIO_OPE = GETDATE(),
	@LNDURACION = 0,
	@LSOPERA = 'EXECUTE',
	@LSPROC = OBJECT_NAME(@@PROCID),
	@LSTABLA = 'NINGUNA',
	@LSERRORLOG = @@SERVERNAME + '.' + DB_NAME() + '.' + USER_NAME() + '.' + OBJECT_NAME(@@PROCID) + ' - ',
	@LSERRORDESC = NULL,
	@LSSQL_CMD = NULL
;
-- DECLARA LAS VARIABLES.
DECLARE
@LS_TABLA VARCHAR(50),
@LSPKEY VARCHAR(50),
@LS_NOT_ALLOWED VARCHAR(1)
;
-- ASIGNA VALORES PREDETERMINADOS A LAS VARIABLES.
SELECT	@LS_TABLA = ISNULL(LTRIM(RTRIM(@PSTABLA)), ' '),
	@LSPKEY = NULL,
	@LS_NOT_ALLOWED = '0'
;
 
-- DECLARO LA TRANSACCIÓN.
BEGIN TRANSACTION
 
-- EXCLUSIÓN DE TABLAS DSST, WKFD Y ETL.
SELECT	@LS_NOT_ALLOWED =
	CASE @LS_TABLA
	WHEN 'DSS_TBATTENDED_CUSTOMER' THEN '1'
	WHEN 'DSS_TBPHYSICAL_CALL' THEN '1'
	WHEN 'DSS_TBPHYSICAL_CALL_CONV_STEPS' THEN '1'
	WHEN 'DSS_TBPHYSICAL_JOB' THEN '1'
	WHEN 'DSS_TBPHYS_CALL_ANSWERED_QUES' THEN '1'
	WHEN 'ATTENDED_CUSTOMER' THEN '1'
	WHEN 'PHYS_CALL_ANSWERED_QUESTIONS' THEN '1'
	WHEN 'PHYSICAL_ACTIVITIES' THEN '1'
	WHEN 'PHYSICAL_ATTACHED_DOCUMENT' THEN '1'
	WHEN 'PHYSICAL_CALL' THEN '1'
	WHEN 'PHYSICAL_CALL_CONV_STEPS' THEN '1'
	WHEN 'PHYSICAL_CALL_NUMBERS' THEN '1'
	WHEN 'PHYSICAL_JOB' THEN '1'
	WHEN 'PHYSICAL_JOB_ACTIONS' THEN '1'
	WHEN 'PHYSICAL_JOB_ALARMS' THEN '1'
	WHEN 'PHYSICAL_JOB_ATTACHED_DATA' THEN '1'
	WHEN 'PHYSICAL_JOB_NOTIFICATIONS' THEN '1'
	WHEN 'PHYSICAL_NOTES' THEN '1'
	WHEN 'PHYSICAL_CALL_TRANSACTIONS' THEN '1'
	WHEN 'PSESSIONS_FAILURES' THEN '1'
	WHEN 'CUST_TYPE_ENT_KEY_DET' THEN '1'
	WHEN 'EIS_RESPONSE' THEN '1'
	WHEN 'ENTITY_BROWSER' THEN '1'
	WHEN 'ENTITY_BROWSER_DETAIL' THEN '1'
	WHEN 'PSESSIONS' THEN '1'
	WHEN 'ENTITY_VIRTUAL_DETAIL' THEN '1'
	WHEN 'AUDITOR' THEN '1'
	WHEN 'EMD_INBOX_VIEWS_DATA' THEN '1'
	WHEN 'EMD_INBOX_VIEWS_UNITS' THEN '1'
	WHEN 'EMD_INBOX_VIEWS_DETAILS' THEN '1'
	ELSE '1' END;
 
-- AGREGA EL SUFIJO '_KEY' AL NOMBRE DE LA TABLA.
SET @LS_TABLA = @LS_TABLA + '_KEY';
 
-- DETERMINA SI CORRESPONDE GENERAR CLAVE DE PRM PARA LA TABLA ACTUAL.
IF (@LS_NOT_ALLOWED = '0') BEGIN
	-- INCREMENTA EL CONTADOR CORRESPONDIENTE EN LA TABLA PRM.
	UPDATE	PRM
	SET	PRM_VAL = CONVERT(VARCHAR(50), CONVERT(NUMERIC(10), PRM_VAL) + 1)
	WHERE	(PRM_COD = @LS_TABLA);
	SELECT @LSOPERA = 'UPDATE', @LSTABLA = 'PRM', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
	-- TOMA EL VALOR DE LA CLAVE SIN EL INCREMENTO.
	SELECT	@LSPKEY = RTRIM(RIGHT(RTRIM('0000000000' + RTRIM(CONVERT(NUMERIC(10), PRM_VAL) - 1)), 10) + '_' + ISNULL(PRM_NUM, '95'))
	FROM	PRM
	WHERE	(PRM_COD = @LS_TABLA);
	SELECT @LSOPERA = 'SELECT', @LSTABLA = 'PRM', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
END
ELSE BEGIN
	-- GENERA UNA CLAVE GUID EN FORMA AUTOMÁTICA SIN ACCESO A LA TABLA PRM.
	SET @LSPKEY = NEWID();
END;
 
-- DETERMINA SI SE GENERÓ UNA CLAVE O SI HUBO ERROR LÓGICO.
IF (@LSPKEY IS NULL) BEGIN
	SET @LSERRORDESC = 'LA CLAVE ' + @LS_TABLA + ' NO EXISTE EN PRM.PRM_COD';
	SET @LNERRORNUM = 50000;
	GOTO FALLO;
END
ELSE BEGIN
	SET @PSPKEY = @LSPKEY;
END;
 
FALLO:
-- REGISTRO DE SUCESOS Y CONTROL DE FIN DE PROCEDIMIENTO. CONCLUYE LA TRANSACCIÓN SI TODO FUE EXITOSO.
SELECT @LNDURACION = DATEDIFF(SECOND, @LDINICIO_OPE, GETDATE()), @LNSEVERITY = ISNULL(EM.SEVERITY, 16), @LSERRORDESC = 'ERROR ' + CONVERT(VARCHAR, ISNULL(EM.ERROR, 0)) + ' - ' + ISNULL(EM.DESCRIPTION, ' ') FROM MASTER.DBO.SYSMESSAGES EM WHERE (EM.ERROR = @LNERRORNUM);
IF (@LNERRORNUM <> 0) BEGIN
	-- NOTIFICACIÓN EN EL REGISTRO DE SQL SERVER.
	SET @LSERRORLOG = @LSERRORLOG + CASE WHEN (ISNULL(CHARINDEX('%', @LSERRORDESC), 0) > 0) THEN RTRIM(LEFT(@LSERRORDESC, 11)) ELSE @LSERRORDESC END;
	-- DESHACE LA TRANSACCIÓN COMPLETA SI LA OPERACIÓN FALLÓ.
	IF (@@TRANCOUNT > 0) ROLLBACK TRANSACTION;
	EXECUTE @LNERRORNUM = PA_SYS_REGISTRO_SUCESOS_INSERT @PSPROCEDIMIENTO_1 = @LSPROC, @PSTABLA_2 = @LSTABLA, @PNFILAS_AFECTADAS_3 = @LNFILAS_AFEC, @PSOPERACION_4 = @LSOPERA, @PNDURACION_5 = @LNDURACION, @PSRESULTADO_6 = @LSERRORDESC, @PSSQL_CMD_7 = @LSERRORDESC;
	RAISERROR(@LSERRORLOG, @LNSEVERITY, -1) WITH NOWAIT;
END
ELSE BEGIN
	-- EXECUTE @LNERRORNUM = PA_SYS_REGISTRO_SUCESOS_INSERT @PSPROCEDIMIENTO_1 = @LSPROC, @PSTABLA_2 = @LSTABLA, @PNFILAS_AFECTADAS_3 = @LNFILAS_AFEC, @PSOPERACION_4 = @LSOPERA, @PNDURACION_5 = @LNDURACION, @PSRESULTADO_6 = @LSERRORDESC, @PSSQL_CMD_7 = @LSERRORDESC;
	IF (@@TRANCOUNT > 0) COMMIT TRANSACTION;
END;
RETURN;
 
