CREATE PROCEDURE [dbo].[CMB_APTITUDES]
AS
BEGIN	
 
	SELECT	DISTINCT ID_APTITUD AS CAT_DATA_CODE,
			DESC_APTITUD AS CAT_DATA_DESC,
			'TRUE'
	FROM	LK_APTITUDES
	WHERE	STATUS_APTITUD = '1'
	ORDER BY DESC_APTITUD
 
 
END
