CREATE   PROCEDURE [dbo].[SV_01_CMB_EMPLEADO_APTITUD]
(@IPKEYJOB	AS VARCHAR(100))
AS
 
DECLARE @VEMPLEADO VARCHAR(50),
		@VTIPO		VARCHAR(50)
 
BEGIN
 
	SELECT	@VEMPLEADO = EMPLEADO,
			@VTIPO = ISNULL(TIPO_SERVICIO,'')
	FROM	TMT_SV_01
	WHERE	PAR_KEY = @IPKEYJOB	
 
	SELECT	APT.ID_APTITUD AS CAT_DATA_CODE,
			APT.DESC_APTITUD AS CAT_DATA_DESC,
			'TRUE'
	FROM	LK_APTITUDES APT
	WHERE	APT.STATUS_APTITUD = '1'
	AND		APT.ID_APTITUD NOT IN (SELECT ID_APTITUD
								   FROM	  LK_EMPLEADOS_APTITUD
								   WHERE  ID_EMPLEADO = @VEMPLEADO
								   AND	  ID_TIPO = @VTIPO)
	ORDER BY APT.ID_APTITUD
 
END
 
