CREATE PROCEDURE [dbo].[HOME_ADD_CHECKLIST]
(@IPKEYJOB	AS VARCHAR(100),
 @IAGENTE	AS VARCHAR(100),
 @OCODE		AS VARCHAR(2) OUTPUT,
 @OMENSAJE	AS VARCHAR(400) OUTPUT)
AS
 
DECLARE	@VPROYECTO			VARCHAR(50),
		@VPROYECTO_SERV		VARCHAR(50),
		@VSERVICIO			VARCHAR(50),
		@VFECHA				DATETIME,
		@VOBSERVACION		VARCHAR(400),
		@VNOMBRE			VARCHAR(100),
		@VCURSO				VARCHAR(100),
		@VASISTENTES		VARCHAR(50),
		@VID_DOC			VARCHAR(50),
		@VID_PROYECTO_DOCUM	VARCHAR(50),
		@VDESC_DOC_DET		VARCHAR(400), 
		@VGRUPO_DOC_DET		VARCHAR(50),
		@VCANT				INT,
		@VERROR				VARCHAR(50),
		@VAGENDA_ID			VARCHAR(50),
		@VID_SELEC			VARCHAR(100)
 
BEGIN	
 
	SET @OCODE = '0'
	SET @OMENSAJE = ''
 
	SELECT	@VPROYECTO		= ISNULL(PROYECTO_ID,''),
			@VPROYECTO_SERV = ISNULL(PROYECTO_SERV_ID,''),
			@VFECHA			= ISNULL(FECHA_CLC,''),
			@VCURSO			= ISNULL(CURSO_CLC,''),
			@VASISTENTES	= ISNULL(ASISTENTES_CLC,''),
			@VOBSERVACION	= ISNULL(OBSERVACION_HR,''),
			@VNOMBRE		= ISNULL(NOMBRE_CLC,''),
			@VERROR			= ISNULL(ERROR,''),
			@VAGENDA_ID		= ISNULL(AGENDA_ID,''),
			@VID_SELEC		= ISNULL(HOJA_RUTA_ID,'')
	FROM	XAGENDA
	WHERE	PAR_KEY = @IPKEYJOB
 
	SELECT	@VPROYECTO  = ID_PROYECTO,
			@VSERVICIO  = ID_SERVICIO
	FROM	LK_AGENDA
	WHERE	ID_AGENDA = @VAGENDA_ID
 
	IF (@VFECHA = '') BEGIN
		SET @OCODE = '1'
			
		UPDATE	XAGENDA
		SET		ERROR = 'SI', DESC_ERROR = 'Debe Completar el Campo Fecha'
		WHERE	PAR_KEY = @IPKEYJOB
		RETURN
	END
 
	IF (@VID_SELEC = '') BEGIN
 
		/* Grabo el ID de Documentacion que corresponda segun el Servicio, este siempre es solamente para Capacitacion 
			4	RE-PP-018
 
			1	Consultoria
			2	Auditoria
			3	Capacitacion
		*/
		SELECT	@VID_DOC =	'4'
 
		INSERT INTO LK_PROYECTO_DOCUM
		(ID_PROYECTO, ID_TIPO_SERVICIO, ID_DOCUMENTACION, FECHA_DOCUM, NRO_DOCUM_INTERNO,
			PARTICIPANTES_DOCUM, TEMAS_DOCUM, ADJUNTO_DOCUM,
			CONSULTOR, VISITA_MES, CONSULTOR_ACOMP, OBSERVACIONES,FECHA_CIERRE, ID_AGENDA)
		VALUES
		(@VPROYECTO, @VSERVICIO, @VID_DOC, @VFECHA, @VNOMBRE,
			@VASISTENTES, @VCURSO, NULL,
			NULL, NULL, NULL, @VOBSERVACION, NULL, @VAGENDA_ID)
 
			SELECT	@VID_PROYECTO_DOCUM = IDENT_CURRENT ('LK_PROYECTO_DOCUM')
 
			--RECUPERO TODOS LOS ITEMS QUE CORRESPONDEN AL DETALLE DE CHECKLIST--
			DECLARE Items CURSOR FOR 
			SELECT	DESC_DOC_DET, GRUPO_DOC_DET
			FROM	LK_DOCUMENTACION_DET
			WHERE	ID_DOCUMENTACION = @VID_DOC
			AND		STATUS_DOC_DET = '1'
			ORDER BY ID_DOCUMENTACION_DET
 
		OPEN Items  
		FETCH NEXT FROM Items INTO @VDESC_DOC_DET, @VGRUPO_DOC_DET  
 
		WHILE @@FETCH_STATUS = 0  
		BEGIN  
 
			INSERT INTO LK_PROYECTO_DOCUM_DET
			(ID_PROYECTO_DOCUM, DESC_DOC_DET, VALOR_DOC_DET, GRUPO_DOC_DET, ADJUNTO_DOC_DET)
			VALUES
			(@VID_PROYECTO_DOCUM, @VDESC_DOC_DET, NULL, @VGRUPO_DOC_DET, NULL)
 
			FETCH NEXT FROM Items INTO @VDESC_DOC_DET, @VGRUPO_DOC_DET
		END 
 
		CLOSE Items  
		DEALLOCATE Items
 
	END ELSE BEGIN
 
		UPDATE	LK_PROYECTO_DOCUM 
		SET		FECHA_DOCUM = @VFECHA, 
				NRO_DOCUM_INTERNO = @VNOMBRE,
				TEMAS_DOCUM = @VCURSO,
				PARTICIPANTES_DOCUM = @VASISTENTES, 
				OBSERVACIONES = @VOBSERVACION
		WHERE	ID_PROYECTO_DOCUM = @VID_SELEC
 
	END
 
	UPDATE	XAGENDA
	SET		--HOJA_RUTA_ID = @VID_PROYECTO_DOCUM,
			FECHA_CLC = NULL,
			OBSERVACION_HR = NULL,
			NOMBRE_CLC = NULL,
			CURSO_CLC = NULL,
			ASISTENTES_CLC = NULL
	WHERE	PAR_KEY = @IPKEYJOB
 
	IF (@OCODE = '0') BEGIN
		UPDATE	XAGENDA
		SET		ERROR = 'NO'
		WHERE	PAR_KEY = @IPKEYJOB
	END
END
 
