CREATE   PROCEDURE dbo.VCT_MIGRAR_PROYECTOS_DESDE_LK
 @Aplicar bit=0,@PermitirOrigenVacio bit=0
AS
BEGIN
 SET NOCOUNT ON; SET XACT_ABORT ON; SET IMPLICIT_TRANSACTIONS OFF;
 SET ANSI_NULLS ON; SET QUOTED_IDENTIFIER ON; SET ANSI_PADDING ON;
 SET ANSI_WARNINGS ON; SET ARITHABORT ON; SET CONCAT_NULL_YIELDS_NULL ON; SET NUMERIC_ROUNDABORT OFF;
IF DB_NAME()<>N'MuhlePROD' OR ISNULL(CONVERT(nvarchar(128),SERVERPROPERTY('ServerName')),N'')<>N'WIN-83AM68966R4'
 THROW 55000,'Ejecutar solamente en MuhlePROD / WIN-83AM68966R4 (desarrollo).',1;
 
 IF @@TRANCOUNT<>0 THROW 55003,'Ejecutar sin transacciones abiertas.',1;
 DECLARE @run uniqueidentifier=NEWID(),@ahora datetime=GETDATE(),@lock int,@sql nvarchar(max),@tabla nvarchar(517),
 @nombre sysname,@parent int,@trust bit,@identity sysname=NULL,@n bigint,@esperado bigint,@ultimo bigint,@valor bigint,@columna sysname,@hay bit;
 BEGIN TRY
  BEGIN TRANSACTION;
  EXEC @lock=sys.sp_getapplock @Resource=N'VCT_MIG_MODELO_NUEVO',@LockMode=N'Exclusive',@LockOwner=N'Transaction',@LockTimeout=0;
  IF @lock<0 THROW 55004,'Hay otra migracion en curso.',1;
  CREATE TABLE #Excepciones(TABLA_ORIGEN varchar(100) COLLATE DATABASE_DEFAULT,ID_ORIGEN bigint,CAMPO varchar(100) COLLATE DATABASE_DEFAULT,OBSERVACIONES varchar(max) COLLATE DATABASE_DEFAULT);
  IF (SELECT COUNT(*) FROM dbo.VCT_PRM_PROYECTOS_ESTADOS WHERE CODIGO COLLATE DATABASE_DEFAULT='BORRADOR')<>1
    OR (SELECT COUNT(*) FROM dbo.VCT_PRM_PROYECTOS_ROLES WHERE CODIGO COLLATE DATABASE_DEFAULT='CONSULTOR')<>1
    OR (SELECT COUNT(*) FROM dbo.VCT_PRM_PROYECTOS_ROLES WHERE CODIGO COLLATE DATABASE_DEFAULT='CONSULTOR_LIDER')<>1
   THROW 55005,'Faltan estados/roles del modelo: BORRADOR, CONSULTOR, CONSULTOR_LIDER.',1;
  DECLARE @borrador int=(SELECT ID FROM dbo.VCT_PRM_PROYECTOS_ESTADOS WHERE CODIGO COLLATE DATABASE_DEFAULT='BORRADOR'),
   @rol int=(SELECT ID FROM dbo.VCT_PRM_PROYECTOS_ROLES WHERE CODIGO COLLATE DATABASE_DEFAULT='CONSULTOR'),
   @lider int=(SELECT ID FROM dbo.VCT_PRM_PROYECTOS_ROLES WHERE CODIGO COLLATE DATABASE_DEFAULT='CONSULTOR_LIDER');
  SELECT CAST(l.CODIGO AS varchar(100)) COLLATE DATABASE_DEFAULT AS [CODIGO],
   CAST(l.FECHA_INICIO_REAL AS datetime) AS [FECHA_INICIO_REAL],
   CAST(l.FECHA_FIN_REAL AS datetime) AS [FECHA_FIN_REAL],
   CAST(l.MONTO_PRES AS numeric(15, 2)) AS [MONTO_PRES],
   CAST(l.MONTO_PRES_VIAT AS numeric(15, 2)) AS [MONTO_PRES_VIAT],
   CAST(l.COSTO_MO AS numeric(15, 2)) AS [COSTO_MO],
   CAST(l.COSTO_VIAT AS numeric(15, 2)) AS [COSTO_VIAT],
   CAST(l.COSTO_VARIOS AS numeric(15, 2)) AS [COSTO_VARIOS],
   CAST(l.MONTO_TOTAL AS numeric(15, 2)) AS [MONTO_TOTAL],
   CAST(l.COSTO_TOTAL AS numeric(15, 2)) AS [COSTO_TOTAL],
   CAST(l.MONTO_COBRADO AS numeric(15, 2)) AS [MONTO_COBRADO],
   CAST(l.OBSERV_RENTA AS varchar(4000)) COLLATE DATABASE_DEFAULT AS [OBSERV_RENTA],
   CAST(l.FECHA_PRESUPUESTO AS datetime) AS [FECHA_PRESUPUESTO],
   CAST(l.FECHA_ALTA AS datetime) AS [FECHA_ALTA],
   CAST(l.USUARIO_ALTA AS varchar(100)) COLLATE DATABASE_DEFAULT AS [USUARIO_ALTA],
   CAST(l.TOTAL_HORAS_PROYECTADAS AS int) AS [TOTAL_HORAS_PROYECTADAS],
   CAST(l.NIVEL_RIESGO AS varchar(50)) COLLATE DATABASE_DEFAULT AS [NIVEL_RIESGO],
   CAST(l.ESTADO_COBRO AS varchar(50)) COLLATE DATABASE_DEFAULT AS [ESTADO_COBRO],
   CAST(l.ID_PROYECTO AS int) AS [ID],
   CAST(l.ID_CLIENTE AS int) AS [IDCLIENTE],
   CAST(COALESCE(NULLIF(LTRIM(RTRIM(l.NORMA_REF)),''),NULLIF(LTRIM(RTRIM(l.CODIGO)),''),CONCAT('Proyecto ',l.ID_PROYECTO)) AS varchar(300)) COLLATE DATABASE_DEFAULT AS [NOMBRE],
   CAST(l.NORMA_REF AS varchar(300)) COLLATE DATABASE_DEFAULT AS [REFERENCIA],
   CAST(COALESCE(e.ID,@borrador) AS int) AS [ID_ESTADO],
   CAST(l.FECHA_INICIO_TOTAL AS datetime) AS [FECHA_INICIO],
   CAST(l.FECHA_FIN_TOTAL AS datetime) AS [FECHA_FIN],
   CAST(ISNULL(l.PORCENTAJE_AVANCE_TOTAL,0) AS int) AS [PORCENTAJE_AVANCE],
   CAST('ARS' AS varchar(3)) COLLATE DATABASE_DEFAULT AS [MONEDA],
   CAST(CONCAT(CAST('LK_PROYECTO - valores originales: ' AS varchar(max)),'; ID_PROYECTO=',COALESCE(CONVERT(varchar(max),l.[ID_PROYECTO]),'<NULL>'),'; ID_COTIZACION=',COALESCE(CONVERT(varchar(max),l.[ID_COTIZACION]),'<NULL>'),'; ID_CLIENTE=',COALESCE(CONVERT(varchar(max),l.[ID_CLIENTE]),'<NULL>'),'; NORMA_REF=',COALESCE(CONVERT(varchar(max),l.[NORMA_REF]),'<NULL>'),'; FECHA_ALTA=',COALESCE(CONVERT(varchar(max),l.[FECHA_ALTA],126),'<NULL>'),'; USUARIO_ALTA=',COALESCE(CONVERT(varchar(max),l.[USUARIO_ALTA]),'<NULL>'),'; ESTADO_PROYECTO_TOTAL=',COALESCE(CONVERT(varchar(max),l.[ESTADO_PROYECTO_TOTAL]),'<NULL>'),'; FECHA_INICIO_TOTAL=',COALESCE(CONVERT(varchar(max),l.[FECHA_INICIO_TOTAL],126),'<NULL>'),'; FECHA_FIN_TOTAL=',COALESCE(CONVERT(varchar(max),l.[FECHA_FIN_TOTAL],126),'<NULL>'),'; FECHA_INICIO_REAL=',COALESCE(CONVERT(varchar(max),l.[FECHA_INICIO_REAL],126),'<NULL>'),'; FECHA_FIN_REAL=',COALESCE(CONVERT(varchar(max),l.[FECHA_FIN_REAL],126),'<NULL>'),'; TOTAL_HORAS_PROYECTADAS=',COALESCE(CONVERT(varchar(max),l.[TOTAL_HORAS_PROYECTADAS]),'<NULL>'),'; TOTAL_HORAS_EJECUTADAS=',COALESCE(CONVERT(varchar(max),l.[TOTAL_HORAS_EJECUTADAS]),'<NULL>'),'; MONTO_PRESUP=',COALESCE(CONVERT(varchar(max),l.[MONTO_PRESUP]),'<NULL>'),'; MONTO_COBRADO=',COALESCE(CONVERT(varchar(max),l.[MONTO_COBRADO]),'<NULL>'),'; ESTADO_COBRO=',COALESCE(CONVERT(varchar(max),l.[ESTADO_COBRO]),'<NULL>'),'; PORCENTAJE_AVANCE_TOTAL=',COALESCE(CONVERT(varchar(max),l.[PORCENTAJE_AVANCE_TOTAL]),'<NULL>'),'; CODIGO=',COALESCE(CONVERT(varchar(max),l.[CODIGO]),'<NULL>'),'; OBSERVACIONES=',COALESCE(CONVERT(varchar(max),l.[OBSERVACIONES]),'<NULL>'),'; NORMAS=',COALESCE(CONVERT(varchar(max),l.[NORMAS]),'<NULL>'),'; CONTACTO=',COALESCE(CONVERT(varchar(max),l.[CONTACTO]),'<NULL>'),'; NIVEL_RIESGO=',COALESCE(CONVERT(varchar(max),l.[NIVEL_RIESGO]),'<NULL>'),'; MONTO_PRES=',COALESCE(CONVERT(varchar(max),l.[MONTO_PRES]),'<NULL>'),'; MONTO_PRES_VIAT=',COALESCE(CONVERT(varchar(max),l.[MONTO_PRES_VIAT]),'<NULL>'),'; COSTO_MO=',COALESCE(CONVERT(varchar(max),l.[COSTO_MO]),'<NULL>'),'; COSTO_VIAT=',COALESCE(CONVERT(varchar(max),l.[COSTO_VIAT]),'<NULL>'),'; COSTO_VARIOS=',COALESCE(CONVERT(varchar(max),l.[COSTO_VARIOS]),'<NULL>'),'; MONTO_TOTAL=',COALESCE(CONVERT(varchar(max),l.[MONTO_TOTAL]),'<NULL>'),'; COSTO_TOTAL=',COALESCE(CONVERT(varchar(max),l.[COSTO_TOTAL]),'<NULL>'),'; OBSERV_RENTA=',COALESCE(CONVERT(varchar(max),l.[OBSERV_RENTA]),'<NULL>'),'; FECHA_PRESUPUESTO=',COALESCE(CONVERT(varchar(max),l.[FECHA_PRESUPUESTO],126),'<NULL>')) AS varchar(max)) COLLATE DATABASE_DEFAULT AS [OBSERVACIONES],
   CAST(NULL AS int) AS [IDPROPUESTA],
   CAST(0 AS int) AS [TOTAL_HORAS_EJECUTADAS],
   CAST(ct.ID AS int) AS [IDCONTACTO] INTO #P FROM dbo.LK_PROYECTO l WITH(HOLDLOCK) LEFT JOIN dbo.VCT_PRM_PROYECTOS_ESTADOS e ON e.CODIGO COLLATE DATABASE_DEFAULT=UPPER(LTRIM(RTRIM(l.ESTADO_PROYECTO_TOTAL))) COLLATE DATABASE_DEFAULT OUTER APPLY(SELECT CASE WHEN COUNT(*)=1 THEN MAX(c.ID) END ID FROM dbo.VCT_CONTACTOS c WHERE c.IDCLIENTE=l.ID_CLIENTE AND (LTRIM(RTRIM(CONCAT(c.NOMBRES,' ',c.APELLIDO))) COLLATE DATABASE_DEFAULT=LTRIM(RTRIM(l.CONTACTO)) COLLATE DATABASE_DEFAULT OR LTRIM(RTRIM(CONCAT(c.APELLIDO,' ',c.NOMBRES))) COLLATE DATABASE_DEFAULT=LTRIM(RTRIM(l.CONTACTO)) COLLATE DATABASE_DEFAULT)) ct;
  CREATE UNIQUE CLUSTERED INDEX IX_P_ID ON #P([ID]);
  IF NOT EXISTS(SELECT 1 FROM #P) AND @PermitirOrigenVacio=0 THROW 55006,'LK_PROYECTO vacia: no se borra el destino.',1;
  INSERT #Excepciones SELECT 'LK_PROYECTO',[ID],'ID_CLIENTE',CONCAT(CAST(N'Cliente inexistente. Proyecto omitido; original conservado: ' AS nvarchar(max)),OBSERVACIONES) FROM #P WHERE NOT EXISTS(SELECT 1 FROM dbo.VCT_CLIENTES c WHERE c.ID=#P.IDCLIENTE);
  DELETE #P WHERE NOT EXISTS(SELECT 1 FROM dbo.VCT_CLIENTES c WHERE c.ID=#P.IDCLIENTE);
  INSERT #Excepciones SELECT 'LK_PROYECTO',p.ID,'ESTADO',CONCAT(N'Estado desconocido; BORRADOR. ',p.OBSERVACIONES) FROM #P p JOIN dbo.LK_PROYECTO l ON l.ID_PROYECTO=p.ID WHERE NOT EXISTS(SELECT 1 FROM dbo.VCT_PRM_PROYECTOS_ESTADOS e WHERE e.CODIGO COLLATE DATABASE_DEFAULT=UPPER(LTRIM(RTRIM(l.ESTADO_PROYECTO_TOTAL))) COLLATE DATABASE_DEFAULT);
  INSERT #Excepciones SELECT 'LK_PROYECTO',p.ID,'CONTACTO',CONCAT(N'Contacto sin coincidencia unica para este cliente; IDCONTACTO NULL. ',p.OBSERVACIONES) FROM #P p JOIN dbo.LK_PROYECTO l ON l.ID_PROYECTO=p.ID WHERE p.IDCONTACTO IS NULL AND NULLIF(LTRIM(RTRIM(l.CONTACTO)),'') IS NOT NULL;
  SELECT CAST(l.ID_PROYECTO AS int) AS [ID_PROYECTO],
   CAST(l.FECHA_INICIO AS datetime) AS [FECHA_INICIO],
   CAST(l.FECHA_FIN AS datetime) AS [FECHA_FIN],
   CAST(l.FECHA_INICIO_REAL AS datetime) AS [FECHA_INICIO_REAL],
   CAST(l.FECHA_FIN_REAL AS datetime) AS [FECHA_FIN_REAL],
   CAST(l.FECHA_ALTA AS datetime) AS [FECHA_ALTA],
   CAST(l.USUARIO_ALTA AS varchar(100)) COLLATE DATABASE_DEFAULT AS [USUARIO_ALTA],
   CAST(l.LUGAR AS varchar(300)) COLLATE DATABASE_DEFAULT AS [LUGAR],
   CAST(l.TOTAL_HORAS_PROYECTADAS AS int) AS [TOTAL_HORAS_PROYECTADAS],
   CAST(l.ID_PROYECTO_SERVICIO AS int) AS [ID],
   CAST(l.ID_TIPO_SERVICIO AS int) AS [ID_SERVICIO],
   CAST(COALESCE(e.ID,@borrador) AS int) AS [ID_ESTADO],
   CAST(CASE WHEN ROW_NUMBER() OVER(PARTITION BY l.ID_PROYECTO ORDER BY l.ID_PROYECTO_SERVICIO)=1 THEN 1 ELSE 0 END AS bit) AS [PRINCIPAL],
   CAST(ROW_NUMBER() OVER(PARTITION BY l.ID_PROYECTO ORDER BY l.ID_PROYECTO_SERVICIO) AS int) AS [ORDEN],
   CAST(ROW_NUMBER() OVER(PARTITION BY l.ID_PROYECTO,l.ID_TIPO_SERVICIO ORDER BY l.ID_PROYECTO_SERVICIO) AS int) AS [SECUENCIA],
   CAST(ISNULL(l.PORCENTAJE_AVANCE,0) AS int) AS [PORCENTAJE_AVANCE],
   CAST(CONCAT(CAST('LK_PROYECTO_SERVICIO - valores originales: ' AS varchar(max)),'; ID_PROYECTO_SERVICIO=',COALESCE(CONVERT(varchar(max),l.[ID_PROYECTO_SERVICIO]),'<NULL>'),'; ID_PROYECTO=',COALESCE(CONVERT(varchar(max),l.[ID_PROYECTO]),'<NULL>'),'; ID_TIPO_SERVICIO=',COALESCE(CONVERT(varchar(max),l.[ID_TIPO_SERVICIO]),'<NULL>'),'; PORCENTAJE_AVANCE=',COALESCE(CONVERT(varchar(max),l.[PORCENTAJE_AVANCE]),'<NULL>'),'; FECHA_ALTA=',COALESCE(CONVERT(varchar(max),l.[FECHA_ALTA],126),'<NULL>'),'; USUARIO_ALTA=',COALESCE(CONVERT(varchar(max),l.[USUARIO_ALTA]),'<NULL>'),'; ESTADO_PROYECTO=',COALESCE(CONVERT(varchar(max),l.[ESTADO_PROYECTO]),'<NULL>'),'; FECHA_INICIO=',COALESCE(CONVERT(varchar(max),l.[FECHA_INICIO],126),'<NULL>'),'; FECHA_FIN=',COALESCE(CONVERT(varchar(max),l.[FECHA_FIN],126),'<NULL>'),'; FECHA_INICIO_REAL=',COALESCE(CONVERT(varchar(max),l.[FECHA_INICIO_REAL],126),'<NULL>'),'; FECHA_FIN_REAL=',COALESCE(CONVERT(varchar(max),l.[FECHA_FIN_REAL],126),'<NULL>'),'; TOTAL_HORAS_PROYECTADAS=',COALESCE(CONVERT(varchar(max),l.[TOTAL_HORAS_PROYECTADAS]),'<NULL>'),'; TOTAL_HORAS_EJECUTADAS=',COALESCE(CONVERT(varchar(max),l.[TOTAL_HORAS_EJECUTADAS]),'<NULL>'),'; MONTO_PRESUP=',COALESCE(CONVERT(varchar(max),l.[MONTO_PRESUP]),'<NULL>'),'; MONTO_COBRADO=',COALESCE(CONVERT(varchar(max),l.[MONTO_COBRADO]),'<NULL>'),'; ESTADO_COBRO=',COALESCE(CONVERT(varchar(max),l.[ESTADO_COBRO]),'<NULL>'),'; FRECUENCIA_ENVIO=',COALESCE(CONVERT(varchar(max),l.[FRECUENCIA_ENVIO]),'<NULL>'),'; DOC_EMPRESA=',COALESCE(CONVERT(varchar(max),l.[DOC_EMPRESA]),'<NULL>'),'; MANUALES=',COALESCE(CONVERT(varchar(max),l.[MANUALES]),'<NULL>'),'; REQUISITO_INGRESO=',COALESCE(CONVERT(varchar(max),l.[REQUISITO_INGRESO]),'<NULL>'),'; CV_CERTIFICADOS=',COALESCE(CONVERT(varchar(max),l.[CV_CERTIFICADOS]),'<NULL>'),'; LOGISTICA=',COALESCE(CONVERT(varchar(max),l.[LOGISTICA]),'<NULL>'),'; NOMBRE_CURSO=',COALESCE(CONVERT(varchar(max),l.[NOMBRE_CURSO]),'<NULL>'),'; MATERIALES=',COALESCE(CONVERT(varchar(max),l.[MATERIALES]),'<NULL>'),'; ESTADO_ENVIO=',COALESCE(CONVERT(varchar(max),l.[ESTADO_ENVIO]),'<NULL>'),'; RECIBIDO=',COALESCE(CONVERT(varchar(max),l.[RECIBIDO]),'<NULL>'),'; CIERRE=',COALESCE(CONVERT(varchar(max),l.[CIERRE]),'<NULL>'),'; NOMBRE=',COALESCE(CONVERT(varchar(max),l.[NOMBRE]),'<NULL>'),'; LUGAR=',COALESCE(CONVERT(varchar(max),l.[LUGAR]),'<NULL>')) AS varchar(max)) COLLATE DATABASE_DEFAULT AS [OBSERVACIONES],
   CAST(COALESCE(NULLIF(l.NOMBRE,''),NULLIF(l.NOMBRE_CURSO,'')) AS varchar(300)) COLLATE DATABASE_DEFAULT AS [NOMBRE],
   CAST(0 AS int) AS [TOTAL_HORAS_EJECUTADAS] INTO #S FROM dbo.LK_PROYECTO_SERVICIO l WITH(HOLDLOCK) LEFT JOIN dbo.VCT_PRM_PROYECTOS_ESTADOS e ON e.CODIGO COLLATE DATABASE_DEFAULT=UPPER(LTRIM(RTRIM(l.ESTADO_PROYECTO))) COLLATE DATABASE_DEFAULT;
  CREATE UNIQUE CLUSTERED INDEX IX_S_ID ON #S([ID]);
  INSERT #Excepciones SELECT 'LK_PROYECTO_SERVICIO',[ID],'PADRES',CONCAT(CAST(N'Servicio con proyecto/tipo inexistente. Omitido: ' AS nvarchar(max)),OBSERVACIONES) FROM #S WHERE NOT EXISTS(SELECT 1 FROM #P p WHERE p.ID=#S.ID_PROYECTO) OR ID_SERVICIO NOT IN (1,2,3) OR NOT EXISTS(SELECT 1 FROM dbo.VCT_PRM_SERVICIOS s WHERE s.ID=#S.ID_SERVICIO);
  DELETE #S WHERE NOT EXISTS(SELECT 1 FROM #P p WHERE p.ID=#S.ID_PROYECTO) OR ID_SERVICIO NOT IN (1,2,3) OR NOT EXISTS(SELECT 1 FROM dbo.VCT_PRM_SERVICIOS s WHERE s.ID=#S.ID_SERVICIO);
  INSERT #Excepciones SELECT 'LK_PROYECTO_SERVICIO',s.ID,'ESTADO',CONCAT(N'Estado desconocido; BORRADOR. ',s.OBSERVACIONES) FROM #S s JOIN dbo.LK_PROYECTO_SERVICIO l ON l.ID_PROYECTO_SERVICIO=s.ID WHERE NOT EXISTS(SELECT 1 FROM dbo.VCT_PRM_PROYECTOS_ESTADOS e WHERE e.CODIGO COLLATE DATABASE_DEFAULT=UPPER(LTRIM(RTRIM(l.ESTADO_PROYECTO))) COLLATE DATABASE_DEFAULT);
  CREATE INDEX IX_S_PROY_TIPO ON #S(ID_PROYECTO,ID_SERVICIO) INCLUDE(ID,LUGAR);
  INSERT #Excepciones SELECT 'LK_PROYECTO',[ID],'FECHA_FIN',CONCAT(CAST(N'Fecha final anterior al inicio; se carga NULL: ' AS nvarchar(max)),OBSERVACIONES) FROM #P WHERE FECHA_FIN<FECHA_INICIO;
  UPDATE #P SET FECHA_FIN=NULL WHERE FECHA_FIN<FECHA_INICIO;
  INSERT #Excepciones SELECT 'LK_PROYECTO',[ID],'FECHA_FIN_REAL',CONCAT(CAST(N'Fecha final anterior al inicio; se carga NULL: ' AS nvarchar(max)),OBSERVACIONES) FROM #P WHERE FECHA_FIN_REAL<FECHA_INICIO_REAL;
  UPDATE #P SET FECHA_FIN_REAL=NULL WHERE FECHA_FIN_REAL<FECHA_INICIO_REAL;
  INSERT #Excepciones SELECT 'LK_PROYECTO',[ID],'PORCENTAJE_AVANCE',CONCAT(CAST(N'Avance fuera de rango; se limita a 0..100: ' AS nvarchar(max)),OBSERVACIONES) FROM #P WHERE PORCENTAJE_AVANCE NOT BETWEEN 0 AND 100;
  UPDATE #P SET PORCENTAJE_AVANCE=CASE WHEN PORCENTAJE_AVANCE<0 THEN 0 WHEN PORCENTAJE_AVANCE>100 THEN 100 ELSE PORCENTAJE_AVANCE END;
  INSERT #Excepciones SELECT 'LK_PROYECTO_SERVICIO',[ID],'FECHA_FIN',CONCAT(CAST(N'Fecha final anterior al inicio; se carga NULL: ' AS nvarchar(max)),OBSERVACIONES) FROM #S WHERE FECHA_FIN<FECHA_INICIO;
  UPDATE #S SET FECHA_FIN=NULL WHERE FECHA_FIN<FECHA_INICIO;
  INSERT #Excepciones SELECT 'LK_PROYECTO_SERVICIO',[ID],'FECHA_FIN_REAL',CONCAT(CAST(N'Fecha final anterior al inicio; se carga NULL: ' AS nvarchar(max)),OBSERVACIONES) FROM #S WHERE FECHA_FIN_REAL<FECHA_INICIO_REAL;
  UPDATE #S SET FECHA_FIN_REAL=NULL WHERE FECHA_FIN_REAL<FECHA_INICIO_REAL;
  INSERT #Excepciones SELECT 'LK_PROYECTO_SERVICIO',[ID],'PORCENTAJE_AVANCE',CONCAT(CAST(N'Avance fuera de rango; se limita a 0..100: ' AS nvarchar(max)),OBSERVACIONES) FROM #S WHERE PORCENTAJE_AVANCE NOT BETWEEN 0 AND 100;
  UPDATE #S SET PORCENTAJE_AVANCE=CASE WHEN PORCENTAJE_AVANCE<0 THEN 0 WHEN PORCENTAJE_AVANCE>100 THEN 100 ELSE PORCENTAJE_AVANCE END;
  SELECT CAST(l.ID_PROYECTO AS int) AS [ID_PROYECTO],
   CAST(l.DIAS AS int) AS [DIAS],
   CAST(l.OBSERVADOR AS varchar(400)) COLLATE DATABASE_DEFAULT AS [OBSERVADOR],
   CAST(l.OBSERV_LOGISTICA AS varchar(400)) COLLATE DATABASE_DEFAULT AS [OBSERV_LOGISTICA],
   CAST(l.OBSERV_CALIF AS varchar(400)) COLLATE DATABASE_DEFAULT AS [OBSERV_CALIF],
   CAST(l.INDICADOR_HR AS varchar(50)) COLLATE DATABASE_DEFAULT AS [INDICADOR_HR],
   CAST(l.FECHA_ALTA AS datetime) AS [FECHA_ALTA],
   CAST(l.USUARIO_ALTA AS varchar(100)) COLLATE DATABASE_DEFAULT AS [USUARIO_ALTA],
   CAST(l.ID_AGENDA AS int) AS [ID],
   CAST(COALESCE(s.ID,fb.ID) AS int) AS [ID_PROYECTO_SERVICIO],
   CAST(l.FECHA AS datetime) AS [FECHA_DESDE],
   CAST(l.FECHA_HASTA AS datetime) AS [FECHA_HASTA],
   CAST(COALESCE(s.LUGAR,fs.LUGAR) AS varchar(300)) COLLATE DATABASE_DEFAULT AS [LUGAR],
   CAST(CONCAT('Visita migrada LK_AGENDA ',l.ID_AGENDA) AS varchar(1000)) COLLATE DATABASE_DEFAULT AS [DESCRIPCION],
   CAST(CONCAT(CAST('LK_AGENDA - valores originales: ' AS varchar(max)),'; ID_AGENDA=',COALESCE(CONVERT(varchar(max),l.[ID_AGENDA]),'<NULL>'),'; FECHA=',COALESCE(CONVERT(varchar(max),l.[FECHA],126),'<NULL>'),'; ID_CLIENTE=',COALESCE(CONVERT(varchar(max),l.[ID_CLIENTE]),'<NULL>'),'; ID_PROYECTO=',COALESCE(CONVERT(varchar(max),l.[ID_PROYECTO]),'<NULL>'),'; ID_SERVICIO=',COALESCE(CONVERT(varchar(max),l.[ID_SERVICIO]),'<NULL>'),'; ID_CONSULTOR=',COALESCE(CONVERT(varchar(max),l.[ID_CONSULTOR]),'<NULL>'),'; DIA=',COALESCE(CONVERT(varchar(max),l.[DIA]),'<NULL>'),'; MES=',COALESCE(CONVERT(varchar(max),l.[MES]),'<NULL>'),'; ANO=',COALESCE(CONVERT(varchar(max),l.[ANO]),'<NULL>'),'; ESTADO=',COALESCE(CONVERT(varchar(max),l.[ESTADO]),'<NULL>'),'; NORMA=',COALESCE(CONVERT(varchar(max),l.[NORMA]),'<NULL>'),'; FECHA_ALTA=',COALESCE(CONVERT(varchar(max),l.[FECHA_ALTA],126),'<NULL>'),'; USUARIO_ALTA=',COALESCE(CONVERT(varchar(max),l.[USUARIO_ALTA]),'<NULL>'),'; OBSERVADOR=',COALESCE(CONVERT(varchar(max),l.[OBSERVADOR]),'<NULL>'),'; FECHA_HASTA=',COALESCE(CONVERT(varchar(max),l.[FECHA_HASTA],126),'<NULL>'),'; DIAS=',COALESCE(CONVERT(varchar(max),l.[DIAS]),'<NULL>'),'; OBSERV_LOGISTICA=',COALESCE(CONVERT(varchar(max),l.[OBSERV_LOGISTICA]),'<NULL>'),'; OBSERV_CALIF=',COALESCE(CONVERT(varchar(max),l.[OBSERV_CALIF]),'<NULL>'),'; LIDER=',COALESCE(CONVERT(varchar(max),l.[LIDER]),'<NULL>'),'; PROYECTO_SERV_ID=',COALESCE(CONVERT(varchar(max),l.[PROYECTO_SERV_ID]),'<NULL>'),'; INDICADOR_HR=',COALESCE(CONVERT(varchar(max),l.[INDICADOR_HR]),'<NULL>')) AS varchar(max)) COLLATE DATABASE_DEFAULT AS [OBSERVACIONES],
   CAST(CASE UPPER(LTRIM(RTRIM(l.ESTADO))) WHEN 'C' THEN 'CONFIRMADO' WHEN 'P' THEN 'PENDIENTE' ELSE 'PENDIENTE' END AS varchar(50)) COLLATE DATABASE_DEFAULT AS [ESTADO],
   CAST(0 AS numeric(15,2)) AS [TOTAL_HORAS_EJECUTADAS],
   CAST(0 AS numeric(15,2)) AS [HORAS_SIN_CONSULTOR] INTO #V FROM dbo.LK_AGENDA l WITH(HOLDLOCK) LEFT JOIN #S s ON s.ID=l.PROYECTO_SERV_ID AND s.ID_PROYECTO=l.ID_PROYECTO AND s.ID_SERVICIO=l.ID_SERVICIO OUTER APPLY(SELECT CASE WHEN COUNT(*)=1 THEN MAX(x.ID) END ID FROM #S x WHERE x.ID_PROYECTO=l.ID_PROYECTO AND x.ID_SERVICIO=l.ID_SERVICIO) fb LEFT JOIN #S fs ON fs.ID=fb.ID;
  CREATE UNIQUE CLUSTERED INDEX IX_V_ID ON #V([ID]);
  CREATE INDEX IX_V_SERV ON #V(ID_PROYECTO_SERVICIO) INCLUDE(TOTAL_HORAS_EJECUTADAS);
  CREATE INDEX IX_V_PROY ON #V(ID_PROYECTO) INCLUDE(TOTAL_HORAS_EJECUTADAS);
  INSERT #Excepciones SELECT 'LK_AGENDA',[ID],'SERVICIO',CONCAT(CAST(N'Visita sin proyecto/servicio identificable. Omitida: ' AS nvarchar(max)),OBSERVACIONES) FROM #V WHERE ID_PROYECTO_SERVICIO IS NULL OR NOT EXISTS(SELECT 1 FROM #P p WHERE p.ID=#V.ID_PROYECTO);
  DELETE #V WHERE ID_PROYECTO_SERVICIO IS NULL OR NOT EXISTS(SELECT 1 FROM #P p WHERE p.ID=#V.ID_PROYECTO);
  INSERT #Excepciones SELECT 'LK_AGENDA',v.ID,'PROYECTO_SERV_ID',CONCAT(N'Servicio original inconsistente; asignado el unico del proyecto y tipo. ',v.OBSERVACIONES) FROM #V v JOIN dbo.LK_AGENDA l ON l.ID_AGENDA=v.ID WHERE ISNULL(l.PROYECTO_SERV_ID,-1)<>v.ID_PROYECTO_SERVICIO;
  INSERT #Excepciones SELECT 'LK_AGENDA',v.ID,'ESTADO',CONCAT(N'Estado desconocido; PENDIENTE. ',v.OBSERVACIONES) FROM #V v JOIN dbo.LK_AGENDA l ON l.ID_AGENDA=v.ID WHERE ISNULL(UPPER(LTRIM(RTRIM(l.ESTADO))),'') NOT IN ('C','P');
  INSERT #Excepciones SELECT 'LK_AGENDA',v.ID,'ID_CLIENTE',CONCAT(N'Cliente de agenda diferente al proyecto; se conserva cliente del proyecto. ',v.OBSERVACIONES) FROM #V v JOIN #P p ON p.ID=v.ID_PROYECTO JOIN dbo.LK_AGENDA l ON l.ID_AGENDA=v.ID WHERE l.ID_CLIENTE<>p.IDCLIENTE;
  INSERT #Excepciones SELECT 'LK_AGENDA',[ID],'FECHA_HASTA',CONCAT(CAST(N'Fecha hasta invalida; NULL: ' AS nvarchar(max)),OBSERVACIONES) FROM #V WHERE FECHA_HASTA<FECHA_DESDE;
  UPDATE #V SET FECHA_HASTA=NULL WHERE FECHA_HASTA<FECHA_DESDE;
  INSERT #Excepciones SELECT 'LK_AGENDA',[ID],'DIAS',CONCAT(CAST(N'Dias negativos; NULL: ' AS nvarchar(max)),OBSERVACIONES) FROM #V WHERE DIAS<0;
  UPDATE #V SET DIAS=NULL WHERE DIAS<0;
  SELECT CAST(l.FECHA AS date) AS [FECHA],
   CAST(l.DIA AS tinyint) AS [DIA],
   CAST(l.MES AS tinyint) AS [MES],
   CAST(l.ANO AS int) AS [ANO],
   CAST(l.ISHOLIDAY AS bit) AS [ISHOLIDAY],
   CAST(l.HOLIDAYTEXT AS varchar(64)) COLLATE DATABASE_DEFAULT AS [HOLIDAYTEXT],
   CAST(l.TIPO AS varchar(50)) COLLATE DATABASE_DEFAULT AS [TIPO],
   CAST(l.FECHA_ALTA AS datetime) AS [FECHA_ALTA],
   CAST(l.USUARIO_ALTA AS varchar(100)) COLLATE DATABASE_DEFAULT AS [USUARIO_ALTA],
   CAST(l.HORAS AS int) AS [HORAS],
   CAST(l.DESCRIPCION AS varchar(300)) COLLATE DATABASE_DEFAULT AS [DESCRIPCION],
   CAST(l.HORAS_DISP AS int) AS [HORAS_DISP],
   CAST(ROW_NUMBER() OVER(ORDER BY l.FECHA,l.ID_EMPLEADO,l.TIPO,l.HOLIDAYTEXT) AS bigint) AS [ID],
   CAST(CASE WHEN c.ID IS NOT NULL THEN 'CONSULTOR' WHEN e.ID IS NOT NULL THEN 'EMPLEADO' ELSE 'DESCONOCIDO' END AS varchar(30)) COLLATE DATABASE_DEFAULT AS [TIPO_ENTIDAD],
   CAST(c.ID AS int) AS [ID_CONSULTOR],
   CAST(e.ID AS int) AS [ID_EMPLEADO],
   CAST(l.ID_EMPLEADO AS int) AS [ID_PERSONA_ORIGEN],
   CAST(v.ID AS int) AS [ID_VISITA],
   CAST(TRY_CAST(NULLIF(LTRIM(RTRIM(l.HOLIDAYTEXT)),'') AS int) AS int) AS [ID_AGENDA_ORIGEN],
   CAST(NULL AS int) AS [ID_ESTADO],
   CAST(CONCAT(CAST('LK_AGENDA_EMPLEADO - valores originales: ' AS varchar(max)),'; ID_EMPLEADO=',COALESCE(CONVERT(varchar(max),l.[ID_EMPLEADO]),'<NULL>'),'; FECHA=',COALESCE(CONVERT(varchar(max),l.[FECHA],126),'<NULL>'),'; DIA=',COALESCE(CONVERT(varchar(max),l.[DIA]),'<NULL>'),'; MES=',COALESCE(CONVERT(varchar(max),l.[MES]),'<NULL>'),'; ANO=',COALESCE(CONVERT(varchar(max),l.[ANO]),'<NULL>'),'; ISHOLIDAY=',COALESCE(CONVERT(varchar(max),l.[ISHOLIDAY]),'<NULL>'),'; HOLIDAYTEXT=',COALESCE(CONVERT(varchar(max),l.[HOLIDAYTEXT]),'<NULL>'),'; TIPO=',COALESCE(CONVERT(varchar(max),l.[TIPO]),'<NULL>'),'; FECHA_ALTA=',COALESCE(CONVERT(varchar(max),l.[FECHA_ALTA],126),'<NULL>'),'; USUARIO_ALTA=',COALESCE(CONVERT(varchar(max),l.[USUARIO_ALTA]),'<NULL>'),'; HORAS=',COALESCE(CONVERT(varchar(max),l.[HORAS]),'<NULL>'),'; DESCRIPCION=',COALESCE(CONVERT(varchar(max),l.[DESCRIPCION]),'<NULL>'),'; HORAS_DISP=',COALESCE(CONVERT(varchar(max),l.[HORAS_DISP]),'<NULL>')) AS varchar(max)) COLLATE DATABASE_DEFAULT AS [OBSERVACIONES] INTO #D FROM dbo.LK_AGENDA_EMPLEADO l WITH(HOLDLOCK) LEFT JOIN dbo.VCT_CONSULTORES c ON c.ID=l.ID_EMPLEADO LEFT JOIN dbo.VCT_EMPLEADOS e ON e.ID=l.ID_EMPLEADO LEFT JOIN #V v ON v.ID=TRY_CAST(NULLIF(LTRIM(RTRIM(l.HOLIDAYTEXT)),'') AS int) AND UPPER(LTRIM(RTRIM(l.TIPO))) COLLATE DATABASE_DEFAULT='A';
  CREATE UNIQUE CLUSTERED INDEX IX_D_ID ON #D([ID]);
  CREATE INDEX IX_D_VISITA_PERSONA ON #D(ID_VISITA,ID_CONSULTOR) INCLUDE(HORAS);
  INSERT #Excepciones SELECT 'LK_AGENDA_EMPLEADO',[ID_PERSONA_ORIGEN],'PERSONA',CONCAT(CAST(N'Persona inexistente; disponibilidad conservada sin FK de persona: ' AS nvarchar(max)),OBSERVACIONES) FROM #D WHERE TIPO_ENTIDAD='DESCONOCIDO';
  INSERT #Excepciones SELECT 'LK_AGENDA_EMPLEADO',[ID_PERSONA_ORIGEN],'HOLIDAYTEXT',CONCAT(CAST(N'Agenda sin visita migrada; disponibilidad sin FK de visita: ' AS nvarchar(max)),OBSERVACIONES) FROM #D WHERE UPPER(LTRIM(RTRIM(TIPO)))='A' AND ID_VISITA IS NULL;
  INSERT #Excepciones SELECT 'LK_AGENDA_EMPLEADO',[ID_PERSONA_ORIGEN],'HORAS',CONCAT(CAST(N'Horas negativas; NULL: ' AS nvarchar(max)),OBSERVACIONES) FROM #D WHERE HORAS<0;
  UPDATE #D SET HORAS=NULL,OBSERVACIONES=CONCAT(OBSERVACIONES,CHAR(13),CHAR(10),'EXCEPCION: HORAS negativas; NULL.') WHERE HORAS<0;
  INSERT #Excepciones SELECT 'LK_AGENDA_EMPLEADO',[ID_PERSONA_ORIGEN],'HORAS_DISP',CONCAT(CAST(N'Horas disponibles negativas; NULL: ' AS nvarchar(max)),OBSERVACIONES) FROM #D WHERE HORAS_DISP<0;
  UPDATE #D SET HORAS_DISP=NULL,OBSERVACIONES=CONCAT(OBSERVACIONES,CHAR(13),CHAR(10),'EXCEPCION: HORAS_DISP negativas; NULL.') WHERE HORAS_DISP<0;
  INSERT #Excepciones SELECT 'LK_AGENDA_EMPLEADO',ID_PERSONA_ORIGEN,'TIPO',CONCAT(N'Codigo desconocido; se conserva TIPO, sin estado de catalogo. ',OBSERVACIONES) FROM #D WHERE ISNULL(UPPER(LTRIM(RTRIM(TIPO))),'') NOT IN ('OC','ND','D','OP','OA','A','LIC','POT');
  CREATE TABLE #Tokens(ID_VISITA int,ID_CONSULTOR int,LIDER int,TOKEN varchar(1000) COLLATE DATABASE_DEFAULT);
  INSERT #Tokens SELECT v.ID,t.ID,0,t.TOKEN COLLATE DATABASE_DEFAULT FROM #V v JOIN dbo.LK_AGENDA l ON l.ID_AGENDA=v.ID CROSS APPLY dbo.VCT_MIG_PROY_SEPARAR_IDS(l.ID_CONSULTOR) t;
  INSERT #Tokens SELECT v.ID,t.ID,1,t.TOKEN COLLATE DATABASE_DEFAULT FROM #V v JOIN dbo.LK_AGENDA l ON l.ID_AGENDA=v.ID CROSS APPLY dbo.VCT_MIG_PROY_SEPARAR_IDS(l.LIDER) t;
  INSERT #Tokens SELECT ID_VISITA,ID_CONSULTOR,0,CONVERT(varchar(1000),ID_PERSONA_ORIGEN) FROM #D WHERE ID_VISITA IS NOT NULL AND ID_CONSULTOR IS NOT NULL;
  INSERT #Excepciones SELECT 'LK_AGENDA',t.ID_VISITA,'CONSULTOR',CONCAT(N'Consultor/token inexistente: ',t.TOKEN,N'. ',v.OBSERVACIONES) FROM #Tokens t JOIN #V v ON v.ID=t.ID_VISITA WHERE NOT EXISTS(SELECT 1 FROM dbo.VCT_CONSULTORES c WHERE c.ID=t.ID_CONSULTOR);
  SELECT t.ID_VISITA,t.ID_CONSULTOR,CAST(MAX(t.LIDER) AS bit) LIDER,
   CAST(NULL AS numeric(10,2)) HORAS_PLANIFICADAS,CAST(NULL AS numeric(10,2)) HORAS_EJECUTADAS,
   CAST('Consultor/leader de LK_AGENDA y/o LK_AGENDA_EMPLEADO.' AS varchar(max)) COLLATE DATABASE_DEFAULT OBSERVACIONES,
   @ahora FECHA_ALTA,CAST('MIGRACION_LK' AS varchar(100)) COLLATE DATABASE_DEFAULT USUARIO_ALTA
  INTO #VC FROM #Tokens t JOIN dbo.VCT_CONSULTORES c ON c.ID=t.ID_CONSULTOR GROUP BY t.ID_VISITA,t.ID_CONSULTOR;
  CREATE UNIQUE CLUSTERED INDEX IX_VC ON #VC(ID_VISITA,ID_CONSULTOR);
  SELECT ID_VISITA,ID_CONSULTOR,SUM(CONVERT(bigint,HORAS)) HORAS INTO #H FROM #D WHERE ID_VISITA IS NOT NULL AND ID_CONSULTOR IS NOT NULL GROUP BY ID_VISITA,ID_CONSULTOR;
  CREATE UNIQUE CLUSTERED INDEX IX_H ON #H(ID_VISITA,ID_CONSULTOR);
  IF EXISTS(SELECT 1 FROM #H WHERE HORAS>99999999) THROW 55007,'Horas por consultor exceden numeric(10,2). Se revierte todo.',1;
  UPDATE vc SET HORAS_EJECUTADAS=h.HORAS FROM #VC vc JOIN #H h ON h.ID_VISITA=vc.ID_VISITA AND h.ID_CONSULTOR=vc.ID_CONSULTOR;
  UPDATE v SET TOTAL_HORAS_EJECUTADAS=ISNULL(h.HORAS,0),HORAS_SIN_CONSULTOR=ISNULL(h.SIN_PERSONA,0) FROM #V v
   OUTER APPLY(SELECT SUM(CONVERT(bigint,d.HORAS)) HORAS,SUM(CASE WHEN d.ID_CONSULTOR IS NULL THEN CONVERT(bigint,d.HORAS) ELSE 0 END) SIN_PERSONA FROM #D d WHERE d.ID_VISITA=v.ID) h;
  INSERT #Excepciones SELECT 'LK_AGENDA',ID,'HORAS_SIN_CONSULTOR',CONCAT(N'El total incluye ',HORAS_SIN_CONSULTOR,N' horas de personas sin consultor migrado. No se inventa un consultor. ',OBSERVACIONES) FROM #V WHERE HORAS_SIN_CONSULTOR<>0;
  IF EXISTS(SELECT 1 FROM #S s CROSS APPLY(SELECT SUM(CONVERT(bigint,v.TOTAL_HORAS_EJECUTADAS)) HORAS FROM #V v WHERE v.ID_PROYECTO_SERVICIO=s.ID) h WHERE h.HORAS>2147483647)
    OR EXISTS(SELECT 1 FROM #P p CROSS APPLY(SELECT SUM(CONVERT(bigint,v.TOTAL_HORAS_EJECUTADAS)) HORAS FROM #V v WHERE v.ID_PROYECTO=p.ID) h WHERE h.HORAS>2147483647)
   THROW 55008,'Horas totales exceden int del modelo. Se revierte todo.',1;
  UPDATE s SET TOTAL_HORAS_EJECUTADAS=ISNULL(h.HORAS,0) FROM #S s OUTER APPLY(SELECT SUM(CONVERT(bigint,v.TOTAL_HORAS_EJECUTADAS)) HORAS FROM #V v WHERE v.ID_PROYECTO_SERVICIO=s.ID) h;
  UPDATE p SET TOTAL_HORAS_EJECUTADAS=ISNULL(h.HORAS,0) FROM #P p OUTER APPLY(SELECT SUM(CONVERT(bigint,v.TOTAL_HORAS_EJECUTADAS)) HORAS FROM #V v WHERE v.ID_PROYECTO=p.ID) h;
  SELECT ROW_NUMBER() OVER(ORDER BY ID_VISITA,ID_CONSULTOR) ID,* INTO #VC_ID FROM #VC;
  SELECT v.ID_PROYECTO,v.ID_PROYECTO_SERVICIO,vc.ID_CONSULTOR,MAX(CONVERT(int,vc.LIDER)) LIDER,MIN(v.FECHA_DESDE) FECHA_DESDE,MAX(COALESCE(v.FECHA_HASTA,v.FECHA_DESDE)) FECHA_HASTA
   INTO #EBASE FROM #VC vc JOIN #V v ON v.ID=vc.ID_VISITA GROUP BY v.ID_PROYECTO,v.ID_PROYECTO_SERVICIO,vc.ID_CONSULTOR;
  SELECT ROW_NUMBER() OVER(ORDER BY ID_PROYECTO,ID_PROYECTO_SERVICIO,ID_CONSULTOR) ID,ID_PROYECTO,ID_PROYECTO_SERVICIO,
   CAST('CONSULTOR' AS varchar(20)) COLLATE DATABASE_DEFAULT TIPO_MIEMBRO,CAST(NULL AS int) ID_EMPLEADO,ID_CONSULTOR,
   CASE WHEN LIDER=1 THEN @lider ELSE @rol END ID_ROL,
   CAST(CASE WHEN ROW_NUMBER() OVER(PARTITION BY ID_PROYECTO,ID_PROYECTO_SERVICIO ORDER BY LIDER DESC,ID_CONSULTOR)=1 THEN 1 ELSE 0 END AS bit) PRINCIPAL,
   FECHA_DESDE,FECHA_HASTA,CAST('ACTIVO' AS varchar(20)) COLLATE DATABASE_DEFAULT ESTADO,
   CAST('Equipo derivado de las visitas; liderazgo tomado de LK_AGENDA.LIDER.' AS varchar(max)) COLLATE DATABASE_DEFAULT OBSERVACIONES,@ahora FECHA_ALTA,CAST('MIGRACION_LK' AS varchar(100)) COLLATE DATABASE_DEFAULT USUARIO_ALTA
   INTO #E FROM #EBASE;
  CREATE TABLE #NT(ID_PROYECTO int,ID_PROYECTO_SERVICIO int,ID_VISITA int,ID_NORMA int,TOKEN varchar(1000) COLLATE DATABASE_DEFAULT);
  INSERT #NT SELECT p.ID,NULL,NULL,t.ID,t.TOKEN COLLATE DATABASE_DEFAULT FROM #P p JOIN dbo.LK_PROYECTO l ON l.ID_PROYECTO=p.ID CROSS APPLY dbo.VCT_MIG_PROY_SEPARAR_IDS(l.NORMAS) t;
  INSERT #NT SELECT v.ID_PROYECTO,v.ID_PROYECTO_SERVICIO,v.ID,t.ID,t.TOKEN COLLATE DATABASE_DEFAULT FROM #V v JOIN dbo.LK_AGENDA l ON l.ID_AGENDA=v.ID CROSS APPLY dbo.VCT_MIG_PROY_SEPARAR_IDS(l.NORMA) t;
  INSERT #Excepciones SELECT CASE WHEN ID_VISITA IS NULL THEN 'LK_PROYECTO' ELSE 'LK_AGENDA' END,COALESCE(ID_VISITA,ID_PROYECTO),'NORMA',CONCAT(N'Norma/token inexistente: ',TOKEN,N'; proyecto=',ID_PROYECTO) FROM #NT WHERE NOT EXISTS(SELECT 1 FROM dbo.VCT_PRM_NORMAS n WHERE n.ID=#NT.ID_NORMA);
  DELETE #NT WHERE NOT EXISTS(SELECT 1 FROM dbo.VCT_PRM_NORMAS n WHERE n.ID=#NT.ID_NORMA);
  SELECT DISTINCT ID_PROYECTO,ID_PROYECTO_SERVICIO,ID_NORMA INTO #PNBASE FROM #NT;
  SELECT ROW_NUMBER() OVER(ORDER BY ID_PROYECTO,ID_PROYECTO_SERVICIO,ID_NORMA) ID,*,
   CAST(CASE WHEN ROW_NUMBER() OVER(PARTITION BY ID_PROYECTO,ID_PROYECTO_SERVICIO ORDER BY ID_NORMA)=1 THEN 1 ELSE 0 END AS bit) PRINCIPAL,
   CAST(1 AS bit) OBLIGATORIA,CAST('ACTIVA' AS varchar(20)) COLLATE DATABASE_DEFAULT ESTADO,
   CAST('Norma migrada de LK_PROYECTO.NORMAS / LK_AGENDA.NORMA.' AS varchar(max)) COLLATE DATABASE_DEFAULT OBSERVACIONES,@ahora FECHA_ALTA,CAST('MIGRACION_LK' AS varchar(100)) COLLATE DATABASE_DEFAULT USUARIO_ALTA
  INTO #PN FROM #PNBASE;
  SELECT DISTINCT ID_VISITA,ID_NORMA INTO #VNBASE FROM #NT WHERE ID_VISITA IS NOT NULL;
  SELECT ROW_NUMBER() OVER(ORDER BY ID_VISITA,ID_NORMA) ID,*,CAST('Norma migrada de LK_AGENDA.NORMA.' AS varchar(max)) COLLATE DATABASE_DEFAULT OBSERVACIONES,@ahora FECHA_ALTA,CAST('MIGRACION_LK' AS varchar(100)) COLLATE DATABASE_DEFAULT USUARIO_ALTA INTO #VN FROM #VNBASE;
  SELECT CAST(l.ID_PROYECTO_RENTA AS int) AS [ID_PROYECTO_RENTA],
   CAST(l.ID_PROYECTO AS int) AS [ID_PROYECTO],
   CAST(l.PERIODO AS varchar(50)) COLLATE DATABASE_DEFAULT AS [PERIODO],
   CAST(l.VENTAS AS numeric(15, 2)) AS [VENTAS],
   CAST(l.COMPRAS AS numeric(15, 2)) AS [COMPRAS],
   CAST(l.FECHA_ALTA AS datetime) AS [FECHA_ALTA],
   CAST(l.USUARIO_ALTA AS varchar(100)) COLLATE DATABASE_DEFAULT AS [USUARIO_ALTA],
   CAST(CONCAT(CAST('LK_PROYECTO_RENTABILIDAD - valores originales: ' AS varchar(max)),'; ID_PROYECTO_RENTA=',COALESCE(CONVERT(varchar(max),l.[ID_PROYECTO_RENTA]),'<NULL>'),'; ID_PROYECTO=',COALESCE(CONVERT(varchar(max),l.[ID_PROYECTO]),'<NULL>'),'; PERIODO=',COALESCE(CONVERT(varchar(max),l.[PERIODO]),'<NULL>'),'; VENTAS=',COALESCE(CONVERT(varchar(max),l.[VENTAS]),'<NULL>'),'; COMPRAS=',COALESCE(CONVERT(varchar(max),l.[COMPRAS]),'<NULL>'),'; FECHA_ALTA=',COALESCE(CONVERT(varchar(max),l.[FECHA_ALTA],126),'<NULL>'),'; USUARIO_ALTA=',COALESCE(CONVERT(varchar(max),l.[USUARIO_ALTA]),'<NULL>')) AS varchar(max)) COLLATE DATABASE_DEFAULT AS [OBSERVACIONES] INTO #R FROM dbo.LK_PROYECTO_RENTABILIDAD l WITH(HOLDLOCK) ;
  CREATE UNIQUE CLUSTERED INDEX IX_R_ID ON #R([ID_PROYECTO_RENTA]);
  INSERT #Excepciones SELECT 'LK_PROYECTO_RENTABILIDAD',[ID_PROYECTO_RENTA],'ID_PROYECTO',CONCAT(CAST(N'Rentabilidad sin proyecto; omitida: ' AS nvarchar(max)),OBSERVACIONES) FROM #R WHERE NOT EXISTS(SELECT 1 FROM #P p WHERE p.ID=#R.ID_PROYECTO);
  DELETE #R WHERE NOT EXISTS(SELECT 1 FROM #P p WHERE p.ID=#R.ID_PROYECTO);
  SELECT CAST(l.ID_TIPO_SERVICIO AS int) AS [ID_TIPO_SERVICIO],
   CAST(l.ID_AGENDA AS int) AS [ID_AGENDA],
   CAST(l.FECHA AS datetime) AS [FECHA],
   CAST(l.LUGAR AS varchar(300)) COLLATE DATABASE_DEFAULT AS [LUGAR],
   CAST(l.IMPORTE AS varchar(50)) COLLATE DATABASE_DEFAULT AS [IMPORTE],
   CAST(l.ID_PROYECTO_HONORARIOS AS int) AS [ID],
   CAST(l.ID_PROYECTO AS int) AS [ID_PROYECTO_ORIGEN],
   CAST(l.ID_CONSULTOR AS varchar(50)) COLLATE DATABASE_DEFAULT AS [ID_CONSULTOR_ORIGEN],
   CAST(p.ID AS int) AS [ID_PROYECTO],
   CAST(v.ID AS int) AS [ID_VISITA],
   CAST(COALESCE(v.ID_PROYECTO_SERVICIO,fb.ID) AS int) AS [ID_PROYECTO_SERVICIO],
   CAST(c.ID AS int) AS [ID_CONSULTOR],
   CAST(CONCAT(CAST('LK_PROYECTO_HONORARIOS - valores originales: ' AS varchar(max)),'; ID_PROYECTO_HONORARIOS=',COALESCE(CONVERT(varchar(max),l.[ID_PROYECTO_HONORARIOS]),'<NULL>'),'; ID_PROYECTO=',COALESCE(CONVERT(varchar(max),l.[ID_PROYECTO]),'<NULL>'),'; ID_TIPO_SERVICIO=',COALESCE(CONVERT(varchar(max),l.[ID_TIPO_SERVICIO]),'<NULL>'),'; ID_AGENDA=',COALESCE(CONVERT(varchar(max),l.[ID_AGENDA]),'<NULL>'),'; ID_CONSULTOR=',COALESCE(CONVERT(varchar(max),l.[ID_CONSULTOR]),'<NULL>'),'; FECHA=',COALESCE(CONVERT(varchar(max),l.[FECHA],126),'<NULL>'),'; LUGAR=',COALESCE(CONVERT(varchar(max),l.[LUGAR]),'<NULL>'),'; IMPORTE=',COALESCE(CONVERT(varchar(max),l.[IMPORTE]),'<NULL>')) AS varchar(max)) COLLATE DATABASE_DEFAULT AS [OBSERVACIONES],
   CAST(dbo.VCT_MIG_PROY_IMPORTE(l.IMPORTE) AS numeric(15,2)) AS [IMPORTE_NUMERICO] INTO #F FROM dbo.LK_PROYECTO_HONORARIOS l WITH(HOLDLOCK) LEFT JOIN #P p ON p.ID=l.ID_PROYECTO LEFT JOIN #V v ON v.ID=l.ID_AGENDA AND v.ID_PROYECTO=l.ID_PROYECTO LEFT JOIN dbo.VCT_CONSULTORES c ON c.ID=TRY_CAST(NULLIF(LTRIM(RTRIM(l.ID_CONSULTOR)),'') AS int) OUTER APPLY(SELECT CASE WHEN COUNT(*)=1 THEN MAX(s.ID) END ID FROM #S s WHERE s.ID_PROYECTO=l.ID_PROYECTO AND s.ID_SERVICIO=l.ID_TIPO_SERVICIO) fb;
  CREATE UNIQUE CLUSTERED INDEX IX_F_ID ON #F([ID]);
  INSERT #Excepciones SELECT 'LK_PROYECTO_HONORARIOS',[ID],'REFERENCIAS',CONCAT(CAST(N'Referencia inexistente/ambigua; fila conservada con FK NULL: ' AS nvarchar(max)),OBSERVACIONES) FROM #F WHERE ID_PROYECTO IS NULL OR (ID_AGENDA IS NOT NULL AND ID_VISITA IS NULL) OR (NULLIF(LTRIM(RTRIM(ID_CONSULTOR_ORIGEN)),'') IS NOT NULL AND ID_CONSULTOR IS NULL);
  INSERT #Excepciones SELECT 'LK_PROYECTO_HONORARIOS',[ID],'IMPORTE',CONCAT(CAST(N'Importe ambiguo/no numerico; IMPORTE_NUMERICO NULL, texto conservado: ' AS nvarchar(max)),OBSERVACIONES) FROM #F WHERE NULLIF(LTRIM(RTRIM(IMPORTE)),'') IS NOT NULL AND IMPORTE_NUMERICO IS NULL;
  SELECT CAST(l.ID_TIPO_SERVICIO AS int) AS [ID_TIPO_SERVICIO],
   CAST(l.ID_AGENDA AS int) AS [ID_AGENDA],
   CAST(l.TIPO_CONSULTOR AS varchar(50)) COLLATE DATABASE_DEFAULT AS [TIPO_CONSULTOR],
   CAST(l.TIPO_PROVEEDOR AS varchar(50)) COLLATE DATABASE_DEFAULT AS [TIPO_PROVEEDOR],
   CAST(l.NRO_FC AS varchar(100)) COLLATE DATABASE_DEFAULT AS [NRO_FC],
   CAST(l.CANT_PERSONAS AS varchar(50)) COLLATE DATABASE_DEFAULT AS [CANT_PERSONAS],
   CAST(l.DESCRIP_SERVICIO AS varchar(300)) COLLATE DATABASE_DEFAULT AS [DESCRIP_SERVICIO],
   CAST(l.FECHA_FC AS datetime) AS [FECHA_FC],
   CAST(l.PRECIO_FINAL AS numeric(12, 2)) AS [PRECIO_FINAL],
   CAST(l.FORMA_PAGO AS varchar(50)) COLLATE DATABASE_DEFAULT AS [FORMA_PAGO],
   CAST(l.CANT_CUOTAS AS int) AS [CANT_CUOTAS],
   CAST(l.ESTADO_PAGO AS varchar(50)) COLLATE DATABASE_DEFAULT AS [ESTADO_PAGO],
   CAST(l.FECHA_ULT_PAGO AS datetime) AS [FECHA_ULT_PAGO],
   CAST(l.PRECIO_CUOTA AS numeric(12, 2)) AS [PRECIO_CUOTA],
   CAST(l.PROX_VENCIMIENTO AS datetime) AS [PROX_VENCIMIENTO],
   CAST(l.SALDO_PEND AS numeric(12, 2)) AS [SALDO_PEND],
   CAST(l.DESTINO AS varchar(100)) COLLATE DATABASE_DEFAULT AS [DESTINO],
   CAST(l.FECHA_DESDE_SERV AS datetime) AS [FECHA_DESDE_SERV],
   CAST(l.FECHA_HASTA_SERV AS datetime) AS [FECHA_HASTA_SERV],
   CAST(l.DESC_FORMA_PAGO AS varchar(300)) COLLATE DATABASE_DEFAULT AS [DESC_FORMA_PAGO],
   CAST(l.ID_PROYECTO_VIATICOS AS int) AS [ID],
   CAST(l.ID_PROYECTO AS int) AS [ID_PROYECTO_ORIGEN],
   CAST(l.ID_CONSULTOR AS varchar(50)) COLLATE DATABASE_DEFAULT AS [ID_CONSULTOR_ORIGEN],
   CAST(p.ID AS int) AS [ID_PROYECTO],
   CAST(v.ID AS int) AS [ID_VISITA],
   CAST(COALESCE(v.ID_PROYECTO_SERVICIO,fb.ID) AS int) AS [ID_PROYECTO_SERVICIO],
   CAST(c.ID AS int) AS [ID_CONSULTOR],
   CAST(CONCAT(CAST('LK_PROYECTO_VIATICOS - valores originales: ' AS varchar(max)),'; ID_PROYECTO_VIATICOS=',COALESCE(CONVERT(varchar(max),l.[ID_PROYECTO_VIATICOS]),'<NULL>'),'; ID_PROYECTO=',COALESCE(CONVERT(varchar(max),l.[ID_PROYECTO]),'<NULL>'),'; ID_TIPO_SERVICIO=',COALESCE(CONVERT(varchar(max),l.[ID_TIPO_SERVICIO]),'<NULL>'),'; ID_AGENDA=',COALESCE(CONVERT(varchar(max),l.[ID_AGENDA]),'<NULL>'),'; TIPO_CONSULTOR=',COALESCE(CONVERT(varchar(max),l.[TIPO_CONSULTOR]),'<NULL>'),'; ID_CONSULTOR=',COALESCE(CONVERT(varchar(max),l.[ID_CONSULTOR]),'<NULL>'),'; ID_PROVEEDOR=',COALESCE(CONVERT(varchar(max),l.[ID_PROVEEDOR]),'<NULL>'),'; TIPO_PROVEEDOR=',COALESCE(CONVERT(varchar(max),l.[TIPO_PROVEEDOR]),'<NULL>'),'; NRO_FC=',COALESCE(CONVERT(varchar(max),l.[NRO_FC]),'<NULL>'),'; CANT_PERSONAS=',COALESCE(CONVERT(varchar(max),l.[CANT_PERSONAS]),'<NULL>'),'; DESCRIP_SERVICIO=',COALESCE(CONVERT(varchar(max),l.[DESCRIP_SERVICIO]),'<NULL>'),'; FECHA_FC=',COALESCE(CONVERT(varchar(max),l.[FECHA_FC],126),'<NULL>'),'; PRECIO_FINAL=',COALESCE(CONVERT(varchar(max),l.[PRECIO_FINAL]),'<NULL>'),'; FORMA_PAGO=',COALESCE(CONVERT(varchar(max),l.[FORMA_PAGO]),'<NULL>'),'; CANT_CUOTAS=',COALESCE(CONVERT(varchar(max),l.[CANT_CUOTAS]),'<NULL>'),'; ESTADO_PAGO=',COALESCE(CONVERT(varchar(max),l.[ESTADO_PAGO]),'<NULL>'),'; FECHA_ULT_PAGO=',COALESCE(CONVERT(varchar(max),l.[FECHA_ULT_PAGO],126),'<NULL>'),'; PRECIO_CUOTA=',COALESCE(CONVERT(varchar(max),l.[PRECIO_CUOTA]),'<NULL>'),'; PROX_VENCIMIENTO=',COALESCE(CONVERT(varchar(max),l.[PROX_VENCIMIENTO],126),'<NULL>'),'; SALDO_PEND=',COALESCE(CONVERT(varchar(max),l.[SALDO_PEND]),'<NULL>'),'; DESTINO=',COALESCE(CONVERT(varchar(max),l.[DESTINO]),'<NULL>'),'; FECHA_DESDE_SERV=',COALESCE(CONVERT(varchar(max),l.[FECHA_DESDE_SERV],126),'<NULL>'),'; FECHA_HASTA_SERV=',COALESCE(CONVERT(varchar(max),l.[FECHA_HASTA_SERV],126),'<NULL>'),'; DESC_FORMA_PAGO=',COALESCE(CONVERT(varchar(max),l.[DESC_FORMA_PAGO]),'<NULL>')) AS varchar(max)) COLLATE DATABASE_DEFAULT AS [OBSERVACIONES],
   CAST(l.ID_PROVEEDOR AS int) AS [ID_PROVEEDOR_ORIGEN],
   CAST(pr.ID_PROVEEDOR AS int) AS [ID_PROVEEDOR],
   CAST(NULL AS int) AS [ID_TIPO_VIATICO] INTO #W FROM dbo.LK_PROYECTO_VIATICOS l WITH(HOLDLOCK) LEFT JOIN #P p ON p.ID=l.ID_PROYECTO LEFT JOIN #V v ON v.ID=l.ID_AGENDA AND v.ID_PROYECTO=l.ID_PROYECTO LEFT JOIN dbo.VCT_CONSULTORES c ON c.ID=TRY_CAST(NULLIF(LTRIM(RTRIM(l.ID_CONSULTOR)),'') AS int) OUTER APPLY(SELECT CASE WHEN COUNT(*)=1 THEN MAX(s.ID) END ID FROM #S s WHERE s.ID_PROYECTO=l.ID_PROYECTO AND s.ID_SERVICIO=l.ID_TIPO_SERVICIO) fb LEFT JOIN dbo.VCT_PROVEEDORES pr ON pr.ID_PROVEEDOR=l.ID_PROVEEDOR;
  CREATE UNIQUE CLUSTERED INDEX IX_W_ID ON #W([ID]);
  INSERT #Excepciones SELECT 'LK_PROYECTO_VIATICOS',[ID],'REFERENCIAS',CONCAT(CAST(N'Referencia inexistente/ambigua; fila conservada con FK NULL: ' AS nvarchar(max)),OBSERVACIONES) FROM #W WHERE ID_PROYECTO IS NULL OR (ID_AGENDA IS NOT NULL AND ID_VISITA IS NULL) OR (NULLIF(LTRIM(RTRIM(ID_CONSULTOR_ORIGEN)),'') IS NOT NULL AND ID_CONSULTOR IS NULL);
  INSERT #Excepciones SELECT 'LK_PROYECTO_VIATICOS',[ID],'ID_PROVEEDOR',CONCAT(CAST(N'Proveedor inexistente; FK NULL: ' AS nvarchar(max)),OBSERVACIONES) FROM #W WHERE ID_PROVEEDOR_ORIGEN IS NOT NULL AND ID_PROVEEDOR IS NULL;
  INSERT #Excepciones SELECT 'LK_PROYECTO_VIATICOS',[ID],'TIPO_PROVEEDOR',CONCAT(CAST(N'Tipo de viatico desconocido; texto conservado: ' AS nvarchar(max)),OBSERVACIONES) FROM #W WHERE ISNULL(UPPER(LTRIM(RTRIM(TIPO_PROVEEDOR))),'') NOT IN ('MICRO','HOTEL','REMIS','AVION','REFRIGERIO','TAXI','ALQUILER','AUTO');
  CREATE TABLE #WD([ID_AGENDA] int NULL,[DET_PROV_RESERVA] varchar(max) COLLATE DATABASE_DEFAULT NULL,[DET_PROV_VUELO] varchar(max) COLLATE DATABASE_DEFAULT NULL,[DET_PROV_ORIGEN] varchar(max) COLLATE DATABASE_DEFAULT NULL,[DET_PROV_DESTINO] varchar(max) COLLATE DATABASE_DEFAULT NULL,[DET_PROV_SALIDA] varchar(max) COLLATE DATABASE_DEFAULT NULL,[DET_PROV_LLEGADA] varchar(max) COLLATE DATABASE_DEFAULT NULL,[DET_PROV_LOCAL] varchar(max) COLLATE DATABASE_DEFAULT NULL,[PAGA_CONSULTOR] varchar(max) COLLATE DATABASE_DEFAULT NULL,[PAGA_CONSULTORA] varchar(max) COLLATE DATABASE_DEFAULT NULL,[RENDICION_CLIENTE] varchar(max) COLLATE DATABASE_DEFAULT NULL,[DET_PROV_KMS] varchar(max) COLLATE DATABASE_DEFAULT NULL,[DET_PROV_PEAJES] varchar(max) COLLATE DATABASE_DEFAULT NULL,[DET_PROV_FECHA] datetime NULL,[DET_PROV_FINGRESO] datetime NULL,[DET_PROV_FEGRESO] datetime NULL,[DET_PROV_FPARTIDA] datetime NULL,[DET_PROV_FLLEGADA] datetime NULL,[ID] int NULL,[ID_VIATICO] int NULL,[ID_VISITA] int NULL,[ID_PROYECTO_VIATICOS_ORIGEN] int NULL,[KMS_NUMERICO] numeric(15,2) NULL,[PEAJES_NUMERICO] numeric(15,2) NULL,[OBSERVACIONES] varchar(max) COLLATE DATABASE_DEFAULT NULL);
  IF OBJECT_ID(N'dbo.LK_PROYECTO_VIATICOS_DET',N'U') IS NOT NULL EXEC sys.sp_executesql N'INSERT #WD([ID_AGENDA],[DET_PROV_RESERVA],[DET_PROV_VUELO],[DET_PROV_ORIGEN],[DET_PROV_DESTINO],[DET_PROV_SALIDA],[DET_PROV_LLEGADA],[DET_PROV_LOCAL],[PAGA_CONSULTOR],[PAGA_CONSULTORA],[RENDICION_CLIENTE],[DET_PROV_KMS],[DET_PROV_PEAJES],[DET_PROV_FECHA],[DET_PROV_FINGRESO],[DET_PROV_FEGRESO],[DET_PROV_FPARTIDA],[DET_PROV_FLLEGADA],[ID],[ID_VIATICO],[ID_VISITA],[ID_PROYECTO_VIATICOS_ORIGEN],[KMS_NUMERICO],[PEAJES_NUMERICO],[OBSERVACIONES]) SELECT CAST(l.ID_AGENDA AS int),CAST(l.DET_PROV_RESERVA AS varchar(max)) COLLATE DATABASE_DEFAULT,CAST(l.DET_PROV_VUELO AS varchar(max)) COLLATE DATABASE_DEFAULT,CAST(l.DET_PROV_ORIGEN AS varchar(max)) COLLATE DATABASE_DEFAULT,CAST(l.DET_PROV_DESTINO AS varchar(max)) COLLATE DATABASE_DEFAULT,CAST(l.DET_PROV_SALIDA AS varchar(max)) COLLATE DATABASE_DEFAULT,CAST(l.DET_PROV_LLEGADA AS varchar(max)) COLLATE DATABASE_DEFAULT,CAST(l.DET_PROV_LOCAL AS varchar(max)) COLLATE DATABASE_DEFAULT,CAST(l.PAGA_CONSULTOR AS varchar(max)) COLLATE DATABASE_DEFAULT,CAST(l.PAGA_CONSULTORA AS varchar(max)) COLLATE DATABASE_DEFAULT,CAST(l.RENDICION_CLIENTE AS varchar(max)) COLLATE DATABASE_DEFAULT,CAST(l.DET_PROV_KMS AS varchar(max)) COLLATE DATABASE_DEFAULT,CAST(l.DET_PROV_PEAJES AS varchar(max)) COLLATE DATABASE_DEFAULT,CAST(l.DET_PROV_FECHA AS datetime),CAST(l.DET_PROV_FINGRESO AS datetime),CAST(l.DET_PROV_FEGRESO AS datetime),CAST(l.DET_PROV_FPARTIDA AS datetime),CAST(l.DET_PROV_FLLEGADA AS datetime),CAST(l.ID_PROYECTO_VIATICOS_DET AS int),CAST(w.ID AS int),CAST(v.ID AS int),CAST(l.ID_PROYECTO_VIATICOS AS int),CAST(dbo.VCT_MIG_PROY_IMPORTE(l.DET_PROV_KMS) AS numeric(15,2)),CAST(dbo.VCT_MIG_PROY_IMPORTE(l.DET_PROV_PEAJES) AS numeric(15,2)),CAST(CONCAT(CAST(''LK_PROYECTO_VIATICOS_DET - valores originales: '' AS varchar(max)),''; ID_PROYECTO_VIATICOS_DET='',COALESCE(CONVERT(varchar(max),l.[ID_PROYECTO_VIATICOS_DET]),''<NULL>''),''; ID_PROYECTO_VIATICOS='',COALESCE(CONVERT(varchar(max),l.[ID_PROYECTO_VIATICOS]),''<NULL>''),''; ID_AGENDA='',COALESCE(CONVERT(varchar(max),l.[ID_AGENDA]),''<NULL>''),''; DET_PROV_RESERVA='',COALESCE(CONVERT(varchar(max),l.[DET_PROV_RESERVA]),''<NULL>''),''; DET_PROV_VUELO='',COALESCE(CONVERT(varchar(max),l.[DET_PROV_VUELO]),''<NULL>''),''; DET_PROV_ORIGEN='',COALESCE(CONVERT(varchar(max),l.[DET_PROV_ORIGEN]),''<NULL>''),''; DET_PROV_DESTINO='',COALESCE(CONVERT(varchar(max),l.[DET_PROV_DESTINO]),''<NULL>''),''; DET_PROV_SALIDA='',COALESCE(CONVERT(varchar(max),l.[DET_PROV_SALIDA]),''<NULL>''),''; DET_PROV_LLEGADA='',COALESCE(CONVERT(varchar(max),l.[DET_PROV_LLEGADA]),''<NULL>''),''; DET_PROV_LOCAL='',COALESCE(CONVERT(varchar(max),l.[DET_PROV_LOCAL]),''<NULL>''),''; PAGA_CONSULTOR='',COALESCE(CONVERT(varchar(max),l.[PAGA_CONSULTOR]),''<NULL>''),''; PAGA_CONSULTORA='',COALESCE(CONVERT(varchar(max),l.[PAGA_CONSULTORA]),''<NULL>''),''; RENDICION_CLIENTE='',COALESCE(CONVERT(varchar(max),l.[RENDICION_CLIENTE]),''<NULL>''),''; DET_PROV_KMS='',COALESCE(CONVERT(varchar(max),l.[DET_PROV_KMS]),''<NULL>''),''; DET_PROV_PEAJES='',COALESCE(CONVERT(varchar(max),l.[DET_PROV_PEAJES]),''<NULL>''),''; DET_PROV_FECHA='',COALESCE(CONVERT(varchar(max),l.[DET_PROV_FECHA],126),''<NULL>''),''; DET_PROV_FINGRESO='',COALESCE(CONVERT(varchar(max),l.[DET_PROV_FINGRESO],126),''<NULL>''),''; DET_PROV_FEGRESO='',COALESCE(CONVERT(varchar(max),l.[DET_PROV_FEGRESO],126),''<NULL>''),''; DET_PROV_FPARTIDA='',COALESCE(CONVERT(varchar(max),l.[DET_PROV_FPARTIDA],126),''<NULL>''),''; DET_PROV_FLLEGADA='',COALESCE(CONVERT(varchar(max),l.[DET_PROV_FLLEGADA],126),''<NULL>'')) AS varchar(max)) COLLATE DATABASE_DEFAULT FROM dbo.LK_PROYECTO_VIATICOS_DET l WITH(HOLDLOCK) LEFT JOIN #W w ON w.ID=l.ID_PROYECTO_VIATICOS LEFT JOIN #V v ON v.ID=l.ID_AGENDA;';
  INSERT #Excepciones SELECT 'LK_PROYECTO_VIATICOS_DET',[ID],'REFERENCIAS',CONCAT(CAST(N'Detalle conservado con FK NULL por referencia faltante: ' AS nvarchar(max)),OBSERVACIONES) FROM #WD WHERE ID_VIATICO IS NULL OR (ID_AGENDA IS NOT NULL AND ID_VISITA IS NULL);
  INSERT #Excepciones SELECT 'LK_PROYECTO_VIATICOS_DET',[ID],'DET_PROV_KMS',CONCAT(CAST(N'Valor numerico ambiguo; texto conservado: ' AS nvarchar(max)),OBSERVACIONES) FROM #WD WHERE NULLIF(LTRIM(RTRIM(DET_PROV_KMS)),'') IS NOT NULL AND KMS_NUMERICO IS NULL;
  INSERT #Excepciones SELECT 'LK_PROYECTO_VIATICOS_DET',[ID],'DET_PROV_PEAJES',CONCAT(CAST(N'Valor numerico ambiguo; texto conservado: ' AS nvarchar(max)),OBSERVACIONES) FROM #WD WHERE NULLIF(LTRIM(RTRIM(DET_PROV_PEAJES)),'') IS NOT NULL AND PEAJES_NUMERICO IS NULL;
  CREATE INDEX IX_EX_ORIGEN ON #Excepciones(TABLA_ORIGEN,ID_ORIGEN) INCLUDE(CAMPO);
  UPDATE p SET OBSERVACIONES=CONCAT(p.OBSERVACIONES,CHAR(13),CHAR(10),x.NOTAS) FROM #P p CROSS APPLY(SELECT (SELECT CHAR(13)+CHAR(10)+'EXCEPCION '+e.CAMPO+' (detalle completo en VCT_MIGRACION_PROYECTOS_EXCEPCIONES).' FROM #Excepciones e WHERE e.TABLA_ORIGEN='LK_PROYECTO' AND e.ID_ORIGEN=p.ID ORDER BY e.CAMPO FOR XML PATH(''),TYPE).value('.','varchar(max)') NOTAS) x;
  UPDATE p SET OBSERVACIONES=CONCAT(p.OBSERVACIONES,CHAR(13),CHAR(10),x.NOTAS) FROM #S p CROSS APPLY(SELECT (SELECT CHAR(13)+CHAR(10)+'EXCEPCION '+e.CAMPO+' (detalle completo en VCT_MIGRACION_PROYECTOS_EXCEPCIONES).' FROM #Excepciones e WHERE e.TABLA_ORIGEN='LK_PROYECTO_SERVICIO' AND e.ID_ORIGEN=p.ID ORDER BY e.CAMPO FOR XML PATH(''),TYPE).value('.','varchar(max)') NOTAS) x;
  UPDATE p SET OBSERVACIONES=CONCAT(p.OBSERVACIONES,CHAR(13),CHAR(10),x.NOTAS) FROM #V p CROSS APPLY(SELECT (SELECT CHAR(13)+CHAR(10)+'EXCEPCION '+e.CAMPO+' (detalle completo en VCT_MIGRACION_PROYECTOS_EXCEPCIONES).' FROM #Excepciones e WHERE e.TABLA_ORIGEN='LK_AGENDA' AND e.ID_ORIGEN=p.ID ORDER BY e.CAMPO FOR XML PATH(''),TYPE).value('.','varchar(max)') NOTAS) x;
  UPDATE p SET OBSERVACIONES=CONCAT(p.OBSERVACIONES,CHAR(13),CHAR(10),x.NOTAS) FROM #F p CROSS APPLY(SELECT (SELECT CHAR(13)+CHAR(10)+'EXCEPCION '+e.CAMPO+' (detalle completo en VCT_MIGRACION_PROYECTOS_EXCEPCIONES).' FROM #Excepciones e WHERE e.TABLA_ORIGEN='LK_PROYECTO_HONORARIOS' AND e.ID_ORIGEN=p.ID ORDER BY e.CAMPO FOR XML PATH(''),TYPE).value('.','varchar(max)') NOTAS) x;
  UPDATE p SET OBSERVACIONES=CONCAT(p.OBSERVACIONES,CHAR(13),CHAR(10),x.NOTAS) FROM #W p CROSS APPLY(SELECT (SELECT CHAR(13)+CHAR(10)+'EXCEPCION '+e.CAMPO+' (detalle completo en VCT_MIGRACION_PROYECTOS_EXCEPCIONES).' FROM #Excepciones e WHERE e.TABLA_ORIGEN='LK_PROYECTO_VIATICOS' AND e.ID_ORIGEN=p.ID ORDER BY e.CAMPO FOR XML PATH(''),TYPE).value('.','varchar(max)') NOTAS) x;
  UPDATE p SET OBSERVACIONES=CONCAT(p.OBSERVACIONES,CHAR(13),CHAR(10),x.NOTAS) FROM #WD p CROSS APPLY(SELECT (SELECT CHAR(13)+CHAR(10)+'EXCEPCION '+e.CAMPO+' (detalle completo en VCT_MIGRACION_PROYECTOS_EXCEPCIONES).' FROM #Excepciones e WHERE e.TABLA_ORIGEN='LK_PROYECTO_VIATICOS_DET' AND e.ID_ORIGEN=p.ID ORDER BY e.CAMPO FOR XML PATH(''),TYPE).value('.','varchar(max)') NOTAS) x;
  UPDATE p SET OBSERVACIONES=CONCAT(p.OBSERVACIONES,CHAR(13),CHAR(10),x.NOTAS) FROM #R p CROSS APPLY(SELECT (SELECT CHAR(13)+CHAR(10)+'EXCEPCION '+e.CAMPO+' (detalle completo en VCT_MIGRACION_PROYECTOS_EXCEPCIONES).' FROM #Excepciones e WHERE e.TABLA_ORIGEN='LK_PROYECTO_RENTABILIDAD' AND e.ID_ORIGEN=p.ID_PROYECTO_RENTA ORDER BY e.CAMPO FOR XML PATH(''),TYPE).value('.','varchar(max)') NOTAS) x;
  UPDATE #D SET OBSERVACIONES=CONCAT(OBSERVACIONES,CASE WHEN TIPO_ENTIDAD='DESCONOCIDO' THEN CHAR(13)+CHAR(10)+'EXCEPCION: persona inexistente.' ELSE '' END,CASE WHEN UPPER(LTRIM(RTRIM(TIPO)))='A' AND ID_VISITA IS NULL THEN CHAR(13)+CHAR(10)+'EXCEPCION: visita inexistente.' ELSE '' END,CASE WHEN ISNULL(UPPER(LTRIM(RTRIM(TIPO))),'') NOT IN ('OC','ND','D','OP','OA','A','LIC','POT') THEN CHAR(13)+CHAR(10)+'EXCEPCION: tipo de disponibilidad desconocido.' ELSE '' END);
  CREATE TABLE #Resumen(Tabla sysname COLLATE DATABASE_DEFAULT PRIMARY KEY,Temp sysname COLLATE DATABASE_DEFAULT,Esperadas bigint,ColumnaId sysname COLLATE DATABASE_DEFAULT);
  INSERT #Resumen VALUES('VCT_PROYECTOS','P',(SELECT COUNT_BIG(*) FROM #P),'ID');
  INSERT #Resumen VALUES('VCT_PROYECTOS_SERVICIOS','S',(SELECT COUNT_BIG(*) FROM #S),'ID');
  INSERT #Resumen VALUES('VCT_PROYECTOS_VISITAS','V',(SELECT COUNT_BIG(*) FROM #V),'ID');
  INSERT #Resumen VALUES('VCT_AGENDA_PERSONAS','D',(SELECT COUNT_BIG(*) FROM #D),'ID');
  INSERT #Resumen VALUES('VCT_PROYECTOS_VISITAS_CONSULTORES','VC_ID',(SELECT COUNT_BIG(*) FROM #VC_ID),'ID');
  INSERT #Resumen VALUES('VCT_PROYECTOS_EQUIPO','E',(SELECT COUNT_BIG(*) FROM #E),'ID');
  INSERT #Resumen VALUES('VCT_PROYECTOS_NORMAS','PN',(SELECT COUNT_BIG(*) FROM #PN),'ID');
  INSERT #Resumen VALUES('VCT_PROYECTOS_VISITAS_NORMAS','VN',(SELECT COUNT_BIG(*) FROM #VN),'ID');
  INSERT #Resumen VALUES('VCT_PROYECTOS_RENTABILIDAD','R',(SELECT COUNT_BIG(*) FROM #R),'ID_PROYECTO_RENTA');
  INSERT #Resumen VALUES('VCT_PROYECTOS_HONORARIOS','F',(SELECT COUNT_BIG(*) FROM #F),'ID');
  INSERT #Resumen VALUES('VCT_PROYECTOS_VIATICOS','W',(SELECT COUNT_BIG(*) FROM #W),'ID');
  INSERT #Resumen VALUES('VCT_PROYECTOS_VIATICOS_DET','WD',(SELECT COUNT_BIG(*) FROM #WD),'ID');
  SELECT Tabla,Esperadas FROM #Resumen ORDER BY Tabla;
  SELECT TABLA_ORIGEN,CAMPO,COUNT_BIG(*) Cantidad FROM #Excepciones GROUP BY TABLA_ORIGEN,CAMPO ORDER BY TABLA_ORIGEN,CAMPO;
  SELECT SUM(CONVERT(bigint,TOTAL_HORAS_EJECUTADAS)) HORAS_EJECUTADAS,SUM(CONVERT(bigint,HORAS_SIN_CONSULTOR)) HORAS_SIN_CONSULTOR FROM #V;
  IF @Aplicar=0
  BEGIN
   SELECT * FROM #Excepciones ORDER BY TABLA_ORIGEN,ID_ORIGEN,CAMPO;
   ROLLBACK TRANSACTION;
   RETURN;
  END;
  DECLARE @Tablas TABLE(ObjectId int PRIMARY KEY,Nombre sysname);
  INSERT @Tablas SELECT OBJECT_ID(N'dbo.'+Tabla),Tabla FROM #Resumen;
  IF EXISTS(SELECT 1 FROM #Resumen r LEFT JOIN sys.identity_columns c ON c.object_id=OBJECT_ID(N'dbo.'+r.Tabla)
    WHERE c.column_id IS NULL OR c.name COLLATE DATABASE_DEFAULT<>r.ColumnaId COLLATE DATABASE_DEFAULT OR CONVERT(bigint,c.seed_value)<>1 OR CONVERT(bigint,c.increment_value)<>1)
   THROW 55009,'Identidades diferentes del modelo suministrado.',1;
  DECLARE bloquear CURSOR LOCAL FAST_FORWARD FOR SELECT Nombre FROM @Tablas ORDER BY ObjectId;
  OPEN bloquear; FETCH NEXT FROM bloquear INTO @nombre;
  WHILE @@FETCH_STATUS=0
  BEGIN
   SET @sql=N'SELECT @N=COUNT_BIG(*) FROM dbo.'+QUOTENAME(@nombre)+N' WITH(TABLOCKX,HOLDLOCK);';
   EXEC sys.sp_executesql @sql,N'@N bigint OUTPUT',@N=@n OUTPUT;
   FETCH NEXT FROM bloquear INTO @nombre;
  END;
  CLOSE bloquear; DEALLOCATE bloquear;
  -- Evitar reasignar IDs regenerados que tengan referencias externas (incluye documentos/planes).
  DECLARE dependencias CURSOR LOCAL FAST_FORWARD FOR
   SELECT f.parent_object_id,f.name,
    N'SELECT @H=CASE WHEN EXISTS(SELECT 1 FROM '+QUOTENAME(OBJECT_SCHEMA_NAME(f.parent_object_id))+N'.'+QUOTENAME(OBJECT_NAME(f.parent_object_id))+N' d WITH(HOLDLOCK) WHERE '
    +STUFF((SELECT N' AND d.'+QUOTENAME(COL_NAME(fc.parent_object_id,fc.parent_column_id))+N' IS NOT NULL' FROM sys.foreign_key_columns fc WHERE fc.constraint_object_id=f.object_id ORDER BY fc.constraint_column_id FOR XML PATH(''),TYPE).value('.','nvarchar(max)'),1,5,N'')+N') THEN 1 ELSE 0 END;'
   FROM sys.foreign_keys f JOIN @Tablas t ON t.ObjectId=f.referenced_object_id
   WHERE t.Nombre IN ('VCT_PROYECTOS_EQUIPO','VCT_PROYECTOS_NORMAS','VCT_PROYECTOS_VISITAS_CONSULTORES','VCT_PROYECTOS_VISITAS_NORMAS','VCT_AGENDA_PERSONAS')
    AND NOT EXISTS(SELECT 1 FROM @Tablas x WHERE x.ObjectId=f.parent_object_id);
  OPEN dependencias; FETCH NEXT FROM dependencias INTO @parent,@nombre,@sql;
  WHILE @@FETCH_STATUS=0
  BEGIN
   EXEC sys.sp_executesql @sql,N'@H bit OUTPUT',@H=@hay OUTPUT;
   IF @hay=1
   BEGIN
    SELECT OBJECT_SCHEMA_NAME(@parent) Esquema,OBJECT_NAME(@parent) TablaExterna,@nombre Restriccion;
    THROW 55010,'Hay referencias externas a IDs regenerados; no se borraron documentos/planes. Resolver esa dependencia.',1;
   END;
   FETCH NEXT FROM dependencias INTO @parent,@nombre,@sql;
  END;
  CLOSE dependencias; DEALLOCATE dependencias;
  CREATE TABLE #FKs(ParentId int,Nombre sysname COLLATE DATABASE_DEFAULT,Deshabilitada bit,NoConfiable bit);
  INSERT #FKs SELECT f.parent_object_id,f.name,f.is_disabled,f.is_not_trusted FROM sys.foreign_keys f
   WHERE EXISTS(SELECT 1 FROM @Tablas t WHERE t.ObjectId=f.parent_object_id OR t.ObjectId=f.referenced_object_id);
  CREATE TABLE #Triggers(ParentId int,Nombre sysname COLLATE DATABASE_DEFAULT);
  INSERT #Triggers SELECT tr.parent_id,tr.name FROM sys.triggers tr JOIN @Tablas t ON t.ObjectId=tr.parent_id WHERE tr.is_disabled=0;
  DECLARE desactivar CURSOR LOCAL FAST_FORWARD FOR SELECT ParentId,Nombre FROM #FKs WHERE Deshabilitada=0;
  OPEN desactivar; FETCH NEXT FROM desactivar INTO @parent,@nombre;
  WHILE @@FETCH_STATUS=0
  BEGIN
   SET @sql=N'ALTER TABLE '+QUOTENAME(OBJECT_SCHEMA_NAME(@parent))+N'.'+QUOTENAME(OBJECT_NAME(@parent))+N' NOCHECK CONSTRAINT '+QUOTENAME(@nombre)+N';'; EXEC sys.sp_executesql @sql;
   FETCH NEXT FROM desactivar INTO @parent,@nombre;
  END;
  CLOSE desactivar; DEALLOCATE desactivar;
  DECLARE desactivartrg CURSOR LOCAL FAST_FORWARD FOR SELECT ParentId,Nombre FROM #Triggers;
  OPEN desactivartrg; FETCH NEXT FROM desactivartrg INTO @parent,@nombre;
  WHILE @@FETCH_STATUS=0
  BEGIN
   SET @sql=N'DISABLE TRIGGER '+QUOTENAME(@nombre)+N' ON '+QUOTENAME(OBJECT_SCHEMA_NAME(@parent))+N'.'+QUOTENAME(OBJECT_NAME(@parent))+N';'; EXEC sys.sp_executesql @sql;
   FETCH NEXT FROM desactivartrg INTO @parent,@nombre;
  END;
  CLOSE desactivartrg; DEALLOCATE desactivartrg;
  INSERT dbo.VCT_PRM_AGENDA_ESTADOS(CODIGO,DESCRIPCION)
   SELECT c.CODIGO,c.DESCRIPCION FROM (VALUES('OC','Ocupado Certificacion'),('ND','No Disponible'),('D','Disponible'),('OP','Ocupado Personal'),('OA','Ocupado A'),('A','Agendado'),('LIC','Licencia'),('POT','Potencial')) c(CODIGO,DESCRIPCION)
   WHERE NOT EXISTS(SELECT 1 FROM dbo.VCT_PRM_AGENDA_ESTADOS e WHERE e.CODIGO COLLATE DATABASE_DEFAULT=c.CODIGO COLLATE DATABASE_DEFAULT);
  UPDATE d SET ID_ESTADO=e.ID FROM #D d JOIN dbo.VCT_PRM_AGENDA_ESTADOS e ON e.CODIGO COLLATE DATABASE_DEFAULT=UPPER(LTRIM(RTRIM(d.TIPO))) COLLATE DATABASE_DEFAULT;
  INSERT dbo.VCT_PRM_VIATICOS_TIPOS(CODIGO,DESCRIPCION,ORDEN,ESTADO,FECHA_ALTA,USUARIO_ALTA)
   SELECT c.CODIGO,c.DESCRIPCION,c.ORDEN,'ACTIVO',@ahora,'MIGRACION_LK' FROM (VALUES('MICRO','Micro',10),('HOTEL','Hotel',20),('REMIS','Remis',30),('AVION','Avion',40),('REFRIGERIO','Refrigerio',50),('TAXI','Taxi',60),('ALQUILER','Alquiler',70),('AUTO','Auto',80)) c(CODIGO,DESCRIPCION,ORDEN)
   WHERE NOT EXISTS(SELECT 1 FROM dbo.VCT_PRM_VIATICOS_TIPOS e WHERE e.CODIGO COLLATE DATABASE_DEFAULT=c.CODIGO COLLATE DATABASE_DEFAULT);
  UPDATE w SET ID_TIPO_VIATICO=e.ID FROM #W w JOIN dbo.VCT_PRM_VIATICOS_TIPOS e ON e.CODIGO COLLATE DATABASE_DEFAULT=UPPER(LTRIM(RTRIM(w.TIPO_PROVEEDOR))) COLLATE DATABASE_DEFAULT;
  DELETE dbo.VCT_PROYECTOS_VIATICOS_DET;
  DELETE dbo.VCT_PROYECTOS_VIATICOS;
  DELETE dbo.VCT_PROYECTOS_HONORARIOS;
  DELETE dbo.VCT_PROYECTOS_RENTABILIDAD;
  DELETE dbo.VCT_PROYECTOS_VISITAS_NORMAS;
  DELETE dbo.VCT_PROYECTOS_NORMAS;
  DELETE dbo.VCT_PROYECTOS_EQUIPO;
  DELETE dbo.VCT_PROYECTOS_VISITAS_CONSULTORES;
  DELETE dbo.VCT_AGENDA_PERSONAS;
  DELETE dbo.VCT_PROYECTOS_VISITAS;
  DELETE dbo.VCT_PROYECTOS_SERVICIOS;
  DELETE dbo.VCT_PROYECTOS;
  SET IDENTITY_INSERT dbo.VCT_PROYECTOS ON; SET @identity=N'VCT_PROYECTOS';
  INSERT dbo.VCT_PROYECTOS([CODIGO],[FECHA_INICIO_REAL],[FECHA_FIN_REAL],[MONTO_PRES],[MONTO_PRES_VIAT],[COSTO_MO],[COSTO_VIAT],[COSTO_VARIOS],[MONTO_TOTAL],[COSTO_TOTAL],[MONTO_COBRADO],[OBSERV_RENTA],[FECHA_PRESUPUESTO],[FECHA_ALTA],[USUARIO_ALTA],[TOTAL_HORAS_PROYECTADAS],[NIVEL_RIESGO],[ESTADO_COBRO],[ID],[IDCLIENTE],[NOMBRE],[REFERENCIA],[ID_ESTADO],[FECHA_INICIO],[FECHA_FIN],[PORCENTAJE_AVANCE],[MONEDA],[OBSERVACIONES],[IDPROPUESTA],[TOTAL_HORAS_EJECUTADAS],[IDCONTACTO]) SELECT [CODIGO],[FECHA_INICIO_REAL],[FECHA_FIN_REAL],[MONTO_PRES],[MONTO_PRES_VIAT],[COSTO_MO],[COSTO_VIAT],[COSTO_VARIOS],[MONTO_TOTAL],[COSTO_TOTAL],[MONTO_COBRADO],[OBSERV_RENTA],[FECHA_PRESUPUESTO],[FECHA_ALTA],[USUARIO_ALTA],[TOTAL_HORAS_PROYECTADAS],[NIVEL_RIESGO],[ESTADO_COBRO],[ID],[IDCLIENTE],[NOMBRE],[REFERENCIA],[ID_ESTADO],[FECHA_INICIO],[FECHA_FIN],[PORCENTAJE_AVANCE],[MONEDA],[OBSERVACIONES],[IDPROPUESTA],[TOTAL_HORAS_EJECUTADAS],[IDCONTACTO] FROM #P;
  SET IDENTITY_INSERT dbo.VCT_PROYECTOS OFF; SET @identity=NULL;
  SET IDENTITY_INSERT dbo.VCT_PROYECTOS_SERVICIOS ON; SET @identity=N'VCT_PROYECTOS_SERVICIOS';
  INSERT dbo.VCT_PROYECTOS_SERVICIOS([ID_PROYECTO],[FECHA_INICIO],[FECHA_FIN],[FECHA_INICIO_REAL],[FECHA_FIN_REAL],[FECHA_ALTA],[USUARIO_ALTA],[LUGAR],[TOTAL_HORAS_PROYECTADAS],[ID],[ID_SERVICIO],[ID_ESTADO],[PRINCIPAL],[ORDEN],[SECUENCIA],[PORCENTAJE_AVANCE],[OBSERVACIONES],[NOMBRE],[TOTAL_HORAS_EJECUTADAS]) SELECT [ID_PROYECTO],[FECHA_INICIO],[FECHA_FIN],[FECHA_INICIO_REAL],[FECHA_FIN_REAL],[FECHA_ALTA],[USUARIO_ALTA],[LUGAR],[TOTAL_HORAS_PROYECTADAS],[ID],[ID_SERVICIO],[ID_ESTADO],[PRINCIPAL],[ORDEN],[SECUENCIA],[PORCENTAJE_AVANCE],[OBSERVACIONES],[NOMBRE],[TOTAL_HORAS_EJECUTADAS] FROM #S;
  SET IDENTITY_INSERT dbo.VCT_PROYECTOS_SERVICIOS OFF; SET @identity=NULL;
  SET IDENTITY_INSERT dbo.VCT_PROYECTOS_VISITAS ON; SET @identity=N'VCT_PROYECTOS_VISITAS';
  INSERT dbo.VCT_PROYECTOS_VISITAS([ID_PROYECTO],[DIAS],[OBSERVADOR],[OBSERV_LOGISTICA],[OBSERV_CALIF],[INDICADOR_HR],[FECHA_ALTA],[USUARIO_ALTA],[ID],[ID_PROYECTO_SERVICIO],[FECHA_DESDE],[FECHA_HASTA],[LUGAR],[DESCRIPCION],[OBSERVACIONES],[ESTADO],[TOTAL_HORAS_EJECUTADAS],[HORAS_SIN_CONSULTOR]) SELECT [ID_PROYECTO],[DIAS],[OBSERVADOR],[OBSERV_LOGISTICA],[OBSERV_CALIF],[INDICADOR_HR],[FECHA_ALTA],[USUARIO_ALTA],[ID],[ID_PROYECTO_SERVICIO],[FECHA_DESDE],[FECHA_HASTA],[LUGAR],[DESCRIPCION],[OBSERVACIONES],[ESTADO],[TOTAL_HORAS_EJECUTADAS],[HORAS_SIN_CONSULTOR] FROM #V;
  SET IDENTITY_INSERT dbo.VCT_PROYECTOS_VISITAS OFF; SET @identity=NULL;
  SET IDENTITY_INSERT dbo.VCT_PROYECTOS_VISITAS_CONSULTORES ON; SET @identity=N'VCT_PROYECTOS_VISITAS_CONSULTORES';
  INSERT dbo.VCT_PROYECTOS_VISITAS_CONSULTORES([ID],[ID_VISITA],[ID_CONSULTOR],[LIDER],[HORAS_PLANIFICADAS],[HORAS_EJECUTADAS],[OBSERVACIONES],[FECHA_ALTA],[USUARIO_ALTA]) SELECT [ID],[ID_VISITA],[ID_CONSULTOR],[LIDER],[HORAS_PLANIFICADAS],[HORAS_EJECUTADAS],[OBSERVACIONES],[FECHA_ALTA],[USUARIO_ALTA] FROM #VC_ID;
  SET IDENTITY_INSERT dbo.VCT_PROYECTOS_VISITAS_CONSULTORES OFF; SET @identity=NULL;
  SET IDENTITY_INSERT dbo.VCT_PROYECTOS_EQUIPO ON; SET @identity=N'VCT_PROYECTOS_EQUIPO';
  INSERT dbo.VCT_PROYECTOS_EQUIPO([ID],[ID_PROYECTO],[ID_PROYECTO_SERVICIO],[TIPO_MIEMBRO],[ID_EMPLEADO],[ID_CONSULTOR],[ID_ROL],[PRINCIPAL],[FECHA_DESDE],[FECHA_HASTA],[ESTADO],[OBSERVACIONES],[FECHA_ALTA],[USUARIO_ALTA]) SELECT [ID],[ID_PROYECTO],[ID_PROYECTO_SERVICIO],[TIPO_MIEMBRO],[ID_EMPLEADO],[ID_CONSULTOR],[ID_ROL],[PRINCIPAL],[FECHA_DESDE],[FECHA_HASTA],[ESTADO],[OBSERVACIONES],[FECHA_ALTA],[USUARIO_ALTA] FROM #E;
  SET IDENTITY_INSERT dbo.VCT_PROYECTOS_EQUIPO OFF; SET @identity=NULL;
  SET IDENTITY_INSERT dbo.VCT_PROYECTOS_NORMAS ON; SET @identity=N'VCT_PROYECTOS_NORMAS';
  INSERT dbo.VCT_PROYECTOS_NORMAS([ID],[ID_PROYECTO],[ID_PROYECTO_SERVICIO],[ID_NORMA],[PRINCIPAL],[OBLIGATORIA],[ESTADO],[OBSERVACIONES],[FECHA_ALTA],[USUARIO_ALTA]) SELECT [ID],[ID_PROYECTO],[ID_PROYECTO_SERVICIO],[ID_NORMA],[PRINCIPAL],[OBLIGATORIA],[ESTADO],[OBSERVACIONES],[FECHA_ALTA],[USUARIO_ALTA] FROM #PN;
  SET IDENTITY_INSERT dbo.VCT_PROYECTOS_NORMAS OFF; SET @identity=NULL;
  SET IDENTITY_INSERT dbo.VCT_PROYECTOS_VISITAS_NORMAS ON; SET @identity=N'VCT_PROYECTOS_VISITAS_NORMAS';
  INSERT dbo.VCT_PROYECTOS_VISITAS_NORMAS([ID],[ID_VISITA],[ID_NORMA],[OBSERVACIONES],[FECHA_ALTA],[USUARIO_ALTA]) SELECT [ID],[ID_VISITA],[ID_NORMA],[OBSERVACIONES],[FECHA_ALTA],[USUARIO_ALTA] FROM #VN;
  SET IDENTITY_INSERT dbo.VCT_PROYECTOS_VISITAS_NORMAS OFF; SET @identity=NULL;
  SET IDENTITY_INSERT dbo.VCT_PROYECTOS_RENTABILIDAD ON; SET @identity=N'VCT_PROYECTOS_RENTABILIDAD';
  INSERT dbo.VCT_PROYECTOS_RENTABILIDAD([ID_PROYECTO_RENTA],[ID_PROYECTO],[PERIODO],[VENTAS],[COMPRAS],[FECHA_ALTA],[USUARIO_ALTA],[OBSERVACIONES]) SELECT [ID_PROYECTO_RENTA],[ID_PROYECTO],[PERIODO],[VENTAS],[COMPRAS],[FECHA_ALTA],[USUARIO_ALTA],[OBSERVACIONES] FROM #R;
  SET IDENTITY_INSERT dbo.VCT_PROYECTOS_RENTABILIDAD OFF; SET @identity=NULL;
  SET IDENTITY_INSERT dbo.VCT_AGENDA_PERSONAS ON; SET @identity=N'VCT_AGENDA_PERSONAS';
  INSERT dbo.VCT_AGENDA_PERSONAS([FECHA],[DIA],[MES],[ANO],[ISHOLIDAY],[HOLIDAYTEXT],[TIPO],[FECHA_ALTA],[USUARIO_ALTA],[HORAS],[DESCRIPCION],[HORAS_DISP],[ID],[TIPO_ENTIDAD],[ID_CONSULTOR],[ID_EMPLEADO],[ID_PERSONA_ORIGEN],[ID_VISITA],[ID_AGENDA_ORIGEN],[ID_ESTADO],[OBSERVACIONES]) SELECT [FECHA],[DIA],[MES],[ANO],[ISHOLIDAY],[HOLIDAYTEXT],[TIPO],[FECHA_ALTA],[USUARIO_ALTA],[HORAS],[DESCRIPCION],[HORAS_DISP],[ID],[TIPO_ENTIDAD],[ID_CONSULTOR],[ID_EMPLEADO],[ID_PERSONA_ORIGEN],[ID_VISITA],[ID_AGENDA_ORIGEN],[ID_ESTADO],[OBSERVACIONES] FROM #D;
  SET IDENTITY_INSERT dbo.VCT_AGENDA_PERSONAS OFF; SET @identity=NULL;
  SET IDENTITY_INSERT dbo.VCT_PROYECTOS_HONORARIOS ON; SET @identity=N'VCT_PROYECTOS_HONORARIOS';
  INSERT dbo.VCT_PROYECTOS_HONORARIOS([ID_TIPO_SERVICIO],[ID_AGENDA],[FECHA],[LUGAR],[IMPORTE],[ID],[ID_PROYECTO_ORIGEN],[ID_CONSULTOR_ORIGEN],[ID_PROYECTO],[ID_VISITA],[ID_PROYECTO_SERVICIO],[ID_CONSULTOR],[OBSERVACIONES],[IMPORTE_NUMERICO]) SELECT [ID_TIPO_SERVICIO],[ID_AGENDA],[FECHA],[LUGAR],[IMPORTE],[ID],[ID_PROYECTO_ORIGEN],[ID_CONSULTOR_ORIGEN],[ID_PROYECTO],[ID_VISITA],[ID_PROYECTO_SERVICIO],[ID_CONSULTOR],[OBSERVACIONES],[IMPORTE_NUMERICO] FROM #F;
  SET IDENTITY_INSERT dbo.VCT_PROYECTOS_HONORARIOS OFF; SET @identity=NULL;
  SET IDENTITY_INSERT dbo.VCT_PROYECTOS_VIATICOS ON; SET @identity=N'VCT_PROYECTOS_VIATICOS';
  INSERT dbo.VCT_PROYECTOS_VIATICOS([ID_TIPO_SERVICIO],[ID_AGENDA],[TIPO_CONSULTOR],[TIPO_PROVEEDOR],[NRO_FC],[CANT_PERSONAS],[DESCRIP_SERVICIO],[FECHA_FC],[PRECIO_FINAL],[FORMA_PAGO],[CANT_CUOTAS],[ESTADO_PAGO],[FECHA_ULT_PAGO],[PRECIO_CUOTA],[PROX_VENCIMIENTO],[SALDO_PEND],[DESTINO],[FECHA_DESDE_SERV],[FECHA_HASTA_SERV],[DESC_FORMA_PAGO],[ID],[ID_PROYECTO_ORIGEN],[ID_CONSULTOR_ORIGEN],[ID_PROYECTO],[ID_VISITA],[ID_PROYECTO_SERVICIO],[ID_CONSULTOR],[OBSERVACIONES],[ID_PROVEEDOR_ORIGEN],[ID_PROVEEDOR],[ID_TIPO_VIATICO]) SELECT [ID_TIPO_SERVICIO],[ID_AGENDA],[TIPO_CONSULTOR],[TIPO_PROVEEDOR],[NRO_FC],[CANT_PERSONAS],[DESCRIP_SERVICIO],[FECHA_FC],[PRECIO_FINAL],[FORMA_PAGO],[CANT_CUOTAS],[ESTADO_PAGO],[FECHA_ULT_PAGO],[PRECIO_CUOTA],[PROX_VENCIMIENTO],[SALDO_PEND],[DESTINO],[FECHA_DESDE_SERV],[FECHA_HASTA_SERV],[DESC_FORMA_PAGO],[ID],[ID_PROYECTO_ORIGEN],[ID_CONSULTOR_ORIGEN],[ID_PROYECTO],[ID_VISITA],[ID_PROYECTO_SERVICIO],[ID_CONSULTOR],[OBSERVACIONES],[ID_PROVEEDOR_ORIGEN],[ID_PROVEEDOR],[ID_TIPO_VIATICO] FROM #W;
  SET IDENTITY_INSERT dbo.VCT_PROYECTOS_VIATICOS OFF; SET @identity=NULL;
  SET IDENTITY_INSERT dbo.VCT_PROYECTOS_VIATICOS_DET ON; SET @identity=N'VCT_PROYECTOS_VIATICOS_DET';
  INSERT dbo.VCT_PROYECTOS_VIATICOS_DET([ID_AGENDA],[DET_PROV_RESERVA],[DET_PROV_VUELO],[DET_PROV_ORIGEN],[DET_PROV_DESTINO],[DET_PROV_SALIDA],[DET_PROV_LLEGADA],[DET_PROV_LOCAL],[PAGA_CONSULTOR],[PAGA_CONSULTORA],[RENDICION_CLIENTE],[DET_PROV_KMS],[DET_PROV_PEAJES],[DET_PROV_FECHA],[DET_PROV_FINGRESO],[DET_PROV_FEGRESO],[DET_PROV_FPARTIDA],[DET_PROV_FLLEGADA],[ID],[ID_VIATICO],[ID_VISITA],[ID_PROYECTO_VIATICOS_ORIGEN],[KMS_NUMERICO],[PEAJES_NUMERICO],[OBSERVACIONES]) SELECT [ID_AGENDA],[DET_PROV_RESERVA],[DET_PROV_VUELO],[DET_PROV_ORIGEN],[DET_PROV_DESTINO],[DET_PROV_SALIDA],[DET_PROV_LLEGADA],[DET_PROV_LOCAL],[PAGA_CONSULTOR],[PAGA_CONSULTORA],[RENDICION_CLIENTE],[DET_PROV_KMS],[DET_PROV_PEAJES],[DET_PROV_FECHA],[DET_PROV_FINGRESO],[DET_PROV_FEGRESO],[DET_PROV_FPARTIDA],[DET_PROV_FLLEGADA],[ID],[ID_VIATICO],[ID_VISITA],[ID_PROYECTO_VIATICOS_ORIGEN],[KMS_NUMERICO],[PEAJES_NUMERICO],[OBSERVACIONES] FROM #WD;
  SET IDENTITY_INSERT dbo.VCT_PROYECTOS_VIATICOS_DET OFF; SET @identity=NULL;
  DECLARE validar CURSOR LOCAL FAST_FORWARD FOR SELECT Tabla,Temp,Esperadas,ColumnaId FROM #Resumen;
  DECLARE @temp sysname;
  OPEN validar; FETCH NEXT FROM validar INTO @nombre,@temp,@esperado,@columna;
  WHILE @@FETCH_STATUS=0
  BEGIN
   SET @sql=N'SELECT @N=COUNT_BIG(*) FROM dbo.'+QUOTENAME(@nombre)+N';';
   EXEC sys.sp_executesql @sql,N'@N bigint OUTPUT',@N=@n OUTPUT;
   IF @n<>@esperado THROW 55011,'Conteos incorrectos; se revierte todo.',1;
   SET @sql=N'SELECT @H=CASE WHEN EXISTS(SELECT '+QUOTENAME(@columna)+N' FROM #'+@temp+N' EXCEPT SELECT '+QUOTENAME(@columna)+N' FROM dbo.'+QUOTENAME(@nombre)+N') OR EXISTS(SELECT '+QUOTENAME(@columna)+N' FROM dbo.'+QUOTENAME(@nombre)+N' EXCEPT SELECT '+QUOTENAME(@columna)+N' FROM #'+@temp+N') THEN 1 ELSE 0 END;';
   EXEC sys.sp_executesql @sql,N'@H bit OUTPUT',@H=@hay OUTPUT;
   IF @hay=1 THROW 55012,'IDs incorrectos; se revierte todo.',1;
   SET @tabla=N'dbo.'+QUOTENAME(@nombre);
   SET @sql=N'SELECT @M=MAX(CONVERT(bigint,'+QUOTENAME(@columna)+N')) FROM '+@tabla;
   EXEC sys.sp_executesql @sql,N'@M bigint OUTPUT',@M=@ultimo OUTPUT;
   SET @valor=CASE WHEN @ultimo IS NOT NULL THEN @ultimo WHEN EXISTS(SELECT 1 FROM sys.identity_columns WHERE object_id=OBJECT_ID(@tabla) AND last_value IS NULL) THEN 1 ELSE 0 END;
   SET @sql=N'DBCC CHECKIDENT(N'''+REPLACE(@tabla,'''','''''')+N''',RESEED,'+CONVERT(nvarchar(20),@valor)+N') WITH NO_INFOMSGS;'; EXEC sys.sp_executesql @sql;
   FETCH NEXT FROM validar INTO @nombre,@temp,@esperado,@columna;
  END;
  CLOSE validar; DEALLOCATE validar;
  DECLARE restaurar CURSOR LOCAL FAST_FORWARD FOR SELECT ParentId,Nombre,NoConfiable FROM #FKs WHERE Deshabilitada=0;
  OPEN restaurar; FETCH NEXT FROM restaurar INTO @parent,@nombre,@trust;
  WHILE @@FETCH_STATUS=0
  BEGIN
   SET @tabla=QUOTENAME(OBJECT_SCHEMA_NAME(@parent))+N'.'+QUOTENAME(OBJECT_NAME(@parent));
   SET @sql=N'ALTER TABLE '+@tabla+N' WITH CHECK CHECK CONSTRAINT '+QUOTENAME(@nombre)+N';'; EXEC sys.sp_executesql @sql;
   IF @trust=1
   BEGIN
    SET @sql=N'ALTER TABLE '+@tabla+N' NOCHECK CONSTRAINT '+QUOTENAME(@nombre)+N'; ALTER TABLE '+@tabla+N' CHECK CONSTRAINT '+QUOTENAME(@nombre)+N';'; EXEC sys.sp_executesql @sql;
   END;
   FETCH NEXT FROM restaurar INTO @parent,@nombre,@trust;
  END;
  CLOSE restaurar; DEALLOCATE restaurar;
  DECLARE restaurartrg CURSOR LOCAL FAST_FORWARD FOR SELECT ParentId,Nombre FROM #Triggers;
  OPEN restaurartrg; FETCH NEXT FROM restaurartrg INTO @parent,@nombre;
  WHILE @@FETCH_STATUS=0
  BEGIN
   SET @sql=N'ENABLE TRIGGER '+QUOTENAME(@nombre)+N' ON '+QUOTENAME(OBJECT_SCHEMA_NAME(@parent))+N'.'+QUOTENAME(OBJECT_NAME(@parent)); EXEC sys.sp_executesql @sql;
   FETCH NEXT FROM restaurartrg INTO @parent,@nombre;
  END;
  CLOSE restaurartrg; DEALLOCATE restaurartrg;
  INSERT dbo.VCT_MIGRACION_PROYECTOS_EJECUCIONES(ID,FECHA,USUARIO,EXCEPCIONES) SELECT @run,@ahora,LEFT(SUSER_SNAME(),100),COUNT_BIG(*) FROM #Excepciones;
  INSERT dbo.VCT_MIGRACION_PROYECTOS_EXCEPCIONES(ID_EJECUCION,TABLA_ORIGEN,ID_ORIGEN,CAMPO,OBSERVACIONES) SELECT @run,TABLA_ORIGEN,ID_ORIGEN,CAMPO,OBSERVACIONES FROM #Excepciones;
  COMMIT TRANSACTION;
  SELECT N'MIGRACION PROYECTOS CONFIRMADA' Resultado,@run ID_EJECUCION;
  SELECT Tabla,Esperadas FilasCargadas FROM #Resumen ORDER BY Tabla;
 END TRY
 BEGIN CATCH
  IF XACT_STATE()<>0 ROLLBACK TRANSACTION;
  IF @identity IS NOT NULL
  BEGIN TRY
   SET @sql=N'SET IDENTITY_INSERT dbo.'+QUOTENAME(@identity)+N' OFF;'; EXEC sys.sp_executesql @sql;
  END TRY
  BEGIN CATCH
   PRINT N'Cerrar esta conexion antes de reintentar: no pudo limpiarse IDENTITY_INSERT.';
  END CATCH;
  THROW;
 END CATCH;
END;
