CREATE   PROCEDURE [dbo].[M_CONFIG_DEL_USER_SECTOR]
(@IPKEYJOB	AS VARCHAR(100),
 @IUSERID	AS VARCHAR(100))
AS
 
BEGIN	
 
	DECLARE	@ID_USER_SEL VARCHAR(50),
			@ID_SECTOR_SEL VARCHAR(50),
			@VUSER VARCHAR(50)
 
	SELECT	@ID_USER_SEL = ID_DELETE, 
			@ID_SECTOR_SEL = ID_SECTOR_SEL  
	FROM	M_CONFIG 
	WHERE	PAR_KEY = @IPKEYJOB;
 
	SELECT	@VUSER = ID_USER
	FROM	USERSSECTOR
	WHERE	ID_USERSECTOR = @ID_USER_SEL
 
	DECLARE @VSECTOR_DESC VARCHAR(300), @VDESC_USER VARCHAR(300)
 
	SELECT	@VSECTOR_DESC = ISNULL(DESC_SECTOR,'')
	FROM	SECTORES
	WHERE	ID_SECTOR = CONVERT(NUMERIC,@ID_SECTOR_SEL)
 
	SELECT	@VDESC_USER = ISNULL(NAME,'')
	FROM	USERS
	WHERE	ID = @VUSER
 
	/* ====== Insert ====== */
	BEGIN TRANSACTION
 
		DELETE UsersSector where Id_Sector= @ID_SECTOR_SEL  and Id_UserSector = @ID_USER_SEL;	
 
	COMMIT TRANSACTION
	RETURN;
 
END
