CREATE PROCEDURE [dbo].[HOME_ADD_PLANEST_CONS]
(@IPKEYJOB	AS VARCHAR(100),
 @IAGENTE	AS VARCHAR(100),
 @OCODE		AS VARCHAR(2) OUTPUT,
 @OMENSAJE	AS VARCHAR(400) OUTPUT)
AS
 
DECLARE	@VID_PROYECTO		VARCHAR(100),
		@VID_SERVICIO		VARCHAR(100),
		@VSERVICIO			VARCHAR(50),
		@VFECHA				DATETIME,
		@VOBSERVACION		VARCHAR(400),
		@VFRECUENCIA		VARCHAR(50),
		@VID_DOC			VARCHAR(50),
		@VID_PROYECTO_DOCUM	VARCHAR(50),
		@VDESC_DOC_DET		VARCHAR(400), 
		@VGRUPO_DOC_DET		VARCHAR(50),
		@VCANT				INT,
		@VERROR				VARCHAR(50),
		@VAGENDA_ID			VARCHAR(50),
		@VTIPO				VARCHAR(50),
		@VADJUNTO_ANT		VARCHAR(100),
		@VADJUNTO			VARCHAR(100),
		@VID_MINUTA			VARCHAR(100)
 
BEGIN	
 
	SET @OCODE = '0'
	SET @OMENSAJE = ''
 
	SELECT	@VAGENDA_ID		= ISNULL(AGENDA_ID,''),
			@VID_PROYECTO	= ISNULL(PROYECTO_ID,''),
			@VID_SERVICIO	= ISNULL(PROYECTO_SERV_ID,''),
			@VFECHA			= ISNULL(CONS_FECHA_PE,''),
			@VOBSERVACION	= ISNULL(CONS_OBSERV_PE,''),
			@VFRECUENCIA	= ISNULL(CONS_FRECUENCIA_PE,''),
			@VERROR			= ISNULL(ERROR,''),
			@VTIPO			= ISNULL(TIPO_SELEC,''),
			@VID_MINUTA		= ISNULL(ID_MINUTA,'')
	FROM	XAGENDA
	WHERE	PAR_KEY = @IPKEYJOB	
 
	SELECT	@VSERVICIO = ID_TIPO_SERVICIO
	FROM	LK_PROYECTO_SERVICIO
	WHERE	ID_PROYECTO_SERVICIO = @VID_SERVICIO
 
	SELECT	@VADJUNTO_ANT = ISNULL(ID_ADJUNTO,'')
	FROM	LK_PROYECTO_DOCUM
	WHERE	ID_PROYECTO_DOCUM = @VID_MINUTA
 
	SELECT	@VADJUNTO = ISNULL(PKEY,'')
	FROM	PHYSICAL_ATTACHED_DOCUMENT
	WHERE	PAR_KEY = @IPKEYJOB
 
	IF (@VFECHA = '') BEGIN
		SET @OCODE = '1'
			
		UPDATE	XAGENDA
		SET		ERROR = 'SI', DESC_ERROR = 'Debe Completar el Campo Fecha'
		WHERE	PAR_KEY = @IPKEYJOB
		RETURN
	END
	
	IF (@VID_MINUTA = '') BEGIN
		
		INSERT INTO LK_PROYECTO_DOCUM
		(ID_PROYECTO, ID_TIPO_SERVICIO, ID_DOCUMENTACION, FECHA_DOCUM, NRO_DOCUM_INTERNO,
			PARTICIPANTES_DOCUM, TEMAS_DOCUM, ADJUNTO_DOCUM,
			CONSULTOR, VISITA_MES, CONSULTOR_ACOMP, OBSERVACIONES,FECHA_CIERRE, ID_AGENDA, TIPO, ID_ADJUNTO, PROYECTO_SERV_ID)
		VALUES
		(@VID_PROYECTO, @VSERVICIO, 0, @VFECHA, 'Plan Estrategico',
			NULL, @VFRECUENCIA, NULL,
			NULL, NULL, NULL, @VOBSERVACION, NULL, NULL, 'PE', @VADJUNTO, @VID_SERVICIO)
 
	END ELSE BEGIN
 
		UPDATE	LK_PROYECTO_DOCUM
		SET		FECHA_DOCUM = @VFECHA, OBSERVACIONES = @VOBSERVACION,
				ID_ADJUNTO = ISNULL(@VADJUNTO,@VADJUNTO_ANT)
		WHERE	ID_PROYECTO_DOCUM = @VID_MINUTA
 
		IF (@VADJUNTO <> '') BEGIN
			UPDATE	PHYSICAL_ATTACHED_DOCUMENT
			SET		PAR_KEY = @VID_PROYECTO
			WHERE	PKEY = @VADJUNTO
 
			DELETE	PHYSICAL_ATTACHED_DOCUMENT
			WHERE	PKEY = @VADJUNTO_ANT
		END
 
	END
 
	IF (@VADJUNTO <> '') BEGIN
		UPDATE	PHYSICAL_ATTACHED_DOCUMENT
		SET		PAR_KEY = @VID_PROYECTO
		WHERE	PKEY = @VADJUNTO
	END
 
	UPDATE	XAGENDA
	SET		CONS_FECHA_PE = NULL,
			CONS_OBSERV_PE = NULL,
			CONS_FRECUENCIA_PE = NULL
	WHERE	PAR_KEY = @IPKEYJOB
	
	IF (@OCODE = '0') BEGIN
		UPDATE	XAGENDA
		SET		ERROR = 'NO'
		WHERE	PAR_KEY = @IPKEYJOB
	END
END
