CREATE PROCEDURE [dbo].[EP_DEL_EQUIPO_CERTIF]
(@IPKEYJOB	AS VARCHAR(100))
AS
 
BEGIN	
 
	DECLARE 
	@ID_EQ_CERTIF_SEL VARCHAR(50)
 
 
	SELECT @ID_EQ_CERTIF_SEL = EQ_CERTIF_SEL FROM TMT_CRON WHERE PAR_KEY= @IPKEYJOB;
 
	DELETE EP_EQUIPOS_CERTIF 
		WHERE ID = @ID_EQ_CERTIF_SEL
 
	DELETE PHYSICAL_ATTACHED_DOCUMENT
		WHERE PAR_KEY=@ID_EQ_CERTIF_SEL
 
END
