 
CREATE PROCEDURE [dbo].[EP_UPD_USUARIO]
(@IPKEYJOB	AS VARCHAR(100),
 @IUSERID	AS VARCHAR(100))
AS
 
BEGIN	
 
	DECLARE @ID_USER_SEL VARCHAR(50),
	@NEW_ID VARCHAR(50),
	@NEW_NAME VARCHAR(100),
	@NEW_EMAIL VARCHAR(100),
	@NEW_PASS VARCHAR(100),
	@CURRENT_PASS VARCHAR(100),
	@NEW_ESTADO_CUENTA VARCHAR(20),
	@STATE INT
	
	
 
	SELECT @NEW_ID= NEW_ID, @NEW_EMAIL=NEW_EMAIL, @NEW_NAME=NEW_NAME, @NEW_PASS=NEW_PASSWORD, @NEW_ESTADO_CUENTA=NEW_ESTADO_CUENTA  
		FROM TMT_CRON WHERE PAR_KEY = @IPKEYJOB;
	SELECT @CURRENT_PASS=[Password] FROM Users WHERE Id = @NEW_ID;
	SELECT @state=cast(attr1 as int) FROM CAT_DATA WHERE CAT_DATA_CODE = @NEW_ESTADO_CUENTA;
	
	IF (isnull(@CURRENT_PASS,'')<>@NEW_PASS)
		BEGIN
			SET @NEW_PASS = CONVERT(VARCHAR(40), HashBytes('SHA1', upper(@NEW_ID)+@NEW_PASS), 2);
		END
 
	UPDATE USERS
	SET EMAIL=@NEW_EMAIL,
	[PASSWORD]=@NEW_PASS,
	[NAME]=@NEW_NAME,
	[STATE] = @STATE,
	LOGINFAILURE = 0	
	WHERE [ID]=@NEW_ID;
	 
 
END
