CREATE PROCEDURE [dbo].[HOME_INICIO_PROYECTO_HIST]
(@IPKEYJOB	AS VARCHAR(100),
 @FORM_ID	AS VARCHAR(100))
AS
 
DECLARE		
	@VF_CLIENTE			VARCHAR(50),
	@VF_PROYECTO		VARCHAR(50),
	@VF_SERVICIO		VARCHAR(50)
 
BEGIN	
 
		SELECT	@VF_CLIENTE = ISNULL(INICIO_CLIENTE,''),
				@VF_PROYECTO = ISNULL(PROYECTO,''),
				@VF_SERVICIO = ISNULL(SERVICIO,'')
		FROM	XAGENDA
		WHERE	PAR_KEY = @IPKEYJOB
 
 
		SELECT	CLIENTE						AS Cliente, 
				PROYECTO							AS Proyecto, 
				'<font style="font-family:Tahoma, Arial, Helvetica, sans-serif;font-size:10px;color:black;text-align: left">'+ISNULL(OBSERV,'Sin Observaciones')+'</font>' AS Obs, 
				ISNULL(ESTADO_DESC,'Sin Estado')	AS Estado, 
				dbo.FN_GET_NORMA_HTML('<font style="font-family:Tahoma, Arial, Helvetica, sans-serif;font-size:10px;color:black;text-align: left">',NORMAS,'</font>') AS Normas,
				FECHA_INICIO						AS "Fecha Inicio", 
				FECHA_FIN							AS "Fecha Fin", 
				HORASP+'/'+[dbo].[FN_GET_TOTAL_HS_EJECUTADAS] ('P', ID, NULL, NULL) AS "Horas",
				[dbo].[FN_GET_SERVICIOS_PROY] (ID, @FORM_ID) AS "Servicios",
				--'<i class="fas fa-edit w3-large" style="cursor:pointer;" title="Modificar" onclick="almacenarSeleccion(''NRO_COTIZA'','''+cast(NRO_COTIZA as varchar)+''');almacenarSeleccion(''CLIENTE'','''+cast(PROYECTOS.ID_CLIENTE as varchar)+''');almacenarSeleccion(''ESTADO_PROY'','''+ISNULL(PROYECTOS.ESTADO,'')+''');almacenarSeleccion(''PROYECTO_ID'','''+cast(ID as varchar)+''');goto('''+@FORM_ID+''',''2F0833BA-8A65-4039-8443-95158FCDB8CF'');"></i>&nbsp;'+
				CASE WHEN ISNULL(NRO_COTIZA,0) <> 0 THEN 
					'<i class="fas fa-file-word w3-large" style="cursor:pointer;" title="Ver Propuesta" onclick="OpenAttach('''+ISNULL(ID_ADJUNTO,'')+''','''+ISNULL(ATACH_COTIZ.FILE_NAME,'')+''');return false;"></i>'  
				ELSE '' END 
				/*+ '&nbsp;' +
				CASE WHEN ISNULL(SUM(A.DIAS),0) = 0 THEN 
					'<i class="fas fa-trash-alt w3-large" style="cursor:pointer;" title="' +'Eliminar Proyecto'+ '" 
						onclick="confirmar=confirm(''¿Esta seguro que quiere eliminar el Proyecto?'');
						if (confirmar){almacenarSeleccion(''ID_DELETE'','''+cast(ID as varchar)+ ''');goto('''+@FORM_ID+''',''522967A7-DDC9-465B-969B-85997AE1B085'');}"/>'
				ELSE ''
				END*/ AS Propuesta		
		FROM	
			(
			SELECT DISTINCT CLI.RAZON_SOCIAL_CLIENTE						AS CLIENTE,
					'('+CODIGO+') - '+NORMA_REF								AS PROYECTO,
					CONVERT(VARCHAR,P.FECHA_INICIO_REAL,103)				AS FECHA_INICIO,
					CASE WHEN ISNULL(P.FECHA_FIN_REAL,'') = '' THEN '' ELSE CONVERT(VARCHAR,P.FECHA_FIN_REAL,103) END	AS FECHA_FIN,
					CONVERT(VARCHAR,P.TOTAL_HORAS_PROYECTADAS)				AS HORASP,
					--CONVERT(VARCHAR,ISNULL(P.TOTAL_HORAS_EJECUTADAS,'0'))	AS HORASE,
					P.ID_PROYECTO							 AS ID,
					CLI.ID_CLIENTE							 AS ID_CLIENTE,
					ESTADO_PROYECTO_TOTAL					 AS ESTADO,
					CD.CAT_DATA_DESC						 AS ESTADO_DESC,
					NORMAS									 AS NORMAS,
					P.OBSERVACIONES							 AS OBSERV,
					P.ID_COTIZACION							 AS NRO_COTIZA,
					C.ID_ADJUNTO
			FROM	LK_PROYECTO P
					INNER JOIN LK_CLIENTES CLI ON P.ID_CLIENTE = CLI.ID_CLIENTE
					--LEFT JOIN LK_PROYECTO_SERVICIO PS ON P.ID_PROYECTO = PS.ID_PROYECTO
					LEFT JOIN CAT_DATA CD ON CD.CAT_DATA_CODE = P.ESTADO_PROYECTO_TOTAL AND CD.PAR_KEY = (SELECT PKEY FROM CAT_TYPE WHERE CAT_TYPE_CODE = 'ESTADOS_PROYECTO')
					--LEFT JOIN LK_AGENDA A ON A.ID_CLIENTE = CLI.ID_CLIENTE AND A.ID_PROYECTO = P.ID_PROYECTO
					LEFT JOIN LK_COTIZACIONES C ON C.ID_COTIZACION = P.ID_COTIZACION
			WHERE	P.ESTADO_PROYECTO_TOTAL = 'TERMINADO'
			) PROYECTOS 
			LEFT JOIN PHYSICAL_ATTACHED_DOCUMENT ATACH_COTIZ ON ATACH_COTIZ.PKEY = PROYECTOS.ID_ADJUNTO
			LEFT JOIN LK_AGENDA A ON A.ID_CLIENTE = PROYECTOS.ID_CLIENTE AND A.ID_PROYECTO = PROYECTOS.ID
		WHERE	CONVERT(VARCHAR,PROYECTOS.ID_CLIENTE) = CASE WHEN @VF_CLIENTE <> '' THEN @VF_CLIENTE ELSE CONVERT(VARCHAR,PROYECTOS.ID_CLIENTE) END
		AND		CONVERT(VARCHAR,PROYECTOS.ID) = CASE WHEN @VF_PROYECTO <> '' THEN @VF_PROYECTO ELSE CONVERT(VARCHAR,PROYECTOS.ID) END
		--AND		CONVERT(VARCHAR,ISNULL(PS.ID_TIPO_SERVICIO,'')) = CASE WHEN @VF_SERVICIO <> '' THEN @VF_SERVICIO ELSE CONVERT(VARCHAR,ISNULL(PS.ID_TIPO_SERVICIO,'')) END
		GROUP BY CLIENTE, PROYECTO, OBSERV, PROYECTOS.ESTADO, NORMAS, FECHA_INICIO, FECHA_FIN, HORASP, ID, PROYECTOS.ID_CLIENTE, NRO_COTIZA, ID_ADJUNTO, ESTADO_DESC,ATACH_COTIZ.FILE_NAME
		ORDER BY CLIENTE, FECHA_INICIO
END
