CREATE PROCEDURE SP_SAVE_ATTACHED_DOC
	(@PKEY AS VARCHAR(100),
	@OUTPUT_FILE AS VARCHAR(500))
AS
 
DECLARE @OBJECTTOKEN INT,
		@BINARYDATA VARBINARY(MAX),
		@ERROR AS INTEGER
 
SELECT @BINARYDATA = ATTACHED_DOC
FROM PHYSICAL_ATTACHED_DOCUMENT
WHERE PKEY = @PKEY
 
EXEC SP_OACREATE 'ADODB.STREAM', @OBJECTTOKEN OUTPUT
EXEC SP_OASETPROPERTY @OBJECTTOKEN, 'TYPE', 1
EXEC SP_OAMETHOD @OBJECTTOKEN, 'OPEN'
EXEC SP_OAMETHOD @OBJECTTOKEN, 'WRITE', NULL, @BINARYDATA
EXEC @ERROR = SP_OAMETHOD @OBJECTTOKEN, 'SAVETOFILE', NULL, @OUTPUT_FILE, 2
EXEC SP_OAMETHOD @OBJECTTOKEN, 'CLOSE'
EXEC SP_OADESTROY @OBJECTTOKEN
 
PRINT 'EXTRACCION DE ATTACHMENT: ' + @OUTPUT_FILE + ' (RESULTADO: ' + CONVERT(VARCHAR, @@ERROR) + ')'
