CREATE PROCEDURE PA_SYS_RPT_LOCKED_UNLOCKED_ACC (@PD_FECHA_DESDE DATETIME = NULL, @PD_FECHA_HASTA DATETIME = NULL, @PS_RET_MESSAGE VARCHAR(440) = NULL OUTPUT) AS
 
-- =========================================================================================================================
-- AUTOR: TITO - ENGAGE SOFTWARE COMPANY
-- FECHA DE CREACIÓN: 12/09/2011
-- EDITOR: MAXI BRIZZI - ENGAGE SOFTWARE COMPANY
-- FECHA DE MODIFICACIÓN: 23/12/2011
-- TABLAS LEÍDAS: AUDITOR, VW_SYS_USUARIO.
-- TABLAS MODIFICADAS: NINGUNA.
-- DESCRIPCIÓN: PROCEDIMIENTO QUE REPORTA LAS ACCIONES DE BLOQUEO Y DESBLOQUEO DE CUENTAS.
-- CONSIDERACIONES:
-- 1. EL PARÁMETRO DE SALIDA @PS_RET_MESSAGE DEVUELVE EL MENSAJE DE ERROR. NULL SI NO HUBO.
-- =========================================================================================================================
 
SET NOCOUNT ON;
SET XACT_ABORT ON;
 
-- DECLARACIÓN E INICIALIZACIÓN DE VARIABLES DE ERROR Y AUXILIARES.
DECLARE @LNERRORNUM AS INTEGER,
	@LNSEVERITY AS SMALLINT,
	@LNFILAS_AFEC AS INTEGER,
	@LDINICIO_OPE AS DATETIME,
	@LNDURACION AS INTEGER,
	@LSOPERA AS VARCHAR(30),
	@LSPROC AS VARCHAR(30),
	@LSTABLA AS VARCHAR(30),
	@LSERRORLOG AS VARCHAR(440),
	@LSERRORDESC AS VARCHAR(440),
	@LSSQL_CMD AS VARCHAR(4000)
;
SELECT 	@LNERRORNUM = 0,
	@LNSEVERITY = 16,
	@LNFILAS_AFEC = 0,
	@LDINICIO_OPE = GETDATE(),
	@LNDURACION = 0,
	@LSOPERA = 'EXECUTE',
	@LSPROC = OBJECT_NAME(@@PROCID),
	@LSTABLA = 'NINGUNA',
	@LSERRORLOG = @@SERVERNAME + '.' + DB_NAME() + '.' + USER_NAME() + '.' + OBJECT_NAME(@@PROCID) + ' - ',
	@LSERRORDESC = NULL,
	@LSSQL_CMD = NULL
;
-- DECLARA LAS VARIABLES.
DECLARE
@LD_FECHA_DESDE DATETIME,
@LD_FECHA_HASTA DATETIME,
@LN_GRUPO_ACCION_ACC NUMERIC(5, 0),
@LN_ACCION_MODIF_ACC NUMERIC(5, 0);
 
-- DETERMINA LAS FECHAS DE PROCESO. SÓLO FECHA SIN HORA.
SELECT @LD_FECHA_DESDE = CASE WHEN @PD_FECHA_DESDE IS NULL THEN CONVERT(VARCHAR, GETDATE(), 112) ELSE CONVERT(VARCHAR, @PD_FECHA_DESDE, 112) END;
SELECT @LD_FECHA_HASTA = CASE WHEN @PD_FECHA_HASTA IS NULL THEN CONVERT(VARCHAR, GETDATE() + 1, 112) ELSE CONVERT(VARCHAR, @PD_FECHA_HASTA, 112) END;
 
SELECT  @LN_GRUPO_ACCION_ACC = 1100, -- AUTENTICACIÓN DE ENGAGE.
	@LN_ACCION_MODIF_ACC = 1103; -- MODIFICAR ESTADO DE CUENTA.
 
-- DECLARO LA TRANSACCIÓN.
BEGIN TRANSACTION
 
IF (@LD_FECHA_DESDE = @LD_FECHA_HASTA) BEGIN
	SET @LD_FECHA_HASTA = @LD_FECHA_HASTA + 1;
END;
 
IF (@LD_FECHA_DESDE < @LD_FECHA_HASTA) BEGIN
	SELECT	US.USER_NAME AS "Nombre de usuario",
		US.USER_ID AS "Id de usuario",
		A1.TS_BEGIN AS "Fecha de la acción",
		CASE CONVERT(NUMERIC(1, 0), A1.REG_ACTUAL)
		WHEN 0 THEN 'No activa'
		WHEN 1 THEN 'Activa'
		WHEN 2 THEN 'Bloqueada'
		WHEN 3 THEN 'Expirada'
		WHEN 4 THEN 'Bloqueada por inactividad'
		WHEN 5 THEN 'Expirada por inactividad'
		ELSE NULL END AS "Estado actual de la cuenta",
		CASE CONVERT(NUMERIC(1, 0), A1.REG_ANTERIOR)
		WHEN 0 THEN 'No activa'
		WHEN 1 THEN 'Activa'
		WHEN 2 THEN 'Bloqueada'
		WHEN 3 THEN 'Expirada'
		WHEN 4 THEN 'Bloqueada por inactividad'
		WHEN 5 THEN 'Expirada por inactividad'
		ELSE NULL END AS "Estado anterior de la cuenta",
		A1.TS_USER_ID AS "Ejecutante"
	FROM	AUDITOR A1
		INNER JOIN VW_SYS_USUARIO US ON (A1.USER_ID_ACCION = US.USER_ID)
	WHERE	(A1.TS_BEGIN >= @LD_FECHA_DESDE
		AND A1.TS_BEGIN < @LD_FECHA_HASTA)
		AND (A1.GRUPO_ACCION = @LN_GRUPO_ACCION_ACC)
		AND (A1.ACCION = @LN_ACCION_MODIF_ACC)
		AND (A1.REG_ANTERIOR IN ('2', '3', '4', '5'))
		AND (A1.REG_ACTUAL IN ('0', '1'))
	UNION ALL
	SELECT	US.USER_NAME AS "Nombre de usuario",
		US.USER_ID AS "Id de usuario",
		A1.TS_BEGIN AS "Fecha de la acción",
		CASE CONVERT(NUMERIC(1, 0), A1.REG_ACTUAL)
		WHEN 0 THEN 'No activa'
		WHEN 1 THEN 'Activa'
		WHEN 2 THEN 'Bloqueada'
		WHEN 3 THEN 'Expirada'
		WHEN 4 THEN 'Bloqueada por inactividad'
		WHEN 5 THEN 'Expirada por inactividad'
		ELSE NULL END AS "Estado actual de la cuenta",
		CASE CONVERT(NUMERIC(1, 0), A1.REG_ANTERIOR)
		WHEN 0 THEN 'No activa'
		WHEN 1 THEN 'Activa'
		WHEN 2 THEN 'Bloqueada'
		WHEN 3 THEN 'Expirada'
		WHEN 4 THEN 'Bloqueada por inactividad'
		WHEN 5 THEN 'Expirada por inactividad'
		ELSE NULL END AS "Estado anterior de la cuenta",
		A1.TS_USER_ID AS "Ejecutante"
	FROM	AUDITOR A1
		INNER JOIN VW_SYS_USUARIO US ON (A1.USER_ID_ACCION = US.USER_ID)
	WHERE	(A1.TS_BEGIN >= @LD_FECHA_DESDE
		AND A1.TS_BEGIN < @LD_FECHA_HASTA)
		AND (A1.GRUPO_ACCION = @LN_GRUPO_ACCION_ACC)
		AND (A1.ACCION = @LN_ACCION_MODIF_ACC)
		AND (A1.REG_ACTUAL IN ('2', '3', '4', '5'))
		AND (A1.REG_ANTERIOR IN ('0', '1'))
	ORDER BY 1 ASC, 2 ASC, 3 DESC, 4 ASC;
	SELECT @LSOPERA = 'SELECT', @LSTABLA = 'AUDITOR', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
END
ELSE BEGIN
	SET @PS_RET_MESSAGE = 'EL PARÁMETRO @PD_FECHA_HASTA DEBE CONTENER UNA FECHA MAYOR A LA DE @PD_FECHA_DESDE';
END;
 
FALLO:
-- REGISTRO DE SUCESOS Y CONTROL DE FIN DE PROCEDIMIENTO. CONCLUYE LA TRANSACCIÓN SI TODO FUE EXITOSO.
SELECT @LNDURACION = DATEDIFF(SECOND, @LDINICIO_OPE, GETDATE()), @LNSEVERITY = ISNULL(EM.SEVERITY, 16), @LSERRORDESC = 'ERROR ' + CONVERT(VARCHAR, ISNULL(EM.ERROR, 0)) + ' - ' + ISNULL(EM.DESCRIPTION, ' ') FROM MASTER.DBO.SYSMESSAGES EM WHERE (EM.ERROR = @LNERRORNUM);
IF (@LNERRORNUM <> 0) BEGIN
	-- NOTIFICACIÓN EN EL REGISTRO DE SQL SERVER.
	SET @LSERRORLOG = @LSERRORLOG + CASE WHEN (ISNULL(CHARINDEX('%', @LSERRORDESC), 0) > 0) THEN RTRIM(LEFT(@LSERRORDESC, 11)) ELSE @LSERRORDESC END;
	-- DEVUELVE EL ERROR EN EL PARÁMETRO DE SALIDA.
	SET @PS_RET_MESSAGE = SUBSTRING(@LSERRORDESC, 1, 440);
	-- DESHACE LA TRANSACCIÓN COMPLETA SI LA OPERACIÓN FALLÓ.
	IF (@@TRANCOUNT > 0) ROLLBACK TRANSACTION;
	EXECUTE @LNERRORNUM = PA_SYS_REGISTRO_SUCESOS_INSERT @PSPROCEDIMIENTO_1 = @LSPROC, @PSTABLA_2 = @LSTABLA, @PNFILAS_AFECTADAS_3 = @LNFILAS_AFEC, @PSOPERACION_4 = @LSOPERA, @PNDURACION_5 = @LNDURACION, @PSRESULTADO_6 = @LSERRORDESC, @PSSQL_CMD_7 = @LSERRORDESC;
	-- RAISERROR(@LSERRORLOG, @LNSEVERITY, -1) WITH NOWAIT;
END
ELSE BEGIN
--	EXECUTE @LNERRORNUM = PA_SYS_REGISTRO_SUCESOS_INSERT @PSPROCEDIMIENTO_1 = @LSPROC, @PSTABLA_2 = @LSTABLA, @PNFILAS_AFECTADAS_3 = @LNFILAS_AFEC, @PSOPERACION_4 = @LSOPERA, @PNDURACION_5 = @LNDURACION, @PSRESULTADO_6 = @LSERRORDESC, @PSSQL_CMD_7 = @LSERRORDESC;
	IF (@@TRANCOUNT > 0) COMMIT TRANSACTION;
END;
RETURN;
