CREATE PROCEDURE [dbo].[HOME_CMB_EMPLEADO_CALIF]
(@IPKEYJOB	AS VARCHAR(100))
AS
 
DECLARE @VSERVICIO VARCHAR(50),
		@VTIPOSERVICIO varchar(50)
 
BEGIN	
 
	SELECT	@VSERVICIO = PROYECTO_SERV_ID
	FROM	XAGENDA
	WHERE	PAR_KEY = @IPKEYJOB
 
	SELECT	@VTIPOSERVICIO = ID_TIPO_SERVICIO
	FROM	LK_PROYECTO_SERVICIO
	WHERE	ID_PROYECTO_SERVICIO = @VSERVICIO
 
	SELECT	DISTINCT EMP.ID_EMPLEADO AS CAT_DATA_CODE,
				 APELLIDO_EMPLEADO + ', ' + NOMBRE_EMPLEADO + ' - (' + MIN(APT.CALIFICACION) +')' AS CAT_DATA_DESC,
				 'TRUE' TRUE
	FROM	LK_EMPLEADOS_TIPO T
			INNER JOIN LK_EMPLEADOS EMP ON EMP.ID_EMPLEADO = T.ID_EMPLEADO
			LEFT JOIN (SELECT	EA.ID_EMPLEADO, CALIFICACION 
						FROM	LK_EMPLEADOS_APTITUD EA 
								INNER JOIN LK_EMPLEADOS EMP ON EMP.ID_EMPLEADO = EA.ID_EMPLEADO AND EA.CALIFICACION IS NOT NULL) APT ON APT.ID_EMPLEADO =  EMP.ID_EMPLEADO
	WHERE	T.ID_TIPO = @VTIPOSERVICIO
	AND		EMP.PERFIL_EMP = 'CONSULTOR'
	GROUP BY EMP.ID_EMPLEADO, APELLIDO_EMPLEADO + ', ' + NOMBRE_EMPLEADO
 
END
 
