CREATE PROCEDURE PA_SYS_OBTIENE_PKEY_RANGO (@PSTABLA VARCHAR(50), @PNCANTIDADCLAVES INT, @PSSECUENCIAL VARCHAR(50) OUTPUT, @PSDIFERENCIADOR VARCHAR(4) OUTPUT) AS
 
-- =========================================================================================================================
-- AUTOR: GASTÓN ARIMÓN - ENGAGE SOFTWARE COMPANY
-- FECHA DE CREACIÓN: 27/11/2006
-- EDITOR: TITO - ENGAGE SOFTWARE COMPANY
-- FECHA DE EDICIÓN: 01/09/2009
-- TABLAS LEÍDAS: PRM.
-- TABLAS MODIFICADAS: PRM.
-- DESCRIPCIÓN: PROCEDIMIENTO QUE TOMA UN RANGO DE CLAVES NUEVAS PARA LA TABLA PASADA POR PARÁMETRO.
-- CONSIDERACIONES:
-- 1. UTLIZADO POR EL MANAGER PARA GENERACIÓN DE CLAVES MASIVAS PARA TRÁMITES DE LISTAS.
-- =========================================================================================================================
 
SET NOCOUNT ON;
SET XACT_ABORT ON;
 
-- DECLARACIÓN E INICIALIZACIÓN DE VARIABLES DE ERROR Y AUXILIARES.
DECLARE @LNERRORNUM AS INTEGER,
	@LNSEVERITY AS SMALLINT,
	@LNFILAS_AFEC AS INTEGER,
	@LDINICIO_OPE AS DATETIME,
	@LNDURACION AS INTEGER,
	@LSOPERA AS VARCHAR(30),
	@LSPROC AS VARCHAR(30),
	@LSTABLA AS VARCHAR(30),
	@LSERRORLOG AS VARCHAR(440),
	@LSERRORDESC AS VARCHAR(440),
	@LSSQL_CMD AS VARCHAR(4000)
;
SELECT 	@LNERRORNUM = 0,
	@LNSEVERITY = 16,
	@LNFILAS_AFEC = 0,
	@LDINICIO_OPE = GETDATE(),
	@LNDURACION = 0,
	@LSOPERA = 'EXECUTE',
	@LSPROC = OBJECT_NAME(@@PROCID),
	@LSTABLA = 'NINGUNA',
	@LSERRORLOG = @@SERVERNAME + '.' + DB_NAME() + '.' + USER_NAME() + '.' + OBJECT_NAME(@@PROCID) + ' - ',
	@LSERRORDESC = NULL,
	@LSSQL_CMD = NULL
;
-- DECLARA LAS VARIABLES.
DECLARE
@LS_TABLA VARCHAR(50),
@LNCANTIDADCLAVES INT,
@LSSECUENCIAL VARCHAR(50),
@LSDIFERENCIADOR VARCHAR(4)
;
-- ASIGNA VALORES PREDETERMINADOS A LAS VARIABLES.
SELECT	@LS_TABLA = LTRIM(RTRIM(@PSTABLA)),
	@LNCANTIDADCLAVES = ISNULL(@PNCANTIDADCLAVES, 0),
	@LSSECUENCIAL = NULL,
	@LSDIFERENCIADOR = NULL
;
 
-- DECLARO LA TRANSACCIÓN.
BEGIN TRANSACTION
 
IF (@LNCANTIDADCLAVES > 0) BEGIN
	-- AGREGA EL SUFIJO '_KEY' AL NOMBRE DE LA TABLA.
	SET @LS_TABLA = @LS_TABLA + '_KEY';
	-- INCREMENTA EL CONTADOR CORRESPONDIENTE EN LA TABLA PRM.
	UPDATE	PRM
	SET	PRM_VAL = CONVERT(VARCHAR, CONVERT(NUMERIC(10), PRM_VAL) + @LNCANTIDADCLAVES)
	WHERE	(PRM_COD = @LS_TABLA)
	SELECT @LSOPERA = 'UPDATE', @LSTABLA = 'PRM', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
	-- TOMA EL VALOR DE LA CLAVE SIN EL INCREMENTO.
	SELECT	@LSSECUENCIAL = CONVERT(VARCHAR, CONVERT(NUMERIC(10), PRM_VAL) - @LNCANTIDADCLAVES),
		@LSDIFERENCIADOR = PRM_NUM
	FROM	PRM
	WHERE	(PRM_COD = @LS_TABLA)
	SELECT @LSOPERA = 'SELECT', @LSTABLA = 'PRM', @LNFILAS_AFEC = @@ROWCOUNT, @LNERRORNUM = @@ERROR;
	IF (@LNERRORNUM <> 0) GOTO FALLO;
END;
 
-- DETERMINA SI SE GENERÓ UNA CLAVE O SI HUBO ERROR LÓGICO.
IF (@LSSECUENCIAL IS NULL) BEGIN
	SET @LSERRORDESC = 'LA CLAVE ' + @LS_TABLA + ' NO EXISTE EN PRM.PRM_COD';
	SET @LNERRORNUM = 50000;
	GOTO FALLO;
END
ELSE BEGIN
	SELECT	@PSSECUENCIAL = @LSSECUENCIAL,
		@PSDIFERENCIADOR = @LSDIFERENCIADOR;
END;
 
FALLO:
-- REGISTRO DE SUCESOS Y CONTROL DE FIN DE PROCEDIMIENTO. CONCLUYE LA TRANSACCIÓN SI TODO FUE EXITOSO.
SELECT @LNDURACION = DATEDIFF(SECOND, @LDINICIO_OPE, GETDATE()), @LNSEVERITY = ISNULL(EM.SEVERITY, 16), @LSERRORDESC = 'ERROR ' + CONVERT(VARCHAR, ISNULL(EM.ERROR, 0)) + ' - ' + ISNULL(EM.DESCRIPTION, ' ') FROM MASTER.DBO.SYSMESSAGES EM WHERE (EM.ERROR = @LNERRORNUM);
IF (@LNERRORNUM <> 0) BEGIN
	-- NOTIFICACIÓN EN EL REGISTRO DE SQL SERVER.
	SET @LSERRORLOG = @LSERRORLOG + CASE WHEN (ISNULL(CHARINDEX('%', @LSERRORDESC), 0) > 0) THEN RTRIM(LEFT(@LSERRORDESC, 11)) ELSE @LSERRORDESC END;
	-- DESHACE LA TRANSACCIÓN COMPLETA SI LA OPERACIÓN FALLÓ.
	IF (@@TRANCOUNT > 0) ROLLBACK TRANSACTION;
	EXECUTE @LNERRORNUM = PA_SYS_REGISTRO_SUCESOS_INSERT @PSPROCEDIMIENTO_1 = @LSPROC, @PSTABLA_2 = @LSTABLA, @PNFILAS_AFECTADAS_3 = @LNFILAS_AFEC, @PSOPERACION_4 = @LSOPERA, @PNDURACION_5 = @LNDURACION, @PSRESULTADO_6 = @LSERRORDESC, @PSSQL_CMD_7 = @LSERRORDESC;
	RAISERROR(@LSERRORLOG, @LNSEVERITY, -1) WITH NOWAIT;
END
ELSE BEGIN
	-- EXECUTE @LNERRORNUM = PA_SYS_REGISTRO_SUCESOS_INSERT @PSPROCEDIMIENTO_1 = @LSPROC, @PSTABLA_2 = @LSTABLA, @PNFILAS_AFECTADAS_3 = @LNFILAS_AFEC, @PSOPERACION_4 = @LSOPERA, @PNDURACION_5 = @LNDURACION, @PSRESULTADO_6 = @LSERRORDESC, @PSSQL_CMD_7 = @LSERRORDESC;
	IF (@@TRANCOUNT > 0) COMMIT TRANSACTION;
END;
RETURN;
