CREATE PROCEDURE [dbo].[HOME_ADD_HOJA_RUTA]
(@IPKEYJOB	AS VARCHAR(100),
 @IAGENTE	AS VARCHAR(100),
 @OCODE		AS VARCHAR(2) OUTPUT,
 @OMENSAJE	AS VARCHAR(400) OUTPUT)
AS
 
DECLARE	@VPROYECTO			VARCHAR(50),
		@VPROYECTO_SERV		VARCHAR(50),
		@VTIPO_SERV			VARCHAR(50),
		@VFECHA_INI			DATETIME,
		@VCONSULTOR			VARCHAR(50),
		@VVISITA			DATETIME,
		@VCONSULTOR_ACOMP	VARCHAR(50),
		@VOBSERVACION		VARCHAR(400),
		@VFECHA_CIERRE		DATETIME,
		@VNOMBRE			VARCHAR(100),
		@VID_DOC			VARCHAR(50),
		@VID_PROYECTO_DOCUM	VARCHAR(50),
		@VDESC_DOC_DET		VARCHAR(400), 
		@VGRUPO_DOC_DET		VARCHAR(50),
		@VCANT				INT
 
BEGIN	
 
	SET @OCODE = '0'
	SET @OMENSAJE = ''
 
	SELECT	@VPROYECTO		= ISNULL(PROYECTO_ID,''),
			@VPROYECTO_SERV = ISNULL(PROYECTO_SERV_ID,''),
			@VFECHA_INI = ISNULL(FECHA_HR,''),
			@VCONSULTOR = ISNULL(CONSULTOR_HR,''),
			@VVISITA = NULLIF(ISNULL(VISITA_MES_HR,''),''),
			@VCONSULTOR_ACOMP = ISNULL(CONSULTOR_ACOMP_HR,''),
			@VOBSERVACION = ISNULL(OBSERVACION_HR,''),
			@VFECHA_CIERRE = NULLIF(ISNULL(FECHA_CIERRE_HR,''),''),
			@VNOMBRE = ISNULL(NOMBRE_HR,'')
	FROM	XAGENDA
	WHERE	PAR_KEY = @IPKEYJOB
 
	SELECT	@VTIPO_SERV = ID_TIPO_SERVICIO
	FROM	LK_PROYECTO_SERVICIO
	WHERE	ID_PROYECTO_SERVICIO = @VPROYECTO_SERV
 
	/*
	IF (@VNOMBRE = '') BEGIN
		SET @OCODE = '1'
		SET @OMENSAJE = CASE WHEN @VTIPO_SERV = '1' THEN
								'<script> alert("Debe completar el Campo Nro/Nombre");</script>'
							 WHEN @VTIPO_SERV = '2' THEN
								'<script> alert("Debe completar el Campo Fechas");</script>'
							 WHEN @VTIPO_SERV = '3' THEN
								'<script> alert("Debe completar el Capacitacion (Tipo,Lugar)");</script>'
						END
		RETURN
	END
	*/
 
	IF (@VFECHA_INI = '') BEGIN
		SET @OCODE = '1'
		SET @OMENSAJE = '<script> alert("Debe completar el Campo Fecha Inicio");</script>'
		RETURN
	END
 
	/*
	--VALIDO QUE NO EXISTA EL MISMO CODIGO EN LK_DOCUMENTACION--
	SELECT	@VCANT = COUNT(1)
	FROM	LK_PROYECTO_DOCUM
	WHERE	ID_PROYECTO = @VPROYECTO
	AND		ID_TIPO_SERVICIO = @VTIPO_SERV
	AND		NRO_DOCUM_INTERNO = LTRIM(RTRIM(@VNOMBRE))
 
	IF (@VCANT > 0) BEGIN
		
		SET @OCODE = '1'
		SET @OMENSAJE = '<script> alert("Ya Existe una Documentacion con el mismo Nro/Nombre para el mismo Proyecto/Servicio");</script>'
		RETURN
 
	END ELSE */
	
	BEGIN
 
		/* Grabo el ID de Documentacion que corresponda segun el Servicio
			5	RE-PP-038	Hoja de Ruta Auditoria
			6	RE-PP-039	Hoja de Ruta Capacitacion
			7	RE-PP-040	Hoja de Ruta Consultoria
 
			1	Consultoria --> GRABO ID 7
			2	Auditoria --> GRABO ID 5
			3	Capacitacion --> GRABO ID 6
		*/
		SELECT	@VID_DOC =	CASE WHEN @VTIPO_SERV = '1' THEN '7'
								 WHEN @VTIPO_SERV = '2' THEN '5'
								 WHEN @VTIPO_SERV = '3' THEN '6'
							END 
 
		INSERT INTO LK_PROYECTO_DOCUM
		(ID_PROYECTO, ID_TIPO_SERVICIO, ID_DOCUMENTACION, FECHA_DOCUM, NRO_DOCUM_INTERNO,
		 PARTICIPANTES_DOCUM, TEMAS_DOCUM, ADJUNTO_DOCUM,
		 CONSULTOR, VISITA_MES, CONSULTOR_ACOMP, OBSERVACIONES,FECHA_CIERRE)
		VALUES
		(@VPROYECTO, @VTIPO_SERV, @VID_DOC, @VFECHA_INI, @VNOMBRE,
		 NULL, NULL, NULL,
		 @VCONSULTOR, @VVISITA, @VCONSULTOR_ACOMP, @VOBSERVACION, @VFECHA_CIERRE)
 
		 SELECT	@VID_PROYECTO_DOCUM = IDENT_CURRENT ('LK_PROYECTO_DOCUM')
 
		 --RECUPERO TODOS LOS ITEMS QUE CORRESPONDEN AL DETALLE DE LA HOJA DE RUTA QUE CORRESPONDA SEGUN SERVICIO--
		 DECLARE Items CURSOR FOR 
			SELECT	DESC_DOC_DET, GRUPO_DOC_DET
			FROM	LK_DOCUMENTACION_DET
			WHERE	ID_DOCUMENTACION = @VID_DOC
			AND		STATUS_DOC_DET = '1'
			ORDER BY ID_DOCUMENTACION_DET
 
		OPEN Items  
		FETCH NEXT FROM Items INTO @VDESC_DOC_DET, @VGRUPO_DOC_DET  
 
		WHILE @@FETCH_STATUS = 0  
		BEGIN  
 
			INSERT INTO LK_PROYECTO_DOCUM_DET
			(ID_PROYECTO_DOCUM, DESC_DOC_DET, VALOR_DOC_DET, GRUPO_DOC_DET, ADJUNTO_DOC_DET)
			VALUES
			(@VID_PROYECTO_DOCUM, @VDESC_DOC_DET, NULL, @VGRUPO_DOC_DET, NULL)
 
			FETCH NEXT FROM Items INTO @VDESC_DOC_DET, @VGRUPO_DOC_DET
		END 
 
		CLOSE Items  
		DEALLOCATE Items
 
	END
 
	UPDATE	XAGENDA
	SET		HOJA_RUTA_ID = @VID_PROYECTO_DOCUM,
			FECHA_HR = NULL,
			CONSULTOR_HR = NULL,
			VISITA_MES_HR = NULL,
			CONSULTOR_ACOMP_HR = NULL,
			OBSERVACION_HR = NULL,
			FECHA_CIERRE_HR = NULL,
			NOMBRE_HR = NULL
	WHERE	PAR_KEY = @IPKEYJOB
 
END
 
