CREATE PROCEDURE PA_SYS_UPD_PORTFOLIO_HIST_TOT (@PSESTUDIO_CODE VARCHAR(50)) AS
-- ESTE PROCEDIMIENTO ALMACENADO SE DEBERÁ UTILIZAR PARA MANTENER LA HISTORIA DE ASIGNACIONES DE ESTUDIOS JURÍDICOS DE TODA LA CARTERA DE CLIENTES.
SET NOCOUNT ON;
SET XACT_ABORT ON;
 
DECLARE
@LSESTUDIO_CODE AS VARCHAR(50);
 
BEGIN TRANSACTION
 
SELECT @LSESTUDIO_CODE = @PSESTUDIO_CODE;
 
COMMIT TRANSACTION;
 
RETURN;
