 
CREATE   PROCEDURE dbo.VCT_NOTIF_GENERAR
(
    @IUNIDAD VARCHAR(100),
    @IAGENTE VARCHAR(100)
)
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @U VARCHAR(100) = LOWER(LTRIM(RTRIM(ISNULL(@IAGENTE,'')))),
            @PERFIL VARCHAR(100) = UPPER(LTRIM(RTRIM(ISNULL(@IUNIDAD,'')))),
            @HOY DATE = CONVERT(DATE, GETDATE()), @CONS_ID INT, @EMP_ID INT, @PRIMERA BIT = 0;
    IF @U = '' RETURN;
 
    SELECT TOP 1 @CONS_ID = ID FROM dbo.VCT_CONSULTORES
    WHERE LOWER(LTRIM(RTRIM(ISNULL(ID_USUARIO_SEGURIDAD,'')))) = @U AND UPPER(ISNULL(ESTADO,'')) = 'ACTIVO' ORDER BY ID DESC;
    SELECT TOP 1 @EMP_ID = ID FROM dbo.VCT_EMPLEADOS
    WHERE LOWER(LTRIM(RTRIM(ISNULL(ID_USUARIO_SEGURIDAD,'')))) = @U AND UPPER(ISNULL(ESTADO,'')) = 'ACTIVO' ORDER BY ID DESC;
    IF NOT EXISTS (SELECT 1 FROM dbo.VCT_NOTIFICACIONES WHERE USUARIO = @U) SET @PRIMERA = 1;
 
    CREATE TABLE #N (TIPO VARCHAR(20), CLAVE VARCHAR(100), TITULO VARCHAR(300), DETALLE VARCHAR(1000),
                     ID_PROYECTO INT, ID_CLIENTE INT, FECHA DATETIME);
 
    CREATE TABLE #G (ID INT PRIMARY KEY);
    INSERT INTO #G (ID)
    SELECT DISTINCT GP.ID_GESTION
    FROM dbo.VCT_GESTIONES_PARTICIPANTES GP
    WHERE GP.ROL_PARTICIPANTE = 'RESPONSABLE' AND GP.ESTADO = 'ACTIVO'
      AND ((GP.TIPO_ENTIDAD = 'CONSULTOR' AND GP.ID_ENTIDAD = @CONS_ID) OR (GP.TIPO_ENTIDAD = 'EMPLEADO' AND GP.ID_ENTIDAD = @EMP_ID));
 
    INSERT INTO #N
    SELECT CASE WHEN T.CODIGO = 'AVISO' THEN 'AVISO' ELSE 'GESTION' END, CONVERT(VARCHAR(20), G.ID),
           LEFT(CASE WHEN T.CODIGO = 'AVISO' THEN G.TITULO ELSE 'Nueva gesti' + CHAR(243) + 'n: ' + G.TITULO END, 300),
           LEFT(ISNULL('(' + P.CODIGO + ') ', '') + ISNULL(P.NOMBRE, '')
                + CASE WHEN G.FECHA_VENCIMIENTO IS NOT NULL THEN ' - vence ' + CONVERT(VARCHAR(10), G.FECHA_VENCIMIENTO, 103) ELSE '' END, 1000),
           G.ID_PROYECTO, P.IDCLIENTE, G.FECHA_CREACION
    FROM #G X
    INNER JOIN dbo.VCT_GESTIONES G ON G.ID = X.ID
    INNER JOIN dbo.VCT_PRM_GESTIONES_ESTADOS GE ON GE.ID = G.ID_ESTADO
    LEFT JOIN dbo.VCT_PRM_GESTIONES_TIPOS T ON T.ID = G.ID_TIPO
    LEFT JOIN dbo.VCT_PROYECTOS P ON P.ID = G.ID_PROYECTO
    WHERE GE.ES_FINAL = 0 AND G.FECHA_CREACION >= DATEADD(DAY, -30, @HOY);
 
    INSERT INTO #N
    SELECT 'VENCIDA', CONVERT(VARCHAR(20), G.ID) + '-' + CONVERT(VARCHAR(8), G.FECHA_VENCIMIENTO, 112),
           LEFT('Gesti' + CHAR(243) + 'n vencida: ' + G.TITULO, 300),
           LEFT(ISNULL('(' + P.CODIGO + ') ', '') + ISNULL(P.NOMBRE, '') + ' - venci' + CHAR(243) + ' el ' + CONVERT(VARCHAR(10), G.FECHA_VENCIMIENTO, 103), 1000),
           G.ID_PROYECTO, P.IDCLIENTE, DATEADD(DAY, 1, CONVERT(DATETIME, CONVERT(DATE, G.FECHA_VENCIMIENTO)))
    FROM #G X
    INNER JOIN dbo.VCT_GESTIONES G ON G.ID = X.ID
    INNER JOIN dbo.VCT_PRM_GESTIONES_ESTADOS GE ON GE.ID = G.ID_ESTADO
    LEFT JOIN dbo.VCT_PROYECTOS P ON P.ID = G.ID_PROYECTO
    WHERE GE.ES_FINAL = 0 AND G.FECHA_VENCIMIENTO IS NOT NULL AND CONVERT(DATE, G.FECHA_VENCIMIENTO) < @HOY;
 
    IF @CONS_ID IS NOT NULL
        INSERT INTO #N
        SELECT 'VISITA', CONVERT(VARCHAR(20), V.ID),
               'Visita sin registrar: ' + CONVERT(VARCHAR(10), V.FECHA_DESDE, 103),
               LEFT(ISNULL('(' + P.CODIGO + ') ', '') + ISNULL(P.NOMBRE, '') + ' - cargale los temas trabajados', 1000),
               V.ID_PROYECTO, P.IDCLIENTE, DATEADD(DAY, 1, CONVERT(DATETIME, CONVERT(DATE, V.FECHA_DESDE)))
        FROM dbo.VCT_PROYECTOS_VISITAS V
        INNER JOIN dbo.VCT_PROYECTOS_VISITAS_CONSULTORES VC ON VC.ID_VISITA = V.ID AND VC.ID_CONSULTOR = @CONS_ID
        INNER JOIN dbo.VCT_PROYECTOS P ON P.ID = V.ID_PROYECTO
        WHERE CONVERT(DATE, V.FECHA_DESDE) BETWEEN DATEADD(DAY, -30, @HOY) AND DATEADD(DAY, -1, @HOY)
          AND NOT EXISTS (SELECT 1 FROM dbo.VCT_PROYECTOS_VISITAS_REGISTRO R WHERE R.ID_VISITA = V.ID);
 
    INSERT INTO #N
    SELECT 'PENDIENTE', CONVERT(VARCHAR(20), G.ID) + '-' + CONVERT(VARCHAR(8), G.FECHA_VENCIMIENTO, 112),
           LEFT('Pendiente del cliente vencido: ' + G.TITULO, 300),
           LEFT(ISNULL('(' + P.CODIGO + ') ', '') + ISNULL(P.NOMBRE, ''), 1000),
           G.ID_PROYECTO, P.IDCLIENTE, DATEADD(DAY, 1, CONVERT(DATETIME, CONVERT(DATE, G.FECHA_VENCIMIENTO)))
    FROM dbo.VCT_GESTIONES G
    INNER JOIN dbo.VCT_PRM_GESTIONES_SUBTIPOS ST ON ST.ID = G.ID_SUBTIPO AND ST.CODIGO = 'PENDIENTE_CLIENTE'
    INNER JOIN dbo.VCT_PRM_GESTIONES_ESTADOS GE ON GE.ID = G.ID_ESTADO
    INNER JOIN dbo.VCT_PROYECTOS P ON P.ID = G.ID_PROYECTO
    WHERE GE.ES_FINAL = 0 AND G.FECHA_VENCIMIENTO IS NOT NULL AND CONVERT(DATE, G.FECHA_VENCIMIENTO) < @HOY
      AND EXISTS (SELECT 1 FROM dbo.VCT_PROYECTOS_EQUIPO EQ WHERE EQ.ID_PROYECTO = P.ID AND EQ.ESTADO = 'ACTIVO'
                  AND ((EQ.TIPO_MIEMBRO = 'CONSULTOR' AND EQ.ID_CONSULTOR = @CONS_ID) OR (EQ.TIPO_MIEMBRO = 'EMPLEADO' AND EQ.ID_EMPLEADO = @EMP_ID)));
 
    IF @PERFIL IN ('GERENCIA','SQUAD','ADMINISTRACION')
        INSERT INTO #N
        SELECT 'HORAS', CONVERT(VARCHAR(20), P.ID),
               LEFT('Horas excedidas: (' + ISNULL(P.CODIGO,'') + ') ' + P.NOMBRE, 300),
               dbo.VCT_FMT_HORAS(H.U) + ' h usadas de ' + CONVERT(VARCHAR(10), P.TOTAL_HORAS_PROYECTADAS) + ' contratadas',
               P.ID, P.IDCLIENTE, GETDATE()
        FROM dbo.VCT_PROYECTOS P
        INNER JOIN dbo.VCT_PRM_PROYECTOS_ESTADOS E ON E.ID = P.ID_ESTADO AND E.CODIGO = 'ENCURSO'
        CROSS APPLY (SELECT SUM(C.HORAS_USADAS) AS U FROM dbo.VCT_PROYECTO_VISITAS_CALC(P.ID) C) H
        WHERE P.TOTAL_HORAS_PROYECTADAS > 0 AND H.U > P.TOTAL_HORAS_PROYECTADAS;
 
    INSERT INTO dbo.VCT_NOTIFICACIONES (USUARIO, TIPO, CLAVE, TITULO, DETALLE, ID_PROYECTO, ID_CLIENTE, FECHA, LEIDA, FECHA_LEIDA)
    SELECT @U, N.TIPO, N.CLAVE, N.TITULO, N.DETALLE, N.ID_PROYECTO, N.ID_CLIENTE, ISNULL(N.FECHA, GETDATE()),
           CASE WHEN @PRIMERA = 1 AND ISNULL(N.FECHA, GETDATE()) < DATEADD(DAY, -7, GETDATE()) THEN 1 ELSE 0 END,
           CASE WHEN @PRIMERA = 1 AND ISNULL(N.FECHA, GETDATE()) < DATEADD(DAY, -7, GETDATE()) THEN GETDATE() END
    FROM (SELECT *, ROW_NUMBER() OVER (PARTITION BY TIPO, CLAVE ORDER BY FECHA DESC) AS RN FROM #N) N
    WHERE N.RN = 1
      AND NOT EXISTS (SELECT 1 FROM dbo.VCT_NOTIFICACIONES X WHERE X.USUARIO = @U AND X.TIPO = N.TIPO AND X.CLAVE = N.CLAVE);
END
