CREATE PROCEDURE [dbo].[HOME_EDIT_DATOS_SEGUIMIENTO]
(@IPKEYJOB	AS VARCHAR(100),
 @IAGENTE	AS VARCHAR(100),
 @OCODE		AS VARCHAR(2) OUTPUT,
 @OMENSAJE	AS VARCHAR(400) OUTPUT)
AS
 
DECLARE	@VPROYECTO			VARCHAR(50),
		@VPROYECTO_SERV		VARCHAR(50),
		@VSERVICIO			VARCHAR(50),
		@VFECHA				DATETIME,
		@VOBSERVACION		VARCHAR(400),
		@VID_DOC			VARCHAR(50),
		@VID_PROYECTO_DOCUM	VARCHAR(50),
		@VDESC_DOC_DET		VARCHAR(400), 
		@VGRUPO_DOC_DET		VARCHAR(50),
		@VCANT				INT,
		@VERROR				VARCHAR(50),
		@VAGENDA_ID			VARCHAR(50),
		@VTIPO				VARCHAR(50),
		@VADJUNTO	VARCHAR(100),
		@VFRECUENCIA		VARCHAR(50),
		@VDOC_EMPRESA		VARCHAR(50),
		@VMANUAL_DOC		VARCHAR(50),
		@VREQ_INGRESO		VARCHAR(50),
		@VCV_CERTIF			VARCHAR(50),
		@VLOGISTICA			VARCHAR(50),
		@VCURSO				VARCHAR(300),
		@VMATERIAL			VARCHAR(50),
		@VESTADO_ENVIO		VARCHAR(50),
		@VRECIBIDO			VARCHAR(50)
 
BEGIN	
 
	SET @OCODE = '0'
	SET @OMENSAJE = ''
 
	SELECT	@VPROYECTO		= ISNULL(PROYECTO_ID,''),
			@VPROYECTO_SERV = ISNULL(PROYECTO_SERV_ID,''),
			@VERROR = ISNULL(ERROR,''),
			@VFRECUENCIA = ISNULL(CONS_FRECUENCIA_PE,''), 
			@VDOC_EMPRESA = ISNULL(CONS_DOC_EMPRESA,''), 
			@VMANUAL_DOC = ISNULL(AUDI_MANUAL,''), 
			@VREQ_INGRESO = ISNULL(AUDI_REQ_INGRESO,''), 
			@VCV_CERTIF = ISNULL(AUDI_CV_CERTIF,''), 
			@VLOGISTICA = ISNULL(AUDI_LOGISTICA,''),
			@VCURSO = ISNULL(CAPA_CURSO,''), 
			@VMATERIAL = ISNULL(CAPA_MATERIAL,''), 
			@VESTADO_ENVIO = ISNULL(CAPA_ESTADO_ENVIO,''), 
			@VRECIBIDO = ISNULL(CAPA_RECIBIDO,'')
	FROM	XAGENDA
	WHERE	PAR_KEY = @IPKEYJOB
 
	SELECT	@VSERVICIO = ID_TIPO_SERVICIO
	FROM	LK_PROYECTO_SERVICIO
	WHERE	ID_PROYECTO_SERVICIO = @VPROYECTO_SERV
 
	BEGIN
		
		UPDATE	LK_PROYECTO_SERVICIO
		SET		FRECUENCIA_ENVIO = @VFRECUENCIA, 
				DOC_EMPRESA = @VDOC_EMPRESA, 
				MANUALES = @VMANUAL_DOC, 
				REQUISITO_INGRESO = @VREQ_INGRESO, 
				CV_CERTIFICADOS = @VCV_CERTIF, 
				LOGISTICA = @VLOGISTICA,
				NOMBRE_CURSO = @VCURSO, 
				MATERIALES = @VMATERIAL, 
				ESTADO_ENVIO = @VESTADO_ENVIO, 
				RECIBIDO = @VRECIBIDO
		WHERE	ID_PROYECTO_SERVICIO = @VPROYECTO_SERV
 
		UPDATE	XAGENDA
		SET		CONS_FRECUENCIA_PE = NULL, 
				CONS_DOC_EMPRESA = NULL, 
				AUDI_MANUAL = NULL, 
				AUDI_REQ_INGRESO = NULL, 
				AUDI_CV_CERTIF = NULL,  
				AUDI_LOGISTICA = NULL, 
				CAPA_CURSO = NULL,  
				CAPA_MATERIAL = NULL,  
				CAPA_ESTADO_ENVIO = NULL,  
				CAPA_RECIBIDO = NULL 
		WHERE	PAR_KEY = @IPKEYJOB
	END
 
END
 
