/* buscar_consultor_con_visitas.sql
   Lista consultores con al menos una visita cuya FECHA_DESDE cae dentro del
   mes calendario en curso -- exactamente el mismo rango que usa {{AGENDA}}
   en VCT_MAIN_SEND_EMAIL, para elegir un @ID_CONSULTOR real de prueba. */

DECLARE @MES_DESDE DATE = DATEFROMPARTS(YEAR(GETDATE()), MONTH(GETDATE()), 1);
DECLARE @MES_HASTA DATE = DATEADD(MONTH, 1, @MES_DESDE);

SELECT
    VC.IDCONSULTOR,
    C.NOMBRES,
    C.APELLIDOS,
    COUNT(*) AS CANTIDAD_VISITAS_MES,
    MIN(V.FECHA_DESDE) AS PRIMERA_VISITA,
    MAX(V.FECHA_DESDE) AS ULTIMA_VISITA
FROM dbo.VCT_PROYECTOS_VISITAS_CONSULTORES VC
INNER JOIN dbo.VCT_PROYECTOS_VISITAS V ON V.ID = VC.IDVISITA
INNER JOIN dbo.VCT_CONSULTORES C ON C.ID = VC.IDCONSULTOR
WHERE V.FECHA_DESDE >= @MES_DESDE
  AND V.FECHA_DESDE < @MES_HASTA
GROUP BY VC.IDCONSULTOR, C.NOMBRES, C.APELLIDOS
ORDER BY CANTIDAD_VISITAS_MES DESC;
