2025-10-10 00:44:09.883	error	The mail could not be sent to the recipients because of the mail server failure. (Sending Mail using Account 10 (2025-10-10T00:44:09). Exception Message: Could not connect to mail server. (A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 167.250.5.42:587).  )	2	Prueba Database Mail - VocaturoSMTP (587 STARTTLS)	lucas.romaniello@squad.com.ar
2025-10-10 00:42:54.423	error	The mail could not be sent to the recipients because of the mail server failure. (Sending Mail using Account 10 (2025-10-10T00:42:54). Exception Message: Could not connect to mail server. (A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 167.250.5.42:587).  )	2	Prueba Database Mail - VocaturoSMTP (587 STARTTLS)	lucas.romaniello@squad.com.ar
2025-10-10 00:42:48.873	error	The mail could not be sent to the recipients because of the mail server failure. (Sending Mail using Account 10 (2025-10-10T00:42:48). Exception Message: Could not connect to mail server. (A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 167.250.5.42:587).  )	2	Prueba Database Mail - VocaturoSMTP (587 STARTTLS)	lucas.romaniello@squad.com.ar
2025-10-10 00:42:09.850	error	The mail could not be sent to the recipients because of the mail server failure. (Sending Mail using Account 10 (2025-10-10T00:42:09). Exception Message: Could not connect to mail server. (A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 167.250.5.42:587).  )	2	Prueba Database Mail - VocaturoSMTP (587 STARTTLS)	lucas.romaniello@squad.com.ar
2025-10-10 00:41:33.413	error	The mail could not be sent to the recipients because of the mail server failure. (Sending Mail using Account 10 (2025-10-10T00:41:33). Exception Message: Could not connect to mail server. (A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 167.250.5.42:587).  )	2	Prueba Database Mail - VocaturoSMTP (587 STARTTLS)	lucas.romaniello@squad.com.ar
2025-10-10 00:40:48.843	error	The mail could not be sent to the recipients because of the mail server failure. (Sending Mail using Account 10 (2025-10-10T00:40:48). Exception Message: Cannot send mails to mail server. (Mailbox unavailable. The server response was: Access denied - Invalid HELO name (See RFC2821 4.1.1.1)).  )	2	Prueba Database Mail - VocaturoSMTP (587 STARTTLS)	lucas.romaniello@squad.com.ar
2025-10-10 00:35:27.083	error	The mail could not be sent to the recipients because of the mail server failure. (Sending Mail using Account 10 (2025-10-10T00:35:27). Exception Message: Cannot send mails to mail server. (The operation has timed out.).  )	2	Prueba Database Mail - VocaturoSMTP	lucas.romaniello@squad.com.ar
2025-10-10 00:34:05.040	error	The mail could not be sent to the recipients because of the mail server failure. (Sending Mail using Account 10 (2025-10-10T00:34:05). Exception Message: Cannot send mails to mail server. (The operation has timed out.).  )	2	Prueba Database Mail - VocaturoSMTP	lucas.romaniello@squad.com.ar
2025-10-10 00:33:11.413	error	The mail could not be sent to the recipients because of the mail server failure. (Sending Mail using Account 10 (2025-10-10T00:33:11). Exception Message: Cannot send mails to mail server. (The operation has timed out.).  )	2	Prueba Database Mail - VocaturoSMTP	lucas.romaniello@squad.com.ar
2025-10-10 00:32:46.827	error	The mail could not be sent to the recipients because of the mail server failure. (Sending Mail using Account 10 (2025-10-10T00:32:46). Exception Message: Cannot send mails to mail server. (The operation has timed out.).  )	2	Prueba Database Mail - VocaturoSMTP	lucas.romaniello@squad.com.ar
2025-10-10 00:31:24.790	error	The mail could not be sent to the recipients because of the mail server failure. (Sending Mail using Account 10 (2025-10-10T00:31:24). Exception Message: Cannot send mails to mail server. (The operation has timed out.).  )	2	Prueba Database Mail - VocaturoSMTP	lucas.romaniello@squad.com.ar
2025-10-10 00:30:31.150	error	The mail could not be sent to the recipients because of the mail server failure. (Sending Mail using Account 10 (2025-10-10T00:30:31). Exception Message: Cannot send mails to mail server. (The operation has timed out.).  )	2	Prueba Database Mail - VocaturoSMTP	lucas.romaniello@squad.com.ar
2025-10-10 00:28:58.397	error	The mail could not be sent to the recipients because of the mail server failure. (Sending Mail using Account 10 (2025-10-10T00:28:58). Exception Message: Cannot send mails to mail server. (The operation has timed out.).  )	2	Prueba Database Mail - VocaturoSMTP	lucas.romaniello@squad.com.ar
2025-10-10 00:26:18.133	error	The mail could not be sent to the recipients because of the mail server failure. (Sending Mail using Account 10 (2025-10-10T00:26:18). Exception Message: Cannot send mails to mail server. (The operation has timed out.).  )	2	Prueba Database Mail - VocaturoSMTP	lucas.romaniello@squad.com.ar
2025-10-10 00:23:02.550	error	The mail could not be sent to the recipients because of the mail server failure. (Sending Mail using Account 10 (2025-10-10T00:23:02). Exception Message: Cannot send mails to mail server. (The operation has timed out.).  )	2	Prueba Database Mail - VocaturoSMTP	lucas.romaniello@squad.com.ar
2025-10-10 00:20:22.300	error	The mail could not be sent to the recipients because of the mail server failure. (Sending Mail using Account 10 (2025-10-10T00:20:22). Exception Message: Cannot send mails to mail server. (The operation has timed out.).  )	2	Prueba Database Mail - VocaturoSMTP	lucas.romaniello@squad.com.ar
2024-12-02 22:02:48.537	error	The mail could not be sent to the recipients because of the mail server failure. (Sending Mail using Account 9 (2024-12-02T22:02:48). Exception Message: Could not connect to mail server. (A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 135.181.67.245:25).  )	2	[CRM Estrucplan] Actualizacion Cronograma OK	webmaster@squad.com.ar; rvalentinuzzi@estrucplan.com.ar; pgomez@estrucplan.com.ar
2024-12-02 22:01:27.507	error	The mail could not be sent to the recipients because of the mail server failure. (Sending Mail using Account 9 (2024-12-02T22:01:27). Exception Message: Could not connect to mail server. (A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 135.181.67.245:25).  )	2	[CRM Estrucplan] Actualizacion Cronograma OK	webmaster@squad.com.ar; rvalentinuzzi@estrucplan.com.ar; pgomez@estrucplan.com.ar
2024-12-01 22:02:53.867	error	The mail could not be sent to the recipients because of the mail server failure. (Sending Mail using Account 9 (2024-12-01T22:02:53). Exception Message: Could not connect to mail server. (A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 135.181.67.245:25).  )	2	[CRM Estrucplan] Actualizacion Cronograma OK	webmaster@squad.com.ar; rvalentinuzzi@estrucplan.com.ar; pgomez@estrucplan.com.ar
2024-12-01 22:01:32.820	error	The mail could not be sent to the recipients because of the mail server failure. (Sending Mail using Account 9 (2024-12-01T22:01:32). Exception Message: Could not connect to mail server. (A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 135.181.67.245:25).  )	2	[CRM Estrucplan] Actualizacion Cronograma OK	webmaster@squad.com.ar; rvalentinuzzi@estrucplan.com.ar; pgomez@estrucplan.com.ar