/* ========================================================================
   DIAG_VISITAS_2  (solo lectura)  -  correr con Query > SQLCMD Mode
   Estados y valores reales de las visitas + quien usa la tabla.
   ======================================================================== */
:OUT C:\Users\Usuario\Desktop\muhle-vct\_diag\DIAG_VISITAS_2.txt
USE [MuhlePROD];
SET NOCOUNT ON;

PRINT '=== 1. ESTADO de las visitas (cantidad, primera y ultima fecha) ===';
SELECT ISNULL(ESTADO,'(null)') AS ESTADO, COUNT(*) AS VISITAS, MIN(FECHA_DESDE) AS DESDE, MAX(FECHA_DESDE) AS HASTA
FROM dbo.VCT_PROYECTOS_VISITAS GROUP BY ESTADO ORDER BY COUNT(*) DESC;
GO
PRINT '=== 2. Modalidad (OBSERVADOR) mas usada ===';
SELECT TOP 15 LTRIM(RTRIM(ISNULL(OBSERVADOR,'(null)'))) AS MODALIDAD, COUNT(*) AS VISITAS
FROM dbo.VCT_PROYECTOS_VISITAS GROUP BY LTRIM(RTRIM(ISNULL(OBSERVADOR,'(null)'))) ORDER BY COUNT(*) DESC;
GO
PRINT '=== 3. INDICADOR_HR, DIAS y horas con hora (no solo fecha) ===';
SELECT ISNULL(INDICADOR_HR,'(null)') AS INDICADOR_HR, COUNT(*) AS VISITAS FROM dbo.VCT_PROYECTOS_VISITAS GROUP BY INDICADOR_HR;
SELECT SUM(CASE WHEN CONVERT(TIME, FECHA_DESDE) <> '00:00' THEN 1 ELSE 0 END) AS CON_HORA,
       SUM(CASE WHEN TOTAL_HORAS_EJECUTADAS > 0 THEN 1 ELSE 0 END) AS CON_HORAS_EJEC,
       AVG(TOTAL_HORAS_EJECUTADAS) AS PROM_HORAS
FROM dbo.VCT_PROYECTOS_VISITAS;
GO
PRINT '=== 4. Visitas de un proyecto en curso de ejemplo (proyecto 978) ===';
SELECT V.ID, V.FECHA_DESDE, V.FECHA_HASTA, V.ESTADO, V.OBSERVADOR, V.LUGAR, V.TOTAL_HORAS_EJECUTADAS,
       VC.ID_CONSULTOR, VC.LIDER, VC.HORAS_PLANIFICADAS, VC.HORAS_EJECUTADAS, P.TOTAL_HORAS_PROYECTADAS, P.TOTAL_HORAS_EJECUTADAS
FROM dbo.VCT_PROYECTOS_VISITAS V
JOIN dbo.VCT_PROYECTOS P ON P.ID = V.ID_PROYECTO
LEFT JOIN dbo.VCT_PROYECTOS_VISITAS_CONSULTORES VC ON VC.ID_VISITA = V.ID
WHERE V.ID_PROYECTO = 978 ORDER BY V.FECHA_DESDE;
GO
PRINT '=== 5. Lineas de VCT_EVENTO_PROCESAR y VCT_VW_PROYECTOS_ACTORES que mencionan visitas ===';
DECLARE @n SYSNAME, @D NVARCHAR(MAX), @p INT, @e INT, @l NVARCHAR(MAX);
DECLARE c CURSOR LOCAL FAST_FORWARD FOR SELECT name FROM (VALUES ('VCT_EVENTO_PROCESAR'),('VCT_VW_PROYECTOS_ACTORES')) x(name);
OPEN c; FETCH NEXT FROM c INTO @n;
WHILE @@FETCH_STATUS = 0
BEGIN
    PRINT '--- ' + @n;
    SET @D = OBJECT_DEFINITION(OBJECT_ID('dbo.' + @n)); SET @p = 1;
    WHILE @D IS NOT NULL AND @p <= LEN(@D)
    BEGIN
        SET @e = CHARINDEX(NCHAR(10), @D, @p); IF @e = 0 SET @e = LEN(@D) + 1;
        SET @l = SUBSTRING(@D, @p, @e - @p);
        IF @l LIKE '%VISITA%' PRINT LEFT(@l, 300);
        SET @p = @e + 1;
    END;
    FETCH NEXT FROM c INTO @n;
END;
CLOSE c; DEALLOCATE c;
GO
