/* ========================================================================
   PROYECTO_ALTA_BORRAR_PRUEBA  (BORRA DATOS: solo proyectos de prueba)
   Borra TODOS los proyectos cuyo nombre empieza con "PRUEBA ALTA" y termina
   en "- borrar", con sus servicios, normas, equipo y gestiones.
   Primero lista lo que va a borrar.
   ======================================================================== */
USE [MuhlePROD];
GO
SET NOCOUNT ON;
SET XACT_ABORT ON;

DECLARE @P TABLE (ID INT PRIMARY KEY);
INSERT INTO @P (ID)
SELECT ID FROM dbo.VCT_PROYECTOS
WHERE NOMBRE LIKE 'PRUEBA ALTA%- borrar';

SELECT P.ID, P.CODIGO, P.NOMBRE, P.FECHA_ALTA, P.USUARIO_ALTA
FROM dbo.VCT_PROYECTOS P INNER JOIN @P X ON X.ID = P.ID;

IF NOT EXISTS (SELECT 1 FROM @P)
BEGIN
    PRINT 'No hay proyectos de prueba para borrar.';
    RETURN;
END;

BEGIN TRANSACTION;
    DELETE GP FROM dbo.VCT_GESTIONES_PARTICIPANTES GP INNER JOIN dbo.VCT_GESTIONES G ON G.ID = GP.ID_GESTION INNER JOIN @P X ON X.ID = G.ID_PROYECTO;
    DELETE GH FROM dbo.VCT_GESTIONES_HISTORIAL GH INNER JOIN dbo.VCT_GESTIONES G ON G.ID = GH.ID_GESTION INNER JOIN @P X ON X.ID = G.ID_PROYECTO;
    DELETE GC FROM dbo.VCT_GESTIONES_COMENTARIOS GC INNER JOIN dbo.VCT_GESTIONES G ON G.ID = GC.ID_GESTION INNER JOIN @P X ON X.ID = G.ID_PROYECTO;
    DELETE GR FROM dbo.VCT_GESTIONES_RELACIONES GR INNER JOIN dbo.VCT_GESTIONES G ON G.ID = GR.ID_GESTION INNER JOIN @P X ON X.ID = G.ID_PROYECTO;
    DELETE G FROM dbo.VCT_GESTIONES G INNER JOIN @P X ON X.ID = G.ID_PROYECTO;
    DELETE E FROM dbo.VCT_PROYECTOS_EQUIPO E INNER JOIN @P X ON X.ID = E.ID_PROYECTO;
    DELETE N FROM dbo.VCT_PROYECTOS_NORMAS N INNER JOIN @P X ON X.ID = N.ID_PROYECTO;
    DELETE S FROM dbo.VCT_PROYECTOS_SERVICIOS S INNER JOIN @P X ON X.ID = S.ID_PROYECTO;
    DELETE P FROM dbo.VCT_PROYECTOS P INNER JOIN @P X ON X.ID = P.ID;
COMMIT TRANSACTION;

PRINT 'OK: proyectos de prueba borrados.';
GO
