USE [MuhlePROD]
GO

-- Columnas de las 4 entidades que necesito para el SP de envio
SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME IN ('VCT_CONSULTORES','VCT_PROYECTOS','VCT_EMPLEADOS','VCT_CLIENTES','VCT_EMAILS','VCT_PRM_EMAIL_TEMPLATES')
ORDER BY TABLE_NAME,
         CASE WHEN COLUMN_NAME LIKE 'ID%' THEN 0 ELSE 1 END,
         ORDINAL_POSITION;

-- Como se linkea VCT_EMAILS a las otras entidades (algunas filas de ejemplo)
SELECT TOP 20 * FROM dbo.VCT_EMAILS;
