/* Compara el calculo NUEVO (por conjuntos) contra las funciones ORIGINALES
   para DIAS_AUDITOR y HS_EJEC sobre todos los servicios de auditoria del rango.
   Solo lectura (usa tablas temporales). Tarda ~15 s por la parte vieja.
   Esperado: mismatch_dias = 0 y mismatch_hs = 0. */
USE [MuhlePROD]
GO
SET NOCOUNT ON;
DECLARE @VPA_FDESDE_DATE DATETIME='2024-01-01', @VPA_FHASTA_DATE DATETIME='2026-10-31';

IF OBJECT_ID('tempdb..#AUDI_S')   IS NOT NULL DROP TABLE #AUDI_S;
IF OBJECT_ID('tempdb..#AUDI_AG')  IS NOT NULL DROP TABLE #AUDI_AG;
IF OBJECT_ID('tempdb..#AUDI_CNT') IS NOT NULL DROP TABLE #AUDI_CNT;
IF OBJECT_ID('tempdb..#AUDI_X')   IS NOT NULL DROP TABLE #AUDI_X;

DECLARE @t DATETIME2 = SYSDATETIME();

CREATE TABLE #AUDI_S (IDPS INT NOT NULL PRIMARY KEY, ID_CLIENTE INT, ID_PROYECTO INT, ID_TIPO INT);
INSERT INTO #AUDI_S (IDPS,ID_CLIENTE,ID_PROYECTO,ID_TIPO)
SELECT DISTINCT PS.ID_PROYECTO_SERVICIO,P.ID_CLIENTE,PS.ID_PROYECTO,PS.ID_TIPO_SERVICIO
FROM dbo.LK_PROYECTO P WITH(NOLOCK)
    INNER JOIN dbo.LK_PROYECTO_SERVICIO PS ON P.ID_PROYECTO=PS.ID_PROYECTO
WHERE PS.FECHA_INICIO_REAL>=@VPA_FDESDE_DATE AND PS.FECHA_INICIO_REAL<=@VPA_FHASTA_DATE AND PS.ID_TIPO_SERVICIO='2';

CREATE TABLE #AUDI_AG (ID_AGENDA INT NOT NULL PRIMARY KEY, IDPS INT NOT NULL, DIAS INT NULL, ES_SERV BIT NOT NULL);
INSERT INTO #AUDI_AG (ID_AGENDA,IDPS,DIAS,ES_SERV)
SELECT A.ID_AGENDA,S.IDPS,CONVERT(INT,A.DIAS),
       CASE WHEN A.ID_CLIENTE=S.ID_CLIENTE AND A.ID_PROYECTO=S.ID_PROYECTO AND A.ID_SERVICIO=S.ID_TIPO THEN 1 ELSE 0 END
FROM #AUDI_S S INNER JOIN dbo.LK_AGENDA A ON A.PROYECTO_SERV_ID=S.IDPS;

CREATE TABLE #AUDI_CNT (ID_AGENDA INT NOT NULL PRIMARY KEY, CNT INT NOT NULL);
INSERT INTO #AUDI_CNT (ID_AGENDA,CNT)
SELECT G.ID_AGENDA,COUNT(DISTINCT AE.ID_EMPLEADO)
FROM #AUDI_AG G INNER JOIN dbo.LK_AGENDA_EMPLEADO AE WITH(NOLOCK) ON AE.HOLIDAYTEXT=CONVERT(VARCHAR,G.ID_AGENDA)
WHERE G.ES_SERV=1 GROUP BY G.ID_AGENDA;

CREATE TABLE #AUDI_X (IDPS INT NOT NULL PRIMARY KEY, DIAS DECIMAL(10,2) NULL, HS DECIMAL(18,2) NOT NULL);
INSERT INTO #AUDI_X (IDPS,DIAS,HS)
SELECT S.IDPS, CASE WHEN D.IDPS IS NULL THEN 0 ELSE D.DIAS END, CONVERT(DECIMAL(18,2),ISNULL(H.HS,0))
FROM #AUDI_S S
    LEFT JOIN (SELECT G.IDPS, CASE WHEN COUNT(*)>COUNT(G.DIAS) THEN NULL ELSE SUM(G.DIAS*ISNULL(C.CNT,0)) END AS DIAS
               FROM #AUDI_AG G LEFT JOIN #AUDI_CNT C ON C.ID_AGENDA=G.ID_AGENDA WHERE G.ES_SERV=1 GROUP BY G.IDPS) D ON D.IDPS=S.IDPS
    LEFT JOIN (SELECT G.IDPS,SUM(AE.HORAS) AS HS
               FROM #AUDI_AG G INNER JOIN dbo.LK_AGENDA_EMPLEADO AE WITH(NOLOCK) ON AE.HOLIDAYTEXT=CONVERT(VARCHAR,G.ID_AGENDA) AND AE.TIPO='A'
               GROUP BY G.IDPS) H ON H.IDPS=S.IDPS;

SELECT 'calculo nuevo (ms)' AS que, DATEDIFF(MILLISECOND,@t,SYSDATETIME()) AS valor, (SELECT COUNT(*) FROM #AUDI_X) AS servicios;

/* Comparacion con las funciones originales (lento a proposito) */
SELECT
    SUM(CASE WHEN ISNULL(CONVERT(DECIMAL(10,2),O.DIAS_F),-1) <> ISNULL(X.DIAS,-1) THEN 1 ELSE 0 END) AS mismatch_dias,
    SUM(CASE WHEN ISNULL(CONVERT(DECIMAL(18,2),O.HS_F),-1)   <> X.HS              THEN 1 ELSE 0 END) AS mismatch_hs,
    COUNT(*) AS total
FROM #AUDI_S S
    INNER JOIN #AUDI_X X ON X.IDPS=S.IDPS
    CROSS APPLY (SELECT dbo.FN_GET_SERVICIO_DIAS(S.ID_CLIENTE,S.ID_PROYECTO,S.ID_TIPO,S.IDPS) AS DIAS_F,
                        dbo.FN_GET_TOTAL_HS_EJECUTADAS('PS',NULL,NULL,S.IDPS) AS HS_F) O;

/* Detalle de diferencias (vacio si todo coincide) */
SELECT TOP 20 S.IDPS, O.DIAS_F, X.DIAS AS DIAS_NUEVO, O.HS_F, X.HS AS HS_NUEVO
FROM #AUDI_S S
    INNER JOIN #AUDI_X X ON X.IDPS=S.IDPS
    CROSS APPLY (SELECT dbo.FN_GET_SERVICIO_DIAS(S.ID_CLIENTE,S.ID_PROYECTO,S.ID_TIPO,S.IDPS) AS DIAS_F,
                        dbo.FN_GET_TOTAL_HS_EJECUTADAS('PS',NULL,NULL,S.IDPS) AS HS_F) O
WHERE ISNULL(CONVERT(DECIMAL(10,2),O.DIAS_F),-1) <> ISNULL(X.DIAS,-1)
   OR ISNULL(CONVERT(DECIMAL(18,2),O.HS_F),-1) <> X.HS;
GO
