USE [MuhlePROD]
GO

CREATE OR ALTER PROCEDURE [dbo].[VCT_MAIN_EMAIL_TEMPLATE_GET]
    @CODIGO VARCHAR(50)
AS
BEGIN
    SET NOCOUNT ON;

    SELECT
        T.ID,
        T.CODIGO,
        T.DESCRIPCION,
        T.TIPO_ENVIO,
        T.DESTINO_TIPO,
        T.DESTINO_LIBRE,
        T.CC_TIPO,
        T.CC_LIBRE,
        T.ESTADO,
        T.ASUNTO,
        T.HTML_CONTENIDO
    FROM dbo.VCT_PRM_EMAIL_TEMPLATES T WITH(NOLOCK)
    WHERE UPPER(LTRIM(RTRIM(T.CODIGO))) COLLATE DATABASE_DEFAULT =
          UPPER(LTRIM(RTRIM(@CODIGO))) COLLATE DATABASE_DEFAULT;
END
GO
