CREATE VIEW [dbo].[VW_SYS_HISTORY_PROCESS] AS
-- CONSULTA UTILIZADA PARA VER LA HISTORIA DE LOS PROCESOS.
SELECT	TOP 100 PERCENT
	CT.CUST_TYPE_CODE,
	DSSPJ.ID_CUSTOMER,
	DSSPJ.PKEY_PHYSICAL_JOB,
	ISNULL(N.NOTE_COUNT, 0) AS NOTESCOUNT,
	ISNULL(D.ATTACH_COUNT, 0) AS ATTACHEDCOUNT,
	DSSPJ.JOB_SEQ,
	JT.JOB_TYPE_DESC,
	DSSPJ.JOB_START_DATE_TIME,
	DSSPJ.JOB_STATE_DATE_TIME,
	DSSPJ.JOB_MAX_END_DATE,
	DSSPJ.JOB_STATE_CODE,
	(CASE
	WHEN DSSPJ.JOB_STATE_CODE = 'OPENED' THEN (CASE WHEN GETDATE() <= DSSPJ.JOB_MAX_END_DATE THEN 'OPENED' ELSE 'OPENEDEXPIRED' END)
	WHEN DSSPJ.JOB_STATE_CODE = 'CLOSED' THEN (CASE WHEN DSSPJ.JOB_STATE_DATE_TIME <= DSSPJ.JOB_MAX_END_DATE THEN 'CLOSED' ELSE 'CLOSEDEXPIRED' END)
	WHEN DSSPJ.JOB_STATE_CODE = 'NOTWORKED' THEN (CASE WHEN GETDATE() <= DSSPJ.JOB_MAX_END_DATE THEN 'NOTWORKED' ELSE 'NOTWORKEDEXPIRED' END)
	WHEN DSSPJ.JOB_STATE_CODE = 'PAUSED' THEN (CASE WHEN GETDATE() <= DSSPJ.JOB_MAX_END_DATE THEN 'PAUSED' ELSE 'PAUSEDEXPIRED' END)
	END) AS JOB_STATE_VALIDATION,
--	DSSPJ.ATT_STATE_CODE AS PJATTSC,
--	DSSATT.ATT_STATE_CODE,
	ISNULL(JRT.JOB_RESULT_DESC, DSSPJ.JOB_RESULT_CODE) AS JOB_RESULT_DESC,
	ISNULL(A.USER_NAME, 'SIN ASIGNAR') AS LAST_USER,
	ISNULL(ORG.UNIT_DESCRIPTION, 'SIN ASIGNAR') AS LAST_UNIT,
	ISNULL(PL.PHYSICAL_LIST_DESC, 'NO PERTENECE A UNA LISTA') AS PHYSICAL_LIST_DESC,
	ISNULL(CDRC.CAT_DATA_DESC, 'SIN MOTIVO') AS JOB_REASON_DESC,
	ISNULL(CDSRC.CAT_DATA_DESC, 'SIN SUBMOTIVO') AS JOB_SUBREASON_DESC
FROM	CUSTOMER_TYPE CT
	INNER JOIN JOB_TYPE JT ON (CT.CUST_TYPE_CODE = JT.CUST_TYPE_CODE)
	INNER JOIN DSS_TBPHYSICAL_JOB DSSPJ ON (JT.JOB_TYPE_CODE = DSSPJ.ID_JOB_TYPE)
--	INNER JOIN DSS_TBATTENDED_CUSTOMER DSSATT ON (DSSPJ.PKEY_PHYSICAL_JOB = DSSATT.PKEY_PHYSICAL_JOB)
	LEFT OUTER JOIN JOB_RESULT_TYPE JRT ON (DSSPJ.ID_JOB_TYPE = JRT.JOB_TYPE_CODE AND DSSPJ.JOB_RESULT_CODE = JRT.JOB_RESULT_CODE)
	LEFT OUTER JOIN VW_SYS_UNIDAD ORG ON (DSSPJ.ID_GROUP = ORG.UNIT_CODE)
	LEFT OUTER JOIN VW_SYS_USUARIO A ON (DSSPJ.ID_AGENT = A.USER_ID)
	LEFT OUTER JOIN PHYSICAL_LIST PL ON (DSSPJ.ID_CAMPAIGN = PL.PKEY)
	LEFT OUTER JOIN VW_SYS_PROCESS_NOTE_QTY N ON (N.PAR_KEY = DSSPJ.PKEY_PHYSICAL_JOB)
	LEFT OUTER JOIN VW_SYS_PROCESS_ATTACH_QTY D ON (D.PAR_KEY = DSSPJ.PKEY_PHYSICAL_JOB)
	LEFT OUTER JOIN VW_SYS_PROCESS_REASONS CDRC ON (DSSPJ.ID_JOB_TYPE = CDRC.JOB_TYPE_CODE AND DSSPJ.JOB_REASON_CODE = CDRC.CAT_DATA_CODE)
	LEFT OUTER JOIN VW_SYS_PROCESS_SUBREASONS CDSRC ON (DSSPJ.ID_JOB_TYPE = CDSRC.JOB_TYPE_CODE AND DSSPJ.JOB_SUBREASON_CODE = CDSRC.CAT_DATA_CODE AND CDRC.PKEY = CDSRC.PARENT_CAT_DATA_PKEY)
WHERE	(CT.HISTORY_JOB_CODE <> JT.JOB_TYPE_CODE)
--	AND EXISTS (
--	SELECT	1
--	FROM	DSS_TBATTENDED_CUSTOMER DSSATT2
--	WHERE	(DSSPJ.PKEY_PHYSICAL_JOB = DSSATT2.PKEY_PHYSICAL_JOB)
--	GROUP BY DSSATT2.PKEY_PHYSICAL_JOB
--	HAVING	DSSATT.TS_BEGIN = MAX(DSSATT2.TS_BEGIN))
ORDER BY DSSPJ.JOB_STATE_DATE_TIME ASC,
	DSSPJ.PKEY_PHYSICAL_JOB ASC
 
