CREATE VIEW [dbo].[VW_SYS_HISTORY_ACTIVITY] AS
-- CONSULTA UTILIZADA PARA VER LA HISTORIA DE LAS ACTIVIDADES DE CADA PROCESO.
SELECT	TOP 100 PERCENT
	DSSATT.PKEY_PHYSICAL_JOB,
	DSSATT.PKEY_ATTENDED_CUSTOMER,
	CT.CALL_TYPE_DESC,
	DSSATT.TS_BEGIN AS ATT_START_DATE_TIME,
	DSSATT.ATT_STATE_DATE_TIME,
	DSSATT.ATT_MAX_END_DATE,
	DSSATT.ATT_STATE_CODE,
	ISNULL(CRT.CALL_RESULT_DESC, DSSATT.ATT_RESULT_CODE) AS CALL_RESULT_DESC,
	ISNULL(A.USER_NAME, 'SIN ASIGNAR') AS LAST_USER,
	ISNULL(ORG.UNIT_DESCRIPTION, 'SIN ASIGNAR') AS LAST_UNIT,
	DSSATT.COMMENTA
FROM	DSS_TBATTENDED_CUSTOMER DSSATT
	INNER JOIN CALL_TYPE CT ON (DSSATT.ID_CALL_TYPE = CT.CALL_TYPE_CODE)
	LEFT OUTER JOIN VW_SYS_UNIDAD ORG ON (DSSATT.ID_GROUP = ORG.UNIT_CODE)
	LEFT OUTER JOIN VW_SYS_USUARIO A ON (DSSATT.ID_AGENT = A.USER_ID)
	LEFT OUTER JOIN CALL_RESULT_TYPE CRT ON (DSSATT.ID_CALL_TYPE = CRT.CALL_TYPE_CODE AND DSSATT.ATT_RESULT_CODE = CRT.CALL_RESULT_CODE)
ORDER BY DSSATT.ATT_STATE_DATE_TIME ASC,
	DSSATT.PKEY_ATTENDED_CUSTOMER ASC
 
