 
 
-- INCORPORACIÓN DE TABLAS DEL MODELO COLLECTION Y DE TABLAS ADICIONALES DE ENGAGE.
-- EN CASO DE QUE LAS TABLAS EXISTAN, VERIFICAR QUE TENGAN LOS CAMPOS MOSTRADOS EN ESTE SCRIPT.
CREATE VIEW [dbo].[VW_SYS_LISTAS_INTERNAS] AS
 
-- MUESTRA LAS LISTAS INTERNAS.
-- ORDENADAS POR: SI ES EXLUYENTE, PRIORIDAD DEL TIPO DE LISTA Y PRIORIDAD DE LA LISTA.
SELECT	TOP 100 PERCENT
	LT.LIST_CAT_TYPE,
	LT.EXCL_IDR,
	LT.PRIORITY_VALUE,
	PL.PKEY AS PHYSICAL_LIST_PKEY,
	CONVERT(VARCHAR(4000), LTRIM(RTRIM(REPLACE(PL.QUERY_DESC, '#', CHAR(39))))) AS QUERY_DESC,
	PL.START_DATE,
	PL.STATE_CODE,
	PL.STATE_DATE,
	PL.PHYSICAL_LIST_ASSIGNED_IDR,
	PL.PHYSICAL_LIST_DESC,
	PL.GROUP_CODE,
	PL.LOAD_DATE,
	PL.ATT_GROUP_CODE,
	PL.PRIORITY,
	PL.FIRST_DATE,
	PL.LAST_DATE,
	PL.LIST_TYPE_NAME,
	PL.JOB_TYPE_CODE,
	PL.MEDIA_TYPE,
	PL.PHYSICAL_LIST_NUMBER,
	PL.CALL_TYPE_CODE,
	PL.PAR_KEY AS CAMPAIGN_GROUP_PKEY,
	PL.LIST_TYPE_PKEY
FROM	PHYSICAL_LIST PL
	INNER JOIN LIST_TYPE LT ON (PL.LIST_TYPE_PKEY = LT.PKEY)
WHERE	(LT.LIST_CAT_TYPE = 'Interna')
	AND (LT.REGENERAR = '1')
	AND (PL.STATE_CODE = 'INICIADA')
	AND (PL.FIRST_DATE <= GETDATE() AND PL.LAST_DATE >= GETDATE())
ORDER BY LT.EXCL_IDR DESC,
	LT.PRIORITY_VALUE ASC,
	PL.PRIORITY ASC
 
