CREATE VIEW [dbo].[VW_SYS_PROCESOS_PEND_LISTAS] AS
-- LISTA LA CANTIDAD DE PROCESOS DE LISTAS CON UNA ACTIVIDAD ABIERTA QUE ESTÁN PENDIENTES PARA CADA CLIENTE.
SELECT	PJ.PKEY_CUSTOMER,
	COUNT(1) AS PENDING_COUNT
FROM	ATTENDED_CUSTOMER AC
	INNER JOIN CALL_TYPE CT ON (AC.CALL_TYPE_CODE = CT.CALL_TYPE_CODE)
	INNER JOIN PHYSICAL_JOB PJ ON (AC.PKEY_JOB = PJ.PKEY)
	INNER JOIN PHYSICAL_LIST PL ON (AC.PKEY_CAMPAIGN = PL.PKEY)
	INNER JOIN JOB_TYPE JT ON (PJ.JOB_TYPE_CODE = JT.JOB_TYPE_CODE)
	INNER JOIN CUSTOMER_TYPE CU ON (JT.CUST_TYPE_CODE = CU.CUST_TYPE_CODE)
WHERE	(AC.ATT_STATE_CODE = 'Abierto' OR AC.ATT_STATE_CODE = 'NOTWORKED')
	AND (JT.JOB_TYPE_CODE <> CU.HISTORY_JOB_CODE)
	AND (CT.CALL_READY_IDR = '1')
	AND (CT.MEDIA_TYPE = 'AGENT')
	AND (PL.LAST_DATE >= GETDATE())
	AND (PL.STATE_CODE = 'INICIADA' OR PL.MOSTRAR_EN_BUSQUEDA = 0)
GROUP BY PJ.PKEY_CUSTOMER
 
