 
CREATE VIEW [dbo].[EVI_OBJECT_DEPENDENCIES] AS
-- MUESTRA LAS DEPENDENCIAS DE LOS OBJETOS ACCESIBLES DE LA BASE DE DATOS LOCAL PARA EL USUARIO ACTUAL.
SELECT	TOP 100 PERCENT
	CONVERT(VARCHAR(30), O1.OBJECT_CATALOG) AS OBJECT_CATALOG,
	CONVERT(VARCHAR(30), O1.OBJECT_SCHEMA) AS OBJECT_SCHEMA,
        CONVERT(VARCHAR(30), O1.OBJECT_TYPE) AS OBJECT_TYPE,
        CONVERT(VARCHAR(30), O1.OBJECT_NAME) AS OBJECT_NAME,
	CONVERT(VARCHAR(30), ISNULL(O2.OBJECT_CATALOG, DB_NAME())) AS REFERENCED_CATALOG,
	CONVERT(VARCHAR(30), ISNULL(O2.OBJECT_SCHEMA, USER_NAME())) AS REFERENCED_SCHEMA,
        CONVERT(VARCHAR(30), ISNULL(O2.OBJECT_TYPE, 'SYSTEM OBJECT')) AS REFERENCED_TYPE,
	CONVERT(VARCHAR(30), ISNULL(O2.OBJECT_NAME, OBJECT_NAME(SD.DEPID))) AS REFERENCED_NAME
FROM	EVI_OBJECTS O1
	INNER JOIN
	(SELECT	SD.ID,
		SD.DEPID
	FROM	DBO.SYSDEPENDS SD
	WHERE	NOT (SD.DEPID = 0)
	GROUP BY SD.ID,
		SD.DEPID
	) SD ON (O1.OBJECT_NAME = OBJECT_NAME(SD.ID))
	LEFT OUTER JOIN EVI_OBJECTS O2 ON (OBJECT_NAME(SD.DEPID) = O2.OBJECT_NAME)
ORDER BY 1 ASC, 2 ASC, 3 ASC, 4 ASC, 5 ASC, 6 ASC, 7 ASC, 8 ASC
 
