 
CREATE VIEW [dbo].[EVI_PROCEDURES] AS
-- MUESTRA LOS PROCEDIMIENTOS ACCESIBLES DE LA BASE DE DATOS LOCAL PARA EL USUARIO ACTUAL.
-- DBO.SYSOBJECTS.STATUS < 0, INDICA QUE EL OBJETO ES DE SISTEMA O, SI ES DE USUARIO, ESTÁ CORRUPTO.
-- PERMISSIONS(DBO.SYSOBJECTS.ID) = 0, INDICA QUE EL OBJETO NO ES ACCESIBLE PARA EL USUARIO ACTUAL.
SELECT	TOP 100 PERCENT
	CONVERT(VARCHAR(30), DB_NAME()) AS PROCEDURE_CATALOG,
	CONVERT(VARCHAR(30), USER_NAME(O.UID)) AS PROCEDURE_SCHEMA,
	CONVERT(VARCHAR(30), CASE O.XTYPE
	WHEN 'P' THEN 'PROCEDURE' -- 'STORED PROCEDURE'
	WHEN 'FN' THEN 'FUNCTION' -- 'SCALAR FUNCTION'
	WHEN 'IF' THEN 'FUNCTION' -- 'INLINED TABLE-FUNCTION'
	WHEN 'RF' THEN 'PROCEDURE' -- 'REPLICATION FILTER STORED PROCEDURE'
	WHEN 'TF' THEN 'FUNCTION' -- 'TABLE FUNCTION'
	WHEN 'X' THEN 'PROCEDURE' -- 'EXTENDED STORED PROCEDURE'
        -- ELSE 'PACKAGE'
	END) AS PROCEDURE_TYPE,
	CONVERT(VARCHAR(30), O.NAME) AS PROCEDURE_NAME,
	CONVERT(VARCHAR(30), O.NAME) AS SUBPROCEDURE_NAME
FROM	DBO.SYSOBJECTS O
WHERE	(O.XTYPE IN ('P', 'FN', 'IF', 'RF', 'TF', 'X'))
	AND (UPPER(O.NAME) NOT IN ('SP_ALTERDIAGRAM', 'SP_CREATEDIAGRAM', 'SP_DROPDIAGRAM', 'SP_HELPDIAGRAMDEFINITION', 'SP_HELPDIAGRAMS', 'SP_RENAMEDIAGRAM', 'SP_UPGRADDIAGRAMS', 'FN_DIAGRAMOBJECTS'))
	AND (O.STATUS >= 0)
--	AND (PERMISSIONS(O.ID) <> 0)
ORDER BY 1 ASC, 2 ASC, 3 ASC, 4 ASC, 5 ASC
 
