 
CREATE VIEW [dbo].[VW_SYS_RPT_MOT_SUBMOT] AS
SELECT	TOP 100 PERCENT
	ISNULL(D.CAT_DATA_CODE, '') AS JOB_REASON_CODE,
	ISNULL(D.CAT_DATA_DESC, '') AS JOB_REASON_DESC,
	ISNULL(E.CAT_DATA_CODE, '') AS JOB_SUBREASON_CODE,
	ISNULL(E.CAT_DATA_DESC, '') AS JOB_SUBREASON_DESC
FROM	(CAT_TYPE Y
	INNER JOIN CAT_DATA D ON Y.PKEY = D.PAR_KEY AND Y.CAT_TYPE_CODE LIKE 'MOTIVO%'
	)
	INNER JOIN
	(CAT_TYPE Z
	INNER JOIN CAT_DATA E ON Z.PKEY = E.PAR_KEY AND Z.CAT_TYPE_CODE LIKE 'SUBMOTIVO%'
	) ON D.CAT_DATA_CODE = E.PARENT_CAT_DATA_CODE
GROUP BY ISNULL(D.CAT_DATA_CODE, ''),
	ISNULL(D.CAT_DATA_DESC, ''),
	ISNULL(E.CAT_DATA_CODE, ''),
	ISNULL(E.CAT_DATA_DESC, '')
ORDER BY ISNULL(D.CAT_DATA_CODE, '') ASC,
	ISNULL(D.CAT_DATA_DESC, '') ASC,
	ISNULL(E.CAT_DATA_CODE, '') ASC,
	ISNULL(E.CAT_DATA_DESC, '') ASC
 
