 
 
 
 
 
 
 
CREATE VIEW [dbo].[VW_COTIZACIONES] AS
 
SELECT	DISTINCT
		CO.ID_COTIZACION AS CAT_DATA_CODE, 
		CO.NRO_COTIZACION AS CAT_DATA_DESC, 
		CO.ID_COTIZACION AS PKEY, 
		CLI.ID_CLIENTE AS PARENT_CAT_DATA_CODE, 
		CLI.ID_CLIENTE AS PARENT_CAT_DATA_PKEY
FROM    LK_COTIZACIONES CO 
		INNER JOIN LK_CLIENTES CLI ON CO.ID_CLIENTE = CLI.ID_CLIENTE
		--INNER JOIN LK_PROYECTO P ON CO.ID_COTIZACION = P.ID_COTIZACION
WHERE	CO.ESTADO_COTIZACION = 'CONFIRMADO'
--AND		CO.ID_COTIZACION NOT IN (SELECT ID_COTIZACION FROM LK_PROYECTO WHERE ID_COTIZACION <> 0)
 
 
