 
 
CREATE VIEW [dbo].[EVI_TABLE_COLUMNS] AS
-- MUESTRA LAS COLUMNAS DE LAS TABLAS ACCESIBLES DE LA BASE DE DATOS LOCAL PARA EL USUARIO ACTUAL.
-- PERMISSIONS(OBJECT_ID(T.TABLE_NAME), COL.NAME) = 0, INDICA QUE LA COLUMNA NO ES ACCESIBLE PARA EL USUARIO ACTUAL.
SELECT     TOP (100) PERCENT T.TABLE_CATALOG, T.TABLE_SCHEMA, T.TABLE_NAME, CONVERT(NUMERIC(15), C.ORDINAL_POSITION) AS ORDINAL_POSITION, 
                      CONVERT(VARCHAR(30), C.COLUMN_NAME) AS COLUMN_NAME, CONVERT(VARCHAR(4000), C.COLUMN_DEFAULT) AS COLUMN_DEFAULT, CONVERT(VARCHAR(1), 
                      CASE C.IS_NULLABLE WHEN 'YES' THEN 'Y' ELSE 'N' END) AS IS_NULLABLE, CONVERT(VARCHAR(30), UPPER(C.DATA_TYPE)) AS DATA_TYPE_NAME, 
                      CONVERT(NUMERIC(15), COL.length) AS BYTE_LENGTH, CONVERT(NUMERIC(15), ISNULL(C.CHARACTER_MAXIMUM_LENGTH, 0)) AS CHAR_COL_DECL_LENGTH, 
                      CONVERT(NUMERIC(15), NULLIF (COL.xprec, 0)) AS NUMERIC_PRECISION, CONVERT(NUMERIC(15), COL.scale) AS NUMERIC_SCALE, CONVERT(VARCHAR(30), 
                      C.CHARACTER_SET_NAME) AS CHARACTER_SET_NAME, CONVERT(VARCHAR(256), COL.collation) AS COLLATION_NAME
FROM         dbo.EVI_TABLES AS T INNER JOIN
                      INFORMATION_SCHEMA.COLUMNS AS C ON T.TABLE_NAME = C.TABLE_NAME INNER JOIN
                      sys.syscolumns AS COL ON OBJECT_ID(C.TABLE_NAME) = COL.id AND C.COLUMN_NAME = COL.name
ORDER BY T.TABLE_CATALOG, T.TABLE_SCHEMA, T.TABLE_NAME, ORDINAL_POSITION
 
