 
 
 
 
 
CREATE VIEW [dbo].[VW_TIPOS_VIATICOS]
AS
 
SELECT	CAT_DATA_CODE AS CAT_DATA_CODE, 
		CAT_DATA_DESC AS CAT_DATA_DESC, 
        CAT_DATA_CODE AS PKEY, 
		'' AS PARENT_CAT_DATA_CODE, 
		'' AS PARENT_CAT_DATA_PKEY
FROM	CAT_DATA 
WHERE	PAR_KEY = (SELECT PKEY FROM CAT_TYPE WHERE CAT_TYPE_CODE = 'TIPO_PROVEEDOR')
             
 
