CREATE VIEW [dbo].[VW_SYS_CAT_TYPE] AS
-- UNE LAS CATEGORÍAS EXTERNAS CON LAS INTERNAS.
SELECT	CTE.PKEY,
	NULLIF(CTE.PAR_KEY, '') AS PAR_KEY,
	CTE.CAT_TYPE_CODE,
	CTE.CAT_TYPE_CODE AS CAT_TYPE_DESC,
	NULL AS CAT_TYPE_GROUP, 
	CASE WHEN NULLIF(CTE.PAR_KEY, '') IS NULL THEN 1 ELSE 2 END AS CAT_LEVEL
FROM	CAT_TYPE_EXT CTE
UNION
SELECT	CAT.PKEY,
	NULLIF(CAT.PAR_KEY, '') AS PAR_KEY,
	CAT.CAT_TYPE_CODE,
	CAT.CAT_TYPE_DESC,
	NULLIF(CAT.CAT_TYPE_GROUP, '') AS CAT_TYPE_GROUP,
	CAT.CAT_LEVEL
FROM	CAT_TYPE CAT
 
