CREATE VIEW [dbo].[VW_SYS_QUERY_INBOX_COUNT] AS
-- VISTA DE CONTEO PARA LA INBOX.
SELECT	PJ.JOB_STATE_CODE,
	PJ.JOB_STATE_DATE,
	AC.PROGRAMMED_IDR,
	AC.PROGRAMMED_DATE_TIME,
	AC.USER_ID,
	UN1.UNIT_CODE AS GROUP_CODE,
	AC.ATT_STATE_CODE,
	AC.PKEY_CAMPAIGN,
	CL.RESTRICTION_TYPE,
	PJ.CAMPAIGN_IDR AS ACTION_CAMPAIGN,
	CT.CUST_TYPE_CODE,
	CU.PKEY AS CUSTOMER_PKEY
FROM	CUSTOMER_TYPE CT
	INNER JOIN JOB_TYPE JT ON (CT.CUST_TYPE_CODE = JT.CUST_TYPE_CODE AND JT.JOB_READY_IDR = '1')
	INNER JOIN PHYSICAL_JOB PJ ON (JT.JOB_TYPE_CODE = PJ.JOB_TYPE_CODE)
	INNER JOIN CUSTOMER CU ON (PJ.PKEY_CUSTOMER = CU.PKEY)
	INNER JOIN (CALL_TYPE CL INNER JOIN ATTENDED_CUSTOMER AC ON CL.CALL_TYPE_CODE = AC.CALL_TYPE_CODE) ON (JT.PKEY = CL.PAR_KEY AND PJ.PKEY = AC.PKEY_JOB)
	INNER JOIN VW_SYS_UNIDAD UN1 ON (AC.GROUP_CODE = UN1.UNIT_CODE)
WHERE	(PJ.JOB_STATE_CODE = 'NOTWORKED' OR PJ.JOB_STATE_CODE = 'OPENED')
	AND (JT.JOB_TYPE_CODE NOT LIKE 'AUTOEXEC%' AND JT.JOB_TYPE_CODE NOT LIKE 'HOME%' AND JT.JOB_TYPE_CODE NOT LIKE 'SUPER%')
	AND NOT EXISTS (SELECT 1 FROM CUSTOMER_TYPE CT1 WHERE (CT1.HISTORY_JOB_CODE = JT.JOB_TYPE_CODE))
 
