 
CREATE VIEW [dbo].[EVI_OBJECT_SOURCES] AS
-- MUESTRA EL CÓDIDO FUENTE DE LOS OBJETOS ACCESIBLES DE LA BASE DE DATOS LOCAL PARA EL USUARIO ACTUAL.
SELECT	TOP 100 PERCENT
	CONVERT(VARCHAR(30), O.OBJECT_CATALOG) AS OBJECT_CATALOG,
	CONVERT(VARCHAR(30), O.OBJECT_SCHEMA) AS OBJECT_SCHEMA,
        CONVERT(VARCHAR(30), O.OBJECT_TYPE) AS OBJECT_TYPE,
        CONVERT(VARCHAR(30), O.OBJECT_NAME) AS OBJECT_NAME,
	CONVERT(NUMERIC(15), SC.COLID) AS ORDINAL_POSITION,
--	CONVERT(VARCHAR(4000), CASE WHEN O.OBJECT_TYPE IN ('CHECK', 'DEFAULT') THEN LEFT(RIGHT(SC.TEXT, LEN(SC.TEXT) - 1), LEN(SC.TEXT) - 2) ELSE SC.TEXT END) AS OBJECT_SOURCE
	CONVERT(VARCHAR(4000), SC.TEXT) AS OBJECT_SOURCE
FROM	EVI_OBJECTS O
	INNER JOIN DBO.SYSCOMMENTS SC ON (O.OBJECT_NAME = OBJECT_NAME(SC.ID))
ORDER BY 1 ASC, 2 ASC, 3 ASC, 4 ASC, 5 ASC
 
