 
CREATE VIEW [dbo].[EVI_TABLE_TRIGGERS] AS
-- MUESTRA LOS DISPARADORES DE TABLAS ACCESIBLES DE LA BASE DE DATOS LOCAL PARA EL USUARIO ACTUAL.
-- DBO.SYSOBJECTS.STATUS < 0, INDICA QUE EL OBJETO ES DE SISTEMA O, SI ES DE USUARIO, ESTÁ CORRUPTO.
-- PERMISSIONS(DBO.SYSOBJECTS.ID) = 0, INDICA QUE EL OBJETO NO ES ACCESIBLE PARA EL USUARIO ACTUAL.
SELECT	TOP 100 PERCENT
	T.TABLE_CATALOG,
	T.TABLE_SCHEMA,
	T.TABLE_NAME,
	CONVERT(VARCHAR(30), CASE
	WHEN OBJECTPROPERTY(O.ID, 'EXECISINSTEADOFTRIGGER') = 1 THEN 'INSTEAD OF'
	WHEN OBJECTPROPERTY(O.ID, 'EXECISAFTERTRIGGER') = 1 THEN 'AFTER'
	ELSE 'BEFORE'
	END) AS TRIGGER_TYPE,
	CONVERT(VARCHAR(30), O.NAME) AS TRIGGER_NAME,
	CONVERT(VARCHAR(30), CASE
	WHEN OBJECTPROPERTY(O.ID, 'EXECISINSTEADOFTRIGGER') = 1 THEN 'DELETE'
	WHEN OBJECTPROPERTY(O.ID, 'EXECISINSERTTRIGGER') = 1 THEN 'INSERT'
	WHEN OBJECTPROPERTY(O.ID, 'EXECISUPDATETRIGGER') = 1 THEN 'UPDATE'
	ELSE NULL
	END) AS TRIGGERING_EVENT,
	CONVERT(VARCHAR(30), CASE WHEN OBJECTPROPERTY(O.ID, 'EXECISTRIGGERDISABLED') = 1 THEN 'DISABLED' ELSE 'ENABLED' END) AS TRIGGER_STATUS
FROM	DBO.SYSOBJECTS O
	INNER JOIN EVI_TABLES T ON (OBJECT_NAME(O.PARENT_OBJ) = T.TABLE_NAME)
WHERE	(O.XTYPE IN ('TR'))
	AND (O.STATUS >= 0)
--	AND (PERMISSIONS(O.ID) <> 0)
ORDER BY 1 ASC, 2 ASC, 3 ASC, 4 ASC
 
