CREATE VIEW [dbo].[VW_SYS_PROCESS_REASONS] AS
-- LISTA LOS MOTIVOS USADOS PARA LOS PROCESOS.
SELECT	-- TOP 100 PERCENT
	CTM.JOB_TYPE_CODE,
	CDM.PKEY,
	CDM.PAR_KEY,
	CDM.CAT_DATA_CODE,
	CDM.CAT_DATA_DESC,
	NULLIF(CDM.PARENT_CAT_DATA_CODE, '') AS PARENT_CAT_DATA_CODE,
	NULLIF(CDM.PARENT_CAT_DATA_PKEY, '') AS PARENT_CAT_DATA_PKEY,
	CDM.CAT_INACTIVE
FROM	VW_SYS_PROCESS_TYPE_CATS CTM
	INNER JOIN CAT_DATA CDM ON (CTM.CAT_TYPE_PKEY = CDM.PAR_KEY)
	AND CDM.CAT_DATA_CODE IN (
	SELECT	DISTINCT DSSPJ.JOB_REASON_CODE
	FROM	DSS_TBPHYSICAL_JOB DSSPJ
	WHERE	NULLIF(DSSPJ.JOB_REASON_CODE, '') IS NOT NULL
		AND (DSSPJ.ID_JOB_TYPE = CTM.JOB_TYPE_CODE)
	)
-- ORDER BY CTM.JOB_TYPE_CODE ASC, CDM.CAT_DATA_DESC ASC
 
