 
CREATE VIEW [dbo].[EVI_TABLE_SIZES] AS
-- MUESTRA PARA LAS TABLAS ACCESIBLES DE LA BASE DE DATOS LOCAL PARA EL USUARIO ACTUAL:
-- NOMBRE DE CADA TABLA.
-- LONGITUD EN BYTES OCUPADO POR LOS DATOS DE UN REGISTRO DE CADA TABLA.
-- LONGITUD EN BYTES OCUPADO POR LOS ÍNDICES DE UN REGISTRO DE CADA TABLA.
-- CANTIDAD DE REGISTROS DE CADA TABLA.
-- MÁXIMO TAMAÑO TOTAL EN BYTES OCUPADO POR TODOS LOS REGISTROS DE CADA TABLA.
-- MÁXIMO TAMAÑO TOTAL EN BYTES OCUPADO POR TODOS LOS ÍNDICES DE CADA TABLA.
-- MÁXIMO TAMAÑO TOTAL EN BYTES OCUPADO POR CADA TABLA.
SELECT	TOP 100 PERCENT
	T.TABLE_NAME,
	CONVERT(NUMERIC(15), SUM(TC.BYTE_LENGTH)) AS ROW_DATA_BYTE_LENGTH,
	CONVERT(NUMERIC(15), SUM(ISNULL(TCI.BYTE_LENGTH, 0))) AS ROW_INDEXES_BYTE_LENGTH,
	CONVERT(NUMERIC(15), MAX(T.TABLE_ROWS)) AS ROW_QUANTITY,
	CONVERT(NUMERIC(15), SUM(TC.BYTE_LENGTH) * MAX(T.TABLE_ROWS)) AS TOTAL_DATA_SIZE,
	CONVERT(NUMERIC(15), SUM(ISNULL(TCI.BYTE_LENGTH, 0)) * MAX(T.TABLE_ROWS)) AS TOTAL_INDEXES_SIZE,
	CONVERT(NUMERIC(15), (SUM(TC.BYTE_LENGTH) + SUM(ISNULL(TCI.BYTE_LENGTH, 0))) * MAX(T.TABLE_ROWS)) AS TOTAL_TABLE_SIZE
FROM	EVI_TABLES T
	INNER JOIN EVI_TABLE_COLUMNS TC ON (T.TABLE_NAME = TC.TABLE_NAME)
	LEFT OUTER JOIN EVI_TABLE_COLUMN_INDEXES TCI ON (TC.TABLE_NAME = TCI.TABLE_NAME AND TC.COLUMN_NAME = TCI.COLUMN_NAME)
GROUP BY T.TABLE_NAME
ORDER BY T.TABLE_NAME ASC
 
