CREATE VIEW [dbo].[VW_SYS_UNIDAD] AS
 
-- MUESTRA DE MANERA NORMALIZADA TODAS LAS UNIDADES DE ENGAGE.
SELECT	TOP 100 PERCENT
	UNIT_CODE,
	UNIT_DESCRIPTION
FROM	ORGANIZATION
GROUP BY UNIT_CODE,
	UNIT_DESCRIPTION
ORDER BY 1 ASC,
	2 ASC
 
