CREATE VIEW [dbo].[VW_SYS_CRITERIOS] AS
-- VISTA DE SISTEMA EDITABLE QUE MUESTRA LAS VISTAS DE USUARIO UTILIZADAS POR EL MANAGER.
SELECT	TOP 100 PERCENT
	VIEW_NAME
FROM	EVI_VIEWS
WHERE	(VIEW_NAME <> 'CAT_TYPE_EXT')
	AND (VIEW_NAME NOT LIKE 'EVI_%')
	AND (VIEW_NAME NOT LIKE 'VW_SYS_%')
ORDER BY 1 ASC
 
