 
CREATE VIEW [dbo].[EVI_SCHEMA_SIZES] AS
-- MUESTRA PARA LA BASE DE DATOS LOCAL PARA EL USUARIO ACTUAL:
-- MÁXIMO TAMAÑO TOTAL DE LOS DATOS DEL ESQUEMA.
-- MÁXIMO TAMAÑO TOTAL DE LOS ÍNDICES DEL ESQUEMA.
-- MÁXIMO TAMAÑO TOTAL DEL ESQUEMA.
SELECT	CONVERT(NUMERIC(15, 4), SUM(TOTAL_DATA_SIZE) / 1048576) AS TOTAL_SCHEMA_DATA_SIZE_MB,
	CONVERT(NUMERIC(15, 4), SUM(TOTAL_INDEXES_SIZE) / 1048576) AS TOTAL_SCHEMA_INDEXES_SIZE_MB,
	CONVERT(NUMERIC(15, 4), SUM(TOTAL_TABLE_SIZE) / 1048576) AS TOTAL_SCHEMA_SIZE_MB
FROM	EVI_TABLE_SIZES
 
