 
CREATE VIEW [dbo].[EVI_TABLE_COLUMN_FOREIGN_KEYS] AS
-- MUESTRA LAS RESTRICCIONES DE CLAVE FORÁNEA DE LAS COLUMNAS DE LAS TABLAS ACCESIBLES DE LA BASE DE DATOS LOCAL PARA EL USUARIO ACTUAL.
-- NO SE UTILIZA LA TABLA DBO.SYSREFERENCES PORQUE MUESTRA LAS CLAVES FORÁNEAS APLANADAS.
SELECT	TOP 100 PERCENT
	CC.TABLE_CATALOG,
	CC.TABLE_SCHEMA,
	TC1.TABLE_NAME AS FK_TABLE_NAME,
	CONVERT(NUMERIC(15), FK.KEYNO) AS COLUMN_ORDER,
	TC1.COLUMN_NAME AS FK_COLUMN_NAME,
	TC2.TABLE_NAME AS PK_TABLE_NAME,
	TC2.COLUMN_NAME AS PK_COLUMN_NAME,
        CC.CONSTRAINT_NAME AS RELATIONSHIP_NAME
FROM	EVI_TABLE_CONSTRAINTS CC
	INNER JOIN DBO.SYSFOREIGNKEYS FK ON (CC.TABLE_NAME = OBJECT_NAME(FK.FKEYID) AND CC.CONSTRAINT_NAME = OBJECT_NAME(FK.CONSTID))
	INNER JOIN EVI_TABLE_COLUMNS TC1 ON (OBJECT_NAME(FK.FKEYID) = TC1.TABLE_NAME AND FK.FKEY = TC1.ORDINAL_POSITION)
	INNER JOIN EVI_TABLE_COLUMNS TC2 ON (OBJECT_NAME(FK.RKEYID) = TC2.TABLE_NAME AND FK.RKEY = TC2.ORDINAL_POSITION)
ORDER BY 1 ASC, 2 ASC, 3 ASC, 4 ASC, 5 ASC, 6 ASC, 7 ASC
 
