CREATE VIEW [dbo].[VW_SYS_PROCESS_NOTE_QTY] AS
-- LISTA LA CANTIDAD DE NOTAS POR CADA PROCESO O CLIENTE.
SELECT	-- TOP 100 PERCENT
	PN.PAR_KEY,
	COUNT(1) AS NOTE_COUNT
FROM	PHYSICAL_NOTES PN
GROUP BY PN.PAR_KEY
-- ORDER BY PN.PAR_KEY ASC
 
