CREATE VIEW [dbo].[EVI_DATABASE_SESSIONS] AS
-- MUESTRA INFORMACIÓN DE LAS SESIONES CONECTADAS A LA BASE DE DATOS DE LA SESIÓN ACTUAL.
SELECT	TOP 100 PERCENT
	CONVERT(NUMERIC(15), P.SPID) AS SPID,
	CONVERT(VARCHAR(30), CASE WHEN (P.DBID = 0) THEN NULL ELSE DB_NAME(P.DBID) END) AS SERVER_CATALOG,
	CONVERT(VARCHAR(30), USER_NAME(P.UID)) AS SERVER_SCHEMA,
	P.LOGIN_TIME AS LOGON_TIME,
	CONVERT(NUMERIC(15), CASE WHEN (P.LAST_BATCH <= CONVERT(DATETIME, '1900-01-01')) THEN DATEDIFF(SECOND, P.LOGIN_TIME, GETDATE()) ELSE DATEDIFF(SECOND, P.LAST_BATCH, GETDATE()) END) AS LAST_CALL_ET,
	CONVERT(VARCHAR(30), CASE WHEN UPPER(LTRIM(RTRIM(P.STATUS))) = 'SLEEPING' AND UPPER(LTRIM(RTRIM(P.CMD))) = 'AWAITING COMMAND' THEN 'INACTIVE' ELSE UPPER(LTRIM(RTRIM(P.STATUS))) END) AS SESSION_STATUS,
	CONVERT(VARCHAR(64), NULLIF(LTRIM(RTRIM(P.NT_DOMAIN)), '') + '\' + NULLIF(LTRIM(RTRIM(P.HOSTNAME)), '')) AS MACHINE_NAME,
	CONVERT(VARCHAR(30), NULLIF(LTRIM(RTRIM(P.HOSTNAME)), '')) AS TERMINAL_NAME,
	CONVERT(VARCHAR(128), NULLIF(LTRIM(RTRIM(P.PROGRAM_NAME)), '')) AS PROGRAM_NAME,
	CONVERT(VARCHAR(17), CONVERT(VARCHAR, NULLIF(LTRIM(RTRIM(P.HOSTPROCESS)), '')) + CASE WHEN (P.KPID = 0) THEN '' ELSE ':' + CONVERT(VARCHAR, P.KPID) END) AS HOST_PROCESS,
	CONVERT(VARCHAR(30), NULLIF(LTRIM(RTRIM(P.NT_USERNAME)), '')) AS OS_USER,
	CONVERT(VARCHAR(30), NULLIF(LTRIM(RTRIM(P.LOGINAME)), '')) AS LOGON_NAME
FROM	MASTER.SYS.SYSPROCESSES P WITH (NOLOCK)
WHERE	(P.DBID = DB_ID()) -- BASE DE DATOS DE LA SESIÓN ACTUAL.
ORDER BY 1 ASC
 
