CREATE VIEW [dbo].[VW_SYS_PROCESS_SUBREASONS] AS
-- LISTA LOS SUBMOTIVOS USADOS PARA LOS PROCESOS.
SELECT	-- TOP 100 PERCENT
	CTSM.JOB_TYPE_CODE,
	CDSM.PKEY,
	CDSM.PAR_KEY,
	CDSM.CAT_DATA_CODE,
	CDSM.CAT_DATA_DESC,
	NULLIF(CDSM.PARENT_CAT_DATA_CODE, '') AS PARENT_CAT_DATA_CODE,
	NULLIF(CDSM.PARENT_CAT_DATA_PKEY, '') AS PARENT_CAT_DATA_PKEY,
	CDSM.CAT_INACTIVE
FROM	VW_SYS_PROCESS_TYPE_CATS CTSM
	INNER JOIN CAT_DATA CDSM ON (CTSM.CAT_TYPE_PKEY = CDSM.PAR_KEY)
	AND CDSM.CAT_DATA_CODE IN (
	SELECT	DISTINCT DSSPJ.JOB_SUBREASON_CODE
	FROM	DSS_TBPHYSICAL_JOB DSSPJ
	WHERE	NULLIF(DSSPJ.JOB_SUBREASON_CODE, '') IS NOT NULL
		AND (DSSPJ.ID_JOB_TYPE = CTSM.JOB_TYPE_CODE)
	)
-- ORDER BY CTSM.JOB_TYPE_CODE ASC, CDSM.CAT_DATA_DESC ASC
 
