CREATE VIEW [dbo].[VW_SYS_HISTORY_CALL] AS
-- CONSULTA UTILIZADA PARA VER LA HISTORIA DE LAS LLAMADAS DE CADA ACTIVIDAD.
SELECT	TOP 100 PERCENT
	DSSPC.PKEY_ATTENDED_CUSTOMER,
	DSSPC.PKEY_PHYSICAL_CALL,
--	DSSPC.ATT_STATE_CODE,
--	DSSPC.ATT_RESULT_CODE,
	DSSPC.CALL_DATE_TIME,
	DSSPC.CALL_DATE_TIME_END,
	DSSPC.PHYS_STATE_CODE,
	DSSPC.PHYS_RESULT_CODE,
--	DSSPC.MEDIA_ID1,
	DSSPC.IN_OUT_IDR,
	CONVERT(VARCHAR, DSSPC.CALL_DATE_TIME_END - DSSPC.CALL_DATE_TIME, 108) AS ELAPSED_TIME,
	DSSPC.ID_RANGHOUR,
	DSSPC.PROGRAMMED_DATE_TIME,
	ISNULL(A.USER_NAME, 'SIN ASIGNAR') AS LAST_USER,
	ISNULL(ORG.UNIT_DESCRIPTION, 'SIN ASIGNAR') AS LAST_UNIT,
	DSSPC.COMMENTA
FROM	DSS_TBPHYSICAL_CALL DSSPC
	LEFT OUTER JOIN VW_SYS_UNIDAD ORG ON (DSSPC.ID_GROUP = ORG.UNIT_CODE)
	LEFT OUTER JOIN VW_SYS_USUARIO A ON (DSSPC.ID_AGENT = A.USER_ID)
ORDER BY DSSPC.CALL_DATE_TIME_END ASC,
	DSSPC.PKEY_PHYSICAL_CALL ASC
 
