CREATE VIEW [dbo].[VW_SYS_USUARIO] AS
 
-- MUESTRA DE MANERA NORMALIZADA TODOS LOS USUARIOS DE ENGAGE, SEAN AGENTES O SUPERVISORES.
SELECT	TOP 100 PERCENT
	-- T1.UNIT_CODE,
	T1.USER_ID,
	T1.USER_NAME
FROM	(
SELECT	-- AG.UNIT_CODE,
	AG.USER_ID,
	AG.USER_NAME
FROM	AGENTE AG
 
UNION
 
SELECT	-- SU.UNIT_CODE,
	SU.SUPERVISOR_CODE AS USER_ID,
	SU.SUPERVISOR_NAME AS USER_NAME
FROM	SUPERVISOR SU
) T1
ORDER BY 1 ASC,
	2 ASC
 
