 
CREATE VIEW [dbo].[EVI_SEQUENCES] AS
-- MUESTRA LAS SECUENCIAS ACCESIBLES DE LA BASE DE DATOS LOCAL PARA EL USUARIO ACTUAL.
SELECT	TOP 100 PERCENT
	TC.TABLE_CATALOG AS SEQUENCE_CATALOG,
	TC.TABLE_SCHEMA AS SEQUENCE_SCHEMA,
	TC.TABLE_NAME,
	TC.COLUMN_NAME,
	CONVERT(VARCHAR(30), 'SEQ' + '_' + TC.TABLE_NAME) AS SEQUENCE_NAME,
        CONVERT(NUMERIC(15), ISNULL(IDENT_SEED(TC.TABLE_NAME), 1)) AS MIN_VALUE,
        CONVERT(NUMERIC(15), REPLICATE('9', ISNULL(TC.NUMERIC_PRECISION, 0) - ISNULL(TC.NUMERIC_SCALE, 0))) AS MAX_VALUE,
        CONVERT(NUMERIC(15), ISNULL(IDENT_INCR(TC.TABLE_NAME), 1)) AS INCREMENT_BY,
        CONVERT(VARCHAR(1), 'N') AS CYCLE_FLAG, -- 'N', 'Y'.
        CONVERT(VARCHAR(1), 'Y') AS ORDER_FLAG, -- 'N', 'Y'.
        CONVERT(NUMERIC(15), 0) AS CACHE_SIZE,
        CONVERT(NUMERIC(15), ISNULL(IDENT_CURRENT(TC.TABLE_NAME), 1)) AS LAST_NUMBER
FROM	EVI_TABLE_COLUMNS TC
WHERE	(ISNULL(COLUMNPROPERTY(OBJECT_ID(TC.TABLE_NAME), TC.COLUMN_NAME, 'ISIDENTITY'), 0) = 1)
ORDER BY 1 ASC, 2 ASC, 3 ASC, 4 ASC, 5 ASC
 
