 
 
 
 
 
 
 
CREATE VIEW [dbo].[VW_PROYECTOS] AS
 
SELECT	DISTINCT TOP 1000
		P.ID_PROYECTO	AS CAT_DATA_CODE, 
		'('+P.CODIGO+') - ' + P.NORMA_REF AS CAT_DATA_DESC, 
		P.ID_PROYECTO	AS PKEY, 
		CLI.ID_CLIENTE	AS PARENT_CAT_DATA_CODE, 
		CLI.ID_CLIENTE	AS PARENT_CAT_DATA_PKEY
FROM    LK_PROYECTO P 
		INNER JOIN LK_CLIENTES CLI ON P.ID_CLIENTE = CLI.ID_CLIENTE
		--INNER JOIN LK_PROYECTO P ON CO.ID_COTIZACION = P.ID_COTIZACION
ORDER BY PARENT_CAT_DATA_CODE, CAT_DATA_DESC
 
