 
CREATE VIEW [dbo].[EVI_TABLE_CONSTRAINTS] AS
-- MUESTRA LAS RESTRICCIONES DE TABLAS ACCESIBLES DE LA BASE DE DATOS LOCAL PARA EL USUARIO ACTUAL.
-- DBO.SYSOBJECTS.STATUS < 0, INDICA QUE EL OBJETO ES DE SISTEMA O, SI ES DE USUARIO, ESTÁ CORRUPTO.
-- PERMISSIONS(DBO.SYSOBJECTS.ID) = 0, INDICA QUE EL OBJETO NO ES ACCESIBLE PARA EL USUARIO ACTUAL.
SELECT	TOP 100 PERCENT
	T.TABLE_CATALOG,
	T.TABLE_SCHEMA,
	T.TABLE_NAME,
	CONVERT(VARCHAR(30), CASE O.XTYPE
	WHEN 'C' THEN 'CHECK'
	WHEN 'D' THEN 'DEFAULT'
	WHEN 'F' THEN 'FOREIGN KEY'
	WHEN 'PK' THEN 'PRIMARY KEY'
	WHEN 'UQ' THEN 'UNIQUE'
	END) AS CONSTRAINT_TYPE,
	CONVERT(VARCHAR(30), O.NAME) AS CONSTRAINT_NAME,
	CONVERT(VARCHAR(30), CASE WHEN OBJECTPROPERTY(O.ID, 'CNSTISDISABLED') = 1 THEN 'DISABLED' ELSE 'ENABLED' END) AS CONSTRAINT_STATUS,
	CONVERT(VARCHAR(30), CASE WHEN OBJECTPROPERTY(O.ID, 'CNSTISNOTTRUSTED') = 1 THEN 'NOT VALIDATED' ELSE 'VALIDATED' END) AS CONSTRAINT_VALIDATED,
	CONVERT(VARCHAR(1), CASE WHEN OBJECTPROPERTY(O.ID, 'CNSTISDELETECASCADE') = 1 THEN 'Y' ELSE 'N' END) AS ON_DELETE_CASCADE,
	CONVERT(VARCHAR(1), CASE WHEN OBJECTPROPERTY(O.ID, 'CNSTISUPDATECASCADE') = 1 THEN 'Y' ELSE 'N' END) AS ON_UPDATE_CASCADE
FROM	DBO.SYSOBJECTS O
	INNER JOIN EVI_TABLES T ON (OBJECT_NAME(O.PARENT_OBJ) = T.TABLE_NAME)
WHERE	(O.XTYPE IN ('C', 'D', 'F', 'PK', 'UQ'))
	AND (O.STATUS >= 0)
--	AND (PERMISSIONS(O.ID) <> 0)
ORDER BY 1 ASC, 2 ASC, 3 ASC, 4 ASC, 5 ASC
 
