 
CREATE VIEW [dbo].[EVI_TABLE_COLUMN_INDEXES] AS
-- MUESTRA LOS ÍNDICES DE LAS COLUMNAS DE LAS TABLAS ACCESIBLES DE LA BASE DE DATOS LOCAL PARA EL USUARIO ACTUAL.
SELECT	TOP 100 PERCENT
	TI.TABLE_CATALOG,
	TI.TABLE_SCHEMA,
	TI.TABLE_NAME,
	TI.INDEX_NAME,
	CONVERT(NUMERIC(15), IK.KEYNO) AS COLUMN_ORDER,
	TC.COLUMN_NAME,
	TC.BYTE_LENGTH,
	TC.CHAR_COL_DECL_LENGTH
FROM	EVI_TABLE_INDEXES TI
	INNER JOIN DBO.SYSINDEXES O ON (TI.TABLE_NAME = OBJECT_NAME(O.ID) AND TI.INDEX_NAME = O.NAME)
        INNER JOIN DBO.SYSINDEXKEYS IK ON (O.ID = IK.ID AND O.INDID = IK.INDID)
	INNER JOIN EVI_TABLE_COLUMNS TC ON (TI.TABLE_NAME = TC.TABLE_NAME AND IK.COLID = TC.ORDINAL_POSITION)
ORDER BY 1 ASC, 2 ASC, 3 ASC, 4 ASC, 5 ASC
 
