CREATE VIEW [dbo].[v_sys_profiles] AS
 
select TOP (100) PERCENT UNIT_CODE, UNIT_DESCRIPTION
FROM ORGANIZATION
WHERE BOTTOM = 1
GROUP BY UNIT_CODE, UNIT_DESCRIPTION
ORDER BY UNIT_CODE, UNIT_DESCRIPTION
 
