CREATE VIEW [dbo].[EVI_TABLE_INDEXES] AS
-- MUESTRA LOS ÍNDICES DE TABLAS ACCESIBLES DE LA BASE DE DATOS LOCAL PARA EL USUARIO ACTUAL.
-- SYS.SYSINDEXES.STATUS < 0, INDICA QUE EL OBJETO ES DE SISTEMA O, SI ES DE USUARIO, ESTÁ CORRUPTO.
-- PERMISSIONS(SYS.SYSINDEXES.ID) = 0, INDICA QUE EL OBJETO NO ES ACCESIBLE PARA EL USUARIO ACTUAL.
-- LEFT(SYS.SYSINDEXES.NAME) <> '_', FILTRA LOS ÍNDICES ESTADÍSTICOS.
-- SYS.SYSINDEXES.INDID NOT IN (0, 255), FILTRA LOS ÍNDICES DE SISTEMA PARA CAMPOS IMAGE Y EL REGISTRO DE LA MISMA TABLA.
SELECT	TOP 100 PERCENT
	T.TABLE_CATALOG,
	T.TABLE_SCHEMA,
	T.TABLE_NAME,
	CONVERT(VARCHAR(30), O.NAME) AS INDEX_NAME,
	CONVERT(VARCHAR(30), CASE O.INDID WHEN 0 THEN 'NONINDEXED' WHEN 1 THEN 'CLUSTERED' WHEN 255 THEN 'LOB' ELSE 'NONCLUSTERED' END) AS INDEX_TYPE,
	CONVERT(VARCHAR(1), CASE WHEN ((O.STATUS % 16) - 2 = 0) THEN 'Y' ELSE 'N' END) AS IS_UNIQUE,
	CONVERT(VARCHAR(30), FG.GROUPNAME) AS TABLESPACE_NAME,
	CONVERT(NUMERIC(15), ISNULL(O.ROWS, 0)) AS INDEX_ROWS
FROM	SYS.SYSINDEXES O
	INNER JOIN SYS.SYSFILEGROUPS FG ON (O.GROUPID = FG.GROUPID)
	INNER JOIN EVI_TABLES T ON (OBJECT_NAME(O.ID) = T.TABLE_NAME)
WHERE	(O.STATUS >= 0)
	AND (LEFT(O.NAME, 1) <> '_')
	AND (O.INDID NOT IN (0, 255))
--	AND (PERMISSIONS(O.ID) <> 0)
ORDER BY 4 ASC
 
