 
CREATE VIEW [dbo].[EVI_TABLES] AS
-- MUESTRA LAS TABLAS ACCESIBLES DE LA BASE DE DATOS LOCAL PARA EL USUARIO ACTUAL.
-- DBO.SYSOBJECTS.STATUS < 0, INDICA QUE EL OBJETO ES DE SISTEMA O, SI ES DE USUARIO, ESTÁ CORRUPTO.
-- PERMISSIONS(DBO.SYSOBJECTS.ID) = 0, INDICA QUE EL OBJETO NO ES ACCESIBLE PARA EL USUARIO ACTUAL.
SELECT	TOP 100 PERCENT
	CONVERT(VARCHAR(30), DB_NAME()) AS TABLE_CATALOG,
	CONVERT(VARCHAR(30), USER_NAME(O.UID)) AS TABLE_SCHEMA,
	CONVERT(VARCHAR(30), O.NAME) AS TABLE_NAME,
	CONVERT(VARCHAR(30), ISNULL(FG.GROUPNAME, 'DEFAULT')) AS TABLESPACE_NAME, -- SE PONE EL VALOR 'DEFAULT' CUANDO NO SE PUEDE OBTENER EL FILEGROUP.
	CONVERT(NUMERIC(15), ISNULL(SI.ROWS, 0)) AS TABLE_ROWS
FROM	DBO.SYSOBJECTS O
	LEFT OUTER JOIN DBO.SYSINDEXES SI ON (O.ID = SI.ID AND (SI.INDID = 0 OR SI.INDID = 1)) -- DBO.SYSINDEXES.INDID = 1 ES PARA PK CLUSTERED. DBO.SYSINDEXES.INDID = 0 ES PARA TABLA SIN ÍNDICES.
	LEFT OUTER JOIN DBO.SYSFILEGROUPS FG ON (SI.GROUPID = FG.GROUPID)
WHERE	(O.XTYPE IN ('U'))
	AND (O.STATUS >= 0)
	AND (UPPER(O.NAME) NOT IN ('DTPROPERTIES', 'SYSDIAGRAMS'))
--	AND (PERMISSIONS(O.ID) <> 0)
ORDER BY 1 ASC, 2 ASC, 3 ASC
 
