CREATE VIEW [dbo].[VW_SYS_PROCESS_TYPE_CATS] AS
-- LISTA LOS TIPOS DE PROCESO Y SUS CATEGORÍAS ASOCIADAS A VALIDACIONES DE LISTAS DE VALORES.
SELECT	JT.JOB_TYPE_CODE,
	CT2.PKEY AS CAT_TYPE_PKEY
FROM	JOB_TYPE JT
	INNER JOIN CALL_TYPE CT ON (JT.PKEY = CT.PAR_KEY)
	INNER JOIN CALL_CONV_STRUCTURES CCS ON (CT.PKEY = CCS.PAR_KEY)
	INNER JOIN CONV_STRUCTURE_STEP_NORMAL CSSN ON (CCS.PKEY = CSSN.PAR_KEY)
	INNER JOIN DETAIL_FIELD DF ON (CSSN.PKEY = DF.PAR_KEY)
	INNER JOIN VW_SYS_CAT_TYPE CT2 ON (CT2.PKEY = DF.VAL_TBL_NAME)
WHERE	(DF.CTL_TYPE_CODE = 'campovalidable')
	AND (DF.VAL_TBL_NAME IS NOT NULL)
GROUP BY JT.JOB_TYPE_CODE, CT2.PKEY
 
