CREATE VIEW [dbo].[VW_SYS_QUERY_INBOX] AS
-- VISTA DE SOPORTE PARA LA INBOX.
SELECT	PJ.JOB_TYPE_CODE,
	PJ.JOB_REASON_CODE,
	PJ.JOB_SUBREASON_CODE,
	PJ.PKEY AS JOB_PKEY,
	PJ.JOB_SEQ,
	PJ.CAMPAIGN_IDR AS ACTION_CAMPAIGN,
	PJ.JOB_PRIORITY,
	PJ.JOB_STATE_CODE,
	PJ.JOB_STATE_DATE,
	CT.CUST_TYPE_CODE,
	CASE WHEN (GETDATE() > PJ.JOB_MAX_END_DATE) THEN 1 ELSE 0 END AS DEFEATED_PROCESS,
	UN1.UNIT_CODE AS GROUP_CODE,
	ISNULL(US1.USER_ID, AC.USER_ID) AS USER_ID,
	AC.PKEY AS ATT_PKEY,
	AC.PKEY_CAMPAIGN,
	AC.ATT_STATE_CODE,
	AC.PROGRAMMED_IDR,
	AC.PROGRAMMED_DATE_TIME,
	AC.ATT_COMMENT,
	CASE WHEN (GETDATE() > AC.ATT_MAX_END_DATE) THEN 1 ELSE 0 END AS DEFEATED_ACTIVITY,
	CASE WHEN (AC.USER_ID IS NULL OR AC.USER_ID = ' ') THEN 'UNIDAD' ELSE 'USUARIO' END AS OWNER_TYPE,
	CT.CUST_TYPE_DESC,
	JT.JOB_TYPE_DESC,
	CL.CALL_TYPE_DESC,
	CL.RESTRICTION_TYPE,
	CU.CUSTOMER_NAME,
	CU.PKEY AS CUSTOMER_PKEY,
	UN.UNIT_DESCRIPTION AS PREV_UNIT_DESCRIPTION,
	UN1.UNIT_DESCRIPTION,
	US.USER_NAME AS PREV_USER_NAME,
	ISNULL(US1.USER_NAME, UN1.UNIT_DESCRIPTION) AS USER_NAME,
	ISNULL(T4.NOTE_COUNT, 0) AS NOTESCOUNT,
	ISNULL(T5.ATTACH_COUNT, 0) AS DOCUMENTSCOUNT
FROM	CUSTOMER_TYPE CT
	INNER JOIN JOB_TYPE JT ON (CT.CUST_TYPE_CODE = JT.CUST_TYPE_CODE AND JT.JOB_READY_IDR = '1')
	INNER JOIN PHYSICAL_JOB PJ ON (JT.JOB_TYPE_CODE = PJ.JOB_TYPE_CODE)
	INNER JOIN CUSTOMER CU ON (PJ.PKEY_CUSTOMER = CU.PKEY)
	INNER JOIN (CALL_TYPE CL INNER JOIN ATTENDED_CUSTOMER AC ON CL.CALL_TYPE_CODE = AC.CALL_TYPE_CODE) ON (JT.PKEY = CL.PAR_KEY AND PJ.PKEY = AC.PKEY_JOB)
	INNER JOIN VW_SYS_UNIDAD UN1 ON (AC.GROUP_CODE = UN1.UNIT_CODE)
	LEFT OUTER JOIN VW_SYS_USUARIO US1 ON (AC.USER_ID = US1.USER_ID)
	LEFT OUTER JOIN VW_SYS_UNIDAD UN ON (AC.PREV_GROUPCODE = UN.UNIT_CODE)
	LEFT OUTER JOIN VW_SYS_USUARIO US ON (AC.PREV_USERID = US.USER_ID)
	LEFT OUTER JOIN VW_SYS_PROCESS_NOTE_QTY T4 ON (PJ.PKEY = T4.PAR_KEY)
	LEFT OUTER JOIN VW_SYS_PROCESS_ATTACH_QTY T5 ON (PJ.PKEY = T5.PAR_KEY)
WHERE	(PJ.JOB_STATE_CODE = 'NOTWORKED' OR PJ.JOB_STATE_CODE = 'OPENED')
	AND (JT.JOB_TYPE_CODE NOT LIKE 'AUTOEXEC%' AND JT.JOB_TYPE_CODE NOT LIKE 'HOME%' AND JT.JOB_TYPE_CODE NOT LIKE 'SUPER%')
	AND NOT EXISTS (SELECT 1 FROM CUSTOMER_TYPE CT1 WHERE (CT1.HISTORY_JOB_CODE = JT.JOB_TYPE_CODE))
 
