 
 
 
 
 
 
CREATE VIEW [dbo].[VW_SERVICIOS] AS
 
SELECT	DISTINCT TOP 100 
		ID_TIPO_SERVICIO	AS CAT_DATA_CODE, 
		DESC_TIPO_SERVICIO	AS CAT_DATA_DESC, 
		ID_TIPO_SERVICIO	AS PKEY, 
		''					AS PARENT_CAT_DATA_CODE, 
		''					AS PARENT_CAT_DATA_PKEY
FROM    LK_TIPO_SERVICIOS
 
