 
CREATE VIEW [dbo].[VW_SYS_CANTIDAD_USUARIOS] AS
-- MUESTRA LA CANTIDAD DE USUARIOS DEFINIDOS EN ENGAGE.
-- MUESTRA LA CANTIDAD DE USUARIOS QUE ACTUALMENTE ESTÁN OPERANDO CON ENGAGE.
SELECT	(SELECT CONVERT(NUMERIC(9), COUNT(DISTINCT USER_ID)) FROM VW_SYS_USUARIO) AS CANTIDAD_USUARIOS_DEFINIDOS,
	(SELECT CONVERT(NUMERIC(9), COUNT(DISTINCT USER_ID)) FROM PSESSIONS WHERE BEGIN_TIMESTAMP BETWEEN CONVERT(VARCHAR, GETDATE(), 112) AND CONVERT(VARCHAR, GETDATE() + 1, 112)) AS CANTIDAD_USUARIOS_CONCURRENTES
 
