 
CREATE VIEW [dbo].[EVI_TABLE_COLUMN_CONSTRAINTS] AS
-- MUESTRA LAS RESTRICCIONES DE LAS COLUMNAS DE LAS TABLAS ACCESIBLES DE LA BASE DE DATOS LOCAL PARA EL USUARIO ACTUAL.
SELECT	TOP 100 PERCENT
	CC.TABLE_CATALOG,
	CC.TABLE_SCHEMA,
	CC.TABLE_NAME,
        CC.CONSTRAINT_TYPE,
        CC.CONSTRAINT_NAME,
        ISNULL(TCI.COLUMN_ORDER, 1) AS COLUMN_ORDER,
	ISNULL(TCI.COLUMN_NAME, TC.COLUMN_NAME) AS COLUMN_NAME
FROM	EVI_TABLE_CONSTRAINTS CC
        INNER JOIN DBO.SYSCONSTRAINTS RC ON (CC.TABLE_NAME = OBJECT_NAME(RC.ID) AND CC.CONSTRAINT_NAME = OBJECT_NAME(RC.CONSTID))
	LEFT OUTER JOIN EVI_TABLE_COLUMNS TC ON (CC.TABLE_NAME = TC.TABLE_NAME AND RC.COLID = TC.ORDINAL_POSITION)
	LEFT OUTER JOIN EVI_TABLE_COLUMN_INDEXES TCI ON (CC.TABLE_NAME = TCI.TABLE_NAME AND CC.CONSTRAINT_NAME = TCI.INDEX_NAME)
ORDER BY 1 ASC, 2 ASC, 3 ASC, 4 ASC, 5 ASC, 6 ASC
 
