 
CREATE VIEW [dbo].[EVI_VIEWS] AS
-- MUESTRA LAS VISTAS ACCESIBLES DE LA BASE DE DATOS LOCAL PARA EL USUARIO ACTUAL.
-- DBO.SYSOBJECTS.STATUS < 0, INDICA QUE EL OBJETO ES DE SISTEMA O, SI ES DE USUARIO, ESTÁ CORRUPTO.
-- PERMISSIONS(DBO.SYSOBJECTS.ID) = 0, INDICA QUE EL OBJETO NO ES ACCESIBLE PARA EL USUARIO ACTUAL.
SELECT	TOP 100 PERCENT
	CONVERT(VARCHAR(30), DB_NAME()) AS VIEW_CATALOG,
	CONVERT(VARCHAR(30), USER_NAME(O.UID)) AS VIEW_SCHEMA,
	CONVERT(VARCHAR(30), O.NAME) AS VIEW_NAME
FROM	DBO.SYSOBJECTS O
WHERE	(O.XTYPE IN ('V'))
	AND (O.STATUS >= 0)
--	AND (PERMISSIONS(O.ID) <> 0)
ORDER BY 1 ASC, 2 ASC, 3 ASC
 
