 
CREATE VIEW [dbo].[EVI_DATA_TYPES] AS
-- MUESTRA LOS TIPOS DE DATOS ACCESIBLES DE LA BASE DE DATOS LOCAL PARA EL USUARIO ACTUAL.
SELECT	TOP 100 PERCENT
	CONVERT(VARCHAR(30), DB_NAME()) AS DATA_TYPE_CATALOG,
	CONVERT(VARCHAR(30), USER_NAME(ST.UID)) AS DATA_TYPE_SCHEMA,
	CONVERT(VARCHAR(30), UPPER(ST.NAME)) AS DATA_TYPE_NAME
FROM	DBO.SYSTYPES ST
ORDER BY 1 ASC, 2 ASC, 3 ASC
 
