 
CREATE VIEW [dbo].[EVI_OBJECTS] AS
-- MUESTRA TODOS LOS OBJETOS ACCESIBLES DE LA BASE DE DATOS LOCAL PARA EL USUARIO ACTUAL.
-- DBO.SYSOBJECTS.STATUS < 0, INDICA QUE EL OBJETO ES DE SISTEMA O, SI ES DE USUARIO, ESTÁ CORRUPTO.
-- PERMISSIONS(DBO.SYSOBJECTS.ID) = 0, INDICA QUE EL OBJETO NO ES ACCESIBLE PARA EL USUARIO ACTUAL.
-- LOS OBJETOS DE TIPO 'SEQUENCE' SON, EN REALIDAD, CAMPOS IDENTITY DE LAS TABLAS Y, POR ENDE, TOMAN LA FECHA DE CREACIÓN DE LAS MISMAS.
-- LOS OBJETOS DE TIPO 'INDEX' TOMAN LA FECHA DE CREACIÓN DE LA TABLA A LA QUE PERTENECEN.
SELECT	TOP 100 PERCENT
	T1.OBJECT_CATALOG,
	T1.OBJECT_SCHEMA,
	T1.OBJECT_TYPE,
	T1.OBJECT_NAME,
	T1.NAME_LENGTH,
	T1.TABLE_NAME,
	T1.CREATION_DATE,
	T1.OBJECT_STATUS
FROM	(
SELECT	DB_NAME() AS OBJECT_CATALOG,
	USER_NAME(O.UID) AS OBJECT_SCHEMA,
	CONVERT(VARCHAR(30), CASE O.XTYPE
	WHEN 'C' THEN 'CHECK'
	WHEN 'D' THEN 'DEFAULT'
	WHEN 'F' THEN 'FOREIGN KEY'
	WHEN 'PK' THEN 'PRIMARY KEY'
	WHEN 'UQ' THEN 'UNIQUE'
	WHEN 'U' THEN 'TABLE' -- 'USER TABLE'
	WHEN 'S' THEN 'SYSTEM TABLE'
	WHEN 'V' THEN 'VIEW' -- 'USER VIEW'
	WHEN 'P' THEN 'PROCEDURE' -- 'STORED PROCEDURE'
	WHEN 'FN' THEN 'FUNCTION' -- 'SCALAR FUNCTION'
	WHEN 'IF' THEN 'FUNCTION' -- 'INLINED TABLE-FUNCTION'
	WHEN 'RF' THEN 'PROCEDURE' -- 'REPLICATION FILTER STORED PROCEDURE'
	WHEN 'TF' THEN 'FUNCTION' -- 'TABLE FUNCTION'
	WHEN 'X' THEN 'PROCEDURE' -- 'EXTENDED STORED PROCEDURE'
	WHEN 'TR' THEN 'TRIGGER'
	END) AS OBJECT_TYPE,
	O.NAME AS OBJECT_NAME,
	CONVERT(NUMERIC(15), LEN(O.NAME)) AS NAME_LENGTH,
	OBJECT_NAME(O.PARENT_OBJ) AS TABLE_NAME,
	O.CRDATE AS CREATION_DATE,
	CONVERT(VARCHAR(30), CASE WHEN (O.STATUS < 0) THEN 'INVALID' ELSE 'VALID' END) AS OBJECT_STATUS
FROM	DBO.SYSOBJECTS O
WHERE	(O.XTYPE IN ('C', 'D', 'F', 'PK', 'UQ', 'U', 'V', 'P', 'FN', 'IF', 'TF', 'TR'))
	AND (O.STATUS >= 0)
	AND (UPPER(O.NAME) NOT IN ('SP_ALTERDIAGRAM', 'SP_CREATEDIAGRAM', 'SP_DROPDIAGRAM', 'SP_HELPDIAGRAMDEFINITION', 'SP_HELPDIAGRAMS', 'SP_RENAMEDIAGRAM', 'SP_UPGRADDIAGRAMS', 'FN_DIAGRAMOBJECTS', 'UK_PRINCIPAL_NAME'))
	AND (UPPER(O.NAME) NOT LIKE ('%DTPROPER%'))
	AND (UPPER(O.NAME) NOT LIKE ('%SYSDIAGRAMS%'))
--	AND (PERMISSIONS(O.ID) <> 0)
UNION
SELECT	T.TABLE_CATALOG AS OBJECT_CATALOG,
	T.TABLE_SCHEMA AS OBJECT_SCHEMA,
	CONVERT(VARCHAR(30), 'INDEX') AS OBJECT_TYPE, -- 'INDEX'.
	TI.NAME AS OBJECT_NAME,
	CONVERT(NUMERIC(15), LEN(TI.NAME)) AS NAME_LENGTH,
	OBJECT_NAME(TI.ID) AS TABLE_NAME,
	SO.CRDATE AS CREATION_DATE,
	CONVERT(VARCHAR(30), CASE WHEN (TI.STATUS < 0) THEN 'INVALID' ELSE 'VALID' END) AS OBJECT_STATUS
FROM	DBO.SYSINDEXES TI
	INNER JOIN EVI_TABLES T ON (OBJECT_NAME(TI.ID) = T.TABLE_NAME)
	INNER JOIN DBO.SYSOBJECTS SO ON (T.TABLE_NAME = SO.NAME)
WHERE	(TI.STATUS >= 0)
	AND (LEFT(TI.NAME, 1) <> '_')
	AND (TI.INDID <> 255)
--	AND (PERMISSIONS(TI.ID) <> 0)
	AND NOT EXISTS (
	SELECT	1
	FROM	DBO.SYSOBJECTS O
	WHERE	(O.NAME = TI.NAME)
	)
UNION
SELECT	S.SEQUENCE_CATALOG AS OBJECT_CATALOG,
	S.SEQUENCE_SCHEMA AS OBJECT_SCHEMA,
	CONVERT(VARCHAR(30), 'SEQUENCE') AS OBJECT_TYPE, -- 'SEQUENCE'.
	S.SEQUENCE_NAME AS OBJECT_NAME,
	CONVERT(NUMERIC(15), LEN(S.SEQUENCE_NAME)) AS NAME_LENGTH,
	S.TABLE_NAME,
	SO.CRDATE AS CREATION_DATE,
	CONVERT(VARCHAR(30), CASE WHEN (SO.STATUS < 0) THEN 'INVALID' ELSE 'VALID' END) AS OBJECT_STATUS
FROM	EVI_SEQUENCES S
	INNER JOIN DBO.SYSOBJECTS SO ON (S.TABLE_NAME = SO.NAME)
WHERE	NOT EXISTS (
	SELECT	1
	FROM	DBO.SYSOBJECTS O
	WHERE	(O.NAME = S.SEQUENCE_NAME)
	)
) T1
-- WHERE	-- (T1.OBJECT_TYPE IN ('CHECK', 'DEFAULT', 'FOREIGN KEY', 'INDEX', 'PRIMARY KEY', 'UNIQUE'))
--	(T1.NAME_LENGTH > 30)
ORDER BY 1 ASC, 2 ASC, 3 ASC, 4 ASC
 
