CREATE VIEW [dbo].[VW_SYS_PROCESS_ATTACH_QTY] AS
-- LISTA LA CANTIDAD DE ADJUNTOS POR CADA PROCESO O CLIENTE.
SELECT	-- TOP 100 PERCENT
	AD.PAR_KEY,
	COUNT(1) AS ATTACH_COUNT
FROM	PHYSICAL_ATTACHED_DOCUMENT AD
GROUP BY AD.PAR_KEY
-- ORDER BY AD.PAR_KEY ASC
 
