 
 
 
 
 
CREATE VIEW [dbo].[VW_PROVEEDORES] AS
 
 
SELECT	TOP 1000 P.ID_PROVEEDOR		AS CAT_DATA_CODE, 
		P.RAZON_SOCIAL_PROV	AS CAT_DATA_DESC, 
		P.ID_PROVEEDOR		AS PKEY, 
		CD.CAT_DATA_CODE	AS PARENT_CAT_DATA_CODE, 
		CD.CAT_DATA_CODE	AS PARENT_CAT_DATA_PKEY
FROM    LK_PROVEEDORES P 
		INNER JOIN CAT_DATA CD ON P.TIPO_PROV = CD.CAT_DATA_CODE AND CD.PAR_KEY = (SELECT PKEY FROM CAT_TYPE WHERE CAT_TYPE_CODE = 'TIPO_PROVEEDOR')
WHERE	P.STATUS_PROV = '1'
UNION ALL
SELECT	9999				AS CAT_DATA_CODE, 
		'Otros'				AS CAT_DATA_DESC, 
		9999				AS PKEY, 
		CD.CAT_DATA_CODE	AS PARENT_CAT_DATA_CODE, 
		CD.CAT_DATA_CODE	AS PARENT_CAT_DATA_PKEY
FROM    CAT_DATA CD  
WHERE	CD.PAR_KEY = (SELECT PKEY FROM CAT_TYPE WHERE CAT_TYPE_CODE = 'TIPO_PROVEEDOR')
AND		CD.CAT_DATA_CODE <> 'AUTO'
 
