CREATE VIEW [dbo].[VW_SYS_PROCESOS_PEND_INBOX] AS
-- LISTA LA CANTIDAD DE PROCESOS PROGRAMADOS CON UNA ACTIVIDAD ABIERTA QUE ESTÁN PENDIENTES EN LA INBOX PARA CADA CLIENTE.
SELECT	PJ.PKEY_CUSTOMER,
	COUNT(1) AS PENDING_COUNT
FROM	ATTENDED_CUSTOMER AC
	INNER JOIN CALL_TYPE CT ON (AC.CALL_TYPE_CODE = CT.CALL_TYPE_CODE)
	INNER JOIN PHYSICAL_JOB PJ ON (AC.PKEY_JOB = PJ.PKEY)
	INNER JOIN JOB_TYPE JT ON (PJ.JOB_TYPE_CODE = JT.JOB_TYPE_CODE)
	INNER JOIN CUSTOMER_TYPE CU ON (JT.CUST_TYPE_CODE = CU.CUST_TYPE_CODE)
WHERE	(AC.ATT_STATE_CODE = 'Abierto' OR AC.ATT_STATE_CODE = 'NOTWORKED')
	AND (AC.PKEY_CAMPAIGN = 'NO APLICA' OR AC.PKEY_CAMPAIGN = ' ')
	AND (JT.JOB_TYPE_CODE <> CU.HISTORY_JOB_CODE)
	AND (CT.CALL_READY_IDR = '1')
	AND (CT.MEDIA_TYPE = 'AGENT')
GROUP BY PJ.PKEY_CUSTOMER
 
