 
CREATE FUNCTION [dbo].[FN_GET_AGENDA_HORAS_CONSULTOR] (@IAGENDA INT, @ICONSULTOR INT, @IFECHA VARCHAR(50))
RETURNS VARCHAR(400)
AS BEGIN
    DECLARE @VHORAS VARCHAR(50)
 
    SELECT	@VHORAS = NULLIF(ISNULL(SUM(HORAS),'0'),'0')
	FROM	LK_AGENDA_EMPLEADO
	WHERE	HOLIDAYTEXT = CONVERT(VARCHAR,@IAGENDA)
	AND		ID_EMPLEADO = @ICONSULTOR
	AND		FECHA = CASE WHEN ISNULL(@IFECHA,'') = '' THEN FECHA ELSE @IFECHA END
	
    RETURN ISNULL(@VHORAS,'0')
END
