 
CREATE FUNCTION [dbo].[FN_GET_CALIFICACION] (@ICONSULTOR VARCHAR(50), @INORMA INT, @ISERVICIO VARCHAR(50))
RETURNS VARCHAR(50)
AS BEGIN
    DECLARE @VALOR		VARCHAR(400)
 
	SELECT	@VALOR = ISNULL(CALIFICACION,'NA')
	FROM	LK_EMPLEADOS_APTITUD
	WHERE	ID_EMPLEADO = @ICONSULTOR
	AND		ID_APTITUD = @INORMA
	AND		ID_TIPO = @ISERVICIO
 
	RETURN ISNULL(@VALOR,'NA')
 
END
