 
CREATE FUNCTION [dbo].[FN_GET_OBLIGA_MINUTA_GESTION] (@IPROYECTO INT)
RETURNS VARCHAR(50)
AS BEGIN
    DECLARE @VEXISTE INT,
			@VCANT	 INT,
			@VOBLIGA VARCHAR(50),
			@VID_MINUTA VARCHAR(50)
	
	SET @VEXISTE = 0
	SET @VCANT = 0
	SET @VOBLIGA = 'NO'
	
	--ME FIJO SI TIENE GENERADA UN MINUTA DE GESTION--
	SELECT	@VID_MINUTA = ISNULL(ID_PROYECTO_DOCUM,'') 
	FROM	LK_PROYECTO_DOCUM 
	WHERE	ID_PROYECTO = @IPROYECTO 
	AND		TIPO = 'MG'
 
	IF (@VID_MINUTA <> '') BEGIN
		SELECT	@VCANT = COUNT(1 )
		FROM	LK_PROYECTO_DOCUM_DET 
		WHERE	ID_PROYECTO_DOCUM = @VID_MINUTA
		AND		ISNULL(OBLIGATORIO_DOC_DET,'') = 'SI'
		AND		ISNULL(VALOR_DOC_DET,'') = ''
 
		IF (@VCANT > 0) BEGIN
			SET @VOBLIGA = 'SI'
		END
	END
				
    RETURN @VOBLIGA
 
END
