 
CREATE FUNCTION [dbo].[FN_GET_DIAS_DISP_ANUAL] (@ICONSULTOR INT, @IANO INT)
RETURNS INT
AS BEGIN
    DECLARE @VTOTAL		INT,
		@VDIAS		INT,
		@VMES		INT,
		@VFECHA_ALTA VARCHAR(10),--MESAÑO
		@VANO_ALTA	INT
 
	
	SET @VTOTAL = 0
 
	--si el año seleccionado en pantalla es igual al año del alta del consultor, tomar mes de alta y sacar anual desde el mes de alta hasta fin de año
 
	SELECT	@VFECHA_ALTA = CONVERT(VARCHAR,FORMAT(CONVERT(INT,DATEPART(MM, FECHA_ALTA)),'00')) + CONVERT(VARCHAR,CONVERT(INT,DATEPART(YYYY, FECHA_ALTA))), 
			@VANO_ALTA = CONVERT(INT,DATEPART(YYYY, FECHA_ALTA))
	FROM	LK_EMPLEADOS
	WHERE	ID_EMPLEADO = @ICONSULTOR
 
	IF (@IANO = @VANO_ALTA) BEGIN
 
		DECLARE Anual CURSOR FOR 
			SELECT	DISTINCT Mes
			FROM	Calendar
			WHERE	MesAno >= @VFECHA_ALTA
	
	END ELSE BEGIN
		
		DECLARE Anual CURSOR FOR 
			SELECT	DISTINCT Mes
			FROM	Calendar
 
	END
			
	OPEN Anual  
	FETCH NEXT FROM Anual INTO @VMES
 
	WHILE @@FETCH_STATUS = 0  
	BEGIN  
		
		SELECT	@VDIAS = [dbo].[FN_GET_DIAS_DISPONIBLES] (@ICONSULTOR, @VMES, @IANO)
 
		SET @VTOTAL = @VTOTAL + @VDIAS
					
		FETCH NEXT FROM Anual INTO @VMES
	END 
 
	CLOSE Anual  
	DEALLOCATE Anual
				
    RETURN @VTOTAL
 
END
