 
CREATE FUNCTION [dbo].[FN_GET_AGENDA_ESTADO] (@IAGENDA INT)
RETURNS VARCHAR(400)
AS BEGIN
    DECLARE @VESTADO VARCHAR(50)
 
    SELECT	@VESTADO = NULLIF(ISNULL(ESTADO,'S'),'S')
	FROM	LK_AGENDA A
	WHERE	ID_AGENDA = @IAGENDA
 
	IF (@VESTADO = '') BEGIN
		SET @VESTADO = 'S'
	END
 
    RETURN ISNULL(@VESTADO,'S')
END
