 
/* Estado de los 3 pasos del lanzamiento. */
CREATE   FUNCTION dbo.VCT_PROYECTO_LANZ_ESTADO (@ID_PROYECTO INT)
RETURNS TABLE
AS
RETURN
(
    SELECT
        E.CODIGO AS ESTADO_CODIGO,
        E.DESCRIPCION AS ESTADO,
        (SELECT COUNT(*) FROM dbo.VCT_PROYECTOS_EQUIPO EQ
          INNER JOIN dbo.VCT_PRM_PROYECTOS_ROLES R ON R.ID = EQ.ID_ROL
          WHERE EQ.ID_PROYECTO = P.ID AND EQ.TIPO_MIEMBRO = 'CONSULTOR' AND EQ.ESTADO = 'ACTIVO'
            AND R.CODIGO = 'CONSULTOR_LIDER') AS LIDERES,
        (SELECT COUNT(*) FROM dbo.VCT_PROYECTOS_EQUIPO EQ
          WHERE EQ.ID_PROYECTO = P.ID AND EQ.TIPO_MIEMBRO = 'CONSULTOR' AND EQ.ESTADO = 'ACTIVO') AS CONSULTORES,
        (SELECT COUNT(*) FROM dbo.VCT_PROYECTO_MINUTAS(P.ID) M WHERE M.ITEMS_OK > 0) AS DATOS_CARGADOS,
        (SELECT COUNT(*) FROM dbo.VCT_PROYECTOS_DOCUMENTOS D
          INNER JOIN dbo.VCT_PROYECTOS_DOCUMENTOS_ITEMS I ON I.ID_PROYECTO_DOCUMENTO = D.ID
          WHERE D.ID_PROYECTO = P.ID AND D.TIPO = 'CONS' AND I.CAMPO = 'CONSIDERACION') AS CONSIDERACIONES,
        CASE WHEN EXISTS (SELECT 1 FROM dbo.VCT_GESTIONES G
                           INNER JOIN dbo.VCT_PRM_GESTIONES_SUBTIPOS ST ON ST.ID = G.ID_SUBTIPO
                           INNER JOIN dbo.VCT_PRM_GESTIONES_ESTADOS GE ON GE.ID = G.ID_ESTADO
                           WHERE G.ID_PROYECTO = P.ID AND ST.CODIGO = 'ASIGNACION_ANALISTA' AND GE.CODIGO = 'CUMPLIDA')
             THEN 1 ELSE 0 END AS REUNION_OK
    FROM dbo.VCT_PROYECTOS P
    LEFT JOIN dbo.VCT_PRM_PROYECTOS_ESTADOS E ON E.ID = P.ID_ESTADO
    WHERE P.ID = @ID_PROYECTO
)
