CREATE   FUNCTION dbo.VCT_PERFIL_PUEDE
(
    @IUNIDAD   VARCHAR(100),   -- perfil (Groups.Id), el mismo @IUNIDAD de los SP de MAIN
    @ACTION_ID VARCHAR(150)    -- ej. 'RENTABILIDAD.VIEW'
)
RETURNS BIT
AS
BEGIN
    RETURN CASE WHEN EXISTS
    (
        SELECT 1
        FROM dbo.GroupsActions GA WITH (NOLOCK)
        WHERE UPPER(LTRIM(RTRIM(GA.GroupId))) = UPPER(LTRIM(RTRIM(@IUNIDAD)))
          AND UPPER(LTRIM(RTRIM(GA.ActionId))) = UPPER(LTRIM(RTRIM(@ACTION_ID)))
    ) THEN 1 ELSE 0 END;
END
