 
CREATE FUNCTION [dbo].[FN_GET_AGENDA_PROYECTO] (@IAGENDA INT)
RETURNS VARCHAR(400)
AS BEGIN
    DECLARE @VPROYECTO VARCHAR(400)
 
    SELECT	@VPROYECTO = '('+CODIGO+') - '+P.NORMA_REF
	FROM	LK_AGENDA A
			INNER JOIN LK_PROYECTO P ON A.ID_PROYECTO = P.ID_PROYECTO
	WHERE	ID_AGENDA = @IAGENDA
 
    RETURN isnull(@VPROYECTO,'')
END
