 
 
CREATE FUNCTION [dbo].[FN_GET_AGENDA_CONSULTOR_DESC] (@IFECHA DATE, @ICONSULTOR INT)
RETURNS VARCHAR(400)
AS BEGIN
    DECLARE @VDESC VARCHAR(400)
 
    SELECT	@VDESC = NULLIF(ISNULL(DESCRIPCION,''),'')
	FROM	LK_AGENDA_EMPLEADO A
	WHERE	ID_EMPLEADO = @ICONSULTOR
	AND		FECHA = @IFECHA
 
    RETURN ISNULL(@VDESC,'')
END
