 
CREATE FUNCTION [dbo].[FN_GET_AGENDA_CLIENTE] (@IAGENDA INT)
RETURNS VARCHAR(400)
AS BEGIN
    DECLARE @VCLIENTE VARCHAR(400)
 
    SELECT	@VCLIENTE = ISNULL(RAZON_SOCIAL_CLIENTE,'')
	FROM	LK_AGENDA A
			INNER JOIN LK_CLIENTES C ON A.ID_CLIENTE = C.ID_CLIENTE
	WHERE	ID_AGENDA = @IAGENDA
 
    RETURN isnull(@VCLIENTE,'')
END
