 
/* ---------------- 4. horas usadas por consultor ---------------- */
/* Registrada: el consultor del registro. Historica: cada consultor de la
   visita con sus horas (o la parte proporcional si no tiene). */
CREATE   FUNCTION dbo.VCT_PROYECTO_VISITAS_HORAS_CONS (@ID_PROYECTO INT)
RETURNS TABLE
AS
RETURN
    SELECT Z.ID_CONSULTOR, CONVERT(DECIMAL(12,2), SUM(Z.H)) AS HORAS, COUNT(DISTINCT Z.ID_VISITA) AS VISITAS
    FROM
    (
        SELECT C.ID AS ID_VISITA, C.R_CONSULTOR AS ID_CONSULTOR, C.R_HORAS AS H
        FROM dbo.VCT_PROYECTO_VISITAS_CALC(@ID_PROYECTO) C
        WHERE C.ESTADO_CALC = 'REGISTRADA'
        UNION ALL
        SELECT C.ID, VC.ID_CONSULTOR, ISNULL(VC.HORAS_EJECUTADAS, C.HORAS_VISITA / ISNULL(NULLIF(N.N, 0), 1))
        FROM dbo.VCT_PROYECTO_VISITAS_CALC(@ID_PROYECTO) C
        OUTER APPLY (SELECT COUNT(*) AS N FROM dbo.VCT_PROYECTOS_VISITAS_CONSULTORES Q WHERE Q.ID_VISITA = C.ID) N
        LEFT JOIN dbo.VCT_PROYECTOS_VISITAS_CONSULTORES VC ON VC.ID_VISITA = C.ID
        WHERE C.ESTADO_CALC = 'REALIZADA'
    ) Z
    GROUP BY Z.ID_CONSULTOR;
