 
CREATE FUNCTION [dbo].[FN_GET_OBLIGA_ANEXO_MINUTA] (@IANEXO INT)
RETURNS VARCHAR(50)
AS BEGIN
    DECLARE @VEXISTE INT,
			@VCANT	 INT,
			@VOBLIGA VARCHAR(50)
	
	SET @VEXISTE = 0
	SET @VCANT = 0
	SET @VOBLIGA = 'NO'
 
	SELECT	@VCANT = COUNT(1 )
	FROM	LK_PROYECTO_DOCUM_DET 
	WHERE	ID_PROYECTO_DOCUM = @IANEXO
	AND		ISNULL(OBLIGATORIO_DOC_DET,'') = 'SI'
	AND		ISNULL(VALOR_DOC_DET,'') = ''
 
	IF (@VCANT > 0) BEGIN
		SET @VOBLIGA = 'SI'
	END
				
    RETURN @VOBLIGA
 
END
