 
CREATE FUNCTION [dbo].[FN_GET_DIAS_DISP_ANUAL_BK] (@ICONSULTOR INT, @IANO INT)
RETURNS INT
AS BEGIN
    DECLARE @VTOTAL		INT,
		@VDIAS		INT,
		@VMES		INT
	
	SET @VTOTAL = 0
 
	DECLARE Anual CURSOR FOR 
		SELECT	DISTINCT Mes
		FROM	Calendar
		WHERE	ANO = @IANO
			
	OPEN Anual  
	FETCH NEXT FROM Anual INTO @VMES
 
	WHILE @@FETCH_STATUS = 0  
	BEGIN  
		
		SELECT	@VDIAS = [dbo].[FN_GET_DIAS_DISPONIBLES] (@ICONSULTOR, @VMES, @IANO)
 
		SET @VTOTAL = @VTOTAL + @VDIAS
					
		FETCH NEXT FROM Anual INTO @VMES
	END 
 
	CLOSE Anual  
	DEALLOCATE Anual
				
    RETURN @VTOTAL
 
END
