CREATE FUNCTION [dbo].[FN_GET_STATUS_AGENDA] (@IDAGENDA INT)
RETURNS VARCHAR(400)
AS BEGIN
    DECLARE @VSTATUS	VARCHAR(50),
			@VCONSULTOR VARCHAR(50),
			@VCANT		INT
	
	--SET @VCANT = 0
 
	SELECT	@VCONSULTOR = ISNULL(ID_CONSULTOR,'')
	FROM	LK_AGENDA 
	WHERE	ID_AGENDA = @IDAGENDA
 
	IF (@VCONSULTOR = '') BEGIN
		SET @VSTATUS = 'R'
 
	END ELSE BEGIN
		
		SELECT	@VCANT = COUNT(1)
		FROM	LK_AGENDA A
				INNER JOIN LK_PROYECTO_DOCUM DOC ON DOC.ID_AGENDA = A.ID_AGENDA
				INNER JOIN LK_PROYECTO_DOCUM_DET DET ON DET.ID_PROYECTO_DOCUM = DOC.ID_PROYECTO_DOCUM
		WHERE	A.ID_AGENDA = @IDAGENDA
		AND		DOC.ID_DOCUMENTACION =	CASE WHEN ID_SERVICIO = '1' THEN '7'
												WHEN ID_SERVICIO = '2' THEN '5'
												WHEN ID_SERVICIO = '3' THEN '6'
										END
		--AND		GRUPO_DOC_DET = 'LOGISTICO'
		AND		ISNULL(DET.VALOR_DOC_DET,'') = ''
 
		IF  @VCANT = 0 BEGIN
			SET  @VSTATUS = 'V'
		
		END ELSE BEGIN
 
			SELECT	TOP 1 @VSTATUS = CASE	WHEN GRUPO_DOC_DET = 'LOGISTICO' THEN 'N'
											WHEN GRUPO_DOC_DET = 'TECNICO' THEN 'A'
											WHEN GRUPO_DOC_DET = 'ADMINISTRACION' THEN 'C'
									END
			FROM	LK_AGENDA A
					INNER JOIN LK_PROYECTO_DOCUM DOC ON DOC.ID_AGENDA = A.ID_AGENDA
					INNER JOIN LK_PROYECTO_DOCUM_DET DET ON DET.ID_PROYECTO_DOCUM = DOC.ID_PROYECTO_DOCUM
			WHERE	A.ID_AGENDA = @IDAGENDA
			AND		DOC.ID_DOCUMENTACION =	CASE WHEN ID_SERVICIO = '1' THEN '7'
													WHEN ID_SERVICIO = '2' THEN '5'
													WHEN ID_SERVICIO = '3' THEN '6'
											END
			--AND		GRUPO_DOC_DET = 'LOGISTICO'
			AND		ISNULL(DET.VALOR_DOC_DET,'') = ''
			ORDER BY ID_PROYECTO_DOCUM_DET
		END
 
		/*SELECT	@VCANT = COUNT(*)
		FROM	LK_AGENDA A
				INNER JOIN LK_PROYECTO_DOCUM DOC ON DOC.ID_AGENDA = A.ID_AGENDA
				INNER JOIN LK_PROYECTO_DOCUM_DET DET ON DET.ID_PROYECTO_DOCUM = DOC.ID_PROYECTO_DOCUM
		WHERE	A.ID_AGENDA = @IDAGENDA
		AND		DOC.ID_DOCUMENTACION =	CASE WHEN ID_SERVICIO = '1' THEN '7'
											 WHEN ID_SERVICIO = '2' THEN '5'
											 WHEN ID_SERVICIO = '3' THEN '6'
										END
		AND		GRUPO_DOC_DET = 'LOGISTICO'
		AND		ISNULL(DET.VALOR_DOC_DET,'') = ''
 
		IF (@VCANT > 0) BEGIN
			SET  @VSTATUS = 'N'
		
		END ELSE BEGIN
			SELECT	@VCANT = COUNT(*)
			FROM	LK_AGENDA A
					INNER JOIN LK_PROYECTO_DOCUM DOC ON DOC.ID_AGENDA = A.ID_AGENDA
					INNER JOIN LK_PROYECTO_DOCUM_DET DET ON DET.ID_PROYECTO_DOCUM = DOC.ID_PROYECTO_DOCUM
			WHERE	A.ID_AGENDA = @IDAGENDA
			AND		DOC.ID_DOCUMENTACION =	CASE WHEN ID_SERVICIO = '1' THEN '7'
												 WHEN ID_SERVICIO = '2' THEN '5'
												 WHEN ID_SERVICIO = '3' THEN '6'
											END
			AND		GRUPO_DOC_DET = 'TECNICO'
			AND		ISNULL(DET.VALOR_DOC_DET,'') = ''
			
			IF (@VCANT > 0) BEGIN
				SET  @VSTATUS = 'A'
			
			END ELSE BEGIN
								 
				SELECT	@VCANT = COUNT(*)
				FROM	LK_AGENDA A
						INNER JOIN LK_PROYECTO_DOCUM DOC ON DOC.ID_AGENDA = A.ID_AGENDA
						INNER JOIN LK_PROYECTO_DOCUM_DET DET ON DET.ID_PROYECTO_DOCUM = DOC.ID_PROYECTO_DOCUM
				WHERE	A.ID_AGENDA = @IDAGENDA
				AND		DOC.ID_DOCUMENTACION =	CASE WHEN ID_SERVICIO = '1' THEN '7'
													 WHEN ID_SERVICIO = '2' THEN '5'
													 WHEN ID_SERVICIO = '3' THEN '6'
												END
				AND		GRUPO_DOC_DET = 'ADMINISTRACION'
				AND		ISNULL(DET.VALOR_DOC_DET,'') = ''
				
				IF (@VCANT > 0) BEGIN
					SET  @VSTATUS = 'C'
			
				END ELSE BEGIN
					SET  @VSTATUS = 'V'
				END*/
			--END
		--END
	END
 
    RETURN @VSTATUS
END
