 
CREATE FUNCTION [dbo].[FN_GET_SERVICIO_VISITAS] (@ICLIENTE INT, @IPROYECTO INT, @ISERVICIO INT, @IPROYECTOSERV INT)
RETURNS DATETIME
AS BEGIN
    DECLARE @VFECHA	DATETIME
 
	SELECT	@VFECHA = MAX(CONVERT(DATETIME,FECHA))
	FROM	LK_AGENDA
	WHERE	ID_CLIENTE = @ICLIENTE
	AND		ID_PROYECTO = @IPROYECTO
	AND		ID_SERVICIO = @ISERVICIO
	AND		PROYECTO_SERV_ID = @IPROYECTOSERV
				
    RETURN @VFECHA
 
END
