 
CREATE FUNCTION [dbo].[FN_GET_AGENDA_SERVICIO] (@IAGENDA INT)
RETURNS VARCHAR(400)
AS BEGIN
    DECLARE @VSERVICIO VARCHAR(400)
 
    SELECT	@VSERVICIO = DESC_TIPO_SERVICIO
	FROM	LK_AGENDA A
			INNER JOIN LK_TIPO_SERVICIOS T ON A.ID_SERVICIO = T.ID_TIPO_SERVICIO
	WHERE	ID_AGENDA = @IAGENDA
 
    RETURN isnull(@VSERVICIO,'')
END
