 
CREATE FUNCTION [dbo].[FN_GET_DIAS_OCUPADOS] (@ICONSULTOR INT, @IMES INT, @IANO INT)
RETURNS DECIMAL(10,2)
AS BEGIN
    DECLARE @VTOTAL_A	DECIMAL(10,2)
	DECLARE @VTOTAL_P	DECIMAL(10,2)
	DECLARE @VTOTAL	DECIMAL(10,2)
 
	SELECT	@VTOTAL_A = convert(decimal(10,2),(CONVERT(float,SUM(HORAS)) / CONVERT(float,8)))
	FROM	LK_AGENDA_EMPLEADO
	WHERE	ID_EMPLEADO = @ICONSULTOR
	AND		MES = @IMES
	AND		ANO = @IANO
	AND		TIPO IN ('A')
	
	--sumar por empleado los dias potenciales del mes año. tomar 8 horas por default
	SELECT	@VTOTAL_P = COUNT(1)--convert(decimal(10,2),(CONVERT(float,SUM(HORAS)) / CONVERT(float,8)))
	FROM	LK_AGENDA_EMPLEADO
	WHERE	ID_EMPLEADO = @ICONSULTOR
	AND		MES = @IMES
	AND		ANO = @IANO
	AND		TIPO IN ('POT')
 
	--SET @VTOTAL_P = ISNULL(@VTOTAL_P,0.00) * 8
 
	SET  @VTOTAL = ISNULL(@VTOTAL_A,0.00) + ISNULL(@VTOTAL_P,0.00)
			
    RETURN ISNULL(@VTOTAL,0.00)
 
END
 
