CREATE FUNCTION dbo.FN_GET_SERVICIO (@ISERVICIO INT)
RETURNS VARCHAR(400)
AS BEGIN
    DECLARE @VSERVICIO VARCHAR(400)
 
    SELECT	@VSERVICIO = ISNULL(DESC_TIPO_SERVICIO,'')
	FROM	LK_TIPO_SERVICIOS
	WHERE	ID_TIPO_SERVICIO = @ISERVICIO
 
    RETURN @VSERVICIO
END
