 
CREATE FUNCTION [dbo].[FN_GET_CONSULTOR_HORAS] (@ICONSULTOR INT, @IFECHA VARCHAR(50))
RETURNS VARCHAR(400)
AS BEGIN
    DECLARE @VHORAS VARCHAR(50)
 
    SELECT	@VHORAS = NULLIF(ISNULL(SUM(HORAS),'0'),'0')
	FROM	LK_AGENDA_EMPLEADO
	WHERE	ID_EMPLEADO = @ICONSULTOR
	AND		FECHA = @IFECHA
	
    RETURN ISNULL(@VHORAS,'0')
END
						
 
