 
 
CREATE FUNCTION [dbo].[FN_GET_TOTAL_HS_EJEC_PERIODO] (@ID_SERVICIO INT, @FECHA_DESDE DATETIME, @FECHA_HASTA DATETIME)
RETURNS INT
AS BEGIN
 
    DECLARE @VTOTAL VARCHAR(400)
 
	SELECT	@VTOTAL = ISNULL(SUM(HORAS),0)
	FROM	LK_AGENDA_EMPLEADO
	WHERE	HOLIDAYTEXT IN (SELECT	CONVERT(VARCHAR,ID_AGENDA)
							FROM	LK_AGENDA
							WHERE	PROYECTO_SERV_ID = @ID_SERVICIO)
	AND		FECHA >= @FECHA_DESDE
	AND		FECHA <= @FECHA_HASTA
 
	RETURN isnull(@VTOTAL,0)
END
