CREATE FUNCTION dbo.FN_GET_PROYECTO (@IPROYECTO INT)
RETURNS VARCHAR(400)
AS BEGIN
    DECLARE @VPROYECTO VARCHAR(400)
 
    SELECT	@VPROYECTO = ISNULL(NORMA_REF,'')
	FROM	LK_PROYECTO
	WHERE	ID_CLIENTE = @IPROYECTO
 
    RETURN @VPROYECTO
END
