CREATE FUNCTION dbo.FN_GET_CLIENTE (@ICLIENTE INT)
RETURNS VARCHAR(400)
AS BEGIN
    DECLARE @VCLIENTE VARCHAR(400)
 
    SELECT	@VCLIENTE = ISNULL(RAZON_SOCIAL_CLIENTE,'')
	FROM	LK_CLIENTES
	WHERE	ID_CLIENTE = @ICLIENTE
 
    RETURN @VCLIENTE
END
