 
CREATE FUNCTION [dbo].[FN_GET_AGENDA_HORAS] (@IAGENDA INT)
RETURNS VARCHAR(400)
AS BEGIN
    DECLARE @VHORAS VARCHAR(50)
 
    SELECT	@VHORAS = NULLIF(ISNULL(SUM(HORAS),'0'),'0')
	FROM	LK_AGENDA_EMPLEADO
	WHERE	HOLIDAYTEXT = CONVERT(VARCHAR,@IAGENDA)
	
    RETURN ISNULL(@VHORAS,'0')
END
