 
CREATE FUNCTION [dbo].[FN_GET_DIAS_DISPONIBLES] (@ICONSULTOR INT, @IMES INT, @IANO INT)
RETURNS INT
AS BEGIN
    DECLARE @VMIN_MES	INT,
		@VMIN_ANO	INT,
		@VMAX_MES	INT,
		@VMAX_ANO	INT,
		@VDIAS		INT,
		@VMES_HIST	INT, 
		@VDIAS_HIST INT,
		@VEXISTE	VARCHAR(50)
 
		SELECT	@VMIN_MES = MIN(MES), @VMIN_ANO = MIN(ANO), @VMAX_MES = MAX(MES), @VMAX_ANO = MAX(ANO)
		FROM	LK_EMPLEADOS_DIAS
		WHERE	ID_EMPLEADO = @ICONSULTOR
 
		--NO TENGO NINGUN REGISTRO EN EL HISTORICO--
		IF (ISNULL(@VMIN_ANO,'') = '') BEGIN
			SELECT	@VDIAS = DIAS_MENSUALES
			FROM	LK_EMPLEADOS 
			WHERE	ID_EMPLEADO = @ICONSULTOR
		END
 
		--SI EL AÑO ENTRADA ES MENOR QUE EL MINIMO DEL HISTORICO, MUESTRO EL DIA DEL MINIMO--
		IF (@IANO < @VMIN_ANO) BEGIN
			SELECT	@VDIAS = DIAS
			FROM	LK_EMPLEADOS_DIAS
			WHERE	ID_EMPLEADO = @ICONSULTOR
			AND		MES = @VMIN_MES
			AND		ANO = @VMIN_ANO
		END
 
		--SI EL AÑO ENTRADA ES MAYOR QUE EL MINIMO DEL HISTORICO, MUESTRO EL DIA DEL MINIMO--
		IF (@IANO > @VMAX_ANO) BEGIN
			SELECT	@VDIAS = DIAS_MENSUALES
			FROM	LK_EMPLEADOS 
			WHERE	ID_EMPLEADO = @ICONSULTOR
		END
 
		IF (ISNULL(@VDIAS,'') = '') BEGIN
 
			SET @VEXISTE = 'NO'
 
			DECLARE Historico CURSOR FOR 
				SELECT	MES, DIAS
				FROM	LK_EMPLEADOS_DIAS
				WHERE	ID_EMPLEADO = @ICONSULTOR
				AND		ANO = @IANO
				ORDER BY MES, ANO
			
			OPEN Historico  
			FETCH NEXT FROM Historico INTO @VMES_HIST, @VDIAS_HIST
 
			WHILE @@FETCH_STATUS = 0  
			BEGIN  
 
				IF (ISNULL(@VEXISTE,'') = 'NO') BEGIN
					IF (@IMES <= @VMES_HIST) BEGIN
						SET @VDIAS = @VDIAS_HIST
						SET @VEXISTE = 'SI'
					END
				END
					
				FETCH NEXT FROM Historico INTO @VMES_HIST, @VDIAS_HIST
			END 
 
			CLOSE Historico  
			DEALLOCATE Historico
 
			IF (ISNULL(@VDIAS,'') = '') BEGIN
 
				SELECT	@VDIAS = DIAS_MENSUALES
				FROM	LK_EMPLEADOS 
				WHERE	ID_EMPLEADO = @ICONSULTOR
 
			END
		END
				
    RETURN @VDIAS
 
END
