 
 
CREATE FUNCTION [dbo].[FN_GET_TOTAL_HS_EJECUTADAS] (@TIPO VARCHAR(50), @ID_PROYECTO INT, @TIPO_SERVICIO INT, @ID_SERVICIO INT)
RETURNS VARCHAR(400)
AS BEGIN
 
    DECLARE @VTOTAL VARCHAR(400)
 
	--devuelve el total de horas ejecutadas de un proyecto--
	--TIPO = P, ID_PROYECTO = xx, TIPO_SERVICIO = NULL, ID_SERVICIO = NULL
	IF (@TIPO = 'P') BEGIN
 
		SELECT	@VTOTAL = ISNULL(SUM(HORAS),0)
		FROM	LK_AGENDA_EMPLEADO
		WHERE	TIPO = 'A'
		AND		HOLIDAYTEXT IN (SELECT	CONVERT(VARCHAR,ID_AGENDA)
								FROM	LK_AGENDA
								WHERE	ID_PROYECTO = @ID_PROYECTO)
 
	END
	
	--devuelve el total de horas ejecutadas de un tipo de servicio del proyecto--
	--TIPO = S, ID_PROYECTO = xx, TIPO_SERVICIO = 1/2/3, ID_SERVICIO = NULL
	IF (@TIPO = 'S') BEGIN
		
		SELECT	@VTOTAL = ISNULL(SUM(HORAS),0)
		FROM	LK_AGENDA_EMPLEADO
		WHERE	TIPO = 'A'
		AND		HOLIDAYTEXT IN (SELECT	CONVERT(VARCHAR,ID_AGENDA)
								FROM	LK_AGENDA
								WHERE	ID_PROYECTO = @ID_PROYECTO
								AND		ID_SERVICIO = @TIPO_SERVICIO)
	END
 
	--devuelve el total de horas ejecutadas de un servicio especifico del proyecto--
	--TIPO = PS, ID_PROYECTO = NULL, TIPO_SERVICIO = NULL, ID_SERVICIO = xx
	IF (@TIPO = 'PS') BEGIN
		
		SELECT	@VTOTAL = ISNULL(SUM(HORAS),0)
		FROM	LK_AGENDA_EMPLEADO
		WHERE	TIPO = 'A'
		AND		HOLIDAYTEXT IN (SELECT	CONVERT(VARCHAR,ID_AGENDA)
								FROM	LK_AGENDA
								WHERE	PROYECTO_SERV_ID = @ID_SERVICIO)
 
	END
 
	RETURN isnull(@VTOTAL,'')
END
