 
CREATE FUNCTION [dbo].[FN_GET_CONSULTOR_HORAS_DISP] (@ICONSULTOR INT, @IFECHA VARCHAR(50))
RETURNS VARCHAR(400)
AS BEGIN
    DECLARE @VHORAS_DISP VARCHAR(50)
 
    SELECT	TOP 1 @VHORAS_DISP = ISNULL(HORAS_DISP,0)
	FROM	LK_AGENDA_EMPLEADO
	WHERE	ID_EMPLEADO = @ICONSULTOR
	AND		FECHA = @IFECHA
	
    RETURN ISNULL(@VHORAS_DISP,'0')
END
						
 
