 
/* ---------------- 3. visitas del proyecto ---------------- */
CREATE   FUNCTION dbo.VCT_PROYECTO_VISITAS_CALC (@ID_PROYECTO INT)
RETURNS TABLE
AS
RETURN
    SELECT V.ID, V.FECHA_DESDE, V.FECHA_HASTA, V.DIAS, V.LUGAR, V.OBSERVADOR, V.ESTADO,
           CONVERT(DECIMAL(9,2), ISNULL(V.TOTAL_HORAS_EJECUTADAS, 0)) AS HORAS_VISITA,
           R.ID AS ID_REG, R.FECHA AS R_FECHA, R.HORA_DESDE, R.HORA_HASTA, R.HORAS AS R_HORAS,
           R.ID_CONSULTOR AS R_CONSULTOR, R.MODALIDAD AS R_MODALIDAD, R.LUGAR AS R_LUGAR,
           R.TEMAS_TRABAJADOS, R.PROXIMOS_TEMAS, R.ACCIONES_CLIENTE, R.ID_GESTION_PENDIENTE,
           ISNULL(R.USUARIO_UPD, R.USUARIO_ALTA) AS R_USUARIO, ISNULL(R.FECHA_UPD, R.FECHA_ALTA) AS R_FECHA_ALTA,
           X.ESTADO_CALC,
           CONVERT(DATE, ISNULL(CONVERT(DATETIME, R.FECHA), V.FECHA_DESDE)) AS FECHA,
           CONVERT(DECIMAL(9,2), CASE X.ESTADO_CALC WHEN 'REGISTRADA' THEN R.HORAS
                                                    WHEN 'REALIZADA' THEN ISNULL(V.TOTAL_HORAS_EJECUTADAS, 0)
                                                    ELSE 0 END) AS HORAS_USADAS,
           CONVERT(DECIMAL(9,2), CASE WHEN X.ESTADO_CALC = 'AGENDADA' THEN ISNULL(V.TOTAL_HORAS_EJECUTADAS, 0) ELSE 0 END) AS HORAS_AGENDADAS
    FROM dbo.VCT_PROYECTOS_VISITAS V
    LEFT JOIN dbo.VCT_PROYECTOS_VISITAS_REGISTRO R ON R.ID_VISITA = V.ID
    CROSS APPLY
    (
        SELECT CASE WHEN R.ID IS NOT NULL THEN 'REGISTRADA'
                    WHEN CONVERT(DATE, V.FECHA_DESDE) > CONVERT(DATE, GETDATE()) THEN 'AGENDADA'
                    WHEN UPPER(LTRIM(RTRIM(ISNULL(V.ESTADO, '')))) = 'CONFIRMADO' THEN 'REALIZADA'
                    ELSE 'SIN_CONFIRMAR' END AS ESTADO_CALC
    ) X
    WHERE V.ID_PROYECTO = @ID_PROYECTO;
