 
CREATE FUNCTION [dbo].[FN_GET_SERVICIO_DIAS] (@ICLIENTE INT, @IPROYECTO INT, @ISERVICIO INT, @IPROYECTOSERV INT)
RETURNS INT
AS BEGIN
    DECLARE @VTOTAL	INT,
			@VID_AGENDA	INT,
			@VDIAS	INT,
			@VCONSULTORES INT
 
	SET @VTOTAL = 0
 
	DECLARE Agendas CURSOR FOR 
		SELECT	ID_AGENDA, DIAS
		FROM	LK_AGENDA
		WHERE	ID_CLIENTE = @ICLIENTE
		AND		ID_PROYECTO = @IPROYECTO
		AND		ID_SERVICIO = @ISERVICIO
		AND		PROYECTO_SERV_ID = @IPROYECTOSERV
			
	OPEN Agendas  
	FETCH NEXT FROM Agendas INTO @VID_AGENDA, @VDIAS
 
	WHILE @@FETCH_STATUS = 0  
	BEGIN  
		
		SELECT	@VCONSULTORES = COUNT(DISTINCT ID_EMPLEADO)
		FROM	LK_AGENDA_EMPLEADO
		WHERE	HOLIDAYTEXT = CONVERT(VARCHAR,@VID_AGENDA)
 
		SET @VTOTAL = @VTOTAL + (@VDIAS * @VCONSULTORES)
 
		FETCH NEXT FROM Agendas INTO @VID_AGENDA, @VDIAS
	END 
 
	CLOSE Agendas  
	DEALLOCATE Agendas
				
    RETURN @VTOTAL
 
END
