CREATE FUNCTION [dbo].[FN_GET_DOC_VISITA] (@IAGENDA INT, @VTIPO VARCHAR(50))
RETURNS VARCHAR(400)
AS BEGIN
    DECLARE @VFECHA		VARCHAR(50)
 
    SELECT	@VFECHA = ISNULL(CONVERT(VARCHAR,FECHA_DOCUM,103),'')
	FROM	LK_PROYECTO_DOCUM
	WHERE	CASE WHEN @VTIPO = 'MV' THEN ID_AGENDA ELSE PROYECTO_SERV_ID END = @IAGENDA
	AND		TIPO = @VTIPO
 
    RETURN @VFECHA
END
