 
CREATE FUNCTION [dbo].[FN_GET_DIAS_COMP_ANUAL] (@ICONSULTOR INT, @IANO INT)
RETURNS DECIMAL(10,2)
AS BEGIN
    DECLARE @VTOTAL_HORAS_DISP INT
	DECLARE @VTOTAL_HORAS_AGENDA INT
	DECLARE @VTOTAL_HORAS INT
	DECLARE @VTOTAL DECIMAL(10,2)
 
	--dias comprometidos = dias Disp y Agendados del consultor -->> sumar horas disponibles + horas agenda y dividir por 8
	--recupero directamente la suma de horas disponibles, si estan agendadas nunca supera el total de horas disponibles por dia
 
	/*
	SELECT	@VTOTAL_HORAS_DISP = ISNULL(SUM(HORAS_DISP),0)
	FROM	LK_AGENDA_EMPLEADO
	WHERE	ID_EMPLEADO = @ICONSULTOR
	AND		ANO = @IANO
	AND		TIPO = 'D'
 
	SELECT	@VTOTAL_HORAS_AGENDA = ISNULL(SUM(HORAS),0)
	FROM	LK_AGENDA_EMPLEADO
	WHERE	ID_EMPLEADO = @ICONSULTOR
	AND		ANO = @IANO
	AND		TIPO = 'A'*/
 
	SELECT	@VTOTAL_HORAS = ISNULL(SUM(HORAS_DISP),0)
	FROM	LK_AGENDA_EMPLEADO
	WHERE	ID_EMPLEADO = @ICONSULTOR
	AND		ANO = @IANO
	AND		TIPO IN ('A','D')
	
	SET @VTOTAL = CASE WHEN @VTOTAL_HORAS = 0 THEN 0 ELSE convert(decimal(10,2),(CONVERT(float,@VTOTAL_HORAS)) / CONVERT(float,8)) END
 
    RETURN ISNULL(@VTOTAL,0.00)
 
END
