CREATE FUNCTION [dbo].[FN_GET_NORMA] (@ISTRING VARCHAR(400), @INORMA INT)
RETURNS VARCHAR(50)
AS BEGIN
    DECLARE @VNORMAS	VARCHAR(4000),
			@VALOR		VARCHAR(400),
			@RESULTADO	INT,
			@N			INT,
			@VEXISTE	VARCHAR(50)
 
	SET	@VNORMAS = ISNULL(@ISTRING,'')
 
	SET @N = 0
			
	WHILE PATINDEX('%|%',@VNORMAS)>0
	BEGIN
		SET @RESULTADO = PATINDEX('%|%',@VNORMAS) --+ @N
		SET  @VALOR = SUBSTRING(@VNORMAS,1, @RESULTADO-1)
						
			IF (@VALOR = CONVERT(VARCHAR,@INORMA)) BEGIN
				SET  @VEXISTE = 'SI'
			END
 
		SELECT @VNORMAS = RIGHT(@VNORMAS,LEN(@VNORMAS)-PATINDEX('%|%',@VNORMAS))
	END
 
	RETURN ISNULL(@VEXISTE,'NO')
 
END
