 
/* ---------------- 2. calculo de items ---------------- */
CREATE   FUNCTION dbo.VCT_PROYECTO_PLAN_CALC (@ID_PROYECTO INT)
RETURNS TABLE
AS
RETURN
(
    SELECT
        I.ID, I.ID_PLAN, I.ID_PADRE, I.ID_DOCUMENTO_ITEM, I.CODIGO_ITEM, I.TITULO, I.DESCRIPCION,
        I.VALOR AS RESPONSABLES, ISNULL(I.ORDEN, 0) AS ORDEN, I.OBSERVACIONES,
        I.FECHA_INICIO, I.FECHA_VENCIMIENTO, I.FECHA_CIERRE,
        ISNULL(G.TOTAL, 0) AS G_TOTAL,
        ISNULL(G.CUMPLIDAS, 0) AS G_CUMPLIDAS,
        CASE WHEN ISNULL(G.TOTAL, 0) > 0 THEN (ISNULL(G.CUMPLIDAS, 0) * 100) / G.TOTAL
             WHEN I.FECHA_CIERRE IS NOT NULL THEN 100
             ELSE 0 END AS AVANCE,
        CASE WHEN I.FECHA_CIERRE IS NOT NULL THEN 100
             WHEN I.FECHA_INICIO IS NULL OR I.FECHA_VENCIMIENTO IS NULL THEN 0
             WHEN CONVERT(DATE, I.FECHA_INICIO) > T.HOY THEN 0
             WHEN CONVERT(DATE, I.FECHA_VENCIMIENTO) <= CONVERT(DATE, I.FECHA_INICIO) THEN 100
             WHEN T.HOY >= CONVERT(DATE, I.FECHA_VENCIMIENTO) THEN 100
             ELSE (DATEDIFF(DAY, CONVERT(DATE, I.FECHA_INICIO), T.HOY) * 100)
                  / DATEDIFF(DAY, CONVERT(DATE, I.FECHA_INICIO), CONVERT(DATE, I.FECHA_VENCIMIENTO)) END AS TIEMPO,
        CASE WHEN I.FECHA_CIERRE IS NOT NULL THEN 'CUMPLIDO'
             WHEN I.FECHA_VENCIMIENTO IS NOT NULL AND CONVERT(DATE, I.FECHA_VENCIMIENTO) < T.HOY THEN 'VENCIDO'
             WHEN I.FECHA_INICIO IS NULL THEN 'SIN_FECHAS'
             WHEN CONVERT(DATE, I.FECHA_INICIO) > T.HOY THEN 'PENDIENTE'
             ELSE 'EN_CURSO' END AS ESTADO_CALC,
        CASE WHEN I.FECHA_CIERRE IS NULL AND I.FECHA_VENCIMIENTO IS NOT NULL AND CONVERT(DATE, I.FECHA_VENCIMIENTO) < T.HOY
             THEN DATEDIFF(DAY, CONVERT(DATE, I.FECHA_VENCIMIENTO), T.HOY) ELSE 0 END AS DIAS_ATRASO
    FROM dbo.VCT_PROYECTOS_PLAN_ITEMS I
    INNER JOIN (SELECT TOP 1 PL.ID FROM dbo.VCT_PROYECTOS_PLANES PL
                WHERE PL.ID_PROYECTO = @ID_PROYECTO ORDER BY PL.ID DESC) P ON P.ID = I.ID_PLAN
    CROSS APPLY (SELECT CONVERT(DATE, GETDATE()) AS HOY) T
    OUTER APPLY
    (
        SELECT COUNT(*) AS TOTAL,
               SUM(CASE WHEN E.CODIGO = 'CUMPLIDA' THEN 1 ELSE 0 END) AS CUMPLIDAS
        FROM dbo.VCT_GESTIONES GX
        INNER JOIN dbo.VCT_PRM_GESTIONES_ESTADOS E ON E.ID = GX.ID_ESTADO
        WHERE GX.ID_PLAN_ITEM = I.ID AND E.CODIGO <> 'CANCELADA'
    ) G
)
