 
CREATE FUNCTION [dbo].[FN_GET_AGENDA_DIA_CONSULTOR] (@IAGENDA INT, @IFECHA VARCHAR(50))
RETURNS VARCHAR(4000)
AS BEGIN
    DECLARE @VCONSULTORES		VARCHAR(400),
			@VCONSULTOR_DESC	VARCHAR(400),
			@VDATO				VARCHAR(4000),
			@lstDato			VARCHAR(100), 
			@lnuPosComa			INT
	
	SELECT	@VCONSULTORES = ISNULL(A.ID_CONSULTOR,'')
	FROM	LK_AGENDA A
	WHERE	ID_AGENDA = @IAGENDA
 
	IF (@VCONSULTORES <> '') BEGIN
 
		WHILE LEN(@VCONSULTORES) > 0
		BEGIN 
			SET @lnuPosComa = CHARINDEX('|', @VCONSULTORES) -- Busca el caracter a separador
			IF (@lnuPosComa = 0) BEGIN 
				SET @lstDato = @VCONSULTORES
				SET @VCONSULTORES = '' 
			END ELSE BEGIN
 
				SET @lstDato = SUBSTRING(@VCONSULTORES, 1, @lnuPosComa - 1)
 
				SELECT	@VCONSULTOR_DESC = APELLIDO_EMPLEADO + ', ' + NOMBRE_EMPLEADO
				FROM	LK_EMPLEADOS
				WHERE	CONVERT(VARCHAR,ID_EMPLEADO) = @lstDato
 
				SET @VDATO = ISNULL(@VDATO,'') +
							 CASE WHEN ISNULL([dbo].[FN_GET_AGENDA_HORAS_CONSULTOR] (@IAGENDA,@lstDato,@IFECHA),'0') <> '0' THEN	
							 '<li><span class="event">'+@VCONSULTOR_DESC+ '</span>
								  <span class="time"><b>('+CONVERT(VARCHAR,ISNULL([dbo].[FN_GET_AGENDA_HORAS_CONSULTOR] (@IAGENDA,@lstDato,@IFECHA),'0'))+')</b></span>
							 </li>' ELSE '' END
 
				SET @VCONSULTORES = SUBSTRING(@VCONSULTORES, @lnuPosComa + 1, LEN(@VCONSULTORES))
			END
		END
	END
 
	RETURN ISNULL(@VDATO,'')
 
END
