 
/* horas usadas para el KPI de la cabecera ("264 h") */
CREATE   FUNCTION dbo.VCT_PROYECTO_HORAS_USADAS_TXT (@ID_PROYECTO INT)
RETURNS VARCHAR(10)
AS
BEGIN
    DECLARE @H DECIMAL(12,2) = (SELECT SUM(HORAS_USADAS) FROM dbo.VCT_PROYECTO_VISITAS_CALC(@ID_PROYECTO));
    RETURN LEFT(dbo.VCT_FMT_HORAS(ISNULL(@H, 0)) + ' h', 10);
END
