 
CREATE FUNCTION [dbo].[FN_GET_AGENDA_CONSULTOR] (@IAGENDA INT, @IMENU VARCHAR(50))
RETURNS VARCHAR(8000)
AS BEGIN
    DECLARE @VCONSULTORES	VARCHAR(400),
			@VDESCCONS		VARCHAR(MAX),
			@lstDato		varchar(100), 
			@lnuPosComa		int ,
			@VALOR			VARCHAR(8000),
			@VLIDER			VARCHAR(50),
			@VINICIO		VARCHAR(50),
			@VFECHA_AGENDA	DATE,
			@VCANT			INT,
			@VHORAS			INT
 
	SET @VCANT = 0
	SET @VHORAS = 0
 
	SELECT	@VCONSULTORES = CASE WHEN (ISNULL(A.ID_CONSULTOR,'')='') THEN 
							'1' 
						  ELSE 
							A.ID_CONSULTOR
						  END,
			@VLIDER = ISNULL(SUBSTRING(LIDER,1,CHARINDEX('|',LIDER)-1),''),
			@VFECHA_AGENDA = ISNULL(FECHA,'')
	FROM	LK_AGENDA A
			--INNER JOIN LK_EMPLEADOS EMP ON A.ID_CONSULTOR = EMP.ID_EMPLEADO
	WHERE	ID_AGENDA = @IAGENDA
 
	IF (@VCONSULTORES <> '1') BEGIN
 
		WHILE LEN(@VCONSULTORES) > 0
		BEGIN 
			SET @lnuPosComa = CHARINDEX('|', @VCONSULTORES) -- Busca el caracter a separador
			IF (@lnuPosComa = 0) BEGIN 
				SET @lstDato = @VCONSULTORES
				SET @VCONSULTORES = '' 
			END ELSE BEGIN
 
				SET @lstDato = SUBSTRING(@VCONSULTORES, 1, @lnuPosComa - 1)
 
				SELECT	@VHORAS = NULLIF(ISNULL(SUM(HORAS),'0'),'0')
				FROM	LK_AGENDA_EMPLEADO
				WHERE	ID_EMPLEADO = @lstDato
				AND		HOLIDAYTEXT = CONVERT(VARCHAR,@IAGENDA)
 
				SELECT	@VALOR = CASE WHEN @IMENU = 'M' THEN 
										CASE WHEN @VLIDER = @lstDato THEN
											'<span style="font-size:11px;color:red;text-align:left" title="Lider">'+APELLIDO_EMPLEADO + ', ' + NOMBRE_EMPLEADO +' - ('+CONVERT(VARCHAR,@VHORAS)+')</span>'
										ELSE
											'<span style="font-size:11px;color:black;text-align:left" title="Consultor">'+APELLIDO_EMPLEADO + ', ' + NOMBRE_EMPLEADO +' - ('+CONVERT(VARCHAR,@VHORAS)+')</span>'
										END
								 ELSE 
									APELLIDO_EMPLEADO + ', ' + NOMBRE_EMPLEADO
								 END
				FROM	LK_EMPLEADOS
				WHERE	CONVERT(VARCHAR,ID_EMPLEADO) = @lstDato
 
				IF (@IMENU = 'M')  
					SET @VDESCCONS = ISNULL(@VDESCCONS,'') + @VALOR + char(10) 
				IF (@IMENU = 'A')
					SET @VDESCCONS = ISNULL(@VDESCCONS,'') + @VALOR + ' - '
 
				SET @VCONSULTORES = SUBSTRING(@VCONSULTORES, @lnuPosComa + 1, LEN(@VCONSULTORES))
			END
		END
	END
 
    RETURN CASE WHEN @IMENU = 'A' THEN ISNULL(SUBSTRING(@VDESCCONS,1,LEN(@VDESCCONS)-1),'1') WHEN @IMENU = 'M' THEN ISNULL(@VDESCCONS,'1') END
END
