CREATE FUNCTION [dbo].[FN_GET_EXISTE] (@ISTRING VARCHAR(MAX), @IVALOR VARCHAR(400))
RETURNS VARCHAR(50)
AS BEGIN
    DECLARE @VSTRING	VARCHAR(MAX),
			@VALOR		VARCHAR(400),
			@RESULTADO	INT,
			@N			INT,
			@VEXISTE	VARCHAR(50)
 
	SET	@VSTRING = ISNULL(@ISTRING,'')
 
	SET @N = 0
			
	WHILE PATINDEX('%|%',@VSTRING)>0
	BEGIN
		SET @RESULTADO = PATINDEX('%|%',@VSTRING) --+ @N
		SET  @VALOR = SUBSTRING(@VSTRING,1, @RESULTADO-1)
						
			IF (@VALOR = CONVERT(VARCHAR,@IVALOR)) BEGIN
				SET  @VEXISTE = 'SI'
			END
 
		SELECT @VSTRING = RIGHT(@VSTRING,LEN(@VSTRING)-PATINDEX('%|%',@VSTRING))
	END
 
	RETURN ISNULL(@VEXISTE,'NO')
 
END
