 
CREATE FUNCTION [dbo].[FN_GET_SERVICIO_CONSULTORES] (@ICLIENTE INT, @IPROYECTO INT, @ISERVICIO INT, @IPROYECTOSERV INT)
RETURNS VARCHAR(MAX)
AS BEGIN
    DECLARE @VCONSULTORES	VARCHAR(400),
			@VDESCCONS		VARCHAR(MAX),
			@lstDato		varchar(100), 
			@lnuPosComa		int ,
			@VALOR			VARCHAR(8000),
			@VTODOS			VARCHAR(8000)
 
	DECLARE Consultores CURSOR FOR 
		SELECT	ID_CONSULTOR
		FROM	LK_AGENDA
		WHERE	ID_CLIENTE = @ICLIENTE
		AND		ID_PROYECTO = @IPROYECTO
		AND		ID_SERVICIO = @ISERVICIO
		AND		PROYECTO_SERV_ID = @IPROYECTOSERV
			
	OPEN Consultores  
	FETCH NEXT FROM Consultores INTO @VCONSULTORES
 
	WHILE @@FETCH_STATUS = 0  
	BEGIN  
		
		SET @VTODOS = ISNULL(@VTODOS,'') + @VCONSULTORES
 
					
		FETCH NEXT FROM Consultores INTO @VCONSULTORES
	END 
 
	CLOSE Consultores  
	DEALLOCATE Consultores
 
	WHILE LEN(@VTODOS) > 0
	BEGIN 
		SET @lnuPosComa = CHARINDEX('|', @VTODOS) -- Busca el caracter a separador
		IF (@lnuPosComa = 0) BEGIN 
			SET @lstDato = @VTODOS
			SET @VTODOS = '' 
		END ELSE BEGIN
			SET @lstDato = SUBSTRING(@VTODOS, 1, @lnuPosComa - 1)
 
			SELECT	@VALOR = '<font style="font-family:Tahoma, Arial, Helvetica, sans-serif;font-size:10px;color:black;text-align: left">'+APELLIDO_EMPLEADO + ', ' + NOMBRE_EMPLEADO +'</font>'
			FROM	LK_EMPLEADOS
			WHERE	CONVERT(VARCHAR,ID_EMPLEADO) = @lstDato
 
			SET @VDESCCONS = CASE WHEN (CHARINDEX(@VALOR, ISNULL(@VDESCCONS,'')) = 0) THEN ISNULL(@VDESCCONS,'') + @VALOR + '</br>' ELSE ISNULL(@VDESCCONS,'') END
 
			SET @VTODOS = SUBSTRING(@VTODOS, @lnuPosComa + 1, LEN(@VTODOS))
		END
	END
	
    RETURN ISNULL(SUBSTRING(@VDESCCONS,1,LEN(@VDESCCONS)-1),'1')
 
END
